### ISSUE TITLE
Instant Preview cannot connect over WiFi

### ISSUE THREAD

**Issue by ccrutchf** [googlevr/gvr-unity-sdk#1001]
### SPECIFIC ISSUE ENCOUNTERED
Cannot connect Daydream Instant Preview to Unity running on Windows 10 x64 1809 via WiFi.  There appears to be an issue querying the network SSID.

![image](https://user-images.githubusercontent.com/25113015/51509939-d4e88000-1daf-11e9-820b-2a8ab8935975.png)

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2018.3.2f1
- Google VR SDK for Unity: 1.190.1
- Device manufacturer, model, and O/S: Google Pixel 2 XL, Android 9.PQ1A.190105.004
- Device fingerprint: google/taimen/taimen:9/PQ1A.190105.004/5148680:user/release-keys
- Device display metrics: 
mBaseDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1440  x 2880, real 1440 x 2880, largest app 1440 x 2880, smallest app 1440 x 2880, mo de 1, defaultMode 1, modes [{id=1, width=1440, height=2880, fps=60.000004}], col orMode 0, supportedColorModes [0, 7, 9], hdrCapabilities android.view.Display$Hd rCapabilities@413e3a39, rotation 0, density 560 (537.882 x 537.882) dpi, layerSt ack 0, appVsyncOff 2000000, presDeadline 11666666, type BUILT_IN, state ON, FLAG _SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, removeMode 0}
- Google VR Services:
Packages:
    versionName=1.19.219215888
Hidden system packages:
    versionName=1.15.195746028
- Viewer manufacturer & model: Google Daydream View G014A

### Additional Comments
Daydream Instant Preview also will not connect via USB.  I can connect adb both over USB and over WiFi.  When connected to USB, Unity will launch Instant Preview, but then it indicates that it is "Not connected to editor".

**Comment by ddrocco** [comment]
Hi, thanks for reporting.  We'll take a look.

**Comment by ddrocco** [comment]
This looks like it could be related to https://github.com/googlevr/gvr-unity-sdk/issues/1002.  If it is the same bug, the steps listed there should be a reasonable workaround until we can get a fix out.

**Comment by ccrutchf** [comment]
I was able to confirm that I can connect over USB after disabling Hyper-V.  I still cannot connect over WiFi.  for my purposes, I'm satisfied with this, and am comfortable with the issue being closed if you want to track it at #1002.
