### ISSUE TITLE
Cardboard Unity sdk cant stop tracking on Android

### ISSUE THREAD

**Issue by zbzdys** [googlevr/gvr-unity-sdk#1005]
I cant find the answer for my "stop tracking on Android" so i post a issue here try to get your official response.

I have the latest googlevr cardboard sdk for unity and i have finished most of the work. The problem is the hardware test found that the gyro is always running even though turning off the screen. The mobile phone is Huawei P10 which running on Android 8.1 and the gyro costs 150mA even though the cardboard app is suspended.

I noticed that on ios or android ndk, you can use the api of pause or resuming tracking but i did not find that api at the unity sdk. So what i did try to solve the problem? i tried to switch to none vr mode if the app lose focus but no help.

Is gyro used by google vr still working(tracking) when the app is suspended(lose focus)?

I want to get some help for controlling tracking on Android platform. if its a specific problem of different hardward or i did something wrong, please correct me. Thank you.

**Comment by rusmaxham** [comment]
GoogleVR disconnects from the motion sensors subsystem when the app is suspended.  If it is continuing to run, it may be some system issue where these systems don't shut down immediately.

Do you notice any difference in power drain if you kill the cardboard app, not just suspend it?

**Comment by zbzdys** [comment]
I have solved the problem and it was my fault. I use gyro enabled but unity does not suspend this "Rotation Vector Sensor" when loses focus. After adding my disable gyro when losing focus, the sensors can be closed correctly. Sorry to disrupt, now close this issue please.

**Comment by zbzdys** [comment]
My blog about this problem is https://blog.csdn.net/u012911347/article/details/87878270
