### ISSUE TITLE
Cannot disable Vsync in native Unity Cardboard SDK

### ISSUE THREAD

**Issue by Kjos** [googlevr/gvr-unity-sdk#1006]
### SPECIFIC ISSUE ENCOUNTERED
I cannot disable the VSync in the Unity Cardboard SDK. I'm just falling short of 60 fps when my phone heats up, using an extremely simple scene. I notice in the profiler that sometimes WaitForGPU takes 18ms! Since I take it there is not timewarping of any kind, why not just disable VSync? It beats going to 30fps?

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2018.2
- Google VR SDK for Unity: Native Unity embedded
- Device manufacturer, model, and O/S: Android 7, Chinese phone with MediaTek
- Device fingerprint:
  Use `adb shell getprop ro.build.fingerprint`
- Device display metrics:
  Output of `adb shell dumpsys display | grep mBaseDisplayInfo`
- Google VR Services:
  On Windows, use: `adb shell pm dump com.google.vr.vrcore | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.vr.vrcore | egrep -i versionName\|packages:`
- Viewer manufacturer & model:
- Link to Unity project that reproduces the issue:

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by rusmaxham** [comment]
It is not possible to disable VSYNC with GoogleVR.  GoogleVR handles final presentation to the screen and due to VR systems to maximize comfort and minimize latency, VSYNC must remain locked.

If you are seeing blocking in `WaitForGPU`, you are very likely GPU bound.  This could be due to heavyweight shaders or extensive use of transparency.

**Comment by Kjos** [comment]
I'm not using any shaders or transparency. It's a scene with just one object. However there are some processes running in a (GPU based) tracking app in the background, so yes, it's probably GPU bound.
I've removed the Cardboard & VR implementation since my previous post, and now have disabled vsync. I have to say this is much better, so I still don't quite understand why you guys don't allow for it to be disabled (or maybe it's up to Unity). 
Also the 16.6+ ms frametime measurements tells me the Unity VR implementation sometimes overshoots the estimation for the frame end, which might be because phones tend to throttle aggressively and perhaps inconsistently. 
Anyway, it's not a concern for me anymore now that I don't use the Unity VR feature anymore. I now rely on my own tracking and am going to use a vertex warping shader instead (which will also lower overhead and suits my application better).

**Comment by rusmaxham** [comment]
Rendering to VR is a two pass rendering process.  Unity renders each eye to an undistorted render buffer.  Then it hands this buffer off to the GVR renderer which does the distortion rendering pass and can do async reprojection and scanline racing to account for head movement between beginning of frame and end of frame.  This last process is always locked to VSYNC.  To unlock it would defeat the timing of these headpose adjustments and cause discomfort in VR.

**Comment by Kjos** [comment]
Ah, I wasn't sure GVR did that too (reprojection). From my results it fell back to 30FPS a lot, and I figure that was for the second pass, as there was a lot of noticeable low framerate stuttering and I didn't notice the reprojection kicking in. My application ran at 60fps at start and dipped to 50fps due to thermal throttling. I hadn't had an issue when the frametime was solid below 16ms though with GVR. Anyway, thanks for answering and I'm on my way again.
