### ISSUE TITLE
64-bit Support Missing gvrshim.so

### ISSUE THREAD

**Issue by pokelege** [googlevr/gvr-unity-sdk#1008]
### SPECIFIC ISSUE ENCOUNTERED
When building an APK in IL2CPP and only 64-bit, the scene runs, but the controller doesn't appear. Console log shows that a script is trying to access gvrshim. I checked the gvr.aar archive and gvrshim.so is missing in the arm64-v8a folder.

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2018.3.3f1
- Google VR SDK for Unity: 1.190.1
- Device manufacturer, model, and O/S: Google Pixel 3/2 XL and Lenovo Mirage Solo

### STEPS TO REPRODUCE THE ISSUE
 1. Get the latest Google VR SDK.
 2. Create a scene with a headset and controller.
 3. Change Scripting Backend to IL2CPP and set the Target Architectures to ONLY ARM64.
 4. Build and run.
 5. Notice that scene shows, but no controller is showing up.

### ADDITIONAL COMMENTS
The reason on making a 64-bit only build is that we have a plugin that is dependent on 64-bit.

**Comment by rusmaxham** [comment]
Android 64 bit build support will be available in the next release, due in March.

**Comment by pokelege** [comment]
Thank you, will check back around March.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
