### ISSUE TITLE
Not able to build the C++ video plugin

### ISSUE THREAD

**Issue by dmvictor** [googlevr/gvr-unity-sdk#1009]
The C++ [video plugin](https://github.com/googlevr/gvr-unity-sdk/tree/master/native_libs/video_plugin) in the SDK use the [gradle experimental plugin](http://tools.android.com/tech-docs/new-build-system/gradle-experimental), which is not supported with the current release of Android Studio. When I made the C++ module "video_plugin", Android Studio had no response with no error message. I could not find the built shared library as well. My Android studio version is 3.2.1, and ndk version is r18b. According to the [README.md](https://github.com/googlesamples/android-ndk/blob/master/README.md) in Google ndk samples repository, I downgraded my Android studio and ndk version to 2.3.3 and r10e respectively. Under this setting, I could build [hello-jni](https://github.com/googlesamples/android-ndk/tree/gradle-experimental/hello-jni) and [hello-libs](https://github.com/googlesamples/android-ndk/tree/gradle-experimental/hello-libs) sample successfully. Since the gradle experimental plugin is going to be deprecated, will this video plugin be updated with cmake plugin or ndk-build as @ggfan [suggested](https://github.com/googlesamples/android-ndk/issues/554#issuecomment-464487297)? Thank you!

**Comment by rusmaxham** [comment]
we're working on a fix.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
