### ISSUE TITLE
DllNotFoundException: instant_preview_unity_plugin

### ISSUE THREAD

**Issue by panchoruy** [googlevr/gvr-unity-sdk#1011]
### SPECIFIC ISSUE ENCOUNTERED
Upon attempting to run the HelloVR demo per the instructions here https://developers.google.com/vr/develop/unity/instant-preview, I get the errors:
```
DllNotFoundException: instant_preview_unity_plugin
InstantPreviewHelper.Awake () (at Assets/GoogleVR/Scripts/InstantPreview/InstantPreviewHelper.cs:96)

DllNotFoundException: instant_preview_unity_plugin
Gvr.Internal.InstantPreview.Awake () (at Assets/GoogleVR/Scripts/InstantPreview/Internal/InstantPreview.cs:257)
```
It's noteworthy that I do not see in the console "Google VR SDK for Unity Version: 1.xx and Instant Preview Version: 1.0.0.x (where x is replaced by a version number)" per the troubleshooting guide.

### HARDWARE/SOFTWARE VERSIONS
Running Unity 2018.3.5f1 on Ubuntu 18.04.2 LTS.
GVR SDK for Unity v1.190.1 Android SDK Platform 28

### STEPS TO REPRODUCE THE ISSUE
Installed Latest Version of Unity and follow the instructions here: https://developers.google.com/vr/develop/unity/get-started-android
https://developers.google.com/vr/develop/unity/instant-preview

I would really appreciate some input on the issue

**Comment by ddrocco** [comment]
Instant Preview unfortunately only runs on Windows and Mac.  We don't currently have plans to support a Linux plugin for that feature.

**Comment by panchoruy** [comment]
@ddrocco Alright! Thank you for your fast response.

**Comment by lunarcloud** [comment]
Could you at least make it so the existence of the Instant Preview gives a warning about not supporting Linux instead of throwing an error?
