### ISSUE TITLE
Magic window on galaxy s6 is very inaccurate

### ISSUE THREAD

**Issue by whizzkid** [googlevr/gvr-unity-sdk#1016]
I've tried using the magic window script for a mono-view of my gvr app.
https://developers.google.com/vr/develop/unity/guides/magic-window

But the results are pretty awful on a samsung galaxy s6
When using stereoscopic rendering in gvr, everything works perfectly. but when I use the magic-window code, my camera sorta works, but the camera wobbles around. and seems to be nudged around every now and again.
(this does not happen on a galaxy s7, and this does not happen on my s6 when in stereo mode)

Why can't we just switch the rendering to stereo or mono, while still using the head tracking that GVR uses in stereo mode?

regards,

**Comment by rusmaxham** [comment]
Unfortunately, GVR's use of a device's motion sensors is tied to VR mode and not separable.
