### ISSUE TITLE
Performing CV on top of See Through Camera feed on Mirage Solo.

### ISSUE THREAD

**Issue by 12xq4** [googlevr/gvr-unity-sdk#1020]
Hello, and apologies in advance if this issue has been answered in the past. I'm working on a urgent project which requires me to perform some CV features on the See Through Camera data feed. I think I have read from somewhere that details how this feature is not accessible from Unity. Is there anyway I could access see through camera feed, either through ndk or some other forms of interface (that then I can expose to Unity)?

Thanks.

**Comment by rusmaxham** [comment]
Please see the discussion in [issue 988](https://github.com/googlevr/gvr-unity-sdk/issues/988).
