### ISSUE TITLE
Supported device for see through

### ISSUE THREAD

**Issue by Zumbalamambo** [googlevr/gvr-unity-sdk#1021]
### SPECIFIC ISSUE ENCOUNTERED

I'm trying to run HelloMr example. However it says that the "See through is not supported on this system"

### HARDWARE/SOFTWARE VERSIONS
- Unity version:  2018.3.5
- Google VR SDK for Unity: 1.20
- Device manufacturer, model, and O/S: Xiaomi 8

### ADDITIONAL COMMENTS

Is there any ways to see overcome this issue?

**Comment by rusmaxham** [comment]
See-through mode is only supported on the Lenovo Mirage Solo.
