### ISSUE TITLE
Exoplayer Audio data 

### ISSUE THREAD

**Issue by user32768** [googlevr/gvr-unity-sdk#1022]
I want the L&R audio data that currently goes direct to the hardware to be available for post processing for spatialisation instead.
We've got a virtual cinema but the sound is headlocked, we can't make it come from anywhere else, as we have no access to the audio data.

### SPECIFIC ISSUE ENCOUNTERED
No spatialisation on audio from exoplayer. 
No audio stream available from exoplayer to do any processing on.
All playback is headlocked stereo which is far from ideal in VR.

### HARDWARE/SOFTWARE VERSIONS
Unity3D 2014.22f1, Any GVR version.

### STEPS TO REPRODUCE THE ISSUE
none

### WORKAROUNDS (IF ANY)
none

### ADDITIONAL COMMENTS
I'd like if we could just enable current streaming audio data to be delivered as an event that we can then push through Unity AudioSources which can then be physically placed inthe virtual world.
The latest Video sample for Unity3D does nothing with the audio except set the volume .

**Comment by rusmaxham** [comment]
There currently is no support for piping audio from the Exoplayer instance in GvrVideoPlayerTexture into Unity's audio pipeline and no plans to do so given the complexities of this integration.  I suggest you look into some other video player solution for Unity.
