### ISSUE TITLE
Align FOV

### ISSUE THREAD

**Issue by Zumbalamambo** [googlevr/gvr-unity-sdk#1029]
### SPECIFIC ISSUE ENCOUNTERED
Detected plane and object moves together with the camera.

### HARDWARE/SOFTWARE VERSIONS
- Unity:2018.3.5
- Google VR SDK for Unity: 1.20
- Device manufacturer, model, and O/S: Xiaomi 8

### ADDITIONAL COMMENTS

The detected plane moves together with the camera while using ARCore. It's due to the misaligned FOV of VR and ARCore. Is there any way to align the field of view of Google VR to be the same as that of the ARCore?

**Comment by rusmaxham** [comment]
We do not currently support concurrent use of GVR and ARCore.

**Comment by Zumbalamambo** [comment]
@rusmaxham could we expect this in any upcoming release?

**Comment by rusmaxham** [comment]
We have no timeline for supporting this use case at this time.
