### ISSUE TITLE
Is there a way to disable the system from using the bluetooth controller?

### ISSUE THREAD

**Issue by KJon** [googlevr/gvr-unity-sdk#1036]
### SPECIFIC ISSUE ENCOUNTERED
Currently I have an Android app that connects to a bluetooth heart rate monitor but when I enable VR in Unity the app would not be able to detect the heart rate monitor anymore. I suspect it might be due to gvr trying to connect to a bluetooth controller instead which might be conflicting with the plugin I am using to connect to the heart rate monitor.
Is there a way to disable gvr from using bluetooth by setting an environment symbol or something?

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2018.3.12f1
- Google VR SDK for Unity:
- Device manufacturer, model, and O/S: Google Pixel 3xl

**Comment by rusmaxham** [comment]
There is no way to disable the Daydream controller in Daydream apps running on Daydream-ready devices.  You could try removing Daydream from your VR SDKs in Unity's XR Settings and add Cardboard.  That will not require or even attempt to connect to the Daydream controller.

**Comment by KJon** [comment]
Currently the problem happens when I am using Google cardboard in my Unity XR settings. 

Interestingly, when a colleague tried the app it works fine without any conflict but the problem persists on my device so I'm thinking this might be a hardware compatibility issue? The problem happens on a Google Pixel 3xl device
