### ISSUE TITLE
Duplicated definitions

### ISSUE THREAD

**Issue by daserge** [googlevr/gvr-unity-sdk#1039]
### SPECIFIC ISSUE ENCOUNTERED
There's a lot of duplicated definitions in the latest release causing compilation errors, f.e.:
https://github.com/googlevr/gvr-unity-sdk/commit/4f53096386d40326c9d732879b6b1620c4a1e485#diff-d33b840fd917e2aacec440f1b6323ed5R22
https://github.com/googlevr/gvr-unity-sdk/blob/4f53096386d40326c9d732879b6b1620c4a1e485/Assets/GoogleVR/Scripts/EventSystem/IGvrPointerHoverHandler.cs#L22

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2019.1.0f2, 2018.3.8f1
- Google VR SDK for Unity:
- Device manufacturer, model, and O/S:
- Device fingerprint:
  Use `adb shell getprop ro.build.fingerprint`
- Device display metrics:
  Output of `adb shell dumpsys display | grep mBaseDisplayInfo`
- Google VR Services:
  On Windows, use: `adb shell pm dump com.google.vr.vrcore | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.vr.vrcore | egrep -i versionName\|packages:`
- Viewer manufacturer & model:
- Link to Unity project that reproduces the issue:

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by daserge** [comment]
@rusmaxham Hello! Is there any workaround to this issue?
Thanks

**Comment by MaggleMitch** [comment]
I am also having this issue!

**Comment by rusmaxham** [comment]
What duplicated definitions?  Can you copy the errors from the Unity console?

**Comment by daserge** [comment]
OK, so the issue was solved after I've created a blank project, imported the plugin to it and then compared the existing proj with it. Turned out Unity placed some dupes on "upgrade" probably because there were some meta files left over.
