### ISSUE TITLE
GvrShimUnity_getControllerConnectionStatus returned error during GoogleVR SDK Upgrade on existing project

### ISSUE THREAD

**Issue by adammpkins** [googlevr/gvr-unity-sdk#1045]
### SPECIFIC ISSUE ENCOUNTERED
App fails with latest version of unity editor with 

> E/Unity: GvrShimUnity_getControllerConnectionStatus returned error.
>     Gvr.Internal.AndroidNativeShimControllerProvider:ReadState(ControllerState, Int32)
>     GvrControllerInputDevice:Update()
>     GvrControllerInput:Update()
>      
>     (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Repeating in the logs

### HARDWARE/SOFTWARE VERSIONS
- Unity:2019.1.12f1
- Google VR SDK for Unity: v1.200.1
- Device manufacturer, model, and O/S: Samsung Galaxy S8+
- Device fingerprint: samsung/dream2qltesq/dream2qltesq:9/PPR1.180610.011/G955USQS6DSG4:user/release-keys
- Device display metrics:
   mBaseDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1440 x 2960, real 1440 x 2960, largest app 1440 x 2960, smallest app 1440 x 2960, mode 1, defaultMode 1, modes [{id=1, width=1440, height=2960, fps=60.000004}, {id=2, width=1080, height=222
0, fps=60.000004}, {id=3, width=720, height=1480, fps=60.000004}], colorMode 0, supportedColorModes [0], hdrCapabilities android.view.Display$HdrCapabilities@821b95f5, rotation 0, density 560 (522.514 x 525.762) dpi, layerStack 0, appVsyncOff 1000000, presDeadline
16666666, type BUILT_IN, state DOZE_SUSPEND, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, removeMode 0}
    mOverrideDisplayInfo=DisplayInfo{"Built-in Screen", uniqueId "local:0", app 1080 x 2094, real 1080 x 2220, largest app 2094 x 2031, smallest app 1080 x 1017, mode 1, defaultMode 1, modes [{id=1, width=1440, height=2960, fps=60.000004}, {id=2, width=1080, height
=2220, fps=60.000004}, {id=3, width=720, height=1480, fps=60.000004}], colorMode 0, supportedColorModes [0], hdrCapabilities android.view.Display$HdrCapabilities@821b95f5, rotation 0, density 420 (391.8855 x 394.32153) dpi, layerStack 0, appVsyncOff 1000000, presDe
adline 16666666, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, removeMode 0}

- Google VR Services:
Packages:
    versionName=1.20.235017259
Hidden system packages:
    versionName=1.15.196855678
- Viewer manufacturer & model:
- Link to Unity project that reproduces the issue:

### STEPS TO REPRODUCE THE ISSUE

1. Remove old SDK plugin directory from Assets 
2. Re-import the new googlevr SDK asset
3. Toggle XRSettings.enabled = true
4. Application shows a single view with a reticle which would not respond to movements
5. Receive "GvrShimUnity_getControllerConnectionStatus returned error." throughout logcat

**Comment by adammpkins** [comment]
Resolved by the inclusion of the GoogleVR package in the Package Manager. For other users confused by this (because it's not in the documentation, quickstart or otherwise), you must include the GoogleVR package in the Package Manager IN ADDITION to the asset package you download from the releases page. It's not one or the other. The asset package will not function without the package manager package.

**Comment by rusmaxham** [comment]
There is a Unity issue where the GoogleVR Package Manager package is not automatically included when upgrading a Daydream project.  Disabling and re-enabling VR Support will automatically add the required Package Manager dependencies.
