### ISSUE TITLE
Not working for LWRP (only left eye rendered)

### ISSUE THREAD

**Issue by TonGarcia** [googlevr/gvr-unity-sdk#1050]
### SPECIFIC ISSUE ENCOUNTERED
It works correctly for default render, but not for HDRP nor LWRP (Lightweight Render Pipeline).

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2019.2.0f1
- Google VR SDK for Unity: GoogleVRForUnity_1.200.1
- Device manufacturer, model, and O/S: Moto Z Play 2, Android 8,0,0
- Device fingerprint: motorola/albus/albus:8.0.0/OPSS27.76-12-25-23/22:user/release-keys
- Device display metrics: mBaseDisplayInfo=DisplayInfo{"Tela integrada", uniqueId "local:0", app 1080 x 1920, real 1080 x 1920, largest app 1080 x 1920, smallest app 1080 x 1920, mode 1, defaultMode 1, modes [{id=1, width=1080, height=1920, fps=60.000004}], colorMode 0, supportedColorModes [0, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], hdrCapabilities android.view.Display$HdrCapabilities@1d6308, rotation 0, density 480 (403.411 x 403.041) dpi, layerStack 0, appVsyncOff 1000000, presDeadline 16666666, type BUILT_IN, state ON, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, removeMode 0}
- Google VR Services:  find str command not found & mac version returns nothing

### STEPS TO REPRODUCE THE ISSUE
 1. Create default starter LWRP Unity project
 1. Add GVR demo or GVR emulator + camera with raycast pointer
 1. Run on android

### WORKAROUNDS (IF ANY)
If use default render pipeline it works

### ADDITIONAL COMMENTS
It renders only the left eye, and it render correctly, but the right eye is black, All functionalities works for the unique rendered eye.

**Comment by paulgnz** [comment]
Can confirm this issue on iOS also, see my thread on Unity forum https://forum.unity.com/threads/google-vr-unity-2019-2-1-lwrp-only-showing-left-eye-right-eye-blank.735389/

**Comment by tertle** [comment]
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.0/manual/universalrp-builtin-feature-comparison.html

Cardboard is not listed as being supported yet, only in research.

**Comment by TonGarcia** [comment]
@tertle there is any "workaround"/alternative?

**Comment by paulgnz** [comment]
> @tertle there is any "workaround"/alternative?

Yes, change setting in XR Settings to Single Pass !
