### ISSUE TITLE
Can it work for Gear VR?

### ISSUE THREAD

**Issue by savek1986** [googlevr/gvr-unity-sdk#1053]
### HARDWARE/SOFTWARE VERSIONS
- Unity:
- Google VR SDK for Unity:
- Device manufacturer, model, and O/S:
- Device fingerprint:
  Use `adb shell getprop ro.build.fingerprint`
- Device display metrics:
  Output of `adb shell dumpsys display | grep mBaseDisplayInfo`
- Google VR Services:
  On Windows, use: `adb shell pm dump com.google.vr.vrcore | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.vr.vrcore | egrep -i versionName\|packages:`
- Viewer manufacturer & model:
- Link to Unity project that reproduces the issue:

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by rusmaxham** [comment]
No, the GoogleVR SDK does not support GearVR.
