### ISSUE TITLE
HLS live 360 playback is distorted on Oculus Go

### ISSUE THREAD

**Issue by sparanja** [googlevr/gvr-unity-sdk#1057]
### I was trying to live stream 360 video from a HLS playback URL, but the video is all distorted and it can be seen only with one eye(still very distorted). I used the GVR Video Player to stream the HLS URL by following this tutorial -->
https://developers.google.com/vr/develop/unity/video-overview

I tried streaming Dash format URL and it works like a charm, but it does not seem to render the 360 video correctly when i put in the HLS format URL. Has anyone faced this issue?? Please help me out here.

Thanks

### HARDWARE/SOFTWARE VERSIONS
- Unity: Unity 2019.1.4f2
- Google VR SDK for Unity: GVR SDK for Unity v1.200.1
- Oculus, Go, and Android 7.1 Nougat:
- Device fingerprint:
oculus/vr_pacific/pacific:7.1.1/NGI77B/358570.6130.0:user/release-keys

Link to the Unity project. Just replace the URL to any test HLS stream available online
https://github.com/sparanja/VR-360-Player

### STEPS TO REPRODUCE THE ISSUE
 1. Just replace the URL to any test HLS stream available online under the Sphere's video player settings
 2. Build for Android with VR support enabled for Oculus Go 
 3. Deploy App on the Device and run it.

**Comment by rusmaxham** [comment]
This repo is for the GoogleVR SDK which does not support Oculus hardware.

**Comment by sparanja** [comment]
Is there any way to make it compatible with the Oculus Go since essentially it is an Android device? i looked at the code and figured there must be some issue with the UpdateMaterial() function because the HLS stream is decoded correctly since i can see the content of the stream. Only concern is that the video is distorted and i believe it can be fixed in the rendereing phase. Could you please let me know what could be the issue in rendering on the Oculus device?
