### ISSUE TITLE
Arrow on iphone

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/gvr-unity-sdk#1067]
Hello,
We can not post our appllication bcause of the arrow in left corner. How to disable this arrow or to make it work  ?
We use unity3d 2018.3.6f1 and GVR SDK for Unity v1.200.0
![28E15206-759A-49D3-AF68-07E3FB44A25B](https://user-images.githubusercontent.com/55288472/67624560-94d09500-f83a-11e9-988c-688e0957e2b5.jpg)

**Comment by andrewio** [comment]
Why? App Store Moderation?

**Comment by MusemoDeveloper** [comment]
I do not know, this arow just does nothing, i want to remove it or to add some machanics. How to do that?

**Comment by andrewio** [comment]
> I do not know, this arow just does nothing, i want to remove it or to add some machanics. How to do that?

Go To Menu Scene or Quit the App: 
https://stackoverflow.com/questions/41968789/google-cardboard-unity-back-close-button

**Comment by MusemoDeveloper** [comment]
Thanks, it works
