### ISSUE TITLE
Twitchy head tracking on HTC One m7

### ISSUE THREAD

**Issue by handyface** [googlevr/gvr-unity-sdk#107]
Using SDK 0.5.2 and Unity 5.2.1f1, the HTC ONE M7 has very obvious twitching in the head tracking. My S6 and several other phones don't have this problem.

When I open an app I made previously on 5.1.2f1 & SDK 5.0, the head tracking seems to work correctly. I tried disabling distortion correction, and the drift correction, but that doesn't deem to work.

I got the chance to test the same app on a different M7, and the issue seems to consistently happen on all M7 phones I tested. Here's a video showing the problem.

https://drive.google.com/open?id=0B5XLOVf_JxT4b2FPSFpmdTZ3WkE

**Comment by smdol** [comment]
This looks like the head orientation is being continuously reset to the starting direction.

**Comment by handyface** [comment]
Yes, it constantly twitches back to the first position.

**Comment by Forux** [comment]
I have the same problem with unity 5.2.2f1 + SDK 0.52 on LG G3.

And when i use webvr or https://github.com/JScott/cardboard-controls/releases/tag/v3.2 - i have no such problem.

How this can be solved?

**Comment by smdol** [comment]
Doed it look the same as handyface's sample video, where it looks like the head tracking is resetting to zero frequently?

**Comment by frizzorossi** [comment]
I had the same issue. I know I could sound like IT Crowd shows... but restarting the phone the issue has disappeared :)

**Comment by handyface** [comment]
Yes, the issue sometimes disappears, especially after reboot. But still the problem seems to come back regularly.

**Comment by chaosemer** [comment]
Closing this due to its age. Please reopen if this is still an issue.
