### ISSUE TITLE
SDK 0.6 | Unity 5.3.1 | Application.Quit() crashes app

### ISSUE THREAD

**Issue by MiCkSoftware** [googlevr/gvr-unity-sdk#147]
I can't tell if it's related to 0.6 update or spatialized audio but now my came crashes on exit.
Any idea?

01-20 13:36:22.074 25908 25924 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9eb53050 in tid 25924 (UnityMain)
01-20 13:36:22.178   468   468 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-20 13:36:22.178   468   468 F DEBUG   : Build fingerprint: 'motorola/victara_reteu/victara:6.0/MPE24.49-18/19:user/release-keys'
01-20 13:36:22.178   468   468 F DEBUG   : Revision: 'p2bf'
01-20 13:36:22.178   468   468 F DEBUG   : ABI: 'arm'
01-20 13:36:22.178   468   468 F DEBUG   : pid: 25908, tid: 25924, name: UnityMain  >>> com.mick.we.ep0 <<<
01-20 13:36:22.178   468   468 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9eb53050
01-20 13:36:22.179   471  1119 W APM::EffectDescriptor: unregisterEffect() unknown effect ID 206
01-20 13:36:22.203   468   468 F DEBUG   :     r0 9eb53050  r1 9eb54000  r2 fffffe8c  r3 9eb54000
01-20 13:36:22.203   468   468 F DEBUG   :     r4 9eb53050  r5 00000001  r6 9eb53ffc  r7 af5b6000
01-20 13:36:22.203   468   468 F DEBUG   :     r8 9c67c9e0  r9 00000000  sl a24847ec  fp a248436c
01-20 13:36:22.203   468   468 F DEBUG   :     ip af988ed8  sp a2484340  lr af8a9d7c  pc af8a9cec  cpsr 80070010
01-20 13:36:22.214   468   468 F DEBUG   :
01-20 13:36:22.214   468   468 F DEBUG   : backtrace:
01-20 13:36:22.214   468   468 F DEBUG   :     #00 pc 002b2cec  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.214   468   468 F DEBUG   :     #01 pc 002b2d78  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so (GC_push_all_stack+72)
01-20 13:36:22.214   468   468 F DEBUG   :     #02 pc 002bb9fc  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #03 pc 002bbacc  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #04 pc 002b7840  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #05 pc 002b4834  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #06 pc 002b1128  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #07 pc 002ab1fc  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #08 pc 002aace0  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #09 pc 002abaa4  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #10 pc 002abb44  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.215   468   468 F DEBUG   :     #11 pc 001396d8  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so (mono_gc_collect+40)
01-20 13:36:22.215   468   468 F DEBUG   :     #12 pc 001717b0  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so (mono_domain_finalize+96)
01-20 13:36:22.215   468   468 F DEBUG   :     #13 pc 00024be8  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so
01-20 13:36:22.216   468   468 F DEBUG   :     #14 pc 000bc99c  /data/app/com.mick.we.ep0-2/lib/arm/libmono.so (mono_jit_cleanup+20)
01-20 13:36:22.216   468   468 F DEBUG   :     #15 pc 003483c8  /data/app/com.mick.we.ep0-2/lib/arm/libunity.so
01-20 13:36:22.216   468   468 F DEBUG   :     #16 pc 00383b6c  /data/app/com.mick.we.ep0-2/lib/arm/libunity.so
01-20 13:36:22.216   468   468 F DEBUG   :     #17 pc 004cd6ac  /data/app/com.mick.we.ep0-2/lib/arm/libunity.so
01-20 13:36:22.216   468   468 F DEBUG   :     #18 pc 004d18b4  /data/app/com.mick.we.ep0-2/lib/arm/libunity.so
01-20 13:36:22.216   468   468 F DEBUG   :     #19 pc 0004192f  /data/app/com.mick.we.ep0-2/oat/arm/base.odex (offset 0x32000)

**Comment by smdol** [comment]
Yes, this is the bug in Unity 5.2/3 that affects mobile.  We are trying to find a workaround, but hopefully Unity will have a fix pretty soon.

**Comment by nathanmartz** [comment]
If you disable the CardboardAudioListener component then this background crash will go away. We updated the 0.6.0 SDK package to disable this by default. Note that we're working to get a fix or workaround for this asap, so it should be safe to use during development if you need it.

**Comment by nathanmartz** [comment]
Closing as this is fixed now.
