### ISSUE TITLE
no audio, then?

### ISSUE THREAD

**Issue by StefanoCecere** [googlevr/gvr-unity-sdk#150]
latest commit ( https://github.com/googlesamples/cardboard-unity/commit/cc42435f1e67c280e9acd1a6bcfecb501e46e670 )
allows the app to compile under Unity 5.3.1 and latest everything without crashing on startup..
but at the cost of no audio! (Audio Listener disabled)

anybody has a clue how to fix it?
i could work on it if there is any direction where to look!

**Comment by jkammerl** [comment]
This crash related to a bug in Unity and we are actively working on a fix/workaround.

**Comment by nathanmartz** [comment]
To be clear, the crash only happens when the app is backgrounded. We disabled CardboardAudioListener so that no one was inadvertently impacted by this crash, but you can safely enable it for development. We expect that either Unity will post a fix or we will post a workaround soon.

**Comment by StefanoCecere** [comment]
did you already check if Unity 5.4 beta fixes it?
