### ISSUE TITLE
iOS white background

### ISSUE THREAD

**Issue by justinwasilenko** [googlevr/gvr-unity-sdk#159]
I recently updated my app on the App store and had users instantly complain of having White backgrounds where it should be black around each eye. I don't think I changed anything in my project that would affect this but this build was using Unity 5.3.1 and the 0.5.2 SDK. 

This apprently is happening on the iPhone 6S+. I have tested my app on 2 iPhone 6's with no problem. The user who supplied the pictures said this happened when they upgraded from a iPhone 6 to the 6S+. So maybe it's a 6S+ issue??

Pictures below:
![unnamed](https://cloud.githubusercontent.com/assets/11709400/12639035/e04c20d2-c5a1-11e5-8bf7-759046bf30ba.png)
![unnamed 1](https://cloud.githubusercontent.com/assets/11709400/12639036/e1ca4ec0-c5a1-11e5-9adc-b2030430f1ff.png)

**Comment by smdol** [comment]
Are you using Metal or OpenGL?  We have another weird rendering bug reported here on Github I think, which is also Metal-specific.  Interesting point about the 6S+ vs 6S, which I can check on the other bug too.  Also, any idea what version of iOS they are running?

**Comment by justinwasilenko** [comment]
Forgot to mention that... iOS 9.2.1. I'll check on Metal or OpenGL in a little bit. Is one recommended over the other for Cardboard?

**Comment by justinwasilenko** [comment]
Auto Graphics API was checked, so I believe that enables Metal?

**Comment by smdol** [comment]
For any iPhone 6 family device, Auto implies Metal, yes.  We don't have a recommended graphics API for Cardboard on ios, you ought to be able to use either based on your own needs.

**Comment by nathanmartz** [comment]
Justin, can you update to the 0.6.0 SDK and try again? IIRC we added a couple of fixes for the newest iOS phones in that release.

**Comment by justinwasilenko** [comment]
Yeah I just finished updating all my audio sources to use the new
spatialized audio system. And will try to submit a iOS build this week.
Unfortunately I don't have a 6s+ to test anything, so it will be up to the
users to let me know with their reviews again. Hope 0.6 is ok for
production!

**Comment by justinwasilenko** [comment]
I updated the SDK to 0.6 and released an update on the App Store using the new SDK and the upgraded audio system, but users are still complaining of a complete white screen when using the iPhone 6s+.

As far as I know that's the only phone that's affected.

**Comment by smdol** [comment]
From your original screenshots, I see a few things poking out around the outside edges of the eyes (mostly on the left side).  Do you have a non-VR screen with a white background?  It looks like the PreRender camera is not clearing the whole frame.  Just to check:  Make sure the PreRender camera has a black solid color background, and try setting it to (0,0,0,1), opaque black.  (If you updated this project to 0.5.2 from an older SDK, the PreRender camera might not have the right settings, perhaps.)

**Comment by justinwasilenko** [comment]
Yeah, The initial scene is a non VR scene, and then it loads a new scene with VR enabled. The stuff in the background is the initial scene images from the Unity UI.
So it looks like that isn't getting cleared.
The PreRender camera was set correctly, with black solid background. According to the latest App Store review, the whole screen is now white in the latest update using the 0.6 SDK. Not just the edges in the screenshot.

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
