### ISSUE TITLE
LoadScene after magnetic sensor triggered result in crash

### ISSUE THREAD

**Issue by SisadaR** [googlevr/gvr-unity-sdk#163]
using Unity 5.3.2 on Android 5.0.2 / iOS 9.2

In every cases using magnetic sensor is working as it should. SDK.Triggered is set true as it intended. and using it on any Unity UI are work fine.

The wired issue is that every time magnetic sensor was triggered and afterward I use UnityEngine.SceneManagement.SceneManager.LoadScene() app will crash. 

Tired with clean project then import sdk/sample v0.6/v0.5 from github also having the same result.

**Comment by nathanmartz** [comment]
Thanks for the report. We'll try to have a fix for this in the next version.

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
