### ISSUE TITLE
Building in Unity 5.3.2f1 with XCode 7.2 complains about BITCODE

### ISSUE THREAD

**Issue by sampattuzzi** [googlevr/gvr-unity-sdk#164]
I believe this is because of new LLVM settings in Xcode 7 onwards. 
### Environment:
- Unity 5.3.2f1
- XCode 7.2
- Cardboard SDK v0.6
### Steps to reproduce:
1. Building a Unity app for iOS with the IL2CPP compiler option.
2. Compile in Xcode.
### Result:

```
 ld: '/Users/sam/Code/Squashy-Road-VR/Build/Squashy-Road-VR/Libraries/Plugins/iOS/libvrunity.a(vraudio_unity.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
### Workarounds:
- Disabling ENABLE_BITCODE in the Xcode project settings (obviously this is a volatile change and will be wiped when rebuilding from Unity).
- Switching to the Mono 2.x compiler option in Unity. Not ideal either as Unity is moving towards IL2CPP as the prefered option.

**Comment by Wofiel** [comment]
With bitcode now being enabled by default in Unity when using IL2CPP, supplying a version of the Cardboard library is highly desired. It will also mean devs will be able to use the slicing offered by the Apple instead of building all the versions ourselves.

**Comment by austinmao** [comment]
Disabling ENABLE_BITCODE is still not working for me

**Comment by austinmao** [comment]
FYI I am not getting this error when I use https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVRForUnity.unitypackage instead of cloning from the git repo and running the sample scenes. I am not sure why.

**Comment by rusmaxham** [comment]
This has not been an issue for the GoogleVRForUnity SDK for a number of releases now.  Please use the latest .unitypackage for your iOS development.  The demo scenes won't run on iOS or Android when built from the repo (not the package) since the native plugins to support those platforms only exist in the .unitypackage.
