### ISSUE TITLE
Animation with cardboard broken

### ISSUE THREAD

**Issue by futer24** [googlevr/gvr-unity-sdk#165]
Hi

I have a begining animation of cardboardmain prefab but only get a solid color when the animator has not checked the root option. I tested with/without track position/rotation.

In Unity editor no problem with that issue, only when android mobile builds.

Thks in advance

Cardboard SDK 0.52, 0.6
PC
UNITY 5.3.2
Samsung S6

**Comment by smdol** [comment]
To tell the SDK to keep the stereo cameras updated from the main camera during animation, set StereoController.keepStereoUpdated = true.  If it is resetting the position of the camera to (0,0,0), clear the TrackPosition flag on CardboardHead.

**Comment by futer24** [comment]
I already tried with these options, it happens the same

**Comment by futer24** [comment]
any solution?

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
