### ISSUE TITLE
Gaze cursor removed from GazeInputModule?

### ISSUE THREAD

**Issue by thesambassador** [googlevr/gvr-unity-sdk#168]
I'm looking at the differences between version 0.6 and version 0.5.2, and the "cursor" GameObject has just been completely removed, along with everything that had to do with the cursor.  Is there something to replace it?  I see no other mention of a "cursor" in any of the other files.  Why was it removed?

**Comment by smdol** [comment]
There is a new reticle script that replaces it.  See the demo package for an example.

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
