### ISSUE TITLE
Security.framework - sugested fix

### ISSUE THREAD

**Issue by arturleao** [googlevr/gvr-unity-sdk#169]
This can be fixed by going to the Plugins\iOS folder and select the Cardboard.SDK bundle and tick Security in the Framework depedencies tab.

It would be nice if this could be updated in the repository also.

**Comment by edusoft** [comment]
Hi @arturleao  Did you build GoogleDesingLab sample on IOS successfully? Can you help me? This is my post: https://github.com/googlesamples/cardboard-unity/issues/171

Thanks in advanced

**Comment by arturleao** [comment]
Hi @edusoft ,
I didn't but I've been building iOS cardboard apps without any issues, there are a few work arounds though. First one is to add Security in the Framweork dependencies tab in Unity like I've mentioned above. The other one is to disable Bitcode in the Build Settings in XCode and last but not least, fix the library path "\" to a "/" also in the Build Settings in XCode under Library Search Paths. That did it for me, let me know if that works for you. Hope it helps.

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
