### ISSUE TITLE
Crash after LoadLevel and Application.Quit()

### ISSUE THREAD

**Issue by foundway** [googlevr/gvr-unity-sdk#180]
In previous SDK, we have to comment out OnPause override to avoid a LoadLevel crash:

https://github.com/googlesamples/cardboard-unity/issues/126

But now with the latest SDK (0.6), the crash still happens (10% of the time) and comment/uncomment OnPause has no effect anymore. Especially on Galaxy S6. Can anyone take another look?

**Comment by smdol** [comment]
Do you know what viewer the crashes happen with?  Particularly, are they v1 Cardboards (or others) that have the magnet trigger?

**Comment by foundway** [comment]
I didn't put in any viewer yet. Just trying it with naked phone.

**Comment by smdol** [comment]
Can you do this with the standard demo scene (the red cube)?  Or is it another project?

**Comment by asarior** [comment]
I can agree the issue by @foundway. Loading a scene ends in a crash (for me 50% of a time on Android 5.1 and 20% on Android 6.0) with logcat reporting:

> Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9cfa76d0 in tid 9637 (UnityMain)

Maybe its associated with the Gaze. I´m often not able to trigger a GameObject with a script. In this constellation a crash happens nearly ever. All this doesn't happen in the editor.

**Comment by smdol** [comment]
@asarior Do you know which phones?  Galaxy S6?

Here's a test:  See if the crash is related to tilting the phone to the right (as in Cardboard App, which is used to go back to the main menu).  If you keep the phone firmly in landscape, looking forward, is it still possible to cause the crash?

**Comment by asarior** [comment]
@smdol Both phones are different HTC One M8

The crash also happend while keeping the phone in landscape. Disabling the automatic rotation in Android reduces the problem to a minimum.

**Comment by gopumon** [comment]
I am also on SDK v0.6 have a similar issue.

My current scene and the new scene have Cardboard Main prefab. I use a UI button click event to load the new scene with `SceneManager.LoadScene();`.

I use a Samsung S6 and a v1 type Cardboard (with magnetic trigger) to view the app. When I gaze and trigger on the button to load the next scene the app crashes. But when I view the app without the cardboard and do gaze at the button and tap on the screen, it smoothly loads the next scene.

Have no clue whats happening. 
Other button triggers works fine, only one with `LoadScene` have the problem.

**Comment by ybeaulieu** [comment]
Looks like we're having the same issue, but on a Nexus 6. It happened with the Touch input and we're using LoadScene. Logcat also reports this:

> F/libc    (24825): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x96bbf6b0 in tid 24884 (UnityMain)

I don't know if it's related, but it seems that after each crash we have this in the log:

> W/WindowManager(  805): Failed looking up window
> W/WindowManager(  805): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@3145182e does not exist
> W/WindowManager(  805): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8539)
> W/WindowManager(  805): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8530)
> W/WindowManager(  805): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1142)
> W/WindowManager(  805): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:551)

**Comment by nathanmartz** [comment]
We should have a fix for this in our next release.

**Comment by ybeaulieu** [comment]
@nathanmartz Do you have an ETA?

**Comment by nathanmartz** [comment]
In the next few weeks.

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
