### ISSUE TITLE
OnPause() & Resume() Blackscreen issue

### ISSUE THREAD

**Issue by Oshroth** [googlevr/gvr-unity-sdk#187]
I have BaseCardboardDevice::OnPause() commented out due to some issue I was previously having, that I'm having trouble recalling, possibly a crash related to LoadLevel.

I am currently having an issue where Cardboard VR mode doesn't work in the first scene it exists and instead just has a black screen. This occurs if I comment out the Resume() call in BaseCardboardDevice::OnPause(), so there must be something in Resume() that is needed to set up Cardboard properly in the first scene. Non-VR mode is fine, its only the VR Mode of the first scene that is effected.

The issue occurs on Android devices, but not in the editor.

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
