### ISSUE TITLE
Default Parameters Incompatible with MonoDevelop - Unable To Debug

### ISSUE THREAD

**Issue by DashW** [googlevr/gvr-unity-sdk#189]
Although Unity3D supports default parameters, MonoDevelop does not, since Mono C# v2.0 is technically only meant to be compliant with .NET 3.5, not .NET 4.0.

http://forum.unity3d.com/threads/monodevelop-problems-with-default-parameters.67867/

As a result of this, it is no longer possible to attach the MonoDevelop debugger to Unity when the Cardboard SDK is added to the project.

Would it be possible to refactor method signatures with default parameters into multiple methods, to be compliant with Mono 2.0 / .NET 3.5 ?

**Comment by chaosemer** [comment]
I believe this is now fixed with newer versions of Unity. If this is still an issue for you, please reopen.
