### ISSUE TITLE
BitCode Support on IOS

### ISSUE THREAD

**Issue by image28** [googlevr/gvr-unity-sdk#191]
Can't seem to link with libvrunity.so because of lack of bitcode support, can compile with bitcode turned off, but bitcode is now the standard for ios apps.

**Comment by image28** [comment]
Is the source for libvrunity.so available so I can do a recompile

**Comment by Ethan-VisualVocal** [comment]
Even BitCode issue aside, the source for libvrunity would be fantastic.

**Comment by austinmao** [comment]
Related: https://github.com/googlevr/gvr-unity-sdk/issues/164

**Comment by chaosemer** [comment]
I believe this is now fixed. Please reopen if you are still having issues.
