### ISSUE TITLE
Display is too small

### ISSUE THREAD

**Issue by jingjing0327** [googlevr/gvr-unity-sdk#193]
1920 * 1080 screen mobile phone, I do not know why this show, only this one show such as mobile phones, others are normal.
![](http://img.vim-cn.com/fe/7123689037d3931b808448c5653b3bbfec47da.png)

**Comment by jingjing0327** [comment]
if distortion correction choose "None",display is normal...

**Comment by nosmirck** [comment]
What is the physical size of the screen?

**Comment by jingjing0327** [comment]
@nosmirck  hysical size is 5 inche.

**Comment by nosmirck** [comment]
This is really weird, never happened to me before. Which device is this? can you provide more information?

**Comment by smdol** [comment]
This can happen on phones that mis-report the dots-per-inch.  What model phone is it?

**Comment by jingjing0327** [comment]
I use google to search for the same problem：
[https://www.reddit.com/r/GoogleCardboard/comments/395asp/why_doesnt_the_cardboard_app_go_fullscreen/?](url)
I think there might be problems CM ROM.

My device is unpublished phone, I write about the parameters：
 CPU：Qualcomm MSM8974AC2.5Ghz
 Android version :6.0.1
 Resolution：1920*1080
 hysical size：5 inche

thank you @nosmirck @smdol

**Comment by nosmirck** [comment]
@jingjing0327 yeah, it seems that your device is not reporting the DPI correctly.

I wonder if we can set this manually @smdol so we can create a custom settings UI where we can let the user input those parameters (physics screen size, DPI, resolution) and the render will adjust best on those devices.

I've seen apps made on native code (like ParisVR, from 360images on the Google Play Store) that has this option. They allow you to modify these parameters in an advanced settings tab.

This could be a solution for those people using non-common devices or custom ROMs that don't report the DPI to Unity.

**Comment by jingjing0327** [comment]
@nosmirck Thank you very much for your answer, I try to do so, I will write later about the results.

**Comment by cybrbeast** [comment]
I think I have similar problems on the Huawei G6-L11. Any fix that doesn't require rooting would be greatly appreciated.

![20160324_160002](https://cloud.githubusercontent.com/assets/4268422/14142674/69ae83f4-f687-11e5-9301-e568ca5a09ec.jpg)
