### ISSUE TITLE
Get position of Gaze input for Slider

### ISSUE THREAD

**Issue by monizka** [googlevr/gvr-unity-sdk#202]
Hi I'm looking for implementing Gaze function into Unity Slider UI, but since it could not get gazed position, it was not successful. I am using Event Trigger(Point Enter) to get the input.

Any idea for using gaze with Unity Slider??

**Comment by smdol** [comment]
Are you using GazeInputModule, like in the demo scene?  It should be able to set a uGUI Slider if its Canvas is set to World Space render mode.

**Comment by monizka** [comment]
Oh What I was meant by gaze was, like stairing it for 5 seconds.
With GazeInputModule and Event Trigger, normal input like clicking or dragging is working fine(Dragging is not supported with Magnetic trigger though). And I have implemented gazing input with button, but it couldn't be worked with Slider since it does not send any position value of crosshair or normalized value for slider.

**Comment by smdol** [comment]
You could edit GazeInputModule's Process command to keep track of how long the current object has been started at, and if it exceeds a threshold, call the HandleTrigger() function.

**Comment by devXprt** [comment]
Any update?any success ?
