### ISSUE TITLE
World Canvas not displayind

### ISSUE THREAD

**Issue by neHCuoHEpa** [googlevr/gvr-unity-sdk#203]
When I changed a canvas to world space render mode it is start to blinking or disappear in "Game" screen during the edit mode. When I play the scene the canvas disappeared totally.

Im using Cardboard 0.6 and Unity 5.3.4p2, the latest version on the moment.

**Comment by smdol** [comment]
How far away is it from the camera?  If it is too close, it will get clipped by the near plane.

**Comment by neHCuoHEpa** [comment]
No, the canvas is in the range of the camera/cameras. I checked this kind of possibilities.
Attached images are made on same time.
Also another people have this problem.
http://forum.unity3d.com/threads/world-canvas-not-displaying-on-cardboard.396425/

![screen shot 2016-04-12 at 00 03 18](https://cloud.githubusercontent.com/assets/230302/14443887/658cc26c-0042-11e6-8763-a015d85b4f01.png)
![screen shot 2016-04-12 at 00 03 31](https://cloud.githubusercontent.com/assets/230302/14443888/658e097e-0042-11e6-9a77-b98ee55a79b6.png)
![screen shot 2016-04-12 at 00 03 40](https://cloud.githubusercontent.com/assets/230302/14443890/6596bbf0-0042-11e6-8218-b00111e4df07.png)
![screen shot 2016-04-12 at 00 03 52](https://cloud.githubusercontent.com/assets/230302/14443889/659300d2-0042-11e6-8285-c8a6caadc94c.png)

**Comment by smdol** [comment]
Does this same issue appear in the demo scene included with the SDK, particularly the buttons down on the floor?

**Comment by smdol** [comment]
It looks like the answer has been found:

http://forum.unity3d.com/threads/world-canvas-not-displaying-on-cardboard.396425/

**Comment by misclabs** [comment]
I'm seeing this issue on Unity 5.3.4p4. Downgrading to 5.3.4f1 fixed the issue for me.

**Comment by misclabs** [comment]
For me the issue only happened in VR mode. I tested it with my own project and the Cardboard Demo scene.

**Comment by MHDante** [comment]
The 5.4.0b22 Build currently works. Although I'm sure 5.4 release and 5.3.6 will be out soon.
