### ISSUE TITLE
Parental gates for iOS

### ISSUE THREAD

**Issue by zulman** [googlevr/gvr-unity-sdk#204]
Hi,

As you know after tap to the Gear icon user will be able to open Help web-page. From Apple's side it looks like not limited web access, so the Unity app with Cardboard will have 17+ rating.
To avoid it web access must be handled by Parental Gates https://developer.apple.com/app-store/parental-gates/

Now we are able to keep rating 12+ only by hiding Gear icon, but in this case player unable to calibrate app via scan QR code. 
Is it possible to add "Enable Parental Gates" checkbox or something else?

**Comment by nathanmartz** [comment]
How about an option to disable the help center link so that kids can't
browse the open web?

**Comment by zulman** [comment]
Good one, i'll be happy for it too, but user experience will be little bit damaged :)
