### ISSUE TITLE
0.7.2: unpublished release notes, incorrect documentation

### ISSUE THREAD

**Issue by Ethan-VisualVocal** [googlevr/gvr-unity-sdk#205]
Couldn't find anywhere to submit this via the actual site, but: https://developers.google.com/cardboard/unity/release-notes still shows release notes for 0.6.0.

Also, the "GUI in VR" section of the Developer Guide (https://developers.google.com/cardboard/unity/guide#gui_in_vr) contains incorrect info -- there is no "cursor" property on the `GazeInputModule`.

---
0.7.2 update: Recently the packages were updated to 0.7.2, but no indication of what changed in them, nor why the file changes within weren't also committed to the repo.

**Comment by kschmidtdev** [comment]
Bump, would like to see this fixed

**Comment by MiCkSoftware** [comment]
Any update?

**Comment by Ethan-VisualVocal** [comment]
Closing issue -- release notes and documentation were both updated for latest 0.8 release.
