### ISSUE TITLE
iOS Cardboard package overrides brightness. 

### ISSUE THREAD

**Issue by smcilhargey** [googlevr/gvr-unity-sdk#207]
Using Unity 5.3.4f1, and Cardboard-Unity 0.7.0, I've noticed that when launching the application, even without any cardboard scripts in scene, also occurs when you do use the Cardboard prefabs. The brightness of the phone will be set to max, instead of respecting the value the user has set it to.

I basically built a empty unity project, added the package, and made a build, and you can see that the brightness increases as soon as unity splash is shown.

**Comment by smdol** [comment]
It's coming from the GCSOverlayViewController class, which is set up during the call to createUiLayer() in CardboardAppController.mm (in Plugins/iOS).  It does that to prevent screen dimming when you enclose the phone inside a Cardboard viewer.

**Comment by smcilhargey** [comment]
So Unity provides a method of preventing this problem. 
Which it looks like is being used at Line 491 of Cardboard.cs
http://docs.unity3d.com/ScriptReference/SleepTimeout.NeverSleep.html
http://docs.unity3d.com/ScriptReference/Screen-sleepTimeout.html

**Comment by smdol** [comment]
Sorry, I meant auto screen brightness adjustment.

**Comment by toykeinc** [comment]
I had the same problem. The Unity view would auto dim, then lock the screen; it is very bad and it is a show stopper for us. v0.6 does not have this problem. I saw the line 491, but it does not seem to help. Please help!

**Comment by smdol** [comment]
@toykeinc The showstopper is the screen dimming and then turning off?  The initial issue reported here is different: the screen brightness is going to 100%.  If the screen is locking on you despite the Screen.sleepTimeout setting in Cardboard.cs, then that seems like a different bug.  If so, can you create a separate issue for that?

**Comment by toykeinc** [comment]
will do

**Comment by smcilhargey** [comment]
I guess the issue I see is that in parts of an application where people aren't currently using the Cardboard HMD their is still a brightness override, and applications should try their best to respect current settings.

**Comment by chris3000** [comment]
+1 on this issue. iOS screen goes to 100% brightness even if the Cardboard SDK isn't getting called in the scene.

**Comment by chris3000** [comment]
Is there a code patch we can implement ourselves? This is literally the last bug in our app and I'd love to find a solution.

**Comment by smcilhargey** [comment]
I found a temporary solution of downgrading to 0.6.0, unless 0.7.0 was a required update you might get some mileage there.

**Comment by Chang-han** [comment]
Any solution yet? I'm facing the same problem :(
I want to brightness not changing except turning on vr mode because my app has normal screen mode too.

**Comment by smdol** [comment]
In our latest SDK, the brightness in VR Mode is held at the level it was at when VR Mode got enabled.

**Comment by Chang-han** [comment]
@smdol Okay I'll try it
