### ISSUE TITLE
Unity view would auto-dim despite Line 491 Screen.sleepTimeout setting in Cardboard.cs

### ISSUE THREAD

**Issue by toykeinc** [googlevr/gvr-unity-sdk#208]
I am using Unity 5.2.2f1. In Unity view, the screen would auto dim, then lock the screen automatically. The user has to remove the phone from the cardboard to unlock it.

Line 491: Screen.sleepTimeout setting in Cardboard.cs
This line does not seem to work.

I also tried
[UIApplication sharedApplication].idleTimerDisabled = YES;
Does not work either.

**Comment by smdol** [comment]
Where did you try "[UIApplication sharedApplication].idleTimerDisabled = YES;"?

**Comment by toykeinc** [comment]
I tried a few places. E.g. appDelegate didFinishLaunchingWithOptions. None worked

**Comment by toykeinc** [comment]
Repro steps:

1. open sample app in Demo 0.7. Build for iOS
2. If you move your head constantly, then no problem
3. If you don't move (e.g. reading a menu) after 1 min, it will auto-dim
Go to iPhone > Settings > General > Auto Lock (it is set to 1 min)
4. You have to move head quickly to cancel dim. If not, after 3 seconds, the screen turns off
It is so annoying that we can't ship our app like this

This is a regression from v0.6

**Comment by smdol** [comment]
v0.7 has a motion-detection based idle timer.  The normal idle timer is disabled when the phone is moving but enabled when it is still, so the battery won't drain so fast if you set the phone down.  It sounds like the motion threshold is too eager to enable the idle timer.  I will try to find where you can add code to get around this.

**Comment by ianhirschfeld** [comment]
I'm seeing the same thing in Unity 5.3.4f1 using the Cardboard SDK downloaded on April 7th. I tried manually putting `[UIApplication sharedApplication].idleTimerDisabled = YES;` in the compiled Xcode project's `didFinishLaunchingWithOptions` as well as manually setting `.NeverSleep` in `Start()` in a script I attached to the Cardboard object in Unity.

**Comment by ianhirschfeld** [comment]
@smdol can you point me in the direction of where that motion detection is happening in the code please? I'd love to put in a hack for now locally for a project I am working on. Thanks!

**Comment by smdol** [comment]
There is a class called GCSIdleManagementHelper, which is used by GCSOverlayViewController, but I don't think it is public.
