### ISSUE TITLE
(X-POST) Android : New version of the Cardboard SDK requires 'READ_PHONE_STATE'

### ISSUE THREAD

**Issue by apollow** [googlevr/gvr-unity-sdk#209]
This is a port over from the issue brought by @R1ck77: 
https://github.com/googlesamples/cardboard-java/issues/71

Refer to the last comment he made, but the files to change are
unityvractivity.aar and cardboard_android_common.aar, this will fix the READ_PHONE_STATE that we could not have in our app.

**Comment by smdol** [comment]
The Unity SDK has a different manifest than the Java one, and it has targetSDK = 19.  Has there been a problem with READ_PHONE_STATE permission in the Unity SDK?

**Comment by R1ck77** [comment]
The android manifest created by Unity is not the culprit: if one of the `aar`'s included in the Unity project is missing the 

    <uses-sdk android:minSdkVersion="16"/>    // or 19 for what matters

element, a backward compatibility rule will kick in, and add the `READ_PHONE_STATE` permission automatically to the app.

I don't have Unity installed right now, so I can't check, but you can dothat yourself by using the command

    aapt d permissions unity_generated_package.apk

(you will need to find the `aapt` command in the android sdk package).

**Comment by apollow** [comment]
I have upgraded to 0.8.0 and have not found this issue since, I think it's appropriate to close this issue now.
