### ISSUE TITLE
Reflections on water-surface (Unity WaterProDaytime) are wrong

### ISSUE THREAD

**Issue by miarchimi** [googlevr/gvr-unity-sdk#212]
In "Stereomode" With Cardboard Cameras (Camera Left and Camera Right) the Reflections on the Unity Water Prefab "WaterProDaytime" are wrong rendered. In the "2D-View" the reflections are correct rendered.
In the Unity Scene i use a Skybox witch is reflecting on the Unity-Water.
And i use the Unity Prefab FirstPersonCharacter with his Camera.
See uploaded images:

<img width="683" alt="bildschirmfoto 2016-04-26 um 16 52 00" src="https://cloud.githubusercontent.com/assets/15873119/14822821/64eb68d8-0bd0-11e6-9c8b-0cd71290aa68.png">
<img width="691" alt="bildschirmfoto 2016-04-26 um 16 52 24" src="https://cloud.githubusercontent.com/assets/15873119/14822832/6efea808-0bd0-11e6-845b-20c0178fc7c6.png">

**Comment by nathanmartz** [comment]
Hi. We expect this to be resolved when Unity releases native Cardboard
support later this year. Until then, I'm not sure that there will be a
straightforward fix.

**Comment by miarchimi** [comment]
Thank's for the answer. So then i hope it will be fixed by Unity later this year.

**Comment by Selzier** [comment]
Is there a mobile device that can render Unity water with reflections in VR that won't melt the GPU?

**Comment by smdol** [comment]
The Tango dev kits might be able to handle it (they use the Tegra K1), but other than that... I don't know.

**Comment by miarchimi** [comment]
Yes, iPhone 6 and above render it great with Metal API - https://en.wikipedia.org/wiki/Metal_(API)

**Comment by liiijz** [comment]
I meet this same bug, is there any way to fix it?
or any suggestion on plan b ?

**Comment by smdol** [comment]
Unity will have Cardboard / GoogleVR built-in to the engine in the not too distant future.  There's no known easy fix in the current SDK, which is going to be deprecated anyway in favor of the built-in support.

**Comment by Ashokmaurya** [comment]
but i m using Cardboard / GoogleVR

**Comment by savashito** [comment]
This is still broken on Unity 2017.1.0f3 with cardboard 1.7, any fix for it?

**Comment by fredsa** [comment]
This is Unity case 816992, according https://forum.unity3d.com/threads/water-reflections-in-vr-are-wrong-in-5-4-0f1.417495/, referenced in the issue #673.

I was able to reproduce this in Unity 2017.3.0b6. I filed new Unity bug report (case 964054) with a small repro project for this version.

**Comment by fredsa** [comment]
Unity is working on a fix for this.

**Comment by savashito** [comment]
Thank you @fredsa ! Do you have any update on this? The first time this bug was reported was over 3.5 years ago. This is a feature is critical for our release, I am just worried that it will be long till this is fix.

**Comment by tonnyESP** [comment]
Is there any news about this bug?

**Comment by anubisza** [comment]
Hi,

I struggled with this for days and finally managed to fix it! The fix involves having one camera for each eye to render the reflection texture for that eye. It also seems like Unity/GVR is swapping the left/right eye cameras so I had to use the inverse in my WaterVR2.cs.

 For reference I'm using:
- Unity 2017.3.1
- Google VR SDK ForUnity v1.120.0
- Google Pixel 1 Android device running Android 8.1

My patch was inspired by these fine souls:
- https://github.com/Vytek/WaterVRTest
- https://gist.github.com/miketucker/7253ec502f9ad205eee8a146481d6a74

How to try this fix in your project:
1. Create a new Material called WaterVR
2. Assign the attached GVR/WaterVR2 shader to the WaterVR material.
3. Create a new Plane in your scene and attached the WaterVR2.cs script and the WaterVR material.
4. Hopefully this works in the editor and your device!

[WaterVR2.shader.txt](https://github.com/googlevr/gvr-unity-sdk/files/1784263/WaterVR2.shader.txt)
[WaterVR2.cs.txt](https://github.com/googlevr/gvr-unity-sdk/files/1784264/WaterVR2.cs.txt)

**Comment by rusmaxham** [comment]
Unfortunately, Unity has declared that [water reflections are not supported in VR](https://docs.unity3d.com/Manual/HOWTO-Water.html), so this issue won't be fixed.
