### ISSUE TITLE
Unable to .GetOutputData() on CardboardAudioSource

### ISSUE THREAD

**Issue by Selzier** [googlevr/gvr-unity-sdk#213]
Unity's AudioSource component has the following function: [](http://docs.unity3d.com/ScriptReference/AudioSource.GetOutputData.html)http://docs.unity3d.com/ScriptReference/AudioSource.GetOutputData.html

.. which Provides a block of the currently playing source's output data (we're using this for Lip-Sync).

Is it possible to GetOutputData with a CardboardAudioSource?

**Comment by smdol** [comment]
For your use case, does it matter if the data you get back is spatialized or not?

**Comment by Selzier** [comment]
No, not important for this. We only need to get the output data to generate the lip-sync positions. For this, the spatialized audio would actually be worse, because lip-sync would not respond to positional audio (my lips will move regardless of what other person is doing with their head).

**Comment by smdol** [comment]
This seems like a useful feature.  CardboardAudioSource.cs actually contains an AudioSource internally, so if you edit that script and add a passthrough method, does it work?  (This is a quick test, and if it works, unblocks you.  We can still add an official passthrough in an upcoming release.)

**Comment by Selzier** [comment]
I've seen the AudioSouce in CardboardAudioSource.cs and have accessed it's .GetOutputData, but nothing is there. I'm not sure how to pass the .GetOutputData from from AudioSource to CardboardAudioSource :(

**Comment by Selzier** [comment]
Yes, when adding the passthrough method, we are still getting all "0"s for the .GetOutputData.

**Comment by smdol** [comment]
OK.  This requires a change in the actual audio plugin (libaudiopluginvrunity) to pass the data along.  We'll have that in the next release, coming very soon (a few weeks).

**Comment by anokta** [comment]
@Selzier FYI, GvrAudioSource.GetOutputData can be used now, was added with the v0.8.0 update (b633dae). As discussed, the function will return the unprocessed audio input - before spatialization.
