### ISSUE TITLE
Cardboard0.7.2 LG-H860 : The Pose3D.Orientation is never change

### ISSUE THREAD

**Issue by tachen** [googlevr/gvr-unity-sdk#219]
The LG-H860 is use armv8I and I suspect that in this problem because cardboard not have the plugins.

**Comment by smdol** [comment]
Are you able to install and run the Cardboard app from the Play Store?

**Comment by tachen** [comment]
Yeah,It have an other problem but the orientation have data!
![cbaeb3c315079191ac6f3e424ce8ccf0](https://cloud.githubusercontent.com/assets/5178366/15279045/a02bc316-1b52-11e6-8d8b-04bbe225840e.jpg)
