### ISSUE TITLE
Blurry UI and Text Meshes - iOS

### ISSUE THREAD

**Issue by yalfers** [googlevr/gvr-unity-sdk#221]
I've noticed a very blurry experience on iOS with the majority of the UI and sprites. Nothing has changed with the setup, yet I can't seem to find a scenario where things look as clear as they were. I have rolled back to previous versions of Unity and Cardboard.

I'm running out of things to modify. The scene looks perfectly fine with all objects, minus UI and sprites.

To elaborate, it's also with TextMeshes. Everything looks perfectly fine in the scene and also with VRMode disabled. Once I try to run it in VRMode, it becomes a complete blur.

This is running the latest SDK in Unity 5.3.4f1 as well as 5.3.1p2

**Comment by zhuyifan2013** [comment]
How about this issue ? @yalfers
