### ISSUE TITLE
GVr Audio is not working

### ISSUE THREAD

**Issue by prasadxna** [googlevr/gvr-unity-sdk#222]
Cant hear anything in headset Demo scene

**Comment by smdol** [comment]
Under Edit>Project Settings>Audio, is the Spatializer plugin set to Gvr?

**Comment by prasadxna** [comment]
Thank you that must be it!

**Comment by smdol** [comment]
OK, I'll close the issue.  If that doesn't fix it, re-open.

**Comment by nilssanderson** [comment]
Thank you very much, it should maybe be more apparent in documentation on setup that this setting needs to be turned on.

**Comment by Morphjeus31** [comment]
Thanks!!!
