### ISSUE TITLE
DLLNotFoundException: audiopluggingvrunity

### ISSUE THREAD

**Issue by stuartsoft** [googlevr/gvr-unity-sdk#223]
I just recently updated my copy of the Google VR SDK in my Unity game from 0.7.2 to 0.8.0 but upon deleting and re-importing the new package, I was greeted with the following error message while unpacking the new SDK in Unity:

![copy failed](https://cloud.githubusercontent.com/assets/6208902/15414746/76003a34-1e0b-11e6-809a-8b3b62f36b1b.PNG)

Pressing cancel will allow the rest of the sdk to install without an issue. I then dropped a new GvrMain prefab into my scene and started up the game like normal and although it is running, the game throws a DLLNotFoundException error each time:

![missingdll](https://cloud.githubusercontent.com/assets/6208902/15414781/acc9c4b8-1e0b-11e6-8bfb-dce6e8f2517f.PNG)

For reference, I'm using Unity 5.3.4f1 on Win 10

**Comment by nathanmartz** [comment]
When upgrading our plugin, it's usually best to delete the old version and
then install the new version. Have you tried that?

**Comment by smdol** [comment]
The file name in your error message (audiopluginvrunity.dll) is the old name of that file. The new SDK should not be unpacking anything to that path, since the new dll name is (slightly) different: audioplugingvrunity.dll (vr -> gvr).  There may still be a permissions issue, but that does seem weird.  If you delete the entire Plugins directory, does that help?  Another workaround is to unpack the SDK into a new empty Unity project, then copy the missing file over.

**Comment by stuartsoft** [comment]
Before upgrading the Google VR SDK, I completely removed the entire Cardboard folder from the assets directory and also deleted the entire Plugins folder.

**Comment by stuartsoft** [comment]
@smdol, I'll give your solution a try later today...

**Comment by smdol** [comment]
We've replicated your issue internally.  Looks like there is some permissions issue with the old SDK that shows up in Win10.  Let me know if the workaround helps.

**Comment by christianchomiak** [comment]
Same problem here, although it seems that deleting the Cardboard and Plugins folder using the Windows Explorer, instead from inside Unity, seems to work alright.

**Comment by j2l** [comment]
renaming audiopluginvrunity.dll to audioplugingvrunity.dll also seems to work.

**Comment by Pixel-Labs** [comment]
Can confirm the same problem. Eventually shifted it. Noticed that on deletion is would re-appear. Ended up removing all cardboard references outside of Unity when project was closed. Started Unity again, let it do it's thing with importing. Closed Unity then reopened and imported new version of cardboard / GVR. Phew!
