### ISSUE TITLE
question  ios  8.0   unity5.3.4p6 xcode7.3.1

### ISSUE THREAD

**Issue by wxpasta** [googlevr/gvr-unity-sdk#224]
unity 5.3.4p6   xcode7.3.1

2016-05-20 14:55:25.256 VRMAX[2028:592689] -> registered mono modules 0x10150ff58
-> applicationDidFinishLaunching()
May 20 14:55:26  VRMAX[2028] <Error>: CGContextSetShouldAntialias: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 14:55:26  VRMAX[2028] <Error>: CGContextSetInterpolationQuality: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 14:55:26  VRMAX[2028] <Error>: CGContextScaleCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 14:55:26  VRMAX[2028] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 14:55:26  VRMAX[2028] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 14:55:26  VRMAX[2028] <Error>: CGContextSetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 14:55:26  VRMAX[2028] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 14:55:26  VRMAX[2028] <Error>: CGContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2016-05-20 14:55:26.329 VRMAX[2028:592689] Uncaught exception: NSInvalidArgumentException: **\* -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument
(
    0   CoreFoundation                      0x0000000184a91918 <redacted> + 148
    1   libobjc.A.dylib                     0x00000001840fff80 objc_exception_throw + 56
    2   CoreFoundation                      0x0000000184a91848 <redacted> + 0
    3   Foundation                          0x0000000185362814 <redacted> + 124
    4   Foundation                          0x0000000185362710 <redacted> + 68
    5   VRMAX                               0x000000010135676c -[GVROverlayView initWithFrame:] + 3228
    6   VRMAX                               0x0000000101353328 -[GVRUnityController init] + 104
    7   VRMAX                               0x0000000101353940 createUiLayer + 88
    8   VRMAX                               0x00000001006d994c -[CardboardAppController createUnityView] + 108
    9   VRMAX                               0x0000000100501460 -[UnityAppController application:didFinishLaunchingWithOptions:] + 1044
    10  UIKit                               0x00000001897f9704 <redacted> + 400
    11  UIKit                               0x0000000189a28130 <redacted> + 2904
    12  UIKit                               0x0000000189a2c4b8 <redacted> + 1672
    13  UIKit                               0x0000000189a295c0 <redacted> + 168
    14  FrontBoardServices                  0x0000000186047790 <redacted> + 184
    15  FrontBoardServices                  0x0000000186047b10 <redacted> + 56
    16  CoreFoundation                      0x0000000184a48efc <redacted> + 24
    17  CoreFoundation                      0x0000000184a48990 <redacted> + 540
    18  CoreFoundation                      0x0000000184a46690 <redacted> + 724
    19  CoreFoundation                      0x0000000184975680 CFRunLoopRunSpecific + 384
    20  UIKit                               0x00000001897f2580 <redacted> + 460
    21  UIKit                               0x00000001897ecd90 UIApplicationMain + 204
    22  VRMAX                               0x0000000100a42b30 main + 208
    23  libdyld.dylib                       0x00000001845168b8 <redacted> + 4
)
2016-05-20 14:55:26.330 VRMAX[2028:592689] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
**\* First throw call stack:
(0x184a91900 0x1840fff80 0x184a91848 0x185362814 0x185362710 0x10135676c 0x101353328 0x101353940 0x1006d994c 0x100501460 0x1897f9704 0x189a28130 0x189a2c4b8 0x189a295c0 0x186047790 0x186047b10 0x184a48efc 0x184a48990 0x184a46690 0x184975680 0x1897f2580 0x1897ecd90 0x100a42b30 0x1845168b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by smdol** [comment]
This looks like the issue:

2016-05-20 14:55:26.329 VRMAX[2028:592689] Uncaught exception: NSInvalidArgumentException: *** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument

Did you make any changes to the Xcode project that Unity created?

**Comment by wxpasta** [comment]
unity and iOS Secondary development

**Comment by smdol** [comment]
Is it a new project, or did you upgrade the SDK in an existing project?  If upgrade, did you delete the Plugins directory before upgrading?

**Comment by biframes** [comment]
I have the same problem to.
I'm traing to embebed Unity3d inside IOS.
did you solve it?

**Comment by wxpasta** [comment]
add  GLKit.framework
