### ISSUE TITLE
Issue with VRMode and Cardboard UI

### ISSUE THREAD

**Issue by MuhammadTirmizey** [googlevr/gvr-unity-sdk#226]
Hi, I developed a 3D scene with Unity 5.3.4f1, then added the Google VR SDK as per the instructions on the website (Version before the Castle Defense sample was added). Then I imported the project to android studio, however when I run the scene on my phone through android studio it does not show any Cardboard UI however running directly from Unity shows the UI. 
![image](https://cloud.githubusercontent.com/assets/5859994/15447965/5e280848-1f4a-11e6-91d9-b10e5bde9bd2.png)

E/Unity: Object is null when calling method setUILayerEnabled   
                                                                             (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

I think it maybe something to do with the above error messages, there are several of these: 

Object is null when calling method setVRModeEnabled
                                                                              (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Any help would be appreciated.

P.S Also I had another question, I was able to figure out how to get the VR up and running however I was wondering, I want my app to be able to communicate information between my application (written in Android Studio) and the Unity scene, would I need to configure this on the Unity side or is it possible to do it in android studio as well? (Mainly just displaying images taken within the app in the Unity scene). I'm aware this might not be the perfect place for this however I have had very minimal success finding resources/documentation on this specific usage of Studio and Unity.

P.S.S There is another issue that keeps popping up even when the application is able to load up the unity scene.
Exception getting class com.google.vr.platform.unity.UnityVrActivityListener: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.vr.platform.unity.UnityVrActivityListener
                                                       java.lang.ClassNotFoundException: com.google.vr.platform.unity.UnityVrActivityListener

Im not sure where this originates from? After I port I only change the name of the activity within the manifest as it named com.google.unity,GoogleUnityActivity which I change to UnityPlayerNativeActivity, the rest remains as it is.

Also, do we need to include the libraries (app,common,core) from the Cardboard SDK for android studio to the apps that we want to run through android studio?

Thanks in advance!

**Comment by smdol** [comment]
This happens when the manifest gets reset from the one included in the
unitypackage.  In particular, the Java class needs to be
GoogleUnityActivity.  If you delete it and reimport the SDK -- uncheck
everything wise but this one file -- this will likely fix the problem.

**Comment by smdol** [comment]
Follow-up thought.  If you need the activity class to be your own, there
are some options.  If you extend GoogleUnityActivity, that should take care
of it.  Otherwise, it gets tricky, involving decompilation and modifying
the SDK C# code.  Let me know if you have to go that way and I can give
more details.  (This is just one reason we are pursuing native integration
with Unity.)

**Comment by MuhammadTirmizey** [comment]
I tried to extend GoogleUnityActivity but it doesnt seem to recognise it for some reason. Am I doing something wrong? 
I import the gvr sdk to my unity project, then I export it to android, I then import a new android project, it doesnt run yet because in the AndroidManifest it expects an activity com.google.unity,GoogleUnityActivity, which doesnt seem to be available.

**Comment by smdol** [comment]
There are actually two things to do if you extend GoogleUnityActivity.  First, change the manifest so it refers to your class.  Second, edit the corresponding string in VRDevices/AndroidDevice.cs.  Text search for com.google.unity,GoogleUnityActivity to find it.

**Comment by MuhammadTirmizey** [comment]
There doesn't seem to be any mention of GoogleUnityActivity in gvr-unity-sdk\GoogleVR\Scripts\VRDevices\AndroidDevice.cs

**Comment by smdol** [comment]
Oops, sorry.  My advice is out of date.  Let me dig a little.  First, did you update the manifest to your extended class?

**Comment by MuhammadTirmizey** [comment]
Yes, so now the activity refers to UnityPlayerNativeActivity in the manifest.

**Comment by smdol** [comment]
That definitely won't work.  If your activity class extends GoogleUnityActivity, the manifest needs to refer to your class specifically.  GoogleUnityActivity lives in Assets/Plugins/Android/unitygvractivity.aar, and it depends on other classes in gvr_android_common.aar in the same place.  Make sure to add those as dependencies in Android Studio.

**Comment by MuhammadTirmizey** [comment]
Sorry for the confusion, I meant: <activity android:name=".UnityPlayerNativeActivity"> 
And ill have a look, also is it necessary for us to add dependencies on the libraries for the gvr android sdk?

**Comment by smdol** [comment]
Yes.

**Comment by MuhammadTirmizey** [comment]
Dude, thanks alot! Sorry to have bothered you for such a trivial thing. On a side note, is it possible for making changes to the unity scene from within android studio? Pass an image that would be displayed in the 3D view? 
Once again thank you so much!

**Comment by nathanmartz** [comment]
This is possible but requires careful work between Unity and Java. For that kind of information, you should look to the Unity forums as we aren't able to give out general Unity tech support here.
