### ISSUE TITLE
Drift issue fix for Google VR SDK

### ISSUE THREAD

**Issue by andregm3** [googlevr/gvr-unity-sdk#227]
Can someone integrate this open source Sensor Fusion to Cardboard SDK ? Improved orientation sensor 2 and calibrated gyro, made my sensors work pefectly !

https://play.google.com/store/apps/details?id=org.hitlabnz.sensor_fusion_demo

the project is here: 

https://bitbucket.org/apacha/sensor-fusion-demo/

**Comment by nathanmartz** [comment]
Thanks for the link, but no no need to double post.
