### ISSUE TITLE
Issue when importing new GoogleVRForUnity.unitypackage

### ISSUE THREAD

**Issue by osvaldovillagrana** [googlevr/gvr-unity-sdk#228]
Unity 5.3.2 and 5.3.5
When importing GoogleVRForUnity.unitypackage in a new Unity project, two compile errors are shown:

File: EmulatorClientSocket.cs

Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs(74,46): error CS0120: An object reference is required to access non-static member `System.Diagnostics.Process.Start()'

Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs(78,17): error CS1061: Type `System.Diagnostics.Process' does not contain a definition for `Close' and no extension method `Close' of type `System.Diagnostics.Process' could be found (are you missing a using directive or an assembly reference?)

**Comment by btco** [comment]
This is due to the fact that in some version of Unity, the default platform is WebGL.
You can solve this by switching to the Android platform in File | Build Settings.

**Comment by btco** [comment]
(the root cause is that this part of the code is missing correct #if/#endif guards, we will fix that soon).
