### ISSUE TITLE
AppCompat and GoogleUnityActivity on Device Profile

### ISSUE THREAD

**Issue by apollow** [googlevr/gvr-unity-sdk#229]
(I am currently working on 0.8.0 on GoogleVR)

Just discovered a serious technical issue on our end with our ongoing Cardboard SDK integration endeavors in regards to device profiling for Android.

Our Android app is primarily a Single Activity app that utilizes techniques involved in: http://forum.unity3d.com/threads/using-unity-android-in-a-sub-view.98315/, while extending AppCompatActivity.

The technical issue is when our single activity app extends AppCompatActivity, we cannot get Cardboard's full capabilities, as to my knowledge, AndroidBaseDevice requires that the activity for which the unityview is held in to be a GoogleUnityActivity. (I believe most of the code that checks this is not changeable on the Unity side/Android side, so I have to accept this as my restriction according to https://github.com/googlevr/gvr-unity-sdk/issues/158)

I was able to change and extend to the GoogleUnityActivity to see that the cardboard device profiler was doing its job, but the issue that's caused here is that I cannot utilize the support library without force switching into minimum API 21 for our Toolbar. Our app is material designed focused so the library is deeply embedded within our Vrideo app. Having it forced API 21 cannot be acceptable as we have a good percentage of users on our app using KitKat.

What I want accomplished is the following:
1) KitKat compatible
2) AppCompat/Support Library functionalities or something similar for Material Design
3) Proper device profiling

Any thoughts?

**Comment by smdol** [comment]
This is a bit of a hack, but you can decompile GoogleUnityActivity and change its base class to AppCompatActivity and then recompile that.

**Comment by apollow** [comment]
That works. People who are looking into this take note to putting the requestFeature line before super.onCreate() and potentially(?) remove the "final" part of the "final  /* synthetic */ Activity val$self;" statement if you are using the decompiler from javadecompilers site.
