### ISSUE TITLE
GetIntersectionPosition

### ISSUE THREAD

**Issue by whizzkid** [googlevr/gvr-unity-sdk#231]
I want to know where I'm pointing at using the gazeInputModule.  

Right now I can do this if I edit the GazeInputModule and change GetIntersectionMethod() to a public.
and then I can use 
`Vector3 goal = GazeInputMod.GetIntersectionPosition ();  `

Is this the correct way to see where I'm pointing at?  If so, shouldn't GetIntersectionMethod be a public?
Or should I use a different way to get the position I'm currently pointing at?

**Comment by smdol** [comment]
If you are using the IGazePointer interface (which GvrReticle.cs does) you can get the intersection position that way.  Through IGazePointer you get more information, like whether an object is even being gazed at, which camera is seeing it, and what the intersection position is.

**Comment by whizzkid** [comment]
How do I 'get the position from that'? from the looks of IGvrGazePointer (not IGazePointer, that one doesn't exist) i should make my own gazepointer ? i or something ?

My little project right now is setup like this:

I have a floor with a navmesh, when I gaze upon it and click, I want to sent the player to that position.

Right now, using the method i first described, 
On my floor i have a Pointer Click event, which calls my Manager.moveToMeshPoint() method.
this method does:
```
	Vector3 goal = GazeInputMod.GetIntersectionPosition ();
	Player.GetComponent<NavMeshAgent> ().destination = goal;
```
This works, but needs the GazeInputModule to be modified and GetIntersectionPosition to become public.


What's a better/proper way to do this?   (get the position that was clicked on)

**Comment by whizzkid** [comment]
(I have a separate object which i send to that location, the player follows that object, so that you don't auto-orient towards the direction you're moving to)

**Comment by ashleydb** [comment]
If it helps, take a look at the "Bonus Interaction" section of a tutorial I
wrote a while back, (replace "Cardboard" with "GVR" for the newer SDK.)

Specifically I think you would want something like this as a script
component on the ground. I assume you've got the Physics Raycaster setup
too, but take a look at the rest of the tutorial if not.

public class GroundTriggers : MonoBehaviour, IPointerClickHandler {

  // Will work for clicks and Cardboard trigger presses
  public void OnPointerClick(PointerEventData eventData)
  {
    Manager.moveToMeshPoint(*eventData.pointerCurrentRaycast.worldPosition*
);
  }
}



Ashley Bennett
www.HiAsh.com

**Comment by ashleydb** [comment]
Forgot the tutorial link :)
http://blog.hiash.com/2016/02/vr-for-beginners-cardboard-unity-and.html



Ashley Bennett
www.HiAsh.com

**Comment by nathanmartz** [comment]
We need to keep GitHub issues focused on actual bugs. I think there is enough info to resolve the OP but if not, this kind of conversation is better for StackOverflow.
