### ISSUE TITLE
Skybox not working?

### ISSUE THREAD

**Issue by MuhammadTirmizey** [googlevr/gvr-unity-sdk#232]
Hi, I have a skybox that came with this package and for some reason it doesn't apply to the gvrmain. I tested this in the sample scenes that come with gvr sdk and they dont seem to display the sandbox either. I tried it with the default skybox as well and it doesnt seem to work. The floor shows the skybox reflection however it doesnt get shown in VR mode, any help would be appreciated, Thanks

**Comment by smdol** [comment]
Do you mean the skybox doesn't appear in the sky or on the reflection on the floor (or both)?

**Comment by MuhammadTirmizey** [comment]
It doesn't seem to appear in the sky, does show the reflection on floor however.

**Comment by MuhammadTirmizey** [comment]
Never mind, it was just an issue of changing the clear flags from solid colours to skybox for both Main Camera Left and Main Camera Right. Thanks though.

**Comment by smdol** [comment]
Hmm.  Those clear flags should have been copied from the parent Main Camera
at startup.
