### ISSUE TITLE
Camera Issues with Cardboard v .8

### ISSUE THREAD

**Issue by yalfers** [googlevr/gvr-unity-sdk#233]
My issue started when VRMode was disabled, but it appears to be translating to occurring during VRMode as well.

Hopefully the picture below gives an idea of what I'm facing. Previous versions of the SDK were fine with the camera rendering, but I cannot go back due to the render texture being far too blurry when text was displayed (found a workaround by increasing the render texture's size in v0.8).

<img width="1264" alt="vrdisabled" src="https://cloud.githubusercontent.com/assets/8351186/15649198/c4611c0e-263d-11e6-9ac0-7a1490379c7e.png">

The picture depicts the scene view vs the Camera Preview. The camera seems to be picking up the UI and distant objects. No matter how much I modify the camera values I cannot seem to get anything to display, but the camera was perfectly fine in previous versions.

If I downgrade Unity to 5.3.4f1 and leave the distortion correction to Unity it renders properly in VREnabled mode. As soon as I try to run it with VRMode disabled I get the issue described above.

**Comment by yalfers** [comment]
This can be avoided in the editor by changing Graphics Emulation to none, but this is no help on the device.

**Comment by ezonecom** [comment]
Have you made any changes to OpenGL settings?

**Comment by yalfers** [comment]
I have tried all combinations possible on Android with no luck. I have not retargeted iOS for a metal test.

**Comment by smdol** [comment]
Regarding UI, Unity 5.3.4p2 introduced a bug that doesn't draw World Space UI into cameras with a target texture.  We use a target texture for VR Mode to do the distortion correction.  Due to that and some other reasons, I'm sticking with 5.3.3 for the time being.  Can you try that?

I can't tell from the preview there what the issue is for non-UI elements.  Can you explain?

**Comment by yalfers** [comment]
I will try 5.3.3 when I can. Basically what's happening is the camera displays what appears to be near clipping much farther than it really is. The near is set as close as possible (.3-10). What you can see through the distance is a rather significant distance away. This has become a sudden issue, and reverting back to a previous cardboard version isn't possible since my workaround for blurry text on ui is most easily fixed with v0.8.

I can give more images to elaborate if necessary

**Comment by smdol** [comment]
As a test, set the distortion method to None.  This switches off the post-processing for distortion, allowing Unity to draw directly to the screen.  Any change?

**Comment by yalfers** [comment]
When it was set to None I noticed the issue translate over to VRMode enabled as well. I will try on 5.3.3 to be sure, but in the two versions I tested I had no luck. There was a noticeable difference between 5.3.4 and the most recent patch, but I did not go earlier than 5.3.4.

**Comment by nathanmartz** [comment]
99% sure this is the Unity 5.3.4 render texture bug.

**Comment by yalfers** [comment]
Unfortunately this wasn't the case. It's still happening with 5.3.3f1 (I was using a version of 5.3.4 that was noted to still be working).

I reinstalled 5.3.3f1 and attempted all distortion correction modes with no luck.

The VR mode still works as expected, but VR disabled is a complete mess.

**Comment by smdol** [comment]
Your issue seems to be happening precisely when Unity is drawing directly to the screen, as opposed to through the post-processing filter we apply for distortion correction.  

Are you using any other Image Effects?  Maybe you could post a screenshot of your Main Camera's inspector panel?

**Comment by yalfers** [comment]
It appears the entire project was corrupt. Resorted to moving everything to a new project and so far on Android it has not been reproduced.
