### ISSUE TITLE
Error building Player: Effect GVR Audio Renderer could not be found

### ISSUE THREAD

**Issue by edulix** [googlevr/gvr-unity-sdk#234]
Just installed everything today (using commit b826947c3d6b1f33c70cea50e59f870fd09714c9, unity 5.4.0b18 in opensuse x86_64 linux), and followed the instructions in https://developers.google.com/vr/unity/get-started-android and I'm getting this building error in unity, resulting on no successful build:

"Error building Player: Effect GVR Audio Renderer could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly."

What immediate solution is there for this? I should add that this is my first experience with unity and android vr.

**Comment by smdol** [comment]
I'm not sure the Audio plugin we ship will link on Linux.  We don't officially support it since it is still experimental.  But:  did you build for a mobile platform or for desktop?

**Comment by edulix** [comment]
@smdol my target is building for Android, but I have just tried for Linux Desktop and WebGL and the build error happens in all of three of them.

**Comment by nathanmartz** [comment]
We don't support the linux version of the Unity editor. It's currently
experimental.

**Comment by edulix** [comment]
@nathanmartz is there any way I can remove any audio need for my project so that.. I can compile?

**Comment by nathanmartz** [comment]
I'm confused. What platform are you actually targeting? Android or Linux? The GVR SDK is only intended for Android and iOS.

**Comment by edulix** [comment]
@nathanmartz I'm sorry: I'm trying to build and run, the host OS is Linux, and the target is Android.

**Comment by lorenzochomp** [comment]
I second that... I'm also using the Unity Editor on linux, and it would be great being able to work and compile. I can manage to make the final build on my mac, but I'd prefer to work on Linux, most of the time :)

**Comment by jdknox** [comment]
How can the GVR Audio Renderer be disabled on Windows or Mac?
