### ISSUE TITLE
Android : An implementation integrating GoogleUnityActivity asks for EXTERNAL_STORAGE permissions twice.

### ISSUE THREAD

**Issue by apollow** [googlevr/gvr-unity-sdk#235]
This is a continuation of the efforts in fully integrating with cardboard sdk from https://github.com/googlevr/gvr-unity-sdk/issues/229.

Currently on startup, I get the following issue that pops up:

![screenshot_20160531-155948](https://cloud.githubusercontent.com/assets/2719085/15693437/0066a77a-274a-11e6-9ac9-7ac850490a52.png)

http://sendvid.com/q0atek3n (Video shown here)
This permission dialog pops up twice during the startup of the app, which we don't want. This behavior can repeat itself multiple times if you let it run through the resume/onpause activity lifecycle and the dialog stack up on one another.

I've tried getting rid of the permissions on the manifest, but this removes all access of properly profiling the device.

I've tried to see if theres a way to auto deny these dialog permissions but soon discovered they are explicitly requested.

I've tried to see if there is any way to ask the permission later on in the app: through decompiling and looking through the common source to see if it asks for it on startup. I concluded that ConfigUtils, UIUtils and PermissionsUtils have no connection towards showing the permissions dialog on startup (Up to my knowledge however, ConfigUtils could still be suspect)

After exhausting all options that I know of, I come to ask this question: Is it possible to change it so it only shows up once or lazily demanded when I am actually using the cardboard interface?

Some more information:
Previously before integrating GoogleUnityActivity into our architecture layout, the app did ask for media/storage etc once, which was fine.

**Comment by smdol** [comment]
You can bypass this completely by setting the targetSDK in the manifest to 22 (Lollipop).  Then the user will be asked for permission during installation per the old method before Marshmallow.  Is this an option for you?

**Comment by apollow** [comment]
I'd love to, but unfortunately we get issues uploading to google play since our app version is already on  SDK 23. (It works for those of you looking in to this btw)

Is there any other way to suppress this dialog? Currently I think the permission dialog is necessary but the fact it can pop up multiple seems to be a bug of some sort with relation to requestPermissions(..), but I have no idea where in the code on Unity/Android side it may be in.

**Comment by smdol** [comment]
Can you check adb logcat to see if you are getting any errors posted during this process?  Also, is the app set up for landscape or portrait orientation?

**Comment by apollow** [comment]
The app is primarily portrait oriented.

Nothing out of the ordinary for errors up till the end of the 2nd dialog:
```
06-02 11:59:47.602 3896-3896/com.myapp.app E/MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@b3c2d93
06-02 11:59:47.612 3896-3896/com.myapp.app E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@13461d0
06-02 11:59:47.612 3896-3896/com.myapp.app E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@13461d0
06-02 11:59:48.302 3896-3896/com.myapp.app E/Sensors: ~SensorEventQueue 0
06-02 11:59:48.312 3896-3896/com.myapp.app E/Sensors: ~SensorEventQueue 0
```

I've made a diagram on how the app works, maybe there could be something useful here?
![stateforappopen](https://cloud.githubusercontent.com/assets/2719085/15758988/cc547574-28c1-11e6-97ba-d395ad13fc33.png)

**Comment by smdol** [comment]
After asking around internally, I hear that the GoogleVR (Cardboard) SDK doesn't ask for this permission (or any permission) at activity startup, only when the gear button is tapped. So I guess part of the problem is to figure out who/what is requesting it, in addition to how.
