### ISSUE TITLE
Skybox becomes black after resuming app on Nexus 6P

### ISSUE THREAD

**Issue by ayip6w** [googlevr/gvr-unity-sdk#236]
Hi, I have set my app's skybox material to a custom cubemap through the Rendersettings.skybox api. Everything works fine until focus out from the app and later focus back in. At this point, the skybox would be pure black.

The bug does not occur on the editor. Toggling multithreaded rendering (as some other related issues hinted at) doesn't help with the situation either. Can take a look?

**Comment by nathanmartz** [comment]
This is very likely to be a bug for Unity and is not specific to our SDK.
