### ISSUE TITLE
error CS0234 Audio does not exist in namespace 

### ISSUE THREAD

**Issue by rangerone8** [googlevr/gvr-unity-sdk#237]
Hi guys, 

I am getting the error on Unity "The type or namespace name 'audio' does not exist in the namespace 'Unity Engine'

I am quite new to this so I am not too sure how to solve the issue.

Thanks

**Comment by anokta** [comment]
@rangerone8 Which Unity version do you use? Please note that the UnityEngine.Audio namespace got introduced in Unity 5, and the Google VR SDK requires Unity 5.2+.
