### ISSUE TITLE
(escalate to level +1)IGvrGazeResponder implemented yet isinteractable is false

### ISSUE THREAD

**Issue by prasadxna** [googlevr/gvr-unity-sdk#238]
![image](https://cloud.githubusercontent.com/assets/18616283/15778401/a7f7bce8-29b3-11e6-8a4a-b09e015e1af2.png)

**Comment by prasadxna** [comment]
I figured that the object must also have Event Trigger Component to get is Interactive  to true.
I don't think this is how it should be done because i'm on comfortable having a component which is made for UI... If there is any neater way please let me know. BTW you can close it if you want.

**Comment by smdol** [comment]
Which script are you using to drive the gaze events, GazeInputModule.cs or GvrGaze.cs?

**Comment by prasadxna** [comment]
I think GazeInputModule cause im using GvrRetical Prefab from demo scene

**Comment by prasadxna** [comment]
So  want to bump this issue... Since i have both UI and Other game objects... So when i add GazeInputModule, GvrGaze stops working, when i remove InputModule the UI stops workign but the normal gaze objects start working. Please Dont tell me i have to add IGvrGazeResponder to all UI elements in order to use GvrGaze on UI element.

**Comment by Selzier** [comment]
Check the release notes for 0.6: 
"Support for gaze-based interaction, either with uGUI EventSystem or **independently** of it. Implement C# interfaces ICardboardGazePointer and/or ICardboardGazeResponder to interact with the gaze system."
[https://developers.google.com/vr/unity/release-notes#cardboard_sdk_for_unity_v06](https://developers.google.com/vr/unity/release-notes#cardboard_sdk_for_unity_v06)

I explain this process here: [https://youtu.be/NfG63Ge3aQk?t=8m36s](https://youtu.be/NfG63Ge3aQk?t=8m36s)

**Comment by nathanmartz** [comment]
Thanks for the great response, Selzier. Considering this closed...
