### ISSUE TITLE
Unable to find libaudioplugingvrunity

### ISSUE THREAD

**Issue by vladich** [googlevr/gvr-unity-sdk#239]
I'm using GvrAdapter to convert existing app to VR-ready and everything works fine in Editor, but when I deploy it to Android, I see this in the logs:
> D/Unity   (30652): Unable to lookup library path for 'libaudioplugingvrunity', native render plugin support disabled.
> E/Unity   (30652): Unable to find libaudioplugingvrunity

And render doesn't work indeed, I see only black screen with cardboard controls (divider and a gear button). Is there a way to fix it?

**Comment by smdol** [comment]
Did you upgrade from the Cardboard SDK to GoogleVR in this project?

**Comment by vladich** [comment]
No I didn't, I installed current VR SDK for the first time.

**Comment by smdol** [comment]
OK.  Check that you have the file libaudioplugingvrunity.so in Assets/Plugins/Android/libs/x86 and libs/armeabi-v7a.  Also, what's your phone model?

**Comment by vladich** [comment]
Yes, I have that file there, for both x86 and armeabi-v7a. I tried it on Nexus 5 and Samsung S6, had the same problem.

**Comment by vladich** [comment]
I'm wondering, is there a way to disable audio completely, so it won't even search for that plugin? I don't need to have audio there at all.

**Comment by smdol** [comment]
If you don't have any GvrAudioSource components in your scene, then the error is really just a log message.  It will have no effect on game play.  In that case, if you are getting a black screen, the problem may lie elsewhere.  Does the DemoScenes/HeadsetDemo sample scene work OK for you?

**Comment by vladich** [comment]
The part that was suspicious for me is "native render plugin support disabled.". If nothing got disabled then yes, it should be something else. Yes, we don't use GVR's audio components. And yes, HeadsetDemo is working fine on the device, but it's using GvrMain while we are using GvrAdapter.

**Comment by smdol** [comment]
I think audio message might be unrelated to the black screen problem.  The "native render plugin" message is referring to audio rendering.  Can you say how you hooked up GvrAdapter to the main camera?  (Mainly, do you have a StereoController on the main camera?)

**Comment by vladich** [comment]
Yes, I have StereoController on the main camera, and everything works fine in Editor, I see correct left/right eye pictures there. It only doesn't work on the device.

**Comment by vladich** [comment]
GvrAdapter is hooked up as a child of our MainCamera:
![image](https://cloud.githubusercontent.com/assets/1085964/15795661/920b072e-29a8-11e6-98f7-e2261e884a4a.png)

**Comment by vladich** [comment]
And that's on the MainCamera:
![image](https://cloud.githubusercontent.com/assets/1085964/15795718/126ef790-29a9-11e6-9276-86c32ec74454.png)

**Comment by smdol** [comment]
As a test, turn off VR Mode Enabled in the GvrViewer inspector.  You should see the scene in mono, and hopefully not just a black screen.

BTW, let's gather some other data:
-  What version of Unity?
-  Any significant changes to the Player Settings compared to the HeadsetDemo?

**Comment by vladich** [comment]
It turns out everything is working fine, we had some sort of race condition on our side, so it worked differently in Editor and on device. Apparently we still have a problem with libaudioplugingvrunity library, but since we are not using audio, it's all good.
Thank you for your help.
