### ISSUE TITLE
Got NSInvalidArgumentException exception running on iOS (iPhone 6 Plus)

### ISSUE THREAD

**Issue by vladich** [googlevr/gvr-unity-sdk#240]
> 2016-06-03 13:57:32.724 dev[2003:562792] +[GOOTypography isLargeForContrastRatios:]: unrecognized selector sent to class 0x1018edbc0
> 
> 2016-06-03 13:57:32.772 dev[2003:562792] Uncaught exception: NSInvalidArgumentException: +[GOOTypography isLargeForContrastRatios:]: unrecognized selector sent to class 0x1018edbc0
> 
> (
> 	0   CoreFoundation                      0x0000000185a54248 <redacted> + 160
> 	1   libobjc.A.dylib                     0x00000001977280e4 objc_exception_throw + 60
> 	2   CoreFoundation                      0x0000000185a5b1e0 <redacted> + 0
> 	3   CoreFoundation                      0x0000000185a580a8 <redacted> + 928
> 	4   CoreFoundation                      0x000000018595a96c _CF_forwarding_prep_0 + 92
> 	5   dev                                 0x000000010130c6c0 +[QTMColorGroup textColorOnColor:textAlpha:font:] + 68
> 	6   dev                                 0x000000010130d8e8 +[QTMColorGroup bodyTextColorOnColor:withFont:] + 104
> 	7   dev                                 0x00000001012e6934 -[GVROverlayView menuButtonWithTitle:image:placedBelowView:] + 644
> 	8   dev                                 0x00000001012e4854 -[GVROverlayView initWithFrame:] + 3288
> 	9   dev                                 0x00000001012e13d4 -[GVRUnityController init] + 104
> 	10  dev                                 0x00000001012e19ec createUiLayer + 88
> 	11  dev                                 0x00000001009f8c78 -[CardboardAppController createUnityView] + 92
> 	12  dev                                 0x0000000100036fc8 -[UnityAppController application:didFinishLaunchingWithOptions:] + 564
> 	13  UIKit                               0x000000018a542f78 <redacted> + 404
> 	14  UIKit                               0x000000018a75a654 <redacted> + 2376
> 	15  UIKit                               0x000000018a75d008 <redacted> + 1504
> 	16  UIKit                               0x000000018a75b578 <redacted> + 184
> 	17  FrontBoardServices                  0x000000018e28d3c8 <redacted> + 32
> 	18  CoreFoundation                      0x0000000185a0bfc8 <redacted> + 20
> 	19  CoreFoundation                      0x0000000185a0b0d0 <redacted> + 312
> 	20  CoreFoundation                      0x0000000185a096f4 <redacted> + 1756
> 	21  CoreFoundation                      0x0000000185934f74 CFRunLoopRunSpecific + 396
> 	22  UIKit                               0x000000018a53c224 <redacted> + 552
> 	23  UIKit                               0x000000018a536d94 UIApplicationMain + 1488
> 	24  dev                                 0x000000010002369c main + 156
> 	25  libdyld.dylib                       0x0000000197dd2a08 <redacted> + 4
> )
> 
> 2016-06-03 13:57:32.773 dev[2003:562792] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[GOOTypography isLargeForContrastRatios:]: unrecognized selector sent to class 0x1018edbc0'
> 
> *** First throw call stack:
> (0x185a5422c 0x1977280e4 0x185a5b1e0 0x185a580a8 0x18595a96c 0x10130c6c0 0x10130d8e8 0x1012e6934 0x1012e4854 0x1012e13d4 0x1012e19ec 0x1009f8c78 0x100036fc8 0x18a542f78 0x18a75a654 0x18a75d008 0x18a75b578 0x18e28d3c8 0x185a0bfc8 0x185a0b0d0 0x185a096f4 0x185934f74 0x18a53c224 0x18a536d94 0x10002369c 0x197dd2a08)
> 
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vladich** [comment]
I can help with debugging if you have any idea what to look for here.

**Comment by smdol** [comment]
I'll ask one of our iOS people, but I think the first thing they will want to know is if you have -ObjC in the linker flags of the Xcode project.

**Comment by vladich** [comment]
No I don't have it there

**Comment by smdol** [comment]
Try adding it.  The last few times I've seen the "unrecognized selector" error happen is was because -ObjC was needed.  Side note:  Our SDK as of v0.7 tries to add this flag to the Xcode project automatically, so I'm surprised it is not there.

**Comment by vladich** [comment]
Thanks, it started linking correctly after I added -ObjC. I had to add a link to GLKit.framework too.
The reason -ObjC is not there is probably that we are porting existing app that has a custom build script that customizes Xcode project for our purposes, so it might be different from what you do in case of a regular build. Also, the project is building fine, but it still doesn't work correctly, it shows something very weird, like some blurred text or something like that. Maybe our build is still off. Can you specify what compilation / linking parameters should Xcode project have to work properly with GVR?

**Comment by smdol** [comment]
For reference, here's the code in Unity that modifies the Xcode project:

https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Editor/GvrViewerEditor.cs#L119

See the link for the specific changes made.  If you include these same modifications via your script, you are good to go.
