### ISSUE TITLE
Compiler Error On Load

### ISSUE THREAD

**Issue by ParsaRt** [googlevr/gvr-unity-sdk#242]
hi , so i just downloaded the google cardboard sdk but it has some compiler errors !

here are they :

-The type System.Diagnostics.ProcessStartInfo' does not contain a constructor that takes 2' arguments

--Property or indexer System.Diagnostics.Process.StartInfo' cannot be assigned to (it is read only) ---Type System.Diagnostics.Process' does not contain a definition for Close' and no extension method Close' of type `System.Diagnostics.Process' could be found (are you missing a using directive or an assembly reference?)

and as i checked , these are some unlogical silly errors ! does anyone have the same problem ? can you show me how to fix it ?

**Comment by ParsaRt** [comment]
Really ?! Still no answer google ?

**Comment by smdol** [comment]
This happens when the build target is WebPlayer, which is obsolete.  Open the Build Settings dialog and select Android or iOS as the build target.

**Comment by felladil3** [comment]
i has an auther compiler error but i installed this it run good now
https://unity3d.com/fr/partners/google/daydream#section-download
