### ISSUE TITLE
Is it okay with Unity 5.3.5f1?

### ISSUE THREAD

**Issue by Cianjoo** [googlevr/gvr-unity-sdk#243]
I am working on google vr with Unity 5.3.5f1.
actually I am okay with 5.3.4f1, but I met not found issue about unitygvractivity after upgrade unity.
when I use export, unity maked different project for unitygvractivity and gvr_android_common.
then I import this to android studio.... and I met this issue.
anyway I used build on unity tool, it is okay..
I just want know how can I fix this issues..or.. gvr-unity-sdk is not yet supported 5.3.5f1?
Thanks,

**Comment by nathanmartz** [comment]
The Google VR SDK for unity should work just fine on 5.3.5.

**Comment by Cianjoo** [comment]
yes, I am fixed~thanks
2016. 6. 14. 오전 12:39에 "nathanmartz" <notifications@github.com>님이 작성:

> The Google VR SDK for unity should work just fine on 5.3.5.
>
