### ISSUE TITLE
Source code for the Controller Emulator APK

### ISSUE THREAD

**Issue by polats** [googlevr/gvr-unity-sdk#244]
Hi!

I've been trying to use 2 remotes simultaneously on the ControllerDemo (1 using USB, and 1 using Wifi) but I was stopped by the emulator APK always connecting to port 7003. Is the controller source code available? Also, will Daydream actively support more than 1 remote?

My code changes here:

https://github.com/polats/gvr-unity-sdk/commit/d42a194d88154fbac97aabb5d64f25be1bdb43c1

Relevant requests:

http://stackoverflow.com/questions/37402162/how-can-i-modify-troubleshoot-the-google-vr-daydream-controller-emulator?newreg=03252859fcac412fb71cf7b698d5d332

https://plus.google.com/u/1/110588989236418175249/posts/eATwMv2wTha

**Comment by nathanmartz** [comment]
Hi. We will not support more than one controller at a time for Daydream.

**Comment by polats** [comment]
Noted, thanks! Hope you'll consider it for future versions; multiple / custom controllers would allow us to create additional interactions :D

**Comment by baymac** [comment]
Can you post the source code of daydream controller emulator?
