### ISSUE TITLE
CommandInvokationFailure Build Failure

### ISSUE THREAD

**Issue by rferrese** [googlevr/gvr-unity-sdk#245]
I am unable to get the GoogleVRForUnity.unitypackage project to build using either Unity 5.3.2 or Unity 5.4.0b21.

The steps that I followed were 1) Create a new project 2) import the unitypackage 3) switch to Android 4) change the bundle identifier & orientation 5) build  (as outlined here: https://developers.google.com/vr/unity/get-started-controller#import_and_preview_the_demo_scene)

I am using:
- The latest from github (v0.8.1)
- jdk1.8.0_91
- Up to date Android Studio installed (2.1)
- Android 6.X (N) API 24 Rev 1 SDK installed

![image](https://cloud.githubusercontent.com/assets/5903547/16169174/5ae92136-34d9-11e6-9655-f3108077fc83.png)

![image](https://cloud.githubusercontent.com/assets/5903547/16169178/6fb34f9c-34d9-11e6-883a-a8c5e727db87.png)

The error that I get is this:

> CommandInvokationFailure: Failed to re-package resources.
> C:\Users\Robert\AppData\Local\Android\sdk\build-tools\24.0.0\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/Robert/AppData/Local/Android/sdk\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages com.google.vr.cardboard:vr.gvr.platform.unity -S "C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res" -S "C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\unitygvractivity\res"
> 
> stderr[
> 
> ]
> stdout[
> Configurations:
>  (default)
> 
> Files:
>   AndroidManifest.xml
>     Src: () AndroidManifest.xml
> 
> Resource Dirs:
> Including resources from package: C:\Users\Robert\AppData\Local\Android\sdk\platforms\android-24\android.jar
> applyFileOverlay for drawable
> trying overlaySet Key=ic_settings_48dp.png
> trying overlaySet Key=quantum_ic_arrow_back_white_24.png
> trying overlaySet Key=quantum_ic_arrow_downward_white_24.png
> trying overlaySet Key=quantum_ic_arrow_upward_white_24.png
> trying overlaySet Key=quantum_ic_settings_white_24.png
> trying overlaySet Key=rippleable.xml
> trying overlaySet Key=transition.png
> trying overlaySet Key=app_banner.png
> trying overlaySet Key=app_icon.png
> applyFileOverlay for layout
> trying overlaySet Key=back_button.xml
> trying overlaySet Key=transition_view.xml
> trying overlaySet Key=ui_layer.xml
> trying overlaySet Key=ui_layer_with_portrait_support.xml
> applyFileOverlay for anim
> applyFileOverlay for animator
> applyFileOverlay for interpolator
> applyFileOverlay for transition
> applyFileOverlay for xml
> applyFileOverlay for raw
> applyFileOverlay for color
> applyFileOverlay for menu
> applyFileOverlay for mipmap
> Processing image: res\drawable-xhdpi\app_banner.png
> Processing image: res\drawable\app_icon.png
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable\ic_settings_48dp.png
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_arrow_back_white_24.png: 154% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_arrow_back_white_24.png: 138% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quantum_ic_arrow_back_white_24.png: 129% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxhdpi-v4\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable\ic_settings_48dp.png: 172% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxxhdpi-v4\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxhdpi-v4\quantum_ic_arrow_back_white_24.png: 136% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-mdpi-v17\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-mdpi-v17\quantum_ic_arrow_back_white_24.png: 152% size of source)
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxxhdpi-v4\quantum_ic_arrow_back_white_24.png: 113% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-hdpi-v17\quantum_ic_arrow_back_white_24.png
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-xhdpi-v17\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-hdpi-v17\quantum_ic_arrow_back_white_24.png: 140% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-xxhdpi-v17\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-xhdpi-v17\quantum_ic_arrow_back_white_24.png: 122% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-xxxhdpi-v17\quantum_ic_arrow_back_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-xxhdpi-v17\quantum_ic_arrow_back_white_24.png: 133% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_arrow_downward_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-ldrtl-xxxhdpi-v17\quantum_ic_arrow_back_white_24.png: 109% size of source)
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_arrow_downward_white_24.png: 146% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_arrow_downward_white_24.png
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quantum_ic_arrow_downward_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_arrow_downward_white_24.png: 142% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxhdpi-v4\quantum_ic_arrow_downward_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quantum_ic_arrow_downward_white_24.png: 147% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxxhdpi-v4\quantum_ic_arrow_downward_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxhdpi-v4\quantum_ic_arrow_downward_white_24.png: 135% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_arrow_upward_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_arrow_upward_white_24.png: 130% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_arrow_upward_white_24.png
>     (processed image C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_arrow_upward_white_24.png: 141% size of source)
> Processing image: C:\Users\Robert\Documents\GitHub\DaydreamTest\Test2\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quan
> ]
> UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
> UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg)
> UnityEditor.Android.PostProcessor.Tasks.BuildResources.CompileResources (UnityEditor.Android.PostProcessor.PostProcessorContext context)
> UnityEditor.Android.PostProcessor.Tasks.BuildResources.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
> UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
> UnityEditor.HostView:OnGUI()
>

**Comment by Pivetta** [comment]
I am running into the same Issue:
I didn't have stored all my debug data.

Tested on unity 5.3.4 and unity 5.3.5:

Unity wont build with the 24 build tools giving the re-packing issue (with or without cardboard)
Cardboard requires the 24 build tools if not it fails saying that the tools are not uptodate with the current version.

**Comment by jeremyfpope** [comment]
Try downgrading the Android SDK Build-tools to 23.0.3.  Seems to have solved the issue for me.

**Comment by nathanmartz** [comment]
Good news!
