### ISSUE TITLE
How to Use effects ?

### ISSUE THREAD

**Issue by nantianliao** [googlevr/gvr-unity-sdk#247]
If the lens effect on the left and right sides of the eye, the left and right sides of the screen will become abnormal. Such as this effect: BloomOptimized.
What should I do to solve this problem?

**Comment by nathanmartz** [comment]
In general, we do not recommend full screen post effects for mobile VR scenes. They are too heavy to be practical. Technically they will work when we release our native integration of Daydream and Cardboard into Unity later this year, but it still won't be a great choice for most apps.
