### ISSUE TITLE
Canvas Menu's not displaying anymore.

### ISSUE THREAD

**Issue by whizzkid** [googlevr/gvr-unity-sdk#248]
STR: create new project, import googleVR package,  open GoogleVR/DemoScenes/HeadSetDemo/DemoScene
run it.. look at the floor.   no menu there.

It will appear when you turn off VR mode in GvrMain. but usually you want to see it in VR mode.

**Comment by nathanmartz** [comment]
This is a known bug in Unity in the interaction between render textures and their UI system. I'm sorry but there's nothing we can do to fix it as it's not a problem with the SDK proper.

**Comment by smdol** [comment]
Unity 5.3.4f1 and earlier do not have the problem.

**Comment by whizzkid** [comment]
a note in the comment in the code or readme would be very helpful.   it would've saved me a lot of time trying to figure out what was wrong.

**Comment by smdol** [comment]
It's posted here:
    https://developers.google.com/vr/unity/release-notes#known_issues

**Comment by momo-the-monster** [comment]
This is fixed in 5.3.6, let's hope that's released soon!
