### ISSUE TITLE
Couldn't open Assets/Plugins/x86_64/audioplugingvrunity.bundle

### ISSUE THREAD

**Issue by fsereno** [googlevr/gvr-unity-sdk#250]
Using Unity 5.3.5, Xcode 5 and Mountain Lion OSX. When trying to follow the Google Cardboard VR SDK guidelines and when running the HeadsetDemo I get the error ...

Couldn't open Assets/Plugins/x86_64/audioplugingvrunity.bundle

The dll is clearly in place, but this error continues to show.

Please can someone who has experienced this issue already, as I see it has come up before, but no solution put forward.

I would really appreciate some help. I am new to Unity also, so please do explain any solutions.

Many thanks

Fabio

**Comment by anokta** [comment]
@fsereno Are you experiencing this issue in the Unity Editor (Play mode) or when you build your app on different platforms? Could you also verify if you have an 64-bit MacOS? Please note that we don't support 32-bit systems on Mac.

**Comment by fsereno** [comment]
Thank you very much for coming back to me. I am running Mountain Lion on an i7 processor at 64 bits.

I took another look at the error I was getting and it does seem slightly different to what i first thought. It actually reads this...

Couldn't open Assets/Plugins/x86_64/audioplugingvrunity.bundle, error: dlopen(Assets/Plugins/x86_64/audioplugingvrunity.bundle, 2): Symbol not found: ___sincos_stret
  Referenced from: Assets/Plugins/x86_64/audioplugingvrunity.bundle
  Expected in: /usr/lib/libSystem.B.dylib
 in Assets/Plugins/x86_64/audioplugingvrunity.bundle

This happens the moment i have finished importing the google vr unity sdk. I am not able to play the project, and when I try to build I get many more errors, I am assuming these are caused by the issue with initial import of the gvr_unity_sdk.

I am following the steps here 
https://developers.google.com/vr/unity/get-started-android

**Comment by smdol** [comment]
It appears that ___sincos_stret was introduced in Mavericks, according to this SO comment:

http://stackoverflow.com/a/19017286/4372377

I don't think we've officially declared a minimum OSX version that our dylibs will run on, so this probably just was happenstance since internally we are all running more recent versions.

**Comment by fsereno** [comment]
Thanks very much @smdol for getting back to me. That is good news to some degree, as I was wondering if it was a wider issue with my environment and not something little that I have missed.

I have tested all steps on OSX 1.9.4 and the error is no longer there, and I can build the project. I haven't tried to export to device yet, but the build is successful! 

Based on this I am happy to close this issue.

Many thanks

Fabio
