### ISSUE TITLE
Cardboard error on Xcode: library not found for -lgvrunity

### ISSUE THREAD

**Issue by amitchai** [googlevr/gvr-unity-sdk#251]
Hi i've built the project on my pc and m getting this error on xcode on my mac:

ld: warning: directory not found for option '-L/Users/amitchai/Desktop/ver2/LibrariesPlugins/iOS'
ld: library not found for -lgvrunity
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please Help!

**Comment by tolotratlt** [comment]
exactly the same problem

**Comment by amitchai** [comment]
Eventually I build it in my mac (instead of my pc...) so this solved the problem. partially,

**Comment by Retina-Design** [comment]
I solved it by adding "$(SRCROOT)/Libraries/Plugins/iOS" (with quotes) to the Library Search path in XCode. (If it is already there, check if it has quotes around it.)

**Comment by linojon** [comment]
Check for back slashes instead of forward slashes in the libraries search paths, and fix before building. This happens when i build the project on Unity Windows then use Xcode on mac to complete the build.

**Comment by nathanmartz** [comment]
Thanks for the info, folks. Pretty sure this is a Unity bug, not in our SDK, so closing the issue.
