### ISSUE TITLE
Button (script) - On Click not working: we must use event trigger

### ISSUE THREAD

**Issue by chelder86** [googlevr/gvr-unity-sdk#252]
Hi. If we use the On Click of the Button (script) component, it won't work. We must remove it and add a Event Trigger component like we can see in the screenshot below.

![screen shot 2016-07-05 at 01 21 40](https://cloud.githubusercontent.com/assets/3020189/16570862/2a914bc0-424f-11e6-9bb6-e7a0167b147d.png)

It would be cool we could use the On Click of the Button (script). It was very confusing in the past, and sometimes I still forget.

Have a good night! Or day!

**Comment by miraclestar** [comment]
I got this error too. anyone knows how to resolve?

**Comment by smdol** [comment]
What version of Unity are you using?

**Comment by miraclestar** [comment]
I use 5.3.2f1

**Comment by papabew** [comment]
I use 5.3.6f1. Event Trigger replaced the functionality of OnClick() using PC.
