### ISSUE TITLE
Loading 3D slower once GvrViewer is instantiated and remains slow after GvrViewer destroyed

### ISSUE THREAD

**Issue by peterept** [googlevr/gvr-unity-sdk#253]
I am switching on/off GoogleVR as needed, and in my app I load 3D content from asset bundles. Typically content might take say ~1/2 second to load. 

As soon as I have instantiated a GvrViewer in my scene, from that moment my content takes ~3 seconds to load. Destroying the GvrViewer has no change - loading content forever is slow at ~3 seconds. 

It happens even if I don't actual create the GvrHead to view cardboard.

This was happening on Cardboard 0.7, and I updated to 0.81 and no change. 

Unity version 5.3.5f1. Testing on IPad Air. 

Anyone else seen anything like this? 

Is it hooking into something that is not cleaned up?

**Comment by nathanmartz** [comment]
Can you post a screenshot of the profiler attached to your application when
things are slowing down?

**Comment by peterept** [comment]
I have found the root cause of this now.

The reason is that in `GoogleVR/Scripts/GvrViewer.cs` the targetFrameRate is locked to 60 FPS, but never restored after VR is shutdown:

```c#
void Awake() {
...
#if UNITY_IOS
    Application.targetFrameRate = 60;
#endif
...
}
```
Setting that in my app has the side-effect of slowing down our 3d loading code

**Comment by smdol** [comment]
Great catch!  We put that line in as a backstop to prevent 90% of developers from accidentally running at 30Hz on iOS (the default), which is really too slow for VR.  A better location for it would probably be in this function:

https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Legacy/Scripts/Internal/VRDevices/iOSDevice.cs#L36
