### ISSUE TITLE
Way to completely unload GVR libraries after destroying GvrViewer.Instance?

### ISSUE THREAD

**Issue by abutt1** [googlevr/gvr-unity-sdk#255]
On iOS (haven't tested Android as of yet), we've been seeing some performance issues after loading the GvrViewer.

After we destroy the GvrViewer.Instance, the performance never seems to improve. We've been looking through the code, and have manually called device.Stop() after destroying the GvrViewer but it appears to have no effect.

Is there any way to completely 'destroy'/shutdown native code after destroying the GvrViewer? From what I can tell, it doesn't appear as if the Stop call actually shuts down and destroys the native code. Our app doesn't require VR all the time, so we'd really appreciate the ability to shutdown vr completely when not required.

Are we just missing something obvious? We're using the latest code from the master branch (0.8.5).
Thanks

**Comment by nathanmartz** [comment]
Have you profiled the app to see where the time is going? There should be
very minimal if any impact on your system after shutting down the GVR
system.

**Comment by abutt1** [comment]
Apologies for the delayed response. Issue appeared to be related to the targetFrameRate being set to 60 fps by the GvrViewer. If we reset our targetFrameRate to 30 (that's what we were using beforehand), our app behaved as expected.

It would be great if the viewer reset the targetFrameRate when it destroyed itself.
