### ISSUE TITLE
Is there a way to disable the instructions?

### ISSUE THREAD

**Issue by Retina-Design** [googlevr/gvr-unity-sdk#257]
Is it possible to disable the instructions that appear when ever I enable the Gvr viewer?

**Comment by nathanmartz** [comment]
The behavior is by design so that users understand how to put the device into the viewer. Do you have a similar screen of your own?

**Comment by Retina-Design** [comment]
Exactly. We made an animation with a customized cardboard, designed for our customer. Unfortunately he insits to have a cardboard with his colours instead of the orange one provided with the sdk.

**Comment by nathanmartz** [comment]
Thanks for the information. I'm looking into what we can do, but TBH I don't think we'll be able to change this behavior quickly.
