### ISSUE TITLE
IOS google cardboard / gvr wired screen size issue.

### ISSUE THREAD

**Issue by oscarmore2** [googlevr/gvr-unity-sdk#258]
Hi guys.

I encounter wired screen issue. It can't able to render properly. I tried on Iphone 5 and Iphone 6 has the same problem.

## the setup of my google cardboard:
* GvrMain / CardboardMain `Screen Size` property: `Iphone 6`
* Gvr version : `0.8.1`, Cardboard version: `0.6.0` (Yes, both version has same problem)
* Unity version: `5.3.2`

## error screenshots (captured from Iphone 6)
 <img src="https://raw.githubusercontent.com/oscarmore2/gvr-unity-sdk/error-screen-shot/444209424040414771.jpg" />
 <img src="https://raw.githubusercontent.com/oscarmore2/gvr-unity-sdk/error-screen-shot/662112152376113758.jpg" />
 <img src="https://raw.githubusercontent.com/oscarmore2/gvr-unity-sdk/error-screen-shot/745583568216079016.jpg" />

**Comment by smdol** [comment]
Can you make sure that you are forcing the app to Landscape mode in Unity's build settings?  For Mac, we recommend doing this by leaving the Default Orientation at Auto, but removing the Portrait modes from the Allow Orientations list.

**Comment by oscarmore2** [comment]
For my project, it could use portrait only because out side of the vr scene, it's portrait layout. But I solved this problem, by forcing the Unity screen to landscape before enter the VR scene. Thanks.

**Comment by nathanmartz** [comment]
Ok. Great. Glad you got it sorted.

**Comment by cajohnson99** [comment]
@oscarmore2 Could you provide some additional detail on your solution? I'm still seeing this issue when using:

`Screen.orientation = ScreenOrientation.Landscape;`
`gvrViewer.VRModeEnabled = true;`

Reloading the scene every time the device orientation is changed isn't an option for me.

Thanks
