### ISSUE TITLE
Wrong Stereo Vision

### ISSUE THREAD

**Issue by jorgeolothar** [googlevr/gvr-unity-sdk#259]
I recently upgraded to version 0.81 to have drift correction. I built my Unity project and everything was good. I rebuilt my project with minimal text changes but now the Cardboard screen output seems wrong. There's no cogwheel to access setup, and the proportions of the two screens look wrong, almost like cat eyes instead of rounded squares. See images for reference

Regular Cardboard App (my screen used to look like this)
![regular cardboard app](https://cloud.githubusercontent.com/assets/9650728/16749744/38c017a6-4792-11e6-9a74-3f1b0b8d5882.jpg)

My App after 0.81 rebuilding
![my app after 0 81](https://cloud.githubusercontent.com/assets/9650728/16749749/3de4a260-4792-11e6-825a-eaa0e729a79f.jpg)

This is happening on Android. What could be causing this? I used to have a previous version, but deleted it as per upgrade instructions, deleted the plugins folder and reimported.

**Comment by nathanmartz** [comment]
Did you delete your old SDK before installing the new one? bad things often
happen when you don't delete the old SDK first.

**Comment by jorgeolothar** [comment]
I deleted the Cardboard/ and Plugins/ folders. Was there anything else to delete?

**Comment by jorgeolothar** [comment]
I also went ahead and deleted everything again, installed version v0.8.5, deleted prefabs cameras and replaced with GvrViewerMain instance. Problem still persists.

**Comment by jorgeolothar** [comment]
Found the issue. Main activity extended "com.unity3d.player.UnityPlayerActivity" instead of "com.google.unity.GoogleUnityActivity". Until v0.8.1 this had been a recoverable issue, logcat showed that the app did throw errors, but recovered into VR mode.
