### ISSUE TITLE
Why do we need to two audio clips for GvrAudioSoundField?

### ISSUE THREAD

**Issue by xdf103** [googlevr/gvr-unity-sdk#261]
The GvrAudioSoundField needs two audio clips, one for channels 1 & 2, and the other for channels 3 & 4. Can we use the same audio file (4 channels FOA ambisonic) for both audio clips? Or must we split this file into two audio files, each with 2 channels?

**Comment by nathanmartz** [comment]
You have to split it into two files with two channels each. There are
issues in Unity that prevent us from supporting a single, 4 channel file.

**Comment by xdf103** [comment]
Thank you! We will be downloading ambisonic file (4 channel) from the web. Is there any way to break it into two audioclip, each with 2 files? Some sample codes will be great.

**Comment by smdol** [comment]
That's an audio file processing problem.  You want to look for audio tools like Audacity or ffmpeg to help with that, as it's out of our scope.
