### ISSUE TITLE
GvrViewer rotates Camera

### ISSUE THREAD

**Issue by jorgeolothar** [googlevr/gvr-unity-sdk#262]
Given an initial Camera.main orientation, GvrViewerMain will reset it and set it to (0,0,0). You can test this in the HeadsetDemo scene. I think the rotation of main interest is in the y-axis (player orientation rather than head rotation).

While you could rotate everything around the camera as a temporary fix, this does not work with terrains, which are optimized not to be rotated.

Is there a temporary fix?

**Comment by miraleung** [comment]
Thanks for your feedback! Resetting the camera orientation is working as intended, so if you would like to change it, please make it a child of another GameObject with the desired orientation. 

Hope this helps!

**Comment by lebalrog** [comment]
That helped, thanks
