### ISSUE TITLE
Can't see geometry with VR mode disabled

### ISSUE THREAD

**Issue by Enumio** [googlevr/gvr-unity-sdk#264]
Hello, I am trying to find if somebody has similar problem but no go.

I am using Cardboard SDK 0.6 still, i know it is a bit outdated but I am far too deep in the project to update SDK now. 

What I'm experiencing is everything is fine when the VR mode is ON but when i disable it all i can see is my skybox, UI, and geometry that has textures with alpha. Regular geometry with textures without alpha is just gone. I tried switching shaders but the result is the same . 

Has anyone experienced the same bug and does anyone know why is that happening?

**Comment by Enumio** [comment]
Okay i solved it. The problem was in the build settings. I had depth buffer and stencil disabled. I enabled it and now it is ok.

Should anyone care...

**Comment by miraleung** [comment]
[Thanks](https://xkcd.com/979/) for posting your solution!
