### ISSUE TITLE
0.8.5 [GOOTypography robotoMediumWithSize:] error when building iOS

### ISSUE THREAD

**Issue by arturleao** [googlevr/gvr-unity-sdk#267]
Seems to be a regression, fixed it with adding "-ObjC" to "Other Linker Flags"

**Comment by nathanmartz** [comment]
This is actually expected.

**Comment by arturleao** [comment]
Could you give further information on this? I've seen in the code that there is a PostBuild method that takes care of this but seems that its not working, so what you're saying is that building failing on iOS is what's expected?

**Comment by nathanmartz** [comment]
Obviously failing to build on iOS is not expected. I suspect this is a bad
interaction between the GVR SDK and another plugin you have installed. What
other plugins are your using? Do any have post-build steps?

**Comment by smdol** [comment]
Here's the line in our post-build method that adds -ObjC:

https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Legacy/Editor/GvrViewerEditor.cs#L103

If you aren't seeing that in the resulting Xcode project, the next step is to figure out if this function is being executed -- maybe a Debug.Log call.  It works for us internally.  Last version of Xcode I used when testing was 7.2 -- 7.3 caused compilation errors in Unity-generated code.

**Comment by arturleao** [comment]
Ok, I've just looked at the code and the thing is I'm building for iOS but on Windows, the compiler directive #UNITY_IOS doesn't make much sense since it will never be run I think.

This should be more than enough and maybe removing the compiler directive should fix it:
https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Legacy/Editor/GvrViewerEditor.cs#L94

**Comment by smdol** [comment]
Very strange!  I am typically building on Mac these days, and the UNITY_IOS guard does seem to work.  Here's the list of directives Unity understands:

http://docs.unity3d.com/Manual/PlatformDependentCompilation.html

Where it says:
UNITY_IOS	#define directive for compiling/executing code for the iOS platform.

Although if the platform check on that line you linked to turns out to be sufficient we can make the change regardless.

**Comment by arturleao** [comment]
So I went back and look at my own build process code and figured out something was preventing the GVR post build process to run properly, I've now fixed it, all is good, thanks for all the feedback. No regression, no bug, just me doing something stupid :)

**Comment by danteangeles** [comment]
What did you do/ I am having the same issue when using firebase sdk with googleVR. When googleVR alone it works well, when firebase alone it works well too, but together the app crash saying [GOOTypography robotoMediumWithSize:] . I am using xcode 8.2.1 please help me.
