### ISSUE TITLE
GvrController.Accel is not Linear Acceleration.

### ISSUE THREAD

**Issue by vitorbalbio** [googlevr/gvr-unity-sdk#268]
Hi.
Today using the controller emulator i notice that the GvrController.Accel return the acceleration with gravity what is almost useless without a lot of math on it to get the Linear Acceleration. In the final controller we can get the linear acceleration also? The IMUs return it almost for free in the Sensor Fusion so please give it to us. ;)
Bye!

**Comment by miraleung** [comment]
We currently return what Unity gives us, which is the accelerometer value. However, we may consider adding linear acceleration in a future release. 

In the meantime, please continue to remove the gravity vector mathematically.

Thanks for your feedback!

**Comment by vitorbalbio** [comment]
Hi miraleung,
Thanks for you reply.
Regards
