### ISSUE TITLE
Unable to find libaudioplugingvrunity

### ISSUE THREAD

**Issue by alimoeeny** [googlevr/gvr-unity-sdk#269]
At run time, build for android, I get 
`Unable to find libaudioplugingvrunity `
and then
```
Error: Cannot create FMOD::Sound instance for resource sharedassets0.resource, (File not found. )    
Function SoundHandle::Instance::~Instance() may only be called from main thread!
```
and the unity scene crashes.
Surprisingly a 

``` java
static {
		System.loadLibrary("audioplugingvrunity");
}
``` 
does not fail, which leads me to believe, somewhere in one of the binaries there is a hardcoded reference to `libaudioplugingvrunity` instead of `audioplugingvrunity`

Does this make sense?

**Comment by smdol** [comment]
The "Unable to find libaudioplugingvrunity" message is Unity's output. This message has been seen for some time, but apparently has no actual effect on the plugin's behavior.  It includes the "lib" prefix, which is implied in the System.loadLibrary argument, so those are actually the same underneath.  

The crash is most likely related to the FMOD message, which looks like it is a thread-related problem.

**Comment by alimoeeny** [comment]
Thanks @smdol . So since I don't have any audio code on my side, I mean my scripts does not call any audio related objects, I assume this is still something internal to GoogleVR , or caused by the interaction between unity and the gvr library. Is that correct?

**Comment by nathanmartz** [comment]
I think this crash is unrelated to our plugin. We don't call any FMOD code
directly. Does this crash still repro if you remove our plugin? I would
think it does not?

-Nathan

**Comment by alimoeeny** [comment]
Thanks @nathanmartz and @smdol 
Yep, looks like you are correct, removing the `gvr` gets ride of the first error message but not the second one. 
So the `audioplugingvrunity` thing is a red herring. 
Thank you.

**Comment by alimoeeny** [comment]
For people who may search for this problem and end up here, the solution (originally from here: http://answers.unity3d.com/questions/919272/sound-files-not-included-in-android-apk-1.html) is to make sure in Unity, in your Player settings under Android under "publishing settings" the checkbox for "Split Application Binary" is NOT set (should be unchecked for the error to go away).
