### ISSUE TITLE
Cardboard UI Overlay launched faster then actual scene

### ISSUE THREAD

**Issue by CAMOBAP795** [googlevr/gvr-unity-sdk#270]
Original post form [here](http://answers.unity3d.com/questions/985083/unity-cardboard-bug-on-nexus-6-ui-of-previous-scen.html)

---

My first scene is a non-Cardboard-VR scene contains U.I dropdown list and confirm button.

When I execute loadLevel() to the Cardboard VR scene, my previous scene's U.I will still be remained on the view, in corrupted form, behind the rectangular VR cameras, like this one:

![48053-screenshot-2015-06-12-14-37-11](https://cloud.githubusercontent.com/assets/2169738/17014980/46014386-4f30-11e6-9bb5-f0111123d9cf.png)

![48054-screenshot-2015-06-12-15-21-46](https://cloud.githubusercontent.com/assets/2169738/17014982/47c828ba-4f30-11e6-95c9-f2a2c1198cd8.png)

I try to use "hacked way" - destroy game objects before loadLevel executes, but the problem remains still.

This bug is only happen on Nexus 6. I built my this VR app on Moto G, Samsung Note 2, Note 3, Nexus 4, Nexus 5 and Nexus 6.

Seems like it is a Cardboard rendering bug.

**Comment by nathanmartz** [comment]
Do you notice the issue when you are looking at the phone through a viewer?
Most likely you do not. Also, make sure that your camera is set to clear to
a color. It may be that it's set to skip the clear entirely.

**Comment by smdol** [comment]
Which version of the SDK are you using?  The script GvrPreRender was added to the SDK to fix this bug, since the two eye regions only clear their own portions of the screen.

**Comment by CAMOBAP795** [comment]
> Which version of the SDK are you using?
I used this one https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVRForUnity.unitypackage (according change log it wasn't changed 24 days)

>  The script GvrPreRender was added to the SDK to fix this bug, since the two eye regions only clear their own portions of the screen.
Yes I have it `/Assets/GoogleVR/Legacy/Scripts/Internal/GvrPreRender.cs`.

Another important detail which I missed, my second scene are heavy (~100k vertices, ~80 triangles), but I load it async.

**Comment by smdol** [comment]
Check that GvrPreRender is getting set up properly and is enabled in your scene.  Its camera is the one that clears the entire screen.  In older versions of the SDK it was part of the GvrMain prefab.  In the most recent version, it is created at start time by GvrViewer.
