### ISSUE TITLE
unity-CardboardDesignLab,add distortion-unity,but the ui is running in iphone is upside down 

### ISSUE THREAD

**Issue by wonderful007** [googlevr/gvr-unity-sdk#272]
@dav-cz  

1. I try to run the samples/CardboardDesignLab/ustwo-cardboard-unity demo.
2. I just checked distortionCorrection-unity
3. Put it into the apk，it is running normally in android devices.
4. but ,the same code, build and run in iphone is upside down,I only changed the distortionCorrection.
5. Please Help me,thanks very much.
![lala](https://cloud.githubusercontent.com/assets/9334365/17075420/4df69b5e-50c5-11e6-803f-64ced374f68f.jpg)

**Comment by wonderful007** [comment]
@jkammerl  @google-admin @miraleung please help me

**Comment by smdol** [comment]
Cardboard Design Lab uses vertex displacement distortion, which is done in the shaders, so you should set the distortion method to None rather than Unity.
