### ISSUE TITLE
Strange Behavior with Distortion Shader and Static Batch

### ISSUE THREAD

**Issue by vitorbalbio** [googlevr/gvr-unity-sdk#273]
Hi.
I'm getting some strange behaviors using or not static batch into a simple scene with the vertex distortion shader. This contains 3 trees with the same transform. So They are overlapped. They are set to Static Object.

With Static Batch Off
[http://puu.sh/qbWDF/58637654cb.jpg](url)

Static Batch On and all three are activated
[http://puu.sh/qbWFV/e329a9fb66.jpg](url)

Static Batch On but only one activated
[http://puu.sh/qbWQO/09bd39b354.jpg](url)

It means that only using the static batch on and only when more than one object of the same are in the scene that it works as it should be (only when static batch really activate).

I'm using Unity3D 5.3.5p5

Here's the shader used:
`Shader "Diffuse Distort" {
Properties {
	_MainTex ("Base (RGB)", 2D) = "white" {}
}
SubShader {
	Tags { "RenderType"="Opaque" }
	LOD 150

CGPROGRAM
#pragma surface surf Lambert noforwardadd vertex:vert
#pragma multi_compile __ GVR_DISTORTION
#include "GvrDistortion.cginc"

sampler2D _MainTex;

struct Input {
	float2 uv_MainTex;
};

void vert(inout appdata_full v) {
	v.vertex = undistortSurface(v.vertex);
}

void surf (Input IN, inout SurfaceOutput o) {
	fixed4 c = tex2D(_MainTex, IN.uv_MainTex);
	o.Albedo = c.rgb;
	o.Alpha = c.a;
}
ENDCG
}
}`

**Comment by smdol** [comment]
There is a bug in undistortSurface that is not in undistortVertex.  Brian Kehrer pointed it out to me recently.  Basically, the bug is that the math in undistortSurface doesn't account for a non-identity model->world matrix (an oversight).  This is apparently "worked around" by the static batching setting that you found.  (To check this, try this test with a modified vert/frag shader, where you call undistortVertex.)

**Comment by smdol** [comment]
Can you try with this instead:

    void vert(inout appdata_full v) {
        v.vertex = mul(_World2Object, undistortSurface(v.vertex));
    }

This is the missing adjustment for the model matrix (inverted, because we're cancelling out of part of Unity's built in MVP transformation).  If it works for you, the "real" fix is for us to move _World2Object into undistortSurface().

**Comment by vitorbalbio** [comment]
Hi, thanks for reply

It seams to fix during play but in editor using the fix suggested it just ignore all object transform values and place the objects it in the center of the world with a apparent 0,0,0 rotation and 1,1,1 scale.

As you said the correct fix is to move the _World2Object to the GvrDistortion:

`// Surface shader hides away the MVP multiplication, so we have
// to multiply by _FixProjection = inverse(MVP)*_RealProjection.
float4 undistortSurface(float4 pos) {
	float4 proj = mul(_FixProjection, undistort(pos));
	return mul(_World2Object, proj);
}`

Now i'm getting a consistent result with and without static batch.
Regards

**Comment by smdol** [comment]
We shipped v0.9 of the SDK today, which includes this fix.
