### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by egkoppel** [googlevr/gvr-unity-sdk#274]
When I try to build for android or iOS, unity returns an error: `Error building Player: BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.`

I am using an empty scene and the only plugin is the Google VR Plugin.

Unity version: 5.3.6f1 Personal

**Comment by Selzier** [comment]
I just tested 5.3.6f1 with GoogleVR 0.85 and it built fine. Do you have any more info on the error?

**Comment by egkoppel** [comment]
Here is the list of errors in the console:

`BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
Mono.Cecil.PE.ImageReader.ReadImage ()
Mono.Cecil.PE.ImageReader.ReadImageFrom (System.IO.Stream stream)
Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName)
Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName)
UnityEditor.AssemblyReferenceChecker.CollectReferences (System.String path, Boolean withMethods, Single progressValue, Boolean ignoreSystemDlls) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Utils/AssemblyReferenceChecker.cs:72)
UnityEditor.AssemblyReferenceChecker.GetScriptsHaveMouseEvents (System.String path) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Utils/AssemblyReferenceChecker.cs:186)
UnityEditor.HostView:OnGUI()`

`BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
Mono.Cecil.PE.ImageReader.ReadImage ()
Mono.Cecil.PE.ImageReader.ReadImageFrom (System.IO.Stream stream)
Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName)
Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName)
UnityEditor.AssemblyReferenceChecker.CollectReferences (System.String path, Boolean withMethods, Single progressValue, Boolean ignoreSystemDlls) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Utils/AssemblyReferenceChecker.cs:72)
UnityEditor.Android.PostProcessAndroidPlayer.PatchManifest (System.String manifest, System.String assetsData, Boolean developmentPlayer, Single progress_value)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcessInternal (System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (BuildPostProcessArgs args)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:316)
UnityEditor.HostView:OnGUI()`

`Error building Player: BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.`

**Comment by miraleung** [comment]
Could you please check whether things build for Android or iOS without the GVR plugin?

**Comment by egkoppel** [comment]
They do build

**Comment by smdol** [comment]
According to this post:

http://forum.unity3d.com/threads/cant-compile-badimageformatexception.212371/

This may be one of those problems that can strike randomly when your system is in a weird state of some kind.  The "builds-with" vs "doesn't-build-with" test is frustrating because it may not actually have to do with the doesn't-build-with packages -- just the code paths they trigger in Unity.  (In that post, the user got the error just by adding empty C# scripts to a new project and then trying to build.  They also fixed their issue by the old standby, rebooting.)

This may not be the same as your instance of the issue -- other pages I've found are all over the place.

**Comment by egkoppel** [comment]
I've never had this problem before, and as soon as I delete the GVR plugin, the project builds properly.

**Comment by Sristy-poka** [comment]
If your project is in any external harddisk, move it to internal and build, my problem was solved in this way :)
