### ISSUE TITLE
Scroll Rect problem on version 0.85 Unity 5.3.4f1

### ISSUE THREAD

**Issue by Enumio** [googlevr/gvr-unity-sdk#278]
Hello, I encountered a problem in Cardboard SDK.

I have a table of buttons 2x2 with scroll rect, and i cant click on any of them. In the editor everything works but not on my s6. When i turn off the scroll rect all buttons are clickable and work on the phone, but then i can't scroll through my table and list other buttons. What can i do?

Here are some Screens:
![table example](https://cloud.githubusercontent.com/assets/13523700/17110045/22ffea04-529b-11e6-9b89-be0fc2240144.jpg)
![table example inspector](https://cloud.githubusercontent.com/assets/13523700/17110051/27a25da8-529b-11e6-9a13-17398cf3bd6d.jpg)

This problem occurs on 0.85. I tried 0.6 and everything is fine there.

Help please.

**Comment by smdol** [comment]
For reference, which version of Unity are you using?  Was it the same version for 0.6 as well?  There have been a number of uGUI-related issues in recent Unity point releases.

**Comment by Enumio** [comment]
Same version of unity, 5.3.4f1. 

That issue i remember began in 0.7 and it is there still.

Weird thing is i can point my gaze towards one of the buttons in the table and hold the physical button pressed on my cardboard headset and can drag the whole content up and down with my head. Like when you grab a slider with a mouse.

Gonna try with different version of Unity tomorrow and report back.

**Comment by smdol** [comment]
The dragging is done here: https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Scripts/GazeInputModule.cs#L191

**Comment by Enumio** [comment]
Ok i tried Unity 5.3.5f1 and i can't see UI at all. I created fresh project and loaded first version 0.6 tested it, and then 0.85 and tried the DemoScene. With distortion correction enabled UI does not render.

Switching back to Unity 5.3.4f1, I'm going to try and workaround from there.

**Comment by smdol** [comment]
The UI issue was a bug in Unity itself, that came in at 5.3.4p2 and was fixed as of 5.3.6f1.  The bug was that Canvas objects in world space mode failed to render into cameras with a target texture.

**Comment by Enumio** [comment]
Okay, thanks for that. That is really useful. :)

**Comment by Zvirtuosity** [comment]
Enumio , are you fixed it?I already have the same problem in unity 5.3.1f1

**Comment by Enumio** [comment]
No, i have been away from that project for a while. I've been doing some AR work but I'll come back to that.

In all my internet searches i haven't found if somebody has similar problem.
