### ISSUE TITLE
Add iOS Simulator support.

### ISSUE THREAD

**Issue by dgoodine** [googlevr/gvr-unity-sdk#280]
It should be a trivial task to add i386 and x86_64 slices in the static libraries. It's a significant burden on developers to not be able to run an app using the simulator if it links your code.

**Comment by miraleung** [comment]
We'll look into adding this for a future release. Thanks for the heads up!

**Comment by dgoodine** [comment]
Is there going to be any update on this?

**Comment by nathanmartz** [comment]
Those additional binaries add a lot of size to the plugin which is problematic for some users. We're looking into other options, so I've re-opened this issue.

**Comment by dgoodine** [comment]
First, post WWDC 2015, having unused architectures doesn't increase the downloaded binary side – those get stripped out on Apple's side when the app is prepared for distribution.  So your users that have problems with the size being an issue are ill-informed.  There was an issue where apps were getting rejected last year for having those slices in place (it false-triggered use of a non-public API), and, as is typical of Apple, there's been no confirmation that has been fixed.

The only other option would be to supply *two* binaries, one with he ARM architectures, and another with the Intel architectures.  That would be fine, as it's easy to combine them into the fat binary that people tend to typically use.  (We're using 18 third party frameworks/libraries in our app, and yours is the *only* one that doesn't include the Intel slices, or alternative .a files.)

When I dowloaded and checked out the native iOS Cardboard library, it did indeed include the Intel architectures. It shouldn't be too hard to implement either choice in your build process.  As more and more Unity experiences move to a native iOS app container, this is going to be more and more important.  Developing while needing to be tethered to a device is a very significant drag on productivity compared to working in the simulator.

**Comment by nathanmartz** [comment]
Sorry, I meant that for some developers the extra size hit was difficult. Cardboard is used around the world, including places where 100MB extra download is meaningful. Still, I agree with you that supporting the simulator is important and something we'll be looking at w/ the native integrations in Unity.

**Comment by dgoodine** [comment]
Ah, I see.  Yeah, if that's a significant burden on some users, you could conceivably make two versions of each release, one for the device, one for the simulator.  Or you could just open-source Cardboard and we could do the build. ;)

**Comment by alimoeeny** [comment]
Yeah, honestly, opensource the damn thing and avoid all the troubles and people can fix all the pesky little bugs,
