### ISSUE TITLE
Setting a place for the view

### ISSUE THREAD

**Issue by rhsu0268** [googlevr/gvr-unity-sdk#281]
I want to set the y-axis of the rotation in unity so that the user is facing a different direction in the VR View. But setting the camera rotation seems to make the VR View rotate in crazy directions. Has anyone encountered this and what is the solution?

**Comment by smdol** [comment]
What's your setup?  Which version of the SDK, are you using one of the prefabs in the older versions or a plain Main Camera with StereoController attached, does the camera have a parent object?

**Comment by rhsu0268** [comment]
I'm using the most recent SDK with a GvrMain. I did notice that there is a Head object in there. Do I need to manipulate the head object?

**Comment by smdol** [comment]
Moving the entire GvrMain object around (meaning, the parent of the Head) is the right way to control the user pose in the scene space, if that's what you are trying to do.

**Comment by rhsu0268** [comment]
Okay. Is there a special setting for setting within the SDK for setting rotation or can I use the regular Unity set up with using the transform?

**Comment by smdol** [comment]
Just change the transform of the GvrMain root node.  This is like moving the player's body.  Their head rotation is relative to that orientation.

**Comment by rhsu0268** [comment]
That worked beautifully! Thank you so much.
