### ISSUE TITLE
Left/right eye distinction in vertex shader?

### ISSUE THREAD

**Issue by AndyWiltonCX** [googlevr/gvr-unity-sdk#282]
Hi all,
I'm working on a geometric shadow system that needs different shader behaviour for each eye. (Concretely the renders for left and right eyes need to either access different textures, or else have different texture coords so as to access different areas of a single atlas texture.) Currently this requires each shadow-casting game object to have two shadow game objects, one per eye, with layer assignments and layer-based culling to ensure that each shadow only gets rendered for the relevant eye. It would simplify things enormously if instead I could tell which eye was being rendered from within the vertex shader, say by accessing a global shader value.  Is there existing support for this? Alternatively, do you have any suggestions on where such a shader value could be set?
Many thanks,
Andy

**Comment by smdol** [comment]
In our current incarnation of the GoogleVR SDK, you could insert per-eye shader uniforms around here:

https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Legacy/Scripts/Internal/GvrEye.cs#L173

This won't translate to the upcoming native integration of GoogleVR in Unity, unfortunately.  Maybe Unity has another method planned or implemented in their native VR support, for cases like yours.

Alternatively, if all you need to know is which eye, then the following trick will work in both current and upcoming SDKs:  In your shader, look at the sign of UNITY_MATRIX_P[2][0].  It will be positive for the left eye and negative for the right eye.  (Or vice versa, if the depressingly common sign-error bug decided to put in an appearance here.)

If-statements in shaders aren't great, although we do use one in our vertex-based distortion code, as it is a net win for Cardboard regardless.

**Comment by AndyWiltonCX** [comment]
Thanks, I've gone with the GvrEye.cs fix for now and will worry about the move to native integration later.
