### ISSUE TITLE
Old Target SDK 24

### ISSUE THREAD

**Issue by daleknauss** [googlevr/gvr-unity-sdk#284]
I'm trying to build the Controller Demo scene to a Nexus 6P and I'm getting an error saying `Package com.me.product3new target SDK 22 doesn't support runtime permissions but the old target SDK 24 does.`

I've made sure I have SDK 24 installed (though Unity only lets me set the Minimum API Level up to 22. I'm on Unity v5.4.0f2.

Is there a way to work around this?

Here's the full error:

`CommandInvokationFailure: Unable to install APK to device. Please make sure the Android SDK is installed and is properly configured in the Editor. See the Console for more details. 
/Users/me/Library/Android/sdk/platform-tools/adb -s "8XV7N15C09000907" install -r "/Users/me/Take3/Temp/StagingArea/Package.apk"

stderr[
Failed to install /Users/me/Take3/Temp/StagingArea/Package.apk: Failure [-26: Package com.me.product3new target SDK 22 doesn't support runtime permissions but the old target SDK 24 does.]
]
stdout[

]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.ADB.RunInternal (System.String[] command, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.ADB.Run (System.String[] command, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidDevice.Exec (System.String[] command, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidDevice.Install (System.String apkfile, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit)
UnityEditor.Android.PostProcessor.Tasks.PublishPackage.UploadAndStartPlayer (UnityEditor.Android.PostProcessor.PostProcessorContext context, Boolean retryUpload)
UnityEditor.Android.PostProcessor.Tasks.PublishPackage.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.HostView:OnGUI()
`

Thank you!

**Comment by smdol** [comment]
The targetSDKVersion attribute is in Assets/Plugins/Android/AndroidManifest.xml, and we been shipping with it set to 22 in order to (for now) use install-time permissions rather than runtime permissions.  

This was because our prior underlying Android NDK didn't actually know how to ask for permissions at runtime.  That's no longer the case, I believe, so updating to 24 ought to be OK.  

Try editing that file and setting the targetSDK to 24 there.

**Comment by daleknauss** [comment]
That fixes it. Thank you!
