### ISSUE TITLE
unitygvractivity.aar requires READ_PHONE_STATE

### ISSUE THREAD

**Issue by sayangel** [googlevr/gvr-unity-sdk#285]
It seems that the READ_PHONE_STATE issue was addressed for most classes, but I'm still getting a request for phone permissions.

I've narrowed the culprit down to unitygvractivity.aar because including just the .jar doesn't throw the permissions err and the manifest file is missing minSDK as discussed in: https://github.com/googlevr/gvr-unity-sdk/issues/209

**Comment by smdol** [comment]
I unpacked the unitygvractivity.aar and here's the manifest:

    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="vr.gvr.platform.unity" >

    <application>
    </application>

That's definitely a bit lighter weight than I recall seeing in the past...

Some questions for you:  

Are you seeing this from a straight Unity build of the apk, or are you exporting to Android Studio and building there?

Is this an install time or runtime permission request you are getting?  (Or: what's the target SDK you have in your main manifest?)

**Comment by sayangel** [comment]
yeah that's what I saw. I noticed the other aars have minSdk specified.

This is exporting to android studio and runtime permission request.

What I find interesting is that a straight Unity build doesn't add READ_PHONE_STATE  according to aapt.

**Comment by sayangel** [comment]
@miraleung was this resolved?

**Comment by miraleung** [comment]
We'll look into a fix for our next release, thanks for asking!
