### ISSUE TITLE
Screen.SetResolution => display is wrong in VR mode

### ISSUE THREAD

**Issue by Whiteseeker** [googlevr/gvr-unity-sdk#290]
I'm using GVR_SDK_VERSION 0.9 (commit id e88afaff88e27093acbcc8443f203e45daaf9367 )
And Unity 5.4.0f3

I made simple scene with a plane and a cube, droped in the gvr plugin, and launch it on Nexus 6P.
As performance were quite poor, I tried to downscale the rendering using:
`Screen.SetResolution(1920, 1080, true);`
While this works fine in the Editor, and on the device with the VR mode deactivated, it doesn't work properly when the VR is activated on Nexus 6P at least (I don't have another device available to try). 

See these screenshots:
VR mode activated, SetResolution **not** called => correct display:
![screenshot_20160806-114649](https://cloud.githubusercontent.com/assets/4581097/17456392/0cdbe67e-5bce-11e6-9ddc-39c7bfc6b822.png)

VR mode activated, SetResolution **called** => display incorrect (not centered, can't see right eye entirely):
![screenshot_20160806-115809](https://cloud.githubusercontent.com/assets/4581097/17456388/f542ab4c-5bcd-11e6-8ac2-d05b3807536d.png)

VR mode **not** activated, SetResolution **called** => correct display:
![screenshot_20160806-115942](https://cloud.githubusercontent.com/assets/4581097/17456390/f544f4ce-5bcd-11e6-9f59-f3e5165f0aa8.png)

**Comment by smdol** [comment]
First thing to check is: when are you executing the SetResolution call?  For it to work given the intermediate render textures the SDK uses, it would have to be done very early, before GvrViewer.StereoScreen gets created.  There might still be an actual bug here even so, but let's check that first.  To try, edit GvrViewer.cs and put the SetResolution call in Awake(), first thing.  Or if you know there is another bit of code in your scripts that executes early enough, put it there.

**Comment by Whiteseeker** [comment]
I added the code in the place you describe:

```
  /// @note Each scene load causes an OnDestroy of the current SDK, followed
  /// by and Awake of a new one.  That should not cause the underlying native
  /// code to hiccup.  Exception: developer may call Application.DontDestroyOnLoad
  /// on the SDK if they want it to survive across scene loads.
  void Awake() {
    Screen.SetResolution(640, 480, true); // I put 640*480 just to make it obvious
    if (instance == null) {
      instance = this;
    }
    if (instance != this) {
      Debug.LogError("There must be only one GvrViewer object in a scene.");
      UnityEngine.Object.DestroyImmediate(this);
      return;
    }
```

But it didn't solve the issue.

**Comment by smdol** [comment]
In the GvrViewer inspector, what do you have the Distortion Correction method set to?

**Comment by Whiteseeker** [comment]
I tried unity and native. They have a different output but they are both wrong, see below (Also these screenshot are taken with `SetResolution(640, 480, true)`, the first ones were with 1920, 1080 so the aberations are a bit different.

Unity mode:
![screenshot_20160807-091414](https://cloud.githubusercontent.com/assets/4581097/17461308/c687da2c-5c7f-11e6-95e0-8eb5a8e60764.png)

Native mode:
![screenshot_20160807-091528](https://cloud.githubusercontent.com/assets/4581097/17461309/c68a3aa6-5c7f-11e6-9914-dbf55b2b46f3.png)
