### ISSUE TITLE
Black camera feed with vuforia

### ISSUE THREAD

**Issue by peterept** [googlevr/gvr-unity-sdk#291]
We are using both Cardboard and Vuforia AR plugins in our app.

On IOS but not on every rebuild - the vuforia camera stops rendering and only displays black.

It is something to do with the way both plugins override the AppController.

Has anyone seen this?

**Comment by smdol** [comment]
There are notes here:

https://developer.vuforia.com/library/articles/Solution/Integrating-Cardboard-to-the-ARVR-Sample

that address the AppController and related iOS issues (near the bottom of the page).

**Comment by ChokWah** [comment]
@peterept I have the save issue. Did you solve

**Comment by peterept** [comment]
It was due to the way both Vuforia and Cardboard override the AppController. If you manually merge them together then it works correctly (Unity 5.3).

**Comment by nathanmartz** [comment]
Sounds like that's the fix.

**Comment by ChokWah** [comment]
@peterept Thanks，it works. But why ？I wanna know detail。If I delete code “IMPL_APP_CONTROLLER_SUBCLASS（CardboardAppController）” in CardboardAppController.mm ，it works too。IMPL_APP_CONTROLLER_SUBCLASS overwrite "load" method for CardboardAppController.mm . If you know，please tell me。

**Comment by ChokWah** [comment]
@peterept Hi man. There is the same problem which is  displays black but can track image target
.In iOS ，override cardboard code in the AppController works.
Do you know how to fix this in Android phone
