### ISSUE TITLE
Determine if Unity app is a Cardboard or Daydream app

### ISSUE THREAD

**Issue by erikriverson** [googlevr/gvr-unity-sdk#293]
Is there a way in Unity to determine if an app is either a Cardboard or Daydream app at compile time and/or run time? 

(I'm assuming that the terms "Cardboard app" and "Daydream app" are well-defined, which may not be the case.)

**Comment by smdol** [comment]
Our current SDK will only support Cardboard.  We're moving to the natively-integrated GoogleVR support in Unity in order to handle Daydream, because of the much higher performance demands.  The build settings in the editor are where you will say which you are targeting.

**Comment by chaosemer** [comment]
There is now [a way](https://developers.google.com/vr/unity/reference/class/gvr-settings?hl=vi#class_gvr_settings_1a1ace5d2aca4019e5526ba55e9d877b12) to check.
