### ISSUE TITLE
gvr.instance.triggered not working (Magnet slide button)

### ISSUE THREAD

**Issue by Rob738** [googlevr/gvr-unity-sdk#295]
Unity Version: 5.4.0f3

I want to detect the input button on my cardboard.
The magnet button also doesn't work in the demo scene provided in the import package.
If I tab on the screen, it doesn the desired action and gvr.instance.triggered is set to true.
However the magnet button doesn't set gvr.instance.triggered to true.

I've tried different headsets. In the cardboard app the magnet button works fine.

**Comment by Rob738** [comment]
Is this change the reason why it doesn't work: 

> GvrView no longer supports magnet trigger detection or NFC-based pairing for v1 Cardboard viewers.

**Comment by Selzier** [comment]
Correct. In the recent 0.9 GVR update, support for the magnetic 'pull' buton has been removed:
https://youtu.be/o_ciUnQQINs

**Comment by JohnTaken** [comment]
So we need to shift back to 0.7 GVR???

**Comment by Selzier** [comment]
GVR 0.85 is the latest release that still supports the magnetic cardboard button. The 'push' style 2015 cardboard buttons still work normally.

**Comment by smdol** [comment]
That's correct.  As of v0.9, the magnet trigger is no longer supported.  Notice given here: https://developers.google.com/vr/unity/release-notes

**Comment by boblaublaw** [comment]
This is astonishing - all the magnetic trigger devices are orphaned?  What rationale is there for this?

**Comment by vanshikakapoor** [comment]
How can I use magnet triggers?
