### ISSUE TITLE
IOS Review been Rejected cause  use non-public API:imageWithName

### ISSUE THREAD

**Issue by 2276555081** [googlevr/gvr-unity-sdk#296]
Hello,

GVr-unity-sdk works normal until submit to App Store; That app was rejected because use non-public API: imageWithName; And I find the keyword 'imageWithName' in sdk's folder: Plugins/IOS/libgvrunity.a;

So maybe there has one issue in gvr-unity-sdk that we need to work out.

Thank you very much!

![1](https://cloud.githubusercontent.com/assets/21049965/17686403/cfc59306-639e-11e6-8829-496ac3a9807f.png)
![2](https://cloud.githubusercontent.com/assets/21049965/17686401/cf12baba-639e-11e6-93fe-759d80b0269a.png)

**Comment by 2276555081** [comment]
no one here?

**Comment by nathanmartz** [comment]
This is actually a problem with Apple. They must have some function called imageWithName and we also have a function with the same name in our SDK. However, we are not calling their API. Their checks are just over-aggressive. We're working to escalate this with Apple, but you should appeal the submission.

**Comment by hyenachi** [comment]
I find same issue that Apple rejects app due to 'imageWithName' at google map
(https://code.google.com/p/gmaps-api-issues/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Introduced%20Fixed%20Summary%20Stars%20ApiType%20Internal&groupby=&sort=&id=9704)

2276555081, How did you solve this problem?

**Comment by 2276555081** [comment]
@nathanmartz  thank you for telling me this

**Comment by 2276555081** [comment]
@hyenachi  well bro, just don't use it.

**Comment by dinhnhat0401** [comment]
@2276555081 you mean not use method 'imageWithName' ??
I did not use this method in my project but our app still be rejected as i described at [link](https://github.com/googlevr/gvr-ios-sdk/issues/121)
