### ISSUE TITLE
Problem with New Project with GoogleVRForUnity v0.9.1 and Unity v5.3.6f1

### ISSUE THREAD

**Issue by joseajimenezg** [googlevr/gvr-unity-sdk#297]
Regards,

I am creating a new project (I am following the instructions of **Enable stereo rendering** from https://developers.google.com/vr/unity/guide) and add the **GvrViewerMain** prefabs in the scene and run the game, some error messages are displayed indicating the following:

- The type or namespace name 'StereoController' could not be found (are you missing a using directive or an assembly reference?)
- The type or namespace name 'GvrProfile' could not be found (are you missing a using directive or an assembly reference?)
- The type or namespace name 'BaseVRDevice' could not be found (are you missing a using directive or an assembly reference?)
- ... GvrPreRender, GvrPostRender, GvrEye,...

Why does this happen?

Thanking you in advance the care provided.

**Comment by smdol** [comment]
First thing to check is if you actually have those scripts in your project.  They live in Assets/GoogleVR/Legacy/Scripts.

**Comment by joseajimenezg** [comment]
Problem solved. In previous versions you could import the prefabs no need to include Legacy. Thankyou.
