### ISSUE TITLE
Crash, if both use “gvr-unity-sdk” and "gvr-android-sdk"  

### ISSUE THREAD

**Issue by solomon2** [googlevr/gvr-unity-sdk#298]
“gvr-unity-sdk” hava "unityvractivity.jar" ，"com.google.vr.cardboard.UiLayer" in it.
"gvr-android-sdk" hava “common.aar” ,also hava "com.google.vr.cardboard.UiLayer" .

So, When I use android VrPanoramaView，it call “gvr-unity-sdk”, so Crash

Please Help me to solve it , we are very anxious.

Thank your very much!

（PS: It seems gvr-ios-sdk and gvr-unity-sdk also hava same problem）

**Comment by smdol** [comment]
What version of the SDKs do you have?  In our recent releases, we renamed unityvractivity.jar to unitygvractivity.aar, and now have a separate file, gvr_android_common.aar, which has the UiLayer and related classes.

**Comment by solomon2** [comment]
"gvr-android-sdk"  is newest.
“gvr-unity-sdk” maybe not .
Just now，I download newest unity-sdk. I also find unityvractivity.jar in demo.
And  what "gvr_android_common.aar"  use for? Sorry I'm android engineer not unity.
And  just now I also find "com.google.vr.cardboard.UiLayer" both  " unityvractivity.jar" and "gvr_android_common.aar"

Thank your for Reply.

**Comment by nathanmartz** [comment]
You generally should not be using both the unity and the android SDKs
together. Either use the Unity SDK inside of Unity or the android/ios SDKs
for native apps.

**Comment by smdol** [comment]
When you upgraded the Unity SDK, did you completely delete the old SDK files first?  Unity does not do that, so you may still have old files like unityvractivity.jar left over from before the upgrade.  See the upgrade instructions here:

https://developers.google.com/vr/unity/release-notes#upgrade_instructions

The current Unity SDK now has unitygvractivity.aar, which has only the classes GoogleUnityActivity and UnityVrActivityListener in it.  The rest of the Android classes it uses, like UiLayer, are now in gvr_android_common.aar, which is basically the same as "common.aar" in the Android SDK.  So you only need to keep one of those files.
