### ISSUE TITLE
when i want change"GvrProfile.ScreenSizes",can`t build android project

### ISSUE THREAD

**Issue by ayanamichaos** [googlevr/gvr-unity-sdk#299]
this is my code

```
using UnityEngine;
using System.Collections;

public class UntiltHead : MonoBehaviour
{
    public GvrViewer gvr;

    void Start()
    {
        if (gvr.ScreenSize != GvrProfile.ScreenSizes.Nexus5)
        {
            gvr.VRModeEnabled = false;
            gvr.ScreenSize = GvrProfile.ScreenSizes.Nexus5;
            gvr.VRModeEnabled = true;
        }
    }

    void Update()
    {
        gvr.ScreenSize = GvrProfile.ScreenSizes.Nexus5;
    }
}
```

I just want to change "GvrProfile.ScreenSizes" in android project, but i cant build project
with this error:

> Assets/UntiltHead.cs(19,27): error CS1061: Type `GvrViewer' does not contain a definition for`ScreenSize' and no extension method `ScreenSize' of type`GvrViewer' could be found (are you missing a using directive or an assembly reference?)

**Comment by smdol** [comment]
GvrProfile is not actually used for much except simulating the stereo profile of a phone when you play the game inside the Unity editor.  In any other case it is meant to hold values that come out of the native C++ layer of the SDK.  So, modifying these values from your code in Android Studio will almost certainly not work the way you want.
