### ISSUE TITLE
DemoScene doesn't work with magnet trigger

### ISSUE THREAD

**Issue by Nodrap** [googlevr/gvr-unity-sdk#300]
Was trying to get my game to work with the magnet switch and was getting nothing from the GvrViewer.Instance.Triggered other than screen taps. Tried building the DemoScene from the samples and it too doesn't detect the magnet trigger. I'm running it on an LG G3 that works fine with other GoogleVR apps with the trigger button. Built with Unity 5.4.0f3

**Comment by Selzier** [comment]
Magnet Trigger support was removed in GVR 0.9:
https://youtu.be/o_ciUnQQINs

**Comment by Nodrap** [comment]
Wow, thanks for the heads up. Are they crazy??? There must be millions of magnet based viewers out there that you can't support now?!! I get that it sucks and there are better options but at least offer a "not recommended" function so your game will work with the largest user base!!! Even if they separated it off to a GvrViewer.Instance.MagnetTriggered variable that would help rather than just dropping a user interface element completely. This really should be reversed. It's called backward compatibility.

**Comment by nathanmartz** [comment]
Removing magnet trigger actually opens up a lot more ways to help the platform going forward. The magnet trigger support had a constant performance overhead and prevented us from doing more interesting things with the compass (like improving drift correction). Given that WWGC partners started moving away from magnets over a year ago, the number of magnet based viewers in active use will only go down over time (they are, after all, just cardboard :)

Also, I should be clear that this SDK change doesn't impact any existing apps, and any developer who wants to hold onto magnet support can stick with an SDK version pre 0.9.

**Comment by Nodrap** [comment]
I picked up a cardboard headset with a magnet just a few months from a developer giving them away free to promote a game. They are still an active part of the VR community. I understand the reason to remove it now, but this will mean that a lot of developers will not upgrade or else their marketing department will slap them in their face and tell them to fix the magnet switch. Please consider putting it as a runtime switch in a build to turn it on or off and then we can offer it to the user whether they want the old experience or move over to the better one. I really don't want to forego any new updates just because of this.

**Comment by MiCkSoftware** [comment]
Hi!

I am wondering if the performance / drift culprit still happens if the
current viewer profile states that it does not have a magnet.

Can you tell?
Cheers!
Mick.
