### ISSUE TITLE
App crashes in 'VR Mode Enabled' switch

### ISSUE THREAD

**Issue by gustavotero7** [googlevr/gvr-unity-sdk#303]
Some times the app crashes when I try to disable **VR Mode** in runtime, It happens very often, even in Unity editor.

Any idea how to fix it?

**Comment by nathanmartz** [comment]
Can you post a call stack from the crash? Either from Editor.log or from logcat?

**Comment by cemrich** [comment]
I have the same issue on a fairly complex project (GVR v0.9.1, Unity 5.4) but can't reproduce it on a clean or reduced unity project. I'll try to provide the logs on Monday.

**Comment by gustavotero7** [comment]
Hi, these is my editor log file 
[Editor.zip](https://github.com/googlevr/gvr-unity-sdk/files/453723/Editor.zip)

**Comment by gustavotero7** [comment]
and the crash log, 
[crash_b27c5f71af76af4e9976538fb9bb6323.zip](https://github.com/googlevr/gvr-unity-sdk/files/453725/crash_b27c5f71af76af4e9976538fb9bb6323.zip)

**Comment by miraleung** [comment]
Thanks for the logs. Could you also please provide an adb logcat dump from device crashes? 

Which method are you using to disable VR mode?

**Comment by nathanmartz** [comment]
Also, If you can reproduce this in a Development build, that would help a
lot with getting a useful stack trace.

**Comment by gustavotero7** [comment]
Hi, the logcat file 
[logcat (2).zip](https://github.com/googlevr/gvr-unity-sdk/files/454065/logcat.2.zip)

and to change the vr mode I'm just
```
public void SwitchView()
    {
        if (viewType < 2)
            viewType++;
        else viewType = 0;



        try
        {
            switch (viewType)
            {
                case 0:
                    GvrViewer.Instance.VRModeEnabled = true;
                    GvrViewer.Controller.Head.trackRotation = true;
                    break;
                case 1:
                    GvrViewer.Instance.VRModeEnabled = false;
                    GvrViewer.Controller.Head.trackRotation = true;
                    break;
                case 2:
                    GvrViewer.Instance.VRModeEnabled = false;
                    GvrViewer.Controller.Head.trackRotation = false;
                    break;
                default:
                    break;
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError(e.Message);
            
        }
        
    }
```

**Comment by miraleung** [comment]
Thanks. Couple questions:

- Could you please verify what is coming from Debug.LogError()? I'm guessing it may be "Unable to find __Internal," but that's the name of our iOS libs.
- What exception are you anticipating? GvrViewer and GvrHead don't throw exceptions, so the root cause might not be coming from the plugin.

**Comment by cemrich** [comment]
Here are my logs:
* [crash_bfa30fdd7364dc428193fd54e7fcae07.zip](https://github.com/googlevr/gvr-unity-sdk/files/454542/crash_bfa30fdd7364dc428193fd54e7fcae07.zip)
* [logcat.txt](https://github.com/googlevr/gvr-unity-sdk/files/454543/logcat.txt)
* [Editor.zip](https://github.com/googlevr/gvr-unity-sdk/files/454545/Editor.zip)

The code to switch between view modes is quite similar to @gustavotero7 but I catch no exceptions.

**Comment by miraleung** [comment]
Thanks for the logs. The logcat stacktrace indicates that it's coming from Unity, with method names that look related to memory (de)allocation, which could be why it can't be repro'd on a smaller project. It's also possible that this is related to #283, which affects versions above v5.3.3. 

Could you please try:
- Turning VR mode off at the start of the scene, and see if it crashes when switching it back on at runtime
- Repro'ing in v5.3.3

**Comment by cemrich** [comment]
> Turning VR mode off at the start of the scene, and see if it crashes when switching it back on at runtime

Yes, I can reproduce the issue this way. 

I cannot try out v5.3.3 right now, but I'll come back to it later. Thank you for your analysis!

**Comment by MiCkSoftware** [comment]
Hi,

I think i encountered a similar issue when switching several time in the
same frame.
Maybe that will help.

Cheers.
Mick.

**Comment by gustavotero7** [comment]
The problem persists, the only way I find for the moment to evade the error is make the switch in a empty scene and in a coroutine in the end of frame, then back to the main scene (I use the camera rig as a persistent object, DontDestroyOnLoad() can be used for it). 

In this way i don't get error, is a bit more tangled or inefficiently but for the moment it works.

**Comment by gustavotero7** [comment]
PD: the Exception is only for test, nothing special, i'm just trying to find some error then one way i use is that :)

**Comment by cemrich** [comment]
> Repro'ing in v5.3.3

Indeed, I can't reproduce the editor crash in v5.3.3 so this most likely is related to #283 and we have to wait for a fix on Unity's side.
