### ISSUE TITLE
Back button in non-VR mode in iOS is not working

### ISSUE THREAD

**Issue by nadiacw** [googlevr/gvr-unity-sdk#304]
I'm using Unity 5.3.6f1 with the latest Google VR Unity sdk and [EasyMovieTexture plugin](https://www.assetstore.unity3d.com/en/#!/content/10032) to play a 360º video on a sphere.

When I uncheck "VR mode enabled" in the Gvr Viewer component and build for iOS the back button doesn't appear. I also have the "back button mode" set to "On" in the inspector and in script.
Could this be a problem because of the video texture plugin?
In Android everything works fine.
Thank you!

**Comment by nadiacw** [comment]
I just tried building the demo scene "HeadsetDemo" and the back button doesn't appear in iOS in non-VR mode. In android the back button appears always in both modes.
Is this meant to be this way? If so, is there a way to make it always visible?

**Comment by nathanmartz** [comment]
Why do you want the back button to appear on iOS?

**Comment by nadiacw** [comment]
The app includes other scenes, which use a normal camera and are not virtual reality. So I'd like to use the google vr back button to go back to these scenes and exit vr. I assume this would be a normal use for the back button.

**Comment by arturleao** [comment]
I had the same issue, I ended up implementing my own back button, it doesn't seem that Google is making that button come back in 360, which makes no sense at all.

**Comment by alimoeeny** [comment]
the button never worked if you implemented a main view controller (effectively embedding the unity view into your viewcontroller), which is unfortunate.

**Comment by bitdelve** [comment]
@arturleao What did you do to implement your own button? I have made a few attempts, but can't seem to get the button to sit right, and not move with the camera movement.

**Comment by arturleao** [comment]
@bitdelve It's been a while but if I recall correctly I've used a standard button in screenspace overlay. Not the best solution but it was effective.

**Comment by bitdelve** [comment]
@arturleao Thanks. Do you know of a way to use the Standard Input Module along with the Gaze Input Module? One seems to block the other from working, and whichever is higher in the inspector list is the one that works.
