### ISSUE TITLE
Cannot Hide Back Arrow

### ISSUE THREAD

**Issue by justinISOFORM** [googlevr/gvr-unity-sdk#305]
Hello it seems that there are no options for removing the back arrow that draws in the corner of the screen. Has anyone come up with a way to remove that?

**Comment by overfile** [comment]
check GvrPostRender.cs -> DrawVRBackButton()

You can see more info in the issue: https://github.com/googlevr/gvr-unity-sdk/issues/266

**Comment by smdol** [comment]
That's a stub, and it only is used for the Game window rendering when playing in the editor.

**Comment by nathanmartz** [comment]
Yes. The back button is not optional. We found that many users did not know how to exit VR without a clear on-screen affordance.
