### ISSUE TITLE
Gyro data update extremely slow on Samsung Galaxy S5 Mini as controller

### ISSUE THREAD

**Issue by foundway** [googlevr/gvr-unity-sdk#306]
Hi,

We are trying to use Samsung Galaxy S5 Mini as temporary controller for our demo because it is the smallest phone with gyro available for now. 

However, when we hook it up, the gyro and accelerometer reading updates every 2 seconds (0.5 FPS) so it is pretty much unusable. Button reacts instantly though so it doesn't seem like connection issue. (tried both Bluetooth on Nexus 6p and Wifi on Editor).

For testing purpose, Cardboard apps themselves works fine on S5 Mini so it means that Gyro should be compatible.

Have everyone seen this on S5 Mini or any other models before? I understand that this is still a workaround dev solution but I am hoping that it is just some kind of setting issue that we can fix in a few clicks. Otherwise we will just have to find more Nexus 4 from flee markets...

**Comment by hyenachi** [comment]
I don't use unity Input.gyro. It is slow to update. I use plugin for android phone. Plugin is faster .
