### ISSUE TITLE
How to check the Drift Correction is working?

### ISSUE THREAD

**Issue by Tony0611** [googlevr/gvr-unity-sdk#307]
In the release note of Version 0.8.1, it mentioned "The Auto Drift Correction option on the GvrViewer script has been removed since gyro drift correction is now an intrinsic feature of the GoogleVR NDK.".  So the option "Auto Drift Correction" is disappear on my Unity. 

Does it mean the "Auto Drift Correction" is default enable on my Unity VR App (with Unity VR SDK 0.9.1)?

**Comment by smdol** [comment]
Yes.  It is now always enabled.
