### ISSUE TITLE
Is the asynchronous reprojection enabled on AndroidN?

### ISSUE THREAD

**Issue by AlexPolishko** [googlevr/gvr-unity-sdk#308]
Is the asynchronous reprojection enabled in latest version of gvr-unity-sdk?
When I fast rotate headset the image is uncomfortable (some double and shake), Especially in details - for instance, the text in Cardboard Design lab (6. Guiding with Light)
But static image is perfect! Only fast movement is some unrealistic and sharpness(juddering). My game is slightly slow (45-60 fps), but another very fast end simple scene (as HeadsetDemo in DemoScene folder of SDK) have this bug too.
Look at the floor(grid) in Sample and try to fast rotate. In highdetailed room it's a problem.
Lerp(or Slerp) of head to target make the movement more smooth, but a latency of image increase.
The rotation in OculusVR is more smooth (on the same device).
I work with Nexus 6p (Android N) one of Daydream-ready devices.

**Comment by smdol** [comment]
It's not enabled yet.  That will arrive when Unity ships with GoogleVR built-in.

**Comment by AlexPolishko** [comment]
Thank you for your quick response.
One more questuion.

Have you any information(date) about this update? is this near future?
I think this technology help me to smooth movement(rotation) of the headset.

**Comment by nathanmartz** [comment]
Hi, Alex. We don't have a hard date yet, but it's coming pretty soon. Note that async reprojection will only work on Daydream ready Android phones, the first of which will come out later this year.
