### ISSUE TITLE
Drift issue on Gvr SDK 0.9.1

### ISSUE THREAD

**Issue by Asia5566** [googlevr/gvr-unity-sdk#309]
Drift issue on Gvr SDK 0.9.1
I try to test different sdk between 0.6 and 0.91 on same unity scene with three different smart phones

step1.
    OPEN APP
setp2.
    Put phone on table , and make sure screen views is on the scene center.
setp3.
    Wait 10 - 20 min , drink cup tea or coffee.

Then 
SDK 0.6  : The screen views still on the scene center.
SDK 0.9.1: The scene shifted big angle(10-60) on different phone and different time.
Detail result:
Link: http://i.imgur.com/sNQe14m.png
1. Could you please let me know if the drift correction can be improved on sdk 0.9.1?  Accroding to the test result, we found the sdk version 0.6 is better than sdk 0.9.1.
   So could you let know me know what's the change on sdk 0.9.1 about drift correction?
2. On GVR Unity release note 0.5.2:
   For gyro drift correction, note that if you are experiencing a steady drift, it helps to place the phone on a solid surface for a few seconds (or until drift subsides).
   
   Does it still work on sdk 0.9.1 ?

**Comment by smdol** [comment]
Were these test done with the phone lying flat?  If so, can you prop the phone on its side and see how that changes things?  The algorithm was changed between 0.6 and 0.9 in a way that should helps in many cases but not so much when the screen is flat (i.e. gravity is aligned with the Z axis).

**Comment by Asia5566** [comment]
In my test case , i put phone on mobile holder . show as below link:
http://i.imgur.com/xIVNFlF.jpg
http://i.imgur.com/7ckRv6N.jpg


I'd also confirm my question-2 (as mentioned above). I supposed the drift correction method (mentioned on 0.5.2) is not workable on 0.9.1 because you mentioned "not so much when the screen is flat (i.e. gravity is aligned with the Z axis)".
It is not workable on SDK 0.9.1. Is that correct?
(if this method still work, I'd introduce end-users to put their phone on a flat surface for calibration)

**Comment by hyenachi** [comment]
You should research average among gyro values and find out how to calibrate in your app at this moment. I think some of phones are not good enough for VR unity.

**Comment by GabeWeiss** [comment]
I'm having the same issues (SDK version 8.5). We're seeing it with any orientation of the phone. Both flat, and upright.

**Comment by GabeWeiss** [comment]
Should also note I've recalibrated my phone and it still occurs, and for clarity, it's a pretty rapid drift.

If holding the phone, it rotates 90 degrees in around 6 or 7 seconds.

**Comment by nathanmartz** [comment]
Gabe, which phone and which OS are you seeing this problem on? 15 degrees per second is really severe.

Also, compass calibration doesn't have any impact.

**Comment by GabeWeiss** [comment]
I see it on iPhone 5, but we've had reports on the Note line of Android phones, iPhone 6, and a couple Samsung S6's I believe.

**Comment by dcwilson303** [comment]
I've had it happen on my project with a Nexus 6p, after about 10 seconds of doing a look over a shoulder (racing game) returning to Y-zero is no longer centered.

**Comment by sylafrs** [comment]
Same issue on Samsung Galaxy S6, GVR 1.0.1

**Comment by noxerr** [comment]
same on samsung note 3 N9005

**Comment by programmerby** [comment]
Same issue on Motorola Nexus 6 and GVR SDK 1.0.3.

**Comment by cxy200927099** [comment]
Same issue on Samsung Galaxy s7 ,GVR1.10,unity 5.4.1f1

**Comment by raldred** [comment]
Drift is temporarily resolved by performing [figure of 8 motion](https://support.google.com/maps/answer/6145351?hl=en) with my Nexus 5X, GVR 1.10, Unity 5.4.1. Comes back as soon as device is lay flat on a table.
