### ISSUE TITLE
Drift issue on Google VR SDK for Unity

### ISSUE THREAD

**Issue by Java-YHB** [googlevr/gvr-unity-sdk#310]
I download the SDK a few days ago,and I find an issue relate to the situation of phone.
I create a new project in Unity 5.3.5f,import GoogleVRForUnity.unitypackage and set Assets/GoogleVR/DemoScenes/HeadSetDemo/DemoScene as current scene.Then click Build&Run.
If my phone is stable,for example put it on table , the demo starts looking great.But,if my phone is not stable,for example on my hands,the demo starts wtih drifting obviously. 
How can I solve the drift ?
Thank you !

**Comment by nathanmartz** [comment]
Drift is a constant challenge for Cardboard apps, and it depends quite a bit on the phone. There's not much you can do to fix it, though we try to improve things with every release.
