### ISSUE TITLE
Apple Rejects cardboard apps because of non-public API:imageWithName 

### ISSUE THREAD

**Issue by hyenachi** [googlevr/gvr-unity-sdk#312]
Apple rejects my app due to 'imageWithName' again. OMG.

I find same issue that Apple rejects app due to 'imageWithName' at google map.
(https://code.google.com/p/gmaps-api-issues/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Introduced%20Fixed%20Summary%20Stars%20ApiType%20Internal&groupby=&sort=&id=9704).
Please change api name like google map did.

**Comment by raldred** [comment]
Same, rejected for breaking rule 2.5.1 Usage of non-public API.
