### ISSUE TITLE
WorldSpace Canvas drawing on top of everything in Play mode?

### ISSUE THREAD

**Issue by Rares95** [googlevr/gvr-unity-sdk#313]
Hi, i am getting 2 graphic bugs related to World Canvases with the VR view in 'Play' mode. If i disable VR, or build the project (VR or not) these 2 issues go away.

1) World canvas movement jitters if it moves, not in the Editor window, not after build, just in the Game Window

2) World canvas renders above everything else, no matter the distance, Z-coordinates, or anything. You can see it through everything. Tried changing the layer, layer depth, still nothing. The thing is it didn't used to do that, and now it seems i can't get rid of it in my project.

https://www.dropbox.com/s/0kljf980xwzklat/Untitled.mov?dl=0
^ Here you can see issue 1

![untitled](https://cloud.githubusercontent.com/assets/2606875/18418041/42642ecc-783f-11e6-9cd7-743c3ebfe3a3.png)
^ Here you can see issue 2

**Comment by mimminito** [comment]
I'm seeing the same issue!
