### ISSUE TITLE
Switching vrmode on/off result in stereo not having the right size

### ISSUE THREAD

**Issue by fcoulombe** [googlevr/gvr-unity-sdk#314]
Basically I have an android application where when the phone is in portrait, it's using monocular and when it is in landscape, it uses stereo.

if i start in portrait and then switch to stereo when we go to landscape, the 2 eyes are rendered with the wrong size (they're smaller than they should)
if i background the application (home button) and then come back, it fixes the problem and renders with the correct size.

maybe there's a function that i can call to force recalculate the size of the eyes?

**Comment by miraleung** [comment]
Could you please try BaseVRDevice.UpdateScreenData()?
