### ISSUE TITLE
Incorrect Lens Render (Samsung S7)

### ISSUE THREAD

**Issue by Zoriak22** [googlevr/gvr-unity-sdk#315]
Problem with lens rendering, specially with S7 devices. I also get this if I try to test on a older Samsung S2.
Don't know what is the problem, users complaining in review on play store because of this. Clean Google VR project file, nothing happens, problem still exists. Older Cardboard SDK working.

![img_2194](https://cloud.githubusercontent.com/assets/22136670/18425387/5ec58db6-78b9-11e6-9338-e0fad793e638.JPG)
![img_2200](https://cloud.githubusercontent.com/assets/22136670/18425389/625be4c0-78b9-11e6-9e82-ba3e41eee0fc.JPG)

**Comment by fubenalvo** [comment]
The problem is, how the Script thinks the phone is an iPhone 5.

The script only support these phones correctly:
    Nexus5,
    Nexus6,
    GalaxyS6,
	GalaxyS7,
    GalaxyNote4,
    LGG3,
    iPhone4,
    iPhone5,
    iPhone6,
    iPhone6p,

I'm searching for a soluton too. If anyone can fix this easily, pleas share it!

**Comment by fubenalvo** [comment]
The solution should be to insert these two line after line 328 (Switch) in GvrProfile.cs but its'n not working

    if (SystemInfo.deviceModel.ToLower().Contains("sm-g930"))
        screen = GalaxyS6;

The S7 detection is working and in theory everything is perfect. Any idea?

**Comment by Zoriak22** [comment]
I try to change the code you mention, you thinking good about solving the problem. Actually I have this problem on Samsung S2 device too.

**Comment by nathanmartz** [comment]
That code is just for the in-editor preview. The actual Android SDK actually has the data for the S7.

**Comment by ezonecom** [comment]
I'm seeing the same thing on an S7 if I'm viewing an app that was originally built with GVR Unity v0.8, but then upgraded to v1.0.3. However, I've found that if you change the 'Bundle Identifier' that fixes it. e.g. my original bundle id was 'com.ezone.smbcgvr', I changed it to 'com.ezone.smbcdd' and then it worked as expected. Maybe Samsung devices save some config file somewhere?

**Comment by MephestoKhaan** [comment]
Having the same issue in some S7 and S6 devices (not all!) Any final solution?

**Comment by VIRTUALITYREPOSI** [comment]
I am experiencing the same issue on both iPod touch 6th Generation, and Samsung Galaxy S7.  Using GVR SDK 1,7 and Unity 2017.1.0f3.  Any help would be greatly appreciated.
