### ISSUE TITLE
public Uri DefaultDeviceProfile in GvrViewer no longer working SDK 0.9.1

### ISSUE THREAD

**Issue by pushbuttons** [googlevr/gvr-unity-sdk#316]
Setting the default viewer own headset no longer works after updating to SDK 0.9.1

 GvrViewer.cs

public Uri DefaultDeviceProfile = new Uri ("http://vr.google.com/cardboard/download/....");

**Comment by nathanmartz** [comment]
This only works if you did not previously have a viewer paired. Are you
sure that you did not have one paired already?

**Comment by pushbuttons** [comment]
Thank you nathanmartz. We've just launched in the Play & App Store, I can confirm no headset has been paired previously.

**Comment by dill0wn** [comment]
I just tried this in an empty project and it properly set my defaultviewer.

**Comment by dill0wn** [comment]
This is a known issue.  It only sets the viewer on the first launch of a fresh install.

**Comment by smdol** [comment]
That is so for iOS.  For Android, the profile is stored on the sdcard, so once the user has scanned a QR code from any app, your default is no longer used.  (You can't override a user's choice.)
