### ISSUE TITLE
DaydreamLabsControllerPlayground doesnt work on device

### ISSUE THREAD

**Issue by doomtoo** [googlevr/gvr-unity-sdk#317]
DaydreamLabsControllerPlayground allows you to look around, but the UI is missing, the scene is dark (so it appears the camera is inside the UI?), and the controller doesn't work (unless it accidentally hits a button, which then takes you to the right demo).

Tested on Nexus 6P( 7.0 Sept update) and Nexus 5x.

(Works fine in Unity with no issues, just not on devices.The basic controller and headset demos work in both the way they should)

**Comment by miraleung** [comment]
Which version of Unity and the GVR Unity SDK are you using?

**Comment by doomtoo** [comment]
Unity 5.3.5f1, and I'm not sure how to find the version of the GVR Unity SDK, but it was the current version downloaded on 9/13/16.
