### ISSUE TITLE
Warning with SDK 0.9.1 and Unity 5.4.0p1 - deprecated function being used

### ISSUE THREAD

**Issue by vfennel** [googlevr/gvr-unity-sdk#318]
Warning reads:

"OnLevelWasLoaded was found on GvrViewer
This message has been deprecated and will be removed in a later version of Unity."

GvrViewer.cs line 518 is where OnLevelWasLoaded is called.

**Comment by jay-seismic** [comment]
My project only has one warning and its from this.  Pretty annoying as I don't like edit library projects.

**Comment by nathanmartz** [comment]
Thanks for the bug report. We'll look into it.

**Comment by vfennel** [comment]
Closed in 1.0.0 - thanks!
