### ISSUE TITLE
360 Video is flickering on IOS device.

### ISSUE THREAD

**Issue by jhorikawa** [googlevr/gvr-unity-sdk#320]
I've tried Google VR SDK 0.9.1 using GvrViewerMain prefab with Easy Movie Texture 
or AVPro Video to show 360 degree video in VR mode but any video I'm trying to 
show flickers.

If I disable vr mode then video plays fine.

**Comment by miraleung** [comment]
Could you please try again with 1.0, and provide an "adb shell screenrecord" if this still occurs?

**Comment by lwwhb** [comment]
same problem,   Unity5.3.4 is ok, It  will be flicker with in Unity 5.4.1 ，only for ios

**Comment by nfooman** [comment]
I have the same problem. Unity 5.3.6 is fine. but  with 5.4.x and IPhone6 plus, It is flickering. It's not gvr problem but Unity problem I guess.

**Comment by peernode** [comment]
I have the same problem. Someone fix it?

**Comment by peernode** [comment]
Unity,  Gvr, Easy Movie Texture who should take the problem?

**Comment by peernode** [comment]
I have the same problem with gvr0.9.1 in unity5.4.2.  Someone fix it?

**Comment by nathanmartz** [comment]
Given that the behavior changes across Unity versions it's likely a unity specific issue. Please file a bug with them.

**Comment by nomadcandy** [comment]
This is happening to me on Android any update?
