### ISSUE TITLE
IOS Unity 5.4.0p4, Gvr 0.91. Failed to find font file : Roboto-Medium

### ISSUE THREAD

**Issue by user32768** [googlevr/gvr-unity-sdk#321]
I get a crash on launch. Any ideas? 

2016-09-19 10:14:26.042 dev[1409:1947106] Failed to load font: file not found at file:///var/containers/Bundle/Application/B802A185-54AA-4E33-82AD-BBBA24CF6374/dev.app/MaterialRobotoFontLoader.bundle/Roboto-Medium.ttf
2016-09-19 10:14:26.042 dev[1409:1947106] **\* Assertion failure in -[MDCFontDiskLoader fontOfSize:], third_party/objective_c/material_components_ios/components/FontDiskLoader/src/MDCFontDiskLoader.m:109
2016-09-19 10:14:26.181 dev[1409:1947106] Uncaught exception: NSInternalInconsistencyException: Failed to find font: Roboto-Medium in file at file:///var/containers/Bundle/Application/B802A185-54AA-4E33-82AD-BBBA24CF6374/dev.app/MaterialRobotoFontLoader.bundle/Roboto-Medium.ttf
(
    0   CoreFoundation                      0x0000000180e82dc8 <redacted> + 148
    1   libobjc.A.dylib                     0x00000001804e7f80 objc_exception_throw + 56
    2   CoreFoundation                      0x0000000180e82c80 <redacted> + 0
    3   Foundation                          0x0000000181808154 <redacted> + 112
    4   dev                                 0x0000000101598b68 -[MDCFontDiskLoader fontOfSize:] + 368
    5   dev                                 0x0000000101596cc0 -[MDCRobotoFontLoader mediumFontOfSize:] + 88
    6   dev                                 0x00000001015998bc +[MDCTypography buttonFont] + 52
    7   dev                                 0x0000000101584784 -[QTMButton commonInitWithColorGroup:shape:] + 400
    8   dev                                 0x00000001015845cc -[QTMButton initWithFrame:colorGroup:shape:] + 144
    9   dev                                 0x000000010158444c +[QTMButton buttonWithColorGroup:] + 96
    10  dev                                 0x00000001015842c0 +[QTMButton flatButtonWithColorGroup:] + 24
    11  dev                                 0x000000010153e854 -[GVROverlayView initWithFrame:createTransitionView:] + 216
    12  dev                                 0x000000010153e774 -[GVROverlayView initWithFrame:] + 24
    13  dev                                 0x0000000101536374 -[GVRUnityController init] + 104
    14  dev                                 0x00000001015367c0 createUiLayer + 88
    15  dev                                 0x0000000100b7a424 -[CardboardAppController createUnityView] + 92
    16  dev                                 0x0000000100109c58 -[UnityAppController application:didFinishLaunchingWithOptions:] + 696
    17  UIKit                               0x000000018605a9c0 <redacted> + 400
    18  UIKit                               0x000000018628a184 <redacted> + 2904
    19  UIKit                               0x000000018628e5f0 <redacted> + 1684
    20  UIKit                               0x000000018628b764 <redacted> + 168
    21  FrontBoardServices                  0x00000001828237ac <redacted> + 36
    22  FrontBoardServices                  0x0000000182823618 <redacted> + 168
    23  FrontBoardServices                  0x00000001828239c8 <redacted> + 56
    24  CoreFoundation                      0x0000000180e3909c <redacted> + 24
    25  CoreFoundation                      0x0000000180e38b30 <redacted> + 540
    26  CoreFoundation                      0x0000000180e36830 <redacted> + 724
    27  CoreFoundation                      0x0000000180d60c50 CFRunLoopRunSpecific + 384
    28  UIKit                               0x000000018605394c <redacted> + 460
    29  UIKit                               0x000000018604e088 UIApplicationMain + 204
    30  dev                                 0x00000001000f57dc main + 156
    31  libdyld.dylib                       0x00000001808fe8b8 <redacted> + 4
)
2016-09-19 10:14:26.182 dev[1409:1947106] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed to find font: Roboto-Medium in file at file:///var/containers/Bundle/Application/B802A185-54AA-4E33-82AD-BBBA24CF6374/dev.app/MaterialRobotoFontLoader.bundle/Roboto-Medium.ttf'

**Comment by smdol** [comment]
Do you have the package Assets/Plugins/iOS/MaterialRobotoFontLoader.bundle in your project?

**Comment by user32768** [comment]
Yes,
