### ISSUE TITLE
Screen.Orientation not work when using Gvr 0.8 and IOS10

### ISSUE THREAD

**Issue by xzhao23** [googlevr/gvr-unity-sdk#322]
My vr app is using cardboard sdk 0.8.1. now I came across a problem when run it in ios 10, it works well before I upgraded my iPhone to ios10.

My app have 2 scene, the first scene, I need to show some information in phone portrait mode, in the second scene, it's the vr mode. my problem is when upgraded to ios 10, the code below seem not work well, 
`Screen.orientation = ScreenOrientation.LandscapeLeft`
cannot work well, so the VR mode (camera side by side view port) can only show a part, in portrait mode.

The screenshot I got: **http://pan.baidu.com/s/1hrOYRrA**  (please copy paste this url)

Do you ever see this kind of issue? 

thanks in advance.

**Comment by smdol** [comment]
There's much discussion of this in a prior issue, with workarounds:

https://github.com/googlevr/gvr-unity-sdk/issues/144

In the case of iOS, try the solution of building the app with orientation set to landscape, and then switch to portrait in Awake().

**Comment by nathanmartz** [comment]
Closing as a dupe. Please add further info on #144
