### ISSUE TITLE
UNITY_HAS_GOOGLEVR

### ISSUE THREAD

**Issue by alimoeeny** [googlevr/gvr-unity-sdk#323]
What is `UNITY_HAS_GOOGLEVR` it is not defined neither in 'gvr' or in Unity.

**Comment by nathanmartz** [comment]
It's defined in unity and means that you're using a version with native
Google VR support.

**Comment by miraleung** [comment]
Adding on to Nathan's answer, it's defined in Unity as of the [5.4.1f1-GVR7 Daydream technical preview](https://unity3d.com/partners/google/daydream).
