### ISSUE TITLE
ios10 crash 

### ISSUE THREAD

**Issue by vivalavladislav** [googlevr/gvr-unity-sdk#326]
Hi guys,

I tried running my cardboard app on ios10 and after pressing **settings** button app crashes. I heard that I need to change some permissions but not sure what I need to do and how. Would be cool, if you could advice me here

Best regards,
Vlad Sviatetskyi

**Comment by alimoeeny** [comment]
Can only imaging it is `NSCameraUsageDescription` that you need to set in your info.plist

**Comment by vivalavladislav** [comment]
Official support tells us that this is a new requirement of iOS10: if you don't provide camera description and try to launch the app it will exit.

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW24

**Comment by nathanmartz** [comment]
That's correct. If you add that manually it'll fix the problem.

**Comment by rusmaxham** [comment]
Fixed in [v1.130](https://github.com/googlevr/gvr-unity-sdk/releases).
