### ISSUE TITLE
Android 7.0 nougat flickering and bright

### ISSUE THREAD

**Issue by gol4er2219** [googlevr/gvr-unity-sdk#327]
I updatedy phone to Android 7.0 and now when I open up the app I was working on, the screen gets bright and the screen starts flickering really bad.

**Comment by nathanmartz** [comment]
What phone are you using? And which version of Unity are you using to build the app?

**Comment by gol4er2219** [comment]
Oh sorry about that. I am using a Nexus 6p as my primary testing phone. The
Unity version i started with was 5.4.0, so after I updated my Nexus 6p from
Android version 6.0.1 to 7.0 and saw that the screen what brighter and
flickering, I thought i might just need to updated Unity to 5.4.1 but that
didn't fix the issue.

I also have a Lg G2 running Android version 5.0.2 and it doesn't have any
problems running the app.

**Comment by nathanmartz** [comment]
Which version of Unity are you using? The Daydream preview build or
something else?

**Comment by gol4er2219** [comment]
I am using Unity 5.4.1. I am not using the Daydream preview build I am
using the normal Google VR SDK Version 0.9.0

**Comment by nathanmartz** [comment]
Very strange. I honestly have no idea what could have caused this. Have you tried rebooting the problematic phone?

**Comment by miraleung** [comment]
@gol4er2219, could you please get a screengrab of the problem with "adb shell screenrecord /sdcard/video.mp4"?

**Comment by JagaHee** [comment]
Hi. I've had the same problem. And the reason is the toggle in Nexus 6P settings. Unfortunately i forgot the name of toggle but it is connected with GPU acceleration for VR apps. Can you please check it and you find it please write here the name of toggle.

**Comment by nguyentuanhung** [comment]
Hello. I'm facing the same problem. I'm also using Nexus 6P, android 7.1.1.
Is this resolved?
