### ISSUE TITLE
Left eye not rendering (black) when Direct Draw disabled (Android)

### ISSUE THREAD

**Issue by nmindiedev** [googlevr/gvr-unity-sdk#328]
Hello folks,

I've installed gvr unity sdk ver 1.0 and tried running the demo with Direct Draw disabled for post processing purposes. Haven't added any image effects yet, just decided to test this option before doing anything else. Unfortunately the left eye is not rendering at all when running on device. In editor everything works perfectly. Switching to GLES 2.0 or GLES 3.0 didn't work at all. 

Could you please help me? I'm very frustrated by this because would love to have Grab Pass refraction shader working in my game.

My mobile: Samsung Galaxy S6 Edge
Unity Version: 5.4.0f3

**Comment by miraleung** [comment]
Could you please clarify what setting you are using to disable Direct Draw?

**Comment by nmindiedev** [comment]
I'm talking about "Direct Draw" checkbox of StereoController component. Btw I'm using a new way of integration, not legacy. Just added this component by hand to get an ability to change Direct Draw value. As I stated before, everything including my GrabPass shader works fine in Editor But when I launch it on Android, left eye stops rendering.

**Comment by lucaslizama** [comment]
I have a similar issue, I'm using a distortion image effect in my app so I need to set Direct Draw to false in the Stereo Controller script for the effects to work how they should. The thing is that if I build the app for android while having "multi threaded rendering" flag active in the Player settings the left eye is rendered 9 times in small sized squares on the left section of the screen.

Like this: http://i.imgur.com/I0qEzDF.png

It works as long as I don't use multi-threaded rendering, but it would be nice being able to use it without the left eye error.

**Comment by miraleung** [comment]
How does HeadsetDemo look with those settings? That is working for me on 5.3.3, on an S6, Direct Render disabled, with or without multithreaded rendering.

**Comment by nmindiedev** [comment]
> How does HeadsetDemo look with those settings? That is working for me on 5.3.3, on an S6, Direct Render disabled, with or without multithreaded rendering.

HeadsetDemo with DirectDraw disabled looks exactly like my game: it does work perfectly in editor, but the left eye is black when running on S6. Unity 5.4 and 5.3.3 have huge internal difference.

**Comment by miraleung** [comment]
This may be fixed in an upcoming release of the Android SDK and GVR Unity SDK, which I what I'm currently using.  

If you're on 5.4, consider upgrading to our [technical preview](https://unity3d.com/partners/google/daydream), which has native GVR support.
