### ISSUE TITLE
Unable to display properly on external display using MHL cable.

### ISSUE THREAD

**Issue by Kidodelog** [googlevr/gvr-unity-sdk#329]
Hi, phone screen show nothing but only VR Configuration UI and phone orientation is upside down when connected to external display using MHL cable. It work fine when I removed the android manifest in the plugin folder but I lost the viewer profile setting. It seem like "com.google.unity.GoogleUnityActivity" stop it from display properly on external display. Any idea how can I mirror to external display? Thank you.

**Comment by nathanmartz** [comment]
Which phone are you using? Which version of Unity are you using?

**Comment by Kidodelog** [comment]
I'm using Unity 5.4.1f with GVR SDK 1.0 & Sony Xperia z3.

**Comment by nathanmartz** [comment]
You can try to use the [Daydream preview version of Unity w/ native integration](https://unity3d.com/partners/google/daydream) but we generally are not able to provide support for this kind of feature as external displays aren't intended to be supported by Google VR.
