### ISSUE TITLE
Everything I export from Unity 3d v.5.4 silently fails on Android when VR is enabled

### ISSUE THREAD

**Issue by ryankcameron** [googlevr/gvr-unity-sdk#330]
Cant open any apk file on my phone with VR enabled, may have something to do with GearVR or Oculus install, but I disabled those and no change.  I can open cardboard VR apps as long as I didnt export them from Unity myself on my Surface PC.

**Comment by nathanmartz** [comment]
Which phone are you using? Which version of Unity? If using the Daydream preview, which VR SDKs are enabled?

**Comment by ryankcameron** [comment]
As it turns out...you cant have "vr enabled" checked in the player settings for android if you are exporting for google Vr.  That checkbox should probably say "oculus/gearvr enabled" so if you do have it checked and dont have oculus or gear vr installed on your phone it appears to silently fail.   Hope that helps someone!

**Comment by nathanmartz** [comment]
You can have vr enabled if you are using the Daydream preview build, but not vanilla 5.4.

**Comment by miraleung** [comment]
@ryankcameron With the [technical preview](https://unity3d.com/partners/google/daydream), you can enable Daydream or Cardboard VR support under Player Settings > Virtual Reality Supported, when the platform is Android.
