### ISSUE TITLE
Black camera feed with vuforia (Android )

### ISSUE THREAD

**Issue by ChokWah** [googlevr/gvr-unity-sdk#332]
hi , guys. I had this problem in Android phone : black camera but can track image target and show something . Same issue like this  [https://github.com/googlevr/gvr-unity-sdk/issues/291](iOS issue) , it fixed in iOS . Can someone know about this ? 

Cardboard sdk : 0.80 
Vuforia SDK : 6.0 
Unity : 5.3.6

**Comment by nathanmartz** [comment]
I'm sorry but we can't provide support here for other pieces of middleware or older versions of our SDK.
