### ISSUE TITLE
5.4 compatibility message occurring on 5.4.1f1

### ISSUE THREAD

**Issue by jeffski13** [googlevr/gvr-unity-sdk#333]
I imported the custom unity package from the root level of this github project. I am on unity version **5.4.1f1**. I got a message saying I need to update unity  to 5.4 and then it downloaded **support libs for 5.3 and 5.2**.

**Comment by nathanmartz** [comment]
Hi. Sorry for the confusing messaging. You are on a version of Unity previous to our native integration, so you should either update to the daydream technical preview or unpack the included legacy support .unitypackage. I've added this to our internal tracker and we'll fix it for the next release.
