### ISSUE TITLE
stencil buffer shader not working in android with Unity5.4.1f1-GVR7.1, SDK 1.0

### ISSUE THREAD

**Issue by jcho89** [googlevr/gvr-unity-sdk#334]
Shaders with stencil buffer did work in editor (mac), but failed in android (nexus 6p with android 7.0 installed).

Shaders are added to "Always Included Shaders" in Built-in shader settings.

Use 32-bit Display Buffer is checked, Disable Depth and Stencil is un-checked in project settings.

Any ideas?

**Comment by miraleung** [comment]
Could you please try the Depth Format setting under Player Settings > Virtual Reality Supported > Daydream (dropdown)?

**Comment by jcho89** [comment]
Problem solved, thanks.

**Comment by nathanmartz** [comment]
Glad you got it fixed!
