### ISSUE TITLE
RaycastAll hits no world colliders in Unity 5.4/5.5 running on iOS, prevents Gaze

### ISSUE THREAD

**Issue by akeybl** [googlevr/gvr-unity-sdk#336]
Works find in the editor (and I'm assuming Android as well, given native Unity VR support), but no dice on iOS. Through debugging GazeInputModule.cs, I'm 99% sure the culprit is the RaycastAll call on the EventSystem. Only Canvas elements are properly gazed with impact to the reticle.

Confirmed not working with the headset demo scene, for reproduction purposes.

Phone: iPhone 7 Plus

**Comment by Selzier** [comment]
Try this fix: https://www.youtube.com/watch?v=CNC2NOjNaUc

**Comment by akeybl** [comment]
Thanks for the quick suggestion! I see this code actually in GazeInputModule, but it's removed at compile-time if the device is not UNITY_ANDROID or UNITY_EDITOR. I'll try adding it back in and report back, but I suspect this was purposely done.

**Comment by akeybl** [comment]
Nope didn't work sadly - VRSettings.enabled is false. "Virtual Reality Supported" also isn't available in iOS build settings.

**Comment by miraleung** [comment]
This should be fixed in an upcoming release of the GVR Unity SDK.

For the Unity GVR7.1 (and GVR7.2) technical previews, native GVR support isn't yet available for iOS, but it's coming in a future release.
