### ISSUE TITLE
can't connected to controller emulator by WIFI if build to card board

### ISSUE THREAD

**Issue by shangchen** [googlevr/gvr-unity-sdk#339]
use sdk 1.0, build to card board, connected success to controller emulator by WIFI in editor. 
but build to card board in android , can't connected  to controller emulator by WIFI.

**Comment by nathanmartz** [comment]
The phone-to-phone mode uses bluetooth. Please make sure to follow the instructions here: https://developers.google.com/vr/daydream/dev-kit-setup
