### ISSUE TITLE
Unify behavior in Unity Editor vs. Running on Device w/ Daydream Unity support and add support for Left/Right cams instead of just Main Camera

### ISSUE THREAD

**Issue by kenyee** [googlevr/gvr-unity-sdk#341]
Using the latest version of Unity 5.4.1f1-GVR7.1, the behavior of code in the simulator vs. on the device is totally different and even though in the release notes, it's mentioned as a feature, it's probably a bad thing IMHO, because you can't really trust what you're developing in Unity will work on the device w/o testing all the time when you make changes.  I was at a hackathon this weekend where I had a weird problems trying to get Left/Right camera support working so I got it to work in the Unity editor/simulator but it worked totally differently on a device (stumped some of the mentors as well because Daydream is relatively new and one of the helped w/ somethat would only work w/ the old Cardboard SDK).

My use case was I wanted different shaders/objects to show up in the left vs. right eyes (objects and cams are on different layers which you can filter via the cam's culling mask).  Hacked it w/ a script I attached to the camera that basically does this but it only works in the Unity editor (LeftEye is on layer 8 and RightEye is on layer 9):
`
    void Update () {
        if (leftCam == null) {
            // initialize cam info
            var leftCamObj = transform.FindChild("Main Camera Left").gameObject;
            leftCam = leftCamObj.GetComponent<Camera>();

```
        var rightCamObj = transform.FindChild ("Main Camera Right").gameObject;
        rightCam = rightCamObj.GetComponent<Camera>();

                    // can add custom shaders here too
    }

    leftCam.cullingMask = (leftCam.cullingMask & ~0x300) | 0x100;
    rightCam.cullingMask = (rightCam.cullingMask & ~0x300) | 0x200;
}
```

`

Then I realized this only applies in the Unity Editor after things worked totally differently on the device with nearly a day of hacking at it to figure out what was wrong :-P

If you do it the "Unity way" w/ native VR support, you create two separate cameras (left cam and right cam) but when you try this w/ the current Google VR Unity SDK, you get a null pointer exception in the StereoController code because it gets attached to both cameras but for some reason, only one of the stereocontrollers initializes the cam object.

In addition, none of image effects (I was trying to use mobileblur) works if the stereocontroller's "direct render" checkbox is enabled...there have been lots of posts on the web on this, so it's a better developer experience if this is disabled by default IMHO unless it's a really huge performance difference like using the OpenGL2 API instead of AutoAPI.

**Comment by camilosw** [comment]
I have the same problem. Have you found a workaround?

**Comment by sousv** [comment]
I also have this problem...  I can't seem to use cullingMasks on left and right cameras individually.  It works on the editor but not on the device.

public class EyeLayerCull : MonoBehaviour
{
    public LayerMask LeftEyeMask;
    public LayerMask RightEyeMask;
	private GameObject cam;
	private GameObject left;
	private GameObject right;

    void Start()
    {
        StartCoroutine(LateStart());
    }

    protected IEnumerator LateStart()
    {
		cam = GameObject.FindWithTag ("MainCamera");
		GameObject left = cam.transform.GetChild (0).gameObject;
		GameObject right = cam.transform.GetChild (1).gameObject;
        yield return new WaitWhile(() => GvrViewer.Controller == null);
        yield return new WaitWhile(() => GvrViewer.Controller.Eyes.Length < 2);
        foreach (GvrEye gvrEye in GvrViewer.Controller.Eyes)
        {
            switch (gvrEye.eye)
            {
                case GvrViewer.Eye.Left:
				gvrEye.toggleCullingMask = LeftEyeMask;
				left.GetComponent<Camera>().cullingMask = LeftEyeMask;
                    break;
                case GvrViewer.Eye.Right:
                gvrEye.toggleCullingMask = RightEyeMask;
				right.GetComponent<Camera>().cullingMask = RightEyeMask;
                    break;
            }
        }	
    }
}

**Comment by LeapGamer** [comment]
I am also interested in a solution. I also need to adjust the rotations of each camera separately. Have something working for oculus/gear VR but not daydream.

**Comment by gdpm27** [comment]
You simply need to set Depth Format to 24 bits depth | 8 bit stencil in player settings > other settings > VR SDKs > Daydream.
