### ISSUE TITLE
Should be able to SetDefaultDeviceProfile More than Once

### ISSUE THREAD

**Issue by dill0wn** [googlevr/gvr-unity-sdk#344]
DefaultDeviceProfile / SetDefaultDeviceProfile should only stop having an effect after the user has set their viewer preference by scanning a headset.  

As it is right now, SetDefaultDeviceProfile only works once.  The first time.  Forever.

**Comment by nathanmartz** [comment]
Thanks for the feedback but the current behavior is WAI and we're don't plan to change this part of our SDK behavior.
