### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources.

### ISSUE THREAD

**Issue by PolymorphiK** [googlevr/gvr-unity-sdk#347]
Can't compile using 'technical preview' from Unity for the GoogleVR SDK. Every time I try to compile I get the following error.

`
CommandInvokationFailure: Failed to re-package resources.
/\* blah blah .... */
stderr[
AndroidManifest.xml:5: error: No resource identifier found for attribute 'enableVrMode' in package 'android'

AndroidManifest.xml:5: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
]`

I don't have a conflicting AndroidManifest file I just added the GoogleVR SDK and tried to compile and APK. I have the most up-to-date SDK via SDK Manager. I have installed KitKat and Marshmallow APIs installed for Android. In PlayerSettings I have selected min-target -> API Level 19 which is 4.4 KitKat and under the new VRSDK Support I have Daydream selected.

If someone could tell me what I am doing wrong that would be great.

**Comment by nathanmartz** [comment]
The problem is that Daydream requires Android N(ougat) which is API 24
which you don't have installed. Once you install support for API 24 you
should be g2g.
