### ISSUE TITLE
App hangs on iOS

### ISSUE THREAD

**Issue by vivalavladislav** [googlevr/gvr-unity-sdk#349]
Hi guys, 

I'm using GVR 0.8.0 and after playing a game for a minute the render hangs, meaning that picture is not updated while everything else seem to be working ok. This is only observed on iOS 10 and using iPhone 5s or higher. 

I cannot update to latest release, cause my app relies on magnetic trigger detection which is removed in latter releases.

I hope that you can help me with that, cause it is really critical.

Thanks in advance,
Vlad

**Comment by vivalavladislav** [comment]
Seems that this is also the case with GVR 1.0. 
Anyone here? Any suggestions will do!

**Comment by alimoeeny** [comment]
Is there any error in the console when the app stops? anything interesting happens in profiles? does it matter if you are actively playing or even if you leave the phone on the table it happens? if you build an empty game with just the vr does it still happen?

**Comment by vivalavladislav** [comment]
First of all, when the actual issue is not a crash or stop, rendering just stops updating. 100% reproduce when playing a game, I haven't tried leaving it alone.

Secondly, I tried to build empty app and keep getting this crashes now. iPhone 6s with 10.0.1, GVR 1.0, Unity 5.4.1f

<img width="1280" alt="screen shot 2016-10-20 at 11 45 21 pm" src="https://cloud.githubusercontent.com/assets/9347812/19577400/e72373e2-971f-11e6-8e09-08308a9e20cc.png">

**Comment by nathanmartz** [comment]
The crash you are seeing in 1.0 is due to a regression where support for Metal broke. If you use GL on iOS for 1.0 it should work fine. We'll restore the codepath that supported Metal in the next update of our Unity SDK.

**Comment by vivalavladislav** [comment]
How do I enable GL in Unity? I want to build empty project to test this rendering problem now.

**Comment by nathanmartz** [comment]
Uncheck Automatic Graphics API in the [player settings.](https://docs.unity3d.com/Manual/class-PlayerSettingsiOS.html)

**Comment by vivalavladislav** [comment]
I did so, and building an empty project and leaving a phone for 10-15 minutes result either in crash or the issue I've been describing here. Reproducible on iPhone 6s and 5

**Comment by nathanmartz** [comment]
I think you are conflating two separate issues. We're already talking about the memory leak in another thread. The issue here is specific to metal based on your screenshot above and that should be totally fixable in player settings.
