### ISSUE TITLE
GvrRectile not responding to objects

### ISSUE THREAD

**Issue by pushonTunde** [googlevr/gvr-unity-sdk#350]
So I've added a GvrReticle but it doesn't respond to object within the scene by expanding the dot. Example image below.

[Game running with GvrRectile](https://drive.google.com/open?id=0B0QLbDLfJn6_Y2NPUlY0U1ZNbjQ)

When i move this over an object i.e. the tree's in my terrain or a cube the circle doesn't seem to expand. I've followed the following steps with setting up the GvrRectile within the scene as well. 
- Make the GvrRectile a child of main camera.
- Add a raycaster to the main camera.
- Add an event system with the script gaze input mode.

Attached are some images of the objects and the attached component.

[GvrViewerMain](https://drive.google.com/open?id=0B0QLbDLfJn6_cEdkZF94RWpUbUE)
[GvrRectile](https://drive.google.com/open?id=0B0QLbDLfJn6_RTZ2UFItbzB1TkU)
[Main Camera](https://drive.google.com/open?id=0B0QLbDLfJn6_RkM1bi1ET0VjTzA)
[Event System](https://drive.google.com/open?id=0B0QLbDLfJn6_b2VWR2s0NlpUcEU)

The only thing that's attached to the main camera which isn't related to the gaze input is a walking script i created with the following code within it.

```
public class VRLookWalk : MonoBehaviour {

    public Transform vrCamera;

    public float toggleAngle = 30.0f;

    public float speed = 3.0f;

    public bool moveForward;

    private CharacterController myCC;

    private AudioSource audio;

    // Use this for initialization
    void Start () {

        myCC =  GetComponent<CharacterController> ();
        audio = GetComponent<AudioSource> ();


    }

    // Update is called once per frame
    void Update () {

        if (vrCamera.eulerAngles.x >= toggleAngle && vrCamera.eulerAngles.x < 90.0f) 
        {

            moveForward = true;

        } else {
            moveForward = false;
        }

        if (moveForward) {

            Vector3 forward = vrCamera.TransformDirection (Vector3.forward);
            myCC.SimpleMove (forward * speed);
            PlayWalking ();
        } else {
            StopWalking ();
        }   
    }


    void PlayWalking(){

        if (!audio.isPlaying)
        {
            audio.PlayOneShot (audio.clip,1);
        }


    }

    void StopWalking(){
        audio.Stop ();
    }
}
```

**Comment by dhartwich1991** [comment]
hey @pushonTunde, sorry I know this is not related but I have a problem and saw you are using the same lookwalkscript as i do (from nurfacegames I guess :D) Did you manage to get the walking working on a daydream view? for me it works on the "Game" view in unity but once I deploy to a real device I can look around but if I look down but  I  don't start walking. Any idea?

**Comment by dhartwich1991** [comment]
this is my stackoverflow issue: http://stackoverflow.com/questions/41100946/charactercontroller-simplemove-not-working-on-daydream-view

**Comment by Selzier** [comment]
Nurfacegames reporting! Thanks for checking my videos guys. Is the Camera a child of another transform? You cannot move the camera directly. "you cannot move the camera directly in Unity. Instead, the camera must be a child of another GameObject, and changes to the position and rotation must be applied to the parent’s Transform."
https://unity3d.com/learn/tutorials/topics/virtual-reality/movement-vr

**Comment by nathanmartz** [comment]
Thanks, Selzier. I think you've addressed the core issue.

**Comment by nekast** [comment]
This one got me so I thought I'd mention it as part of this topic.  

One other thing to check if you are having problems with GVR picking objects is that the GVR Reticle Pointer script has a max distance parameter.  Any objects beyond this distance will not trigger the pointer events. 

If the object that you are trying to trigger is farther away, you will need to up this distance value.

![maxreticle](https://user-images.githubusercontent.com/34923330/34423054-38fe90e2-ebdf-11e7-963e-90dacb772b15.jpg)
