### ISSUE TITLE
Central line cut and left and right cameras too separated when compiled to Android but perfect in the Unity Game view

### ISSUE THREAD

**Issue by chelder86** [googlevr/gvr-unity-sdk#351]
We have attached an screenshot.

When we realized about this issue we thought it was our problem. So we asked here: http://stackoverflow.com/questions/40120859/googlevr-1-0-1-stereo-cameras-are-ok-in-the-unity-game-view-but-too-separated-w 

However it has happened again in another project, and this time we can reproduce the steps:
- We have imported and opened the demo scene of this asset: https://www.assetstore.unity3d.com/en/#!/content/18746
- We have imported GoogleVR1.0.1, and added the GvrViewerMain prefab.
- We have moved the game object of the scene to set it very close to the camera.
- We have compiled to Android changing resolution to landscape left and adding an icon and cursor.

An important point is that **this issue does not exist when we compile the demo scene provided with GoogleVR!** Does it do something "special" besides having the GvrViewerMain prefab?

Maybe the issue happens when automatically updating an old project. Or maybe it happened after updating the Smartphone to Android 6.0 Marshmallow (CyanogenMod 13.0), on Samsung S4.

![screenshot 21 oct 2016 1-28-33](https://cloud.githubusercontent.com/assets/3020189/19582278/6f612354-9733-11e6-9d12-199cc10a5a6a.jpg)

**Comment by nathanmartz** [comment]
Can you confirm that this actually only repros when you build a scene that
isn't our test scene and that the test scene actually works fine?

**Comment by MatzeOGH** [comment]
We are having the same issue on android. Wasn't a problem with GoogleVR0.9

**Comment by chelder86** [comment]
A picture is worth a thousand words. So I have attached two more screenshots:

- Android 6 (CM13 on Samsung s4): demo scene of GoogleVR, you can see the vertical line in the screenshot. I have just realized that the **settings button is in the center in the demo scene but in the upper right corner in our game** (and we have not change anything related to that.
- Iphone6: no line at all in our game (I cannot test the demo scene in an iPhone, sorry)

![android6-cw13-googlevr_demoscene](https://cloud.githubusercontent.com/assets/3020189/19805297/d9c5f860-9d13-11e6-9f4b-f2ed4898bb6c.jpg)
![iphone6](https://cloud.githubusercontent.com/assets/3020189/19805298/d9c907a8-9d13-11e6-89f6-c7a13fd62845.jpg)

**Comment by nadiacw** [comment]
I'm having the same problem using Unity 5.4.2f2-GVR10 and the latest GVR Unity sdk on a Google Pixel, just building the Controller demo scene:

![screenshot_20161028-161143](https://cloud.githubusercontent.com/assets/11364922/19809712/c0c77c96-9d2a-11e6-80ce-58bc6686abd5.png)

**Comment by nathanmartz** [comment]
We intentionally changed the location of the gear and the placement of the alignment line to accommodate the new Daydream View as well as to minimize glare on some cardboard viewers. These changes are active on Android and will propagate to iOS and the Unity editor soon.

**Comment by chelder86** [comment]
OK. So, is it related somehow with the issue of cameras so separated?

**Comment by chelder86** [comment]
Changing scale to 0.007 (a very similar scale to the demo scene objects: 0.003) seems to fix the problem.

**Comment by Mthegamer** [comment]
Changing scale of what? Nothing mentioned here or any other related pages.  Please let me know

**Comment by chelder86** [comment]
Of the game object of the scene like the cube or the canvas in the provided scene. You will see one is at a distance of 1 and the other at a distance of 2, so these game objects must be scaled to that value. Otherwise would be too big as they are quite close.

**Comment by raphtimecn** [comment]
Android app:
/sdcard/Cardboard/current_device_params

all  gvr(cardboard) app will use this file --- "current_device_params".

maybe you should go the url to setup your device profile https://vr.google.com/cardboard/viewerprofilegenerator/

in addiation, you can also do this:

http://stackoverflow.com/questions/40340898/how-to-change-field-of-view-in-google-vr-sdk-for-unity/40358587#40358587

**Comment by chelder86** [comment]
Thanks @raphtimecn! Updated the stackoverflow answer to add your words :)
