### ISSUE TITLE
Cardboard SDK v0.6/ Xcode 8 - iOS Crash on Startup

### ISSUE THREAD

**Issue by tunds** [googlevr/gvr-unity-sdk#354]
So i have to the use the 6.0 version of the cardboard sdk but i seem to be getting an application crash whenever i try to run the app on my phone via xcode. I've looked at the issue recommended on the bug [#140](https://github.com/googlevr/gvr-unity-sdk/issues/140) but the issue is still persisting. 

I've also tried the following to try and prevent this crash:

Unity
- Disabled cardboard audio listener, worth noting that this was the main camera rather than the cardboard main prefab.

Xcode
- Disable bitcode
- Added the security framework

Here's a screenshot of where i'm getting an error and also a copy of my zipped project as well.

<img width="1280" alt="screen shot 2016-10-23 at 09 27 55" src="https://cloud.githubusercontent.com/assets/13200450/19624984/84b967da-9903-11e6-99ce-a6ac8a8cae34.png">

If you want a copy of the project just say and i'll attach a copy of it via google drive.

**Comment by nathanmartz** [comment]
I'm sorry but we can't provide support for old versions of the SDK, especially when combined with versions of Xcode that weren't even available when that version of the SDK was released.
