### ISSUE TITLE
Unable to build sample or personal projects in Xcode 8/Gvr 1.0

### ISSUE THREAD

**Issue by tunds** [googlevr/gvr-unity-sdk#355]
Not having much luck with this sdk recently..., I exported one of my own projects and the sample for ios but when i want to build the project for xcode i keep getting the following error.

`Undefined symbols for architecture arm64:
  "_endSettingsDialog", referenced from:
      -[DismissDialogViewController viewDidAppear:] in libvrunity.a(unity.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

These are the build setting which i've used for both projects in unity as well.

<img width="1280" alt="screen shot 2016-10-23 at 17 33 00" src="https://cloud.githubusercontent.com/assets/13179531/19627852/89f32b9c-9948-11e6-9f8b-0b1662d602b9.png">

**Comment by nathanmartz** [comment]
Which version of Unity are you using?

**Comment by effixx** [comment]
I'm having the same issue.  Unity ver 5.4.2f2

**Comment by austinmao** [comment]
Related issue: https://github.com/googlevr/gvr-unity-sdk/issues/164

**Comment by Claus79** [comment]
I have the same problem, did anybody find a fix?
