### ISSUE TITLE
vrmode (stereo but no magic window) not working in unity cardboard sample under Daydream technical preview

### ISSUE THREAD

**Issue by CGAnderson** [googlevr/gvr-unity-sdk#358]
I think this was done by design? the release notes say that under google native vr support, the magic window is no longer allowed. I take that to mean if you use the Daydream technical preview for Unity, then it assumes native google vr support and won't allow monocular views with cardboard.

I want the option to go to mono from stereo, and therefore take advantage of cardboard support...just not having the cost of stereoscopic rendering. Unity is making it clear that while current builds will support cardboard vr, the future is native google vr support, which means no  more magic window support.

If I'm wrong in my assumption, then I'm reporting a problem running the head demo (cardboard) using most recent gvr unity sdk and under daydream technical preview Unity.  If I'm not wrong, then I'm requesting for magic window support under native google vr be reinstated.

Thanks

**Comment by nathanmartz** [comment]
That's correct. We're migrating from a plugin to the native integration and we had to break a few eggs to make the proverbial omelette. Once we complete the transition to the native integration we'll re-add magic window support.

**Comment by CGAnderson** [comment]
Thanks and good to hear!
Best,
CG

**Comment by CGAnderson** [comment]
Thanks and good to hear!
I'm going to close this issue, if that's ok.
Best,
CG
