### ISSUE TITLE
Error compiling in Unity 5.4.2f2

### ISSUE THREAD

**Issue by p-somers** [googlevr/gvr-unity-sdk#359]
When I add the sdk to my project and try to compile, I get these errors:
Assets/GoogleVR/Scripts/GvrViewer.cs(84,18): error CS0246: The type or namespace name `StereoController' could not be found. Are you missing a using directive or an assembly reference?
Assets/GoogleVR/Scripts/GvrViewer.cs(171,11): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing a using directive or an assembly reference?
Assets/GoogleVR/Scripts/GvrViewer.cs(188,11): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing a using directive or an assembly reference?
Assets/GoogleVR/Scripts/GvrViewer.cs(192,18): error CS0246: The type or namespace name `BaseVRDevice' could not be found. Are you missing a using directive or an assembly reference?
Assets/GoogleVR/Scripts/GvrViewer.cs(69,17): error CS0246: The type or namespace name `StereoController' could not be found. Are you missing a using directive or an assembly reference?
Assets/GoogleVR/Scripts/GvrViewer.cs(157,10): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing a using directive or an assembly reference?
Assets/GoogleVR/Scripts/GvrViewer.cs(174,10): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing a using directive or an assembly reference?
Assets/GoogleVR/Scripts/GvrViewer.cs(253,10): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing a using directive or an assembly reference?

Am I missing something?

**Comment by nathanmartz** [comment]
You need to unpack the backwards compat package inside the SDK.

**Comment by p-somers** [comment]
Okay. I am starting from scratch though, with the latest version of unity.
What does it need backwards compatability for?

**Comment by nathanmartz** [comment]
From 1.0 on, the GVR Unity SDK is targeted at the native integration (now in technical preview). If you are using a version w/ out technical preview, then you need some extra scripts, which are in the "backwards compat" package.
