### ISSUE TITLE
"Enable Controller Emulator" option missing in Pixel's Google VR Services settings

### ISSUE THREAD

**Issue by andrelevi** [googlevr/gvr-unity-sdk#361]
Hi, I've been trying to run the Daydream Playground app on my new Pixel using another phone as the controller, but on my Pixel I cannot seem to find the "Enable Controller Emulator" option described in the instructions of the controller emulator app.

When I look at `Settings -> Apps -> Show System -> Google VR Services`, I don't see the option listed there. When I run the Playground app, I can click the gear in the middle and go to the Google VR Settings, but I don't see an option for the controller emulator there as well.

Is enabling the controller emulator for the Pixel different? Thanks!

**Comment by sigmaxipi** [comment]
Did you [tap on the version number 7 times](https://developers.google.com/vr/daydream/dev-kit-setup) to enable developer options?

**Comment by andrelevi** [comment]
Yes I did. Actually, reading through that documentation, there is no mention about the "Enable Controller Emulator" option, so maybe the controller emulator app just has outdated instructions about it?

**Comment by jdduke** [comment]
Hi @andrelevi , there are some instructions [here](https://developers.google.com/vr/daydream/dev-kit-setup) that explain unlocking the "Developer Options" UI in Google VR Services, as well as how to enable the controller emulator device. Hope that helps.
