### ISSUE TITLE
Demo crashes on android

### ISSUE THREAD

**Issue by jamesryan83** [googlevr/gvr-unity-sdk#362]
I'm using a non-rooted Samsung Galaxy S5 with Marshmallow 6.0.1.  New install of Unity 5.4.1f1 with the latest gvr-unity-sdk.  I'm following the instructions here to run the demo scene...

https://developers.google.com/vr/unity/get-started-android

My phone is flat on the table and there's some serious drift, about 2 degrees/second.  I tried restarting my phone with it flat on the table as I read somewhere that might help, but it didn't.  After about 2 or 3 minutes the screen freezes and it crashes out to the home screen with no messages.  The only interaction with the demo app was opening it from the home screen.  I've tried rebuilding it a few times in unity.  I haven't altered the code in the demo at all or anything in the scene.  Here is the stack trace from the android device monitor...

> 10-31 20:41:35.998: A/libc(12752): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12769 (UnityMain)
> 10-31 20:41:36.058: A/DEBUG(364): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 10-31 20:41:36.058: A/DEBUG(364): Build fingerprint: 'samsung/kccat6xx/kccat6:6.0.1/MMB29M/G901FXXU1CPH3:user/release-keys'
> 10-31 20:41:36.058: A/DEBUG(364): Revision: '0'
> 10-31 20:41:36.058: A/DEBUG(364): ABI: 'arm'
> 10-31 20:41:36.068: A/DEBUG(364): pid: 12752, tid: 12769, name: UnityMain  >>> com.james.vrtest4u <<<
> 10-31 20:41:36.068: A/DEBUG(364): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
> 10-31 20:41:36.318: A/DEBUG(364):     r0 6e600000  r1 00000000  r2 003bc40c  r3 6e600000
> 10-31 20:41:36.318: A/DEBUG(364):     r4 9b2d4a00  r5 00000000  r6 003bc40c  r7 00000000
> 10-31 20:41:36.318: A/DEBUG(364):     r8 00000003  r9 00000006  sl 00000400  fp 00000000
> 10-31 20:41:36.318: A/DEBUG(364):     ip 0000eefa  sp b2bf5fc8  lr 00000400  pc b6c3c102  cpsr 80010030
> 10-31 20:41:36.328: A/DEBUG(364): backtrace:
> 10-31 20:41:36.328: A/DEBUG(364):     #00 pc 00018102  /system/lib/libc.so (__memcpy_base+117)
> 10-31 20:41:36.328: A/DEBUG(364):     #01 pc 000003fc  <unknown>
> 10-31 20:41:36.328: E/Watchdog(1055): !@Sync 61 [10-31 20:41:36.336]
> 10-31 20:41:38.348: E/NativeCrashListener(1055): Exception dealing with report
> 10-31 20:41:38.348: E/NativeCrashListener(1055): android.system.ErrnoException: read failed: EAGAIN (Try again)
> 10-31 20:41:38.348: E/NativeCrashListener(1055): 	at libcore.io.Posix.readBytes(Native Method)
> 10-31 20:41:38.348: E/NativeCrashListener(1055): 	at libcore.io.Posix.read(Posix.java:169)
> 10-31 20:41:38.348: E/NativeCrashListener(1055): 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
> 10-31 20:41:38.348: E/NativeCrashListener(1055): 	at android.system.Os.read(Os.java:367)
> 10-31 20:41:38.348: E/NativeCrashListener(1055): 	at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
> 10-31 20:41:38.348: E/NativeCrashListener(1055): 	at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
> 10-31 20:42:00.518: A/DEBUG(364): Tombstone written to: /data/tombstones/tombstone_09
> 10-31 20:42:00.518: E/DEBUG(364): AM write failed: Broken pipe

**Comment by buptlinyuan** [comment]
@ @jamesryan83 ,hi , do you resolve it ? I have met the same problem, Could you share your idea about it ?

**Comment by jamesryan83** [comment]
@buptlinyuan  No sorry, i haven't looked at it for a long time.  Calibrating my phones gyroscope helped a bit, but i still had the problem.
