### ISSUE TITLE
wrong viewport when vrmode enable in some android devices.

### ISSUE THREAD

**Issue by geron-cn** [googlevr/gvr-unity-sdk#364]
wrong viewport when vrmode enable in some android devices.
the same problem in gvr-android-sdk.
![713722150776666010](https://cloud.githubusercontent.com/assets/1511316/19887931/7ac6f57a-a066-11e6-8371-da10f490b486.jpg)

**Comment by nathanmartz** [comment]
What device is that? It looks like it's probably mis-reporting it's DPI.

**Comment by geron-cn** [comment]
thank you very much, it is a customized version for evo 3d. its dpi information is about:
```
height: 1920
width: 1080
The logical density of the display: 3.0
X dimension: 160.421 pixels per inch
Y dimension: 159.895 pixels per inch
scaledDensity:  3.0
densityDpi:  480
```
the screen is about 5.5 inchs
