### ISSUE TITLE
left eye is not moving

### ISSUE THREAD

**Issue by MeloDai** [googlevr/gvr-unity-sdk#366]
i have tried turn on the Direct Render or off, the left eye is still not moving, and i using the OPENGLE, still has this problem,
only when I turn off the AA, it worked, but the graph is not clear
so do you know what is the problem?

**Comment by MeloDai** [comment]
only using opengle
turn off the direct render, left eye is black
turn on the direct render, left eye is not moving
only turn on the direct render and disable AA, it worked...

**Comment by nathanmartz** [comment]
What kind of AA were you using? Some formats are incompatible with our distortion correction code.
