### ISSUE TITLE
FOV on stereo camera doesn't return correct value 

### ISSUE THREAD

**Issue by pequodification** [googlevr/gvr-unity-sdk#370]
I have been trying to get the vertical field of view property for the stereo cameras using the code below. This is working fine in the editor, however when I build it to Android the camera's fieldOfView property appear to be returning the wrong value. Is this expected behavior?
```
Camera cam = GameObject.FindWithTag("Camera_Left").GetComponent<Camera>();
Debug.Log (cam.fieldOfView);
```

**Comment by nathanmartz** [comment]
Which version of Unity are you using? Which version of the SDK? Is it failing to find Camera_Left or is it returning an FOV you don't expect? What FOV value is being returned?

**Comment by pequodification** [comment]
Hi, thanks for getting back to me :). I've tested the code on Unity 5.4.2f2 with the latest release of the SDK. I am using the FOV to calculate the size a quad needs to be to exactly fill the camera view when it is X distance from the camera. This equation works precisely in the editor but the quad is far too small when I build to Android (although it works on Android with the mono camera). I don't remember what exact values I was getting - I'll get back to you on that as soon as I get in front of the machine with the test code on it.

I'm something of a beginner to Unity but since posting I've come across some suggestions that the actual FOV  is set to be the same as the cardboard headset lenses and will be produced from a projection matrix applied to the camera FOV. Is that the case? And if so what is the best way to calculate an accurate vertical FOV?
