### ISSUE TITLE
Can't Create Stereo Cameras on device

### ISSUE THREAD

**Issue by mdbnet** [googlevr/gvr-unity-sdk#371]
I would like to add geometry that can be seen only in one eye, such as in the image below. I need this feature for stereo movie playback and stereo cube map display, for use in a Cardboard app I am porting to Daydream.
![image](https://cloud.githubusercontent.com/assets/1987770/20208805/56dd5a1e-a7a5-11e6-9258-3bf4080ef97c.png)
Although I can get this to work in the editor (Unity 5.4.2f2-GVR11) in various ways, I can't seem to figure out a way that builds and runs on device (Nexus 6p running Nougat). This technique described here (for example) - https://github.com/googlevr/gvr-unity-sdk/issues/263 - no longer works because GvrEye.UpdateStereoValues() is only available in the editor and versions of Unity without native GVR integration.
Spent the day trying various camera setups and scripts setting masks and eye parameters without landing on a method that worked on the device. Any pointers on how to do this?

Thanks
- David

**Comment by nathanmartz** [comment]
You should take a look writing a shader that uses unity_StereoEyeIndex. This is much more efficient in the GVR Unity builds than setting up two cameras and works perfectly if you just want to change colors or UVs or textures based on which eye is rendering.

**Comment by mdbnet** [comment]
Thanks for your suggestion Nathan, I'll give it a try.
