### ISSUE TITLE
Head Tracking

### ISSUE THREAD

**Issue by s1mar** [googlevr/gvr-unity-sdk#372]
Is there a way to disable head tracking,i.e. moving your head doesn't rotate the cameras ?!?

**Comment by nathanmartz** [comment]
Which version of Unity are you using?

**Comment by s1mar** [comment]
I'm using 5.5b10

**Comment by nathanmartz** [comment]
You can just disable the gvr view component or switch to a different
camera.

**Comment by s1mar** [comment]
I want the split screen, if I disable the component then it's gone.

**Comment by nosmirck** [comment]
Try moving everything you want to not move inside the main camera, not a perfect and ideal solution, but it may help.

**Comment by s1mar** [comment]
I've already  tried that but to no avail, the main camera comes to the proper position, where I want it to in the scene but the 2 gvr cameras,  they always default to a fixed position, I'm unable to change their position via script.

**Comment by frigs** [comment]
Soory S1mar you probably already tried...but Adding everything to an Empty then adjust its Transform ???

**Comment by s1mar** [comment]
Frank, I've added the main camera object as a child  to an empty game object and made the rest of the objects as the children of the main camera object. Now, during runtime, I can see that the parent object and the main camera object are at the right position but the camera objects created by GvrMain always default to a certain position..

**Comment by frigs** [comment]
It sounds like some offset is being captured when you do the parenting, then when the root is moved you get the delta + offset ?? Are all objects Empty and all children added form the origin (0,0,0).
?

**Comment by s1mar** [comment]
The main camera is at relative origin to its parent object and I'm moving the parent object via script, in the scene view during runtime, I can see that the main camera object transform and the parent transform have moved to the appropriate position but the gvr cameras always appear at one fixed position(Now that I think of it, perhaps they are being created at the origin according to the world position and not relative to the camera, I'll have to confirm this at work. )

**Comment by s1mar** [comment]
In the hierarchy they appear to be the child objects of the main camera,but I think they're appearing according to the world position,I've even tried creating an empty game object and attaching  a script to it that will check and translate the transform of the GvrEye objects to the user decided position and set the parent transform as Main Camera as the the parent of these objects,yet to no avail.

I've also tried the legacy prefabs still no success!!

**Comment by s1mar** [comment]
I'm thinking of an alternative approach,in unity we have auto-tilt head up for emulation,can I make that happen in the app,does anybody have any clue

**Comment by s1mar** [comment]
Anyone ?!?

**Comment by rawnsley** [comment]
How about commenting out

`headPose.SetRightHanded(headView.inverse);
`

in GvrDevice::UpdateState?

This stops headPose being changed, which is what the virtual camera orientation is set from.

**Comment by sixblades** [comment]
I have a similar problem, the camera is always positioned to where I "watched" the phone at the time of its execution, if I comment this the camera looks where it has to look, but deactivates the head movement.
Some help?

**Comment by s1mar** [comment]
@sixblades, I've yet to try the solution mentioned by @rawnsley, for I am busy with some other projects, but I think it should word, have you given it a shot?!?.. If not, then please try it out and let us know

**Comment by sixblades** [comment]
Nothing, I tried and the effect is the same as disable track rotation in gvrHead
