### ISSUE TITLE
UI Scroll View Mask doesn't work on Daydream

### ISSUE THREAD

**Issue by mdbnet** [googlevr/gvr-unity-sdk#374]
I am using Version 5.4.2f2-GVR11 to build to a Nexus 6p device.

I modified the ControllerDemo scene that comes with the Google VR SDK for Unity. I duplicated the MessageCanvas, deleted the contents of the new canvas, and added a ScrollView. I also added a Sprite (a red square) under the Content object of the ScrollView and moved it to the top of the scroll view so that it is half visible - 

![image](https://cloud.githubusercontent.com/assets/1987770/20233480/e098b530-a824-11e6-867e-360bf6eface7.png)

Building and running this on the device produces an image where the entire Sprite is visible -

![screenshot_20161111-184730](https://cloud.githubusercontent.com/assets/1987770/20233645/9880f184-a826-11e6-8d79-8bbe36d82d90.png)

**Comment by nathanmartz** [comment]
You need to use a depth format that has a stencil buffer (see the Daydream options in Player Settings).
