### ISSUE TITLE
Full Google VR compliace (Cardboard + Daydream)

### ISSUE THREAD

**Issue by MiCkSoftware** [googlevr/gvr-unity-sdk#376]
Hi there!

I am starting my next project and I'd like to support both Cardboard and Daydream.
While it's clear you can add both VR platform in player settings (in the Google VR unity alpha), I am not sure if it's possible to mix minSDK levels.

Because while it's clear daydream must target Android 7.1, how to manage the application to be available to legacy android version in Cardboard mode ?

Do you have any guideline for that?

By advance thanks for your support.
Cheers!
Mick.

**Comment by nathanmartz** [comment]
I believe you need to target 24 for daydream but can have a min of 19 for
cardboard.

**Comment by MiCkSoftware** [comment]
I did not imagined it might be that simple!
I'll try to follow this path as soon as I can try it out.

Closing.
