### ISSUE TITLE
Unity iOS + Daydream controller

### ISSUE THREAD

**Issue by MattFedo** [googlevr/gvr-unity-sdk#378]
Is there no support for the controller on iOS?  I was hoping to use the controller in a ton of games we were going to port over to Daydream.  Whats up with that?

**Comment by nathanmartz** [comment]
That's correct. The controller is only supported on Daydream devices, and Daydream is Android only.

**Comment by MattFedo** [comment]
Ok well will iOS ever be supported?  iOS is supported for Cardboard.
