### ISSUE TITLE
ControllerInputModule

### ISSUE THREAD

**Issue by nosmirck** [googlevr/gvr-unity-sdk#379]
Is there an easy way to modify the Gaze input module, reticle, pointer and everything to be used with the GvrController instead of the head?

This would be a great addition to the SDK instead of what's implemented in the Controller Demo scene (which is really good for anything else, but really bad for UI interaction)

At least I'm finding difficult to set up a proper way of interaction between the controler pointer and World Canvas UI.

Thanks in advance for any tip.

**Comment by nathanmartz** [comment]
This is a good request and will be something we add in a future SDK.
