### ISSUE TITLE
SDK stops rendering terrain meshes after a certain distance

### ISSUE THREAD

**Issue by MatthewPatience** [googlevr/gvr-unity-sdk#381]
I am using a Unity plugin called Polyworld to generate a flat shaded environment. It turns a terrain into a series of meshes. When I run the game in the Unity Editor the terrain renders fine, but when I run it on the Android device it stops rendering after about 10 distance units in any direction. I did a fair bit of testing and can confirm this bug is caused by the daydream SDK or the Daydream Unity Compiler. When I disable VR support in the player settings my terrain renders fine.

Here is what my terrain meshes look like:
![screen shot 2016-11-17 at 2 46 59 am](https://cloud.githubusercontent.com/assets/675718/20380935/eb82982e-ac72-11e6-8c1e-34ea773a00d0.png)

Unity Player:
![screen shot 2016-11-17 at 2 46 13 am](https://cloud.githubusercontent.com/assets/675718/20380965/25063b64-ac73-11e6-9b80-22de0fe76111.png)

Android w/ VR enabled (notice the ridges are missing):
![screenshot_20161117-024449](https://cloud.githubusercontent.com/assets/675718/20380977/394ee634-ac73-11e6-9f44-bee22ebe1c26.png)

Android w/ VR disabled:
![screenshot_20161117-030256](https://cloud.githubusercontent.com/assets/675718/20380986/43181d16-ac73-11e6-9abe-1c5241dc430c.png)

Any thoughts on why this may be happening? I'd be happy to send code if that helps.

**Comment by nathanmartz** [comment]
I bet this is a depth precision issue, maybe also from the fact that your skybox is geo. Can you try two things:

1) In Daydream settings, use a 32 bit depth buffer not the default of 16. See if hte mountains re-appear.

2) Try hiding your sky and see if the mountains re-appear.

**Comment by MatthewPatience** [comment]
This ended up being an issue where my terrain was composed of too many meshes. After reducing the number of terrain chunks it seems to be working just fine. I believe that before I had generated ~500 chunks, and now it's down to just 4 meshes. I'm fairly new to Unity so I don't know why that worked, but I'm glad it did!

**Comment by MatthewPatience** [comment]
With a little more testing I believe it was also due to LOD quality. By using less meshes I think the LOD was allowed to increase. I'm pretty sure that if I were to have increased my quality level without lowering the number of meshes it probably would have worked just fine.
