### ISSUE TITLE
Control when the headset pairing is done

### ISSUE THREAD

**Issue by alimoeeny** [googlevr/gvr-unity-sdk#382]
On iOS, Is there a way to suppress the headset pairing view/wizard (the one that asks the user to scan a qr code)? 
I previously asked https://github.com/googlevr/gvr-unity-sdk/issues/368 if we can control when and where to do the pairing, but if we cannot, there must be a way to suppress it altogether, right?   

Is this a legacy feature that is going away and that is why I didn't get an answer?

**Comment by nathanmartz** [comment]
We plan to add the ability to suppress this, but it'll be a few versions away.

**Comment by alimoeeny** [comment]
Thank you.
