### ISSUE TITLE
iOS gyro not reacting correctly in all device perspectives

### ISSUE THREAD

**Issue by pgeorges-dpt** [googlevr/gvr-unity-sdk#384]
Hi,

We're mostly using GoogleVR for gyro drift correction and spatialized audio. The gyro controller in GvrController is working perfectly for all device orientations on Android but is only working correctly for one of two landscape orientations and no portrait orientations on iOS. Do you guys have any suggestion on how to fix this or if you even plan on fixing this?

Cheers,

Paul

**Comment by nathanmartz** [comment]
That is by design. We only support a single landscape orientation.

**Comment by pgeorges-dpt** [comment]
Understood. Do you think there is an easy way to patch this on our side? If you think there is, I'll look into doing so. Otherwise, I'll rewrite a gyro controller for iOS.

Cheers,

Paul
