### ISSUE TITLE
iOS 10 lock screen resize

### ISSUE THREAD

**Issue by EddGorman** [googlevr/gvr-unity-sdk#385]
If the screen orientation is set to landscape, and a phone running iOS10 is locked during the app, then upon resuming the app, the size of the viewports will be shrunk as if running in portrait mode. The image below from another issue is what the viewports end up looking like:

![61fb2bfe-913b-11e6-9704-d7b75c2e01e3](https://cloud.githubusercontent.com/assets/23582890/20457024/8d3147b2-ae79-11e6-8c30-91e89596334c.jpeg)

**Comment by AndreGroeschel** [comment]
Had the same issues and after days of unsuccessful hacking we gave up and went back to 0.8 to have screen orientation switching and support for portrait mode. Would be really great if this gets fixed and there is proper support for portrait mode

**Comment by dbuck** [comment]
related: https://github.com/googlevr/gvr-unity-sdk/issues/144

Running into the same problem here.
