### ISSUE TITLE
unity vr viewer simulation not working in GVR12

### ISSUE THREAD

**Issue by laererlund** [googlevr/gvr-unity-sdk#387]
Maybe this is the wrong place, but since I updated installation to 5.4.2f2-GVR12 the viewer simulation stopped working. The split image on screen when running in game mode is no longer the distorted viewfields but fills out both rectangular halfs, and I can no longer simulate head movement by holding Alt-key down and dragging mouse, images are stationary. The upper-left button icon changes from a hand to an eye, though, so holding down Alt registers somewhere.

What am I missing? 

Not even the Google VR Headset Demo Scene works anymore. And it all worked in GVR11 (mostly).

I have uninstalled and reinstalled Unity, have imported and updated Android SDK, have reimported Google VR. Didn't help, I use Windows 10 on an i7 laptop with 16GB memory and a GFX965M GPU

**Comment by miraleung** [comment]
Thanks for bringing this up. The undistorted viewports sounds like "None" is selected under Distortion Correction in the GvrViewerMain prefab. As for the head movement simulation, try clicking on the Game window before moving the mouse - focus may have gone to a different window.

For future re-imports, **after backing up your project**, you may need to nuke Assets/GoogleVR and Assets/Plugins/Android before re-importing the package, because those files may not get overwritten.

**Comment by laererlund** [comment]
@miraleung Thanks for replying - unfortunately no success. 
I can find no text line labeled "None" in the inspector, however, there is a teick mark in a field labeled "Distortion Correction Enabled". Toggling that, whether in or out of game mode, has no visible effect in the display.
I tried removing the folders you mention and re-import the new Google VR build (1.0.3) - no luck
I am aware that probably these issues must in some way be rooted in my machine, my setup. But I have no clues as where to look or tinker. and I have no idea what changes were made during the update. :-(

**Comment by laererlund** [comment]
Hmm - my bad. Perhaps. 

It turns out that the problem was that my project build settings, even after uninstalling Unity and reinstalling from GVR12, remained in set to PC standalone, not Android. Since only Android support is included in the GVR12 installation, the player failed. Changing build settings to Android seemingly solved the problem (I got a new one - somehow, the build process hits "access denied" when trying to build, but that is off topic here). 

However - it is somewhat annoying that after having made a project with Android as target, and trying to make a new project, I still keep the old "standalone" build settings, and the GVR unity package is not there when I open the project. If I try to "Add Asset Package" from the "Make New Project" splash screen, the Google package is not even shown, which means I have to manually import the package and then switch build settings in order to make the new project work. So much for "native support". Is that somehow fixable?

**Comment by nathanmartz** [comment]
What you are describing is pretty much working as intended. Daydream is only supported on Android, hence why you need to make that the build target. And yes, if you want to use the GVR Unity SDK you have to import it after you create the project. Right now the native integration focuses on rendering and head tracking (which you don't need the GVR SDK for) but over time more we'll migrate in more of the GVR SDK.
