### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by cchara11** [googlevr/gvr-unity-sdk#389]
NullReferenceException: Object reference not set to an instance of an object 
   ar StereoController.OnPreCull() in StereoController.cs:345

I tried some solutions (including #283) but still didn't get a workaround. Any way of how it can be fixed? It is frustrating because I can't even see the logcat output since it is filled with this error

I am using Unity 5.4.1f1-GVR7.1, GoogleVR SDK v1.0.1

**Comment by nathanmartz** [comment]
If you are using the native integration then you shouldn't use GVRView or StereoController at all. Also, GVR7 is pretty old. I suggest you update to GVR12.
