### ISSUE TITLE
Touch move controls

### ISSUE THREAD

**Issue by WillDonohoe** [googlevr/gvr-unity-sdk#392]
HI guys,

Would it be possible to add Touch controls to control the rotation of the camera? For example, when outside of VR mode, the user should be able to look around the environment without having to rotate the phone.

I believe this is a common implementation across other VR / cardboard experiences. If this is not within scope, could you suggest a way I could implement this myself? I can't see any documentation to disable the gyro rotation.

Thanks,
Will

**Comment by fredsa** [comment]
I think you're looking for "Magic Window" mode (monoscopic view, magically oriented by the gyroscope, so you can look around), but with the (common) addition of touch controls to provide additional input to the camera yaw (so the user can choose their forward facing direction without having to physically turn their body.

**Comment by WillDonohoe** [comment]
Magic window sounds like what I'm looking for. I can't seem to find much information about integrating this mode though. It looks like it was removed with 1.0? Is there a setting missing or something?

**Comment by fredsa** [comment]
See issue #358

**Comment by WillDonohoe** [comment]
Thanks for your replies @fredsa. Makes sense. I'll keep an eye out for when the feature is re-introduced in the native version.

Closing this now.
