### ISSUE TITLE
Always show "Video Support libraries not found or could not be loaded! Please add the GVRVideoPlayer.unitypackage to this project"

### ISSUE THREAD

**Issue by StevenKeXu** [googlevr/gvr-unity-sdk#393]
After importing GVRVideoPlayer. this message still show.

**Comment by claywilkinson** [comment]
Can you share the log of running the app?

**Comment by StevenKeXu** [comment]
Error obtaining VrCore client API version: UnityEngine.AndroidJavaException: com.google.vr.vrcore.base.api.VrCoreNotAvailableException: VR Service missing
                                                             com.google.vr.vrcore.base.api.VrCoreNotAvailableException: VR Service missing
                                                                 at com.google.vr.vrcore.base.api.VrCoreUtils.getVrCoreClientApiVersion(SourceFile:127)
                                                                 at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                 at com.unity3d.player.UnityPlayer.a(Unknown Source)
                                                                 at com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at com.unity3d.player.UnityPlayer$b.run(Unknown Source)

This api can only use on Android N integrated GVR service?

**Comment by claywilkinson** [comment]
Daydream apps require Google VR Services (which is part of Android N) and a Daydream ready phone, such as the Pixel.  On non-daydream devices you can use Cardboard VR, but it lacks support for the controller and the high performance VR rendering which is part of Daydream.

**Comment by StevenKeXu** [comment]
get it, thanks

**Comment by brianytang** [comment]
@claywilkinson I'm seeing the same error and I'm running it on a Daydream with my Pixel XL -- any ideas?

**Comment by claywilkinson** [comment]
@brianytang  - can you open a separate issue and include your log and the contents of Assets/Plugins/Android?

**Comment by fadookie** [comment]
@claywilkinson I am still seeing this with `GVRDemo.scene` on a moto x gen 1 running android 4.4 w/ Cardboard viewer, even when I am using the cardboard android manifest and linking against the Cardboard SDK. The head tracking works but it doesn't read the click magnet.

**Comment by adolfohd** [comment]
I have reimporting multiple times the GVRVideoPlayer.unitypackage file I get the message:

![unityerror1](https://user-images.githubusercontent.com/22692278/29096968-fad8f452-7c5c-11e7-9572-6c2af3b77fa9.png)

Nevertheless, I still get the message:

![unityerror2](https://user-images.githubusercontent.com/22692278/29096990-0db2b87e-7c5d-11e7-98b9-80d2e015f92b.png)

The console only gives me the warning message:

```
Not implemented on this platform
UnityEngine.Debug:Log(Object)
GvrVideoPlayerTexture:CreateVideoPlayer() (at Assets/GoogleVR/Scripts/Video/GvrVideoPlayerTexture.cs:835)
SwitchVideos:Awake() (at Assets/GoogleVR/Demos/Scripts/VideoDemo/SwitchVideos.cs:40)

```

I have tryed to run this demo in the unity player chosing API levels 23, 24, 25, 26, always reimporting all asssets. Please help!

**Comment by LightOwlFlies** [comment]
It only works in the headset, not within Unity. Build it to your phone and view with Daydream.
