### ISSUE TITLE
Gvr v1.0 Prefabs add StereoControllers and Left/Right Cameras to every Camera

### ISSUE THREAD

**Issue by dill0wn** [googlevr/gvr-unity-sdk#395]
Why? Is there a way to stop this?

**Comment by dill0wn** [comment]
I initially didn't do much digging, but now I see the `GvrViewer::AddStereoControllerToCameras()` method.  Why does it add StereoController's to every camera in the scene?  I will try disabling it for now.

**Comment by raldred** [comment]
I agree it's a bit of a fudge to stop it doing that.
There's a method in `GvrViewer.cs` called `AddStereoControllerToCameras` around line 537

```
  public static void AddStereoControllerToCameras() {
    // for (int i = 0; i < Camera.allCameras.Length; i++) {
      // Camera camera = Camera.allCameras[i];
      Camera camera = Camera.main;
      if (camera.targetTexture == null &&
          camera.cullingMask != 0 &&
          camera.GetComponent<StereoController>() == null &&
          camera.GetComponent<GvrEye>() == null &&
          camera.GetComponent<GvrPreRender>() == null &&
          camera.GetComponent<GvrPostRender>() == null) {
        camera.gameObject.AddComponent<StereoController>();
      }
    // }
  }
```

As you can see I've modified it to only use Camera.main instead of attaching the StereoController to all cameras.
