### ISSUE TITLE
Extreme jitter in VR mode

### ISSUE THREAD

**Issue by justinwasilenko** [googlevr/gvr-unity-sdk#397]
Another upgrade issue that happened in 0.8.5 and is still persistent in 1.10 and Unity 5.4.

We have a cockpit game (Minos Starfighter) the camera is a child object of the cockpit. While in VR mode the camera has a extremely bad jitter as shown in this video:

https://youtu.be/2eGrZdukfww

When not in VR mode there is no jitter.

**Comment by nathanmartz** [comment]
Thanks for the bug report. We've heard of this in a few other places. What exact version of Unity are you using? What device are you testing on?

**Comment by justinwasilenko** [comment]
Sorry for not getting back to you right away. It's happening in Unity 5.4.3p1.

Testing on a Samsung S6 and iPhone 6. Happens in both the editor and in the builds.

**Comment by MephestoKhaan** [comment]
By any chance are you "far away" from (0,0,0) ? I have seen similar issues when having transforms with big numbers

**Comment by wrh** [comment]
@nathanmartz Are you aware of the related/identical issue where relatively fast-moving objects are rendered jittery, with obvious frame drops? I've reported it [here](https://fogbugz.unity3d.com/default.asp?872723_t34vivnbb30cedeu) and it's been discussed [here](https://forum.unity3d.com/threads/jitter-when-objects-are-moving-rapidly-or-attached-to-the-camera.435048/#post-2940117), but still present in Unity 5.6.0b6, and I suspect it's a deeper issue, more your responsibility than Unity's.

**Comment by nickjbenson** [comment]
Issue still present in 5.6.0b8, tested on a Pixel. Example project + GIF [here](https://forum.unity3d.com/threads/jitter-when-objects-are-moving-rapidly-or-attached-to-the-camera.435048/#post-2958439)
