### ISSUE TITLE
Controller scrip Error

### ISSUE THREAD

**Issue by neinte** [googlevr/gvr-unity-sdk#399]
When downloading this new updated version of the SDK, I get tons of errors that point towards the controller. When I take out the SDK I have no compiler errors. When redownloading, I get 394. I'm a noob. So I might be doing something wrong.

**Comment by neinte** [comment]
Script *

**Comment by nathanmartz** [comment]
What platform are you building for? What version of Unity are you using?

**Comment by neinte** [comment]
iOS platform 
Unity 5.5
