### ISSUE TITLE
Missing Scripts After Building for Xcode (iOS)

### ISSUE THREAD

**Issue by normand1** [googlevr/gvr-unity-sdk#400]
Using Unity 5.4.2f2-GVR13
I've tried running the Demo Scenes included with gvr-unity-sdk and they run fine in Unity. I can see the "goggled" view I expect to see once the app is run on an iOS device. However, after building to Xcode and installing to my iPhone I see only the normal scene with no "goggled" stereoscopic view. I'm assuming this is due to the missing script warnings I receive in the xcode terminal window:

```
The referenced script on this Behaviour (Game Object 'TabEffects') is missing!
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Mono/MonoBehaviour.cpp Line: 1656)

A script behaviour (probably PagedScrollRect?) has a different serialization layout when loading. (Read 32 bytes but expected 564 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
```

There are too many missing script errors to list here but the one above is an example of one of the missing script errors.

Is there anything I can do to ensure these scripts are copied over correctly? These are the default demo scenes only, I'm not doing anything but trying to run the demo.

**Comment by MaxFrax** [comment]
Same issue here!

**Comment by nathanmartz** [comment]
Right now the technical preview GVR13 is targeted at Daydream, which is Android only. For native iOS (Cardboard) support, that should land in an upcoming beta of 5.6.

If you need to work around the missing script errors you can move the #ifdefs from the top of those class files to the inside of the class. That will make sure that the components exist, but do nothing.

**Comment by MaxFrax** [comment]
I know I'm a bit off topic but what if I'd like to develop just for cardboard? I mean I'm not interested in daydream or other vr kits

**Comment by nathanmartz** [comment]
The best immediate solution would be to use the 1.0 SDK w/ Unity 5.4 (non
technical preview). The best solution in the near future will be the native
integration in 5.6.

-Nathan
