### ISSUE TITLE
Help: Missing GVRVideoPlayer.unitypackage

### ISSUE THREAD

**Issue by app111** [googlevr/gvr-unity-sdk#403]

**Comment by nathanmartz** [comment]
Please provide more detail.

**Comment by app111** [comment]
![img_4232](https://cloud.githubusercontent.com/assets/1449284/21177405/0b2842e6-c226-11e6-820c-8f28dae857da.PNG)

**Comment by nathanmartz** [comment]
You need to do what it says and extract the GVRVideoPlayer.unitypackage into your project.

**Comment by smoki99** [comment]
Hi you find the "GVRVideoPlayer.unitypackage" inside of the "GoogleVRForUnity.package". You have install this first and you will find it after import in "Asserts/GoogleVR". For here you have to import this for android.

Then everything should work for you! :)

I also had to search for a while.

Cheers,
Christian

**Comment by silviocarrera** [comment]
Just clearing up if any still has any doubts. You need to unpack the "GoogleVRForUnity.package". Once unpacked into your project search for the GoogleVR folder and in there you'll find the "GVRVideoPlayer.unitypackage". 

So, tl;dr: The GVRVideo package is inside GoogleVR's package.

**Comment by asterafrem** [comment]
Hello

I found the GVRVideoPlayer.unitypackage in the Assets. I tried to import it, but I each time I get the notification that this package has been already imported.  

I still also get the picture app111 showed.

Can you help me?
Kind regards,
Aster
