### ISSUE TITLE
Integration with Unity 5.6 Beta for Daydream?

### ISSUE THREAD

**Issue by acorrow** [googlevr/gvr-unity-sdk#405]
Building for Daydream.

Unity 5.6 Beta is out. This SDK uses the UNITY_HAS_GOOGLEVR platform specific IF, and the Beta 5.6 seems to use UNITY_DAYDREAM as the platform specific. Should this be changed? Will there be a different version of the SDK for 5.6?

Thanks

**Comment by acorrow** [comment]
FYI, there is a Unity Beta Forum post on this, but nothing from anyone on the Unity side as of yet.

https://forum.unity3d.com/threads/5-6-0b1-daydream-rendering-issues-and-no-gvr-native-integration.446089/

**Comment by nathanmartz** [comment]
Thanks for the feedback. This is a known issue that we're working to resolve with Unity. I think it'll be fixed in b2 or b3, so check the release notes!
