### ISSUE TITLE
Unable to select Cardboard/Daydream from list of SDKs (Latest Google VR Unity SDK, Unity 5.5)

### ISSUE THREAD

**Issue by Xanjos** [googlevr/gvr-unity-sdk#409]
I've tried importing the latest Google VR Unity package into my Unity 5.5 project but for some reason I'm unable to choose either Cardboard or Daydream from the list of VR SDKs in my Android Player Settings (I've also tried importing it in a new project just to check but I still get the same problems so I'm suspecting that the latest SDK is not compatible with Unity 5.5 yet or something).
 
![nocardboard](https://cloud.githubusercontent.com/assets/4141732/21294931/2d6c87cc-c541-11e6-866e-6f65f09a2f69.PNG)

**Comment by Selzier** [comment]
In order to see that, you need Unity 5.6 (buggy) or Daydream Technical Preview (also buggy):
https://unity3d.com/partners/google/daydream

I recommend using Unity 5.4 or 5.5 with GVR 1.03, you will not see cardboard as a build target for VR.
https://www.youtube.com/watch?v=saPTSdvacLE

**Comment by nathanmartz** [comment]
Selziers recommendation is good for cardboard development.

For daydream development you definitely want to use the technical preview.

When 5.6 gets out of beta it'll be the best option for both cardboard and
daydream, but we're still working through beta bugs.

**Comment by Xanjos** [comment]
Cheers for that guys. I did try deleting the GoogleVR and Plugins folders from my project 1st then imported the GVR 1.03 SDK package instead but I still can't see Cardboard in the list of available VR SDKs (maybe it's meant to be like that since Selzier said I won't be able to see Cardboard as a build target for VR so I don't need to worry?)

**Comment by Selzier** [comment]
Correct, covered at 24m: https://youtu.be/saPTSdvacLE?t=24m14s

For a GearVR build, you enable Virtual Reality Supported (oculus) and for GoogleVR (cardboard) you disable Virtual Reality supported.  More details about the differences between GearVR/cardboard can be found here:
https://www.youtube.com/watch?v=eLCj6_gtLc4

And we keep that project officially updated here:
https://www.assetstore.unity3d.com/en/#!/content/67019

**Comment by Xanjos** [comment]
Ok thanks for that. I'll close the issue since my problem is pretty much solved.
