### ISSUE TITLE
Gvr1.1 + Unity5.3.6f1 Build android apk Failure

### ISSUE THREAD

**Issue by tachen** [googlevr/gvr-unity-sdk#411]
![image](https://cloud.githubusercontent.com/assets/5178366/21303387/1e54b846-c5f9-11e6-8a53-a7ea91d2ac68.png)

I change the AndroidManifest-Cardboard.xml and AndroidManifest.xml the android:targetSdkVersion to 24
![image](https://cloud.githubusercontent.com/assets/5178366/21303364/ed240d76-c5f8-11e6-887c-c597c53c26f2.png)

It works.

**Comment by zulman** [comment]
The same problem here

**Comment by cxy200927099** [comment]
same problem

**Comment by donovankeith** [comment]
Same happened to me.

**Comment by LineKernel** [comment]
me too 
whatever i do it asks for sdk24 if i use 5.4.2f2-GVR13 daydream autoinstall
or cant set the virtual reality sdk to cardboard (not in list) if use another version(5.5.1f1) of unity with GoogleVRForUnity.unitypackage alone
