### ISSUE TITLE
 distortionMesh.Optimize();

### ISSUE THREAD

**Issue by pratham2504** [googlevr/gvr-unity-sdk#412]
While playing my scene in Unity, it says UnityEngine.Mesh.Optimize() is obsolete. This method is no longer supported(UnityUpgradable).

**Comment by nathanmartz** [comment]
What version of the SDK are you using?

**Comment by paintenzero** [comment]
Mesh.Optimize() was removed in Unity 5.5.0p1. 
https://docs.unity3d.com/ScriptReference/Mesh.Optimize.html

**Comment by pratham2504** [comment]
@nathanmartz Its v1.10.0
I think this is the one available in the latest GoogleVR github repository as well..

@paintenzero So what do you suggest to do instead.. This is what comes in sdk..
Should I make some changes to the code.. I tried removing it, but obviously it didn't work..

**Comment by paintenzero** [comment]
@pratham2504 I don't know how to make GoogleVR SDK to work in Unity 5.5.0p1. 
I know GoogleVR SDK is working in 5.3.4. But I didn't want to downgrade my project so I downloaded 5.6.0b1. Cardboard and Daydream is integrated into it. However be aware it is still beta!!

**Comment by nathanmartz** [comment]
This is just a warning so it shouldn't actually cause you any problems. We'll look into a fix for our next version.

**Comment by pratham2504** [comment]
@paintenzero  My current Unity version is 5.5.0f3.
The elements are working fine in a file I downloaded from one of the tutorials I'm learning from.
Anyway there were a couple of errors apart I was receiving apart from that, one was in gvrvideoplayertexture.cs and I fixed that and my other errors stopped bugging me.. at least for now..

@nathanmartz  It was till yesterday, but like I said above, fixed some other bug issue by following the Unity recommended change and it is working for now..

**Comment by pratham2504** [comment]
@nathanmartz @paintenzero 
I have a new problem now.. My cursor doesn't show up..
How do I fix this? I'm unable to trigger event, as I do not have a cursor to point and then click.
