### ISSUE TITLE
Unable to remove Google Cardboard onboarding screen on iOS.

### ISSUE THREAD

**Issue by dangothemango** [googlevr/gvr-unity-sdk#413]
The app we are making provides users with a custom screen detailing how to rotate their phone and insert it into the Cardboard viewer. There doesnt seem to be a way to remove the default google screen and it is confusing to have 2 onboarding screens. This is not an issue on Android.

**Comment by nathanmartz** [comment]
We'll have support for disabling this screen pretty soon. Right now we
allow it in the lower level iOS SDK. We just need to plumb it through to
unity.
