### ISSUE TITLE
Unable to load gvrvideo & libaudioplugingvrunity

### ISSUE THREAD

**Issue by cha0217** [googlevr/gvr-unity-sdk#414]
I'm developing an simple android application which will show live streaming broadcasting.
After building and deploying to galaxy s7 edge(android 6.x), I received following error messages through adb.

12-21 14:53:58.659 25913 25938 E Unity   : Unable to find libaudioplugingvrunity
12-21 14:53:58.989 25913 25938 I Unity   : GVR Unity SDK Version: 1.1
12-21 14:53:58.989 25913 25938 I Unity   :
12-21 14:53:58.989 25913 25938 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
12-21 14:53:58.989 25913 25938 I Unity   :
12-21 14:53:59.019 25913 25938 E Unity   : Unable to find gvrvideo
12-21 14:53:59.129 25913 25938 I Unity   : DllNotFoundException: gvrvideo
12-21 14:53:59.129 25913 25938 I Unity   :   at (wrapper managed-to-native) GvrVideoPlayerTexture:CreateVideoPlayer ()
12-21 14:53:59.129 25913 25938 I Unity   :   at GvrVideoPlayerTexture.Awake () [0x00000] in <filename unknown>:0
12-21 14:53:59.129 25913 25938 I Unity   :
12-21 14:53:59.129 25913 25938 I Unity   : (Filename:  Line: -1)

My development environment is...
- Unity Daydream Preview 5.4.2f2-GVR13 (64-bit)
- Unity External Tools...
 * C:\Users\Tom\AppData\Local\Android\sdk
  >> I installed all android sdk higher than android 4.0 using android studio
 * C:/Program Files/Java/jdk1.8.0_111
 * C:\Program Files\Android\android-ndk-r10e

My project build setting is...
- switched to platform : android
- player settings :
 * virtual reality supported : true
 * virtual reality SDKS : cardboard
 * minimum API level : android 4.4 kitkat
  >> My demo application is for cardboard
 * the others : default value(not modified)

absolutely... I downloaded and imported the latest "Google VR SDK for Unity package".
Also add GVRVideoPlayer.unitypackage..

I guess that my android application can't load libaudioplugingvrunity & gvrvideo...
"video demo" of "Google VR SDK for Unity package" also shows the same error messages.
(although I added GVRVideoPlayer.unitypackage...)

for your information, application runs without crashing.
Please help me.

**Comment by UnstoppableN** [comment]
I'm experiencing exactly the same issue. And have the same errors in logcat.
@cha0217 Did you manage to find a solution to this problem yet?

**Comment by Peanutbutteer** [comment]
Did you find a solution yet?

**Comment by mazerte** [comment]
Hi,

I'm experiencing the same issue, It's really easy to reproduce, I just: 
* import the GoogleVR unity package
* open the video scene in the exemple
* import gvrvideoplayer.unitypackage
* build and run on my Honor 7 (android 6.0.0)

Result, the message to import the video library is still here. For the same project I compile for daydream on the Pixel on it's work.

I hope it's help ...
