### ISSUE TITLE
Double-vision when disabling distortion

### ISSUE THREAD

**Issue by MephestoKhaan** [googlevr/gvr-unity-sdk#415]
This ticket is similar to: https://github.com/googlevr/gvr-unity-sdk/issues/315

Some Galaxy S7 and S6 users have reported that when I disable VR distortion in my game they get very bad double-vision issues.  I have an S6 myself and it is working fine for me.

For other S7/S6 users they say it is already bad before disabling it (like in the linked ticket) but gets even worst after disabling the distortion.

These images where taken by a S6 user with the problem. Notice how the left eye image changes when distortion is enabled/disabled.

![screenshot_20161219-142136](https://cloud.githubusercontent.com/assets/4976810/21387773/981b3e80-c779-11e6-8203-1321b0f33526.png)

![screenshot_20161219-142202](https://cloud.githubusercontent.com/assets/4976810/21387781/9f3153e4-c779-11e6-8d92-8fd9e6559ae8.png)

I am using Unity 5.4.2f2 with  1.0.3.  I really need the distortion disabled so don't know what other ersion I could use as the integrated Unity versions seem to force the distortion.

**Comment by vitorbalbio** [comment]
I'm getting this exactly problem. With S7 it works only if we manually set the resolution to 2k and run with distortion. Any other combination (1080p + Distortion), (1080p + No Distortion), (2k + No Distortion) cause double vision. I'm using unity 5.5 and last version of Gvr Plugin.
