### ISSUE TITLE
Daydream controller is out of sync with the camera after calling GvrViewer.Instance.Recenter() 

### ISSUE THREAD

**Issue by alanlee-gn** [googlevr/gvr-unity-sdk#416]
I call 'GvrViewer.Instance.Recenter ();' when jumping into a new scene so the user is looking at a intended (or the default) direction. It rotates only the camera  to (0,0,0) but does not change the direction of the controller thus making the camera view and the controller be out of sync. It seems there is not a programatic way to correct this. 
* This problem can only be check on the device and not on the Unity game screen.

I've added a hack to make it kind of work but it is not perfect.
Problem also discussed here: https://forum.unity3d.com/threads/re-centering-with-code-when-jumping-to-new-scene.443410/

**Comment by nathanmartz** [comment]
You shouldn't call Recenter() as it'll either do nothing or have bad side
effects. The "global forward" is set when users recenter and you shouldn't
change that programatically. If you need to center the world, you want to
reorient the world or a GameObject that the player is parented to.

**Comment by alanlee-gn** [comment]
> If you need to center the world, you want to
reorient the world or a GameObject that the player is parented to.

Thanks for pointing that out.
I was rolling out my custom built controller and arm model before v.1.10 GVR SDK which was bit more difficult to work with.
I have confirmed that with the v.1.10 GVR SDK, changing the y rotation of the 'Player' object does offset bot the camera and the controller's rotation so I am using this approach.

I am closing this ticket but I think you should update the documentation for Recenter() with what you pointed out.
https://developers.google.com/vr/unity/reference/class/gvr-viewer#class_gvr_viewer_1a9b97ab09a8b8b6b482bb9cb0b29e7e85
