### ISSUE TITLE
Pixel XL with 7.1 Crashing on Google Cardboard App - libaudioplugingvrunity

### ISSUE THREAD

**Issue by czenzel** [googlevr/gvr-unity-sdk#417]
Hello everyone,

I tried both the release and beta versions of Unity3D tonight, freshly re-built the packages, but I am always receiving a crash on the launch of my application with the Google VR SDK for Unity.

I am using a Pixel XL (128g) from Verizon with the latest firmware. I do have it registered with a Daydream headset, but also tried to map it to a QR code for my UMI 3D Headset I got from Amazon.

At the time of the crash I am receiving this error:

```
12-21 23:37:03.899 29959 29959 I GVR     : [vr/gvr/capi/src/gvr.cc:94] Initialized GVR version 1.10.0
12-21 23:37:04.357 29959 29974 E Unity   : Unable to find libaudioplugingvrunity
12-21 23:37:04.358 29959 29974 E Unity   : Unable to find audioplugingvrunity
12-21 23:37:08.767 30162 30162 F DEBUG   :     #01 pc 00017b83  /data/app/com.teamweather.RadarVR-2/lib/arm/libgvrunity.so (UnityRenderEvent+186)
12-21 23:51:38.452 30754 30754 I GVR     : [vr/gvr/capi/src/gvr.cc:94] Initialized GVR version 1.10.0
12-21 23:51:38.873 30754 30772 E Unity   : Unable to find libaudioplugingvrunity
12-21 23:51:48.474 30900 30900 F DEBUG   :     #01 pc 00017b83  /data/app/com.teamweather.RadarVR-1/lib/arm/libgvrunity.so (UnityRenderEvent+186)
```

Does anybody know where I should be looking or if this is a known issue? It seems that the gvr library is loading as ARM, but neither of the included Google Audio libraries work with my device.

Here is debug output from before showing a library built for Pixel XL working on the Unity player launch:

```
amweather.RadarVR-1/lib/arm/libgvrunity.so (UnityRenderEvent+186)
12-21 22:48:42.817 28388 28388 F DEBUG   :     #01 pc 00017b83  /data/app/com.teamweather.RadarVR-1/lib/arm/libgvrunity.so (UnityRenderEvent+186)
12-21 22:52:03.280 28712 28712 F DEBUG   :     #01 pc 00017b83  /data/app/com.teamweather.RadarVR-1/lib/arm/libgvrunity.so (UnityRenderEvent+186)
```

I still have a Nexus 6P somewhere here that I can test it on as well, but I would like to see it work on the Pixel.

Thanks

Chris Zenzel (@czenzel)

**Comment by nathanmartz** [comment]
Those unable to find warnings are actually spurious. Are you trying to make a cardboard app or a daydream app? If you're trying to make a cardboard app, you need to have a cardboard viewer paired when the app launches.

**Comment by czenzel** [comment]
I am actually trying to make a Cardboard app to be more widely supported. This was an app I started about two months ago and want to keep it updated. Could this crashing be in relation to another crash as stated in #418?

**Comment by czenzel** [comment]
I received a new error regarding that the Android could not find the Unity activity when launching the application causing a crash. I am using the latest Unity beta on macOS (the Beta released on 12/23). Is there something else I could be missing? Thank you for your continued help.

**Comment by nathanmartz** [comment]
This looks like a build error of some kind. What version of the GVR SDK are you using? If you are upgrading from an old project, please make sure to delete the old GVR SDK before installing a new one. Also, are you making the APK straight from Unity or are you exporting an Android Studio project?
