### ISSUE TITLE
Daydream VR App crashes while building with Unity 5.6 beta 2 -> Google Pixel XL 7.1.1 

### ISSUE THREAD

**Issue by abhijeetnaik** [googlevr/gvr-unity-sdk#418]
I have two problems i have downloaded and installed Unity 5.6 beta 2 
I am first importing the GVR SDK for Unity [daydream].
Then i am selecting the Virtual Reality supported option from the build settings.
While building and running the app is crashing 
Here is the bug report from Android Device Monitor

12-22 15:20:37.167: E/AndroidRuntime(15770): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.abhij.GVRTEST6-2/base.apk"],nativeLibraryDirectories=[/data/app/com.abhij.GVRTEST6-2/lib/arm, /data/app/com.abhij.GVRTEST6-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-22 15:20:37.167: E/AndroidRuntime(15770): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.abhij.GVRTEST6-2/base.apk"],nativeLibraryDirectories=[/data/app/com.abhij.GVRTEST6-2/lib/arm, /data/app/com.abhij.GVRTEST6-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

12-22 15:23:08.872: I/ActivityManager(1103): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity bnds=[857,1867][1132,2239] (has extras)} from uid 10032 on display 0
12-22 15:23:08.918: I/ActivityManager(1103): Start proc 16205:com.abhij.GVRTEST6/u0a121 for activity com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity
12-22 15:23:09.959: W/ActivityManager(1103): Activity pause timeout for ActivityRecord{2e263ee u0 com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity t205}
12-22 15:23:09.960: I/WindowManager(1103): Failed to capture screenshot of Token{ceb408f ActivityRecord{2e263ee u0 com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity t205}} appWin=Window{763c9fe u0 SurfaceView - com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity} drawState=3
12-22 15:23:09.962: I/WindowManager(1103): Screen frozen for +1s24ms due to Window{4da0067 u0 com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}
12-22 15:23:10.858: W/bik(2168): DON flow failed for ComponentInfo{com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}, pendingIntent=null
12-22 15:23:11.176: A/DEBUG(16304): pid: 16205, tid: 16224, name: UnityMain  >>> com.abhij.GVRTEST6 <<<
12-22 15:23:11.180: A/DEBUG(16304):     #00 pc 0099dc04  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #01 pc 0012e1ac  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #02 pc 0013801c  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #03 pc 0013799c  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #04 pc 00156554  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #05 pc 00308ddc  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #06 pc 0030a898  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #07 pc 005b3658  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.180: A/DEBUG(16304):     #08 pc 005b636c  /data/app/com.abhij.GVRTEST6-1/lib/arm/libunity.so
12-22 15:23:11.181: A/DEBUG(16304):     #09 pc 00098439  /data/app/com.abhij.GVRTEST6-1/oat/arm/base.odex (offset 0x8c000)
12-22 15:23:12.524: W/ActivityManager(1103):   Force finishing activity com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity
12-22 15:23:12.560: I/DaydreamManagerImpl(2168): Daydream client died for: ComponentInfo{com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}
12-22 15:23:12.561: W/DaydreamManagerImpl(2168): Displaying crash notification for: ComponentInfo{com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}
12-22 15:23:12.567: I/WindowManager(1103): WIN DEATH: Window{4811c0e u0 SurfaceView - com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}
12-22 15:23:12.577: I/WindowManager(1103): WIN DEATH: Window{4da0067 u0 com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}
12-22 15:23:12.578: W/WindowManager(1103): Force-removing child win Window{259662f u0 SurfaceView - com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity} from container Window{4da0067 u0 com.abhij.GVRTEST6/com.google.unity.GoogleUnityActivity}
12-22 15:23:12.712: I/ActivityManager(1103): Process com.abhij.GVRTEST6 (pid 16205) has died

**Comment by nathanmartz** [comment]
Do you have a daydream view? If so have you completed the normal first time
setup? Also, the is a broken #define in 5.6b2 that should be fixed in
5.6b3.

**Comment by abhijeetnaik** [comment]
This is now fixed with the Unity 5.6.0b3 Beta 3
