### ISSUE TITLE
Unity 5.6.0b3- Daydream Build with Vulkan Support

### ISSUE THREAD

**Issue by abhijeetnaik** [googlevr/gvr-unity-sdk#419]
I just tried running a Test Build using a Daydream Virtual Reality SDK (AUTO GRAPHICS API) and it successfully worked. 
But,  
When i tried to run it using  VULKAN API(EXPERIMENTAL) ALSO DRAGGED IT TO THE TOP OF THE API LISTING my app crashed.  I also  read the release note it says that "VR: Initial Vulkan support for OpenVR".

Anyways here is my stack trace if any one can help that will be great

12-24 00:18:31.283: A/DEBUG(20817): pid: 20740, tid: 20770, name: Thread-16  >>> com.abhije.daydream <<<
12-24 00:18:31.288: A/DEBUG(20817):     #01 pc 0002f1a9  /data/app/com.abhije.daydream-1/lib/arm/libgvr.so
12-24 00:18:31.288: A/DEBUG(20817):     #02 pc 00020965  /data/app/com.abhije.daydream-1/lib/arm/libgvr.so
12-24 00:18:31.288: A/DEBUG(20817):     #03 pc 00017c11  /data/app/com.abhije.daydream-1/lib/arm/libgvr.so (gvr_swap_chain_create+288)
12-24 00:18:31.288: A/DEBUG(20817):     #04 pc 009b5428  /data/app/com.abhije.daydream-1/lib/arm/libunity.so
12-24 00:18:31.288: A/DEBUG(20817):     #05 pc 009b4fa0  /data/app/com.abhije.daydream-1/lib/arm/libunity.so
12-24 00:18:31.288: A/DEBUG(20817):     #06 pc 009aa44c  /data/app/com.abhije.daydream-1/lib/arm/libunity.so
12-24 00:18:31.288: A/DEBUG(20817):     #07 pc 00536510  /data/app/com.abhije.daydream-1/lib/arm/libunity.so
12-24 00:18:31.288: A/DEBUG(20817):     #08 pc 00537324  /data/app/com.abhije.daydream-1/lib/arm/libunity.so
12-24 00:18:31.288: A/DEBUG(20817):     #09 pc 00531298  /data/app/com.abhije.daydream-1/lib/arm/libunity.so
12-24 00:18:31.288: A/DEBUG(20817):     #10 pc 003ba570  /data/app/com.abhije.daydream-1/lib/arm/libunity.so
12-24 00:18:32.537: W/ActivityManager(1103):   Force finishing activity com.abhije.daydream/com.unity3d.player.UnityPlayerActivity
12-24 00:18:32.576: I/WindowManager(1103): WIN DEATH: Window{5506d3b u0 SurfaceView - com.abhije.daydream/com.unity3d.player.UnityPlayerActivity}
12-24 00:18:32.578: W/InputDispatcher(1103): channel 'eb83a55 com.abhije.daydream/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-24 00:18:32.578: E/InputDispatcher(1103): channel 'eb83a55 com.abhije.daydream/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by bopangzz** [comment]
Unfortunately, Vulkan is not supported in Daydream yet.
