### ISSUE TITLE
does gvrvideoplayer support cardboard?

### ISSUE THREAD

**Issue by cha0217** [googlevr/gvr-unity-sdk#420]
not long ago, I asked why 'libgvrvideo & libaudioplugingvrunity' was not loaded in galaxy s7.
unfortunately nobody answered my question
>> https://github.com/googlevr/gvr-unity-sdk/issues/414

so I write a new question.
1. does gvrvideoplayer.unitypackage(including libgvrvideo & libaudioplugingvrunity) support google cardboard?
2. if not, do i have to buy a pixel (certified daydream phone) to use gvrvideoplayer?

I want to know how to make live streaming(HLS) viewer in cardboard.
thank you.

**Comment by nathanmartz** [comment]
The video components in the GVR Unity SDK should work just fine for cardboard. 

The libaudioplugin warning is likely to be harmless.

Note that while HLS is supported, I don't think HLS supports live streaming. You will likely have to modify the video player source if you want to support live streaming.
