### ISSUE TITLE
Infinite camera within camera

### ISSUE THREAD

**Issue by sskenth** [googlevr/gvr-unity-sdk#422]
![screen shot 2016-12-27 at 14 41 19](https://cloud.githubusercontent.com/assets/1942693/21501827/309e657e-cc43-11e6-8650-ffb8d9a6213d.png)

I can't seem to stop this. If I switch VR mode off in GVRViewerMain then I can at least see a clear image, but then all the vr features stop working.

**Comment by nathanmartz** [comment]
Do you have multiple cameras in the scene? If so, it's a known bug that we'll have fixed in the next version.
