### ISSUE TITLE
Unity 5.5 Google VR crashes on starting. 

### ISSUE THREAD

**Issue by vanshikakapoor** [googlevr/gvr-unity-sdk#424]
I am using Unity 5.5, and try to build VR application. My application is working fine on editor, but application gets crashed on device as soon as splash screen load.

**Comment by technik** [comment]
Same thing here. Just upgraded to 5.5 and pulled latest gvr from the repository, and suddenly it crashes at random (about 70% of the times)

**Comment by nathanmartz** [comment]
Can you post an error log? And what version of the GVR Unity SDK are you using?

**Comment by cardex107** [comment]
I can't publish, Unity 5.5 - GVR 1.10: Unable to merge android manifests. See the Console for more details. See the Console for details.

**Comment by vanshikakapoor** [comment]
I have user older GVR package. Then only I was able to merge manifest.

**Comment by cardex107** [comment]
Ok, but I have a little problems testing versions for GVR and Unity, so, which version works for you @vanshikakapoor? Thanks.

**Comment by vanshikakapoor** [comment]
I am using version 0.9 GVR

**Comment by vanshikakapoor** [comment]
This link may help you
https://github.com/googlevr/gvr-unity-sdk/commits/master/GoogleVRForUnity.unitypackage

**Comment by cardex107** [comment]
Ohhh!!! Excellent!! thanks for all, this can help other users with the same problem 👍

**Comment by pgeorges-dpt** [comment]
This is happening for me with Unity 5.5.0f3 and GVR 0.9 and GVR 1.10

**Comment by pgeorges-dpt** [comment]
Any news concerning this bug? With our launch date approaching, this is definitely a problem.

**Comment by cardex107** [comment]
You try test other version? GVR (0.9.1 - 0.9.0 - 0.8.5) all from August and September of 2016.

**Comment by technik** [comment]
GVR 1.0.3 with Unity 5.5 works fine for me. But that's the most recent version that seems to work.

**Comment by miraleung** [comment]
Could you please post a stacktrace of the crash?

**Comment by pgeorges-dpt** [comment]
01-26 20:07:29.133 15059 15083 F libc    : Fatal signal 11 (SIGSEGV), code 2, fault addr 0x13013000 in tid 15083 (UnityMain)
01-26 20:07:29.183  3486  4478 D libgps  : OnGpsExtensionMessage: message_id(1), data(0x7f73278a44), size(2432)
01-26 20:07:29.183  3486  4478 D libgps  : GpsiHook: API: gpsSvStatusCb(GpsiHookStateGps: e,c,g)
01-26 20:07:29.183  3486  4478 D libgps  : proxy__gps_sv_status_cb : called
01-26 20:07:29.203  3059  3059 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-26 20:07:29.203  3059  3059 F DEBUG   : Build fingerprint: 'samsung/zerofltedv/zeroflte:6.0.1/MMB29K/G920IDVS3EPK1:user/release-keys'
01-26 20:07:29.203  3059  3059 F DEBUG   : Revision: '11'
01-26 20:07:29.203  3059  3059 F DEBUG   : ABI: 'arm'
01-26 20:07:29.213  3059  3059 F DEBUG   : pid: 15059, tid: 15083, name: UnityMain  >>> co.dpt.theenemy <<<
01-26 20:07:29.213  3059  3059 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x13013000
01-26 20:07:29.253  3059  3059 F DEBUG   :     r0 00096933  r1 12f6a608  r2 00000000  r3 13013000
01-26 20:07:29.253  3059  3059 F DEBUG   :     r4 12f6a607  r5 00002800  r6 13013000  r7 eea57e68
01-26 20:07:29.253  3059  3059 F DEBUG   :     r8 f483ce78  r9 f48da928  sl 12f73700  fp eea57e6c
01-26 20:07:29.253  3059  3059 F DEBUG   :     ip 00002800  sp eea57e2c  lr f4650751  pc f474351c  cpsr 20070030
01-26 20:07:29.263  3059  3059 F DEBUG   : 
01-26 20:07:29.263  3059  3059 F DEBUG   : backtrace:
01-26 20:07:29.263  3059  3059 F DEBUG   :     #00 pc 0036e51c  /system/lib/libart.so (_ZN3art14CountUtf8BytesEPKtj+15)
01-26 20:07:29.263  3059  3059 F DEBUG   :     #01 pc 0027b74d  /system/lib/libart.so (_ZN3art3JNI17GetStringUTFCharsEP7_JNIEnvP8_jstringPh+344)
01-26 20:07:29.263  3059  3059 F DEBUG   :     #02 pc 0099ca88  /data/app/co.dpt.theenemy-1/lib/arm/libunity.so
01-26 20:07:30.063  3066  3650 I AudioFlinger: BUFFER TIMEOUT: remove(4098) from active list on thread 0xef000000
01-26 20:07:30.083  3066  3519 I APM::AudioPolicyManager: stopOutput() output 2, stream 3, session 32
01-26 20:07:30.143  3059  3059 F DEBUG   : 
01-26 20:07:30.143  3059  3059 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_01
01-26 20:07:30.143  3059  3059 E DEBUG   : AM write failed: Broken pipe
01-26 20:07:30.143  3059  3059 E         : ro.product_ship = true
01-26 20:07:30.143  3059  3059 E         : ro.debug_level = 0x4f4c
01-26 20:07:30.143  3059  3059 E         : sys.mobilecare.preload = false

**Comment by miraleung** [comment]
This crash doesn't look related to the GVR platform - looks like it's coming from libart.so and libunity.so.

**Comment by Enumio** [comment]
I can confirm crash too. I am using unity 5.5.1f1 and Gvr 1.20 

App works in editor and build is succsessfull but on the phone it crashes on launch.

**Comment by MertMG** [comment]
i have similar issue app work on editor perfect but when i load it to phone it fails. 5.5.1f and gvr1.20 so annoying

**Comment by synthercat** [comment]
@Enumio @MertMG Have you tried to do this with an almost empty project?

**Comment by MertMG** [comment]
YES. start from scratch put GVR 1.20 on it and it fails. when i put Oculus on it it works.

**Comment by synthercat** [comment]
@MertMG there is your problem mate : 
In order to use the GVR 1.20 you should NOT have ticked Oculus VR API on the player settings. If you say it works on Oculus I guess you also have the Oculus VR SDK

**Comment by MertMG** [comment]
i know it mate :1st_place_medal:  i test it Oculus with Virtual reality option and it worked but when i cancel it to work with Google VR 1.20 app crashes. its working with 1.03 by the way. also it worked before on 1.20 but i couldn't understand the problem yet. 

simply i put both SDK in to test and works with Oculus for Gear Vr all the time but GVR fails for some reason. i did tried it several times on several different NEW project setups. step by step but it crashes for some reason when its on GVR 1.20.

**Comment by ideoservo** [comment]
Hello I have the same kind of issue. Did someone find a way to solve it ?
If I use GVR 1.20 alone, it works on my android device (I'm using unity 5.4.1 and MacOSX).
When I put IVR (idealens vr kit) + GVR together IVR version works fine but GVR fails (the app starts on my android device, I see black vr screen  setup + hear sound during about 1 second then the app closes immediately).
Maybe GVR does not like when another vr dev kit (oculus, IVR...) is linked to the app at the same time ? Both versions works fine in editor. I'm going to try an upgrade to a more recent version of unity.
