### ISSUE TITLE
GvrAudioSource won't play if MinDistance is 0

### ISSUE THREAD

**Issue by thesambassador** [googlevr/gvr-unity-sdk#425]
Steps:  Set the MinDistance to 0 on a GvrAudioSource.  The sound will not play.  If you change it back to 1, it will.

Context: I'm updating from a pretty old version of Cardboard SDK (before things changed to Gvr) and the old "CardboardAudioSource" seemed to default to a value of 0 for minDistance, and I never changed it.  Now I've updated to the newer SDK, and all those sounds won't play since they have a minDistance of 0.  I will change all of them, but this seems like an annoying oversight.

**Comment by anokta** [comment]
Hi,

This is an intended behavior. We have recently updated the audio source distance attenuation methods to match Unity's AudioSource component (which gives silence for when minDistance is 0) - as of GVR Unity SDK v1.10.0 (7daef33183bbc70cbdfb33e5e7487ba7f9e6678b).  

FYI, the minDistance value is set to 1 as default, so the values should be updated automatically from 0 to 1, unless you modified them manually.

Sorry for the inconvenience.

**Comment by alimoeeny** [comment]
@thesambassador you are a hero, I've been trying to find out why some of my audio works and some does not, for days, and you saved me. Thank you.
