### ISSUE TITLE
There is no Cardboard or Daydream in "Virtual Reality Supported" settings,There are only three items: Oculus, Split Stereo Display, None.

### ISSUE THREAD

**Issue by cxy200927099** [googlevr/gvr-unity-sdk#426]
when i import the GVR SDK(1.10) to unity 5.4.1f1, then build android apk , And i follow the doc [https://developers.google.cn/vr/unity/get-started](url), but there is no Cardboard or Daydream in "Virtual Reality Supported" settings,There are only three items: Oculus, Split Stereo Display, None.
Can anyone help me ? thanks very much
![Uploading noCardboard.png…]()

**Comment by nathanmartz** [comment]
Those instructions are for the Daydream Technical preview, not 5.4.1.
