### ISSUE TITLE
Help: Where to download GVRVideoPlayer.unitypackage

### ISSUE THREAD

**Issue by Yfy1177** [googlevr/gvr-unity-sdk#427]
I use Google VR SDK for Unity v1.10  run VideoDemo (Daydream/Cardboard),but show "Video Support libraries not found or could not be loaded! Please add the GVRVideoPlayer.unitypackage to this project",GVRVideoPlayer.unitypackage is missing,where to download this unitypackage?Does anyone know?

**Comment by nathanmartz** [comment]
The SDK includes that unitypackage. Just unpack it into the main project.

**Comment by Yfy1177** [comment]
Oh, I found it. Thank you very much!
