### ISSUE TITLE
Add API to disable or recognize Home button press

### ISSUE THREAD

**Issue by alanlee-gn** [googlevr/gvr-unity-sdk#428]
This is not a standard usecase and maybe out of scope of the GVR SDK itself but below is a feature request for Daydream.

When doing demo to multiple users, especially to folks who have never used Google Daydream, it is not rare to find people who have jumped to the Daydream main screen by accidentally hitting the Home button. It usually takes some time to figure this out even if there is person helping out due to lack of visibility into what the VR user is actually doing.
Providing a way to disable the Home button (but not the re-centering) or showing a pop-up asking the users if they want to exit would be nice. At least add some audio cue so someone nearby can hear and know that someone has exited the app and need to take action.

**Comment by nathanmartz** [comment]
We appreciate the feedback and are looking into ways to minimize Home button false positives, but we don't plan to allow apps to disable the home button programatically.

**Comment by alanlee-gn** [comment]
> we don't plan to allow apps to disable the home button programatically
Thanks. I think that is reasonable.
Anyway glad to know you are thinking about the problem.
