### ISSUE TITLE
VideoDemo unable to load gvrvideo.dll

### ISSUE THREAD

**Issue by brianytang** [googlevr/gvr-unity-sdk#430]
Currently seeing "Video Support libraries not found or could not be loaded! Please add the GVRVideoPlayer.unitypackage to this project" when running the VideoDemo scene.

As requested by @claywilkinson :
Contents of Assets/Plugins/Android/
![image](https://cloud.githubusercontent.com/assets/4053667/21668193/55aacc96-d2b4-11e6-8238-d10f5e3f3ecf.png)

Logcat:

> 01-04 19:50:41.887 30145 30273 W Unity   :
01-04 19:50:41.887 30145 30273 W Unity   : (Filename:  Line: 1746)
01-04 19:50:41.887 30145 30273 W Unity   :
01-04 19:50:52.642 30145 30161 I Unity   : GVR Unity SDK Version: 1.1
01-04 19:50:52.642 30145 30161 I Unity   :
01-04 19:50:52.642 30145 30161 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-04 19:50:52.642 30145 30161 I Unity   :
01-04 19:50:52.846 30145 30161 E Unity   : Unable to find gvrvideo
01-04 19:50:52.897 30145 30161 E Unity   : System.DllNotFoundException: gvrvideo
01-04 19:50:52.897 30145 30161 E Unity   :   at (wrapper managed-to-native) GvrVideoPlayerTexture:CreateVideoPlayer ()
01-04 19:50:52.897 30145 30161 E Unity   :   at SwitchVideos.Awake () [0x00000] in <filename unknown>:0
01-04 19:50:52.897 30145 30161 E Unity   :
01-04 19:50:52.897 30145 30161 E Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-04 19:50:52.897 30145 30161 E Unity   :
01-04 19:50:52.914 30145 30161 I Unity   : Initializing Daydream controller API.
01-04 19:50:52.914 30145 30161 I Unity   :
01-04 19:50:52.914 30145 30161 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-04 19:50:52.914 30145 30161 I Unity   :
01-04 19:50:53.033 30145 30161 I Unity   : Creating and initializing GVR API controller object.
01-04 19:50:53.033 30145 30161 I Unity   :
01-04 19:50:53.033 30145 30161 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-04 19:50:53.033 30145 30161 I Unity   :
01-04 19:50:53.063 30145 30161 I Unity   : VrCore client API version: 11
01-04 19:50:53.063 30145 30161 I Unity   :
01-04 19:50:53.063 30145 30161 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-04 19:50:53.063 30145 30161 I Unity   :
01-04 19:50:53.063 30145 30161 I Unity   : GVR API successfully initialized. Now resuming it.
01-04 19:50:53.063 30145 30161 I Unity   :
01-04 19:50:53.063 30145 30161 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
01-04 19:50:53.063 30145 30161 I Unity   :
01-04 19:50:53.065 30145 30161 I Unity   : GVR API resumed.
01-04 19:50:53.065 30145 30161 I Unity   :
01-04 19:50:53.065 30145 30161 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Appears I'm missing the gvrvideo.dll -- except I'm not sure where to find that. Importing GoogleVRForUnity I see GvrVideoPlayer.unitypackage, I'm assuming by importing everything that should be imported as well?

**Comment by claywilkinson** [comment]
You'll need to import the video package as well.

**Comment by brianytang** [comment]
OK that was a silly mistake on my part. Thanks!

**Comment by claywilkinson** [comment]
No worries! Glad it is working now!

**Comment by Peanutbutteer** [comment]
I has this problem but i ready import GvrVideoPlayer.package how to resolve this

**Comment by Grakou** [comment]
@claywilkinson By importing the video package you mean the 'GVRVideoPlayer.unitypackage'? I've already done this and still get the same error message as @brianytang. I'd really appreciate help on this.

**Comment by perqa** [comment]
@Grakou, @Peanutbutteer, @claywilkinson 
I opened a new issue for this, including all details. It still does not work after importing GVRVideoPlayer.unitypackage.
https://github.com/googlevr/gvr-unity-sdk/issues/467
