### ISSUE TITLE
Left eye black in some devices

### ISSUE THREAD

**Issue by MephestoKhaan** [googlevr/gvr-unity-sdk#431]
After updating to 1.10 I am getting a black camera in the left eye in the Galaxy Note 4. But not the S6 for example.

It seems to be related to AA, if I disable it it works fine (but looks bad).

**Comment by bopangzz** [comment]
Which version of Unity you are using? Is it a Daydream Technique preview version?

**Comment by MephestoKhaan** [comment]
No, I am using 5.4.2. With the Daydream preview I have a weird shuttering when moving the head, even tho it says 60 fps. 

This was working fine before the upgrade to 1.10

**Comment by miraleung** [comment]
Does the whole scene stutter? We're investigating a fix for one kind of judder in an upcoming release.

For the black eye issue, please try updating to 1.20.

**Comment by chao0707** [comment]
I did some tests and found why left eye freeze or black in Unity.
When you have any light cast dynamic shadow,
Left eye sight will becomel black(when shadow appear) or freeze(shadow in initial view)
Static shadow won't cast this error.
My device is iPhone6+ iOS with 10.2.1
Unity 5.5.2f1
Google VR SDK 1.30
