### ISSUE TITLE
How can I change the eyes position?

### ISSUE THREAD

**Issue by xdestiny110** [googlevr/gvr-unity-sdk#436]
For some reason, I want to change the eyes position. In other words, I want to use my head model instead of native model.
Is anyone can help?

**Comment by bopangzz** [comment]
I assume you are using the Daydream Technique preview version of Unity? If so, you can try to disable the built in neck model by setting InputTracking.disablePositionalTracking = true and modify your camera position.

**Comment by xdestiny110** [comment]
That's right! Thx~
