### ISSUE TITLE
Go back to Android 4.1 as the minimum version required for Google Cardboard

### ISSUE THREAD

**Issue by chelder86** [googlevr/gvr-unity-sdk#439]
The previous versions Google Cardboard were set for Android 4.1 and above. Actually, [the official help still says 4.1](https://support.google.com/cardboard/answer/6295091?hl=en&ref_topic=6295055), and [the official Cardboard App is also set for 4.1 and above](https://play.google.com/store/apps/details?id=com.google.samples.apps.cardboarddemo). 

Moreover, I have [compiled an app using gvr-unity-sdk for I client with a 4.1 Android device, and it's working perfectly in its device](http://stackoverflow.com/a/41534514/1198404).

So why not going back to Android 4.1? Is there any reason? Maybe it seemed a good decision going from 4.1 to 4.4 in the past because some reason, but it turned out unnecessary finally.

**Comment by bopangzz** [comment]
We uses some level-19 APIs in our sdk so it is not guaranteed to work with pre-19 target. You should set 19 as your minimal target for cardboard.
