### ISSUE TITLE
Android Manifest android:targetSdkVersion="24" not "22"

### ISSUE THREAD

**Issue by fredlemieux** [googlevr/gvr-unity-sdk#440]
I cannot build and run GVR app on the phone unless I change the android:targetSdkVersion="22" to android:targetSdkVersion="24" in the Android Manifest file.  

Can this be updated in the UnityPackage file in the GitRepo?

**Comment by bopangzz** [comment]
Which version of Unity are you using? Are you using the Daydream Technical preview version?

**Comment by mitt8** [comment]
I had the same issue with Unity 5.5 no technical preview.

**Comment by miraleung** [comment]
The minimum supported Android API level for Daydream is 24, and currently only the technical preview and 5.6.0b3+ have Daydream support. Cardboard supports 19+.

**Comment by LineKernel** [comment]
how do i get to compile for cardboard (sdk19)? 
whatever i do it asks for sdk24 if i use your 5.4.2f2-GVR13 daydream autoinstall 
or cant set the vritual reality sdk to cardboard (not in list) if use another version of unity with GoogleVRForUnity.unitypackage alone
