### ISSUE TITLE
Unity5.5, iOS10 Google VR crashes on resume.

### ISSUE THREAD

**Issue by itoh99** [googlevr/gvr-unity-sdk#441]
The VR app we are currently developing crashes when it resumes after being suspended by pressing the power button down during the app running. Google's sample code "HeadsetDemo" also crashes in the same way. The app runs in the environment below:  
 
Google SDK 1.0 
Unity 5.5 
iOS10 
 
Does anyone have any idea what causes this trouble? Thank you.

**Comment by bopangzz** [comment]
Thanks for the bug report. We will look into this on our side.

**Comment by massoul** [comment]
@miraleung Is this fixed in a new release? I'm having the same problem and would like to know if upgrading to the latest version will fix it. Thanks!

**Comment by miraleung** [comment]
We have not been able to repro in 1.40, so it may likely be fixed. 

Heads up: Please note that our upcoming version (1.50) will support only Unity 5.6 and above.
