### ISSUE TITLE
Unity 5.5 - Namespace errors in GvrViewer.cs 

### ISSUE THREAD

**Issue by johannesleander** [googlevr/gvr-unity-sdk#442]
While trying to set up a GVR Project in Unity 5.5, after importing GVR 1.1.0 unity package and loading up any of the demo scenes, the editor throws multiple namespace errors from GvrViewer.cs.  These include not being able to find static class StereoController or GvrProfile.

Assets/GoogleVR/Scripts/GvrViewer.cs(69,17): error CS0246: The type or namespace name `StereoController' could not be found. Are you missing an assembly reference?

Assets/GoogleVR/Scripts/GvrViewer.cs(84,18): error CS0246: The type or namespace name `StereoController' could not be found. Are you missing an assembly reference?

Assets/GoogleVR/Scripts/GvrViewer.cs(157,10): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing an assembly reference?

Assets/GoogleVR/Scripts/GvrViewer.cs(171,11): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing an assembly reference?

Assets/GoogleVR/Scripts/GvrViewer.cs(174,10): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing an assembly reference?

Assets/GoogleVR/Scripts/GvrViewer.cs(188,11): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing an assembly reference?

Assets/GoogleVR/Scripts/GvrViewer.cs(192,18): error CS0246: The type or namespace name `BaseVRDevice' could not be found. Are you missing an assembly reference?

Assets/GoogleVR/Scripts/GvrViewer.cs(253,10): error CS0246: The type or namespace name `GvrProfile' could not be found. Are you missing an assembly reference?

**Comment by mitt8** [comment]
Unity 5.5 is not a Daydream technical preview version therefore some extra scripts are required. Please follow solution in [this link](http://stackoverflow.com/questions/40249606/google-vr-sdk-wont-compile)

**Comment by bopangzz** [comment]
Yeah, if you are not using a Daydream Technical preview version, you need to import the GVRBackwardsCompatibility package.

**Comment by johannesleander** [comment]
Suggested solution did not solve problem. Are there any other actions needed other than importing BackwardsCompatability package?
