### ISSUE TITLE
How to hide the daydream controller in GVR Unity SDK v1.10.0

### ISSUE THREAD

**Issue by futer24** [googlevr/gvr-unity-sdk#445]
Hi

The most easy way is enable or disable GvrControllerPointer prefab.

In the sdk there's a property that could be useful for change the alpha for arm model and reticle,
but it has a private set.

Thanks and good work!

**Comment by miraleung** [comment]
Thanks for your feedback. If you would like to hide just the controller visual object, but not the laser and the wrist offset, you can disable GvrControllerPointer > Controller > ddcontroller.

What is your use case for changing the reticle's alpha? 

Could you please clarify what you meant by changing the alpha for the arm model?

**Comment by futer24** [comment]
Hi

I meant, for a video 360 example: you dont want to show the controller model , laser and reticle unless you press a controller button for show the ui and the controller model , laser and reticle again, no? but what happens if you want to do it smoothly with the alpha, with the actual sdk code, you can't. The materials of components mentioned are directly controlled by private sdk code (it changes the alpha material when the controller is near to head)

Thanks

**Comment by miraleung** [comment]
Thanks @futer24. To clarify, is your feature request for external access to the alpha value for all controller visual components, including the laser and reticle?

**Comment by futer24** [comment]
That is correct

**Comment by miraleung** [comment]
Thanks, we'll look into this.
