### ISSUE TITLE
GVR Audio Renderer not found iOS

### ISSUE THREAD

**Issue by isaacengel** [googlevr/gvr-unity-sdk#446]
I am tinkering with the sample project "SpatialAudio" for iOS. I built it in unity using the latest GVR SDK, so I had to replace a few deprecated keywords (GvrAudioSource instead of CardboardAudioSource, etc.)
If I build it in Xcode just as Unity gives it to me, it runs fine in the physical device.
Then, I tried to edit the file 'main.mm' to change the default App Controller (UnityAppController) to a new one, which I will call NewAppController.
```
// main.mm
...
const char* AppControllerClassName = "UnityAppController";
...
//UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:AppControllerClassName]); // old
UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:"NewAppController"]); // new
```
NewAppController is a class which inherits from UnityAppController and does not override any of its methods or properties, like this:
```
// NewAppController.h
@interface NewAppController : UnityAppController
@end
```
```
// NewAppController.mm
@implementation NewAppController
@end
```
I thought that it should work exactly the same as before, but now I get the following warning in runtime:
"Audio effect GVR Audio Renderer could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly."
Everything else works just fine: I can see the video and even hear the sounds, but only they are not 'spatialized'.

GVR SDK 1.1
Unity 5.5.0f3
iOS 10.1.1

**Comment by isaacengel** [comment]
I found the solution. I was missing two important things:
First, messing with main.mm causes a lot of trouble. The correct approach for defining a custom App Controller is to create a subclass of UnityAppController and adding the macro IMPL_APP_CONTROLLER_SUBCLASS(name_of_the_class) at the bottom of its .mm file.
Second, Unity automatically generates a custom app controller, called CardboardAppController, which is located in the build directory, under 'Libraries/Plugins/iOS'. One of its functions is registering the unity audio effect plugin. I was bypassing this file without knowing, causing the audio renderer to not initialize properly. So my solution was to comment out the macro at the end of the file CardboardAppController.mm (line 71):

` //IMPL_APP_CONTROLLER_SUBCLASS(CardboardAppController)`

And defining the new custom controller as a subclass of CardboardAppController:

```
 #import "CardboardAppController.h"
 
 @interface NewAppController : CardboardAppController
 @end
 
 @implementation NewAppController
 @end
 IMPL_APP_CONTROLLER_SUBCLASS(NewAppController)
```

**Comment by anokta** [comment]
Glad to hear you already figured out the problem! And I can verify that your approach indeed is the recommended solution for this, as the GVR native audio plugin library still needs to be linked explicitly via the controller code for iOS.

Cheers
