### ISSUE TITLE
GVRVideoPlayerTexture.cs does not load properly everytime I start a new project in Unity

### ISSUE THREAD

**Issue by pratham2504** [googlevr/gvr-unity-sdk#447]
This is the error that it gives:
Assets/GoogleVR/Scripts/Video/GvrVideoPlayerTexture.cs(595,7): error CS1622: Cannot return a value from iterators. Use the yield return statement to return a value, or yield break to end the iteration

I have to add yield return instead of the already present return statement. Please look into it.

I'm attaching a screenshot for reference..
![screen shot 2017-01-22 at 7 17 11 pm](https://cloud.githubusercontent.com/assets/20544040/22182955/359bb460-e0d8-11e6-98ba-cf9360c935ea.png)

**Comment by macsche** [comment]
I do have exactly the same problem. But to be honest I just downloaded unity and loaded the Google VR SDK for Unity and started the Assets > GoogleVR > Demos > Scenes > GVRDemo and tried to start it, but this Error came up. 

Do I miss something?

**Comment by macsche** [comment]
Found the solution in this thread:

https://github.com/googlevr/gvr-unity-sdk/issues/406

**Comment by weizaishouex2010** [comment]
just delete the sentence "return false" or annotate it
