### ISSUE TITLE
UI Overlay Missing

### ISSUE THREAD

**Issue by bitdelve** [googlevr/gvr-unity-sdk#450]
I am having an issue where the UI Overlay is missing on iPhone and Android. I am using an older version of the sdk, but I also tried upgrading to the newest version and it still doesn't show. I am using unity 5.4.1f1. I am not sure of the version of the Gvr SDK is that I am using. Any ideas on what could be the cause?

Just to clarify the overlay I am talking about, it is the one with the gear at the bottom middle, the center alignment line, and the back button at the top left. It's not so much a worry for android as it has a built in back button, but iOS only has the home button.

**Comment by miraleung** [comment]
The current UI layer has a short divider on the bottom, with an X on the top left corner and the gear button on the top right. Could you please confirm if that's what you're seeing?

**Comment by bitdelve** [comment]
On mobile there is nothing at all. For both iOS and Android. The only time I see anything is in the Unity player
