### ISSUE TITLE
Scripts not loading

### ISSUE THREAD

**Issue by perqa** [googlevr/gvr-unity-sdk#454]
I installed GoogleVRForUnity.unitypackage and am trying to run the VideoDemo, but some 30 scripts associated with various gamobjects are not loading, just one example here for brevity:

`The referenced script on this Behaviour (Game Object 'MenuBar') is missing!`

Running the project results in this error message (in scene):
`Video support libraries not found or could not be loaded. Please add the GVRVideoPlayer.unitypackage to this project.`

The GVRVideoPlayer package has been installed, and re-imported, but that doesn't help.
All of these scripts seem to start with:
`#if UNITY_HAS_GOOGLEVR && (UNITY_ANDROID || UNITY_EDITOR)`
so I guess the condition is false, but what can I do about it?

I also get this error message:
`Couldn't open /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/VR/OSXUniversal/OVRPlugin.bundle/Contents/MacOS/OVRPlugin, error: dlopen(/Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/VR/OSXUniversal/OVRPlugin.bundle/Contents/MacOS/OVRPlugin, 2): Library not loaded: @rpath/LibOVRRT_0.framework/Versions/5/LibOVRRT_0
  Referenced from: /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/VR/OSXUniversal/OVRPlugin.bundle/Contents/MacOS/OVRPlugin
  Reason: image not found`

**Platform**
- Unity 5.5.1f1
- OS X 10.11.6

**Comment by rusmaxham** [comment]
Unity 5.5 does not have Daydream support in it.  Daydream support is primarily available in Unity 5.4.2f2-GVR13 and in Unity 5.6 betas.

**Comment by perqa** [comment]
But I don't even want Daydream support. I'm only after Cardboard...

**Comment by rusmaxham** [comment]
The GVR Video Player is dependent upon Daydream support.

**Comment by perqa** [comment]
I got rid of most warnings and error messages by starting a new project and importing the SDK again. The first project was created in Unity 5.4.1, which was then updated to 5.5.1. Re-importing the SDK did not help in that case, but starting a new project from scratch did.

However, I still get the message `Video support libraries not found or could not be loaded. Please add the GVRVideoPlayer.unitypackage to this project.` when running the VideoDemo project in Unity, or on a non-Daydream device. Is there a spherical VR video demo for Cardboard?

**Comment by rusmaxham** [comment]
I'm sorry to report that the GVR Video Player is not yet supported on Cardboard at this time.

**Comment by perqa** [comment]
By downloading Unity 5.6 beta and starting a new project, I managed to get rid of most problems reported here. However, one remains. I will close this issue and open a new with just this one.
