### ISSUE TITLE
when in the mode gvrviewermain, can not turn the head 'up and down'

### ISSUE THREAD

**Issue by zhao-zilong** [googlevr/gvr-unity-sdk#455]
I use Unity3D in MAC, my problem is when I use gvrviewermain and fpscontroller  together, I can not look up and down with my mouse, but if I delete gvrviewermain,  It works perfect, so is there something I missed to configurate?
Thanks in advances

**Comment by martinbilello** [comment]
Which version of Unity are you using?

**Comment by zhao-zilong** [comment]
5.4.2f2 personnel 
I have a thought that maybe because the gvrviewermain demand the rotation information from headset, not from mouse, but I really do not have a clue where should I touch the code

**Comment by martinbilello** [comment]
Is this happening on the device or on the Unity Editor?

**Comment by zhao-zilong** [comment]
Unity editor, I am not passing to android device

**Comment by miraleung** [comment]
Are you targeting the Android platform?

**Comment by zhao-zilong** [comment]
no, just want to test in unity

**Comment by miraleung** [comment]
You will  need to switch platform to Android (Ctrl+Shift+B, select Android, click on "Switch Platform") for GvrViewerMain emulation to work.
