### ISSUE TITLE
Unity Terrain not working

### ISSUE THREAD

**Issue by alxvrgames** [googlevr/gvr-unity-sdk#458]
Unity terrain causes the app to crash after splash screen.

**Comment by martinbilello** [comment]
Which version of Unity are you using? Which platform are you building to? Which Terrain are you referring to?

Thanks

**Comment by alxvrgames** [comment]
I am using Unity version 5.4.2f2 building on the android platform. I am
using the built in unity terrain. When the terrain is in my scene the game
crashes.

**Comment by alxvrgames** [comment]
I am on GVR 1.20

**Comment by alxvrgames** [comment]
@martinbilello

**Comment by miraleung** [comment]
Thanks for the report, we're investigating internally.

**Comment by alxvrgames** [comment]
@miraleung can you notify me when you have a solution? I need this to work for my current project.

**Comment by miraleung** [comment]
I tried adding a Terrain to the ScrollingUIDemo, on 5.4.2f2-GVR13, built and ran on Android, and I couldn't repro a crash. Could you please paste the full stacktrace of the crash?

**Comment by alxvrgames** [comment]
My terrain is 1000x1000 that's probably why it's crashing. I will try again
with a smaller terrain.

**Comment by alxvrgames** [comment]
@miraleung Unfortunately I cannot. I dont have the capability to debug my app.

**Comment by chaosemer** [comment]
@alxvrgames, you can get a stack trace by running `adb logcat` in a terminal. When your app crashes you'll see a stack trace along with a brief memory dump. Could you please share that with us here?

**Comment by alxvrgames** [comment]
I would but I don't have a USB cord to set up adb

**Comment by chaosemer** [comment]
Forgive me for the silly question, but how did you install your app?

**Comment by alxvrgames** [comment]
Thats not silly. I had to use an SD card. My phone uses USB c and I don't
have an a to c cord. Unless other people are having this problem you
shouldn't wo try too much about it. I have started another project.

**Comment by chaosemer** [comment]
If you end up with access to a USB C cord, please feel free to reopen with a report.
