### ISSUE TITLE
GVRVideoPlayer iOS Support?

### ISSUE THREAD

**Issue by stuartsoft** [googlevr/gvr-unity-sdk#459]
I'm working on a Daydream/Cardboard app that includes several videos. I've had no issues building and running my app on my Pixel phone in both Daydream and Cardboard, however I have not been able to get the gvr video player to run under iOS. I imagine this is because exoplayer and gvrvideo don't have library files for the iOS platform.

Are there any work arounds for getting 360 videos to play on Cardboard on iOS using Unity? [Perhaps Google should document that their gvrVideo player solution only works on Android atm (at least until iOS gets exoplayer)](https://developers.google.com/vr/video/video-overview)

**Comment by rusmaxham** [comment]
The GVR Unity Video plugin only supports Daydream at this time.  We will update our documentation accordingly.  In the meantime, here is a site that discusses various video plugins for Unity.  http://blog.soom.la/2015/07/top-10-unity-video-plugins.html

**Comment by stuartsoft** [comment]
Okay, thank you :)

**Comment by Neogene** [comment]
I hope this will be sbe supported soon, native iOS library has, native android has, unity android has, the only one is IOS unity.
