### ISSUE TITLE
[ Mac ] [ Unity 5.3.7f1 ] [ iOS Platform ] [ iPhone 7 ] Display noise when switch different scenes.

### ISSUE THREAD

**Issue by ayo1103** [googlevr/gvr-unity-sdk#460]
![snip_20170207124755](https://cloud.githubusercontent.com/assets/2675359/22679990/b752d2f8-ed40-11e6-8b88-0c7df51a7560.png)
[ Using LoadLevelAsync() & LoadLevel() )

iPhone 6 & iPhone 6 Plus has no above issue.
Only on **iPhone 7 ( iOS version : 9.0 )**

We are using Unity Cardboard SDK v1.20.

Does someone know what happened? 
Or any suggestion to solve this problem?

Please help us!
Thanks!

**Comment by chimerakang** [comment]
this is one of distortion bug.
I fix this bug, see below:

https://forum.unity3d.com/threads/mac-unity-5-3-7f1-ios-platform-iphone-7-display-noise-when-switch-different-scenes.455113/

**Comment by ayo1103** [comment]
Thanks so much!!

**Comment by nadiacw** [comment]
I have this problem too. @chimerakang Thanks for the fix! But this should be fixed and implemented in the GoogleVR sdk.
