### ISSUE TITLE
GVR Video Library not found in Cardboard app

### ISSUE THREAD

**Issue by MatthewMedic** [googlevr/gvr-unity-sdk#461]
Using GVR SDK v1.2.0, and I have imported the separate GVRVideoPlayer.unitypackage.

Project settings:
![image](https://cloud.githubusercontent.com/assets/165922/22810731/5f32502a-eeef-11e6-88bd-8bb359215caa.png)

Plugins folder:
![image](https://cloud.githubusercontent.com/assets/165922/22810758/79a54e26-eeef-11e6-9008-9e9529d53fa4.png)

I build a project containing only the unmodified VideoDemo scene and run it on a Galaxy Note 5 running Android 6.0.1.

I get the following exception in my log: 
Unable to find gvrvideo
System.DllNotFoundException: gvrvideo
  at (wrapper managed-to-native) GvrVideoPlayerTexture:CreateVideoPlayer ()
  at SwitchVideos.Awake () [0x00000] in <filename unknown>:0

I opened the APK in 7zip and I checked the apk/lib/armeabi-v7a/ and I see libgvrvideo.so in there, so it is including it.

**Comment by MatthewMedic** [comment]
I want to add: This is on Unity 5.6.0b7, but I have tested the same project with the exact same setup on Unity 5.4.2 GVR13 and I have the same results.

**Comment by miraleung** [comment]
Hmm, I was just able to build the VideoDemo today. Could you please try reimporting everything (Assets > Reimport All)?

**Comment by MatthewMedic** [comment]
I am able to build the apk and run it, but I get a default skybox and a message saying to import the video libraries .unitypackage when I try to play any of the videos, along with that DllNotFoundException

I tried Reimport all, and deleting the library, neither seem to have any effect.

Are you building for Daydream or Cardboard? I do see through google searches that some people have had this issue then managed to get this working, but no info on their setup or what they did to fix this issue.

**Comment by perqa** [comment]
I filed a highly related bug (possible duplicate) on this topic yesterday, including some more details: https://github.com/googlevr/gvr-unity-sdk/issues/467

**Comment by MatthewMedic** [comment]
#467 does appear similar, however I don't have anything like the line
`02-15 10:57:33.804 17767 17782 D Unity   : Unable to load library '/data/app/***.****.gvr-1/lib/arm/libgvrvideo.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_atexit" referenced by "/data/app/***.****.gvr-1/lib/arm/libgvrvideo.so"` in my logcat output.

Which device are you attempting to run on?

**Comment by MatthewMedic** [comment]
#467 does appear to be the same issue.

After more investigating I believe it may be related to the sdk version for the video player libraries. 

I noticed that without sdk version 24 installed on the build machine builds fail at the manifest merge check because gvr-exoplayersupport-release.aar is built with a target SDK version of 24.

**Comment by leon503** [comment]
I tried gvr for unity 1.20, the issue still exists.
however, i tried on Androind N device, it works.
It seems the so file cannot be correctly loaded below api24!

**Comment by miraleung** [comment]
If you have targetSdkVersion set to 24, with both Daydream and Cardboard enabled, you should still be able to deploy to devices that are lower than 24. This works on a Nexus 5 for me.

**Comment by devesh2605** [comment]
@miraleung Hi, I have tried building the demo app, It shows the same error . I have tried reimporting all the packages and assets, and even set the target SDK version to 24, but still can't get rid of the errors.

**Comment by miraleung** [comment]
Thanks everyone. We've found the issue, and the fix will be in our next update.
