### ISSUE TITLE
GVRViewerMain camera distorted about the middle of each lens

### ISSUE THREAD

**Issue by Frolicks** [googlevr/gvr-unity-sdk#464]
I also get the message: "VRDevice cardboard not supported in Editor Mode" in the console, along with several others.
![screenshot 253](https://cloud.githubusercontent.com/assets/10590936/22860489/402b4332-f0b4-11e6-9cd7-c36c30d57f7b.png)

I'm running the latest version of Unity 5.6 beta, GVR SDK 1.20, set the build platform to android, and added the Cardboard SDK on the player settings.

**Comment by synthercat** [comment]
Unity 5.6 has internal support for cardboard VR. If you went to the player settings and added Virtual Reallity support AND also used the googe GVR SDK (I see in the screenshot that you did use that) then you kind of added VR to your project twice... try removing the one from the playert settings or go to Unity 5.5.1f1

**Comment by VadimTikhonyuk** [comment]
Hi, I have same bug on 5.5, But in my case I use two cameras, one for UI, second for 3d Environment
So I just disable GvrEye and StereoRenderEffect on both eyes of UI Camera(this scripts instance at runtime)

**Comment by ghettokon** [comment]
I have same issue, even with the demos. However, it works fine as an app when I export it as an app. 
![ugzn6](https://cloud.githubusercontent.com/assets/3357944/22988091/01a2a894-f37f-11e6-9bda-b7826d95e302.jpg)

**Comment by miraleung** [comment]
The fix for 5.6 will be in our next release. In the meantime, #451 has the workaround.

For multiple cameras, you can use a native plugin with GL.IssuePluginEvent and detect which eye is rendering with viewport[i], where i == 0 for the left eye, and > 0 for the right.
