### ISSUE TITLE
What are "Video Content ID" and "Video Provider ID" ?

### ISSUE THREAD

**Issue by niusounds** [googlevr/gvr-unity-sdk#465]
The `GvrVideoPlayerTexture` script has two properties `Video Content ID` and `Video Provider ID`.
https://developers.google.com/vr/video/video-overview#player_properties
How do I use they for?

**Comment by claywilkinson** [comment]
The content ID and provider ID are needed in some cases when playing back video streams from a Content Delivery Network (CDN) with DRM enabled.  If you are not using DRM (which is not currently supported in the Unity SDK), you can safely leave these blank.

**Comment by niusounds** [comment]
Thanks!
