### ISSUE TITLE
No VR Rendering on Asus Zenfone2 ZE551ML

### ISSUE THREAD

**Issue by Dragonic89** [googlevr/gvr-unity-sdk#466]
Just tested the VR package with Unity 5.6.0b7 on my Asus Zenfone 2 ZE551ML (Android 5, Intel CPU).
GVR Unity SDK v1.20.0, GVRDemo scene, working on Editor (with the #451 issue), but no VR rendering on the smartphone, just a normal rendering as if without VR settings, and camera not updating when moving the device.

No problem on another Android device (Nexus 5) with the same APK.

**Comment by miraleung** [comment]
The Zenfone is still being brought up and is not stable - this is one of the issues being investigated. Thanks for bringing it to our attention.

**Comment by Millais** [comment]
FYI also seeing no VR rendering on the Nexus 6P when the APK gets deployed with the latest SDK. 

Apart from #451, the scene is fine in the 5.6.0b9 editor.
