### ISSUE TITLE
Video support libraries not found or could not be loaded

### ISSUE THREAD

**Issue by perqa** [googlevr/gvr-unity-sdk#467]
I am running Unity 5.6 beta on Mac and the GVRVideoPlayer package has been imported. I have built the VideoDemo sample scene for Cardboard on Android. According to the documentation:
"It works as either a Daydream or Cardboard application, depending on the Virtual Reality SDK selected under Player Settings."
Ref: https://developers.google.com/vr/unity/demos#gvrdemo

However, I get the following message in the built app on the phone:
`Video support libraries not found or could not be loaded. Please add the GVRVideoPlayer.unitypackage to this project.`

I primarily deployed to a Samsung S7 and also tried a Sony Xperia Z3 Compact.

**Contents of Assets/Plugins/Android:**
```
.
├── AndroidManifest-Cardboard.xml
├── AndroidManifest-Cardboard.xml.meta
├── AndroidManifest-Daydream.xml
├── AndroidManifest-Daydream.xml.meta
├── exoplayer-r1.5.11.aar
├── exoplayer-r1.5.11.aar.meta
├── gvr-exoplayersupport-release.aar
├── gvr-exoplayersupport-release.aar.meta
├── gvr-permissionsupport-release.aar
├── gvr-permissionsupport-release.aar.meta
├── libs
│   ├── armeabi-v7a
│   │   ├── libaudioplugingvrunity.so
│   │   ├── libaudioplugingvrunity.so.meta
│   │   ├── libgvrvideo.so
│   │   └── libgvrvideo.so.meta
│   ├── armeabi-v7a.meta
│   ├── x86
│   │   ├── libaudioplugingvrunity.so
│   │   ├── libaudioplugingvrunity.so.meta
│   │   ├── libgvrvideo.so
│   │   └── libgvrvideo.so.meta
│   └── x86.meta
├── libs.meta
├── proguard-gvr.txt
└── proguard-gvr.txt.meta
```

Running the build on a device, logcat outputs the following:

```
02-15 10:57:33.804 17767 17782 D Unity   : Unable to load library '/data/app/***.****.gvr-1/lib/arm/libgvrvideo.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_atexit" referenced by "/data/app/***.****.gvr-1/lib/arm/libgvrvideo.so"...
02-15 10:57:33.814 17767 17782 E Unity   : Unable to find gvrvideo
02-15 10:57:33.834 17767 17782 E Unity   : System.DllNotFoundException: gvrvideo
02-15 10:57:33.834 17767 17782 E Unity   :   at (wrapper managed-to-native) GvrVideoPlayerTexture:CreateVideoPlayer ()
02-15 10:57:33.834 17767 17782 E Unity   :   at SwitchVideos.Awake () [0x00050] in /Users/user/Workspace/GoogleVR 3/Assets/GoogleVR/Demos/Scripts/VideoDemo/SwitchVideos.cs:39 


02-15 10:57:33.914 17767 17782 E Unity   : Error obtaining VrCore client API version: UnityEngine.AndroidJavaException: com.google.vr.vrcore.base.api.VrCoreNotAvailableException: VR Service missing
02-15 10:57:33.914 17767 17782 E Unity   : com.google.vr.vrcore.base.api.VrCoreNotAvailableException: VR Service missing
02-15 10:57:33.914 17767 17782 E Unity   : 	at com.google.vr.vrcore.base.api.VrCoreUtils.getVrCoreClientApiVersion(SourceFile:131)
02-15 10:57:33.914 17767 17782 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
02-15 10:57:33.914 17767 17782 E Unity   : 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
02-15 10:57:33.914 17767 17782 E Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
02-15 10:57:33.914 17767 17782 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-15 10:57:33.914 17767 17782 E Unity   : 	at android.os.Looper.loop(Looper.java:158)
02-15 10:57:33.914 17767 17782 E Unity   : 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
02-15 10:57:33.914 17767 17782 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x0008c] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:25 
02-15 10:57:33.914 17767 17782 E Unity   :   at UnityEngine.AndroidJNISafe.CallStaticIntMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00011] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:256 
02-15 10:57:33.914 17767 17782 E Unity   :   at UnityEngine.A
02-15 10:57:33.914 17767 17782 I Unity   : GVR API successfully initialized. Now resuming it.


02-15 10:57:33.924  4827  4840 W ActivityManager: Unable to start service Intent { act=com.google.vr.vrcore.controller.BIND pkg=com.google.vr.vrcore VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} } U=0: not found
02-15 10:57:33.924 17767 17767 W ServiceBridge: Bind failed. Service is not available.
```

**Comment by leon503** [comment]
libgvrvideo.so can only be correctly loaded above api24! hope to be fixed.

**Comment by reubenkcoutinho** [comment]
Not sure if the issue is because the plugin begins with lib or ends with *.so. The [unity documentation](https://docs.unity3d.com/560/Documentation/Manual/PluginsForAndroid.html) says:
> Please note that PluginName should not include the prefix (‘lib’) nor the extension (‘.so’) of the filename.

**Comment by AayushU** [comment]
@reubenkcoutinho - That refers to this line:

"[DllImport ("PluginName")]"

you just put the name like "gvrvideo" instead of "libgvrvideo.so"

I can repro this issue as well. perqa - what device are you using to deploy?

**Comment by miraleung** [comment]
Did you set targetSdkVersion to 24? That should still deploy on devices with API level < 24.

**Comment by perqa** [comment]
@AayushU: Primarily a Samsung S7 (Android 7) but also a Sony Xperia Z3 Compact (Android 6.0.1).

**Comment by brianytang** [comment]
So if the issue you're having is the same as what mine was -- you literally just need to import GVRVideoPlayer.unitypackage. Basically, GoogleVRForUnity.unitypackage contains the GVRVideoPlayer.unitypackage but it does nothing after its imported. You need to specifically import it as its own custom package. It will be under Assets/GoogleVR/GVRVideoPlayer

**Comment by perqa** [comment]
I did this before filing this issue, but still the same problem. Also re-imported a few times, but no difference.

**Comment by devesh2605** [comment]
Can u check AndroidManifest.xml and AndroidManifest-Cardboard.xml under (ProjectName\Assets\Plugins\Android) and make sure the android:targetSdkVersion is 24

**Comment by devesh2605** [comment]
I have tried the VideoDemo Scene and It does not throw any of the above error and instead it gives this error: 

**UnassignedReferenceException: The variable touchPoint of GvrControllerVisual has not been assigned.
You probably need to assign the touchPoint variable of the GvrControllerVisual script in the inspector.
UnityEngine.GameObject.GetComponent[Renderer] () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GameObjectBindings.gen.cs:38)
GvrControllerVisual.Awake () (at Assets/GoogleVR/Scripts/Controller/GvrControllerVisual.cs:50)**

In the player setting, I choose to build for "CardBoard"

**Comment by devesh2605** [comment]
Hi @reubenkcoutinho ,

For this development, I am using the latest Version of GVR SDK and Unity 5.6.0b9.

1. I first added the GVRSDK under the asset panel and then added GVRVideoPlayer.unitypackage (Under Assets/GoogleVR). 
2. Then I opened the DemoVideo Scene and in order to build the apk I choose Android and made this changes in the player setting "Virtual Reality support" -> Cardboard.

If u need any help then please let me know I will share my code over Github. But first, the video demo should work.

Thanks,
Devesh V

**Comment by reubenkcoutinho** [comment]
@devesh2605 
I followed your steps and I get the following message in the built app on the phone:

> Video support libraries not found or could not be loaded. Please add the GVRVideoPlayer.unitypackage to this project.

Nothin seems to works though

I'm tried it on a Android 6.0.1 device

**Comment by devesh2605** [comment]
@reubenkcoutinho This is strange one of my colleague also tried the same step and he is also getting the same error as you are getting. I guess the SDK is not stable. I will share the screen shots on a dropbox link that you can follow and then let me know if it works or not?

Thanks,
Devesh V

**Comment by devesh2605** [comment]
@reubenkcoutinho Hi,

Check this link, I have taken the screenshots of each and every step, 

https://www.dropbox.com/sh/znwad4emj1q7o52/AADuBRpiZ1f-RAFcFiIbHNG3a?dl=0

Please follow them, I am also working on to get this issue fixed if this works for me then I will share the project and APK.

Thanks,
Devesh V

**Comment by devesh2605** [comment]
@perqa This is strange that no one from Google is supporting this issue..

**Comment by rusmaxham** [comment]
There is a known issue where the libgvrvideo.so only loads on devices that support API 24 (Android 7.0) and later.  It has been resolved and will be available in the next release of the GVR Unity SDK.

**Comment by reubenkcoutinho** [comment]
@perqa I recently got an OS update for Samsung S7 to Android version 24. I can verify it now runs and I can watch the video. The issue that now shows is that it asks me to load Google VR for Daydream from the play store.

**Comment by devesh2605** [comment]
@reubenkcoutinho This may be because you are building for Day Dream. You should build for Cardboard and in order to make it work for Cardboard, you will have to change the scripts.

Thanks,
Devesh V

**Comment by reubenkcoutinho** [comment]
@devesh2605 I tried setting VR support for Cardboard. Is there any other scripts you are talking about?

**Comment by simnys** [comment]
@devesh2605 Did you find a way around this?

**Comment by devesh2605** [comment]
@simnys Hi there,
I am waiting for the next update from Google. Right now I am using Easy Movie Textures and it supports all the need except it doesn't support Fragmented MP4 (FMP4), apart from that it plays everything (local or streaming). If you need any help in that let me know I will share the project. EasyMovieTextures is paid but I have a test copy of that also.

Regards,
Devesh Vyas

**Comment by devesh2605** [comment]
@reubenkcoutinho 
Hey Sorry for the late reply. You need to make changes in "GvrVideoPlayerTexture.cs".
I came up with a 360 video player using EasyMovieTextures, I can share the project if you want.

Regards,
Devesh V

**Comment by simnys** [comment]
@devesh2605 Hey, thanks for the reply, how did you go about getting a test copy of EasyMovieTextures?

**Comment by devesh2605** [comment]
@simnys Hey, I got through some connections man.

Regards,
Devesh V

**Comment by Selzier** [comment]
Cgpeers/cgpersia

**Comment by MrPatrickHenry** [comment]
@devesh2605 am i right in thinking you got streaming of video texture to work with easy movie texture would love to know how you did that I tried but it kept failing
I too can't get this demo, of google video on ios cardboard to run have the same error.

**Comment by devesh2605** [comment]
@MrPatrickHenry Hey Patrick, I am able to build the streaming video apps using Easy Movie Textures and Google VR SDK. I have both the projects, I will share the GitHub repo, with you.

Regards,
Devesh V

**Comment by Selzier** [comment]
Easy Movie Texture is a paid asset and not free to share on Github. I'll definitely inform the developer.
https://www.assetstore.unity3d.com/en/#!/content/10032

**Comment by devesh2605** [comment]
@Selzier I really did not know about this. Will take care of this.

**Comment by MrPatrickHenry** [comment]
thanks @devesh2605 dont' worry I have paid for Easy Movie Texture :) 
I figured out via the easy movie texture i can put urls in to the move location

**Comment by leeprobert** [comment]
This needs to be reopened. I am still seeing this issue with the latest release: GVR SDK for Unity v1.190.1

**Comment by rusmaxham** [comment]
Did you install the additional package in Assets/GoogleVR/GVRVideoPlayer ?
