### ISSUE TITLE
GVR Audio Spatializer doesn't work on iOS

### ISSUE THREAD

**Issue by alandyshev** [googlevr/gvr-unity-sdk#468]
I've made a VR project using gvr-unity-sdk 1.20.
I'm using GVR Audio Spatializer plugin for audio and it works fine on PC and Android.
However on iOS there's no audio.

**Comment by anokta** [comment]
Hi,

I can't seem to reproduce the issue using the GvrDemo scene in Unity 5.6b (on iOS 10.2.1 - iPhone 7). 

Do you experience the same problem in a newly created project? If so, do you mind giving more information on how to reproduce the issue?

Thanks

**Comment by alandyshev** [comment]
Hi. Thanks for response.
I'm using Unity 5.5.1 and also iOS 10.2.1 - iPhone 6s.

**Comment by alandyshev** [comment]
Sound doesn't work in GVRDemo built with Unity 5.5.1 on iOS 10.2.1 - iPhone 6 as well.

**Comment by synthercat** [comment]
If I remember correct spatial sound didn't work on my Mac export... it could be the same issue

**Comment by miraleung** [comment]
@anokta

**Comment by alandyshev** [comment]
I've found that it works, just the sound is too quiet on ios comparing to
Android and editor. Needed to make it much louder to hear it on iOS

28 февр. 2017 г. 8:55 PM пользователь "Mira Leung" <notifications@github.com>
написал:

@anokta <https://github.com/anokta>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlevr/gvr-unity-sdk/issues/468#issuecomment-283129215>,
or mute the thread

**Comment by synthercat** [comment]
@alandyshev  I'll have my Mac owner friend test this on his Mac soon!
