### ISSUE TITLE
No submodule mapping found in .gitmodules for path 'Samples/SchellDemos'

### ISSUE THREAD

**Issue by georgehbr** [googlevr/gvr-unity-sdk#469]
When pulling I get the error:
fatal: no submodule mapping found in .gitmodules for path 'Samples/SchellDemos'

Looks like the changes to .gitmodules haven't been pushed?

**Comment by chaosemer** [comment]
Thanks for the bug report! We'll clean up the repo.

**Comment by chaosemer** [comment]
This is now working for me. Please reopen if you are still having issues.

**Comment by georgehbr** [comment]
Hi @chaosemer what do you mean it's now working? There haven't been any new commits to the repo since then. What changed?

**Comment by chaosemer** [comment]
I did a fresh clone of the repo locally and was able to pull master. Please confirm if this works for you. If it does not, reopen this issue.

**Comment by Joris73** [comment]
Not working for me. My first clone: 06/03/2017

**Comment by miraleung** [comment]
The sample has since been pushed to GitHub.
