### ISSUE TITLE
Enable / Disable VR in game [Android]

### ISSUE THREAD

**Issue by nyudeb** [googlevr/gvr-unity-sdk#471]
Hello,

I actually face a problem with the GoogleVR. 
I'm using Unity 5.6 beta as said here : https://developers.google.com/vr/unity/

In my scene I have the GvrViewMain and a button to switch On/Off the VR with :
   "GvrViewer.Instance.VRModeEnabled = !GvrViewer.Instance.VRModeEnabled;"

When I compile for Android and try to switch from normal to VR mode, the app crash...In the editor it work perfectly...

I would like to know if there is a solution for this? 

thanks.

**Comment by estebanarrua** [comment]
Hi, I have a similar problem with my game. 
Can you tell me how you fixed it?
Thank you.

**Comment by nyudeb** [comment]
If you use the sdk don't take the beta version and it work. ^^ 
I was using the sdk with the version 5.6 beta and that was the problem because in this version the feature is include.
