### ISSUE TITLE
Cardboard Drift OnApplicationPause()

### ISSUE THREAD

**Issue by overfile** [googlevr/gvr-unity-sdk#472]
Hi,

Im trying to integrate Google Play Services with Cardboard sdk in Unity3D 5.4.2f2-GVR13 and when the application is pause i have a issue drift in camera.

Im using the last GVR SDK Version (1.20).

Im tested on Samsung Galaxy Note 4 and Samsung Galaxy S7.

Any ideas?

**Comment by miraleung** [comment]
Could you please post a video of what drift you're seeing?
