### ISSUE TITLE
No stereoscopic view with Unity + GoogleVR on iOS

### ISSUE THREAD

**Issue by AdrianaVecc** [googlevr/gvr-unity-sdk#473]
I built a VR game using Unity, that includes the GoogleVR SDK for Cardboard support.

On Android, it works like a charm: the VR mode is activated with stereoscopic view with the Cardboard distortion.

On iOS, however, it's fine on Unity's emulator but not on device: no stereoscopic view, no gyroscope movement. The GoogleVR SDK seems to have been disabled.
I reproduced this with GoogleVR's sample project.
Following these instructions: https://developers.google.com/vr/unity/get-started-ios

**What's expected (screenshot from Android):**

[![Stereoscopic_Android][1]][1]

**What's happening (screenshot from iOS):**

[![Monoscopic_ios][2]][1]

Versions:

 - Unity 5.4.2f2 - GV13 Personal 
 - Google VR SDK for Unity v1.10 or v.1.20
 - Xcode 8.2    
 - iPhone 6 iOS 10.1 and iPhone 7 iOS 10.2.1

Thanks for your help!

  [1]: https://i.stack.imgur.com/U7ZZk.jpg
  [2]: https://i.stack.imgur.com/LuHOo.png

**Comment by AdrianaVecc** [comment]
Interesting, updating to Unity beta 5.6.0b9 solves the issue, at least for the Demo Scene.

**Comment by miraleung** [comment]
iOS integration isn't fully supported yet - b9 has OpenGL support for iOS, and Metal is coming in b10.

**Comment by AdrianaVecc** [comment]
Thanks @miraleung. In that case, iOS is not supported at all, as this issue was experienced with the bare-bone demo scene, and the documentation should be updated, as it currently states "The Google VR SDK for Unity requires **Unity 5.2.1 or later**" (https://developers.google.com/vr/unity/get-started-ios).  
Thanks
