### ISSUE TITLE
Is GvrVideoTextureplayer supported with Cardboard or it only works with DayDream

### ISSUE THREAD

**Issue by devesh2605** [googlevr/gvr-unity-sdk#474]
I am trying to build the DemoVideo Scene from GVR SDK Unity but after going through the code it looks like the demo scene is made to work with Day Dream, not CardBoard. Is there any link or documents available to use GvrVideoTextureplayer with Cardboard.

**Comment by miraleung** [comment]
Yes, it works with Cardboard. If you replace the controller input in a scene with gaze-based (Cardboard) input, it will work on a phone that supports Cardboard.
