### ISSUE TITLE
Inconsistent GVR UI

### ISSUE THREAD

**Issue by maskedmous** [googlevr/gvr-unity-sdk#475]
Since the UI/UX is forced since 0.85 atleast make it consistent.
On Android I'm getting an 'X' whereas on iOS I'm getting a '<-'

I rather have a back arrow on both
It is confusing to have an 'X' because the 'X' will go back to the menu.
We don't want to close the application using the 'X'
We go back to a selection menu with that.

Would be nice to have some kind of control whether it to be an 'X' or '<-'
Since you don't want developers to be able to hide the icons anymore.

Also had to change the event behind it to a Unity Event rather than a bool.
Checking that bool in an Update loop are just an overhead, simpler is to invoke a Unity Event whenever needed.

I've made changes to support UnityEvent so me as developer can execute my own code without too much overhead.

**Comment by miraleung** [comment]
Thanks for your feedback. Please file this bug under the gvr-ios-sdk repo.
