### ISSUE TITLE
Problem with Blur on center of lens

### ISSUE THREAD

**Issue by Desvar** [googlevr/gvr-unity-sdk#476]
Unity Version: 5.3.5 f1, 5.5.1 f1, 5.5.1 p3
Cardboard SDK: v1.0
BUILD: iOS 9.3.2, iOS 10+
Device: iPhone 6, 6s, 6plus

Description: There is a blur at the center of the VR lens. Only the side near the lens margins  shows the letters on the texture without blur effect.

Example #1 - Text not blurred
![issue-blur-vr-1 copia](https://cloud.githubusercontent.com/assets/21242576/23214236/3af67564-f90e-11e6-8df8-01e8d3e7ec8b.png)

Example #1 - Text with blurred side
![issue_blur-vr-2 copia](https://cloud.githubusercontent.com/assets/21242576/23214163/faa25956-f90d-11e6-940b-b1f6ef4b5f5a.png)

Example #2 - Text not blurred
![issue_blur-vr-4](https://cloud.githubusercontent.com/assets/21242576/23214252/4587aae8-f90e-11e6-98f9-e7789d2fff47.png)

Example #2 - Text with blurred side
![issue_blur-vr-3](https://cloud.githubusercontent.com/assets/21242576/23214244/3fa7309e-f90e-11e6-8c36-613d739f30a7.png)

**Comment by miraleung** [comment]
Thanks for your feedback - please file this bug under the gvr-android-sdk repo.

**Comment by Desvar** [comment]
Sorry, i don't understand what you mean with "file this bug under the gvr-android-sdk repo".It's talking about unity implementation of the googlevr-sdk and building for iOS.
Let me know where post that issue to receive support or resolution
Tanks
Davide

      Da: Mira Leung <notifications@github.com>
 A: googlevr/gvr-unity-sdk <gvr-unity-sdk@noreply.github.com> 
Cc: Desvar <campo.davide@gmail.com>; Author <author@noreply.github.com>
 Inviato: Martedì 28 Febbraio 2017 19:47
 Oggetto: Re: [googlevr/gvr-unity-sdk] Problem with Blur on center of lens (#476)
   
Thanks for your feedback - please file this bug under the gvr-android-sdk repo.—

**Comment by diegorborges** [comment]
Hi, have you found any solution for this? I've been having the same problem. :(
