### ISSUE TITLE
Warning dialog when in VR mode happen in Unity5.4.3f1 and Android N

### ISSUE THREAD

**Issue by xzhao23** [googlevr/gvr-unity-sdk#479]
Hi,
My team have bean using Google VR for the past 9 months within our product. Formerly, we used the Cardboard sdk 8.1 version, problem happen when we update to Google VR 1.0 with Unity 5.4.3f1 in Android N (no problem if below android N).  The problem is when the VR app launches, a pop up warning show up saying: "This application may not work properly without Google VR Services. Please install Google VR Services from the Play Store before continuing.", the VR scene seems work find even this dialog shows up, when user click the "CANCEL" or the "GO TO THE PLAY STORE", the app do nothing(but the dlg is dismissed). 

The phone from Huawei, and the ROM is upgraded to Android 7 two month ago, before that this warning pop never show up,  you can see an example [here](http://imgur.com/V9mKkBs)

We don't want user to see this warning, as it is in English words, end user may strange to see this and it did nothing. By the way, we still want the app work in Cardboard type not Daydream. I post the question here to see if any solution to prevent it show up. 

Thanks.

**Comment by xzhao23** [comment]
Another information: What is strange is, if we build the app with Unity 5.3.4f1 with the same source, the Warning dialog doesn't show, but another problem is when the app is resumed after pressing the home button, the VR screen never  come back (screen becomes black). Upgrading the Unity version solve this but cause the problem in my first post above.

**Comment by xzhao23** [comment]
we solved it internally by hacking the arr lib.

**Comment by damengzai** [comment]
@xzhao23 How do you remove the dialog,can you show the code?

**Comment by binoculars88** [comment]
I'd like to know how you removed the dialog too...
