### ISSUE TITLE
Can't present one object only in one screen on pixel device with sdk 1.2.0

### ISSUE THREAD

**Issue by YuEagle** [googlevr/gvr-unity-sdk#480]
I want to present one object only in one screen on pixel device with sdk 1.2.0, but it present both in right and left screen.
However, with the same settings the editor could work well. Are the settings different for editor and android device? And what should I do for android device?
Thanks.

**Comment by miraleung** [comment]
With the native integration (technical preview 5.4.2f2-GVR13, or 5.6 beta), you can use culling masks and the camera's target eye to present different content per-eye.
