### ISSUE TITLE
Camera rotate in vr360 unity

### ISSUE THREAD

**Issue by sixblades** [googlevr/gvr-unity-sdk#482]
The problem I have is with the googlevr 1.0 SDK in unity 5.5.

I attached GvrHead to the main camera *, if I leave Track Rotation activated the camera starts pointing to where the phone was pointing at the moment of the execution.

If I turn it off, it starts right where I want, but I'm left with no head movement.

I have tried to move the camera with the gyroscope of the mobile, and it does well, the problem then is that if I look down or up and twist, I lose the horizontality and I do not know how to correct that. Some help?

The camera is inside a sphere where I have a 360 video as a texture

**Comment by sixblades** [comment]
I've also tried rotating the sphere, but this is always giving me value -90:
My code:
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;
using System.IO;

public class cam : MonoBehaviour {
	public GameObject camara;
	public GameObject esfera;
	public float ycamara;
	public Text mensaje;

	
	// Use this for initialization
	void Start () {
		Input.gyro.enabled = true;
		for(int i = 0; i < 10; i++)
		{
			ycamara = Input.gyro.attitude.eulerAngles.y-90;
			mensaje.text = ycamara.ToString ();
		}
		esfera.transform.Rotate (0, ycamara, 0);
		}
	
	// Update is called once per frame
	void Update () {

	}
}

**Comment by sixblades** [comment]
In my case was much easier, after reading the documentation of the library. My problem was solved with the recenter function

**Comment by bopangzz** [comment]
Looks like you found the solution. Closing this issue.
