### ISSUE TITLE
Building GVRDemo.unity on Android device

### ISSUE THREAD

**Issue by kevin1437** [googlevr/gvr-unity-sdk#483]
Hi, I'm very new to Unity and VR, My version of Unity is 5.5 and my android device run on 6.0, I try to build the GVRDemo.unity scene from the GoogleVRForUnity.unitypackage on my android device and it worked, but when I tilt my phone the view is not changing, is there anything I should do before building my android device to make the view work on my android device?

**Comment by bopangzz** [comment]
You shouldn't need to do anything. Did it render the scene in stereo on the phone?

**Comment by kevin1437** [comment]
Ah pardon me, it seems my phone didn't support gyroscope for VR features, already tried on other phone and it works well, Thank you for your response @bopangzz :)
