### ISSUE TITLE
Unity 5.6b8 + Google Pixel Phone GVR Mic = Crash. 

### ISSUE THREAD

**Issue by harperAtustwo** [googlevr/gvr-unity-sdk#485]
After upgrading to 5.6b8 from GVR preview, We are getting a crash on device that we do not get in editor. 

03-06 10:44:15.999: I/SoundTriggerHwService::Module(492): void android::SoundTriggerHwService::Module::onCallbackEvent(const sp<android::SoundTriggerHwService::CallbackEvent> &) mClient == 0
03-06 10:44:16.004: E/ANDR-PERF-OPTSHANDLER(621): Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
03-06 10:44:16.004: E/ANDR-PERF-RESOURCEQS(621): Failed to apply optimization [2, 2, 0]
03-06 10:44:16.004: D/audio_hw_primary(492): select_devices: changing use case audio-record input device from(63: voice-rec-mic, acdb 41) to (28: handset-mic, acdb 4)

Any options for resolving this issue?

**Comment by bopangzz** [comment]
Can you please try using Unity 5.6.b10?

**Comment by chaosemer** [comment]
Beta 8 is a beta. We can help with GVR issues, but this issue is with Unity in general and needs to be reported to them at https://unity3d.com/unity/qa/bug-reporting.
