### ISSUE TITLE
Scene keep rotating in some device.

### ISSUE THREAD

**Issue by xzhao23** [googlevr/gvr-unity-sdk#486]
Hi Gvr developers, 

We were keeping use gvr sdk for our VR app, after we publish our app, some a few users complain that when launch the app, the scene keep rotating. We make a video here, you check it. [Link](http://www.iqiyi.com/w_19rtzttap1.html)

Is this related to the gryo data drift ? how to prevent this happen?

**Comment by xzhao23** [comment]
this do not happen in most devices.

**Comment by overfile** [comment]
Hi,
I have the same issue when the application is paused. In my case when i'm using Google Play Services.

**Comment by xzhao23** [comment]
device is: Huawei Honor 8, with Android N.

**Comment by bopangzz** [comment]
Hi, I assume your app is a cardboard app? Which version of Unity and GVR sdk your are using?

**Comment by xzhao23** [comment]
yes, bopangzz 
the version is: 
Unity: 5.3.4f1, Gvr SDK: 1.0

**Comment by kasradzenika** [comment]
@xzhao23 try the latest sdk (v1.30 as of 12/3/17), I had the same problem when I was using v0.83 (one before v1.0)

**Comment by xzhao23** [comment]
thanks @kasradzenika , will try that. 

@offcial, do you have explain for the root cause?

**Comment by xzhao23** [comment]
The same issue happened in Xiaomi 5 phone.

The scenario happen for 2 or 3 times when testing in a day. If re-launch the app, the app the scene rotate slightly (but the data seems very sensitive, that is if move phone with a small angle in space, the scene move a lot and shake), gvr developers can you provide some solution on this? or do you need more input on the issue?

**Comment by xzhao23** [comment]
we record this issue, you can check it [here](http://www.iqiyi.com/w_19rtwq62dh.html)

**Comment by miraleung** [comment]
This is a device-specific issue, and the Unity-side of things doesn't have logic implemented there. Please try the gvr-android-sdk repo.
