### ISSUE TITLE
Can not set the value of "Order in Layer" for one canvas greater than zero

### ISSUE THREAD

**Issue by YuEagle** [googlevr/gvr-unity-sdk#487]
When i develop daydream related functions, I found that if i set the value of "Order in Layer" for one canvas greater than zero, the reticle can not present over the canvas.
Is there some setting need to set if i want to set the value of "Order in Layer" greater than zero, such as ten?

**Comment by bopangzz** [comment]
It is a rendering order issue. I think if you set the Order in Layer of your canvas to non-zero value, you also need to set the reticle mesh renderer sorting order to the same or larger value than the on in your canvas.
