### ISSUE TITLE
gvraudiolistener - Google Cardboard SDK ver 0.6 vs ver 1.3 - World Scale property issue

### ISSUE THREAD

**Issue by xslipstream** [googlevr/gvr-unity-sdk#493]
My game is set up with my world scale increased 100%.  I'm running into a problem after upgrading cardboard sdk from .06 to 1.3.  Now the newest gvraudiolistener script no longer has a world scale property to accommodate my  world scale, thus my game sounds are not working properly.

**Comment by jkammerl** [comment]
Hi, we removed the world scale parameter to be able to integrate Unity's internal distance attenuation calculation into our Unity plugin. To fix this, you'll need to rescale your environment to match 1 unit = 1 meter.
