### ISSUE TITLE
assets/playmaker utils/wizards/linkerwizard/linkerdata.cs(18,7): error cs0246 compile error

### ISSUE THREAD

**Issue by GayanJayasundara** [googlevr/gvr-unity-sdk#494]
Hi..............

I am Creating uGuiDragAndDrop with Playmaker . I use Unity3D 5.3. when i build project i got
assets/playmaker utils/wizards/linkerwizard/linkerdata.cs(18,7): error cs0246: the type or namespace name `playmaker' could not be found. are you missing a using directive or an assembly reference?
error.

Pls help me how can i solve this problem?

Thanks

**Comment by vinhui** [comment]
I don't think this is related to GoogleVR
