### ISSUE TITLE
reticle is not working mode after moving camera

### ISSUE THREAD

**Issue by ManjitBedi** [googlevr/gvr-unity-sdk#496]
I am using a teleport mechanism to move around a 3D scene.  When I interact with a way point object by clicking on it using PointerClick, the camera is moved to the waypoint's position.  

Camera.main.transform.position 	= gameObject.transform.position;

But then the reticle appears to be stuck in focused mode & then way-point game objects  no longer get Pointer Enter, Pointer Exit events.  

I was using GVR SDK 1.3.0 with Unity 5.5.2p2 running on a MacBook Pro  running Sierra.

**Comment by miraleung** [comment]
Consider having the reticle share a parent with the Camera, or as a child of the Camera, so that they can move in sync.

**Comment by ManjitBedi** [comment]
The reticle was a child of the "main camera" game object when I was using SDK 1.3.0.

I reverted back to using 1.0.3 & was able to get it to work.

**Comment by ManjitBedi** [comment]
Someone suggested I use the GVREventSystem prefab & I just did.  Everything seems to be working now.  Previously, I was using an EventSystem with the Gaze input module script.

<img width="271" alt="screen shot 2017-03-21 at 10 57 02 am" src="https://cloud.githubusercontent.com/assets/2837803/24162573/3147b2f4-0e25-11e7-87c6-51a31ea96f9b.png">

<img width="282" alt="screen shot 2017-03-21 at 10 56 18 am" src="https://cloud.githubusercontent.com/assets/2837803/24162582/3b4e2f30-0e25-11e7-8de4-fe68f7f6bbd7.png">
