### ISSUE TITLE
Stereo Screen is shrunk with Native Distortion Correction in 4k display mode

### ISSUE THREAD

**Issue by m-tukiok** [googlevr/gvr-unity-sdk#497]
I'm writing a test app using Unity 5.4.4f1 to enable 4K display mode on Android device.

https://developer.android.com/about/versions/marshmallow/android-6.0.html?#4K-display
https://github.com/m-tukiok/UnityPluginDisplay4k

It was successful on my test app with Android plugin to switch preferredDisplayModeId from normal 1080p display mode to 4K display mode. However, the image of the stereo screen was unexpectedly shrunk to 1/4 size in VR mode. I didn't have this issue when I was using gvr-unity-sdk v1.0.3 (currently I'm using gvr-unity-sdk v1.30.0). I found a work around to solve this issue by switching Distortion Correction from `Native` to `Unity` in GvrViewerMain. But I think C# code in `Unity` mode might have a significant performance drop, so I think the native code of Distortion Correction in libgvrunity.so should support 4k display mode. It will be appreciated if gvr-unity-sdk team can solve this issue in the next release.

**Comment by rusmaxham** [comment]
In our testing of using Unity Distortion Correction, it performs as well, if not better in some cases, than Native Distortion Correction for versions of Unity that don't have native integration of Daydream.  We may look into support of 4k displays with cardboard, but in the meantime, you're best path forward is to use Unity Distortion Correction.

**Comment by m-tukiok** [comment]
I see. Thank you for the clarification.
