### ISSUE TITLE
SDK+huawei mate8(Android7.0)+EasyMovietexture cannot play video.

### ISSUE THREAD

**Issue by damengzai** [googlevr/gvr-unity-sdk#498]
I use sdk1.20.0 made a movie player with EasyMovietexture,when I run the app on huawei mate8(Android7.0),the video cannot play.
But I use sdk0.81 is well or use sdk1.20.0 run on other phone base on Android7.0 is ok.
Is this a problem of googlevr or huawei phone?
And how to resolve?

**Comment by rusmaxham** [comment]
Since Google doesn't maintain EasyMovieTexture, we can't speak to what issues there may be with it on various devices or SDKs.  I would recommend sending a query to the EasyMovieTexture developers to ask them.

**Comment by kasradzenika** [comment]
please test without google vr sdk, if you're sure it's a gvr issue please provide your logcat output or at least something to work with

**Comment by damengzai** [comment]
@kasradzenika I used gvr sdk0.81 to play video with EasyMovieTexture on huawei phone(with huawei Android7.0) it work well.
And sdk1.20.0 on huawei phone cannot play video has no error or something else.

**Comment by rusmaxham** [comment]
What version of Unity are you using?

**Comment by damengzai** [comment]
@rusmaxham I`m using unity5.3.3f1

**Comment by damengzai** [comment]
I solved this problem by update my unity to unity5.4.1f1,seems like #479 ,but I want to know how to hide the warning dialog?

**Comment by xzhao23** [comment]
you can re-compile the jar lib, replace to use your own AndroidNcompitable.cls
