### ISSUE TITLE
problem with gvr native integration

### ISSUE THREAD

**Issue by aishu5** [googlevr/gvr-unity-sdk#499]
hi im using unity5.6.0b11 with gvr sdk of 1.0.0 the issue is **"to use the controller please upgrade to a version of unity with gvr native integration".** how to solve this?

**Comment by martinbilello** [comment]
Please try upgrading to GVR 1.30

**Comment by jessedubord** [comment]
I just tried GVR SDK 1.30 in Unity 5.6.0b10 beta on Ubuntu 16.10 x64, and I'm also getting this error when entering Preview Play mode.

**Comment by synthercat** [comment]
Do you have the Google SDK activated in player settings?

**Comment by jessedubord** [comment]
If you're asking if I have the "Virtual Reality Supported" checkbox checked, and have "Daydream" added to the list of Virtual Reality SDK's, then yes I do.

**Comment by jessedubord** [comment]
My bad, I forgot to switch the platform to "Android" in the Build Settings. After I did that, the controller error went away. :)
