### ISSUE TITLE
GVRAudioSoundfield does not respect its rotation in v1.30.0

### ISSUE THREAD

**Issue by mikerz** [googlevr/gvr-unity-sdk#500]
Using Unity v5.5.2f1 and GVR release 1.30.0, the Soundfield object does not respect the rotation of its GameObject transform. However, it does respect the rotation of the GVRAudioListener. 

The bug can be seen here:
https://github.com/mikerz/GVRSoundfieldBug

**Comment by miraleung** [comment]
@anokta

**Comment by anokta** [comment]
Hi,

Thanks for reporting! The issue should have been resolved with the v1.40 update (a3d1033260dab57cb0f4a62a770796fbd09fe37a).

Cheers
