### ISSUE TITLE
Readme does not include version number

### ISSUE THREAD

**Issue by sterlingcrispin** [googlevr/gvr-unity-sdk#501]
the Readme that comes with the unitypackage doesn't describe what version of the GVR SDK it is, so there's no easy way of knowing what version of the SDK a Unity project has in it

also the release notes don't haves dates next to the version number, so it's unclear when 1.3 was released
https://developers.google.com/vr/unity/release-notes

I'd guess I'm on 1.2 and that 1.3 was released 9 days ago according to the git repo commit history but it would be nice if versioning was more clearly documented

**Comment by miraleung** [comment]
The version is in GvrUnitySdkVersion.cs as of 1.3 onwards, and GvrViewer.cs prior to that. We'll look into updating the README in upcoming releases. Thanks for your feedback!
