### ISSUE TITLE
Error importing RotateInstructions.mp4 v1.30

### ISSUE THREAD

**Issue by jessedubord** [googlevr/gvr-unity-sdk#502]
This appeared after I imported the GoogleVRSDK 1.30 Unity asset. I get two errors in console:

> File Temp/ImportedOgg.ogg could not be read

And

> Error reading encoded movie (buggy encoder?) [Assets/Plugins/iOS/CardboardSDK.bundle/rotateInstructions.mp4]

Bug discovered on Unity 5.6.0b10 on Ubuntu 16.10 x64, Unity 7.5.0 desktop environment, Linux kernel 4.8.0-41-generic.

**Comment by miraleung** [comment]
Could you please try deleting Temp/ and Library/ and trying again? I'm using b10 and haven't encountered that error with the iOS assets.

**Comment by miraleung** [comment]
Unity 5.6 is not supported on Linux, unfortunately, and they haven't announced whether that will be in a future release.
