### ISSUE TITLE
How to use Daydream controller in v1.30?

### ISSUE THREAD

**Issue by jessedubord** [googlevr/gvr-unity-sdk#503]
GVR SDK 1.30 seems to support Daydream controller use in the Unity editor, but I can't seem to find a way to set it up. Anyone have some insight into how I can use the actual Daydream controller in Unity?

**Comment by miraleung** [comment]
Please ensure you're using a version of Unity with the GoogleVR native integration (5.4.2f2-GVR13, or 5.6 beta), and you're targeting Android. A good example of controller usage is in the GVRDemo scene or ScrollingUIDemo scene. The former has both Cardboard and Daydream mode (when they're enabled in Player Settings under "Virtual Reality Supported"), and the latter is Daydream-only.

Hope that helps!
