### ISSUE TITLE
iOS - Locking phone and then un-locking directly back to the app crops/resizes the view

### ISSUE THREAD

**Issue by dill0wn** [googlevr/gvr-unity-sdk#506]
This is seemingly heavily related to #144, but the path to triggering it is different.  Our team had implemented some of the work-arounds from that thread to moderate success, but started seeing this issue occasionally when backgrounding the app, but roughly 100% of the time when locking the phone while the app was running (and unlocking while in portrait).

Unity 5.4.1p2
GoogleVR 1.0.0
iPhone 7 Plus

Steps: 
1. Application has LandscapeLeft as its default
2. start it up and get into the VR bits.
3. Lock the device
4. Hold your phone in normal portrait position
5. Unlock the phone.
6. ???
7. PROFIT!

I'm getting this image (I copied it from that thread, but it is the same problem).

![image](https://cloud.githubusercontent.com/assets/1267330/24225871/4d5d745a-0f39-11e7-9d5a-dd00a561858a.png)

I have also now tested all sorts of variations all the way up to unity 5.6.0f1 with gvr 1.30.0.  And they all have the same issue.

**Comment by dill0wn** [comment]
I found a work-around!  Downgrade to Cardboard 0.6.0.

**Comment by miraleung** [comment]
The solution is to set Landscape Left in Unity's Player Settings, as well as in XCode. Please note that we'll be removing support for non-native integration Unity with iOS in a release after 1.4. That is, iOS will work only with Unity 5.6.0b10 and above, so I would recommend upgrading to our coming 1.4 release, which will be compatible with all versions of Unity.

**Comment by dill0wn** [comment]
I tried that out with Unity 5.5.2p4 and Gvr 1.0.0:
<img width="415" alt="screenshot 2017-03-28 16 07 55" src="https://cloud.githubusercontent.com/assets/1267330/24425069/bda8a4dc-13d0-11e7-8ec0-6937bda56107.png">
<img width="517" alt="screenshot 2017-03-28 16 08 36" src="https://cloud.githubusercontent.com/assets/1267330/24425105/e7b62312-13d0-11e7-87b1-1ec204fcfafa.png">
And I was able to get this:
![2017-03-28 16 08 43](https://cloud.githubusercontent.com/assets/1267330/24427187/112e7166-13d8-11e7-9032-767bb46197d0.png)
Oftentimes, when selecting `Landscape Left` in XCode, the gyro camera is upside down, too.

Or is there a different way I'm supposed to set XCode to landscape left?

**Comment by dill0wn** [comment]
I just found out one extra helpful tidbit!

We have a few iPhone 6 Plus' hanging around.  
- iPhone6+ on iOS 9.3.2 - Works as expected :)
- iPhone6+ on iOS 10.2.1 - BAD.  Produces the above screenshot results.

**Comment by miraleung** [comment]
That's the expected way to set landscape - sounds like it's a device / OS config-specific problem then. Thanks for the update. :)

**Comment by dill0wn** [comment]
Does that mean the issue is open again?

**Comment by steeb-dev** [comment]
This seems to still be an issue with Google Cardboard and ios 10+.  If the Unity application is open when the phone locks the cardboard view is crushed when you return and cannot recover unless you close and re-open the app entirely.
