### ISSUE TITLE
android.content.ContextWrapper.checkSelfPermission exception

### ISSUE THREAD

**Issue by plusagain** [googlevr/gvr-unity-sdk#508]
Hi I'm developing a daydream app.
Sometimes my app is terminated by crash about 'android.content.ContextWrapper.checkSelfPermission'

Here's the call stack ===================================================================
AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ContextWrapper.checkSelfPermission(java.lang.String)' on a null object reference
com.google.gvr.permissionsupport.PermissionsFragment.hasPermission(PermissionsFragment.java:88)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.a(Unknown Source)
com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:154)
com.unity3d.player.UnityPlayer$b.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException ()
UnityEngine.AndroidJNISafe.CallBooleanMethod (IntPtr obj, IntPtr methodID, UnityEngine.jvalue[] args)
UnityEngine.AndroidJavaObject._Call[Boolean] (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaObject.Call[Boolean] (System.String methodName, System.Object[] args)
GvrPermissionsRequester.IsPermissionGranted (System.String permission)

I've created a permission logic followed GVR sample.

I use SDK1.1, Unity 5.4.2f2-gvr12 & gvr13
Please anyone helps me

**Comment by miraleung** [comment]
Without seeing the source, it's hard to tell which object exactly is null. I'd suggest checking that you're passing in a valid argument to IsPermissionGranted, and that permissionsFragment is not null.

**Comment by user32768** [comment]
I'm using Unity 5.4.2f2-gvr12, and I've just updated to 1.3 from 1.0, and I get AndroidJavaException: java.lang.ClassNotFoundException: com.google.vr.sdk.samples.permissions.PermissionsFragment
when trying to instance a GvrPermissionsRequester, Could be a related issue?

I get the same "class not found" problem for the original permission plugin which works in v1.0 . Swapping SDK from 1.0 to 1.3 seems to somehow make the java class not findable.

**Comment by miraleung** [comment]
There should be a gvr-permissions.aar (similarly named) in Assets/Plugins/Android.

**Comment by rusmaxham** [comment]
Are you still experiencing this issue with the latest versions of Unity and the GVR SDK for Unity?

**Comment by rusmaxham** [comment]
If you are still experiencing this issue, feel free to reopen with more details.
