### ISSUE TITLE
Android - Deep Link - getDataString always returns null

### ISSUE THREAD

**Issue by rrahimi01** [googlevr/gvr-unity-sdk#509]
Hi, 

I'm trying to get the deep link working. I can send the activity, open the app and read dashcode and get booleanExtra and all that. So activating the deep link works fine and for example when I call getAction, it returns android.intent.action.VIEW which is correct.

The main problem is that getDataString and getScheme always return null. I'm out of test ideas. Do you think its a bug?

I have attached the manifest file for your reference. And I'm using GvrIntent.GetData() that always returns null. IsLaunchedFromVr() and GetIntentHashCode() are working fine.

and this is the command line I used to test as an example: 
./adb shell am start -W -a android.intent.action.VIEW -d "shapevisual://com.shapevisual.app?wl=gfs" com.shapevisual.app

[AndroidManifest.xml.txt](https://github.com/googlevr/gvr-unity-sdk/files/864522/AndroidManifest.xml.txt)

**Comment by rrahimi01** [comment]
I forgot to mention that I'm using Unity 5.5.2p2.

Google VR SDK v1.30. I did also test v1.20 and got same result. 

And I have tried on three different android devices with KitKat, Lollipop and Marshmallow on each of them. I did also compile with those APIs. 

And I did also test with a custom Android plugin that extends UnityPlayerActivity directly and that worked fine too.

**Comment by rrahimi01** [comment]
Update:

I upgraded to Unity 5.6 beta and my problem is solved. 

Unity 5.5 and below need some additional plugins to work because they don't use Google VR natively like Unity 5.6 and I think that the issue is caused by plugin that receives the activities.

**Comment by nathanmartz** [comment]
Glad to hear that it's fixed.
