### ISSUE TITLE
Render different layers to different eyes?

### ISSUE THREAD

**Issue by cjsauer** [googlevr/gvr-unity-sdk#511]
This question has been posted so many times, but seems to be a bit of a moving target. How, using Unity 5.6 and Google SDK version 1.3, do you update the culling masks for each eye's camera **for Cardboard**? The closest I can get is the script below which I got from #263:

```
    public LayerMask LeftEyeMask;
    public LayerMask RightEyeMask;

    void Start()
    {
        StartCoroutine(LateStart());
    }

    protected IEnumerator LateStart()
    {
        yield return new WaitWhile(() => GvrViewer.Controller == null);
        yield return new WaitWhile(() => GvrViewer.Controller.Eyes.Length < 2);
        foreach (GvrEye gvrEye in GvrViewer.Controller.Eyes)
        {
            switch (gvrEye.eye)
            {
                case GvrViewer.Eye.Left:
                    gvrEye.toggleCullingMask = LeftEyeMask;
                    break;
                case GvrViewer.Eye.Right:
                    gvrEye.toggleCullingMask = RightEyeMask;
                    break;
            }
        }
        GvrViewer.Controller.UpdateStereoValues();
    }
```

This script works in the editor, but will not let me compile for Android, and I get this error message: 

`Type 'StereoController' does not contain a definition for 'UpdateStereoValues' and no extension method 'UpdateStereoValues' of type 'StereoController' could be found. Are you missing an assembly reference?`

Looking at the code it seems that this function is only present within the editor, or when UNITY_HAS_GOOGLEVR is FALSE. This suggests that the API has been updated in the short time between now and when those solutions were proposed. 

I have also tried adding my own left and right cameras manually and setting their culling masks and "target eye" fields appropriately. The GvrViewer prefab seems to be hijacking the entire setup process though, and I end up with an explosion of cameras nested inside cameras...

What is _currently_ the best way to accomplish splitting layers between eyes?

**Comment by cjsauer** [comment]
So I didn't _quite_ solve my issue, but I did successfully get a 360 stereo video playing in Cardboard. For future people trying to do this I'll explain it roughly. _It is not necessary to use two spheres to accomplish 360 stereo video playback!_ You can use only one with a bit of shader magic. 

First of all, I'm using [Easy Movie Texture](https://www.assetstore.unity3d.com/en/#!/content/10032) in order to render .mp4 files to texture on Android. This package is referenced often and seems to be the most recommended solution for accomplishing this on Android. 

From there, drag out a sphere, but do NOT use the Unity standard sphere. The UVs on it are not appropriate for equirectangular videos which causes distortion near the poles. Instead, use the `pSphere09` mesh that comes with Easy Movie Texture. Or alternatively, you could [model up your own in Blender](https://www.youtube.com/watch?v=yc0b5GcYl3U) and use that.

Now the key ingredient: there is a shader bundled with the GVR Unity SDK called `VideoDemoInsideShader`. This is what you want to attach to your sphere's material. To make this work you have to make some edits to the shader code itself, because currently this shader is flipping normals and UVs manually. We don't need this. We already flipped and mapped the UVs correctly in Blender (or are using a sphere that has, like pSphere09). Comment out the following lines in the shader:

```C#
v2f vert (appdata_base v) {
    v2f o;
    // invert the normal of the vertex
    // v.normal.xyz = v.normal * -1;
    // ...
    // o.uv.x = 1 - o.uv.x;
    //  ...
}
```

These lines flip the normals and mirror the UVs respectively.

Now when you set up the `Media Player Control` component to point to the sphere as its target (this is Easy Movie Texture specific again), it _should_ be properly splitting the video to each eye using a shader. No need to use two spheres and culling masks!

**Comment by miraclestar** [comment]
good ，tested  in Unity 2017.1, GVR1.7.

**Comment by babeuf** [comment]
The shader trick is nice. thanks for the tip !

Don't be scared if it doesn't work in the editor. 
Had to change "Cull Front" to "Cull Back" in the shader to get the video inside.
