### ISSUE TITLE
Can you please keep libgvrunity.a under 100MB

### ISSUE THREAD

**Issue by alimoeeny** [googlevr/gvr-unity-sdk#512]
Can you please keep libgvrunity.a under 100MB

**Comment by miraleung** [comment]
As of our next release, you'll be able to use the GVR Unity SDK without libgvrunity.a on Unity 5.6.0b9 and up. We'll be removing libgvrunity.a in a future release afterwards.

**Comment by ShacharWeis** [comment]
Does that mean I can delete it on GVR 1.6 ?

**Comment by miraleung** [comment]
Yes, it can be deleted.
