### ISSUE TITLE
where to set UI Layer Setting

### ISSUE THREAD

**Issue by liujunjie612** [googlevr/gvr-unity-sdk#513]
version 0.8, i can set UI Layer Setting on Gvr Viewer directly,but new version sdk, i only find a method "DrawUILayer", but it just works on unity_editor. When i export as APk, the method can't work on android,
what can i do to hide GUI  layer

**Comment by miraleung** [comment]
Thanks for your feedback! The GUI layer is now controlled by the GVR SDK - please file issues under gvr-android-sdk.
