### ISSUE TITLE
Android. Crash with Signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) with Unity 5.6b9 and GoogleVR 1.3 for Android

### ISSUE THREAD

**Issue by Baptistegrv** [googlevr/gvr-unity-sdk#514]
Our Cardboard and Daydream app crashes everytime that we quit the app with the error Signal 11 (SIGSEGV), code 1 (SEGV_MAPERR).

We have this problem only when we start the app as a non VR app and then switch to VR mode (either Cardboard or Daydream). The app stop crashing on quit when we remove this option.

As I mentioned in the title, we are using Unity 5.6b9 and Google VR 1.30. We are building for Android and have noticed this error on the different phones we used (Google Pixel and Samsung S6).

I spent a lot of time reading this issue which seemed to be similar to ours: https://github.com/googlevr/gvr-unity-sdk/issues/113 but it wasn't helpful.

Let me know if you need more details.

**Comment by fredsa** [comment]
Suggest providing:
- List of VR SDKs specified in Android's "Play Settings", i.e. whether you have [Daydream, Cardboard, None] or [Daydream, None, Cardboard] or something else
- What C# code you are using im your app to switch VR on / off, for example switching to Daydream from 2D might be done by calling `StartCoroutine(SwitchToVR())`:
```
IEnumerator SwitchToVR() {
  // device becomes active in the *next* frame
  VRSettings.LoadDeviceByName("daydream")
  yield return null;
  VRSettings.enabled = true;
}
```

**Comment by guneyozsan** [comment]
If you switch to a VR scene from a non-VR scene and enable VR in Start() of the new scene, delaying the switch a few Update cycles after Start() resolved our crash.

**Comment by felipe-torres** [comment]
Confirmed @guneyozsan that this solved our problem. Many thanks!
