### ISSUE TITLE
Repacking errors

### ISSUE THREAD

**Issue by KaiPar** [googlevr/gvr-unity-sdk#517]
![image](https://cloud.githubusercontent.com/assets/26135296/24441574/c11babee-1477-11e7-8c87-7ae4778ee636.png)

How can I fix this error ? Please help me.

Thank you.

**Comment by chaosemer** [comment]
Can you please copy / paste the full error from Editor.Log here? This will help us diagnose the issue.

**Comment by miraleung** [comment]
Please re-open if you wish to follow up.
