### ISSUE TITLE
Memory leak？

### ISSUE THREAD

**Issue by coffevei** [googlevr/gvr-unity-sdk#519]
I found that GvrControllerVisual has a memory leak,。OnArmModelUpdate ()  touchRenderer.materia, and I don't know if I'm right, using the Unity Profile analysis did detect, this will lead to rising Total Objects Count.

**Comment by chaosemer** [comment]
Thanks for the report! I'm adding this to our internal bug tracker.

**Comment by chaosemer** [comment]
This is now fixed internally and will be part of an upcoming release. If you want to apply a fix yourself, change the line from setting .material to setting .sharedMaterial.
