### ISSUE TITLE
GVRVideoTexture is not playing the HLS FMP4 file

### ISSUE THREAD

**Issue by devesh2605** [googlevr/gvr-unity-sdk#520]
I have tried the latest VideoDemo scene and it works just fine, I have tried out various links with dash and hls streaming. However, the player does not play this link: https://tungsten.aaplimg.com/VOD/bipbop_adv_fmp4_example/v6/prog_index.m3u8 (Official HLS FMP4 link from apple).

Regards,
Devesh V

**Comment by chaosemer** [comment]
The actual video decoding is done using [ExoPlayer](https://google.github.io/ExoPlayer/supported-formats.html) which has some limitations with the FMP4 format.
