### ISSUE TITLE
Dimensions of color surface does not match dimensions

### ISSUE THREAD

**Issue by gekidoslair** [googlevr/gvr-unity-sdk#522]
I'm teaching a workshop using Unity 5.6 and the Google VR toolkit - a number of the students are getting this error:

> Dimensions of color surface does not match dimensions

the game view when previewing in the editor is broken - half of the assets appear in one eye, textures are broken etc.

![pasted image at 2017_04_01 01_57 pm](https://cloud.githubusercontent.com/assets/4552687/24582354/1f141516-16e3-11e7-8e19-13663d7d0d1a.png)

Any ideas?

**Comment by gekidoslair** [comment]
note: this completely breaks Google VR and cardboard output.  [sadface]

**Comment by rusmaxham** [comment]
Is this still an issue?  If so, can you send me a simple project that reproduces the issue?

**Comment by rusmaxham** [comment]
If you are still experiencing this issue, feel free to reopen with more details.

**Comment by fredsa** [comment]
Also, please try the latest version of the Google VR SDk for Unity, which in natively integrated with Unity. Note, with native integration you'll no longer see a stereo preview in the game view, but you will see stereo when running in VR mode on a phone.
