### ISSUE TITLE
App crashes when building for Daydream with Vulkan

### ISSUE THREAD

**Issue by quentinleguennec** [googlevr/gvr-unity-sdk#525]
Hi,

I've been trying to use the new Vulkan API from Unity 5.6 with our Daydream VR project but when we build our app using Vulkan the app crashes at start. It builds without errors, installs fine on the device but when launched it crashes.  It works fine if we use OpenGLES3 but not with Vulkan. 

I don't know if it's because of the GVR SDK or purely a bug in Unity.

**Comment by bopangzz** [comment]
GVR SDK doesn't have Vulkan support for now. You have to use gles if you are developing Daydream.
