### ISSUE TITLE
GvrIntent.IsLaunchedFromVr() always returns true

### ISSUE THREAD

**Issue by cvasquez-github** [googlevr/gvr-unity-sdk#526]
We are using Unity Unity 5.6.0b11 (64-bit) and Google VR SDK for Unity v1.30.
We launch our Daydream app from Daydream launcher only.

From Daydream launcher, you can run the app from the 2D icon (Library list) or from the VR Home (3D icon):  We expected that if we launch our app from the 2D icon (2D Library) GvrIntent.IsLaunchedFromVr() should return false, and if we launch our app from the 3D icon (VR Home) GvrIntent.IsLaunchedFromVr() should return true. BUT we realized that in both cases it returns TRUE.

It looks like it only returns false if launched from a standard Android launcher icon.

Is this a bug?
Thanks

**Comment by vinhui** [comment]
We don't have that issue, we're currently on 5.6.0f1 but I think we implemented that on 5.6.0b11 and didn't have any issues.

**Comment by cvasquez-github** [comment]
I think is a Google VR SDK 1.30 issue, not a Unity issue.
GvrIntent.IsLaunchedFromVr()  is returning TRUE when running the app from Daydream Library regardless of the UI mode (2D or 3D/VR menu). Returning FALSE only if started from Android standard launcher.  I think it should return true ONLY if the app was started from Daydream 3D/VR gui.

**Comment by miraleung** [comment]
If you look at the implementation of GvrIntent.IsLaunchedFromVr, we wrap Android methods as specified by GVR platform requirements. Could you please check if the app is being launched with "android.intent.extra.VR_LAUNCH"? A good reference is [getBooleanExtra](https://developer.android.com/reference/android/content/Intent.html#getBooleanExtra(java.lang.String, boolean)).
