### ISSUE TITLE
launchVrHomescreen not available in Unity SDK

### ISSUE THREAD

**Issue by cvasquez-github** [googlevr/gvr-unity-sdk#527]
In Unity, the only direct option to exit the app is calling Application.Quit() but that doesn't ensure you that the system is going to the VR Home, only if it was actually launched from Daydream VR home.

Daydream API includes launchVrHomescreen function that is intended for that purpose (not closing the app), but i understand that currently there is no way to call that function directly from Unity or from Google VR SDK for Unity (1.30).

The only workaround would be calling the Java function using and AndroidJavaObject like this:

AndroidJavaObject daydreamApiObj;
void Start()
{
AndroidJavaClass player = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
AndroidJavaObject androidActivity = player.GetStatic<AndroidJavaObject>("currentActivity");
AndroidJavaClass daydreamApiClass = new AndroidJavaClass("com.google.vr.ndk.base.DaydreamApi");
androidActivity.Call("runOnUiThread", new AndroidJavaRunnable(() =>
daydreamApiObj = daydreamApiClass.CallStatic<AndroidJavaObject>("create", androidActivity)
));
}

void openHomeScreen()
{
daydreamApiObj.Call("launchVrHomescreen");
}

Is there any reason why not including/exposing this function in the Google VR SDK for Unity? Maybe could be included in the next version? Or is there a better way to go to Daydream VR Home from Unity?

Thank you very much!

**Comment by miraleung** [comment]
This will be included in v1.40, thanks for the feedback. :)

**Comment by cvasquez-github** [comment]
Excellent, good news, Thank you!
