### ISSUE TITLE
brightness

### ISSUE THREAD

**Issue by mjsibbald** [googlevr/gvr-unity-sdk#528]
Is there some documentation about what happens to the brightness in daydream? Our scenes are pretty dark in daydream. And is there a way to override or change it?

**Comment by guneyozsan** [comment]
From Unity 5.6 release notes:

> VR: [Daydream] You may notice that your Daydream VR display is dimmer than other VR devices. This is by design, as a means of prolonging battery life while in VR.
https://unity3d.com/unity/whats-new/unity-5.6.0

**Comment by mjsibbald** [comment]
Yeah I've seen it. So there is no way top control dimming(?) @guneyozsan thanks for sending that!

**Comment by miraleung** [comment]
Thanks for your feedback. This is controlled from VrCore, and the GVR Unity SDK does no logic around this. Please file issues in github.com/googlevr/gvr-android-sdk if you have further questions.
