### ISSUE TITLE
DllNotFoundException: gvr

### ISSUE THREAD

**Issue by rooskienz** [googlevr/gvr-unity-sdk#529]
Hi,

I'm running GVR 1.3 with Unity 5.6.0f3 and when I'm trying to launch the app with Cardboard SDK added to Virtual Reality Supported in Player Settings on ASUS Zenfone 2 the VR mode doesn't kick in. When look at the log from `adb logcat` I see this error: `DllNotFoundException: gvr`

The `VRSettings.supportedDevices` does have the `cardboard` entry but like I said the VR mode doesn't kick in when I try to load the `cardboard` device.

**Comment by miraleung** [comment]
If Cardboard is enabled in Player Settings, could you please check if Google VR Services is installed?

**Comment by rooskienz** [comment]
No it wasn't. Does it need to be installed? Because this same App was running on other devices without Google VR Services in VR mode.

**Comment by miraleung** [comment]
Daydream-ready phones should have Google VR Services installed. Another thing to check is whether there are errors at startup time in the logs - this can prevent the VR mode from loading.

**Comment by rusmaxham** [comment]
I'm going to close this issue.  If you are still experiencing this issue, please comment with more details about your current experience.

**Comment by lionliam96** [comment]
Obsolete? No, it`s not. I`m still experiencing this issue with the zenfone 2 and unity 2017.2f1.

**Comment by lionliam96** [comment]
I`m still experiencing this issue with unity 2017.2.1f1 on Zenfone 2. 
I get the following message in my log when switching to VR mode:
D/Unity: Unable to lookup library path for 'gvr', native render plugin support disabled.
E/Unity: Unable to find gvr
