### ISSUE TITLE
Error Google VR SDK 1.30 in unity5.5 :  CommandInvokationFailure: Failed to re-package resources !!

### ISSUE THREAD

**Issue by abosaqer** [googlevr/gvr-unity-sdk#530]
CommandInvokationFailure: Failed to re-package resources.
C:\Users\Lenovo\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Users/Lenovo/AppData/Local/Android/sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.gvr.permissionsupport:com.google.vr.cardboard:com.oculus.Integration:vr.gvr.platform.unity -S "C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr-permissionsupport-release\res" -S "C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res" -S "C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\OVRPlugin\res" -S "C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\unitygvractivity\res"

stderr[
AndroidManifest.xml:30: error: No resource identifier found for attribute 'enableVrMode' in package 'android'

]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Users\Lenovo\AppData\Local\Android\sdk\platforms\android-23\android.jar
applyFileOverlay for drawable
trying overlaySet Key=quantum_ic_close_white_24.png
trying overlaySet Key=quantum_ic_settings_white_24.png
trying overlaySet Key=rippleable.xml
trying overlaySet Key=transition.png
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
trying overlaySet Key=back_button.xml
trying overlaySet Key=settings_button.xml
trying overlaySet Key=transition_view.xml
trying overlaySet Key=ui_layer.xml
trying overlaySet Key=ui_layer_with_portrait_support.xml
trying overlaySet Key=dialog.xml
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable-xhdpi\app_banner.png
Processing image: res\drawable-mdpi\app_icon.png
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_close_white_24.png
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_close_white_24.png
    (processed image     C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_(proceandroid_common\res\drawable-mdpi-v4\quantum_ic_close_white_24.png: ssed image C:\U134sers\Lenovo\Docum% size of source)
ents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_close_white_24.png: 126% size of source)
PProcesrocessisinng ig maige:ma ge: C:\CUse:\Urs\Lenovos\Dersoc\Leumenontsvo\Documen\VRtssa\VmRsple\amTplemp\Se\tTeagmp\StainginggArAea\andrrea\anodroiidd-l-libibrarrarieiess\gvr_\gvr_anandrdrooiid_d_ccomommomonn\\res\drawrabele-xs\draxhwabdlepi-x-hv4\dpquantium_-v4\quantuic_cm_liosec_close__whwhiite_2te_24.png4
.png
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxhdpi-v4\quantum_ic_close_white_24.png: 113% size of source) 
   (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quantum_ic_close_white_24.png: 117% size of source)
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_cProceommon\res\drawssing image: abC:\Users\Lenovo\Docle-xxxhdpi-v4\quantumeum_ic_close_whitents_24.pn\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\qg
uantum_ic_settings_white_24.png
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\quantum_ic_settings_white_24.png: 186% size of source)
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_settings_white_24.png
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\quantum_ic_settings_white_24.png: 177% size of source)
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quantum_ic_settings_white_24.png
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxxhdpi-v4\quantum_ic_close_white_24.png: 107% size of source)
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxhdpi-v4\quantum_ic_settings_white_24.png
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xhdpi-v4\quantum_ic_settings_white_24.png: 174% size of source)
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxxhdpi-v4\quantum_ic_settings_white_24.png
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxhdpi-v4\quantum_ic_settings_white_24.png: 172% size of source)
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-xxxhdpi-v4\quantum_ic_settings_white_24.png: 164% size of source)
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\transition.png
Processing image: C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\transition.png
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-mdpi-v4\transition.png: 72% size of source)
    (processed image C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-hdpi-v4\transition.png: 66% size of source)
    (processed image res\drawable-xhdpi\app_banner.png: 93% size of source)
    (processed image res\drawable-mdpi\app_icon.png: 94% size of source)
    (new resource id app_banner from xhdpi-v4\drawable\app_banner.png #generated)
    (new resource id app_icon from mdpi-v4\drawable\app_icon.png #generated)
    (new resource id quantum_ic_close_white_24 from mdpi-v4\drawable\quantum_ic_close_white_24.png #generated)
    (new resource id quantum_ic_close_white_24 from hdpi-v4\drawable\quantum_ic_close_white_24.png #generated)
    (new resource id quantum_ic_close_white_24 from xhdpi-v4\drawable\quantum_ic_close_white_24.png #generated)
    (new resource id quantum_ic_close_white_24 from xxhdpi-v4\drawable\quantum_ic_close_white_24.png #generated)
    (new resource id quantum_ic_close_white_24 from xxxhdpi-v4\drawable\quantum_ic_close_white_24.png #generated)
    (new resource id quantum_ic_settings_white_24 from mdpi-v4\drawable\quantum_ic_settings_white_24.png #generated)
    (new resource id quantum_ic_settings_white_24 from hdpi-v4\drawable\quantum_ic_settings_white_24.png #generated)
    (new resource id quantum_ic_settings_white_24 from xhdpi-v4\drawable\quantum_ic_settings_white_24.png #generated)
    (new resource id quantum_ic_settings_white_24 from xxhdpi-v4\drawable\quantum_ic_settings_white_24.png #generated)
    (new resource id quantum_ic_settings_white_24 from xxxhdpi-v4\drawable\quantum_ic_settings_white_24.png #generated)
    (new resource id rippleable from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable\rippleable.xml)
    (new resource id rippleable from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\drawable-v21\rippleable.xml)
    (new resource id transition from mdpi-v4\drawable\transition.png #generated)
    (new resource id transition from hdpi-v4\drawable\transition.png #generated)
    (new resource id back_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout\back_button.xml)
    (new resource id back_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout-land\back_button.xml)
    (new resource id back_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout-ldrtl-v17\back_button.xml)
    (new resource id back_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout-ldrtl-land-v17\back_button.xml)
    (new resource id dialog from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr-permissionsupport-release\res\layout\dialog.xml)
    (new resource id settings_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout\settings_button.xml)
    (new resource id settings_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout-land\settings_button.xml)
    (new resource id settings_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout-ldrtl-v17\settings_button.xml)
    (new resource id settings_button from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout-ldrtl-land-v17\settings_button.xml)
    (new resource id transition_view from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout\transition_view.xml)
    (new resource id ui_layer from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout\ui_layer.xml)
    (new resource id ui_layer_with_portrait_support from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout\ui_layer_with_portrait_support.xml)
    (new resource id ui_layer_with_portrait_support from C:\Users\Lenovo\Documents\VRsample\Temp\StagingArea\android-libraries\gvr_android_common\res\layout-land\ui_layer_with_portrait_support.xml)
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg, Int32 retriesOnFailure)
UnityEditor.HostView:OnGUI()

**Comment by miraleung** [comment]
Looks like this is the AndroidManifest-Daydream.xml. Unity 5.5 does not have the GVR integration, could you please try Unity 5.6.0f3 with Daydream enabled in Player Settings?

**Comment by slashwon** [comment]
The same question and don't know how to resolve it

**Comment by miraleung** [comment]
@slashwon There are two ways to solve this. One is to replace Assets/Plugins/Android/AndroidManifest.xml with Assets/Plugins/Android/AndroidManifest-Cardboard.xml. The other is to upgrade to Unity 5.6.0f3, and build with "Player Settings > Daydream" or Cardboard enabled.
