### ISSUE TITLE
Samples fail in Unity 5.6

### ISSUE THREAD

**Issue by andybak** [googlevr/gvr-unity-sdk#531]
Steps to reproduce:

1. Download zip file of repo master branch (commit March 8th db72f4dd8f255ee143bcc39e95e52c895e1c5e32 )
2. Unzip and open the DaydreamLabsControllerPlayground directory in Unity 5.6.0f3 as a project
3. Agree to the "I made a backup. Upgrading APIs" prompt.
4. Plug in a Daydream compatible phone and select "Build and Run"

Result: Build fails immediately with lots of console errors

Expected result: A successful build.

**Comment by miraleung** [comment]
Could you please ensure you have targeted Android, and Daydream is enabled in Player Settings?

**Comment by dsternfeld7** [comment]
Closing this because DaydreamLabsControllerPlayground is deprecated.
