### ISSUE TITLE
must remove file

### ISSUE THREAD

**Issue by disigenzhiwei** [googlevr/gvr-unity-sdk#534]
![image](https://cloud.githubusercontent.com/assets/17585559/25044382/f69fa94e-2158-11e7-82c6-4dc2b4ce92fb.png)

**Comment by HackerPoet** [comment]
This is normal.  The plugin contains multiple libraries so that it can be compatible with different Unity versions, and will delete the files it doesn't need.  Does the rest of your project work as expected?

**Comment by miraleung** [comment]
Yes, this is expected for 5.4.2f2-GVR13 and 5.6.0f3.

**Comment by disigenzhiwei** [comment]
Sorry if I remove the file,it can’t work on my android phone when the project be packaged into APK.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: HackerPoet<mailto:notifications@github.com>
发送时间: 2017年4月18日 1:04
收件人: googlevr/gvr-unity-sdk<mailto:gvr-unity-sdk@noreply.github.com>
抄送: disigenzhiwei<mailto:disigenzhiwei@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [googlevr/gvr-unity-sdk] must remove file (#534)


This is normal. The plugin contains multiple libraries so that it can be compatible with different Unity versions, and will delete the files it doesn't need. Does the rest of your project work as expected?

―
