### ISSUE TITLE
How to change Field of view on VrEye of Left and Right Camera in unity5.6 android

### ISSUE THREAD

**Issue by Ankitjagrawat** [googlevr/gvr-unity-sdk#535]
Hi,
    I am using Unity 5.6 android , VR Native supported is On and add cardboard and import GoogleVrFor unity V1.30 and drag prefab GvrMain in scene i have change field of view of left/right camera its working fine in unity editior but its working android device
![capture](https://cloud.githubusercontent.com/assets/5147591/25081498/6670d624-2368-11e7-8525-c6c6088816e5.PNG)
![capture1](https://cloud.githubusercontent.com/assets/5147591/25081620/fded3376-2368-11e7-8071-8ae564515393.PNG)

**Comment by HackerPoet** [comment]
You can't change the field of view of a VR camera since the FOV needs to match the physical parameters of the device in order to simulate VR correctly.  If you have design elements that need larger FOVs, you'll need to push them farther back or re-design them.

**Comment by bopangzz** [comment]
Yes, FOV need to match the VR viewer so you cannot change it.
