### ISSUE TITLE
Head tracking freezes at current rotation on LG-M210 when switching from 2D to VR

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/gvr-unity-sdk#537]
The head tracking freezes at the current rotation when the app switches from 2D to VR on an LG-M210. The freeze occurs at whatever rotation you were holding the device while switching. Back button and tap functionality remains (it is possible to tap, if by chance VR mode freezes while the reticle is hovering interactible, or back button goes back to VR mode).

Our app switches from 2D portrait to VR Cardboard. 2D mode is a single scene and we call the VR mode on Start() of the VR scene, with a delay of one second. 

This is a user reported bug so we can't experiment variations.

That version is Unity 5.6.0f2 and Google VR SDK 1.30, Cardboard mode (no Daydream).

**Comment by rusmaxham** [comment]
Are you still experiencing this issue with the latest versions of Unity and the GVR SDK for Unity?

**Comment by rusmaxham** [comment]
If you are still experiencing this issue, feel free to reopen with more details.
