### ISSUE TITLE
[GVR 1.40] Android null reference stereocontroller

### ISSUE THREAD

**Issue by maskedmous** [googlevr/gvr-unity-sdk#538]
What went wrong?

After building an Android build, using Unity 5.6.0f3, GVR v1.40, mono2.x and having Virtual Reality Supported enabled, cardboard in the list as only VR device. The logs are spitting out a constant null reference error in the StereoController script at line 347.

```  C#
void OnPreCull() 
{
    if (GvrViewer.Instance.VRModeEnabled) {
      // Activate the eyes under our control.
      GvrEye[] eyes = Eyes;
      for (int i = 0, n = eyes.Length; i < n; i++) {
        eyes[i].cam.enabled = true;
      }
      // Turn off the mono camera so it doesn't waste time rendering.  Remember to reenable.
      // @note The mono camera is left on from beginning of frame till now in order that other game
      // logic (e.g. referring to Camera.main) continues to work as expected.
      cam.enabled = false;
      renderedStereo = true;
    } else {
      GvrViewer.Instance.UpdateState();
    }
  }
```

The cam variable is not initialized because it has been put under the !UNITY_HAS_GOOGLEVR
``` C#
#if !UNITY_HAS_GOOGLEVR || UNITY_EDITOR
    void Awake()
    {
        cam = GetComponent<Camera>();
    }
```

**Comment by maskedmous** [comment]
Seems like it is caused by mono2.x
When building IL2CPP this error does not occur
Might want to check whether the build is set to IL2CPP just like Virtual Reality supported is checked if possible

**Comment by miraleung** [comment]
StereoController isn't needed for native integration builds (5.6+, 5.4.2f2-GVR13), so this code path should not run on-device. This script, everything in Legacy, and GvrViewer.cs will be going away in the next release, so please consider migrating.
