### ISSUE TITLE
[GVR 1.40] iOS linker error

### ISSUE THREAD

**Issue by maskedmous** [googlevr/gvr-unity-sdk#539]
What went wrong?

I've built an iOS xCodeProject on a Windows PC using Unity 5.6.0f3, virtual reality support enabled with cardboard as target. Using IL2CPP
Updated the pods to 1.40 as described in the readme.
But then building for iOS through xCode, still getting linker errors

ld: warning: directory not found for option '-L/Users/username/Library/Developer/Xcode/DerivedData/Unity-iPhone-ajdekaqqrmledzdchoibvphybhie/Build/Products/Release-iphoneos/GTMSessionFetcher'
ld: warning: directory not found for option '-L/Users/username/Library/Developer/Xcode/DerivedData/Unity-iPhone-ajdekaqqrmledzdchoibvphybhie/Build/Products/Release-iphoneos/GoogleToolboxForMac'
ld: library not found for -lGTMSessionFetcher
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by maskedmous** [comment]
After some searching I came across this:
[(https://forum.unity3d.com/threads/unity-5-6-0f3-google-cardboard-ios-xcode-linker-errors.464719/#post-3036269)]

> I finally found out that i had to open the xcworkspace instead of the xcodeproj. Using the xcworkspace, there is a "Pods" that is added and compiled before the unity project.

If this is the solution for building an iOS build it would be nice to mention somewhere to use the xcworkspace instead of xcodeproj.

**Comment by bopangzz** [comment]
Yeah, that is the correct solution. The step for building iOS is included in the repo README file.

**Comment by fredsa** [comment]
Updated doc here:
https://developers.google.com/vr/unity/get-started-ios

**Comment by RameshSain** [comment]
same issue , with xcode 9.2

**Comment by kuez** [comment]
Same issue, with Xcode 9.3 :/

**Comment by rusmaxham** [comment]
Open the .xcworkspace file, not the .xcodeproj to build.  Unity should be opening the workspace in Xcode automatically.
