### ISSUE TITLE
when entering UI Button Reticle shake 

### ISSUE THREAD

**Issue by Joeeeeeeeee** [googlevr/gvr-unity-sdk#541]
unity5.5.0 & GVR SDK 1.3.0

**Comment by vinhui** [comment]
Is this the same issue as #521 ?

**Comment by Joeeeeeeeee** [comment]
@vinhui when i submited i saw #521 sorry.
but  test unity5.5.0 with GVR SDK1.4.0 ,show same issue.

**Comment by dsternfeld7** [comment]
Thank you for the report! I am not able to reproduce this issue in GVR SDK 1.100.1

If you are still seeing this in the latest SDK, please feel free to open a new issue with details about how to reproduce the bug and I will investigate.

Thanks,

Dan
