### ISSUE TITLE
Can I Disable Stereo Rendering and still use the Daydream Controller with Native Integration?

### ISSUE THREAD

**Issue by momo-the-monster** [googlevr/gvr-unity-sdk#542]
I'd like to be able to demo my application outside of the headset using the Daydream controller.
I see that VRModeEnabled is no longer supported, is there any other way to toggle stereo rendering but keep Daydream Controller input?

**Comment by fredsa** [comment]
VRSettings.enabled and VRSettinga.LoadDeviceByName("") are your friends.

**Comment by momo-the-monster** [comment]
Thanks, @fredsa. I've tried the method from [this Stackoverflow Post](http://stackoverflow.com/a/36702577) and the app restarts in non-VR mode but I no longer have controller input, and my logcat fills with the following error:
`Null GVR context pointer, could not get GVR user prefs' handedness`

I'm using Unity 5.6.0f3.

**Comment by miraleung** [comment]
There are some C# changes that are also required - please see issue #532.

**Comment by momo-the-monster** [comment]
Thanks @miraleung - I've included those changes now but I still have the "Null GVR context pointer" error repeatedly triggered, and the controller is no longer useable. I'll rename this issue to focus on the controller. My focus is on the stereo rendering and not disabling the VR Device because I still want access to the controller, which I imagine is only available while 'using' Daydream mode at the moment.

**Comment by vinhui** [comment]
Have you tried setting Camera.stereoEnabled to false? https://docs.unity3d.com/ScriptReference/Camera-stereoEnabled.html

**Comment by momo-the-monster** [comment]
@vinhui - Camera.stereoEnabled appears to be read-only.
From the engine:
`public bool stereoEnabled { get; }`

**Comment by rusmaxham** [comment]
GVR does not allow the use of the Daydream controller outside of Daydream VR mode.
