### ISSUE TITLE
Daydream iOS development now supported in Unity 5.6?

### ISSUE THREAD

**Issue by borderlineinteractive** [googlevr/gvr-unity-sdk#544]
I saw this on the release notes for Google VR 1.40. Does this mean, that the Daydream controller is now supported on iOS devices, or is this a typo and should this be "Cardboard iOS development now supported in Unity 5.6"?

**Comment by pancymon1** [comment]
You can consider it as a typo. AFAIK, Daydream is not supported on iOS.

**Comment by nathanmartz** [comment]
That's correct. Sorry for the typo.
