### ISSUE TITLE
GvrVideoPlayerTexture Play mp4 exception

### ISSUE THREAD

**Issue by YoungBill** [googlevr/gvr-unity-sdk#546]
I used the sdk inside the VideoDemo scene, when playing 360 video, if the play that comes with the link --- https: //storage.googleapis.com/daydream-deveng.appspot.com/japan360/dash/japan_day06_eagle2_shot0005-2880px_40000kbps .mpd --- video, it is normal, but when I play mp4, playing abnormal, about 2 eyes to see the screen is inconsistent, the gear seen on the gear is very deformed, what is the reason

**Comment by rusmaxham** [comment]
What is the mp4 file?  Is it a local file or something from the internet?

**Comment by YoungBill** [comment]
it is from internet,http://192.168.1.251/server01/test.mp4

**Comment by rusmaxham** [comment]
192.168.x.x is a private network, inaccessible from the open internet.  Is there any way I can access your video to help debug the issue?

**Comment by YoungBill** [comment]
oh，sorry，You can use this link to download this mp4 video and then play it

**Comment by rusmaxham** [comment]
Ah, i see the issue now.  Your video is 360 mono, not stereo.  The shader used in the demo app is configured by default to render top-bottom stereo video like this: http://youtu.be/LKsUxHASFBs

To use mono video you'll need to edit the SteroPanoSphereMaterial on the Sphere game object and set the "Render Stereo Video" value to 0.

**Comment by YoungBill** [comment]
I have changed my shader, as you said that, and then apply up, but when I play this video, the problem still exists, is not also need to change the other properties, I put my shader to you

**Comment by YoungBill** [comment]
Shader "GoogleVR/Demos/My VideoDemo InsideShader" {
    Properties {
        _Gamma ("Video gamma", Range(0.01,3.0)) = 1.0
        _MainTex ("Base (RGB)", 2D) = "white" {}
        _StereoVideo ("Render Stereo Video", Int) = 0
    }

    SubShader {
        Pass {
            Tags { "RenderType" = "Opaque" }

            // cull the outside, since we want to draw on the inside of the mesh.
            Cull Front

            CGPROGRAM
                #pragma vertex vert
                #pragma fragment frag

                #include "UnityCG.cginc"
                #include "../../../Shaders/GvrUnityCompatibility.cginc"

                float4 _MainTex_ST;
                sampler2D _MainTex;
                int _StereoVideo;
                float _Gamma;

                struct v2f {
                    float4 pos : SV_POSITION;
                    float2 uv : TEXCOORD0;
                };

                float3 gammaCorrect(float3 v)
                {
                    return pow(v, 1.0/_Gamma);
                }

                float3 gammaCorrectApprox(float3 v)
                {
                    return rsqrt(v);
                }

                // Apply the gamma correction.  One possible optimization that could
                // be applied is if _Gamma == 2.0, then use gammaCorrectApprox since sqrt will be faster.
                // Also, if _Gamma == 1.0, then there is no effect, so this call could be skipped all together.
                float4 gammaCorrect(float4 v)
                {
                    return float4( gammaCorrect(v.xyz), v.w );
                }

                v2f vert (appdata_base v) {
                    v2f o;
                    // invert the normal of the vertex
                    v.normal.xyz = v.normal * -1;
                    o.pos = GvrUnityObjectToClipPos(v.vertex);
                    o.uv = TRANSFORM_TEX (v.texcoord, _MainTex);
                    if (_StereoVideo > 0) {
                        o.uv.y *= 0.5f;
                        if(unity_StereoEyeIndex == 0) {
                            o.uv.y += 0.5f;
                        }
                    }
                    o.uv.x = 1 - o.uv.x;
                    return o;
                }

                fixed4 frag (v2f i) : SV_Target {
                    return gammaCorrect(tex2D(_MainTex, i.uv));
                }
            ENDCG
        }
    }
    Fallback "Mobile/VertextLit"
}

**Comment by rusmaxham** [comment]
I got your video to play correctly in the video demo by just changing the "Render Stereo Video" setting in the StereoPanoSphereMaterial shader settings to 0.

![screen shot 2017-04-28 at 1 04 50 pm](https://cloud.githubusercontent.com/assets/13911074/25545425/a9217fec-2c13-11e7-9700-5be04ca7d99f.png)

**Comment by YoungBill** [comment]
Ok, thank you, you said the solution is indeed resolved, but I now use easymoivetexture, and this plug-in just fine. I am Chinese, you have qq or WeChat, we can discuss the problem before ah
