### ISSUE TITLE
Lack of proper Documentation and supportive materials

### ISSUE THREAD

**Issue by adi-dhal** [googlevr/gvr-unity-sdk#548]
With much change in the scripts from the previous versions.No proper documentation is being provided about the new introduced scripts so that one can switch from the previous versions. As all the supportive materials present refer to the depreciated versions.

**Comment by martinbilello** [comment]
Hi, which version is the one you refer to as lacking proper documentation? Can you give a specific example?
Thanks

**Comment by mgrider** [comment]
I would agree that there is inadequate (is there any?) documentation regarding upgrading from previous versions.

**Comment by lettucehead** [comment]
This is somewhat absurd

**Comment by nathanmartz** [comment]
We try to make version updates be as simple as dropping on a new plugin. Upgrading Unity is a bit more involved, but the issues you run into there aren't specific to Daydream.

To echo martin's comment earlier, specific examples of pain points would be very helpful.

**Comment by alimoeeny** [comment]
I am basically stuck on Unity 5.6.0b7 because the upgrade process to stable with google-vr is messed up and I spent a couple of days in pain when Unity came out of beta and I am not trying it again anytime soon.

**Comment by mgrider** [comment]
I have google cardboard apps from last year that are basically "stuck" at v0.7.2 because that was the version before everything was renamed. That's definitely one of the biggest pain points as far as I'm concerned.

**Comment by miraleung** [comment]
@alimoeeny The post-beta releases are in a more stable state, 5.6.0f3 is a good one to start with.

@mgrider Thanks for your feedback. We have been improving continuously since then, and have planned our updates to be as smooth as possible. As for upgrading from 0.7.2, here is one path that may work:
- v0.7.2 -> 0.85
- 0.85 -> 1.0
- 1.0 -> 1.4 

Please note that as of 1.50, we will be supporting only Unity 5.6 and newer versions. However, there will be no code changes required when going from 1.4 to 1.5.

Hope that helps.

**Comment by mgrider** [comment]
This is maybe it's own issue, but I've decided Unity 5.6 support for Cardboard is garbage, and the solution for my current project is to roll back to 5.5 (and cardboard 0.7.2). As near as I can tell, there is no way to disable the "transition view" that asks users to put their phone in the headset, etc. Unity issue here: https://issuetracker.unity3d.com/issues/ios-cardboard-splash-screen-appears-even-if-enable-transition-view-is-set-to-false My app needs to launch in full screen, and that's similarly impossible as near as I can tell.

@miraleung As I mentioned, instructions for upgrading past 0.7.2 are what's needed, as all the classes have been renamed, a step-by-step checklist would not be out of order. (It may be as simple as replacing all instances of `Cardboard.SDK` with something else, and re-dragging out prefabs? ...but I have no idea.)

**Comment by alimoeeny** [comment]
It goes without saying that "thank you @miraleung it is a lot of work and needs a lot of patience answering to comments and issues on github".

@miraleung I assume you guys are under a lot of political pressure inside google or in interaction between google and unity. And dealing with lots of non technical restrictions.
On the other hand, we need to know if you expect us to always stay on the latests combination of betas (of unity and gvr) for the upgrades to be less painful or we need to stick to stable releases and have clear upgrade paths. 
That period where unity 5.6 stable did not work with the latest (or any) gvr messed everything up. That is why I and others are stuck in weird combinations of versions. 
I hope unity and google get to some understanding that makes this work smoother in future.

**Comment by nathanmartz** [comment]
Appreciate the feedback, closing out as 5.6.1p3 is pretty solid and we're focused on further improvements, and bug fixes.
