### ISSUE TITLE
Unity5.6 native integration + portrait mode + back button

### ISSUE THREAD

**Issue by noemis84** [googlevr/gvr-unity-sdk#549]
hey there,
nearly all our cardboard apps start in portrait mode and switch later to VR Mode (and back). So the main issue seem to be (when using the new native cardboard integration in Unity 5.6) :

**1. Issue: Why does the checkbox "virtual reality supported" in unity overrides the settings for device orientation?** After enabling this checkbox you can add "none" and "cardboard" - which already shows, someone thought about this case, but it seems not long enough... it would be much less anoying, if an app shows the splash always in portrait and switch later to landscape, after first VR sdk is loaded and enabled. The current status is:
1. Press app icon
2. device automatically switches to landscape (not wanted)
3. app is started
4. app switches back to portrait (not wanted)
5. I press my custom button to start vr mode
6.  device orientation swtiches to landscape

Is there maybe a workaround I do not think of?

**2. Issue: Can we override the "back" behavior?** If cardboad sdk is loaded and activated, the cross appears in the upper left corner. By pressing this, the app closes automatically. Again: why? Should't developer decide, what happens if user interact? I don't want to close, I just want to disable the vrmode and show 2D Menü in portrait mode again.

Hope we'll get some support. Same problem in Unity Forum get's no reaction since begining of the month: [Link Unity Forum same topic](https://forum.unity3d.com/threads/u5-6-native-cardboard-vr-possible-to-launch-app-in-portrait-orientation.464316/)

**Comment by zleisure** [comment]
I have the same problem.Who has a solution？

**Comment by guneyozsan** [comment]
A workaround is to use Unity plus and turn off splash screen. Then if you want you can add a hand made splash screen as a separate scene.

Also you can make the first frame black so that automatic transitions on launch are not noticeable.  But still there is no way to prevent desktop rotating to landscape when the app launches. 

I think exiting with the cross is a global behavior among all cardboards. What you can do is to switch to portrait mode with back button or when you detect portrait orientation.

**Comment by miraleung** [comment]
The orientation is locked to landscape left - displaying in portrait mode was a bug. 

To override the back button behaviour, please take a look at GVRDemo and Assets/GoogleVR/Demos/Scripts/DemoInputManager.cs.

**Comment by miraleung** [comment]
Could you please post a screenshot of the VR SDKs enabled under "Virtual Reality Supported"?

**Comment by noemis84** [comment]
@miraleung: I'm not sure, if a screenshot is helpul at this point - as described in the first post, I add none and cardboard... because I want to start this app in portrait with "none" vr functionality and initiate later cardboard skd.
![sdks](https://cloud.githubusercontent.com/assets/13518143/25611660/2ff8042a-2f28-11e7-817d-abd7ec8a360c.jpg)

@guneyozsan  - thank you for the workaround idea... I hoped in 2017 I won't using workarounds anymore - at least for such simple kind of things, which are just a lag of dev options.

**Comment by miraleung** [comment]
@noemis84 Could you please file a bug in Unity, and reply with the case ID? This will help us sync investigation.

**Comment by noemis84** [comment]
(Case 918407) Starting in portrait orientation when using virtual realtiy supported

[Link to status page](https://fogbugz.unity3d.com/default.asp?918407_st99vnbns3dn5eba)

**Comment by noemis84** [comment]
It seems 5.6.1 hasn't this problem anymore... close this issue for now.

**Comment by PedroEugenio** [comment]
@noemis84 Simple and effective solution! Thanks, that work's for me!
