### ISSUE TITLE
Point Lights not rendering on both eyes (Unity 5.6.f03 + GVR 1.40)

### ISSUE THREAD

**Issue by tibor0991** [googlevr/gvr-unity-sdk#551]
I've noticed today that point lights are rendered only in the left eye instead of being rendered on both.
To test this bug I did the following steps:

1. Made a new 3d Project on Unity 5.6.0f3;
2. Downloaded the entire content of this repo;
3. Launched the GVR Unity Package;
4. Installed the whole package in the project;
5. Switched the project target to Android;
6. When Unity complained about extra files, I gave it the permission to delete them;
7. Set up a sample scene with one point light, one floor and a cube, no directional lights;
8. In _Player Settings_, checked the VR checkbox and added Daydream on the list of supported platforms.

This is the final result.
![image](https://cloud.githubusercontent.com/assets/6933886/25565118/c421b442-2dc1-11e7-8c52-f99d8afc1520.png)
As you can see, on the right eye there are no lights at all.
Are there any workarounds for this?

UPDATE: So, apparently, this bug is only visible during the edit on the Game window, but it's absent on the final build. Still, it must be solved or else you'll have to make a build every time to see if everything works without breaking.

**Comment by miraleung** [comment]
Thanks. We have reported this issue, and Unity is investigating.

**Comment by miraleung** [comment]
The GvrViewerMain editor emulator will be going away in the upcoming release. We will be providing other ways for previewing stereo in Play mode, stay tuned!

**Comment by tareksalah** [comment]
I had a similar bug here https://discussions.udacity.com/t/right-eye-renders-at-a-different-quality-than-left-eye/245515
