### ISSUE TITLE
iOS Documentation issues

### ISSUE THREAD

**Issue by mgrider** [googlevr/gvr-unity-sdk#553]
This page is the one I'm referring to: https://developers.google.com/vr/unity/get-started-ios

1. At the top of the page, there is a reference to some kind of game, Treasure Hunt, which is never mentioned again.

2. An additional step is missing, enabling VR in project settings (and making sure Cardboard is included).

**Comment by miraleung** [comment]
Thanks for your feedback, we'll investigate to get that fixed. :)
