### ISSUE TITLE
distortion wrong on samsung S7

### ISSUE THREAD

**Issue by andyz** [googlevr/gvr-unity-sdk#555]
Built GVRDemo (1.4) with backwardsCompatibility installed (Unity 5.5) to S6 phone (after fixing manifest to stop crash at start - this in docs??).
On S6 works fine and distortion correct.
On S7 the distortion appears different (even after setting to same cardboard device as S6) and in cardboard shows double-vision, incorrect distortion.

Any known issue/fix there?

**Comment by ninjingames** [comment]
This is probably the same as issue #421 
We've been waiting for a fix from the GVR team for almost half a year now, so don't get your hopes up...

**Comment by andyz** [comment]
YES thanks, changing S7 resolution fixes it but as in that thread not a good solution to explain to end users!

**Comment by fredsa** [comment]
Duplicate issue #421
