### ISSUE TITLE
How to disable asynchronous reprojection?

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#557]
Is it possible to disable/prevent asynchronous reprojection when using the Google VR Unity sdk? If so, how is this accomplished?

I'm seeing an issue where my FPS indicators (including the GvrFPS prefab) are reporting 59.98-60fps but the actual rendering feels much closer in reality to 30-45fps. This happens during a particular segment of my game, and after that segment the FPS indicators become slightly more stable at 60fps but the actual rendering then feels like a proper smooth 60fps. I'm not sure if this could be related to asynchronous reprojection, but I figured it was worth disabling as a test.

Any ideas would be appreciated.

Thanks,
Dustin

**Comment by dustinkerstein** [comment]
I have the same performance issues when I enable VSync in the Unity quality settings. The only difference is that instead of the small 59.98-60fps fluctuations, it GvrFPS displays a rock solid 60fps even though the rendering is definitely much lower than that.

**Comment by nathanmartz** [comment]
If you build for cardboard it will disable async reprojection. Daydream always has async reprojection enabled.

Regarding the perf issue you're seeing, what device are you testing on? What version of Unity and what version of the GVR SDK?

**Comment by dustinkerstein** [comment]
Ok good to know. 

My perf issue turned out to be due to a plugin that wasn't fully threaded. Still strange to me that the FPS indicators weren't showing it, but I'll let that slide for now. 

Thanks for the info.
