### ISSUE TITLE
GvrViewer.Instance.VRModeEnabled not working on iOS

### ISSUE THREAD

**Issue by zuspan** [googlevr/gvr-unity-sdk#558]
I took the GVRDemo scene from the SDK package. I then run the code below on load. In the Game view within unity, this works - loading the scene without VR stereo rendering. (I can even toggle it with a button). However, when compiled and tested on iOS on an iPhone it only loads in VR mode, and the button I place in the scene does not trigger a toggle.

(I also cannot get the back arrow to trigger a VR mode toggle either.)

I have searched numerous online resources (stackoverflow, unity forum, etc.) and cannot find a solution. I'm guessing this may be a bug? My apologies if not...

code here:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardboardToggle : MonoBehaviour {

        public vrModeInt = 1; //should load with VR Mode disabled

	public void ToggleVRMode(){

		if (PlayerPrefs.GetInt ("Vr Mode") == 1)
			vrModeInt = 0;
		
		if (PlayerPrefs.GetInt ("Vr Mode") == 0)
			vrModeInt = 1;
		
		PlayerPrefs.SetInt ("Vr Mode", vrModeInt);
	}

	void Start (){
		PlayerPrefs.SetInt ("Vr Mode", vrModeInt);
		Debug.Log(PlayerPrefs.GetInt("Vr Mode"));
	}

	void Update () {

		if (PlayerPrefs.GetInt ("Vr Mode") == 0)
			GvrViewer.Instance.VRModeEnabled = true;
		
		if (PlayerPrefs.GetInt ("Vr Mode") == 1)
			GvrViewer.Instance.VRModeEnabled = false;

		//exits VR mode with back button - (also not working on iOS)
		if (GvrViewer.Instance.BackButtonPressed)
			ToggleVRMode ();

	}
}
```

Unity: 5.6.0f3
Google VR SDK for Unity: 1.40
iOS: 10.3 (iphone 6plus)

**Comment by vinhui** [comment]
I think they added native iOS vr support in unity, this means you have to use `VRSettings.enabled`

**Comment by zuspan** [comment]
@vinhui - thanks for lead on this! You are correct, VRSettings.enabled does toggle stereo VR rendering. Thank you. However, it also toggles head tracking, so when disabled, the camera does not move with the iphone's gyroscope. I would love functionality that toggles stereo rendering, but maintains head-tracking on iOS. Hmmm....

**Comment by vinhui** [comment]
You might still be able to use the GvrHead script

**Comment by zuspan** [comment]
@vinhui - thanks! That did it. If you attached the GvrHead script to your camera object and use `VRSettings.enabled` the cardboard toggle works in iOS. (The GVRDemo scene was attaching the GvrHead script to the camera object at runtime - this attachment was not executing when `VRSettings.enabled` was set to false...presumably.)

**Comment by AlbertMontserrat** [comment]
GvrHead is deprecated... How it works now?

**Comment by rusmaxham** [comment]
VR head-tracking is now built-in to Unity 5.6 and later.  Add VR SDKs in Player Settings and your main camera will be head-tracked and render in stereo.

**Comment by AlbertMontserrat** [comment]
But when i put none as a device, cardboard disapears but the app stops turning with gyroscope... It becomes a static scene...

**Comment by rusmaxham** [comment]
What you describe is called Magic Window, where there is head tracking without stereo rendering.  This is no longer possible with GoogleVR native integration into Unity.  You will need to use Google VR SDK for Unity v1.40 in order to do Magic Window.

**Comment by fredsa** [comment]
Marking this issue as closed since the original issue ("GvrViewer.Instance.VRModeEnabled not working on iOS") is no longer relevant in the latest Google VR SDK.

**Comment by fredsa** [comment]
Request for Magic Window support is tracked in #703.
