### ISSUE TITLE
Unity 2017.1.0b4 - Transitions Start2D>VR>2D>VR>...etc. all except first VR mode results in a mono screen without head tracking on Android.

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/gvr-unity-sdk#561]
Start from 2D mode, switch to VR and back a few times. All except first VR mode results in a mono screen without head tracking on Android (Samsung S7). Everything else remains functional. This happens with both GVR 1.30 and 1.40. on Unity 2017.1.0b3 and 2017.1.0b4. The same project works fine with 5.6.0f3 and 1.30 and 1.40.

(During transition, I wait a few extra frames between each command to address previous VRSettings.enabled crashes discussed here before.)

**Comment by tedruxpin** [comment]
Hello, we are investigating.  Are you able to test with a different device?

**Comment by miraleung** [comment]
Could you please file a bug within Unity and reply with the case ID?

**Comment by miraleung** [comment]
If this is still occurring, please reopen this bug with the Unity case ID. Thanks!

**Comment by guneyozsan** [comment]
Looks like this is fixed in 2017.1.0b8
