### ISSUE TITLE
problems with early phones w/ unity 5.6 iOS build

### ISSUE THREAD

**Issue by AndrewHeumann** [googlevr/gvr-unity-sdk#562]
The documentation claims iPhone 5 or later with iOS 8 or later is supported, but phones earlier than an iphone 6S are incorrectly displaying a recent project built under 5.6. Instead this appears: 
![image uploaded from ios](https://cloud.githubusercontent.com/assets/2157902/25875086/b7bcca4c-34e3-11e7-83ae-a487d29a475a.jpg) 
only a tiny corner displays any image at all, and it's very sluggish.
The same project looks fine on iOS 6S and 7. any ideas? some compatibility setting I'm missing?

**Comment by guneyozsan** [comment]
I develop on Android and use iPad mini 1st gen for testing (same generation with iPhone5) and it also run very sluggish on both iOS8 and iOS9 (impossible to use, just can test) and it crashes if I load some number of large textures.

It is not surprising that VR requires a decent phone but I think you've got point about the documentation.

**Comment by AndrewHeumann** [comment]
Seems like the issue was having player-settings anti-aliasing enabled. worked great on newer phones, but created major crashes / display issues for iPhone 6 or earlier.

**Comment by ChrisCF** [comment]
I was having this problem with 5.6.1f1. 5.6.1p3 seems to have fixed it. It was only happening when using metal for me
