### ISSUE TITLE
Android application after authorization, the camera view becomes smaller, not full screen

### ISSUE THREAD

**Issue by YoungBill** [googlevr/gvr-unity-sdk#563]
I use the unity of the development android applications. When the application does not allow READ_EXTERNAL_STORAGE authority, about 2 cameras view full screen, when running READ_EXTERNAL_STORAGE time, the camera view becomes smaller, not full screen, what is the solution?

**Comment by tedruxpin** [comment]
Could you please clarify the flow of the bug you are seeing?  Does the view shrink after the the permissions dialog appears, or if the permission is not enabled, the view is always smaller?

**Comment by YoungBill** [comment]
When I installed, it will pop up the authorization interface, I agree to go after the authorization, view becomes smaller, after the operation always smaller view. When the installation, I do not agree with those permissions, after running the view is not small, is full view

**Comment by rusmaxham** [comment]
What version of Unity and the GVR SDK for Unity are you using?  Can you reproduce this with the latest [GVR SDK for Unity](https://github.com/googlevr/gvr-unity-sdk/releases)?

**Comment by rusmaxham** [comment]
Feel free to reopen this issue if you are still experiencing it.
