### ISSUE TITLE
 GvrViewer.Instance.VRModeEnabled = false Does not work

### ISSUE THREAD

**Issue by YoungBill** [googlevr/gvr-unity-sdk#566]
why?I want to turn on / off vr mode at any time

**Comment by YoungBill** [comment]
I found GvrViewer.Instance.VRModeEnabled = false in the editor is valid, you can turn off vr mode, but packaged into the phone is invalid. Come and help out

**Comment by vinhui** [comment]
See #558

**Comment by YoungBill** [comment]
When I call VRSettings.enabled inside android, the program crashes

**Comment by miraleung** [comment]
Which Unity version are you using? On Unity 5.6 (which we now support exclusively), you can enable monoscopic mode by following the steps in #532.

**Comment by YoungBill** [comment]
I'm on Unity 5.6.0f3 and GVR SDK 1.4

**Comment by miraleung** [comment]
If this crashes again, could you please file a bug within Unity, and reply with the case ID?

**Comment by justinwasilenko** [comment]
Can confirm this is happening in Unity 5.6.1p1 still using a S6 and a Pixel for testing. Sounds like from some other threads here this is a common problem and I will just disable this option from my app even though it is used by quite a few users.

**Comment by savashito** [comment]
Hey all, reading this other post: [https://github.com/googlevr/gvr-unity-sdk/issues/628](url)
Help me figure it out:
```
using UnityEngine.VR;


        public void DisableVR ()
	{
		VRSettings.enabled = false;
Camera.main.ResetAspect ();
	}

	public void EnableVR ()
	{
		VRSettings.enabled = true;
	}
```

I am only missing the recentering when enabling VR, before I would do : GvrViewer.Recenter();
but GvrViewer, doesn't exist anymore :(

**Comment by fredsa** [comment]
> I found GvrViewer.Instance.VRModeEnabled = false in the editor is valid, you can turn off vr mode, but packaged into the phone is invalid. Come and help out

To correctly switch between VR and non-VR mode at runtime, see this example:
https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime


> When I call VRSettings.enabled inside android, the program crashes

If calling `VRSettings.enabled=false` still causes your app to crash with a recent stable version of Unity, please:
1. File a bug with Unity
2. File a new issue in this issue tracker and include the Unity case number

> Can confirm this is happening in Unity 5.6.1p1 still using a S6 and a Pixel for testing. Sounds like from some other threads here this is a common problem and I will just disable this option from my app even though it is used by quite a few users.

Setting `VRSettings.enabled` to `true`/`false` should not crash your app. However, there is an issue (still present in 1.70.0) which causes your app to crash if you call `Recenter()` while the GVR SDK is not active, see #667 to follow along.

> I am only missing the recentering when enabling VR, before I would do : GvrViewer.Recenter();
> but GvrViewer, doesn't exist anymore :(

Also see #667, which shows how to use `GvrCardboardHelpers.Recenter()`.

**Comment by fredsa** [comment]
Closing as the original issue ("_GvrViewer.Instance.VRModeEnabled = false Does not work_") appears to be resolved.
