### ISSUE TITLE
[Unity5.6.1][iOS] Stereo Cameras replaced issue

### ISSUE THREAD

**Issue by mirrorboy714** [googlevr/gvr-unity-sdk#567]
![c_ko9etuqaago9l](https://cloud.githubusercontent.com/assets/2707800/25966347/b668cf68-36c5-11e7-8c9c-b1762485c85f.jpg)
I'm using latest version of unity 5.6.1f. I made simple scene and built cardboard app for iOS using Unity.

I think cameras is replaced.

**Comment by hedbergj** [comment]
I think this is a Unity Issue, not GVRSDK

[https://forum.unity3d.com/threads/5-6-0p3-gvr-1-40-ios10-3-1-iphone5.468716/](https://forum.unity3d.com/threads/5-6-0p3-gvr-1-40-ios10-3-1-iphone5.468716/)

and on the [issue tracker](https://issuetracker.unity3d.com/issues/ios-cardboard-left-and-right-camera-view-is-offset-too-far-away-from-one-another-in-cardboard-mode-on-iphone-5-slash-ipod-6th-gen)

**Comment by mirrorboy714** [comment]
OK I understand.

Thanks.
