### ISSUE TITLE
How can I make Canvas for each eye in Android?

### ISSUE THREAD

**Issue by havergooday** [googlevr/gvr-unity-sdk#570]
I want make stereo canvas for each eye..
like left eye canvas, right eye canvas

I follow this link
https://github.com/googlevr/gvr-unity-sdk/issues/263
but it can be only unity_editor

maybe "UpdateStereoValues()" can't build in android..

**Comment by miraleung** [comment]
In Unity 5.6, you can target a specific eye per camera, and use layer masks to tweak the content visible for each eye.

**Comment by biezhihua** [comment]
@miraleung 
In Unity 5.6 and Gvr1.5.0 , I don't found eye per camera, and not use layer masks to tweak the content visible for each eye yet.

Can you tell me details? 

Thanks！

**Comment by miraleung** [comment]
<img width="271" alt="screen shot 2017-05-17 at 09 31 13" src="https://cloud.githubusercontent.com/assets/5384433/26165113/a08d5692-3ae3-11e7-883c-9c9e96f4b60f.png">

There should be a "Target Eye" box in the Camera component.

**Comment by Selzier** [comment]
If you don't want to use multiple cameras, we've developed a shader that allows rendering content to the left or right eye: https://www.assetstore.unity3d.com/en/#!/content/88499

**Comment by nathanmartz** [comment]
Yes. Either use TargetEye (easier) or a shader (faster).

**Comment by namputo** [comment]
How does one accomplish this on later versions of google-vr-sdk ?

**Comment by rusmaxham** [comment]
The Camera Target Eye solution should still work for current versions of the GVR SDK and Unity.

**Comment by namputo** [comment]
@rusmaxham Yes! Thank you :). I had been using Unity 5.6 for a long time and did not upgrade to later versions of the GVR SDK. As components like GVRHead got deprecated, i was a bit worried. Target eye solution works.
