### ISSUE TITLE
Camera Left and Camera Right not full screen

### ISSUE THREAD

**Issue by YoungBill** [googlevr/gvr-unity-sdk#571]
When I installed, it will pop up the authorization interface(For example, I allow READ_EXTERNAL_STORAGE permission), I agree to go after the authorization, two camera views become smaller, after the operation always smaller views. When the installation, I do not agree with those permissions, after running the view is not small, is full view

**Comment by miraleung** [comment]
Could you please post a video or screenshot with the issue?

**Comment by YoungBill** [comment]
![img_5022](https://cloud.githubusercontent.com/assets/9884053/26489644/c5be215e-423a-11e7-9a95-52c2c874b384.JPG)
That's it

**Comment by YoungBill** [comment]
@miraleung

**Comment by nathanmartz** [comment]
This is the expected behavior depending on the size of your phone and the viewer that is being used. There's no point rendering pixels that someone can't actually see in the viewer.
