### ISSUE TITLE
Video tearing on adreno 330

### ISSUE THREAD

**Issue by MrSilverstone** [googlevr/gvr-unity-sdk#572]
I have a problem while using the GvrVideoPlayerTexture on adreno 330 devices (tested on galaxy s5, xiaomi note, LG stylus 3, and many others). I seems that the decoding fail on this gpu.

![screenshot_2017-05-15-17-38-53](https://cloud.githubusercontent.com/assets/7988808/26049418/e726d8ac-3995-11e7-8e11-01e0fddeb7da.png)

**Comment by rusmaxham** [comment]
This is a known issue with the GvrVideoPlayerTexture on older chipsets that we are working on resolving, likely to be in the 1.60 release.

**Comment by rusmaxham** [comment]
The fix for this went out in the 1.60 release.
