### ISSUE TITLE
How to adapt to VR glasses since GVR SDK 1.0.0

### ISSUE THREAD

**Issue by zhangyulong882** [googlevr/gvr-unity-sdk#574]
It seems that the GvrProfile is useless since GVR SDK 1.0.0 . If the unity has native GoogleVR support, how can i set the screenSize、fov、distortion parameter to adapt to different VR glasses.

**Comment by miraleung** [comment]
This is taken care of by Google VR Services when you pair the phone to a Daydream View, or to a Cardboard viewer. There is no need to set those parameters manually.

**Comment by zhangyulong882** [comment]
if we can't access Google VR Service, is there any way to set the gvr profile?

**Comment by miraleung** [comment]
For Cardboard, tapping on the gear icon will yield an option to pair the phone to to a Cardboard viewer by scanning a QR code, which will also set the profile. For Daydream phones, simply placing the headset in a Daydream view will do the trick.
