### ISSUE TITLE
Wrong image in several devices: Huawei P7, BQ Aquaris E5 and Doogee X5 3G Galicia

### ISSUE THREAD

**Issue by chelder86** [googlevr/gvr-unity-sdk#578]
I'm using Google Cardboard for Unity v1.10. They all seem to have the same problem:

VIdeo of Huawei P7: https://youtu.be/6PyD7qC71lA

Screenshot of bq aquaris e5:
![bq aquaris e5](https://cloud.githubusercontent.com/assets/3020189/26216886/f91ef8ec-3c05-11e7-905f-b72dcf7db7da.jpeg)

Photo of doogee x5 3g galicia
![doogee x5 3g galicia](https://cloud.githubusercontent.com/assets/3020189/26216887/f91f8262-3c05-11e7-9d2b-798c76551fd7.jpeg)

**Comment by chaosemer** [comment]
Thanks for the bug report! Could you provide a sample project that we can investigate?

**Comment by chelder86** [comment]
Actually we have been doing more tests with the smartphone we have here: Doogee X5 3G Galicia

We have downloaded the latest Unity3D beta, install the Google Cardboard drivers, and compile the demo scene. The image is not broken, but it does not move: it shows a frozen image. You can see a video here: https://youtu.be/3AQF1mLcgNI

Frozen image also with the official [Google Cardboard App](https://play.google.com/store/apps/details?id=com.google.samples.apps.cardboarddemo).

We have tried an app built with a different driver, Durovis Dive: [Dive City Coaster](https://play.google.com/store/apps/details?id=com.divegames.divecitycoaster
). A warning message appears and say: NO GYRO!

Screenshot of the Google Cardboard demo on Doogee X5 3G Galicia (frozen image):
![Screenshot of the Google Cardboard demo on Doogee X5 3G Galicia -frozen image-](http://imgur.com/c0FoTcH)

Screenshot of the warning message of Dive City Coaster on Doogee X5 3G Galicia:
![Screenshot of the warning message of Dive City Coaster on Doogee X5 3G Galicia](http://imgur.com/g5khO4p)

Screenshot of the Google Cardboard demo on Samsung S4 (it works perfectly):
![Screenshot of the Google Cardboard demo on Samsung S4 -it works perfectly-](http://imgur.com/bOQMB5v)

**Comment by nathanmartz** [comment]
I'm pretty sure these phones do not have hardware gyros. They may claim to have a "software gyro" but that's not sufficient for the GVR SDK.

**Comment by chelder86** [comment]
Is there anyway to check if those smartphones have a real gyroscope or a fake - software gyroscope?

It what you are saying is true, it is a clear scam from big companies like Huawei, Doogee or BQ!
