### ISSUE TITLE
Having issues Unity5.6.1 , Gvr 1.5 and iPhone 6+

### ISSUE THREAD

**Issue by Jamenloh** [googlevr/gvr-unity-sdk#579]
Hi guys, 

I was trying to get VrMode supported on iOS and the aspect ratio that comes out of it is halfed and shifted to one side. I just imported imported the GVR package and don't know whats happening, is there a way to solve this ? 

![img_4009](https://cloud.githubusercontent.com/assets/8200464/26282253/19e74714-3e40-11e7-9271-ac9ec7b96e05.PNG)

**Comment by antoniohof** [comment]
I'm getting this too!
On Ipad Pro and Iphone 6
![img_20170522_140553261](https://cloud.githubusercontent.com/assets/8311230/26320167/3952f5d6-3ef8-11e7-9cfe-971bf645e575.jpg)

**Comment by guneyozsan** [comment]
A similar issue was mentioned here before for some WQHD (2560x1440) Androids set to 1920x1080 resolution. The problem was resolving by setting the device to WQHD resolution. Maybe it helps.

**Comment by rusmaxham** [comment]
This is a known issue in Unity 5.6.1 on iOS that does not occur in Unity 5.6.0f3 (or p3).  Unity is aware of the issue and will be releasing a fix in the neat future.

**Comment by Jamenloh** [comment]
@antoniohof @dubois @rusmaxham @guneyozsan Thanks for your inputs. 

I've followed @rusmaxham's suggestion and tried out 5.6.0f and it worked beautifully. 

Thank you! 

![whatsapp image 2017-05-24 at 5 27 08 pm](https://cloud.githubusercontent.com/assets/8200464/26397086/b86c0c6c-40a7-11e7-8ade-f7819e0c78c0.jpeg)
