### ISSUE TITLE
Disable trackRotation in gvr version 1.5.0

### ISSUE THREAD

**Issue by suvajit79** [googlevr/gvr-unity-sdk#580]
Earlier we could disable trackRotation using "GvrHead.trackRotation = false". Since GVRHead is missing in new version(1.5.0), is there any workaround for this ?

**Comment by synthercat** [comment]
It seems that Unity take more control now. Also there isn't any function there to disable rotation, just position. https://docs.unity3d.com/ScriptReference/VR.InputTracking.html

I guess you could always read the rotation and counter-rotate an empty that holds the camera. This should have the same effect (but yes, I don't like the sound of that either!)

**Comment by nathanmartz** [comment]
Yes, in VR disabling head tracking just leads to sick users. If you are trying to do magic window/monocular 360 I suggest you just use the gyro to drive the camera and don't rely on any VR features.
