### ISSUE TITLE
Video also plays in Cardboard

### ISSUE THREAD

**Issue by synthercat** [googlevr/gvr-unity-sdk#583]
As seen here:https://developers.google.com/vr/video/video-overview
The video thing is supposed to exist only in Daydream... It seems to work fine in cardboard as well. Is there any reason for that warning label?

**Comment by rusmaxham** [comment]
The video plugin has been developed and tested primarily for Daydream and Daydream-ready devices, and as such is what we offer full support for.  However, it does work in Cardboard on some Android devices, but has issues on others.  Also, there is no support for iOS.  These issues may or may not be resolved in a future update, so beware of trying to use it in a Cardboard app.
