### ISSUE TITLE
SystemInfo.graphicsDeviceID returns 0 on newest Macbook pro

### ISSUE THREAD

**Issue by Marchelune** [googlevr/gvr-unity-sdk#585]
Hi there, 

In the **ControllerProviderFactory**, there is a check for the **SystemInfo.graphicsDeviceID**. 
However on my newest Macbook pro (2016, with a Radeon Pro 455) this returns **0**.
This prevents from using the emulator controller in the editor. 

I didn't have the opportunity to test on an other Macbook pro, but I think it is worth mentionning for whoever is having trouble when debugging Daydream apps in the editor.

**Comment by chaosemer** [comment]
Thanks for the bug report, we will investigate!

**Comment by miraleung** [comment]
Could you please specify which version of Unity you're using? The controller is supported only in Unity 5.6 and up.

**Comment by Marchelune** [comment]
Right, sorry, Unity 5.6.1f1

**Comment by Marchelune** [comment]
For those running in the same issue, it should be solved in 1.60 : https://developers.google.com/vr/unity/release-notes#fixes
