### ISSUE TITLE
Unity_5.6 + GVR_1.5 : How to switch between VR and non-VR mode?

### ISSUE THREAD

**Issue by tejpratap0** [googlevr/gvr-unity-sdk#586]
Hi, 

In previous version of gvr sdk, I was able to open screen in bot VR and Non-VR mode using VRModeEnabled in GvrViewer class. But in current version 1.50 there is no class named GvrViewer.

Any help would be appreciated.

**Comment by vinhui** [comment]
Nowadays you do it through unity: https://docs.unity3d.com/ScriptReference/VR.VRSettings-enabled.html

**Comment by nomadcandy** [comment]
This was buggy and could not be turned off of VR mode for google cardboard when I tried 3 weeks ago. Is it fixed now?

**Comment by vinhui** [comment]
I have used it with Gvr 1.40 on unity 5.6, be sure to add the extra framed of delay.

**Comment by nomadcandy** [comment]
I am downloading the new build and just saw where to toggle pano and stereo on the texture in Unity. Hoping that cures what ails my build. I built both my apps native after pulling my hair out but need to get this done in Unity for my next project.
#PrayNoMoreDefects Best-
Jami BeckerInnovation Directornektr, augmented+virtualjami@nektr.io1.415.225.8673www.nektr.io









 

    On Tuesday, May 23, 2017 11:44 AM, Vincent Huisman <notifications@github.com> wrote:
 

 I have used it with Gvr 1.40 on unity 5.6, be sure to add the extra framed of delay.—

**Comment by yaweizhu** [comment]
i just see this，https://docs.unity3d.com/ScriptReference/VR.VRSettings.LoadDeviceByName.html，but there have a problem ,there will be delays.who can solve the problem.

**Comment by fredsa** [comment]
Switching between VR and non-VR is documented here:
https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime

**Comment by Rahulxx01** [comment]
I followed everything how to switch from VR to non VR and it worked but when I want to change from one VR scene to another the second VR scene becomes non-VR  I really dont understand why its like that..????

I deployed the Game in my Android device.

**Comment by fredsa** [comment]
@Rahulxx01 If your second scene tries to load an already loaded VR device name, you might find that your app exits VR:

You can use a `String.Compare` in your code that switches to VR as shown in the sample code in https://docs.unity3d.com/ScriptReference/XR.XRSettings.LoadDeviceByName.html
```
    IEnumerator LoadDevice(string newDevice)
    {
        if (String.Compare(XRSettings.loadedDeviceName, newDevice, true) != 0)
        {
            XRSettings.LoadDeviceByName(newDevice);
            yield return null;
            XRSettings.enabled = true;
        }
    }
```

**Comment by mari-yam** [comment]
@Rahulxx01 how did you solve this??

**Comment by mari-yam** [comment]
Oh thanks it works now
One thing more how did I return back to VR mode to non-VR mode ?

**Comment by fredsa** [comment]
To go back to 2D from VR mode, see `SwitchTo2D()` here:
https://developers.google.com/vr/develop/unity/guides/hybrid-apps

**Comment by Fauzi-code** [comment]
> Switching between VR and non-VR is documented here:
> https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime

hii
I have a project that makes a VR temple, I found a problem on the button play that happens the bug is VR mode can not load VR scene. this is my code.

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.VR;

public class VRToggle : MonoBehaviour
{
    
    public void VRMode()
    {
        ToggleVR();
        SceneManager.LoadScene("VRCandi");
    }

    void ToggleVR()
    {

        if (VRSettings.loadedDeviceName == "cardboard")
        {
            StartCoroutine(LoadDevice("None"));
        }
        else
        {
            StartCoroutine(LoadDevice("cardboard"));
        }
    }

    IEnumerator LoadDevice(string newDevice)
    {
        VRSettings.LoadDeviceByName(newDevice);
        yield return null;
        VRSettings.enabled = true;
    }
}

can anyone help me??
