### ISSUE TITLE
How to detect back button press in vr view

### ISSUE THREAD

**Issue by kfy0** [googlevr/gvr-unity-sdk#590]
I try to use 
GvrViewer.BackButtonPressed
Input.GetKeyDown (KeyCode.Escape)
to detect back button press

But those two not work

**Comment by shakhruz** [comment]
Hi,
I'm using a simple script to track back button and send  a playmaker event:

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using HutongGames.PlayMaker;

public class GVRBackButtonTracker : MonoBehaviour {

	public PlayMakerFSM fsm;
	public string eventName = "BackButton";

	private GvrViewer viewer;

	void Awake () {
		viewer = gameObject.GetComponent<GvrViewer> ();
	}
	
	void Update () {
		if (viewer.BackButtonPressed) {
			if (fsm!=null) fsm.SendEvent (eventName);
			else PlayMakerFSM.BroadcastEvent (eventName);
		}
	}
}


Works for me.
I also DON'T use native Unity cardboard code, instead I use the SDK from Google and disable 'Virtual Reality Supported'

**Comment by tertle** [comment]
That only works up to v1.2. For v1.3 onwards I can't seem to find anyway to bind back button.

**Comment by kfy0** [comment]
Hi shakhruz,

Does you use SDK provide's Prefabs GvrViewerMain?

**Comment by nathanmartz** [comment]
In the native integrations, both the X and the back button should come
through as the Esc key being pressed. There is a bug in Unity 5.6.1 where
this doesn't happen properly, but it's in the process of being fixed.
