### ISSUE TITLE
No longer to set Distortion Correction to None (Unity 5.6 & GoogleVR SDK 1.5)

### ISSUE THREAD

**Issue by jgnoel86** [googlevr/gvr-unity-sdk#591]
Specifically on iOS using Unity Cardboard it was very ideal to be able to set Distortion Correction to none and use the undistort shader method. Using Unity 5.6.0p1 and GoogleVR sdk 1.5 I can't find any way so far to turn off the distortion correction.

**Comment by nathanmartz** [comment]
Yes, this was a feature that we had to disable on our way to the native integration. However, it's something that we recognize is very useful for Cardboard developers and we're looking into ways to bring it back.

**Comment by fredsa** [comment]
Use the gear icon in the top right corner to access VR Settings, tap 7x on the build version to enable developer options, then select **Developer options > Force undistorted rendering**.
