### ISSUE TITLE
the issues of carboard on ios

### ISSUE THREAD

**Issue by xiesi88** [googlevr/gvr-unity-sdk#593]
Currently ios cardboard still has the following issues:

I'm using Unity2017.1.0b7 with GVR1.50.

1.When build to iphone, the VR view is distorted.

2.When "Enable Transition View" is set to false, it should not show an instruction splash screen. But Splash Screen appears even if enable tansition view is set to false.

3.Camera rendering has problems on ios carboard in vr mode when using2x and 4x or 8x MSAA.When released to the iphone, the screen is displayed as black and flashing.When I disable Anti Aliasing the rendering becomes normal.

**Comment by ryandobby** [comment]
I am having the same issues, I had to revert back to Unity 5.6.0f3 in order to even build to my iOS device without the odd distortion.

**Comment by AdrianaVecc** [comment]
Reporting issue 1 after migrating to **Unity 5.6.1f1 + GoogleVR SDK 1.4**

Please find screenshots of distorted VR stereoscopic view (on iPhone) vs. correct stereoscopic view (on Android):

iOS:
![img_5552](https://user-images.githubusercontent.com/6166964/26866295-1d8c184e-4b93-11e7-8a9e-343edd213644.PNG)

Android:
![screenshot_20170320-161332](https://user-images.githubusercontent.com/6166964/26866325-3af8d82c-4b93-11e7-82e5-34b3460b669e.png)

Thanks for your help

**Comment by AdrianaVecc** [comment]
Hey! The first issue is solved by upgrading to 5.6.1p2 https://unity3d.com/fr/unity/qa/patch-releases/5.6.1p2

**Comment by jvergara92** [comment]
I've run into an issue where GVR spatial audio works on the editor and Android but not iOS. I'm ending up with a silent game. Anyone else have any ideas why this may be? (5.6.1p3)

**Comment by fredsa** [comment]
@jvergara92 Thanks for filing issue #618 for your unrelated audio issue.

**Comment by fredsa** [comment]
> 1. When build to iphone, the VR view is distorted

> Hey! The first issue is solved by upgrading to 5.6.1p2 …

Closing as the main issue reported here is fixed according to @AdrianaVecc at least three others who gave their thumbs up.

**Comment by fredsa** [comment]
> 2.When "Enable Transition View" is set to false, it should not show an instruction splash screen. But Splash Screen appears even if enable tansition view is set to false.

> 3.Camera rendering has problems on ios carboard in vr mode when using2x and 4x or 8x MSAA.When released to the iphone, the screen is displayed as black and flashing.When I disable Anti Aliasing the rendering becomes normal.

@xiesi88 Would you mind filing separate bugs for these two issues, so it's easier to track them individually?
