### ISSUE TITLE
Keyboard demo crashes immediately

### ISSUE THREAD

**Issue by rpgia** [googlevr/gvr-unity-sdk#594]
The other Gvr demos work fine, but the keyboard demo crashes. Also, when I delete the keyboard-relevant objects/scripts from the keyboard scene, it then works fine.

On my Pixel phone I have the Daydream Keyboard app updated and on v1.6. In the log it says that the GVR Keyboard 1.40 is used, but I'm guessing that is referring to the Keyboard API and not the app. But the two versions are close enough that I wanted to check whether they should match!

Here is the logcat: https://pastebin.com/KD6DzAd1

Also, I'm building with 5.6.1p1, and on OSX 10.11.6 if it matters at all.

Thanks!

**Comment by nathanmartz** [comment]
This should be fixed in 1.6.1 of the keyboard app.
