### ISSUE TITLE
WebCamTexture is not working at Unity 5.6.1f and google VR sdk for Unity 1.50

### ISSUE THREAD

**Issue by JungJinuk** [googlevr/gvr-unity-sdk#596]
hello, first I am sorry for poor english.

I tried "Camera through VR mode" like AR by using WebCamTexture.

hierarchy is very simple. main camera and Quad. and Quad is main camera's child.

Quad have Cam script which plays WebCamTexture and changes Quad's main texture at Start( ).

This is working when using Unity5.4.1f and gvrViewerMain prefab when It built.

however, This is not working when using Unity5.6.1f and gvrEditorEmulator prefab.

both are working at Unity editor game scene. but when I build the app, the second case, Quad looks black.

how can I solve this problem?

**Comment by nathanmartz** [comment]
I'm sorry but this is not a VR specific question, so you'd have better luck posting on the Unity forums.
