### ISSUE TITLE
Fatal Exception with runtime permissions on cardboard application

### ISSUE THREAD

**Issue by bplaster** [googlevr/gvr-unity-sdk#599]
When attempting to request runtime permissions on daydream-based device, permissions work successfully, however, when attempting to request runtime permissions on cardboard-based device (non-daydream-based) with the same code, application crashes with following error:
```
FATAL EXCEPTION: main
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.vr.ndk.base.DaydreamApi.launchInVr(android.content.Intent)' on a null object reference
   at com.google.gvr.permissionsupport.PermissionsFragment$1.run(PermissionsFragment.java:141)
   at android.os.Handler.handleCallback(Handler.java:836)
   at android.os.Handler.dispatchMessage(Handler.java:103)
   at android.os.Looper.loop(Looper.java:203)
   at android.app.ActivityThread.main(ActivityThread.java:6355)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

Presumably this is happening because it is attempting to use the "DaydreamApi" when it is not available. Should there be support for runtime permissions on cardboard-based devices, or is this not planned?

**Comment by bopangzz** [comment]
I think you are correct. The runtime permission code you are using is for Daydream specific, which use the Daydream specific api to transit to a 2D activity so it doesn't work on cardboard-only devices.

Are you trying have you app support both cardboard and daydream at the same time?

**Comment by bplaster** [comment]
The application can be built for either cardboard or daydream, but not at the same time. The main difficult I'm having is supporting runtime permissions with cardboard, since one of the phones I'm supporting runs Android 7.1 with cardboard. I realize I could just write my own Java handler for runtime permissions, but I was hoping that GVR supported runtime permissions for both cardboard and daydream so that I have a consistent design.

**Comment by bopangzz** [comment]
As far as I know, we don't have any plan to have permission api to support Cardboard but I will bring up with the team. 

Also if you are building separately, why not just target Android 22 for your cardboard build?

**Comment by bplaster** [comment]
Thanks! Yeah, currently I'm just using the manifest to force permissions
checking on startup rather than runtime, which works fine. It's not ideal
though because the user is presented with a 2d screen while in the headset,
which breaks the ideal user flow and forces them to leave the headset.
(Ideally it would be similar to how Gear VR does it where it presents the
permissions request in VR, so the user doesn't need to exit the headset.)
