### ISSUE TITLE
Laser pointer direction is inaccurate.

### ISSUE THREAD

**Issue by dalanchoo** [googlevr/gvr-unity-sdk#604]
Hi. I have noticed a bug with the accuracy of GoogleControllerPointer. You can see in the attached video that the laser pointer will sometimes go right through a selected object. I have edited the color of the laser to a bright red so you can more easily see the issue, but there are not code changes. This is version 1.50.

You can see that when the laser does not intersect with an object, the direction that the laser comes out of the controller will suddenly jump by a few degrees. The end of the laser is in empty space, and the laser passes right through the object that I'm trying to select. This is highly confusing.

Please let me know if you have any questions.
Thank You
John Lawrie
[Laser Pointer Bug.zip](https://github.com/googlevr/gvr-unity-sdk/files/1056738/Laser.Pointer.Bug.zip)

**Comment by guneyozsan** [comment]
The stereo focus of the laser changes according to the location of the object it collides. In your case it is the planet and infinity. You can try putting an invisible collider very close to (or in the same plane with) the planet.

**Comment by dsternfeld7** [comment]
I believe this is related to the RaycastMode set on the GvrPointerPhysicsRaycaster you are using.

public enum RaycastMode {
    /// Default method for casting ray.
    /// Casts a ray from the camera through the target of the pointer.
    /// This is ideal for reticles that are always rendered on top.
    /// The object that is selected will always be the object that appears
    /// underneath the reticle from the perspective of the camera.
    /// This also prevents the reticle from appearing to "jump" when it starts/stops hitting an object.
    ///
    /// Note: This will prevent the user from pointing around an object to hit something that is out of sight.
    /// This isn't a problem in a typical use case.
    Camera,
    /// Cast a ray directly from the pointer origin.
    /// This is ideal for full-length laser pointers.
    Direct
  }

It looks like you extended the laser to be as long as the reticle, in which case it is recommended to use the Direct raycast mode.

In Camera raycast mode this can happen if you have a long laser and are pointing at something that is close to you because the laser will be intersecting the planet but the reticle will not from the perspective of the camera.

**Comment by dalanchoo** [comment]
Changing this option did fix my problem and the laser seems to work nicely.

Thank you for the quick response.
John Lawrie.
