### ISSUE TITLE
Odd iOS Cardboard distortion with GoogleVR SDK 1.4 and 1.5

### ISSUE THREAD

**Issue by AdrianaVecc** [googlevr/gvr-unity-sdk#605]
Issue occurred after migrating from GoogleVR SDK 1.1 to **Unity 5.6.1f1 + GoogleVR SDK 1.4**

Please find screenshots of distorted VR stereoscopic view (on iPhone) vs. correct stereoscopic view (on Android):

iOS:
![img_5552](https://user-images.githubusercontent.com/6166964/26866295-1d8c184e-4b93-11e7-8a9e-343edd213644.PNG)

Android:
![screenshot_20170320-161332](https://user-images.githubusercontent.com/6166964/26866325-3af8d82c-4b93-11e7-82e5-34b3460b669e.png)

Thanks for your help

**Comment by AdrianaVecc** [comment]
I reproduced this issue with the **GVRDemo Scene** with **GoogleVR SDK for Unity 1.50** and **Xcode 8.2**.

See below the excessive distortion:

![img_5553](https://user-images.githubusercontent.com/6166964/26873155-6ebf91ec-4bab-11e7-9ce3-37caf0aecfd0.PNG)

**Comment by joejo-unity** [comment]
This should be fixed in Unity release 5.6.1p2.

**Comment by AdrianaVecc** [comment]
Thank you, @joejo-unity! Any ETA when we should expect 5.6.1p2?

**Comment by joejo-unity** [comment]
P2 is available right now.

**Comment by AdrianaVecc** [comment]
Confirming that the problem was solved! Thank you @joejo-unity :)
