### ISSUE TITLE
ios linker failed exit code 1 fails on iOS -lGTMSessionFetcher

### ISSUE THREAD

**Issue by violetforest** [googlevr/gvr-unity-sdk#607]
this took me forever to find. leaving it here for all the other devs pulling their hair out.

**(running GVR v1.60 and Unity 5.6.1f1)**

![screen shot 2017-06-07 at 11 11 09 pm](https://user-images.githubusercontent.com/8921838/26912091-bfd747ba-4bd7-11e7-9439-91315a8b915b.png)

**source**: https://xenforo.unity3d.com/threads/google-vr-builds-fail-on-ios-lgtmsessionfetcher.469314/

**Comment by miraleung** [comment]
Thanks, we'll add it to our release notes and update our docs.

**Comment by rusmaxham** [comment]
Our documentation has been updated.

**Comment by fredsa** [comment]
Updated doc here:
https://developers.google.com/vr/unity/get-started-ios

Duplicate of #539.
