### ISSUE TITLE
Unity: Switching VR Mode doesn't switch mode, returns only a grey screen

### ISSUE THREAD

**Issue by ipeerbhai** [googlevr/gvr-unity-sdk#608]
I have two scenes.  I can start and run either scene indivudually.  One scene is a nonVR scene, the other scene is a VR scene.

NonVR Scene is a single button, with a single click handler.  Here's the code:
public class DataSceneMgr : MonoBehaviour {
    public Button SubmitButton;
	// Use this for initialization
	void Start () {
        VRSettings.enabled = false; // this is a normal scene.
        Button btn = SubmitButton.GetComponent<Button>();
        btn.onClick.AddListener(SubmitClickHandler);
	}
    void SubmitClickHandler() {
        UnityEngine.SceneManagement.SceneManager.LoadScene("VRWorld");
    }

Here's the code from the I'm using to switch modes.  It's attached to the Player GameObject, which has the camera as a child. 
...    
void Start() {
        VRSettings.enabled = true; // this is a VR scene.
        PlayerPrefs.SetInt("Vr Mode", 1);
...

What am I doing wrong?
Unity 5.6.0f3
GoogleVR SDK 1.60

**Comment by vinhui** [comment]
you might have to load the `None` vr sdk, see #492 for examples

**Comment by fredsa** [comment]
For future reference, here's the code for switching between VR and non-VR modes:
https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime
