### ISSUE TITLE
Black patches rendering skybox when VR mode is enabled

### ISSUE THREAD

**Issue by iHaris93** [googlevr/gvr-unity-sdk#609]
Hi, I am using Unity 5.6.0f3 on a Windows 10 64-bit PC System. I am working on [this VR Game](https://play.google.com/store/apps/details?id=com.shooterboy.serenitybeachvr), Google Cardboard VR SDK version 0.80.0 because of the GvrMain and it's compatibility with an Asset that I am using in this game.

The problem that I am facing is very odd. Everything works fine, except on "some" devices (reportedly Samsung Note 3, and HTC Butterfly 2) there are black random patches on skybox which are dynamic and keep changing positions, and the FPS drops significantly in such cases. Also, the camera keeps spinning and gets out of control. It is a total mess.
![iss1](https://user-images.githubusercontent.com/17296557/27010241-37609226-4eb9-11e7-9b01-4686c6231238.jpg)

Please help me resolve this issue, the complaints seem to be increasing each passing day with the increase in users.

**Comment by vinhui** [comment]
Does the logcat say anything interesting?

**Comment by iHaris93** [comment]
@vinhui no, the build logcat is just fine!

**Comment by vinhui** [comment]
Do you mean the Unity build log or the Android logcat when running your app?

**Comment by iHaris93** [comment]
Both shows no abnormality!

**Comment by nathanmartz** [comment]
Looks like a clipping or z-culling issue. Try using a 32 bit depth buffer (in the VR settings).

**Comment by rusmaxham** [comment]
If you are still experiencing this issue, feel free to reopen with more details.
