### ISSUE TITLE
Problem with gvr-unity-sdk-master 

### ISSUE THREAD

**Issue by DKVR** [googlevr/gvr-unity-sdk#611]
I just downloaded that gvr-unity-sdk-master zip file. When I got started this project file, something wrong happened it was compiler errors...... I didn't do anything only downloaded and then get started that file.......

How should I do????
what is the problem with that file???

**Comment by martinbilello** [comment]
Hi, can you paste here the error you are seeing? That would help us figure out what the problem is.

Thanks

**Comment by DKVR** [comment]
Compiler errors happened when I just import that project file

**Comment by fredsa** [comment]
Please try importing `GoogleVRForUnity.unitypackage` into your project instead of downloading the github master branch zip file.

Download that Unity package from:
https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVRForUnity.unitypackage

**Comment by DKVR** [comment]
Thanks for your email
but the link you sent me was not I was looking for.....
I need "gvr-unity-sdk-master" file which includes "sample" folder >
"DaydreamLabsControllerPlayground"

What problem happened to me was all of the scenes in
"DaydreamLabsControllerPlayground" doesn't work ......

Please help me....

Best regards,
DK


2017-06-23 2:20 GMT+01:00 Fred Sauer <notifications@github.com>:

**Comment by vinhui** [comment]
Youre not giving us much information to work with. Could you post the full errors you are getting?

**Comment by DKVR** [comment]
That was it I said
"DaydreamLabsControllerPlayground" is in gvr-unity-sdk-master not working I
mean some compiler errors happened when I open and play demo scenes in "
DaydreamLabsControllerPlayground".....

Errors are :
Cinema 4D converter plugin installation failed. Please run Unity as an
Administrator to have the plugin installed.
Assets/Scripts/GUI/ControllerInputModule.cs(87,48): error CS0117:
`GvrController' does not contain a definition for `Orientation'
Assets/Scripts/GUI/ControllerInputModule.cs(168,32): error CS0117:
`GvrController' does not contain a definition for `ClickButtonDown'
Assets/Scripts/GUI/ControllerWarning.cs(44,25): error CS0117:
`GvrController' does not contain a definition for `State'
Assets/Scripts/Input/ClickInput.cs(31,27): error CS0117: `GvrController'
does not contain a definition for `ClickButtonUp'
Assets/Scripts/Input/ClickInput.cs(34,27): error CS0117: `GvrController'
does not contain a definition for `ClickButtonDown'
Assets/Scripts/Input/ClickInput.cs(37,27): error CS0117: `GvrController'
does not contain a definition for `ClickButton'
Assets/Scripts/Input/ClickInput.cs(40,27): error CS0117: `GvrController'
does not contain a definition for `TouchUp'
Assets/Scripts/Input/ClickInput.cs(46,27): error CS0117: `GvrController'
does not contain a definition for `IsTouching'
Assets/Scripts/Input/ControllerOrientation.cs(39,49): error CS0117:
`GvrController' does not contain a definition for `Orientation'
Assets/Scripts/Input/ControllerOrientation.cs(41,44): error CS0117:
`GvrController' does not contain a definition for `Orientation'
Assets/Scripts/Input/DirectionalSlashInput.cs(37,36): error CS0117:
`GvrController' does not contain a definition for `Gyro'
Assets/Scripts/Input/DirectionalSlashInput.cs(46,69): error CS0117:
`GvrController' does not contain a definition for `Orientation'
Assets/Scripts/Input/ElbowOrientation.cs(51,49): error CS0117:
`GvrController' does not contain a definition for `Orientation'
Assets/Scripts/Input/ElbowOrientation.cs(53,44): error CS0117:
`GvrController' does not contain a definition for `Orientation'
Assets/Scripts/Input/FlickInput.cs(42,36): error CS0117: `GvrController'
does not contain a definition for `AppButton'
Assets/Scripts/Input/FlickInput.cs(47,27): error CS0117: `GvrController'
does not contain a definition for `Gyro'
Assets/Scripts/Input/FlickInput.cs(48,47): error CS0117: `GvrController'
does not contain a definition for `Orientation'
Assets/Scripts/Input/FlickInput.cs(50,27): error CS0117: `GvrController'
does not contain a definition for `Gyro'
Assets/Scripts/Input/FlickInput.cs(51,48): error CS0117: `GvrController'
does not contain a definition for `Orientation'
Assets/Scripts/Input/MaskedOrientationInput.cs(42,44): error CS0117:
`GvrController' does not contain a definition for `Orientation'
Assets/Scripts/Input/RawAccelerometerInput.cs(27,47): error CS0117:
`GvrController' does not contain a definition for `Accel'
.
.
.
.
.

Best regards,


2017-06-28 12:33 GMT+01:00 Vincent Huisman <notifications@github.com>:

**Comment by vinhui** [comment]
Did you switch to Android in the build settings?

**Comment by rusmaxham** [comment]
If you are still experiencing this issue, feel free to reopen with more details.
