### ISSUE TITLE
GoogleVR/Demos/README.md is outdated

### ISSUE THREAD

**Issue by pozil** [googlevr/gvr-unity-sdk#612]
`GoogleVR/Demos/README.md` should be updated or removed as it only contains reference to demos are no longer present in the SDK:
- Headset Demo Scene
- Controller Demo Scene

**Comment by martinbilello** [comment]
Thanks for letting us know! We will update it.

**Comment by pozil** [comment]
Cheers.
And by the way, I made another doc fix in [PR-610](https://github.com/googlevr/gvr-unity-sdk/pull/610).
