### ISSUE TITLE
GvrAudioSoundfield not playing in GVR 1.60

### ISSUE THREAD

**Issue by pozil** [googlevr/gvr-unity-sdk#614]
I have migrated an old project to GVR 1.60 and I noticed that GvrAudioSoundfield are not playing audio.

While analyzing the issue on my Pixel XL, logcat gives the following error:
> GVRAudioMixer could not be found in Resources. Make sure that the GVR SDKUnity package is imported properly.

Looking at the [code](https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Scripts/Audio/GvrAudioSoundfield.cs#L277) from where this error comes from, I can clearly see what is wrong: the GVRAudioMixer is being loaded from the wrong directory.

Moving `/GoogleVR/Resources/GvrAudioMixer.mixer` to `/Resources/GvrAudioMixer.mixer` fixes the issue as `/Resources` is the default path used by the `Resources.Load(...)` method.

**Comment by anokta** [comment]
Hi,

Thanks for sharing, and I'm glad to hear you already figured out a solution!

Could you share which Unity version are you using? Referencing [the related Unity documentation](https://docs.unity3d.com/ScriptReference/Resources.Load.html), any Resources folder in the project assets folder should be included in the search. FYI, I can't seem to reproduce the issue using Unity 5.6.

**Comment by pozil** [comment]
Now that's interesting, I am also running Unity 5.6.1f1.

I have retested on a brand new project without moving the Mixer and it works fine so I guess that we can close the issue.

I wonder if this could this be related to the fact that my original project was created with Unity  5.4.2f2.
Anyway, I followed the migration procedures (Unity and GVR) and this is the only problem I came across so far.

**Comment by pozil** [comment]
More on this issue: for some reason there seem to be an issue with Unity when it generates and deploys the APK on my Pixel XL.

I noticed that on some rare occasions some resources are missing when running the mobile app. This led to the issue of the missing GVRAudioMixer.
