### ISSUE TITLE
Load FBX file in Android Daydream app with Google VR Unity SDK

### ISSUE THREAD

**Issue by nikhilcheruku12** [googlevr/gvr-unity-sdk#615]
I'm able to use the media app template in the unity SDk to view photos and videos in VR mode. However, I'm not able to render models loaded from fbx file models . Does anyone know how to do this?

**Comment by vinhui** [comment]
Do you want to load fbx files on runtime?

**Comment by nikhilcheruku12** [comment]
Yes I do. I am currently able to load them at runtime using Resources.Load. I put the file on the resources folder. I want to load the fail at runtime from the android device itself . I'm able to get the file path. I was wondering if there was a way to instantiate a game object with that file path.

**Comment by vinhui** [comment]
There is no way to load an fbx on runtime natively in unity, you will have to create a loader yourself. Obj might be an easier filetype to load

**Comment by nikhilcheruku12** [comment]
I have been able to load it using the resources folder at runtime. Just need to retrieve it from the device.

**Comment by vinhui** [comment]
You will have to either load it through assetbundles or make your own importer

**Comment by nikhilcheruku12** [comment]
If I use asset bundles would I have to include the file in the apk. I want the user to be able to load the files from the downloads folder in their device. I'm able to do this with photos and videos. Have no idea why it is not working for fbx files.

**Comment by peterept** [comment]
Hi @nikhilcheruku12 to comment on your FBX question: The difference is when you load from a `resources` folder Unity Editor has already imported the FBX file and converted it into a format it knows how to load (you get to change the default import settings in the inspector for model, rig and animations). But when it gets a FBX at runtime (you download it bypassing the Unity Editor) it has no ability to read a FBX file.

An asset bundle is a way you can export a model from the Unity Editor and then it has everything set for Unity runtime to load (eg: download the bundle from the internet). So every asset you want to load that way you will need to first process in the Unity Editor. Secondly there are some gotchas with asset bundles - the biggest being Unity doesn't guarantee compatability between minor versions of Unity and only forward compatability. So you can't say export a Asset Bundle with Unity 5.6 and load it into a runtime built from 5.3.  

Further asset bundles are platform specific, so you need to export them for ios, android, windows, etc. 

You can look at loading other (simpler formats) such as OBJ, DAE at runtime.

As @vinhui said, this topic is not related to GoogleVR and a good forum discussion.

**Comment by nikhilcheruku12** [comment]
Thank you so much @peterept and @vinhui. I posted the same question on unity forums and stackoverflow but didn't get replies. That's why I posted it here.

**Comment by nikhilcheruku12** [comment]
@peterept do you know if it is possible to store an asset bundle on an Android device and load it?

**Comment by nathanmartz** [comment]
For general questions about Unity, please use their forums. This tracker is just for bugs specific to Daydream/GoogleVR.
