### ISSUE TITLE
Spatial Audio does not work on iOS

### ISSUE THREAD

**Issue by jvergara92** [googlevr/gvr-unity-sdk#618]
GVRAudio works perfectly fine on Android and the editor, but is completely silent on iOS. Is anyone else running into this problem? (5.6.1p2 and 5.6.1p3). I haven't found any warnings or errors on XCode or Unity. I've been exporting to an iPhone 6 running iOS 10.1.1

**Comment by pancymon** [comment]
I've forwarded your message to the right person to handle it. Thanks for the report!

**Comment by miraleung** [comment]
Thanks for the report, this will be fixed in the next release.

**Comment by fredsa** [comment]
This regression was fixed in the 1.70.0 release.
