### ISSUE TITLE
Timer Gaze

### ISSUE THREAD

**Issue by aammfe** [googlevr/gvr-unity-sdk#619]
Hi !
is there any option for Timer Gaze ?
when Reticle is on any Clickable Object , after some time(animation) clickable would click, automatically.
with out any input ?

if there is not option for this.

it would be great to have it on "GvrReticlePointer"  or on "GvrPointerInputModule".

it could be some thing like this.
"bool ClickOnTimeOut"

**Comment by guneyozsan** [comment]
This asset from asset store adds timed click to Google VR's reticle:
[GazeClick for GoogleVR](https://www.assetstore.unity3d.com/en/#!/content/77469)

I should mention I didn't tried it personally.

**Comment by aammfe** [comment]
@guneyozsan  thanx for reply. 
i am looking for official support.

i have take closer look on GVR scripts.

GvrBasePointer should have 
OnPointerEnter,
OnPointerExit,
OnClick ,
OnGaze(float step) range [0-1]

events so it could be custom animate. 

GvrPointerInputModuleImpl functions are private means nothing could be done with it.

**Comment by dsternfeld7** [comment]
We do not officially support this feature. You can implement this yourself in the latest SDK by making a subclass of GvrBasePointer and overriding Triggering and TriggerDown to handle the timer.

Thanks,

Dan
