### ISSUE TITLE
Click with game Pad

### ISSUE THREAD

**Issue by aammfe** [googlevr/gvr-unity-sdk#620]
Hi!
Is there any way to get clicked by Game-pad. button?

1- Pointer is on Clickable Object.
2- Press a button on Gamepad and button clicked.

just like [hardcode](https://play.google.com/store/apps/details?id=com.farlenkov.vrtps&hl=en)

if not then it would be great to have it on "GvrPointerInputModule" where we can describe the name of game-pad button.

**Comment by dsternfeld7** [comment]
By Gamepad button clicked are you referring to the ClickButton on the Daydream Controller?

[Here](https://developers.google.com/vr/unity/reference/class/gvr-controller#class_gvr_controller_1ad8097d03743b363db662db50b0b5165a) is a link to the documentation for the ClickButton.

Also, when using "GvrPointerInputModule" you can implements the IPointerClickHandler on an object to receive an event when the the click button is clicked while pointing at the object.

**Comment by dsternfeld7** [comment]
Closing. If you would like help with this in the future please feel free to open a new issue.
