### ISSUE TITLE
Memory Leak still

### ISSUE THREAD

**Issue by nomadcandy** [googlevr/gvr-unity-sdk#623]
I am using 5.6.1 personal version of Unity and the latest plugin of the GVR SDK. I rebuilt my entire app and whenever I deploy the toggle opening the app in 360 switching to a scene and turning Cardboard VR mode on then swap back to scene with 360 mode my app crashes, I assume this is due to a memory leak on IOS. I am running on my iPhone 6s. Anybody have the answer to this? I am so frustrated as they keep saying this thing is fixed and it keeps happening again. I have my apps built native managing this functionality but it would be great to build this toggle GVR thing out in Unity and have a single code base. SOS. Any geniuses out there?

**Comment by peterept** [comment]
How are you switching between cardboard and 360 ? 

I am doing this and not seeing a crash.

**Comment by peterept** [comment]
Here's how I switch in and out of VR mode:

http://talesfromtherift.com/googlevr-cardboard-switch-between-normal-mode-and-vr-mode-at-run-time/

**Comment by nomadcandy** [comment]
Thank You! I am checking it out. Best-
Jami BeckerInnovation Directornektr, augmented+virtualjami@nektr.io1.415.225.8673www.nektr.io









 

    On Tuesday, June 20, 2017 12:12 AM, peterept <notifications@github.com> wrote:
 

 Here's how I switch in and out of VR mode:http://talesfromtherift.com/googlevr-cardboard-switch-between-normal-mode-and-vr-mode-at-run-time/—

**Comment by fredsa** [comment]
For future reference, additional instructions, in case you ever need to switch between VR and non-VR modes:
https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime
