### ISSUE TITLE
gvr version is "1.20.0" in Unity 5.6 project importing Daydream unity SDK 1.50?

### ISSUE THREAD

**Issue by StevenKeXu** [googlevr/gvr-unity-sdk#624]
hi I setup a new Daydream project by importing unity sdk 1.50. And I export this unity project to Android project to get "gvr.aar".  Decompiling this file , I find the version of gvr is "1.20.0".  Even though importing the latest unity sdk, the base gvr is still 1.20 in unity 5.6? Android sdk or ndk now is 1.60.0, and many problems are resolved by update from 1.20 to 1.60.  So, how could i can use lastest gvr version in Unity? 

thanks.

**Comment by nathanmartz** [comment]
Yes, the version of the GVR SDK bundled with Unity lags behind the main release. However, the Google VR Services (required for Daydream) will automatically hot swap the SDK built into your app w/ the latest so you should see these benefits at runtime.
