### ISSUE TITLE
GvrControllerBatteryLevel always return 'unknown'

### ISSUE THREAD

**Issue by pozil** [googlevr/gvr-unity-sdk#627]
When running the GVRDemo scene or other scenes on a mobile, the Daydream controller battery level indicator always returns "unknown".

This issue was identified earlier here:
https://forum.unity3d.com/threads/daydream-gvrcontroller-batterylevel-always-returns-unknown.468781/

Here is the environment in which I reproduce the issue:
- Unity 5.6.1f1
- GVR SDK 1.60
- Pixel XL

**Comment by dsternfeld7** [comment]
The battery indicator should work if you use Unity 5.6.2f1.

Additionally, in the next release of the GVR SDK the battery indicator will be hidden if the battery state is unavailable instead of showing a question mark.

Thanks,

Dan

**Comment by dsternfeld7** [comment]
I misspoke. This is actually fixed in Unity 5.6.2p1, which can be downloaded here: https://unity3d.com/unity/qa/patch-releases

**Comment by fredsa** [comment]
Fixed in 1.70.0
