### ISSUE TITLE
Odd distortion when VRSettings.enabled = false after leaving VR mode

### ISSUE THREAD

**Issue by AdrianaVecc** [googlevr/gvr-unity-sdk#628]
*Unity 5.6.1p2 + GVR 1.40*

User can switch between monoscopic and stereoscopic views, with this code:

```using UnityEngine;
using UnityEngine.VR;
using System.Collections;

public class CardboardSwapper : MonoBehaviour {

	void Start () {

		VRSettings.enabled = false;
// It should start as a normal scene
	
	}
	
	void Update () {
		this.gameObject.transform.Find("Canvas/CardboardButton").gameObject.SetActive(!VRSettings.enabled);
		if (GvrViewer.Instance.Tilted || GvrViewer.Instance.BackButtonPressed) 
		{
			DisableVR();
		}
	
	}

	public void DisableVR ()
	{
		VRSettings.enabled = false;
	}

	public void EnableVR ()
	{
		VRSettings.enabled = true;
	}
}
```

This is what's on screen on an Android device with the monoscopic view:
![whatsapp image 2017-06-21 at 10 15 43 pm](https://user-images.githubusercontent.com/6166964/27388844-42c87430-56cf-11e7-8ed3-e2d4b0db8889.jpeg)

The planet should be spherical, not shaped like a rugby ball. The problem can also be seen when built on iOS.

For reference, this is what it looks like in the Unity emulator (no distortion):
![screen shot 2017-06-21 at 22 11 35](https://user-images.githubusercontent.com/6166964/27388740-f18605ba-56ce-11e7-8d6f-6b006f330dfd.JPEG)

**Comment by antoniohof** [comment]
I'm getting this too. I found a workaround that's annoying: set to orientation portrait and then back to orientation landscape left, with some time between the change, that fixes the distortion.
But that's sure a bug that needs to be fixed. 

Anyone tested this on Unity 5.6.1p4 already?

**Comment by AdrianaVecc** [comment]
@antoniohof thanks for the workaround though, I am going to experiment with that now. What's s the sweet spot in terms of delay during the change?

**Comment by guneyozsan** [comment]
I also load the device with LoadDeviceByName, newDevice being Cardboard or None and both should be added in VR SDK's at Player Settings.

This is how I managed to switch between modes. I wait for a safety check + 5 frames to make the switch without random crashes or falling into that distorted screen. If you call this at start, LoadDeviceByName should also be delayed at least 1 frame. I also wait for extra 0.5 seconds after start which prevents random crashes.


        VRSettings.LoadDeviceByName(newDevice);

        while (!VRSettings.loadedDeviceName.Equals(newDevice))
        {
            yield return null;
        }

        for (int i = 0; i < 5; i++)
        {
            yield return null;
        }

        VRSettings.enabled = true;

**Comment by AdrianaVecc** [comment]
Confirming that @antoniohof's workaround to set ScreenOrientation to Portrait solves the distortion issue, but I'd rather not use it since the non-VR mode is meant to be in Landscape thus it creates some other UI issues

**Comment by noemis84** [comment]
After disable VRSettings I had the same problem. The image was distorted in single mode. I'm using Unity 5.6.2. You should fix it via this simple line, after you disabled VR:
`Camera.main.ResetAspect ();`
That does the trick for me. If you don't use the main camera tag then just use your camera reference.

**Comment by antoniohof** [comment]
Thanks, that worked!

**Comment by AdrianaVecc** [comment]
Worked for me as well :)

**Comment by fredsa** [comment]
The correct fix here is to indeed call the [Camera.ResetAspect()](https://docs.unity3d.com/ScriptReference/Camera.ResetAspect.html) on all VR capable cameras.
* In a scene with only a main camera, calling `Camera.main.ResetAspect()` after switching to non-VR (2D) mode is sufficient.
* If your scene uses multiple cameras, you can loop through `Camera.allCameras` as illustrated in https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime

**Comment by fredsa** [comment]
Unity automatically adjusts both FOV (`fieldOfView`) and aspect ratio (`aspect`) when entering VR mode, but only restores FOV when exiting VR mode.

Having to call `ResetAspect()` on all VR capable cameras after leaving VR seems like an issue which would be best addressed by having Unity automatically restore the previous cameras' aspect ratios.

If you'd like to see this fixed, you can vote here:
https://issuetracker.unity3d.com/issues/android-vrcardboard-aspect-ratio-not-preserved-when-switching-from-vr-cardboard-to-non-vr-vrsettings-dot-enabled-equals-false

**Comment by jplongo** [comment]
Calling ResetAspect() on my Unity scene don't restore aspect ratio. Is there another trick ?

Unity 2017.1.2p2 GVR SDK 1.100 in iOS devices

**Comment by fredsa** [comment]
This is fixed in:
* Unity 5.6.4p2 and later
* Unity 2017.1.2p3 and later
* Unity 2017.2.0p2 and later

This means that you should no longer have call `ResetAspect()` after switching out of VR.
