### ISSUE TITLE
iPhone-resources.sh: line 7: /resources-to-copy-Unity-iPhone.txt: Permission denied

### ISSUE THREAD

**Issue by nagretshei** [googlevr/gvr-unity-sdk#629]
> Here's another workaround that served me well and seems slightly easier to execute. Note, however, that it bypasses the pods, so it won't do if you absolutely need them.
> 
> Copy the GVROverlayView.h file from Pods/Headers/Public/GVRSDK folder to the top-level Classes folder.
> Open the main .xcodeproj file.
> Delete the libPods-Unity-iPhone.a file from the left pane.
> Under Build Settings, double-click the first line in Other Linker Flags.
> Delete the $(inherited) line.
> screen shot 2017-04-07 at 8 44 47 pm
> 
> Build the project.
> Profit.

I did the one mentioned before, but I got new problem:
/Users/***/Developer/unity/Journey/Journey_iOS/Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone-resources.sh: line 7: /resources-to-copy-Unity-iPhone.txt: Permission denied
Unity is 5.6.2f1, and Gvr is 1.6. Can anyone help?

**Comment by rusmaxham** [comment]
Are you still experiencing this issue?
