### ISSUE TITLE
Black screen when in VR mode. 2D mode is working fine.

### ISSUE THREAD

**Issue by saeidfarivar** [googlevr/gvr-unity-sdk#630]
Hi, A user of our app reported that when they use the QR code in the following document

http://www.brookstone.com/static/on/demandware.static/-/Sites-itemmaster_Brookstone/default/v1498117475993/pdfs/320195p_manual.pdf

http://google.com/cardboard/cfg?p=CgpCcm9va3N0b25lEgpWUiBIRUFEU0VUHSlcDz0llkOLPSoQAADwQgAA8EIAAPBCAADwQlgANef7KT06CI_CdT2PwnU9UABgAA

after they restart the app, the 3D mode is all black, however 2D mode is working just fine.

Seems like this actually happens to all the VR apps and not only our app. the way to fix the issue is to switch back to google's official viewer profile.

http://google.com/cardboard/cfg?p=CgZHb29nbGUSCUNhcmRib2FyZB0J-SA9JQHegj0qEAAAcEIAAHBCAABwQgAAcEJYADUpXA89OghX8as-YrENP1AAYAM

We're using Unity 5.4.2f2 and GoogleVR unity package version 1.30.0.

**Comment by rusmaxham** [comment]
Are you still experiencing this with 5.6 or later and a [recent version of the SDK](https://github.com/googlevr/gvr-unity-sdk/releases)?
