### ISSUE TITLE
GVR audio spatialization with effect-generated sound

### ISSUE THREAD

**Issue by mlantin** [googlevr/gvr-unity-sdk#633]
Hello!

I'm trying to figure out why I can't get generated sounds to be spatialized using the GVR Audio Spatializer. I'd like to know if this is a bug, or if it's not designed to do that, or if I'm not setting it up correctly.

I have an object with a GVR Audio Source which does not have a clip associated with it (though result is the same if I attach a blank clip). The sound I want is generated by an effect that is attached to a mixer (call it grain1). The audio source that the GVRAudioSource creates is routed to grain1. grain1 is routed to the Master of GVRMixer.

If I just leave it like that, no sound comes out at all. If I change the GVRMixer's GVRAudioRenderer effect to be wet, then I have sound. But no spatializing. And it breaks the spatialization on all my other (regular) gvr audio sources.

I should also mention that I have an OnAudioFilterRead function on the sound object. It's an empty function. But it is necessary for the mixer effect to work.

So my question is, is there a way to get an effect-rendered sound to spatialize using GVR Audio?

**Comment by Arakade** [comment]
Hi
I've just run into a similar thing.  I've logged a bug with Unity "Google VR audio stops spatializing with Wet effects (e.g. low-pass filter".

I've not investigated whether it's a Unity or Google caused problem but it needs logging somewhere.  Simply using the Google VR SDK demo scene and enabling wet effects on "GVR Audio Renderer" is enough to break spatialization.

Whoever's it is, I think you're running into that same bug.  I tested on 5.6.2, 2017.01 and 2017.02.  The latter performed worst (it played a blip of sound then crashed when I tried disabling wet!)
HTH

**Comment by anokta** [comment]
Hi,

It is possible to use generated audio via OnAudioFilterRead to spatialize the output through GvrAudioSource. However, the additional mixer effects chain in-between the audio source and the master mixer will be ignored by the GvrAudioMixer, i.e., in that case you would still be hearing the spatialized *dry* input from either the audio clip or the generated audio by OnAudioFilterRead. This is a known issue. For basic use cases, one possible workaround is to use Unity's built-in component based audio effects, e.g., [AudioLowPassFilter](https://docs.unity3d.com/Manual/class-AudioLowPassFilter.html).

Also note that, any effects *after* the GvrAudioRenderer process in the mixer hierarchy will work as expected. For instance, you can still apply attenuation and/or other DSP effects to the whole mix after spatialization.

Hope this is helpful!

**Comment by rusmaxham** [comment]
Also, GVR Audio is now deprecated and will be removed from the GVR SDK for Unity in a future release.  GVR Audio has been replaced by [Resonance Audio](https://developers.google.com/resonance-audio/develop/unity/getting-started).  There is a [migration guide](https://developers.google.com/resonance-audio/develop/unity/getting-started#upgrading_existing_projects_from_google_vr_audio_components) to assist you with the transition.

**Comment by rusmaxham** [comment]
GvrAudio is now deprecated by [Resonance Audio](https://developers.google.com/resonance-audio/develop/unity/getting-started).  If you are still experiencing this issue, feel free to file it with the [Resonance Audio issue tracker](https://github.com/resonance-audio/resonance-audio-unity-sdk/issues).
