### ISSUE TITLE
Video Demo Scene not working on ios

### ISSUE THREAD

**Issue by ioanadc93** [googlevr/gvr-unity-sdk#636]
Hello, does the video demo scene work on ios devices? Cause I tried a variety of combinations between unity and GVR sdk versions and whenever I try to open an OBB video from the demo the background turns blue and that is all. 

This is what I get in Xcode console:
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Not implemented on this platform
GvrVideoPlayerTexture:CreateVideoPlayer()
SwitchVideos:Awake()
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting up 1 worker threads for Enlighten.
  Thread -> id: 16f44b000 -> priority: 1 
-> applicationWillResignActive()
-> applicationDidEnterBackground()
-> applicationWillTerminate()

Please help :)

Thanks!

**Comment by Martin-Pitt** [comment]
I have also been having issues with the Video demo scene on iOS devices.

**Comment by rusmaxham** [comment]
The video plugin is only supported on Daydream devices.  It may work in cardboard on some Android devices, but there is no support for it on iOS at this time.

**Comment by alex-nac** [comment]
Sad...

**Comment by Neogene** [comment]
Unity has developed https://assetstore.unity.com/packages/essentials/tutorial-projects/interactive-360-sample-project-108974 which works with video on iOS.
