### ISSUE TITLE
How to change Mono mode for GvrEditorEmulator? (Not GvrViewerMain)

### ISSUE THREAD

**Issue by naoto-github** [googlevr/gvr-unity-sdk#637]
I wanna change Mono mode in Cardboard Application built for **Android**. 
We could change it by setting "VRModeEnabled=false" in **GvrViewerMain** which is the main script in the old sdk version (1.4.0). 
However, I cannot find the same setting in **GvrEditorEmulator** which is the main script in the new sdk version (1.5.0 and after). 
Could you tell me the solution of the problem?

**Comment by miraleung** [comment]
Could you please take a look at #532? The code is not exactly the same, but something similar in any MonoBehaviour script should work.

**Comment by naoto-github** [comment]
Thanks for your reply, miraleung.
Actually, I already tried it, but it didn't work in the app. built for Android.

**Comment by rusmaxham** [comment]
Switching VR modes at runtime is covered here: https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime

**Comment by naoto-github** [comment]
Than you for your .good news.
I'll check it.
