### ISSUE TITLE
GvrAudioSource Stop() function

### ISSUE THREAD

**Issue by mlantin** [googlevr/gvr-unity-sdk#639]
In the GvrAudioSource script, the Stop() function sets the isPaused variable to false. I believe it should be set to true. Currently, calling this function causes the Update() function to repeatedly call Stop().

 ```
/// Stops playing the clip.
  public void Stop () {
    if (audioSource != null) {
      audioSource.Stop();
      ShutdownSource();
//      isPaused = false;
		isPaused = true;
    }
  }
```

**Comment by anokta** [comment]
Thanks for catching this! While the additional Stop calls shouldn't harm (negligible overhead), you're right, there is no need for it.

Will be updated in the next release.
