### ISSUE TITLE
Unity 5.5+ & GoogleVR sdk v1.30+(cardboard):  stereoscopic view does not work after build on Android device

### ISSUE THREAD

**Issue by xslipstream** [googlevr/gvr-unity-sdk#641]
Did everything I was supposed to: Create scene -> switch to android build -> turn VR Support on and set to Cardboard -> build & run.  Native VR is not working for me at all.

On my phone, I'm unable to:
1) look around in my scene (no stereoscopic view).  My view is "fixed".  I can see that frames are running but I have no control of my view.
2) my view(both eyes) is tilted slightly.  This is not by design as my Camera does not have any rotation applied.  

![screenshot_20170703-021522](https://user-images.githubusercontent.com/23559653/27801383-be3ef06a-5feb-11e7-86cc-4cd74221aa56.jpg)
![screenshot_20170703-021609](https://user-images.githubusercontent.com/23559653/27801384-be41ae9a-5feb-11e7-92a2-57d1d2c3e012.png)

Also tried importing googlevr sdk 1.60 and result is the same.  View is tilted and screen is fixated.

**Comment by xslipstream** [comment]
downgraded to unity 5.5.4f1 and v1.30 googlevr sdk, same problem

**Comment by nathanmartz** [comment]
What phone are you using? Does it have a gyro?
