### ISSUE TITLE
GVREditorEmulator not working in game preview

### ISSUE THREAD

**Issue by shu-toz** [googlevr/gvr-unity-sdk#642]
I can't seem to get the reticle mode to work in the demo scene when I'm trying to preview in Unity.
Am I using it wrong? or is there a setting I've yet to set up?
I'm quite new to Unity and I'm not even sure where to start because there's not much online.

Thanks Guys!

**Comment by dsternfeld7** [comment]
If you are looking at GvrDemo in the latest version of the SDK, here is some information that may help you:

The scene includes both the prefab GvrContrllerPointer (Daydream Controller) and GvrReticlePointer (Cardboard Reticle). The script DemoInputManager is used to automatically switch which one is active based on which Virtual Reality SDK is being used according to Unity's Player Settings: https://docs.unity3d.com/Manual/VROverview.html

Thanks,

Dan

**Comment by dsternfeld7** [comment]
Closing. Please feel free to open a new issue if you would like additional help with this problem.

Thanks,

Dan
