### ISSUE TITLE
How can I overlay icon when VRSettings.enabled?

### ISSUE THREAD

**Issue by guitarrapc** [googlevr/gvr-unity-sdk#643]
- Unity 5.6.2p1 + GVRSDK for Unity 1.6.0, Cardboard SDK.

I used to be using Unity 5.3 with GVRSDK 1.2.0 and successfully overlay my own uGUI Button on the screen when `GvrViewer.Instance.VRModeEnabled = true`. This can be done by just use `Canvas Render Mode as Screen Space - Overlay`.

![image](https://user-images.githubusercontent.com/3856350/27868490-c9b09b36-61d7-11e7-8ac5-4572d18dbc77.png)

However, upgrade Unity and GVRSDK prevent me from overlay any uGUI on the top of Screen like builtin GearIcon. This is because it's Unity Native VR and it does not support `Canvas Render Mode as Screen Space - Overlay`. Refer: https://unity3d.com/learn/tutorials/topics/virtual-reality/user-interfaces-vr

Do you have any idea to render my icon on the same layer of GVRSDK Gear Icon?

Notice: Even Custom icon doesn't show on Screen but Button response as desired.

**Comment by WeaselKing** [comment]
I would like this as well. Using a screen space overlay of a black picture was very useful for fading in and out for scenes. The new way that people seem to be doing it of obscuring the screen with an object doesn't work as well, and feels less professional. I'd just like to display things on the screen arbitrarily.

**Comment by guitarrapc** [comment]
I've found issue only happen with Android, iOS can overlay uGUI with `Canvas Render Mode as Screen Space - Overlay` when using Stereo render is enabled.

**Comment by rusmaxham** [comment]
It is no longer possible to do this with the Cardboard native integration in Unity due to Unity no longer handling the final rendering to screen, rather the GoogleVR subsystem is now responsible for it and does not provide for this functionality.

**Comment by guitarrapc** [comment]
Thank you for the comment. Understand and will be careful about this limitation.

**Comment by dekemega** [comment]
is there any thing new on this topic .. i wanna give user some indicators so what should i do ??

**Comment by fredsa** [comment]
Sorry, this issue is closed. Screen space canvas overlay isn't supported while in VR mode.

**Comment by 78Star** [comment]
This is very on professional, companies like to control their user experiences, and there should be no issue with this as long as it is close/same as what google cardboard does. Plus how do some other apps have exit vr button, are they using another engine besides unity?
