### ISSUE TITLE
Android Google VR OPENGL NATIVE PLUG-IN ERROR

### ISSUE THREAD

**Issue by KyKimGlobepoint** [googlevr/gvr-unity-sdk#645]
07-06 15:47:21.419  9679  9699 I Unity   :
07-06 15:47:21.717  9679  9699 I Unity   : Null GVR context pointer, could not get GVR user prefs' handedness
07-06 15:47:21.717  9679  9699 I Unity   :
07-06 15:47:21.717  9679  9699 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
07-06 15:47:21.717  9679  9699 I Unity   :
07-06 15:47:21.768  9679  9699 I Unity   : Null GVR context pointer, could not get GVR user prefs' handedness
07-06 15:47:21.768  9679  9699 I Unity   :
07-06 15:47:21.768  9679  9699 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
07-06 15:47:21.768  9679  9699 I Unity   :
07-06 15:47:22.003  9679  9699 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
07-06 15:47:22.003  9679  9699 E Unity   :
07-06 15:47:22.003  9679  9699 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 383)
07-06 15:47:22.003  9679  9699 E Unity   :
07-06 15:47:22.055  9679  9699 I Unity   : LoadDevice = cardboard
07-06 15:47:22.055  9679  9699 I Unity   :
07-06 15:47:22.055  9679  9699 I Unity   : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
07-06 15:47:22.055  9679  9699 I Unity   :
07-06 15:47:22.178  9679  9699 I Unity   : Skipped rendering frame because GfxDevice is in invalid state (device lost)
07-06 15:47:22.178  9679  9699 I Unity   :
07-06 15:47:22.178  9679  9699 I Unity   : (Filename:  Line: 774)
07-06 15:47:22.178  9679  9699 I Unity   : 

I am looking for a solution that is a log of Android.

unity v 5.6.2f1
gvr sdk v 1.6
device samsung galaxy s7

OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state

This log seems to be a problem, but I can not solve it.

**Comment by sandorvasas** [comment]
I'm having the same error. Did you find any solution?

**Comment by spaul13** [comment]
Anyone with any solution? @sandorvasas @KyKimGlobepoint
