### ISSUE TITLE
single view in left right views of vr app in few phones 

### ISSUE THREAD

**Issue by rm301991** [googlevr/gvr-unity-sdk#646]
HI i am facing this problem in few phones like samsung , redmi, etc while it is running fine in many other phones . the problem is only one view is running in in both(left and right ) view in the app . how do i correct it . i am using unity 5.3.5 f1 . the first one is the correct way it should run and the second images is there is only single view in left right cam .

![19821246_1534459983280008_230452956_o](https://user-images.githubusercontent.com/29944610/27903928-ac37e4e8-6258-11e7-9562-7c6535239bc2.png)

![19619290_1525413644184642_491700526_o](https://user-images.githubusercontent.com/29944610/27903725-efa58f24-6257-11e7-8cb8-063492f70022.jpg)

**Comment by nathanmartz** [comment]
I'm sorry but we can no longer provide support for Unity versions below 5.6 (and the matching 1.60 SDK plugin), so please update and see if these issues persist.
