### ISSUE TITLE
Can gvr benefit from Single Pass Stereo Rendering in Unity?

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#647]
There is a option called "Stereo Rendering Method" in Unity. Can GVR benefit from Single Pass Stereo Rendering?
I am using Unity 5.6.1f1 and Gvr 1.5.

From  [this doc](https://developer.oculus.com/documentation/unity/latest/concepts/unity-rendering/#unity-single-pass) ,Gear VR supports Single Pass Stereo Rendering.

**Comment by nathanmartz** [comment]
As for 5.6.1p2 this mode works on Daydream the same was as on GearVR.

**Comment by clarkehe** [comment]
Does this mode work on Cardboard?
