### ISSUE TITLE
Permission Demo not Working in gvr version 1.60

### ISSUE THREAD

**Issue by Ankitjagrawat** [googlevr/gvr-unity-sdk#648]
I have try to run gvr permission demo in android device but it was crashed in device 

I have use Unity 5.6.2 or 5.6.1 , gvr 1.60 

When I have click request permission in demo  it was crashed i am trying in card-board 

But It is working When i have use Unity 5.5

**Comment by nathanmartz** [comment]
The permissions demo is Daydream only.

**Comment by Ankitjagrawat** [comment]
how to get permission read_external storage permission in unity android
