### ISSUE TITLE
Cannot show non-vr 2D (magic-window) switch on cardboard with gvr 1.60

### ISSUE THREAD

**Issue by ddudek** [googlevr/gvr-unity-sdk#649]
Hi, I'm trying to find a solution for showing non-vr switch in app that starts with regular stereoscopic view for cardboard. This button is for people who start the cardboard application without cardboard headset.

I need a button like "2D" below:

![image](https://user-images.githubusercontent.com/475488/28017047-78299e54-6577-11e7-8897-14823f85c070.png)

I have working solution for switching to non-vr (2d) view, the only issue is that I cannot get 2D button to render on top of stereoscopic camera rig.

How can I achieve that?

**Comment by peterept** [comment]
Apologies for the non-answer -but why not use the X button to exit back to 2d mode?

**Comment by nathanmartz** [comment]
Yes, that is the expected behavior for apps w/ both VR and non-VR modes. If you want to render a screenspace button like the X then you need to hack it into the android view hierarchy.
