### ISSUE TITLE
Can NOT set fps when VR mode enabled.

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#650]
I want to set fps using the following code for Cardboard app (Android)。

```
void Awake ()
{ 
       QualitySettings.vSyncCount = 0;
       Application.targetFrameRate =45; 
}
```

but the fps is still 60。If VR mode disabled, fps is 45。

If set fps to 30, it works when VR mode enabled。Why canNOT set fps to 45 when VR mode enabled.

I am using Unity 5.6.0f3 and GVR 1.4.

**Comment by nathanmartz** [comment]
We only support whole fractions of 60 fps (the vsync rate) to avoid judder.
