### ISSUE TITLE
Can I disable Distortion Correction?

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#653]
Distortion Correction affects performance. I tried a scene using  with Unity 5.5.1.f1 and gvr 1.2 on Android. If Distortion Correction enabled, fps is 20; disabled, fps is 60. 

With Unity 5.5.1.f1 and gvr 1.2, I can disable Distortion Correction.   But with Unity 5.6.0.f3 (cardboard integrated) or newer, there is no way to disable Distortion Correction.  A interface called "EnableDistortionCorrection" is removed from gvr so. 

I want to measure how Distortion Correction affects performance with Unity 5.6.0.f3.  If performance drops down, I plan to try if  [Vertex Displacement](https://www.youtube.com/watch?v=yJVkdsZc9YA) can works when Distortion Correction disabled.

Any suggestions? Help!!!

**Comment by nathanmartz** [comment]
Disabling main distortion and using app-specific vertex distortion is only supported in the legacy (pre 5.6) cardboard path. We may bring it back in the future, but it's not a high priority right now. If you want to go with vertex distortion, we recommend you use Unity 5.4 and an older SDK.
