### ISSUE TITLE
Camera rotate automatically when place phone on table.

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#655]
Using Samsung S7, I start the treasurehunt cardboard app and place the phone on a table, but the camera of scene rotates automatically.  I tested with Gvr ndk (Initialized GVR version 1.60.1) treasurehunt sampe and unity gvr demo. Both have this issue.

1、Start app
![bug3](https://user-images.githubusercontent.com/8831805/28195254-bfabab1c-687b-11e7-9a36-2af17fd84ecd.JPG)

2、About 2 minutes later
![bug4](https://user-images.githubusercontent.com/8831805/28195257-c44ebae2-687b-11e7-8d71-3fb1387a7eab.JPG)

**Comment by vinhui** [comment]
Have you tried different phones, might be your gyro being broken

**Comment by clarkehe** [comment]
@vinhui Different phones also have this issue.
