### ISSUE TITLE
Unity builds fail when built on Unity cloud build

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/gvr-unity-sdk#656]
I don't know if this is a Unity issue or GVR issue but using cloud build to build for iOS with Unity 5.6, 2017.1.0f1, 2017.1.0f3 and GVR 1.30 to 1.60 fails with the errors below.

2017.1 and 1.60 local builds are fine out of the box.

Error log is from 2017.1.0fx and 1.60. Errors from previous versions vary:
> 
> 11188:        [xcode] ld: warning: directory not found for option '-L/BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-cgyqwjesaesgklhhvwnsvegjqtrc/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/GTMSessionFetcher'
> 11189:        [xcode] ld: warning: directory not found for option '-L/BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-cgyqwjesaesgklhhvwnsvegjqtrc/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/GoogleToolboxForMac'
> 11190:        [xcode] ld: library not found for -lGTMSessionFetcher
> 11191:        [xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 11192:        [xcode] ** ARCHIVE FAILED **
> 11193:        [xcode] The following build commands failed:
> 11194:        [xcode] 	Ld /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-cgyqwjesaesgklhhvwnsvegjqtrc/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/testproject normal armv7
> 11195:        [xcode] 	Ld /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-cgyqwjesaesgklhhvwnsvegjqtrc/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/testproject normal arm64
> 11196:        [xcode] (2 failures)
> 11197: ! build of 'ios-builder-2017-1' failed. compile failed
>

**Comment by fredsa** [comment]
Fixed, according to https://github.com/googlevr/gvr-unity-sdk/issues/670#issuecomment-333129842.
