### ISSUE TITLE
iOS - Locking phone while app is running breaks VR view for life of application. 

### ISSUE THREAD

**Issue by steeb-dev** [googlevr/gvr-unity-sdk#658]
Making a Unity app in iOS 10+, with Unity 5.6.2.
Mixed mode (2d & cardboard).

If the app is open while the phone is locked, on returning to the app the VR view is completely squashed and cannot recover. 

Swapping between cardboard & 2d VR devices doesn't fix the issue. 

Reloading the scene doesn't fix the issue.

Only way to fix is to close and reopen the app entirely. 

To test this wasn't an issue with other plugins or code in my app, I created a bare bones Unity project, with a simple UI button which just turns the cardboard device on and off. This issue is 100% replicable in this project. 

-Run the app.
-Lock the phone
-Unlock the phone
-VR view is squashed every time.

This doesn't seem related to issues with Landscape Left, I've forced the XCode build to Landscape Left and in my example code make a call to ensure the Screen is Landscape Left every time the VR device changes. 

Image of VR view before locking the phone.
![img_0423](https://user-images.githubusercontent.com/15644723/28256539-d11389d2-6b06-11e7-94c3-8938326a4b47.PNG)

Image of VR view AFTER unlocking the phone.
![img_0424](https://user-images.githubusercontent.com/15644723/28256542-d2757308-6b06-11e7-8585-cea7e9088832.PNG)

Xcode settings for build
![xcodesettings](https://user-images.githubusercontent.com/15644723/28256609-7670cfac-6b07-11e7-801c-86cb3dcd2aab.png)

I've hosted the example project on GitHub if you want to confirm whether there's any fundamental issue in how I'm activating the cardboard VR device.
https://github.com/steeb-dev/ExampleGVRSquish

**Comment by joejo-unity** [comment]
Please file a Unity bug with repro project and steps so we can start to take action on this.

**Comment by joejo-unity** [comment]
Please make sure you test with 5.6.2p2 prior to filing if  you haven't already.

**Comment by joejo-unity** [comment]
FYI Using your project and the same settings I do not report the issue in 5.6.2.p2.

**Comment by steeb-dev** [comment]
I tried the project on 5.6.2.p2. It seems like the frequency of occurrence has been reduced but I was still able to replicate the issue on that project. 

I should point out that I hit the power button to put the phone to sleep and wait at least 15-20 seconds before waking.

**Comment by joejo-unity** [comment]
Same here. The original issue was made better with an update of the GVR NDK
to 1.6. My guess is an update to GVR to a later version would help. You can
try manually updating the Google Cocoapod and seeing if that helps at all.
Instructions for doing that can be found on the Cocoapods site.

Cocoapods: https://cocoapods.org
Google Library: https://cocoapods.org/?q=GVR


Joseph Jones
Senior Software Engineer
Unity3D

**Comment by steeb-dev** [comment]
Thanks, I'll give that a go.

I've raised this via Unity bug reporting and it's been acknowledged on that end.
https://fogbugz.unity3d.com/default.asp?932138_3ec6cppig4ei7p8t

**Comment by steeb-dev** [comment]
FYI, updating the GVR SDK pod to 1.70 doesn't resolve the issue.

**Comment by fredsa** [comment]
Will continue tracking this issue as #838.
