### ISSUE TITLE
unity5.6 + gvrsdk1.6.0 How to assign left or right camera to render up-down Panoramic

### ISSUE THREAD

**Issue by cwkcyd** [googlevr/gvr-unity-sdk#659]
up-down Panoramic to Separate rendering, such as andese.jpg, Gvr1.0.3 version before use, include Legacy to add gvreye, now How to assign? thanks

**Comment by nathanmartz** [comment]
The best approach is to use the stereo eye index in a custom shader. There is an example of this in the video player samples in the SDK.

**Comment by cwkcyd** [comment]
Thanks
