### ISSUE TITLE
Unity3D and Daydream UI with only skybox bkg in Pixel XL has right eye distortion

### ISSUE THREAD

**Issue by reed-alpert** [googlevr/gvr-unity-sdk#660]
A scene with Unity UI and only skybox bg and 2 cameras (Main for game objects and 2nd for UI to keep it on top) on a Pixel XL has right eye distortion. Works fine on a Moto Z Force Droid and the Unity Editor. Also works for Pixel, Moto, and Unity Editor if the skybox is off and the background is a room built from cubes.

Moto Z Force Droid, Android 7.0
Google Pixel XL, Android 7.1.2

Unity 2017.1.0f3
GVR Unity SDK 1.60

Images attached taken from phone screens to show both eyes. The pixel_with_skybox_bkg.jpg shows the right eye with distorted UI element rendering.

I tried both Mono and IL2CPP builds with the same error.

Also tried Android 7.1 (API 25) for Pixel XL with same error.

Also works OK on Pixel XL and Moto phones if there is only 1 camera, but then game objects can occlude the UI.

 I can provide a project to recreate this if that helps.

![pixel_with_3d_bkg](https://user-images.githubusercontent.com/23744336/28276332-9b499ebc-6ae4-11e7-907a-cc841cbd981e.jpg)
![pixel_with_skybox_bkg](https://user-images.githubusercontent.com/23744336/28276333-9db48d38-6ae4-11e7-87f6-0567a131bc4d.jpg)
![moto_with_3d_bkg](https://user-images.githubusercontent.com/23744336/28276337-a024ae54-6ae4-11e7-8b53-d5cbd5153858.jpg)
![moto_with_skybox_bkg](https://user-images.githubusercontent.com/23744336/28276339-a1e81d02-6ae4-11e7-960e-5ccefa3b5014.jpg)

**Comment by bopangzz** [comment]
@joejo-unity Can you take a look at this issue? Seems like an issue in Unity VR rendering.

**Comment by fredsa** [comment]
@reed-alpert Can you file a Unity bug on a project which reproduces these right side artifacts?
Please reply here with the Unity case number, that way @joejo-unity will have a project to look at.

**Comment by joejo-unity** [comment]
Does this happen on any daydream phone or just the pixel XL?

**Comment by reed-alpert** [comment]
@fredsa  @joejo-unity
The Unity case is 939222 - it has the screen shots attached as well as a skeleton project that shows the issue.
For phones I've tried the Moto, which works fine, and the Pixel XL, which has the right-eye distortion.
Also Unity Editor on Windows 10 is fine.

**Comment by fredsa** [comment]
@reed-alpert Are you still seeing this issue on your Pixel XL?

After some investigation, this sounds like a driver issue. If you're still experiencing this issue can you attach or send me a Unity project which reproduces it?

**Comment by reed-alpert** [comment]
I no longer see this on the Pixel XL with Android 8.0.0 & Unity 2017.1.1p3 / IL2CPP & GVR 1.70.
Closing the case now, thanks.

**Comment by fredsa** [comment]
@reed-alpert For future reference, We believe the right eye issues you were seeing has been fixed by a driver update which was included in the Pixel's Android operating system update from 7.1.2 to 8.0.0.
