### ISSUE TITLE
[Documentation issue] VR Icon format unclear

### ISSUE THREAD

**Issue by Marchelune** [googlevr/gvr-unity-sdk#664]
Hi there,

It is a minor documentation issue, but [PB-P2](https://developers.google.com/vr/distribute/daydream/publishing-requirements#PB-P2) is a bit confusing. Both the criteria and the PSD file point the need of **two 512x512 PNG files**, yet only half of those PNGs are displayed in the Daydream home (small tiles in the image below) :

![Image of daydream home](https://developers.google.com/vr/images/publishing/pb-p1-vr-icons.png)

So the underlying question is here is : **should we use only the half of the PNG files** (then why using 512x512 files ?) or are there some places in the store where the whole PNG is used (e.g. for bigger tiles in the image above) ?

**Comment by reed-alpert** [comment]
If you hover over an icon in the store part of the image will move forwards. That part is the 2nd png file. The two together make the icon, but the top image move forwards, and the bottom image stays put. They are set in the Daydream part of the Virtual Reality SDKs section of the Unity Player settings.

**Comment by Marchelune** [comment]
@reed-alpert I know how the VR icon works, my problem is more about the format : Clients send us the two layers in a 512x512 format, as specified in the doc, yet what is displayed in the tiles in the image above is *not* the whole 512x512 file (seems more like 256x512, see the HBO icon for instance). If you provide Unity with a 512x512, it will appear cut in half here.

**Comment by reed-alpert** [comment]
@Marchelune, yes, I found the same thing to be true, I had to adjust the icons fg/bg so it looked good in Daydream app. There are some Photoshop stencils on the Daydream Requirements site that might help show what the boundaries are. But I haven't see the full 512x512 in another place in Daydream.

**Comment by fredsa** [comment]
[PB-P2](https://developers.google.com/vr/distribute/daydream/publishing-requirements#PB-P2) indeed has a link to a set of Photoshop files, which you can also open in GIMP. These files contain stencils which indicate precisely which portion of the full 512x512 image are used. The unused areas are not used anywhere else.
