### ISSUE TITLE
GvrPointerGraphicRaycaster requires GvrPointer to have a Camera when in Direct mode.

### ISSUE THREAD

**Issue by amrithm98** [googlevr/gvr-unity-sdk#666]
I'm unable to use the play function in unity. Whenever i click the play button, this error comes up and stops rendering. I'm using the controller emulator app in the phone connected to the computer via usb. 
![bug](https://user-images.githubusercontent.com/17807428/28671797-8823e4fe-72fb-11e7-9efe-a03575a9d56a.PNG)

**Comment by dsternfeld7** [comment]
What version of the SDK are you using? If 1.7, What is the raycast mode set to on the GvrLaserPointer script?

The 1.7 SDK made some changes to the structure of the GvrControllerPointer prefab, if you've modified that prefab based on a previous version of the SDK, that could cause this problem.

**Comment by amrithm98** [comment]
I haven't made any changs to the sdk. I'm simply running the demo. The sdk I use is 5.7

**Comment by dsternfeld7** [comment]
Thanks, have you set the demo to Cardboard mode or Daydream mode?

**Comment by amrithm98** [comment]
Cardboard

**Comment by dsternfeld7** [comment]
Select GvrReticlePointer and change the RaycastMode to Camera in the inspector, that should fix it. Thanks for pointing out this bug!

**Comment by amrithm98** [comment]
I'll check that out. Thanks

**Comment by amrithm98** [comment]
That worked Well. Thanks.

**Comment by isometriq** [comment]
I have the same error happening every frame (it's saturating he logs). I've tried the solution, but it seems to be already set up to "Camera".

Using Unity 2017.1 and GVR 1.7.0
I think i'm using Cardboard mode (is that here? Player Settings > Other Settings > Virtual Reality SDKs)

In the demo scene hierarchy, I select the element:
Player > Main Camera > GvrControllerPointer > Laser

In the inspector, under Gvr Laser Pointer, Raycast Mode is already set to "Camera"

**Comment by dsternfeld7** [comment]
This error is happening on the cardboard reticle (GvrReticlePointer), not the controller (GvrControllerPointer). Do you have the demo set to use the the cardboard reticle or the daydream controller?

Thanks,

Dan

**Comment by isometriq** [comment]
I was refering to that other element above because that's the only place I could find a "Raycast Mode" option.

I don't have `GvrReticlePointer` in my hierarchy
The closer I have to reticle is:
Player > Main Camera > Laser > Reticle
it's only a quad mesh with a shader

I'm using the stock demo of 1.7.0 asset package without any changes `/Assets/GoogleVR/Demos/Scenes/GVRDemo`.

**Comment by dsternfeld7** [comment]
Try looking for it under Player->MainCamera->GvrReticlePointer, or in the search bar type "t:GvrReticlePointer".

DemoInputManager automatically switches between using GvrReticlePointer (gaze-based cardboard reticle) and GvrControllerPointer (Daydream controller) based on what you have set in the "Virtual Reality SDKs" player settings.

**Comment by isometriq** [comment]
Oh boy.. it was there all the time.
It was set to "direct". Setting it to "camera" fixes the errors.
Thanks

**Comment by fredsa** [comment]
The `GvrReticlePointer` prefab has the wrong (`Direct`) default raycast mode in 1.70.0.
This should be fixed in the next release. The prefab default will be `Camera`.

**Comment by fredsa** [comment]
Fixed in v1.100.
