### ISSUE TITLE
GvrToolTips.cs: `GvrArmModel' does not contain a definition for `Instance'

### ISSUE THREAD

**Issue by Arakade** [googlevr/gvr-unity-sdk#668]
Imported GoogleVR SDK 1.70 (upgrading from 1.10) on Unity 5.6.2 using unitypackage.
Receive compilation error:

> Assets/GoogleVR/Scripts/Controller/GvrToolTips.cs(80,56): error CS0117: \`GvrArmModel' does not contain a definition for \`Instance'

Checking GitHub, that error seems correct -- it's not there nor in parent GvrBaseArmModel.

p.s. I didn't remove previous package first but this seems a simple error of omission in the code.  Commenting out the line allowed compilation to continue for now.  If problems later, I'll add in what I assume is a simple singleton set in Start() ?

**Comment by dsternfeld7** [comment]
The file GvrTooltips.cs was removed in the 1.20 version of the SDK (Replaced by GvrTooltip.cs). I recommend deleting the previous package before importing the new one to prevent issues like this when files have been removed from the SDK.
