### ISSUE TITLE
Unity CloudBuild not support CocoaPods

### ISSUE THREAD

**Issue by guitarrapc** [googlevr/gvr-unity-sdk#670]
Currently Unity CloudBuild doesn't support CocoaPods. This cause iOS Package generated by CloudBuild will not include packages installed by CocoaPods like GoogleToolboxForMac, GRMSessionFetcher and GVRSDK.

Is there any workaround with this? For example, Google Ad and others have offline Zip file for any situation CocoaPods could not use.

> Integrate without CocoaPods : https://firebase.google.com/docs/ios/setup

**Comment by Ethan-VisualVocal** [comment]
I'm not sure if Unity decided this was a great way to go or Google, or both. Either way, its a non-starter.

**Comment by guneyozsan** [comment]
Details on CocoaPods were more insightful, thanks. I was hopeful for cloud build support since the beginning of this year but no improvement yet. I also mentioned the issue little before here: https://github.com/googlevr/gvr-unity-sdk/issues/656

Being unable to use cloud build, most of the issues on iOS block our QA and deployment cycle and takes away precious development time. Frustrating.

**Comment by rusmaxham** [comment]
Can you file a bug with Unity on this issue from the Unity Editor?

**Comment by guitarrapc** [comment]
Issue is already reported to Unity https://feedback.unity3d.com/suggestions/cocoapod-support-dependency-management , but my concern is "What about Google Vr Support for integrate without CocoaPods".

**Comment by rusmaxham** [comment]
Thank you for the Unity bug.

GoogleVR has no plans at this time to deliver the iOS Cardboard SDK as something other than a CocoaPod.  This issue needs to be addressed by Unity in the Cloud Build service.

**Comment by Marchelune** [comment]
Couldn't we at least have some help to set up dependencies ourselves ? Like it is done for Firebase ? https://firebase.google.com/docs/ios/setup#frameworks

**Comment by guitarrapc** [comment]
Absolutely. What @Marchelune points out is key of this issue. Yes, iOS can be deploy If we use some CI Tool, like Jenkins or others, on macOS. But not for managed CI services which not support XCode or CocoaPods. I hope GVR Team offer any guide like other Google Tools done.

Off course "No support" is one of the choice. (better than no announcement.)

**Comment by Marchelune** [comment]
So according to the comment on https://feedback.unity3d.com/suggestions/cocoapod-support-dependency-management , **cocoapod support has recently been added to unity cloud build** 🎉  !

**Comment by fredsa** [comment]
Duplicate #656 .
