### ISSUE TITLE
Segv with Controller Emulator & Unity running on Pixel XL phone

### ISSUE THREAD

**Issue by reed-alpert** [googlevr/gvr-unity-sdk#672]
Dell XPS 2720, Windows 10 (14393.1198), GeForce GT 750M
Unity 2017.1.0f3
GVR Unity SDK 1.60
Daydream Renderer 1.0
Controller Emulator 1.5.01
Google Pixel XL, Android 7.1.2

When using the Controller Emulator in Real Controller mode I get an Android SIGSEGV crash on the Pixel XL (log attached). My Moto works fine for this. And Pixel works for non-Real-Controller mode.

I start the emulator on the phone and it comes up fine and I can switch to Real Controller mode, but when I start my app in the Unity Editor I get the Android "app has stopped" message.

Log from Pixel phone:
[log_emulator_crash.txt](https://github.com/googlevr/gvr-unity-sdk/files/1188503/log_emulator_crash.txt)

**Comment by rusmaxham** [comment]
We're taking a look into this issue.  Thanks for the report.

**Comment by reed-alpert** [comment]
This is still happening with Pixel XL and Android 8.0.0.
My workaround is to use the Instant Preview which does work in both Full VR and Controller Only modes.

**Comment by chaosemer** [comment]
If this is still happening, please reopen. We believe we fixed this a while ago.
