### ISSUE TITLE
Reflections on water-surface (Unity WaterProDaytime) are wrong

### ISSUE THREAD

**Issue by savashito** [googlevr/gvr-unity-sdk#673]
I am creating a new issue in this topic because it seams that this is broken again for Unity 2017.1.0f3 with cardboard 1.7. 
Reflexions are wrong for vr when using the vr reality sdk cardboard.

![alt text](https://cloud.githubusercontent.com/assets/15873119/14822821/64eb68d8-0bd0-11e6-9c8b-0cd71290aa68.png "wrong vr reflexion")
![alt text](https://cloud.githubusercontent.com/assets/15873119/14822832/6efea808-0bd0-11e6-845b-20c0178fc7c6.png "correct reflexion")

I have been researching and it seams that when using the occulus driver instead, it seams to work correctly, https://forum.unity3d.com/threads/water-reflections-in-vr-are-wrong-in-5-4-0f1.417495/
any ideas?

original post:
https://github.com/googlevr/gvr-unity-sdk/issues/212

**Comment by lamhoan** [comment]
Yeap, go the same problem. And it seems to be affecting daydream only. I ported my app to Oculus Gear VR, Pico Goblin, Cardboard without any problems. There is something the Daydream sdk does which messes with the water reflection. I tried playing with the water pro script but so far no luck. 
I would appreciate any help on this! Thanks

**Comment by savashito** [comment]
Any update? or time frame when this will be fix or address?

**Comment by fredsa** [comment]
Thanks for following up. Let's use the original issue #212 to track this.

**Comment by tonnyESP** [comment]
Any updates? 
Here or in #212 ? 

Is there any way select the camera to project correctly both eyes?

**Comment by fredsa** [comment]
This issue is closed. Please use 212.
