### ISSUE TITLE
GvrFPSDisplay is not being rendered on device

### ISSUE THREAD

**Issue by ichabodcole** [googlevr/gvr-unity-sdk#674]
The new GvrFPSDisplay.prefab in 1.70 is rendering correctly for me in the editor, but nothing is displayed when actually viewing on a device. I get the same result both in my own project and with the GVRDemo scene.

Dev specs:
OSX
Unity 2017.1
GVR 1.70
Pixel XL

**Comment by miraleung** [comment]
Could you please see this can be repro'd with the GVRDemo scene? The GvrFPS.cs script should be drawing the FPS display in both eyes.

**Comment by ichabodcole** [comment]
@miraleung Yep, I tested both with my own scene and with a completely new project with just the GVR 1.7 assets. The GVRDemo scene shows the fps in the editor, but when deployed to the device the FPS counter is not displayed at all (neither eye).

If I get a chance, I'll try to test on a windows machine as well.

**Comment by rusmaxham** [comment]
Are you using single- or multi-pass rendering in your player settings?

**Comment by ichabodcole** [comment]
@rusmaxham Tried with both, and got the same result. I also turned off and on some of the other player settings like gpu skinning, multithreading and graphics jobs, which also had no effect.

**Comment by Bonfi96** [comment]
I have the same issue on windows, same unity and gvr versions

**Comment by ezotb** [comment]
Any updates? I cannot run the demo.

**Comment by pfreema1** [comment]
I have the same issue.  FPS displaying in the editor's game mode, but nothing while testing on actual device.

specs:
OSX 
Unity5.6.0f3
GVR 1.7
Pixel

**Comment by warrenEBB** [comment]
I have same issue. (FPS displays in editor, but nothing on Android device).

specs:
Windows10
Unity 5.6.3p1 Edu
GVR 1.7
Samsung Galaxy Note4

**Comment by fredsa** [comment]
As an alternative to the FPS text component, consider enabling [Performance HUD](https://developers.google.com/vr/tools/perfhud), which provides a lot more information.

**Comment by warrenEBB** [comment]
Cool. but this is Daydream App only feature? (i'm building Cardboard apps)

**Comment by pfreema1** [comment]
Fredsa, thank you for the tip!  That is very useful.  Is there a way to move the HUD from the center of view?

**Comment by tomgoogle** [comment]
I'm afraid there isn't a way to move it. We render it without lens distortion (for archaic platform reasons) so placing it in the center of the screen means it's challenging to move it around. We do render it slightly lower than center so you can look down a little and still see your scene though!

**Comment by JapaMala** [comment]
It's likely that Unity's immediate-mode UI is no longer supported in VR, and the new UI system will need to be used instead.

This will mean making use the the Text component that's currently required by the script, unused, and place the prefab as a child of a screen-space canvas.

**Comment by fredsa** [comment]
The broken `GvrFPSDisplay` prefab and script were removed in v1.100.
Daydream app developers are encouraged to use [Performance HUD](//developers.google.com/vr/tools/perfhud) instead.

**Comment by JapaMala** [comment]
Just want to note here that the performance hud is daydream only.

Cardboard app developers will need to use a different solution.

**Comment by tristandwyer** [comment]
@rusmaxham as @JapaMala noted this new performance hud is daydream only, however I'm working on a cardboard app targeting a device that is not daydream-ready. Is there a way to get a FPS counter going with google's tools instead of a new custom one? I'd prefer to avoid reverting to an older GVR SDK for obvious reasons.
