### ISSUE TITLE
Object NOT visible when using single pass (Stereo Rendering Method)

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#677]
I tried a very simple scene with one object. See the screenshot below.

![0282bba8-dc20-4478-98e5-3c7175ff88ae](https://user-images.githubusercontent.com/8831805/28965716-1a057a0a-7945-11e7-92af-71afd9f672fc.png)

The object is not visible, when i run the scene on Android phone. If I change the shader from unlit/texture to unlit/transparent, the object become visible. 

I tried using Xiao mi 5 and Oppo R9 Plus, both android phones have this problem. If I use Multi Pass Rendering , everything is OK. 

Untiy Version: 2017.1.0.f3
Gvr sdk Version: 1.4

**Comment by rusmaxham** [comment]
There are a variety of issues with Unity's Single-Pass rendering.  Please file a bug with Unity through the Unity Editor to escalate this issue.

**Comment by paulpv** [comment]
I am seeing what I think is the same problem on a mesh that I am programmatically building while parsing a .CTM file.
The object mesh renders fine in the editor and desktop build, but when run in Android the object mesh cannot be seen.

I am a bit new to Unity; How can I create a unlit/transparent multi-pass renderer in C# code?

**Comment by clarkehe** [comment]
@paulpv Ugui use transparent material by default. You can enable Multi-Pass Rendering in player setting.

**Comment by paulpv** [comment]
Turns out my issue on Android was due to simply failing to load the model from file because of problem using System.IO.StreamReader and System.IO.FileStream instead of the Unity recommended "Resources.Load(...)".
I didn't initially see the problem because flipping the Console to show output from the running Android Player seems unreliable.
