### ISSUE TITLE
Apps are named "Keyboard Support"

### ISSUE THREAD

**Issue by kaldhu** [googlevr/gvr-unity-sdk#678]
Using Unity 2017.2.0b2 and the Google VR SDK for Unity v1.70.

All apps created are named "Keyboard Support" regardless of what is set within the player settings.

Have tested by creating a new project setting it up for the android platform, choosing a simple product name ("TestName") and package name("com.fake.demo") and deployed to phone, this was named "TestName" as expected.
Then I imported the Google VR SDK Package into the same project, I did not change the package name or product name. I then uninstalled previous app, rebuilt and redeployed the new version to the phone. The app is now named incorrectly as "Keyboard Support"

**Comment by rusmaxham** [comment]
I believe this has been fixed in the most recent beta of 2017.2.  Please try that and let me know if it resolves your issue.

**Comment by rusmaxham** [comment]
I just learned the fix isn't in a publicly available beta yet.  It is expected to be in 2017.2.0b6.

**Comment by rusmaxham** [comment]
This should be fixed in the latest version of Unity 2017.2.
