### ISSUE TITLE
Custom Setting in 1.7  , how to make 3D feel video?

### ISSUE THREAD

**Issue by miraclestar** [googlevr/gvr-unity-sdk#679]
How to disable setting button?
How to make left and right eye to see different object ?

Thanks ~

**Comment by tedruxpin** [comment]
Hello miraclestar, can you describe in a little more detail what you want to achieve?  Regarding the settings button, do you mean the gear icon in the corner?  When you say the eyes should see different objects, do you mean completely different scenes, or the more typical case of slightly different angles of the same objects?

**Comment by miraclestar** [comment]
@tedruxpin thanks for you reply.

yes,I want to erase the gear icon in the corner.  Unity2017.1, GVR1.7;

![image](https://user-images.githubusercontent.com/1502697/29209120-96415e20-7ebf-11e7-872b-a5337d12a290.png)
I have 3D pictures like this , I want the left eye can only watch the left picture, right eye can only watch the right picture. so how to do this?

**Comment by vinhui** [comment]
Add another camera, and set the left and right eye field accordingly. Then use camera culling mask to only show something for 1 eye.

**Comment by dsternfeld7** [comment]
Additionally, you can render stereo images using a shader to control what texture is used for each eye. An example of this can be found in the Media App Template [here](https://github.com/googlevr/media-app-template/blob/master/Assets/MediaAppTemplate/Shaders/MediaScreen.shader)

**Comment by miraclestar** [comment]
thanks @dsternfeld7

**Comment by rusmaxham** [comment]
Why do you want to disable the settings button?  We strongly discourage doing this as this gives users access to general VR settings and is not visible to users when wearing a headset.
