### ISSUE TITLE
Any way to test cardboard apps without building?

### ISSUE THREAD

**Issue by Bonfi96** [googlevr/gvr-unity-sdk#680]
There is no insta preview for cardboard and there is no stereo preview in unity so I can't even use unity remote for some quick testing.
Is there anything I'm missing? Thanks!

**Comment by VadimTikhonyuk** [comment]
You can add stereo preview, open demo scene in google package, Also you can connect smarpthone via USB and control camera in unity by this way

**Comment by Bonfi96** [comment]
The stereo preview is not supported anymore in 1.70

**Comment by VadimTikhonyuk** [comment]
In my case I use 5.6.0f3 with GVR 1.4

**Comment by Bonfi96** [comment]
What's the difference between daydream and cardboard that prevents instapreview to be used with cardboard?

**Comment by gstanlo** [comment]
The app was originally focused on Daydream, and unfortunately uses several higher level Android API calls that are not available on devices which support Cardboard but not Daydream i.e. API <24.
