### ISSUE TITLE
Arm Model Native C Definitions

### ISSUE THREAD

**Issue by famagusta** [googlevr/gvr-unity-sdk#682]
I am trying to access the native library functions for support of an arm model. I am getting an unsatisfied link error - definition not found. 
Is the libgvr imported by unity different from the libgvr provided by googlevr android sdk? I am using version 1.70.0 for both.

**Comment by nathanmartz** [comment]
For Unity, we recommend you use the built in controller components and prefabs, which have basically the same arm model (plus some additional, Unity specific features).

**Comment by famagusta** [comment]
For my application, I am creating a new activity which has all rendering and controller input handling code written in c++. I am porting my library to enable use for unity end users. I cannot use Unity's built in controller components and prefabs. Can only use native functions in C.
