### ISSUE TITLE
Disable device Battery Notifications when charging

### ISSUE THREAD

**Issue by fabiocesarato** [googlevr/gvr-unity-sdk#685]
Using Unity 5.6.2p4 and the Google VR SDK for Unity v1.70.

I have updated Unity and Google VR SDK and now I see **battery notifications** when the phone is **charging**.
I attached and image that show this notifications:
![screenshot_20170810-093224](https://user-images.githubusercontent.com/5769042/29159766-0a361944-7db0-11e7-94b9-4cbb899c34ca.png)

How could I disable this notifications?

I see that there is the class GvrControllerBatteryLevel but is used to manage battery level of Daydream VR Controller

**Comment by nathanmartz** [comment]
Unfortunately this is a system notification that we can't work around.
