### ISSUE TITLE
Apple store rejects Unity GVR app due to “Kids Category”

### ISSUE THREAD

**Issue by alexberd** [googlevr/gvr-unity-sdk#686]
Publishing a unity ios app with GVR v.1.6 under the apple's "Kids" category, app is declined due to GVR help button (the small '?' at the bottom left) which is activated when the setting button (at the top right) is pressed. According to iTunes Connect support "it includes links out of the app or engages in commerce without first obtaining parental permission".

As per GVR version 1.00 the "setting" button is embedded in the GVR and is it not editable. The GvrView.setSettingsButtonEnabled command has been deactivated from GVR 1.00.

This means that any IOS application made with GVR version later than 1.0 cannot be published in I-tunes under the KIDs Category due to apple store's Guideline 1.3 - Safety - Kids Category as the setting button include links out of the app without obtaining parental permission.

**Comment by dustinfreeman** [comment]
@alexberd Did you get to a satisfactory resolution to this?

**Comment by alexberd** [comment]
Unfortunately not, this is still a limitation. Just, don't apply "Kids" category at Apple store.

**Comment by chaosemer** [comment]
Unfortunately the help button is not customizable in our SDK. We do not plan to add customization at this time.
