### ISSUE TITLE
How can I use single screen mode on Android device

### ISSUE THREAD

**Issue by sccdhyt** [googlevr/gvr-unity-sdk#687]
I‘m using unity 2017.1.0f3 and gvrunity sdk 1.70.
I had seen some issues about switch between VR mode and NonVR mode.
I tried the code like:
void Start () {
		StartCoroutine (initiatevrcoroutine ());
	}
	
	// Update is called once per frame
	void Update () {
		
	}

	IEnumerator initiatevrcoroutine()
	{
		VRSettings.LoadDeviceByName("");
		yield return null;
		VRSettings.enabled = false;
	}
I tried to run it on device and it's single screen but the camera view didn't move when I revolve the device.
It's not I want. How can I use single screen mode?

**Comment by Kermeth** [comment]
If you're trying to use the Magic Window Mode you can use this:

```
UnityEngine.VR.VRSettings.enabled = false;
Camera.main.GetComponent<Transform>().localRotation = UnityEngine.VR.InputTracking.GetLocalRotation(VRNode.CenterEye);
```

More info here: https://docs.unity3d.com/Manual/VRDevices-GoogleVR.html

**Comment by clarkehe** [comment]
@Kermeth  Your suggestion doesNOT work!

**Comment by vinhui** [comment]
Do you set the rotation every frame?

**Comment by Arakade** [comment]
@vinhui hey, I find it works if I VRSettings.LoadDeviceByName("cardboard"); (other stuff the same).  HTH
