### ISSUE TITLE
VideoPlayer Black Texture with Video sound

### ISSUE THREAD

**Issue by tazzkiller** [googlevr/gvr-unity-sdk#689]
On Samsung Phone the video player return a black texture to quad or sphere object but the video sound is playing.

**Comment by rusmaxham** [comment]
What version of Unity?  What version of the GVR Unity SDK?

**Comment by tazzkiller** [comment]
GVR 1.70
Unity 2017.1.0f3

**Comment by Cooper6334** [comment]
I have same issue with Unity 5.6.2f1 and GVR1.7, Samsung S7. But it works fine on HTC M9.

**Comment by sandorvasas** [comment]
Same issue for me with the SDK's VideoDemo. I also tried to wait for 3 seconds after launching the app and then starting the playback but still got black screen.

With latest GVR SDK + Unity 5.6.2f1

Not sure if it's related, but log displays 

`
OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM enum argument out of range
(Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 383)
`

I wanted to check what exactly is the invalid value for the enum, but it seems GfxDeviceGLES.cpp is not open-source (or is it?)

**Comment by alejodaraio** [comment]
Same issue here with S8

**Comment by rusmaxham** [comment]
Thanks for bringing this up.  We'll take a look.

**Comment by rusmaxham** [comment]
That invalid enum error is a red herring and occurs even when the video plugin works properly on Pixel devices.

**Comment by sujay46** [comment]
Any update on this issue?

**Comment by sujay46** [comment]
I am facing the same issue. I traced this issue to the shader(Google VR/Video Unlit Shader). This is working in OpenGLES 3.1 devices. But breaking in OpenGLES3.0 devices.

**Comment by sandorvasas** [comment]
@sujay46 Could you find out any more detail about what could be wrong in the shader code? How did you trace the problem? Do you have any error outputs? I'd also like to take a look into it.

**Comment by sujay46** [comment]
@sandorvasas I used ADB logcat, and I found out it was printing out shader code in logcat. This happens when the device doesn't support the shader.

**Comment by nathanmartz** [comment]
Can you paste the shader code that appears in logcat here?

**Comment by sujay46** [comment]
[logcat_shader.txt](https://github.com/googlevr/gvr-unity-sdk/files/1335847/logcat_shader.txt)

This is what I got in my logcat.

**Comment by sujay46** [comment]
@sandorvasas  and @nathanmartz  I was going through the shaders that are used in GVR 1.70. It is written in "GLSLProgram" as contrary to the shader in GVR 1.60 which is written in "CGPROGRAM". Could that be causing issues in shader compiling? I am not a pro in shaders, but probably this could help you guys to figure out the issue. 
I am attaching both the shaders here. 
shader from Gvr 1.70
[VideoUnlitShader.shader.gvr1_70.txt](https://github.com/googlevr/gvr-unity-sdk/files/1339570/VideoUnlitShader.shader.gvr1_70.txt)
Shader from Gvr 1.60
[VideoDemoInsideShader.shader.gvr1_60.txt](https://github.com/googlevr/gvr-unity-sdk/files/1339566/VideoDemoInsideShader.shader.gvr1_60.txt)

**Comment by rusmaxham** [comment]
Yes, the video player pipeline was redone in 1.70 to remove a buffer copy step that had previously been done in a native plugin to get the video buffers into a form Unity could use.  Now the GLSLProgram is able to use video buffers directly from the decoder without the copy step, improving performance and battery life.

I just tried the Video Demo scene in the SDK built with 5.6 and 2017.1 on Samsung S8+, Android 7.0 and am unable to reproduce the issue.

@sujay46, that logcat suggests the shader didn't compile properly on your device.  Can you give me any more information about the device?  What country was it purchased in?  What version of Android is it running?  What API level are you targeting in Unity?

**Comment by rusmaxham** [comment]
Could you run this adb command and report back the output:

`adb shell getprop ro.build.fingerprint`

**Comment by sujay46** [comment]
@rusmaxham It is a Samsung Galaxy S6.
and this what i got for your adb command.
samsung/zeroflteue/zerofltetmo:7.0/NRD90M/G920TUES5EQH2:user/release-keys

**Comment by rusmaxham** [comment]
@sandorvasas could you send me your android build fingerprint?  I've so far been unable to reproduce on both the Qualcomm and Exynos versions of the Samsung S8 and S8+.

@sujay46 that version of Android should be supporting the needed extensions to support the video player.  Could you send me the project (with project settings) you created to reproduce the issue?

**Comment by sujay46** [comment]
@rusmaxham my device has Android 7.0. Here is the [link](https://www.dropbox.com/s/ras5jmsl88eqrv5/GVR_Video_test.zip?dl=0
) for the project. Just run the VideoDemo scene in Google VR demos.

**Comment by rusmaxham** [comment]
The video plugin is not guaranteed to work on non-Daydream-ready devices, like the S6.  I'm much more able to assist in debugging issues with the video plugin on a Daydream-ready device, like the S8.  If I can get my hands on an S6, I'll try to debug this issue, but no guarantees.

**Comment by azcoffeehabit** [comment]
I am having this issue on a PixelXL Android 8.0.   Unity 2017.2.1f1 with GVR SDK for Unity v1.110.0.   Build and run the GVR VideoDemo scene and playing DASH Video on GCS gets the audio but a blank blue screen with the overlay video controls.

**Comment by azcoffeehabit** [comment]
12-27 12:29:35.078 13514-13735/com.testvr.pablosquared E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state   (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 368)
[logcat.txt](https://github.com/googlevr/gvr-unity-sdk/files/1589853/logcat.txt)
