### ISSUE TITLE
Repo missing .meta files

### ISSUE THREAD

**Issue by otri** [googlevr/gvr-unity-sdk#692]
All prefabs and source linkages are broken without the necessary .meta files.

**Comment by rusmaxham** [comment]
The github repo is not a fully functional repo of the plugin.  It is meant to be used for reference.  Please use the .unitypackage in your Unity projects.

**Comment by nathanmartz** [comment]
[just you]

The repo actually should be fully functional now, so this is a legit bug.
We took steps in that direction before the handoff, but I think mira just
missed the meta files.

**Comment by otri** [comment]
Thanks Nathan.  Yeah, probably the .meta files were hidden by default, which resulted in them being missed on commit. They're pretty essential for version control, so @rusmaxham I recommend re-opening this ticket until .meta files are back in the repo.

**Comment by rusmaxham** [comment]
I just pushed the .metas.

**Comment by otri** [comment]
Wonderful, thank you!
