### ISSUE TITLE
Allow for "Reduce blur" low latency screen mode when VRSettings.enabled = false

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#693]
My app allows toggling between the Magic Window and VR modes as loosely described here -
 https://docs.unity3d.com/Manual/VRDevices-GoogleVR.html

When I set  VRSettings.enabled = false, it doesn't allow me to use the reduced blur latency screen mode. I see this:

`I/VrManagerService: VR mode is allowed
`

But when VRSettings.enabled = true, the reduced blur low latency mode kicks in and I see this:

```
I/VrManagerService: VR mode is allowed
I/VrManagerService: VR mode enabled
```

In an older version of Unity (with the GVR SDK) I was able to have the reduced blur latency screen mode in both Magic Window and VR modes. Is there still a way to accomplish this in the current native integration?

**Comment by rusmaxham** [comment]
GoogleVR doesn't support low-persistence display outside of fullscreen VR.  If it used to work it was unintentional.

**Comment by dustinkerstein** [comment]
Bummer, it was a very nice feature. It seems like most games / 3D apps would benefit from this low-persistence mode. Thanks for the update though.
