### ISSUE TITLE
 Unable to convert classes into dex format when i am using new firebase and gvr sdk 1.30

### ISSUE THREAD

**Issue by MartinjMartin** [googlevr/gvr-unity-sdk#694]
I have a working copy of my Unity project which uses gvr sdk 1.30 and firebase, now i updated the firebase to latest version. after that when i am building i am getting the error - Unable to convert classes into dex format... i have updated  gvr to 1.40 , still i am getting the same issue.. i looked for the duplicate jar files and classes but i could not reach to a solution.

i also get a log - google.versionhandlerImpl already loaded
I have two files in my project after importing new firbase and gvr, they are google.versionhandlerImpl and google.versionhandler

This is my log -

CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_60\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/protobuf/GeneratedExtensionRegistryLoader;
1 error; aborting
]
stdout[
processing archive E:\Backup\WorkShop\Source\Unity\Temp\StagingArea\android-libraries\firebase-analytics-11.0.4\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/measurement/
processing com/google/android/gms/measurement/AppMeasurementContentProvider.class...
processing com/google/android/gms/measurement/AppMeasurementInstallReferrerReceiver.class...
processing com/google/android/gms/measurement/AppMeasurementJobService.class...
processing com/google/android/gms/measurement/AppMeasurementReceiver.class...
processing com/google/android/gms/measurement/AppMeasurementService.class...
processing archive E:\Backup\WorkShop\Source\Unity\Temp\StagingArea\android-libraries\firebase-analytics-impl-11.0.4\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzcec.class...
processing com/google/android/gms/internal/zzced.class...
processing com/google/android/gms/internal/zzcee.class...
processing com/google/android/gms/internal/zzcef.class...
processing com/google/android/gms/internal/zzceg.class...
processing com/google/android/gms/internal/zzceh.class...
processing com/google/android/gms/internal/zzcei.class...
processing com/google/android/gms/internal/zzcej.class...
processing com/google/android/gms/internal/zzcek.class...
processing com/google/android/gms/internal/zzcel.class...
processing com/google/android/gms/internal/zzcem.class...
processing com/google/android/gms/internal/zzcen.class...
processing com/google/android/gms/internal/zzceo.class...
processing com/google/android/gms/internal/zzcep.class...
processing com/google/android/gms/internal/zzceq.class...
processing com/google/android/gms/internal/zzcer.class...
processing com/google/android/gms/internal/zzces.class...
processing com/google/android/gms/internal/zzcet.class...
processing com/google/android/gms/internal/zzceu.class...
processing com/google/android/gms/internal/zzcev.class...
processing com/google/android/gms/internal/zzcew.class...
processing com/google/android/gms/internal/zzcex.class...
processing com/google/android/gms/internal/zzcey.class...
processing com/google/android/gms/internal/zzcez.class...
processing com/google/android/gms/internal/zzcfa.class...
processing com/google/android/gms/internal/zzcfb.class...
processing com/google/android/gms/internal/zzcfc.class...
processing com/google/android/gms/internal/zzcfd.class...
processing com/google/android/gms/internal/zzcfe.class...
processing com/google/android/gms/internal/zzcff.class...
processing com/google/android/gms/internal/zzcfg.class...
processing com/google/android/gms/internal/zzcfh.class...
processing com/google/android/gms/internal/zzcfi.class...
processing com/google/android/gms/internal/zzcfj.class...
processing com/google/android/gms/internal/zzcfk.class...
processing com/google/android/gms/internal/zzcfl.class...
processing com/google/android/gms/internal/zzcfm.class...
processing com/google/android/gms/internal/zzcfn.class...
processing com/google/android/gms/internal/zzcfo.class...
processing com/google/android/gms/internal/zzcfp.class...
processing com/google/android/gms/internal/zzcfq.class...
processing com/google/android/gms/internal/zzcfr.class...
processing com/google/android/gms/internal/zzcfs.class...
processing com/google/android/gms/internal/zzcft.class...
processing com/google/android/gms/internal/zzcfu.class...
processing com/google/android/gms/internal/zzcfv.class...
processing com/google/android/gms/internal/zzcfw.class...
processing com/google/android/gms/internal/zzcfx.class...
processing com/google/android/gms/internal/zzcfy.class...
processing com/google/android/gms/internal/zzcfz.class...
processing com/google/android/gms/internal/zzcga.class...
processing com/google/android/gms/internal/zzcgb.class...
processing com/google/android/gms/internal/zzcgc.class...
processing com/google/android/gms/internal/zzcgd.class...
processing com/google/android/gms/internal/zzcge.class...
processing com/google/android/gms/internal/zzcgf.class...
processing com/google/android/gms/internal/zzcgg.class...
processing com/google/android/gms/internal/zzcgh.class...
processing com/google/android/gms/internal/zzcgi.class...
processing com/google/android/gms/internal/zzcgj.class...
processing com/google/android/gms/internal/zzcgk.class...
processing com/google/android/gms/internal/zzcgl.class...
processing com/google/android/gms/internal/zzcgl$zza.class...
processing com/google/android/gms/internal/zzcgm.class...
processing com/google/android/gms/internal/zzcgn.class...
processing com/google/android/gms/internal/zzcgo.class...
processing com/google/android/gms/internal/zzcgp.class...
processing com/google/android/gms/internal/zzcgq.class...
processing com/google/android/gms/internal/zzcgr.class...
processing com/google/android/gms/internal/zzcgs.class...
processing com/google/android/gms/internal/zzcgt.class...
processing com/google/android/gms/internal/zzcgu.class...
processing com/google/android/gms/internal/zzcgv.class...
processing com/google/android/gms/internal/zzcgw.class...
processing com/google/android/gms/internal/zzcgx.class...
processing com/google/android/gms/internal/zzcgy.class...
processing com/google/android/gms/internal/zzcgz.class...
processing com/google/android/gms/internal/zzcha.class...
processing com/google/android/gms/internal/zzchb.class...
processing com/google/android/gms/internal/zzchc.class...
processing com/google/android/gms/internal/zzchd.class...
processing com/google/android/gms/internal/zzche.class...
processing com/google/android/gms/internal/zzchf.class...
processing com/google/android/gms/internal/zzchg.class...
processing com/google/android/gms/internal/zzchh.class...
processing com/google/android/gms/internal/zzchi.class...
processing com/google/android/gms/internal/zzchj.class...
processing com/google/android/gms/internal/zzchk.class...
processing com/google/android/gms/internal/zzchl.class...
processing com/google/android/gms/internal/zzchm.class...
processing com/google/android/gms/internal/zzchn.class...
processing com/google/android/gms/internal/zzcho.class...
processing com/google/android/gms/internal/zzchp.class...
processing com/google/android/gms/internal/zzchq.class...
processing com/google/android/gms/internal/zzchr.class...
processing com/google/android/gms/internal/zzchs.class...
processing com/google/android/gms/internal/zzcht.class...
processing com/google/android/gms/internal/zzchu.class...
processing com/google/android/gms/internal/zzchv.class...
processing com/google/android/gms/internal/zzchw.class...
processing com/google/android/gms/internal/zzchx.class...
processing com/google/android/gms/internal/zzchy.class...
processing com/google/android/gms/internal/zzchz.class...
processing com/google/android/gms/internal/zzcia.class...
processing com/google/android/gms/internal/zzcib.class...
processing com/google/android/gms/internal/zzcic.class...
processing com/google/android/gms/internal/zzcid.class...
processing com/google/android/gms/internal/zzcie.class...
processing com/google/android/gms/internal/zzcif.class...
processing com/google/android/gms/internal/zzcig.class...
processing com/google/android/gms/internal/zzcih.class...
processing com/google/android/gms/internal/zzcii.class...
processing com/google/android/gms/internal/zzcij.class...
processing com/google/android/gms/internal/zzcik.class...
processing com/google/android/gms/internal/zzcil.class...
processing com/google/android/gms/internal/zzcim.class...
processing com/google/android/gms/internal/zzcin.class...
processing com/google/android/gms/internal/zzcio.class...
processing com/google/android/gms/internal/zzcip.class...
processing com/google/android/gms/internal/zzciq.class...
processing com/google/android/gms/internal/zzcir.class...
processing com/google/android/gms/internal/zzcis.class...
processing com/google/android/gms/internal/zzcit.class...
processing com/google/android/gms/internal/zzciu.class...
processing com/google/android/gms/internal/zzciv.class...
processing com/google/android/gms/internal/zzciw.class...
processing com/google/android/gms/internal/zzcix.class...
processing com/google/android/gms/internal/zzciy.class...
processing com/google/android/gms/internal/zzciz.class...
processing com/google/android/gms/internal/zzcja.class...
processing com/google/android/gms/internal/zzcjb.class...
processing com/google/android/gms/internal/zzcjc.class...
processing com/google/android/gms/internal/zzcjd.class...
processing com/google/android/gms/internal/zzcje.class...
processing com/google/android/gms/internal/zzcjf.class...
processing com/google/android/gms/internal/zzcjg.class...
processing com/google/android/gms/internal/zzcjh.class...
processing com/google/android/gms/internal/zzcji.class...
processing com/google/android/gms/internal/zzcjj.class...
processing com/google/android/gms/internal/zzcjk.class...
processing com/google/android/gms/internal/zzcjl.class...
processing com/google/android/gms/internal/zzcjm.class...
processing com/google/android/gms/internal/zzcjn.class...
processing com/google/android/gms/internal/zzcjo.class...
processing com/google/android/gms/internal/zzcjp.class...
processing com/google/android/gms/internal/zzcjq.class...
processing com/google/android/gms/internal/zzcjr.class...
processing com/google/android/gms/internal/zzcjs.class...
processing com/google/android/gms/internal/zzcjt.class...
processing com/google/android/gms/internal/zzcju.class...
processing com/google/android/gms/internal/zzcjv.class...
processing com/google/android/gms/internal/zzcjw.class...
processing com/google/android/gms/internal/zzcjx.class...
processing com/google/android/gms/internal/zzcjy.class...
processing com/google/android/gms/internal/zzcjz.class...
processing com/google/android/gms/internal/zzcka.class...
processing com/google/android/gms/internal/zzckb.class...
ignored resource com/google/android/gms/measurement/
processing com/google/android/gms/measurement/AppMeasurement.class...
processing com/google/android/gms/measurement/AppMeasurement$ConditionalUserProperty.class...
processing com/google/android/gms/measurement/AppMeasurement$Event.class...
processing com/google/android/gms/measurement/AppMeasurement$EventInterceptor.class...
processing com/google/android/gms/measurement/AppMeasurement$OnEventListener.class...
processing com/google/android/gms/measurement/AppMeasurement$Param.class...
processing com/google/android/gms/measurement/AppMeasurement$UserProperty.class...
processing com/google/android/gms/measurement/AppMeasurement$zza.class...
processing com/google/android/gms/measurement/AppMeasurement$zzb.class...
ignored resource com/google/firebase/
ignored resource com/google/firebase/analytics/
processing com/google/firebase/analytics/FirebaseAnalytics.class...
processing com/google/firebase/analytics/FirebaseAnalytics$Event.class...
processing com/google/firebase/analytics/FirebaseAnalytics$Param.class...
processing com/google/firebase/analytics/FirebaseAnalytics$UserProperty.class...
ignored resource E:\Backup\WorkShop\VRQuiz\Source\Unity\Temp\StagingArea\android-libraries\firebase-app-unity-4.0.3\libs\.\armeabi-v7a\libApp.so
processing archive E:\Backup\WorkShop\VRQuiz\Source\Unity\Temp\StagingArea\android-libraries\firebase-app-unity-4.0.3\libs\.\classes.jar...
ignored resource E:\Backup\WorkShop\VRQuiz\Source\Unity\Temp\StagingArea\android-libraries\firebase-app-unity-4.0.3\libs\.\x86\libApp.so
processing archive E:\Backup\WorkShop\VRQuiz\Source\Unity\Temp\StagingArea\android-libraries\firebase-auth-11.0.4\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/ip.class...
processing com/google/android/gms/internal/iq.class...
processing com/google/android/gms/internal/ir.class...
processing com/google/android/gms/internal/is.class...
processing com/google/android/gms/internal/it.class...
processing com/google/android/gms/internal/iu.class...
processing com/google/android/gms/internal/iv.class...
processing com/google/android/gms/internal/iw.class...
processing com/google/android/gms/internal/ix.class...
processing com/google/android/gms/internal/iy.class...
processing com/google/android/gms/internal/iz.class...
processing com/google/android/gms/internal/ja.class...
processing com/google/android/gms/internal/jb.class...
processing com/google/android/gms/internal/jc.class...
processing com/google/android/gms/internal/jd.class...
processing com/google/android/gms/internal/je.class...
processing com/google/android/gms/internal/jf.class...
processing com/google/android/gms/internal/jg.class...
processing com/google/android/gms/internal/jh.class...
processing com/google/android/gms/internal/ji.class...
processing com/google/android/gms/internal/jj.class...
processing com/google/android/gms/internal/jk.class...
processing com/google/android/gms/internal/jl.class...
processing com/google/android/gms/internal/jm.class...
processing com/google/android/gms/internal/jn.class...
processing com/google/android/gms/internal/jo.class...
processing com/google/android/gms/internal/jp.class...
processing com/google/android/gms/internal/jq.class...
processing com/google/android/gms/internal/jr.class...
processing com/google/android/gms/internal/js.class...
processing com/google/android/gms/internal/jt.class...
processing com/google/android/gms/internal/ju.class...
processing com/google/android/gms/internal/jv.class...
processing com/google/android/gms/internal/jw.class...
processing com/google/android/gms/internal/jx.class...
processing com/google/android/gms/internal/jy.class...
processing com/google/android/gms/internal/jz.class...
processing com/google/android/gms/internal/ka.class...
processing com/google/android/gms/internal/kb.class...
processing com/google/android/gms/internal/kc.class...
processing com/google/android/gms/internal/kd.class...
processing com/google/android/gms/internal/ke.class...
processing com/google/android/gms/internal/kf.class...
processing com/google/android/gms/internal/kg.class...
processing com/google/android/gms/internal/kh.class...
processing com/google/android/gms/internal/ki.class...
processing com/google/android/gms/internal/kj.class...
processing com/google/android/gms/internal/kj$zza.class...
processing com/google/android/gms/internal/kk.class...
processing com/google/android/gms/internal/kl.class...
processing com/google/android/gms/internal/km.class...
processing com/google/android/gms/internal/kn.class...
processing com/google/android/gms/internal/ko.class...
processing com/google/android/gms/internal/kp.class...
processing com/google/android/gms/internal/kq.class...
processing com/google/android/gms/internal/kr.class...
processing com/google/android/gms/internal/ks.class...
processing com/google/android/gms/internal/kt.class...
processing com/google/android/gms/internal/ku.class...
processing com/google/android/gms/internal/kv.class...
processing com/google/android/gms/internal/kw.class...
processing com/google/android/gms/internal/kx.class...
processing com/google/android/gms/internal/ky.class...
processing com/google/android/gms/internal/kz.class...
processing com/google/android/gms/internal/la.class...
pr<message truncated>

**Comment by rusmaxham** [comment]
Some things to try:
• Upgrade to GoogleVR for Unity plugin v1.70
• Use Android API level 24
• If you're using Unity 5.6.x you'll need android-sdk-macosx-25.2.5 you can download the old version http://dl-ssl.google.com/android/repository/tools_r25.2.5-macosx.zip
• Make sure your Android dependencies (AARs / JARs etc.) are up to date.
• Delete Plugins/Android/
• Import the GVR and Firebase plugins again to restore what you deleted.
• Select "Assets > Play Services Resolver > Android Resolver > Resolve Client Jars"
