### ISSUE TITLE
When I switch mono screen mode to stereo mode, the gyo seems like works abnormally.

### ISSUE THREAD

**Issue by sccdhyt** [googlevr/gvr-unity-sdk#696]
I use the magical window mode to switch the mode.

> UnityEngine.VR.VRSettings.enabled = false;
Camera.main.GetComponent<Transform>().localRotation = UnityEngine.VR.InputTracking.GetLocalRotation(VRNode.CenterEye);

When I make the screen toward the horizontal direction, and switch from mono screen mode to stereo mode, it seems like works well.
But if not facing toward the horizontal direction, for example, if rotate the device a little down and switch, the target gameobject which should be right in front of camra will be over the camera. 
How can I solve it?

**Comment by fredsa** [comment]
After existing VR mode you may need to reset the camera aspect ratio ([Camera.ResetAspect](https://docs.unity3d.com/ScriptReference/Camera.ResetAspect.html)):

```C#
Camera.main.ResetAspect();
```

For a full example of switching between VR and non-VR mode, see https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime.

**Comment by sccdhyt** [comment]
@fredsa Thanks for you reply.
I had tried this example before, but when I switched to non-VR mode the camera can't rotate by rotating the device. I just want the result like this.
https://docs.unity3d.com/ScriptReference/Camera.ResetAspect.html
> Magic Window mode

Sometimes, you might want to apply a non-stereoscopic view with head tracking applied (for example, if you want to view a 2D image in VR, or provide a 2D preview of your VR application). This can be useful for promotional materials. To facilitate this, you can access head tracking data when VRSettings.enabled equals false and the VRSettings.loadedDeviceName is daydream or cardboard.

For example:

UnityEngine.VR.VRSettings.enabled = false;
Camera.main.GetComponent<Transform>().localRotation = UnityEngine.VR.InputTracking.GetLocalRotation(VRNode.CenterEye);

And ResetAspect() is reverting the aspect ratio to the screen's aspect ratio. I think it may not work to help me solving the problem of gyo.

**Comment by sccdhyt** [comment]
Maybe my description is difficult to understand, here is a gif to show my problem.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29728329/29648407-85981842-88c0-11e7-9ed4-e8b5809a88bf.gif)
When I switch from non-VR mode to VR mode, the position of the gameobject in the view of camera is irregular.

**Comment by fredsa** [comment]
Ah, I see. Thanks for the video.

You need to reset the camera rotation when you return to VR mode:

```C#
Camera.main.tanform.localRotation = Quaternion.Identity;
```

**Comment by sccdhyt** [comment]
@fredsa Thanks！ It works well now by using the code.
And another question, I just want to get the view of left and right camera when in VR
 mode. I had tried Camera.main but seems not work, Can you tell me the tag of the left and right camera?

**Comment by fredsa** [comment]
I think you want to use the `unity_StereoEyeIndex` shader constant, see https://docs.unity3d.com/Manual/SinglePassStereoRendering.html.

**Comment by fredsa** [comment]
Closing since everything is working.
