### ISSUE TITLE
Sdk will reset position of all cameras in scene

### ISSUE THREAD

**Issue by jayd16** [googlevr/gvr-unity-sdk#697]
The following code snippet from GvrControllerInput.cs is causing some headaches.   We can't have any custom cameras rendering to texture without having to worry about their rotation getting reset.  Any chance we can change this to ignore cameras with a stereoTargetEye set to None?

`  private void UpdateController() {
    controllerProvider.ReadState(controllerState);

#if UNITY_EDITOR
    // If a headset recenter was requested, do it now.
    if (controllerState.recentered) {
      for (int i = 0; i < Camera.allCameras.Length; i++) {
        Camera cam = Camera.allCameras[i];
        // Do not reset pitch, which is how it works on the device.
        cam.transform.localRotation = Quaternion.Euler(cam.transform.localRotation.eulerAngles.x, 0, 0);
      }
    }
#endif  // UNITY_EDITOR
  }`

**Comment by rusmaxham** [comment]
We have fixed this issue in the next release of the SDK.  You can safely remove the entire #if UNITY_EDITOR block in your local copy to work around the issue until the next release.
