### ISSUE TITLE
Asynchronous Reprojection causes wobble in Magic Window mode

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#700]
If the "daydream" device is loaded and Magic Window mode is enabled via VRSettings.Enabled = False then it will feel as though the screen has a wobble / jello effect.  This is due to the Asynchronous Reprojection, but the effect seems to be much worse in Magic Window mode vs. stereo VR mode. Maybe it's just due to VR mode also enabling the Low Persistence screen mode, but it's a very undesirable effect for my 360 Photo viewer use case. 

Have other people encountered this? Is there any known workaround? For my use case I'd actually just love to be able to disable Aynchronous Reprojection altogether, but for some reason this isn't allowed in Daydream. It feels like the simple solution is to just disable Aynchronous Reprojection when VRSettings.Enabled == False.

The above was tested in Unity 2017.1.0f3 on a Moto Z and Nexus 6P.

**Comment by dustinkerstein** [comment]
And further, I'm not quite sure I actually understand why I see this wobble effect in VR mode at all (though it is about 4x less severe compared to Magic Window mode). This VR mode wobble can easily be seen in any Daydream app when the phone is outside of the headset. Just give the phone a shake and you should see the black frames of the eye views wobble. Is this VR mode wobble by design? It just feels like the content being rendered inside of the eyes is 1 frame behind (or possibly more in Magic Window mode).

**Comment by nathanmartz** [comment]
The wobble is not a bug. You can't see it while in VR. The fact that you
can see it if you take the phone out of the viewer is a red herring. I
think the core issue is that you are using the GVR SDK for magic window and
it's not really meant for that.

On Aug 24, 2017 3:34 PM, "dustinkerstein" <notifications@github.com> wrote:

And further, I'm not quite sure I actually understand why I see this wobble
effect in VR mode at all (though it is about 4x less severe compared to
Magic Window mode). This VR mode wobble can easily be seen in any Daydream
app when the phone is outside of the headset. Just give the phone a shake
and you should see the black frames of the eye views wobble. Is this VR
mode wobble by design? It just feels like the content being rendered inside
of the eyes is 1 frame behind (or possibly more in Magic Window mode).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlevr/gvr-unity-sdk/issues/700#issuecomment-324775493>,
or mute the thread

**Comment by dustinkerstein** [comment]
K. I'll try Magic Window without any VR device loaded - though if that is the best solution,  it may be worth asking the Unity folks to update their docs and also updating the GVR wiki as I believe both say you can use Magic Window by just setting VRSetting.enabled = false (see step 5 here - 
https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime)

Also, just due to my curiosity,  do you know where I can find an explanation of that VR mode wobble?

**Comment by dustinkerstein** [comment]
So I've spent some time with various gyro/accelerometer scripts (one even with sensor fusion) but the accuracy and latency isn't even close to the performance of the native GVR orientation tracking. While calling VRSettings.LoadDeviceByName("") does solve the UX issues of the Daydream View interstitial (since it's no longer relying on GVR at all), it leaves me with a sub-par orientation tracking solution. 

In my mind, GVR really does need to properly support both VR and Magic Window modes, and the UX transition between them. Cardboard is meant to be the "bridge" into VR for many consumers, and one of the primary ways developers are going to accomplish this is through a Magic Window <-> VR user experience. There are many ways this could be handled (exposing GVR sensor data even when a GVR device isn't loaded, allowing the developer to disable the Daydream View interstitial, etc.) but as of right now in Unity 2017.1.0f3 and GVR 1.7, it's impossible to build a single app that can seamlessly transition between VR and Magic Window modes for both Cardboard and Daydream headsets while maintaining good orientation tracking. This seems like what everyone should be striving to build: a single app experience that works with Daydream, Cardboard, and Magic Window. Right?

Maybe I should create a new Github issue (closing #700, #701, and #702) that focuses on this particular UX. Does that sound like a good approach to discussing this?

**Comment by nathanmartz** [comment]
Having a single thread instead of three would definitely be good and keep
the discussion focused.

Regarding magic window and sensor fusion, I recommend you check out this
excellent article from Boris Smus. It even has source.
http://smus.com/sensor-fusion-prediction-webvr/

**Comment by dustinkerstein** [comment]
K, I will do that now. 

Yeah, that's a great resource, but IMO it would just be reinventing the wheel at this point. GVR has already essentially solved this problem. It's just not exposed in all cases where you want to use it.

**Comment by dustinkerstein** [comment]
Ok, I create #703 to track this UX discussion and closed the other two issues.

However, I'd like to keep this issue open, as it does seem like there is a bug with Magic Window mode + Daydream device. I'll just try to keep the discussion focused on that particular issue now. Sorry about the tangents.

**Comment by dustinkerstein** [comment]
I'm going to create a new issue to track this asynchronous reprojection wobble specifically in VR mode.
