### ISSUE TITLE
VRDevice.model is null unless VRSettings.enabled is True

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#701]
Apologies if this is more of a Unity issue vs GVR, but I figured I start here.

This likely is as designed, but it'd be very helpful to know what headset is configured even before enabling the VR mode. 

My particular usecase involves supporting both the Daydream View headset and other Cardboard headsets. I need to know if the "Please insert your phone into the Daydream headset" transition view is going to be prompted (which happens immediately after loading either the "daydream" or "cardboard" device if the headset had previously been set to "Daydream View") so that I force VR mode for these particular users. Otherwise they could select Magic Window mode on my app's splash screen (which then loads the "cardboard" or "daydream" device" and sets VRSettings.enabled = true|false), get presented the Daydream View transition screen, put their phone in their headset, and then drop back to Magic Window mode - a bad user experience. 

I could implement a workaround by cycling VRSettings.enabled and testing VRDevice.model, but this feels a bit hacky. [Edit/Update - Doh! This hack wouldn't even work as it would still pop up the transition screen]

Ideally I'd be able to control whether that Daydream View transition screen is shown at all, or if I could query VRDevice.model when VRSettings.enabled == false I could handle this case more gracefully.  
Any thoughts / suggestions would be appreciated.

**Comment by nathanmartz** [comment]
My recommendation is that you don't use the GVR SDK for magic window. Just
get the gyro data from unity and use it to rotate the camera. I think
that'll make your life much easier.

**Comment by dustinkerstein** [comment]
Thanks  I'll give that a try. That very well could avoid all of the issues noted in #700, #701, and #702. The only downside is that I won't be able to use the exact Google VR tracking implementation which I feel is likely the best available...

**Comment by dustinkerstein** [comment]
Yah, I have a feeling like that may not end up working well enough due to this post - https://forum.unity3d.com/threads/using-google-vr-head-tracking-without-activating-vrmode.484467/ - I'll try to find a good gyro sensor fusion script, but if that doesn't work out, can you think of any other possible solutions? I'd really still much prefer to use the camera tracking from Google VR if possible.

**Comment by fredsa** [comment]
> This likely is as designed, but it'd be very helpful to know what headset is configured even before enabling the VR mode.

At runtime you can iterate through [VRSettings.supportedDevices](https://docs.unity3d.com/ScriptReference/VR.VRSettings-supportedDevices.html) which is an array of all devices which are supported in the current environment.

Note:
* The None device is returned as an empty string: `""`
* Device names are returned lowercase: `"daydream"`, `"cardboard"`
* Device names are returned in the order set in Player Settings:
   **Player Settings > Android/iOS > Virtual Reality SDKs**

**Comment by dustinkerstein** [comment]
Hey @fredsa , I'm actually looking for the loaded headset (VRDevice.model) rather than the loaded / supported VR devices.

**Comment by dustinkerstein** [comment]
Closing this issue in favor of tracking in #703

**Comment by fredsa** [comment]
@dustinkerstein The `VRDevice.model` isn't available until the corresponding VR SDK / device has been loaded, because determining the device model is done by the VR SDK.

`VRSettings.supportedDevices` will tell you which VR SDKs can be loaded in the current environment, so it will tell you whether `"cardboard"` or `"daydream"` is supported (assuming you added the desired SDK(s) under **Player Settings > Android/iOS > Virtual Reality SDKs**).

**Comment by dustinkerstein** [comment]
It looks like VRDevice.model doesn't update when the user toggles between headsets using the VR services UX. You need to fully unload/reload the VRDevice itself, or restart the app. I tried waiting multiple frames with `yield return null` but it still doesn't return the current headset if it was changed during runtime. Do you feel like that's a bug? This would really be the only way I can effectively detect what headset a user has configured.

**Comment by fredsa** [comment]
Would you mind filing a new bug for the issue of `VRDevice.model` not updating itself after the VR SDK / device has been loaded? It's helpful if every issue only covers one subject.
