### ISSUE TITLE
Allow prevention of Daydream View transition screen

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#702]
I'm trying to handle both Daydream View and Cardboard headsets in a single Unity app (2017.1.0f3) and the "Please insert your phone into the Daydream View headset" is causing some UX troubles (see #701). Unity currently allows disabling the Cardboard headset transition screen (as a check box on the supported VR device list). Would it be possible to do the same for Daydream View headset? Or could the Daydream View headset just respect the Cardboard transition screen setting if the "cardboard" device is loaded instead of "daydream"? 

I'm just trying to find a clean way of building a UX that supports both Daydream View headset and Cardboard headsets in both VR and Magic Window mode. Any help would be appreciated.

**Comment by nathanmartz** [comment]
Can you give a bit more detail about how that screen is causing you trouble
on daydream? I can't think of any cases where you'd go from 2D into VR and
not need that screen, but would like to understand your specific case.

**Comment by dustinkerstein** [comment]
Sure thing. I'd like to start in 2D, present the user a choice of whether to stay in 2D (but maintain gyro camera) or go into VR mode. Selecting VR works just fine and the transition screen is beneficial. But when I select 2D (which loads the "cardboard" device and sets VRSettings.enabled = false) I still get that transition screen. 

I just saw your comment on #701 recommending to just use the gyro data directly in Unity (and loading "none" device). That may indeed solve my problems here as well. I'll give that a try tonight. Thanks!

**Comment by dustinkerstein** [comment]
Closing this issue in favor of tracking in #703
