### ISSUE TITLE
VRDevice.model doesn't reflect runtime changes after VR SDK/ device has loaded

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#704]
As discussed in #701 - It looks like VRDevice.model doesn't update when the user toggles between headsets using the VR services UX. You need to fully unload/reload the VRDevice itself, or restart the app. I tried waiting multiple frames with `yield return null ` but it still doesn't return the current headset if it was changed at runtime.

**Comment by fredsa** [comment]
Use case for app being notified of `VRDevice.model` changes:
1. User opens app
2. App starts up in VR mode
3. User changes the configured **VR Settings > Headset**

**Comment by dustinkerstein** [comment]
Just wanted to check in on this one.  Anything I can help with?

**Comment by fredsa** [comment]
Unfortunately, switching VR devices at runtime is not supported.

Workaround: Quit the application, then change VR Settings configured device, then restart the app.
