### ISSUE TITLE
How to use code to modify VR camera parameters?

### ISSUE THREAD

**Issue by hejiang123** [googlevr/gvr-unity-sdk#707]
Hello, because there are special requirements.Now I need to use the code were about to adjust the parameters of the camera to achieve the ideal effect about differences.But now after release to the android device.Use the code can't find the two cameras.What is the right way to modify?

**Comment by nathanmartz** [comment]
I'm not sure I understand your question. Are you asking how you can add
support for phones that are not officially supported? Or are you asking how
to render in a way that looks correct on both Pixel and S8?

**Comment by hejiang123** [comment]
My purpose is to set different parameters for around two cameras.To achieve the effect of two eyes see is not the same.But I use on a real machine code GameObject. FindObjectsOfType < Camera > ();It also can find the main camera.But can't find around the eye camera.How I need to get these two cameras Transform to modify the parameters of the camera?

**Comment by nathanmartz** [comment]
You want to create two cameras and set the [stereoTargetEye](https://docs.unity3d.com/ScriptReference/Camera-stereoTargetEye.html) to left for one and right for the other.
