### ISSUE TITLE
Black VR screen with Mali GPU and Single Pass Rendering

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#709]
_Update - See last comment. This isn't actually related to Single Pass Rendering at all._

Tested in Unity 2017.1.0p5 on a Huawei P10 (Mali G71 GPU).

These errors flood when the "cardboard" device is loaded and VRSettings.enabled is set True:

```
09-02 12:31:06.417 13545-13592/? E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is not complete or incompatible with command
                                          
                                          
                                          [ 09-02 12:31:06.421 13545:13592 E/         ]
                                          mali gles error info : 95
                                          
                                          [ 09-02 12:31:06.439 13545:13592 E/         ]
                                          mali gles error info : 95
```

When these errors happen the screen is black but in the VR mode. Things work as expected when Multi Pass Rendering is set.

Not sure if this is more of a Unity bug or GVR. Happy to close this one here and post on Unity if that's the better place.

**Comment by dustinkerstein** [comment]
Closing this as I think I have isolated it to a commit that changed how I was handling setting VRSettings.enabled

**Comment by dustinkerstein** [comment]
So it wasn't how I was setting VRSettings.enabled, but I am still not quite sure why I'm not longer able to consistently replicate this. Anyway, leaving it closed.

**Comment by nathanmartz** [comment]
Thanks for the bug report. We've reproduced this internally and will disable support for single pass on these GPUs as well as on cardboard generally (given overall driver maturity for this feature). Unity will automatically fall back to multi-pass rendering once this update is out when run on these devices.

**Comment by dustinkerstein** [comment]
Ok cool. I just re-tested again and it doesn't seem related to AA. Not sure what was going on in my Unity project. I'll go ahead and rename this issue back to its original since you say it was indeed a bug with single pass rendering.

**Comment by maskedmous** [comment]
It happens in our project as well. We made a workaround for the OpenGL error by first waiting until the screen orientation is in landscape mode and then activate VR. Having the screen in portrait orientation and setting the orientation to landscape left then activate VR in a line after setting the orientation will result in the Open GL error.
I've already made a small project that reproduces the issue and is sent to unity QA (Case 948055).

I ain't a 100% sure what causes this bug, but it doesn't seem to be AA / Single Pass in our project. We've tried many settings but never really fixed the issue. Instead we wrote the workaround which did the trick.

Google VR has a lot of weird bugs in combination with several settings it seems. It is just not clear which settings are causing the problems.

**Comment by MRxRadex** [comment]
@maskedmous can you share your thoughts, or maybe code, about workaround for fixing this issue?
Thanks you.

**Comment by maskedmous** [comment]
Basically what you need is a script that extends UIBehaviour, attach it to an overlay canvas and override OnDimensionsChanged method. When you want to activate VR first set landscape left, wait till OnDimensionsChanged is called and then activate VR.

(We did this by using a static UnityEvent, when OnDimensionsChanged is called we invoke this event which a method is subscribed to activate VR)

**Comment by MRxRadex** [comment]
@maskedmous Thank you very much for your answer!

**Comment by dustinkerstein** [comment]
Upon a little more testing on a Samsung S6 and S8 (Mali version), this actually does seem to be related to both Single Pass Rendering and Anti Aliasing. If AA is disabled when Single Pass Rendering is enabled, these errors will appear and VR mode will be broken. Enabling AA prevents this from happening.

**Comment by dustinkerstein** [comment]
@nathanmartz Do you know if this fix is going to be on the Unity side, or within Google VR Services?

**Comment by nathanmartz** [comment]
Unfortunately single pass rendering just doesn't work reliably on those devices. We're going to release an update to the SDK and VRCore that disables single pass on devices that we know can't support it robustly.

**Comment by dustinkerstein** [comment]
@nathanmartz ok, so that means the fix will be in a future Unity release rather than Google VR Services, correct?

**Comment by nathanmartz** [comment]
Both, actually.

**Comment by dustinkerstein** [comment]
@nathanmartz Interesting. Will both the Unity fix and Google VR Services fix address the issue independently, or will it actually require both components in order to fix it at all?

**Comment by nathanmartz** [comment]
VRCore will fix daydream apps and cardboard apps where VRCore is installed.
To fix all cardboard apps you'll need a unity update.

-Nathan
