### ISSUE TITLE
GvrReticlePointerImpl and GvrReticlePointerImpl missing from version 1.70

### ISSUE THREAD

**Issue by radicalappdev** [googlevr/gvr-unity-sdk#710]
The scripts GvrReticlePointerImpl and GvrReticlePointerImpl are missing from version 1.70.

There is nothing in the release notes to indicate that these files were replaced or renamed: https://developers.google.com/vr/unity/release-notes

Both scripts are still listed in the documentation.
https://developers.google.com/vr/unity/reference/class/gvr-laser-pointer-impl
https://developers.google.com/vr/unity/reference/class/gvr-reticle-pointer-impl

**Comment by dsternfeld7** [comment]
In version 1.70, the functionality of GvrReticlePointerImpl and GvrLaserPointerImpl was merged into GvrReticlePointer and GvrLaserPointer respectively.

We will look into the issue with the documentation.

Thank you!

-Dan

**Comment by dsternfeld7** [comment]
Documentation has been updated.

Thanks!
