### ISSUE TITLE
GVR reports logcat msg for noisy connection to Controller

### ISSUE THREAD

**Issue by reed-alpert** [googlevr/gvr-unity-sdk#713]
I'm running my Unity Daydream app [Spin Paint](https://play.google.com/store/apps/details?id=com.spinpaint.spinpaint) and sometimes have a non-responsive controller, resulting in jerky movement. The logcat shows messages like this:
> 09-03 16:08:13.481  2226 17311 W bpm     : Experiencing large gap between controller packets in controller driver: last packet timestamp: 595881838, packet timestamp: 595882153, diff: 315 in ms.

Pid 2226 is:
> u0_a76    2226  636   1890312 72604 SyS_epoll_ 0000000000 S com.google.vr.vrcore

In general the timestamp diff is around 300 - 500 msec.
Logcat file attached, these msgs start at line 3718.
It is not associated with a specific temperature threshold.
The Controller battery is Full.
I see it on my Pixel XL often, and occasionally on my Moto.

Do you have an idea what could be causing this?

Unity 2017.1.0p5 / IL2CPP
GVR Unity SDK 1.60
Daydream Renderer 1.0
Android NDK r10e
Google Pixel XL, Android 7.1.2
Moto Z Force Droid, Android 7.1.1

Thanks,

Reed.

[controller.txt](https://github.com/googlevr/gvr-unity-sdk/files/1273220/controller.txt)

**Comment by nathanmartz** [comment]
Are you running any other Bluetooth devices at the same time, like
Bluetooth headphones?

**Comment by reed-alpert** [comment]
No Bluetooth headphones. I do have 2 phones (Pixel XL & Moto) for testing my Daydream app, but they are paired to different Controllers. Could the phone be scanning for Bluetooth devices in my apt building and getting congested?

**Comment by nathanmartz** [comment]
It's possible but unlikely. Maybe there is just a ton of RF noise in your
apartment (lots of wifi from neighbors, etc)?

**Comment by reed-alpert** [comment]
I am in NYC, and can see 25 wireless devices from where I am. But I see this more with my SpinPaint app and not so often with the StreetView or Art&Museum apps. It does clear after 2 - 5 minutes, so maybe it is just transient background noise. Do you know of an Android app that can measure/track RF noise? Didn't see one in the PlayStore.

**Comment by fredsa** [comment]
After discussing in person we determined that this is very likely environmental interference given that the same issue occurs with different apps, and separately on two different mobile phones.
