### ISSUE TITLE
D/AndroidNCompat: VR mode is not supported on this N device.

### ISSUE THREAD

**Issue by gerardreches** [googlevr/gvr-unity-sdk#715]
Using a device with android version 7.1.1 shows me this message in the logcat after closing my cardboard GVR app:

```
09-06 13:46:09.873 20302-20302/com.my.app I/Unity: setVrEnabled : VR State [ a=true, b=true, c=false, d=false, e=false, f=false, g=com.unity3d.player.GoogleVrProxy@e964f25,]
09-06 13:46:09.874 20302-20302/com.my.app D/AndroidNCompat: VR mode is not supported on this N device.
09-06 13:46:09.875 20302-20302/com.my.app I/Unity: pauseGvrLayout : VR State [ a=true, b=true, c=false, d=false, e=true, f=false, g=com.unity3d.player.GoogleVrProxy@e964f25,]
09-06 13:46:09.886 20302-20302/com.my.app D/Unity: SetWindow 0 0x0
09-06 13:46:09.901 20302-20302/com.my.app I/Unity: Enable VR : VR State [ a=true, b=true, c=false, d=false, e=true, f=false, g=com.unity3d.player.GoogleVrProxy@e964f25,]
09-06 13:46:09.917 20302-20302/com.my.app I/Unity: unloadGoogleVr : VR State [ a=false, b=false, c=false, d=false, e=true, f=false, g=com.unity3d.player.GoogleVrProxy@e964f25,]
```

Using `GVR Unity SDK Version: 1.60.0` and Unity 2017.1.1f1

**Comment by nathanmartz** [comment]
What phone are you using? Not all Android N phones are Daydream/VR ready.

**Comment by nathanmartz** [comment]
BTW - If you are only building for cardboard and there are no actual errors, these logs are likely harmless.

**Comment by gerardreches** [comment]
@nathanmartz I'm using a One Plus 3T updated to OxygenOS v4.1.7 (Android 7.1.1), but I also have a Samsung Galaxy S7 for testing purposes. The S7 has Android 7.0 and a different log:

```
09-06 16:15:51.905 11621-11621/com.my.app W/AndroidNCompat: No VR service component: android.content.pm.PackageManager$NameNotFoundException: com.google.vr.vrcore/com.google.vr.vrcore.common.VrCoreListenerService
```

@nathanmartz Yes, I'm only building for cardboard, but there are errors that doesn't appear on each execution, just sometimes. When the error appears, I get this stacktrace at each frame:

```
09-06 16:44:21.736 6230-6273/com.my.app E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is not complete or incompatible with command
                                                                     
                                                                    (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 375)
09-06 16:44:21.751 6230-6273/com.my.app E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is not complete or incompatible with command
                                                                     
                                                                    (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 370)
```

**Comment by nathanmartz** [comment]
Do you have single pass rendering enabled? If so, disabling it should fix
those errors.

**Comment by gerardreches** [comment]
@nathanmartz It's using **Stereo Rendering Method** with *Multi Pass* option.

**Comment by behisoft** [comment]
@gerardreches were you able to fix the error? I'm having the same problem with GVR 1.7 in Unity 2017.1.1.

**Comment by rusmaxham** [comment]
Are you still experiencing this issue?  If so, can you try with the latest release [v1.110](https://github.com/googlevr/gvr-unity-sdk/releases)?

**Comment by rusmaxham** [comment]
If you are still experiencing this issue, please reopen.

**Comment by zulman** [comment]
Hello guys,

The same issue on Nexus 6P. Cardboard + Multipass + Unity 564p3.

**Comment by rusmaxham** [comment]
What version of the SDK are you using?  Can you post a logcat snippet of the error and 10-20 lines before it?

**Comment by zulman** [comment]
Hello @rusmaxham. 1.110 SDK. It's very strange because the error appears only when there are no cameras on the scene. I found an old bug, fixed and now everything is good.

**Comment by rusmaxham** [comment]
Happy to hear everything is good now.
