### ISSUE TITLE
Head tracking - Camera position reset - GvrEditorEmulator incoherences with UnityEngine.VR InputTracking: Unity Game preview differs to compiled app

### ISSUE THREAD

**Issue by chelder86** [googlevr/gvr-unity-sdk#716]
**ISSUE 1:**

I have been able to disable partially head tracking with the code:             `VRDevice.DisableAutoVRCameraTracking(Camera.main, true);` (https://docs.unity3d.com/ScriptReference/VR.VRDevice.DisableAutoVRCameraTracking.html). However:

- I have not found how to disable it in the Unity Game preview. I guess the class to do it is GvrEditorEmulator.cs.
- It does not work in the following case (my guess is that the coroutine enable the head tracking after been disabled in the Awake function):
```
void Awake{
  StartCoroutine(SwitchToVR()); /* Code here: https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime */
}
void Start (){
   VRDevice.DisableAutoVRCameraTracking(Camera.main, true);
}
```

By the way, the music is broken during around a second. It did not happen before updating.

**ISSUE 2:**

The position of the camera changes to (0, 0, 0.08) on the Unity Game preview. It works well (position does not change) on the compiled game.

My guess is that GvrEditorEmulator is a workaround and eventually it won't exist because it will be integrated into Unity3D. I don't find much sense to have repeated the code `#if UNITY_ANDROID && !UNITY_EDITOR` everywhere and obligate developers to discover how to code stuff two times: first for Unity and second for the actual video game!

**Comment by fredsa** [comment]
> I have not found how to disable it in the Unity Game preview. I guess the class to do it is GvrEditorEmulator.cs.

`GvrEditorEmulator` is designed to emulate the on-device runtime behavior when running in VR mode. It's not designed to handle If you're trying to run you in non-VR mode, you can disable or remove the `GvrEditorEmulator` script component from the scene.

> By the way, the music is broken during around a second. It did not happen before updating.

Switching between VR and non-VR modes requires an expensive state change since the rendering pipeline is different. You might want to consider fading the music out, and back in, together with a fade to black for the display, when switching modes.

> The position of the camera changes to (0, 0, 0.08) on the Unity Game preview. It works well (position does not change) on the compiled game.

You're seeing the emulator neck model due to this constant in `GvrEditorEmulator`:

```C#
  private static readonly Vector3 NECK_OFFSET = new Vector3(0, 0.075f, 0.08f);
```

**Comment by chelder86** [comment]
@fredsa thanks for your solutions! A couple of 

> GvrEditorEmulator is designed to emulate the on-device runtime behavior when running in VR mode. It's not designed to handle If you're trying to run you in non-VR mode, you can disable or remove the GvrEditorEmulator script component from the scene.

I need to use `GvrEditorEmulator`. Otherwise I must compile each time I want to try the result because I cannot move the camera without it. 

I want to emulate VR. Unfortunately Unity does not seem to be able to emulate VR anymore. If I do: `StartCoroutine(SwitchToVR());`, I got the warning: _VRDevice cardboard not supported in Editor Mode.  Please run on target device_. That's why I have surrounded the code with:

```
#if (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
StartCoroutine(SwitchToVR());
#endif  // (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
```

Do you mean the best solution right now would be something like the following?

```
	private void TrackPositionAndRotation (bool track){
		if (track) {
			#if UNITY_EDITOR
			FindObjectOfType<GvrEditorEmulator>().enabled = true;
			#endif  // UNITY_EDITOR

			#if (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
			VRDevice.DisableAutoVRCameraTracking(Camera.main, false);
			#endif  // (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR

			//cardboardHead.GetComponent<GvrHead>().trackPosition = true;
			//cardboardHead.GetComponent<GvrHead>().trackRotation = true;
		} else {
			#if UNITY_EDITOR
			FindObjectOfType<GvrEditorEmulator>().enabled = false;
			#endif  // UNITY_EDITOR

			#if (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
			VRDevice.DisableAutoVRCameraTracking(Camera.main, true);
			#endif  // (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR

		    //cardboardHead.GetComponent<GvrHead>().trackPosition = false;
			//cardboardHead.GetComponent<GvrHead>().trackRotation = false;
		}
	}
```

> You're seeing the emulator neck model due to this constant in GvrEditorEmulator:

Observing the scene GVRDemo, I think the way to move the position of the camera is creating a parent object to change the position of the parent instead of the camera.


> Switching between VR and non-VR modes requires an expensive state change since the rendering pipeline is different. You might want to consider fading the music out, and back in, together with a fade to black for the display, when switching modes.


Clear. Thank you!

**Comment by fredsa** [comment]
Looks okay to me for both ideas:
1. Don't try to load "daydream" or "cardboard" device when running in the editor, so skip starting `SwitchToVR()` coroutine
1. Only enable `GvrEditorEmulator` script component when you want to emulate VR mode in editor

**Comment by adarshk007** [comment]
your issue 2:

maybe it is coming because of gvrControllerMain,if you are using this in your game . I was also facing the same problem then I encountered this issue716 then I removed the gvrControllerMain. Now,camera started changing its position.
