### ISSUE TITLE
Unity5.6.0/iOS/v1.70/iPhone7P  FPS always keep 30, UI ghost image(afterimage), UI draw the incoherence

### ISSUE THREAD

**Issue by biezhihua** [googlevr/gvr-unity-sdk#718]
HI:

I create a new demo project, and import the new latest sdk( 1.70 )  in the iOS platform.

All project settings use the default setting, i don't change anything except the company and Virtual Reality Supported.

<img width="417" alt="wx20170907-100807 2x" src="https://user-images.githubusercontent.com/6761107/30142686-ba354b0c-93b4-11e7-8a96-e43137bc8ccc.png">

There were some serious issue , when I into the VR mode. 
- FPS always keep 30.
- The slow move the iPhone(Cardboard mode) can clearly see the ghost image (or afterimage)
- The slow move the iPhone(Cardboard mode) can clearly fell the  UI draw the incoherence

![141504750342_ pic](https://user-images.githubusercontent.com/6761107/30142752-10e30a2a-93b5-11e7-91fd-b6f192e4ba28.jpg)

![131504750334_ pic](https://user-images.githubusercontent.com/6761107/30142787-31c429ae-93b5-11e7-83d8-8c317a816812.jpg)

Please anyone meet the same issue?

**Comment by nathanmartz** [comment]
Phones always vsync so if you're not hitting 60fps you'll vsync down to
30fps. That part is expected.

What do you mean by "incoherent" and "residual" UI?

**Comment by biezhihua** [comment]
Thank your reply!!

The incoherent mean that slow move the iPhone(Cardboard mode) can clearly feel the UI draw the incoherence.

The residual mean that The slow move the iPhone(Cardboard mode) can clearly see the ghost image (or afterimage).

At first I thought the frame rate was too low to cause these issue.

Looking forward your reply.

@nathanmartz

**Comment by nathanmartz** [comment]
From what I can tell, higher framerate will help a bit, but these are all expected on Cardboard (iOS and Android). Cardboard is designed to give reasonable quality, short VR sessions to the widest possible audience. If you want an experience with lower latency, better tracking, no ghosting, etc. then you should look to Daydream.

**Comment by zhuyifan2013** [comment]
@nathanmartz  But I could hot 60 fps using older version , I think using Daydream is not a proper way to solve this problem...
