### ISSUE TITLE
Does gvr use the magnetometer (compass) to correct drift?

### ISSUE THREAD

**Issue by chidl003** [googlevr/gvr-unity-sdk#721]
We have been using gvr1.0 GvrViewer.Instance.HeadPose.Orientation to get the orientation of mobile devices but are experiencing drift in the heading (yaw).  We were experimenting with adding our own compass correction on top of gvr but were wondering if you already do this and if not why?Does gvr1.7 improve this drift significantly over 1.0?

**Comment by nathanmartz** [comment]
We are steadily improving our drift correction algorithms, both by improving the quality of the filters and adding new sensors (like magnetometer). In the case of the mag, this is only supported for Daydream ready devices, as there's quite a bit of variance between different versions of a given kind of sensor, and it's easy to wind up adding noise that makes your drift worse.

**Comment by chidl003** [comment]
When do you plan to incorporate mags for drift correction on newer iPhones?  We are working on a high profile AR app at Disney due to ship soon but drift on iPhones is a huge concern.
