### ISSUE TITLE
Performance Improved a lot.

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#722]
I compared the cardboard VR performance using two unity versions: Unity 5.5.3.f1(Gvr 1.4) and Unity 5.6.0f.3(Gvr 1.4).

Cardboard is native integrated in Unity 5.6.0f3. I found the performance improved a lot in Unity 5.6.0f.3 compared to unity 5.5.3.f1.  I tested on an Android phone using a unity scene. The cardboard app complied with Unity 5.6.0.f3 use less GPU. 

I want to know what measures have you taken in Unity 5.6.0.f3 to improve cardboard app performance.
What about the performance of Unity 2017.1 compared to Unity 5.6.0.f3?

**Comment by nathanmartz** [comment]
You'd have to make sure that the 5.5 and 5.6 versions are both rendering to the same sized framebuffer. If they aren't that could account for the difference. If they are, you're probably seeing general optimizations unity makes that we are better able to leverage using the native integration.

I would not expect any performance changes specific to Google VR going from 5.6 to 2017, but of course various parts of Unity get faster and slower.

**Comment by clarkehe** [comment]
@nathanmartz  Got it. Thank you.  I debug the rendering progress using Snapdragon Profiler and found the difference. The main difference is post process in StereoRenderEffect.cs was removed. Left and Right eye RenderTexture are used to create distorted texture directly. In Unity 5.6 post process(OnRenderImage) was changed. A full screen texture will be created and rendered twice.
