### ISSUE TITLE
Extending com.google.unity.UnityPlayerActivity for Android Plugin

### ISSUE THREAD

**Issue by OrtOfOn** [googlevr/gvr-unity-sdk#723]
Hi,

Is there a way to extend this Android Activity?
Can we have access to the classes.jar of the GoogleVR SDK?

I would like to develop a android plugin that extends Extending com.google.unity.UnityPlayerActivity because my plugin has to be the main activity.

Thank you for your response.

Q.

**Comment by nathanmartz** [comment]
You should use unity 5.6 or later, which has a native integration and
removes the need for a Google unity activity entirely.

**Comment by OrtOfOn** [comment]
Same with 2017.1 ?

**Comment by nathanmartz** [comment]
Yes. 2017.1 is later than 5.6.

**Comment by OrtOfOn** [comment]
Thank you for your quick feedback.
