### ISSUE TITLE
"daydream" VR device doesn't load on Android Oreo 8.0.0

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#724]
This is likely more of a Unity issue (I just filed [here](https://fogbugz.unity3d.com/default.asp?951062_82a7h28n6i2ilnh1)) but I figure it would be idea to get folks aware here given that it could be a higher priority issue since Google recently rolled out Oreo OTA to all Pixel phones.

It appears that the "daydream" VR device fails to load on Android O (tested so far on Nexus 6P). This prevents Asynchronous Reprojection from working and causes other issues. 

```
09-14 15:08:58.586 12044-12044/? E/Unity: Error Enabling Async Projection. Aborting load operation.
09-14 15:08:58.586 12044-12101/? E/Unity: Google VR Error [Daydream]: Google VR had a fatal issue while loading. VR will not be available.
```

To reproduce, add the "Daydream" as the only device in the Supported VR device list and start the app.

Tested in Unity 2017.1.1p1 and 2017.2.0b11 with a Nexus 6P. This does not happen on Nougat 7.1.2

Has anyone else seen this? I've tested one other Unity based daydream app and it behaves the same way, but my Nexus 6P won't open most Daydream apps and can't run the Daydream store so I can't test that many.

I will be trying to test on a Pixel later tonight, though I've already gotten verbal confirmation from a friend who owns a Pixel on Android O that they don't see the Asynchronous Reprojection wobble (see #706) working on the apps they've tried.

**Comment by nathanmartz** [comment]
This is actually expected. The 6P is not, technically, a Daydream ready device. It had to be flagged that way during pre-release development (it was our devkit), but it's no longer flagged as Daydream Ready in O.

**Comment by dustinkerstein** [comment]
Ah ok. Sorry for the false alarm. I guess my friend with the Pixel was mistaken.
