### ISSUE TITLE
iOS Cardboard freeze after viewer profile set

### ISSUE THREAD

**Issue by delphinius81** [googlevr/gvr-unity-sdk#725]
Issue:
I'm experiencing an application hang using Unity 2017.1.1p1 when targeting iOS with cardboard. Attempted this on an iPhone 6 running the iOS version 10.3.3. After scanning the QR code for my viewer and tapping ok, when focus returns to my application, the application hangs. There is no obvious error output in Unity/XCode. The crash log indicates that the application has crashed somewhere in the main thread, but the log itself isn't all that enlightening (see attached crashlog.txt).

Trying to start the application again just results in a black screen. The Unity splash screen never appears.

Now for the _really_ weird part. I have another application on my phone, also built in 2017.1.1p1 with the same signing profile and first two parts of the bundle identifier (e.g. com.mycompany.app1 and com.mycompany.app2). The second app also will also hang when trying to enter VR.

This issue occurs whether I start the app in 2D mode and manually transition to VR, or if I start directly in VR. As soon as you use the camera to scan a viewer profile, the application will hang and never start again.

Steps to Reproduce:
Create a new project in Unity 2017.1.1p1.
Add gvr for unity package v1.7
Switch to iOS build
Open the GVRDemo scene included in the gvr package and include in build settings
Enable VR and set Cardboard as the VR device
Build and Run
Tap gear to change viewer profile, accept camera permission
Scan any viewer QR code, hit ok
App will return to Unity and hang

[crashlog.txt](https://github.com/googlevr/gvr-unity-sdk/files/1304802/crashlog.txt)

**Comment by tedruxpin** [comment]
Hello delphinius81,

I've reported your issue to our development team and we will try to get you an answer as soon as possible.  In the meantime, are you able to create a development build that might provide a more detailed crashlog?  And are you using an unusual viewer, or are you able to include a photo of the QR code?  Thank you!

**Comment by delphinius81** [comment]
I've had it happen with a variety of QR codes. One of them is found at: http://www.sitesinvr.com/viewer/boboz4/index.html
Also with the QR code generated by the viewer profile generator using: http://google.com/cardboard/cfg?p=CghGZWFybGVzcxILRmVhcmxlc3MgWjQdl9snPSWPjYA9KhDsAz1C7AM9QuwDPULsAz1CWAE1KVwPPToIj8J1PZqZmb5QAGAD

As for a build with more details, I'm already building the Unity side as a development build and xcode in Debug. Is there a specific logging setting I should enable?

**Comment by Arvin6** [comment]
I have this problem too. Would love to find a way to handle this.

**Comment by delphinius81** [comment]
Trying to set the default profile also results in a hang for me, so that's not an option. (I made the __Internal dll name change for iOS to enable the SetViewerProfile function call.) The only way my app will run is if it uses the default carboard profile and it's never changed.

In fact, further testing today revealed that I can't get the app to launch into VR mode on a second run through even when I make no attempt to change the viewer profile. The application locks up when transitioning to VR mode. The following error shows in xcode log after I initiate the transition:

NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)

However I have no idea what is making this call.

**Comment by nathanmartz** [comment]
@delphinius81, pairing a viewer requires talking to a web service to get the configuration data. Does your test device not have internet access?

**Comment by delphinius81** [comment]
The device has internet access (pairing the viewer works fine using the Cardboard app). I have allow http download enabled through Unity settings for my app.

But I will experience a hang on a second attempt to run my application. This is very possibly a second issue that I've discovered with 2017.1.1p1 (which uses the 1.80 NDK).

I do not call SetViewerProfile in code. I do not tap the settings icon to change the viewer profile through the camera. I launch the app the first time, get it to launch into VR mode, then quit the app. I launch the app again, it hangs when transitioning to VR mode and I see the HTTP load failed error.

**Comment by delphinius81** [comment]
The second run bug appears to go back several versions of 5.6 as well (5.6.1p4, 5.6.3p2, 5.6.3p3) and 2017.1.0p5. I went back to try versions with different gvr ndk versions.

Created a simple scene - just a camera and cube. No scripts added. No packages imported. Cardboard set as target vr device.

Both mentioned issues appear:
1) Hang when attempting to change QR code.
2) App hangs on launch (never loads the Unity splash screen) on a 2nd play attempt.

**Comment by fredsa** [comment]
Using iPhone 6s (A1687) running iOS 11.0, and using Xcode, Version 9.0 (9A235):
* Unity 5.6.3p3 -> Unable to reproduce
* Unity 2017.1.1p1 -> Unable to reproduce

In both cases scanning QR codes works correctly.
I used the GVRDemo scene from GVR SDK 1.70.

Is there anything else about your project that's different?

**Comment by delphinius81** [comment]
I'm thinking that it might have been due to the QR code that I generated from https://vr.google.com/cardboard/viewerprofilegenerator/. Any idea why a QR code would crash the app?

**Comment by fredsa** [comment]
Here's the QR code I made using your config. It does not crash for me.
![qr_viewer_profile](https://user-images.githubusercontent.com/1235362/31024179-151a59a0-a4f3-11e7-8f20-3ce1915150cb.png)

**Comment by delphinius81** [comment]
That QR code works (in that the app does not crash), but it results in a complete lack of lens distortion. The left/right images are rendered completely square, so either the code lacks any parameters, or something is ignoring them.

I've tried to create additional QR codes with different names/parameters, and they all come up when scanned as being "z4" viewer and then freeze my application (though they seem to scan fine in the published iOS cardboard app on the app store).

I can scan other QR codes for this device (found at https://www.reddit.com/r/GoogleCardboard/comments/4i17vu/lets_compare_viewer_profile_values_for_the_bobovr/) just fine.

This is striking me as something wrong with 1) the version of the currently live version of the profile generator or 2) how new QR codes are processed in the latest ios cardboard sdk.

**Comment by fredsa** [comment]
@delphinius81 Can you attach a clear image of the your viewer's QR profile?

**Comment by delphinius81** [comment]
Sure. Following is the image that is generated.
![fearlessz4viewerprofile](https://user-images.githubusercontent.com/4960109/31243119-15e545d2-a9be-11e7-81fc-bd010e3594d8.png)

It uses the following parameters:
Company Name: Fearless
Device Name: FearlessZ4
Screen to lens distance: 38
Inter-lens distance: 60
Button type: Indirect Touch
Screen Vertical Alignment: bottom
Tray to lens center distance: 38
Distortion k1: .2
Distortion k2: .05
FOV angles: all set to 50

Save/Load parameters URI is: http://google.com/cardboard/cfg?p=CghGZWFybGVzcxICejQdl9snPSWPjYA9KhDsAz1C7AM9QuwDPULsAz1CWAE1KVwPPToIj8J1PZqZmb5QAGAD

**Comment by fredsa** [comment]
That QR is indeed bad, as is the URL. If you try loading it, you'll see that the parameter are not the ones you've listed.

If I retype the parameter you've listed I get:
http://google.com/cardboard/cfg?p=CghGZWFybGVzcxICejQd46UbPSWPwnU9KhAAAEhCAABIQgAASEIAAEhCWAA146UbPToIzcxMPs3MTD1QAGAD
![z4](https://user-images.githubusercontent.com/1235362/31253758-e755768e-a9da-11e7-85f7-f28a39cb6c92.png)

**Comment by delphinius81** [comment]
So basically the profile generator is broken for me then? I entered in those parameters from a blank form, and it generated a broken QR code.

If I attempt to load the viewer parameters using the link you give, but I change the viewer name, I end up with a QR that is bad as well. Is https://vr.google.com/cardboard/viewerprofilegenerator/ just broken or something?

**Comment by fredsa** [comment]
I'm using Chrome: 61.0.3163.100 (Official Build) (64-bit)

**Comment by delphinius81** [comment]
Same here. Version 61.0.3163.100 (Official Build) (64-bit). Using Safari seems to work though.

I can load the viewer parameters from your QR code, change the viewer name, and the code is successfully loaded.

Guess I can try incognito mode in Chrome, maybe some extension I'm running is interfering somehow.

**Comment by delphinius81** [comment]
Hmm, everything loads fine when using an incognito browser tab. Must be an extension messing with the javascript somehow.

I guess this issue is resolved as much as need be, though I'd suggest improving the UX for when a bad QR code is scanned/provided. Ideally, if the user scans a bad code, that would be detected and discarded, and the last known good or default values would be used instead, with some kind of warning for the user to try a different code.

**Comment by fredsa** [comment]
Glad we got it resolved.

Viewer profiler and QR code creation are advanced features, not intended to be used by most developers. In fact, it's intended mainly to be used by viewer manufacturers.
