### ISSUE TITLE
Cannot get viewpoint to change

### ISSUE THREAD

**Issue by Jadiker** [googlevr/gvr-unity-sdk#726]
When I run my app in Unity with GVRControllerMain and GVREditorEmulator, everything seems to work great. My camera follows the player, and I can move around the world.

As soon as I upload it onto my iPhone, the main camera no longer follows the player, as if some script continuously is resetting the camera's position. (See [this post](https://stackoverflow.com/questions/46229059/getting-movement-with-google-cardboard-in-unity) for more detail.)

It seems like it may be related to [another issue](https://github.com/googlevr/gvr-unity-sdk/issues/606) that was posted earlier, but the potential (and slightly sketchy) fix for that issue does not seem to work for me here.

How can I get it so my camera follows the player with Google Cardboard?

**Comment by nathanmartz** [comment]
You just need to make the node that follows the player a parent of the camera, not the same game object as the camera.
