### ISSUE TITLE
VR mode is not supported on Asus Zenfone 2 ZE551ML

### ISSUE THREAD

**Issue by IndraYudha** [googlevr/gvr-unity-sdk#728]
VR mod is not supported on Asus Zenfone 2 ZE551ML, Using GVR Unity SDK Version: 1.70.0,
How to Fix ? 

Help me. Thanks

**Comment by nathanmartz** [comment]
The Zenphone 2 is not a [Daydream Ready phone](https://vr.google.com/daydream/smartphonevr/phones/), so it can only run app sin cardboard mode.
