### ISSUE TITLE
GVR changing camera projection and has collision with ARkit on unity

### ISSUE THREAD

**Issue by Arvin6** [googlevr/gvr-unity-sdk#729]
GVR seems to change the projection matrix of the camera when enabling VR mode and doesn't work well with ARkit plugin for unity. This happens because ARkit changes the projection matrix of the camera to map the virtual object onto the camera feed, this seems to collide with GVR. Is there any way to disable that? I've looked into the source code but couldn't find which part is responsible for changing projection matrix for camera. The video feed on AR mode is absolutely fine but the mapping of virtual objects to camera feed is affected which causes a lot of drift. Please check the given video link which demonstrates the problem. [Videolink](https://www.youtube.com/watch?v=9fPHkzz4jew)

**Comment by nathanmartz** [comment]
That's correct. The GVR plugin does this work at the native level and cannot be overridden. We have no plans to support GVR with ARKit, so closing this issue.
