### ISSUE TITLE
Two Questions about Sdk

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#730]
Q1: Why StereoRenderEffect.cs is needed in gvr unity sdk 1.4? 
The code comment say "  Some image effects clobber the whole screen.  Add a final image effect to the chain which restores side-by-side stereo." ?  I am a little confused.   Besides, I profile an Android cardboard app complied using unty 5.6.0f3, and found the post effect is removed.   Can I remove StereoRenderEffect in Unity 5.5.3f1(Gvr 1.4)?

![5 5 3f1](https://user-images.githubusercontent.com/8831805/30518205-8f3722c0-9ba9-11e7-9358-6150aa2a29b5.png)
![5 6 0f3](https://user-images.githubusercontent.com/8831805/30518206-92bce8d0-9ba9-11e7-8c86-c1c0df086098.png)

Q2: This question is about StereoScreen size. The code comment say "Unity  halved the render texture size on 5.6, so we compensate here."    Could you please explain in detail?
![stereoscreen](https://user-images.githubusercontent.com/8831805/30518232-7b45e2b4-9baa-11e7-992f-52e1d4290577.png)

**Comment by nathanmartz** [comment]
I'm sorry, but we can only give support for the latest version of the SDK, which is 1.70. Please give that a try and re-open this post if you still have issues.
