### ISSUE TITLE
HUD distortions 

### ISSUE THREAD

**Issue by SaraKaterji** [googlevr/gvr-unity-sdk#732]
Hello , 
I am having problems with setting up UI unity using gvr 1.7 
I did all what available tutorials suggested which is:  world space canvas then put it as child of camera
but the hud disappears completely on mobile device. After a few line of codes , i got the ui to appear but it seems distorted  as in not in the right position

**Comment by chaosemer** [comment]
Could you please describe what seems distorted? A screenshot or repro project would help a lot.

**Comment by fredsa** [comment]
Also, please check that **Player Settings > Other Settings > Virtual Reality SDKs > Daydream/Cardboard > Depth format** is set to **24-bit | 8-bit stencil**. This is for example important for scroll Canvas UI elements which use the stencil.

**Comment by fredsa** [comment]
If you're still having issues, please include a screenshot, and ideally a small project reproduces the issue.
