### ISSUE TITLE
apk is not building up for vr

### ISSUE THREAD

**Issue by GVSCHOWDARY** [googlevr/gvr-unity-sdk#733]
in windows 7 android apk is not building up when the vr is selected and showing library files not found but i have all the libraries that i need.Any solution for it , please raise your answer here. @hapticdata @dubois @dav-cz @HalfdanJ @borismus

**Comment by chaosemer** [comment]
That is unexpected, Windows 7 is expected to work fine. Could you please share a repro project?

**Comment by fredsa** [comment]
If this is still an issue, please re-open and include any error messages you see, as well as steps to reproduce.
