### ISSUE TITLE
Code conflicts

### ISSUE THREAD

**Issue by DmytroHreshchik** [googlevr/gvr-unity-sdk#734]
It would be amazing, if you could put all of your code into own namespace. Because of code in "GoogleVR/Demos/Scripts" doesn't have own namespace, it creates conflicts with my classes.

**Comment by guneyozsan** [comment]
I also had some issues with ObjectPool class name conflicting with some other plugins.

**Comment by dsternfeld7** [comment]
Thank you, this will be addressed.

**Comment by rusmaxham** [comment]
Fixed in [v1.110](https://github.com/googlevr/gvr-unity-sdk/releases).
