### ISSUE TITLE
My controller will not vertically rotate

### ISSUE THREAD

**Issue by ylluminarious** [googlevr/gvr-unity-sdk#735]
In a scene of my Unity project, my controller will only rotate along the roll axis. It simply refuses to rotate along the pitch or the yaw, no matter what my hand movements are. This is unacceptable for my game, since the user needs to feel like they have free hand movement. However, the controller works completely as expected in the GVR Demo Scene that is supplied with the SDK, so it must be a problem in my project's scene. Could someone give advice on what this problem may be?

Also, for those unfamiliar with the pitch, yaw, and roll axes, here's a diagram from Wikipedia that shows what I mean:

![yaw_axis_corrected svg](https://user-images.githubusercontent.com/4912973/30882587-6de94f82-a2d7-11e7-9416-ebde11c20f02.png)

**Comment by fredsa** [comment]
I would guess that you either have custom scripts which are limiting the controller, or have other constraints such as a rotation frozen rigid body.

Suggest comparing the demo scene which works with your scene to see what the differences are.

**Comment by ylluminarious** [comment]
@fredsa Thanks for the advice. It turns out that the issue was that I had not tagged my Camera component with the `MainCamera` tag.
