### ISSUE TITLE
White screen when back to unity from QR code reader view

### ISSUE THREAD

**Issue by LoofahBu** [googlevr/gvr-unity-sdk#736]
I click setting button enter QR code reader view.

When back to unity, the whole screen become white.

Below is error message and my unity and gvr version.

OpenGLES error 0x0506 in Unity/Classes/Unity/GlesHelper.mm:339
OpenGLES error 0x0502 in Unity/Classes/Unity/GlesHelper.mm:339
OpenGLES error 0x0502 in Unity/Classes/Unity/GlesHelper.mm:339
OpenGLES error 0x0502 in Unity/Classes/Unity/GlesHelper.mm:339

Unity - 5.3.2f1
Gvr - 0.8

**Comment by nathanmartz** [comment]
I'm sorry but we can only provide support for the current version of the SDK, and the one you are using is more than a year old.
