### ISSUE TITLE
Issue when importing new GoogleVRForUnity

### ISSUE THREAD

**Issue by hassan4202** [googlevr/gvr-unity-sdk#739]
I am creating a new project error message is displayed indicating the following
Assets/GoogleVR/Scripts/UI/GvrDropdown.cs(23,28): error CS0246: The type or namespace name `Dropdown' could not be found. Are you missing a using directive or an assembly reference?

Why does this happen?

Thanking you in advance the care provided.

**Comment by nathanmartz** [comment]
Hi, Hassan. Did you delete the old SDK before installing the new one? If
not, that will probably fix your issue.
