### ISSUE TITLE
Crash when I running the DemoScene

### ISSUE THREAD

**Issue by Juanfry88** [googlevr/gvr-unity-sdk#741]
Hi everyone!
I have imported gvr unitypackage and I build for iOS, when I run in xCode the app start but nothing appear, only a black screen... I have xCode 9.0 (9A235) and Unity 2017.1.0f3

_eVR(1641,0x1b5343b80) malloc: *** error for object 0x1082c1648: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
(lldb)_

**Comment by nathanmartz** [comment]
Is this in a brand new project with just the GVR SDK or are there other
plugins and such installed? If the latter, can you try the former?

**Comment by Juanfry88** [comment]
There isn't other plugin... only gvr, and I run the demo scene, without touch anything

**Comment by fredsa** [comment]
@Juanfry88 To help isolate the source of the problem, can you try creating a new Unity project with just an empty scene? Set the build platform to **iOS**, but leave **Player Settings > iOS > Other Settings > Virtual Reality Supported** _disabled_. Build and run the app.

If that works, enable VR support and build and run the app again:
* **Player Settings > iOS > Other Settings > Virtual Reality Supported**: _enabled_
* **Player Settings > iOS > Other Settings > Virtual Reality SDKs**: _Cardboard_

If the app still runs normally, import the Google VR `.unitypackage` into the working project, open the **GVRDemo** scene, and once again build and run the app.

Let us know what you find.

**Comment by fredsa** [comment]
@Juanfry88 Please file a new issue if you have any problems setting up a new project using our updated [Get started with Google VR in Unity on iOS](https://developers.google.com/vr/unity/get-started-ios) guide.
