### ISSUE TITLE
-[UICTFont mdc_weight]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by jplongo** [googlevr/gvr-unity-sdk#744]
I issue big crash when VRIsEnabled. Can't find why my app crash here.

I've set Symbolic breakpoint and know that the crash happen in 
`CardBoardAppController.mm - line 51`
Selector `-[UICTFont mdc_weight]` is in libGVRSDK.a but I can't access inside the library.
Any info about this crash ?

Thanks 

![2017-10-08 at 3 54 pm](https://user-images.githubusercontent.com/22789876/31317449-ab061526-ac41-11e7-99eb-2781fca71fae.png)
![2017-10-08 at 3 58 pm](https://user-images.githubusercontent.com/22789876/31317453-addeebec-ac41-11e7-83ae-f74d57e8dc79.png)

**Comment by jiulongw** [comment]
Adding `-objC` to `OTHER_LDFLAGS` should fix this issue.

https://developer.apple.com/library/content/qa/qa1490/_index.html

jiulongw/swift-unity#3

**Comment by jplongo** [comment]
With help of @jiulongw and StackOverflow, I'm able to solve my issue.
Thanks
