### ISSUE TITLE
GvrVideoPlayerTexture not rendering

### ISSUE THREAD

**Issue by Flameshot** [googlevr/gvr-unity-sdk#745]
Hello. I have imported the last GVR Unity SDK 1.100.0 in my unity project and created a 360 video. When I'm building and runnint it using unity everything works fine. But because I'm using a personal SDK i have to export the project in android studio and compile there.
In my build.gradle I have used:

compile(name: 'gvr', ext: 'aar')
	compile(name: 'play-services-ads-9.4.0', ext: 'aar')
	compile(name: 'play-services-basement-9.4.0', ext: 'aar')
	compile(name: 'unitygvr', ext: 'aar')
	compile 'com.squareup.okio:okio:1.13.0'
	compile 'com.squareup.okhttp3:okhttp:3.8.0'
	compile 'com.google.code.gson:gson:2.8.0'
	compile 'com.android.support:appcompat-v7:25.3.1'
	compile 'com.android.support:design:25.3.1'
	compile 'com.android.support:support-v4:25.3.1'
	compile 'com.android.support:multidex:1.0.1'
	compile 'com.google.android.exoplayer:exoplayer:r1.5.11'
	compile 'com.google.android.exoplayer:exoplayer-core:r2.4.0'
	compile 'com.google.android.exoplayer:exoplayer-dash:r2.4.0'
	compile 'com.google.android.exoplayer:exoplayer-ui:r2.4.0'

The problem is when I move from the first scene to the 360 one my apk crashes having this error:

"JNI GetObjectClass called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.google.gvr.exoplayersupport.VideoPlayer""

I've trying everything about this dependencies. Nothing works.

Also I have set my Type of Player to "OTHER" and I'm using this path:  "jar:file://${Application.dataPath}!/assets/intro_movie_compressed.mp4"

**Comment by Flameshot** [comment]
Fixed it by adding compile(name: 'gvr-exoplayersupport-release', ext: 'aar') in build.gradle dependencies.

**Comment by rusmaxham** [comment]
What version of Unity did this occur with?

**Comment by Flameshot** [comment]
@rusmaxham  Unity 2017.1.0f3
