### ISSUE TITLE
Daydream controller tracking stops working after resuming application

### ISSUE THREAD

**Issue by Moncader** [googlevr/gvr-unity-sdk#748]
The newest GVR SDK v1.100.0 in Unity 2017.2 has an issue where the controller stops working after your application pauses and then resumes.

This can be done in multiple ways. Here are two of them.

Number 1:
1. Make a new Unity Project
2. Add the GVR SDK
3. Set the Unity XR mode to Daydream by default
4. Set the GVRDemo scene as the default scene.
5. Run the app on any Daydream device (tested on Pixel XL, Galaxy S8, and others) from the Android 2D launcher.
6. The scene will load like normal
7. Press the power button on your phone to turn it off (ApplicationPause will happen)
8. Turn it back on.
9. Controller doesn't respond anymore (just tracking, the home button works)

Number 2:
1. Make a new Unity Project
2. Add the GVR SDK
3. Set the Unity XR mode to Daydream by default
4. Set the GVRDemo scene as the default scene.
5. Run the app on any Daydream device (tested on Pixel XL, Galaxy S8, and others) from the Daydream Home launcher
6. The scene will load like normal
7. Press the home button to go back to Daydream Home
8. Enter the app again.
9. Controller doesn't respond anymore (just tracking, the home button works)

**Comment by bopangzz** [comment]
Thanks for the bug report. We will look into it.

**Comment by dsternfeld7** [comment]
Thanks for the report!

This issue is specific to Unity 2017.2 and cannot be fixed in the GVR SDK for Unity. There are more details in this forum post [here](https://forum.unity.com/threads/daydream-controller-freezes-after-returning-from-daydream-home.498778/).

**Comment by rusmaxham** [comment]
This is expected to be fixed in 2017.2.0p1.

**Comment by Moncader** [comment]
Is there any ETA on when the p1 release will happen?
In the current state, 2017.2 released Async Reprojection support + secure video playing but we can't release an app using that feature because of this bug.

**Comment by Moncader** [comment]
This seems to be fixed in the newest patch version 2017.2.0p1

**Comment by pixelbrainstudio** [comment]
Good news,  it is working after the recent released unity patch (15. november)... yesterday I tested
