### ISSUE TITLE
instant preview over wifi

### ISSUE THREAD

**Issue by derekja** [googlevr/gvr-unity-sdk#750]
on gvr-unity-sdk v1.100.1 and unity 2017.2 I cannot get instant preview to work over wifi. This is on an Asus Zenphone AR, and the instant preview app on the phone can see the desktop over wifi, and connection over USB works just fine. This is using the GVRDemo application in the SDK.

In the unity console I see the following warnings:
1) VRDevice daydream not supported in editor mode. Please run on target device.
2) Tiled GPU perf. warning: RenderTexture color surface  (1148x632) was not cleared/discarded, doing <run with profiler for info>
3) A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP, Boolean requireSocketPolicy) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remote_end_point) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPAddress[] ipAddresses, Int32 port) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:LogWarningFormat(String, Object[])
Gvr.Internal.EmulatorClientSocket:phoneEventSocketLoop() (at Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:76)

**Comment by fredsa** [comment]
@derekja Are you able to use `adb` commands over Wi-Fi?
https://developer.android.com/studio/command-line/adb.html#wireless

The most common issue is [AP isolation](https://www.google.com/search?q=What+is+AP+isolation+on+a+wireless+router) which prevents your development machine and phone from being able to communicate with each other, even though they are accessing the same wireless access point / router.

**Comment by derekja** [comment]
yes, ADB connects fine over wifi or USB, but instant preview connects only over USB.

**Comment by gstanlo** [comment]
It's surprising that you can't connect to the host computer, but it's visible in the host selection. When you select it from the drop down menu, does it stay in the disconnected (red) state, or does it appear connected (grey) but not stream? 

There should be little difference between wifi/usb. Instead of connecting to 127.0.0.1, the app will connect to the advertised host address. Is it possible something in your router is blocking tcp packets going to port 49838?

**Comment by derekja** [comment]
no, it stays in the disconnected state. I don't think 49838 is blocked, the firewall looks to be open. I am having a harder time figuring out if multicast is working properly. I'm following the instructions at https://helpdesk.kaseya.com/hc/en-gb/articles/229021468-How-to-test-if-Multicast-is-working-on-your-network and not getting a file to transfer, but I don't have 100% confidence in those directions to test multicast since they are just a random google search.

When I logcat the phone ("adb logcat | grep Instant") I get the following output (abbreviated to cut out past runs for brevity - this is me shifting to a USB connection and then back to the wifi)

10-16 17:16:09.086  1381  1554 D ActivityManager: [MemInfo] Before resuming ActivityRecord{18415da u0 com.google.instantpreview/.FlatInstantPreviewActivity t392}. System free memory=4244660224
10-16 17:16:09.110 27892 27892 I InstantPreviewConnection: Connecting to: 10.1.2.135:49838
10-16 17:16:13.856 27892 27892 I InstantPreviewConnection: setHostAddress: 127.0.0.1:49838
10-16 17:16:13.857 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
(many more lines connecting to 127.0.0.1:49838)
10-16 17:17:15.039 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
10-16 17:17:21.552  1381  1554 D ActivityManager: [MemInfo] Before resuming ActivityRecord{18415da u0 com.google.instantpreview/.FlatInstantPreviewActivity t392}. System free memory=4229955584
10-16 17:17:21.577 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
10-16 17:17:22.599 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
10-16 17:17:23.605 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
10-16 17:17:24.633 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
10-16 17:17:25.666 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
10-16 17:17:26.690 27892 27892 I InstantPreviewConnection: Connecting to: 127.0.0.1:49838
10-16 17:17:26.696 27892 27892 I InstantPreviewConnection: setHostAddress: 10.1.2.135:49838
10-16 17:17:26.697 27892 27892 I InstantPreviewConnection: Connecting to: 10.1.2.135:49838
10-16 17:17:27.709 27892 27892 I InstantPreviewConnection: Connecting to: 10.1.2.135:49838

**Comment by gstanlo** [comment]
The multicast is only used to advertise the host address, and that aspect seems to be working; I'm assuming that the host computer you're trying to connect to is indeed at 10.1.2.135?

Is the logcat showing any exceptions?

**Comment by derekja** [comment]
yes, 10.1.2.135 is the correct host address.

I don't see anything that stands out, except for a huge number of entries about an OAuth failure:

10-16 18:05:28.527  6938  7144 I native  : oauth_provider.cc:92 OAuth provider returned invalid token, sleeping...

Actually, if I filter the logcat by errors I do get some that might be interesting. I'm going to drop all of them in after the instant preview error just because I'm not sure what's relevant:

10-16 18:15:13.928  1381  1958 E InputDispatcher: channel 'c99f4d0 com.google.instantpreview/com.google.instantpreview.FlatInstantPreviewActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-16 18:15:14.077  1381  1381 E qdlights: [LED] set_light_buttons and write: 0
10-16 18:15:15.240  1381  1958 E qdlights: [LED] set_light_buttons and write: 255
10-16 18:15:15.986 26987 26987 E d       : RuntimeException while executing runnable az{com.google.android.libraries.gsa.monet.tools.a.b@b2d7e2d} with executor MoreExecutors.directExecutor()
10-16 18:15:15.986 26987 26987 E d       : java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
10-16 18:15:15.986 26987 26987 E d       :      at android.view.ViewGroup.addViewInner(ViewGroup.java:4454)
10-16 18:15:15.986 26987 26987 E d       :      at android.view.ViewGroup.addView(ViewGroup.java:4295)
10-16 18:15:15.986 26987 26987 E d       :      at android.view.ViewGroup.addView(ViewGroup.java:4235)
10-16 18:15:15.986 26987 26987 E d       :      at android.view.ViewGroup.addView(ViewGroup.java:4208)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.sidekick.shared.overlay.bl.c(SourceFile:8)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.shared.monet.ao.aAZ(SourceFile:9)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.shared.monet.ao.c(SourceFile:6)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.shared.monet.RendererPublisher.publishRenderer(SourceFile:12)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.plugins.shortcuts.a.c.ad.a(SourceFile:14)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.libraries.gsa.monet.tools.children.b.c.run(Unknown Source)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.libraries.gsa.monet.tools.children.b.d.onSuccess(SourceFile:2)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.libraries.gsa.monet.tools.a.b.onSuccess(SourceFile:11)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.common.util.concurrent.az.run(SourceFile:13)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.common.util.concurrent.br.execute(SourceFile:3)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.common.util.concurrent.d.b(SourceFile:271)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.common.util.concurrent.d.addListener(SourceFile:135)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.common.util.concurrent.ax.a(SourceFile:46)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.libraries.gsa.monet.tools.a.a.a(SourceFile:16)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.libraries.gsa.monet.tools.children.b.e.onModelUpdate(SourceFile:60)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.libraries.gsa.monet.internal.shared.b.bz(SourceFile:28)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.shared.monet.o.onServiceEvent(SourceFile:116)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.search.shared.service.ab.call(SourceFile:7)
10-16 18:15:15.986 26987 26987 E d       :      at com.google.android.apps.gsa.search.shared.service.aa.run(SourceFile:2)
10-16 18:15:15.986 26987 26987 E d       :      at android.os.Handler.handleCallback(Handler.java:751)
10-16 18:15:15.986 26987 26987 E d       :      at android.os.Handler.dispatchMessage(Handler.java:95)
10-16 18:15:15.986 26987 26987 E d       :      at android.os.Looper.loop(Looper.java:159)
10-16 18:15:15.986 26987 26987 E d       :      at android.app.ActivityThread.main(ActivityThread.java:6097)
10-16 18:15:15.986 26987 26987 E d       :      at java.lang.reflect.Method.invoke(Native Method)
10-16 18:15:15.986 26987 26987 E d       :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
10-16 18:15:15.986 26987 26987 E d       :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-16 18:15:16.249  2760  2760 E ctxmgr  : [PlaceFenceHelper]NearbyBuffer is null!
10-16 18:15:17.439   882   882 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
10-16 18:15:17.458  1381  1381 E qdlights: [LED] set_light_buttons and write: 0
10-16 18:15:18.126   841  6502 E         : Service not available yet
10-16 18:15:19.889   482  2653 E ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
10-16 18:15:19.889   482  2653 E ANDR-PERF-OPTSHANDLER:  return value 2
10-16 18:15:22.615   882   882 E cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
10-16 18:15:22.615   882   882 E cnss-daemon: : 00:00:00:00:00:00
10-16 18:15:22.615   882   882 E cnss-daemon: Invalid mac address: 0x5572a9a110M
10-16 18:15:23.468 26987 26996 E ReloadingLock: Finalizing LOCKED Token[shortcuts 2017-10-16 18:15:15.907]
10-16 18:15:25.529   882   882 E cnss-daemon: Stale or unreachable neighbors, ndm state: 16
10-16 18:15:36.538   882   882 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
10-16 18:15:38.598   882   882 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
10-16 18:15:58.639   882   882 E cnss-daemon: Stale or unreachable neighbors, ndm state: 16
10-16 18:16:01.106  3111  3962 E SQLiteCastStore: End saving paired guest mode devices
10-16 18:16:10.281   882   882 E cnss-daemon: gateway mac address: %02x:%02x:%02x:%02x:%02x:%02x
10-16 18:16:10.281   882   882 E cnss-daemon: : 00:00:00:00:00:00
10-16 18:16:10.282   882   882 E cnss-daemon: Invalid mac address: 0x5572a9a110M
10-16 18:16:11.719   882   882 E cnss-daemon: Stale or unreachable neighbors, ndm state: 4
10-16 18:16:17.360   882   882 E cnss-daemon: Stale or unreachable neighbors, ndm state: 16

**Comment by gstanlo** [comment]
`Channel is unrecoverably broken and will be disposed` 
looks worrisome, are there any exceptions before that? 

Also, can you try starting in VR mode? It should begin that way if you start it from the Daydream launcher, and it should list your host computer name in the vr view. There might be some issue when it switches activities.

**Comment by rusmaxham** [comment]
Is this still an issue?

**Comment by derekja** [comment]
I will confirm on v1.110.0 and reply. Thanks.

**Comment by ylluminarious** [comment]
@rusmaxham I still have trouble connecting through Wifi, though my issues are somewhat different. Some details are available [here.](https://github.com/googlevr/gvr-instant-preview/issues/10)

**Comment by rusmaxham** [comment]
The gvr-instant-preview repo has been removed since IP now lives in the gvr-unity-sdk.  Could you detail your issues here?

**Comment by chaosemer** [comment]
We believe we fixed this. Please reopen if you still have this issue.

**Comment by fhcampbell** [comment]
> We believe we fixed this. Please reopen if you still have this issue.

Hi,
Could you elablore possible, what is the fix?

I've posted a reply  when the same issue occured immediatly after Android stuido updated.
I am going back through the suggestions to my post about this issue less than 2 weeks ago.

There, you'll see that I ve checked the adb device. 

This is consuming hours.
Was the fix that you are referring to based on anything not accessible on Unity and solely based on android previous API versions?
Thank you for your reply.
It's bizarre that the entire editor is not working on play just after the latest updates to Android.
So, there's got to be an option to restore teh controller.
Thank you Chaosemer.

**Comment by chaosemer** [comment]
We fixed numerous bugs around connection, finding ADB, and such. I suspect that the OP's issue is addressed. But nothing around SDK version. If you are having an issue with the latest SDK, please create a new issue here. If you've already done that, can you point me to that issue?

Thanks.
