### ISSUE TITLE
Unity GVR app - Huge movement delay

### ISSUE THREAD

**Issue by pezvolador** [googlevr/gvr-unity-sdk#752]
Hello everybody. 

Even though my scene is extremely basic (just one plane, medium quality settings) there is a huge delay between the movement of the head and the app responding. I have a total amount of 2 Draw Calls, 2 Batches, 1.9k Tris. Frame rate on pc is 4000 Fps!. So it definitely is not an optimization issue. 

I have unity updated to 2017.2.0f3 and GVR is version 1.100.1. My phone is a Huawei P8 Lite 2017.

Why is this happening?

Thanks in advance.

**Comment by pezvolador** [comment]
I think it has something to do with the phone not having a gyroscope. Not 100% sure but... It looks like that is the problem.

**Comment by dubtor** [comment]
Did you read about this Unity problem? I am having the same problems https://issuetracker.unity3d.com/issues/android-input-dot-gyro-is-extremely-laggy-on-specific-device-with-android-7-dot-0

**Comment by fredsa** [comment]
A gyroscope is required: https://support.google.com/cardboard/answer/6295046

As for sensor lag mentioned in the [linked](https://issuetracker.unity3d.com/issues/android-input-dot-gyro-is-extremely-laggy-on-specific-device-with-android-7-dot-0) Unity case, unfortunately that's not something that can be addressed in the SDK.
