### ISSUE TITLE
Unity 2017.2.0f2 + GVR 1.70 | GVR 1.100 Controller don't work

### ISSUE THREAD

**Issue by VadimTikhonyuk** [googlevr/gvr-unity-sdk#755]
Hi, there
Check this video:
https://youtu.be/vRRdE_fuqCQ

Controller tracking and touchpad don't work
Hardbuttons (Volume, Home) work

I output all available debug info on UI
`
// Update is called once per frame
void Update () 
{
log.text = GvrController.Accel.ToString() + "\n" + GvrController.ApiStatus.ToString () + "\n" + 
GvrController.BatteryLevel.ToString () + "\n" + GvrController.Gyro.ToString() + "\n" + GvrController.State.ToString ();
}
`

**Comment by VadimTikhonyuk** [comment]
If I enable splash screen then it works, need to do some more researches

**Comment by VadimTikhonyuk** [comment]
Also If I enter in VR mode from 2D Scene with this code :

![image](https://user-images.githubusercontent.com/13260375/31719962-d5feb42a-b41d-11e7-83d7-71b32d428903.png)

Then Controller don't work again,
Also If Enter In VR Home then back again controller change position in game

**Comment by rusmaxham** [comment]
This is a known issue with 2017.2f3 and will be fixed in 2017.2**p1** due out soon.
