### ISSUE TITLE
Instant Preview is not displaying any output to screen on moto z

### ISSUE THREAD

**Issue by prasengan** [googlevr/gvr-unity-sdk#757]
instant preview version 1.0.0.65
moto z android 7.1.1 build NPL26.118-20-5
it is not feeding any output to phone screen but the controller is working, I am getting output and controller data if I use version 1.0.0.15, seems like there is some issue with new version.

**Comment by bopangzz** [comment]
@gstanlo Can you take a look at this issue?

**Comment by gstanlo** [comment]
The video streaming should be very similar between both versions -- can you confirm that the gvr demo scene works properly?

**Comment by prasengan** [comment]
gvr demo works on 1.0.0.15, but on 1.0.0.65 i can see  controller on laptop screen not on daydream, on daydream i see default instant preview scene.

**Comment by prasengan** [comment]
Issue resolved, I created a new project and used adb server kill and then reimported my assets in the new project.
