### ISSUE TITLE
Unity exports broken apps crashing on start.

### ISSUE THREAD

**Issue by reinier450** [googlevr/gvr-unity-sdk#758]
No code was modified by me. 
All that happened was that Unity updated to the latest version,
and needed me to update to the latest Android SDK.

I have not altered any function, I have no error messages, my phone just tells me that the app stopped working. I even tried using the demoscene with a brand new project and the problem persisted.
I am exporting on the correct android version number, I can't figure out what's wrong.

**Comment by martinbilello** [comment]
Hi, can you attach the result of a logcat here so we can have more information about the crash?

Thanks

**Comment by fredsa** [comment]
@reinier450 Please reopen if you have additional details which would help us reproduce this issue.
