### ISSUE TITLE
Disable Head Tracking for specific camera without XR.enabled = false

### ISSUE THREAD

**Issue by VadimTikhonyuk** [googlevr/gvr-unity-sdk#759]
Hello,

I have cameras setup in my VR project which capture 360 panorama
I need to disable head tracking which enabling for each camera by default

**Comment by nathanmartz** [comment]
Are these tagged as "Main Camera"? If so, removing the tag should fix the issue.

**Comment by fredsa** [comment]
At runtime, on your mobile phone, only cameras which target one or both eyes should follow the builtin head tracking. Set the Camera **Target Eye** to **None (Main Display)** to disable tracking.

The Camera's [`stereoTargetEye`](https://docs.unity3d.com/ScriptReference/Camera-stereoTargetEye.html) property is visible in the Camera inspector view when VR support is enabled in Player Settings).

Note, while running in the editor, camera tracking is emulated in `GvrEditorEmulator`.
 Its [`ValidCameras()`](https://github.com/googlevr/gvr-unity-sdk/blob/a37f02e8b192be570a76180fc3854aa8f92d9a37/Assets/GoogleVR/Scripts/GvrEditorEmulator.cs#L123) applies the same Target Eye logic as the native tracking applies at runtime on the mobile device.
