### ISSUE TITLE
Volume buttons not work

### ISSUE THREAD

**Issue by haoguo** [googlevr/gvr-unity-sdk#760]
Volume buttons not work, According to https://github.com/googlevr/gvr-unity-sdk/issues/40, I found that volume buttons are no longer disabled in Cardboard. is this a bug?

Found using:
 * Google VR SDK version: 1.100.0
 * Unity version: 5.6.2f1
 * Phone manufacturer, model, and O/S version: MI5

**Comment by rusmaxham** [comment]
This should be fixed in Unity as of 5.6.3f1 and 2017.1.1f1.

**Comment by haoguo** [comment]
thanks a lot @rusmaxham

**Comment by sylafrs** [comment]
I just tested 5.6.3f1, and it doesn't seem to be working.
Do we have to integrate something for it to work?

**Comment by rusmaxham** [comment]
Can you try with 5.6.4f1?  I'm able to use the volume buttons with a Cardboard app built with 5.6.4f1.

**Comment by JonTakahiro** [comment]
I'm using Unity 2017.1.1f1 with GoogleVR 1.50.0, and the volume buttons are not working for me.

Can you confirm this was tested in that version of Unity, or would updating the GoogleVR SDK fix the issue?

**Comment by rusmaxham** [comment]
This is fixed in Unity 2017.1.2f1.
