### ISSUE TITLE
object reference error

### ISSUE THREAD

**Issue by JMAPeters** [googlevr/gvr-unity-sdk#761]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: 1.100.1
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version: ___
 * Viewer manufacturer & model: ___

Steps to reproduce the issue:
 1. Open a project

Workarounds:
When i open a project and load the assets an this error starts counting.

Additional comments:
Object reference not set to an instance of an object
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)

**Comment by dsternfeld7** [comment]
Hey there! I just tried reproducing this issue and wasn't able to. Would be be able to provide more detail about how to reproduce it?

Also, I recommend against using Unity 2017.2.0f3 for Daydream development. Please see the thread [here](https://forum.unity.com/threads/daydream-controller-freezes-after-returning-from-daydream-home.498778/) for more details.

**Comment by JMAPeters** [comment]
Hello, thanks for helping me,

well, when I open a new project, everything is fine, but after i load the google vr sdk for unity v1.100.1 in a got the following errors

![foutmelding](https://user-images.githubusercontent.com/26442488/32013824-8647a1e0-b9bc-11e7-9963-eadf2c24bd9a.png)

the last one keeps adding.

I have no idee why, I followed the get starded steps -> https://developers.google.com/vr/unity/get-started , but the errors are still there, i've even reinstalled unity. 

I hope you can fine a solution for my problem

**Comment by dsternfeld7** [comment]
Do these errors happen when you hit play? or just when the editor is open?

Can you click on the "Object reference not set to an instance of an object" error and copy and paste the full stack trace into this issue?

Thanks,

Dan

**Comment by dsternfeld7** [comment]
What platform is your build target set to?

**Comment by JMAPeters** [comment]
Just when the editor is open, when i try to play unity freeze.

Al the errors copy pased:


ApplicationName='"D:\Programma's 2\Unity\Editor\Data\MonoBleedingEdge\bin\mono.exe"', CommandLine='"D:\Programma's 2\Unity\Editor\Data\MonoBleedingEdge\lib\mono\4.5\mcs.exe"  @Temp/UnityTempFile-ae14441607ee0524f8fc4ce5e479b1dd', CurrentDirectory='D:/Documenten/Unity Games/Cardboard3/Assets/..'
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:CompileScripts(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)


Object reference not set to an instance of an object
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)



android is my build target

**Comment by dsternfeld7** [comment]
Thanks!

When you click on an error in the Console, a window at the bottom of the Console displays more details about that error. Shown in the image below:

<img width="1084" alt="testexception" src="https://user-images.githubusercontent.com/20076332/32015353-b4e081a8-b975-11e7-8000-00f1df39f656.png">

Can you copy and paste the full detailed information about both errors into this issue?

Thanks,

Dan

**Comment by JMAPeters** [comment]
The extra info is the same as the bug, dont know if that is right or im pressing wrong

![foutmelding](https://user-images.githubusercontent.com/26442488/32015535-a8a91962-b9c1-11e7-9016-539f6714df17.png)

**Comment by dsternfeld7** [comment]
I have a suspicion about what is going on - try making sure that your filepath's for both the Unity installation and your project do not contain and spaces or apostrophes.

**Comment by dsternfeld7** [comment]
Thank you! Some errors don't have more detailed information, so what you sent me is correct. Please let me know what happens when you try changing the filepath's for the Unity installation and the project!

Thanks,

Dan

**Comment by JMAPeters** [comment]
Nice i changed the name of the folder and now it works

**Comment by dsternfeld7** [comment]
Great! I'm glad it's working for you now! Closing this issue.
