### ISSUE TITLE
How to use the GameObject pools and PoolManager

### ISSUE THREAD

**Issue by SelaO** [googlevr/gvr-unity-sdk#763]
I have several GameObjects that I want to place in different pools and have the pool manager to hold them, but I don't understand how to use them and there are no docs on how to use them.

I want to use the [GameObjectPool](https://github.com/googlevr/gvr-unity-sdk/blob/27666a66e54427758c8a6aaa6701084ffd456cff/Assets/GoogleVR/Demos/Scripts/ScrollingUIDemo/Pooling/GameObjectPool.cs) and [PoolManager](https://github.com/googlevr/gvr-unity-sdk/blob/27666a66e54427758c8a6aaa6701084ffd456cff/Assets/GoogleVR/Demos/Scripts/ScrollingUIDemo/Pooling/ObjectPoolManager.cs).

So how can I take a GameObject (let's say it's called "Enemy") and create a pool for it and place that pool in the pool manager?

Found using:
 * Google VR SDK version: v1.100.1
 * Unity version: 5.6.2f1
 * Phone manufacturer, model, and O/S version: Android
 * Viewer manufacturer & model: Irrelevant

**Comment by dsternfeld7** [comment]
First, make sure you have an instance of the ObjectPoolManager script in your scene.

Then, you can create a script that has a serialized reference to the enemy prefab and provides a getter for accessing the pool like below.

```
public GameObjectPool EnemyPool {
  get {
    // Get the pool manager.
    ObjectPoolManager poolManager = ObjectPoolManager.Instance;
    Assert.IsNotNull(poolManager);

    // Get the pool and return it if it already exists.
    string poolName = enemyPrefab.name;
    GameObjectPool pool =
      poolManager.GetPool<GameObjectPool>(poolName);

    if (pool != null) {
      return pool;
    }

    // Create the pool if it doesn't exist yet.
    pool = new GameObjectPool(pagePrefab, capacity, preAllocateAmount);
    poolManager.AddPool(poolName, pool);

    return pool;
  }
}
```

Next, you can get an enemy from the pool like this:

`GameObject enemy = EnemyPool.Borrow();`

Finally, you can return an enemy to the pool like this:

`EnemyPool.Return(enemy);`

Please let me know if that helps! I'm happy to answer additional questions.

Thanks,

Dan

**Comment by dsternfeld7** [comment]
[Here](https://github.com/googlevr/gvr-unity-sdk/blob/master/Assets/GoogleVR/Demos/Scripts/ScrollingUIDemo/PaginatedScrolling/PageProviders/PooledPageProvider.cs) is an example of the ObjectPoolManager being used in the ScrollingUIDemo for an example of paginated scrolling that uses pooled pages.

Thanks,

Dan

**Comment by SelaO** [comment]
> you can create a script that has a serialized reference to the enemy prefab

How do you do that?

**Comment by SelaO** [comment]
It looks like it works now, but it keeps growing with every `Burrow` call, isn't there a way to make it stop growing? (other than checking its size before `Burrow`)

**Comment by dsternfeld7** [comment]
If the pool is currently empty, then each time Borrow is called a new instance will be allocated. It's pivotal that when an enemy is removed if is returned to the pool instead of being Destroyed so that it can be re-used.

You'll want to make sure to set the capacity of the pool to a reasonable number based on the number of enemies you need to have borrowed from the pool at one time. Optionally, you can also have the pool preAllocate enemies when the pool is created instead of having them be lazily instantiated when they are requested.

[Wikipedia](https://en.wikipedia.org/wiki/Object_pool_pattern) has some more general information about the Object Pool design pattern that you may find useful.

**Comment by SelaO** [comment]
If I preallocate and then burrow, the preallocated ones stay hidden and new ones are being instantiated and not even under the same parent object. 

Also, there's no way to know if I already have a number of active enemies in the scene or not from the pool itself, I need to keep a counter of my own for each pool.

**Comment by dsternfeld7** [comment]
What did you pass in as the capacity and preAllocateAmount? Can you share your code with me?

After you borrow from the pool, you'll want to change the parent of the returned object to whatever is appropriate for your application.

**Comment by dsternfeld7** [comment]
Additionally, it would also be helpful if you can share an image of what your scene hierarchy looks like after you've created the pool and called borrow.

**Comment by SelaO** [comment]
```
	public GameObjectPool EnemyPool2 {
		get {
			// Get the pool manager.
			ObjectPoolManager poolManager = ObjectPoolManager.Instance;
			Assert.IsNotNull(poolManager);

			// Get the pool and return it if it already exists.
			string poolName = "Enemy";
			GameObjectPool pool =
				poolManager.GetPool<GameObjectPool>(poolName);

			if (pool != null) {
				return pool;
			}

			// Create the pool if it doesn't exist yet.
			pool = new GameObjectPool(enemy, 5, 5);
			poolManager.AddPool(poolName, pool);

			return pool;
		}
	}
```

And then call it like this: `GameObject newEnemy = EnemyPool2.Borrow ();`

Then I have an `EnemyPool` with 5 hidden GameObjects and then with burrow, I get enemies without a parent:
![image](https://user-images.githubusercontent.com/21977571/32021699-c5b94958-b9dc-11e7-8950-fdaa4c682f64.png)

**Comment by dsternfeld7** [comment]
How many times have you called EnemyPool2.Borrow()?

When you borrow an object from the pool, it doesn't automatically change it's parent. You must do that yourself, so unless you change the parent of the borrowed enemy it will still look like it is underneath the pool in the scene hierarchy.

I noticed that there are only four enemies underneath Enemy Pool in the hierarchy, it looks like one of them was re-parented after you borrowed it, but none of the others. It looks to me like what happening is this:

1. Create the pool with a capacity of five and five pre-allocated enemies.
2. One enemy is borrowed, and re-parented.
3. Four more enemies are borrowed, but not re-parented. Therefore, in the hierarchy they still look like they are part of the pool.
4. More enemies are borrowed, but now the pool is considered empty, which means that the pool has to allocate new enemies to meet the demand.

Also, it looks like you're going to want your pool's capacity to be larger than five. That number should be tuned to be a little bit larger than the number of enemies you expect to borrow from the pool based on the design of your game.

**Comment by dsternfeld7** [comment]
Since I saw that the issue is closed, I hope that you got it working and that that this is resolved for you! Please let us know if you need more assistance.

Thanks,

Dan

**Comment by SelaO** [comment]
Not really, I think the behavior I described is a bug, I just implemented my own pool.

**Comment by dsternfeld7** [comment]
If you send me a simple project that reproduces the issue I would be happy to look at it.

Thanks,

Dan

**Comment by dsternfeld7** [comment]
Here is some example code I just tested:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PoolTest : MonoBehaviour {

  public GameObject testObjectOne;
  public GameObject testObjectTwo;


  public GameObjectPool TestPool1 {
    get {
      // Get the pool manager.
      ObjectPoolManager poolManager = ObjectPoolManager.Instance;

      // Get the pool and return it if it already exists.
      string poolName = testObjectOne.name;
      GameObjectPool pool =
        poolManager.GetPool<GameObjectPool>(poolName);

      if (pool != null) {
        return pool;
      }

      // Create the pool if it doesn't exist yet.
      pool = new GameObjectPool(testObjectOne, 5, 5);
      poolManager.AddPool(poolName, pool);

      return pool;
    }
  }

  public GameObjectPool TestPool2 {
    get {
      // Get the pool manager.
      ObjectPoolManager poolManager = ObjectPoolManager.Instance;

      // Get the pool and return it if it already exists.
      string poolName = testObjectTwo.name;
      GameObjectPool pool =
        poolManager.GetPool<GameObjectPool>(poolName);

      if (pool != null) {
        return pool;
      }

      // Create the pool if it doesn't exist yet.
      pool = new GameObjectPool(testObjectTwo, 5, 5);
      poolManager.AddPool(poolName, pool);

      return pool;
    }
  }


  void Awake() {
    // Borrow 10 objects from the pool.
    // The pool only preallocated five, so it will first borrow the five
    // and then allocate five more to meet the demand.
    for (int i = 0; i < 10; i++) {
      GameObject testObj = TestPool1.Borrow();
      testObj.name = testObj.name + " " + (i + 1);
      testObj.transform.SetParent(null);
    }

    // Borow two from the second pool.
    GameObject obj1 = TestPool2.Borrow();
    obj1.name = obj1.name + " 1";
    obj1.transform.SetParent(null);

    GameObject obj2 = TestPool2.Borrow();
    obj2.name = obj2.name + " 2";
    obj2.transform.SetParent(null);

    // Return just one to the second pool.
    TestPool2.Return(obj2);
  }
}
```

Results:

<img width="264" alt="results" src="https://user-images.githubusercontent.com/20076332/32123807-77338a34-bb1a-11e7-9ab5-96f74a2126a0.png">

**Comment by SelaO** [comment]
That's exactly the problem, I don't think that it's an expected behavior that some pooled objects will be children of the pool and some don't.

Also, when you borrow from a pool that already preallocated several objects, why allocate a new different object when burrowing and not gives one of those that were allocated? what's the point of having them if you can't get them?

Lastly, the pool should have a `willGrow` toggle to enable or disable auto growing when burrowing, that's the point of a pool.
