### ISSUE TITLE
How to use the GVR reticle

### ISSUE THREAD

**Issue by SelaO** [googlevr/gvr-unity-sdk#764]
I want to use the reticle that comes with GVR with my game objects like it expands on the floor canvas that comes in the demo, but I don't see any special script on those buttons, and even if I change my objects to be UI layer, the reticle still doesn't expand on them. 

How can I make it expand on a cube for example?

![image](https://i.stack.imgur.com/9d6fI.gif)

I tried to follow the instructions on this [video ](https://www.youtube.com/watch?v=_YTVsLnK-XU)but I think it's too old because it had things that don't exist now (like "gaze input module").

Found using:
Google VR SDK version: v1.100.1
Unity version: 5.6.2f1
Phone manufacturer, model, and O/S version: Android
Viewer manufacturer & model: Irrelevant

**Comment by dsternfeld7** [comment]
Good question!

The reticle will expand if the object it is pointing at is considered "interactive". You can see the implementation in the function SetPointerTarget of [GvrReticlePointer](https://github.com/googlevr/gvr-unity-sdk/blob/master/Assets/GoogleVR/Scripts/Cardboard/GvrReticlePointer.cs).

So what makes something considered interactive?

An object is considered interactive if it implements the IPointerClickHandler, IPointerDownHandler, or IPointerDragHandler [event system handlers](https://docs.unity3d.com/ScriptReference/EventSystems.IEventSystemHandler.html). Alternatively, you can add the Unity script EventTrigger (which implements these interfaces) to the object. This indicates that the object will respond to pointer input. This is part of Unity's API for responding to events from the [Event System](https://unity3d.com/learn/tutorials/topics/user-interface-ui/ui-events-and-event-triggers).

Thanks,

Dan

**Comment by SelaO** [comment]
I added EventTrigger script and it works. Thanks.

**Comment by SelaO** [comment]
Is there a way to make it activate from further away? 
I want to activate on objects that are 100 units away.

**Comment by dsternfeld7** [comment]
Yes, on GvrReticlePointer you can change the property maxReticleDistance (assuming you are using the 1.100 version of the SDK).

Thanks,

Dan
