### ISSUE TITLE
Didn't find class "com.google.unity.UnityPlayerActivity"

### ISSUE THREAD

**Issue by rooskienz** [googlevr/gvr-unity-sdk#765]
<I'm getting this error on a new project when trying to build for Cardboard using latest Unity and GVR sdk>

Found using:
 * Google VR SDK version: v1.100.1
 * Unity version: Unity 2017.3.0b6
 * Phone manufacturer, model, and O/S version: Samsung Galaxy S8, Android 7.0

Steps to reproduce the issue:

1. Create new project with Unity 2017.3.0b6
2. Download and import [GoogleVRForUnity_1.100.1.unitypackage](https://github.com/googlevr/gvr-unity-sdk/releases/download/v1.100.1/GoogleVRForUnity_1.100.1.unitypackage)
3. Player Settings > XR Settings > <check> Virtual Reality Supported
4. Add Cardboard to the list of supported VR SDKs
5. Build & Run on Android device
6. App crashes

`adb logcat` log:
`java.lang.ClassNotFoundException: Didn't find class "com.google.unity.UnityPlayerActivity"`

**Comment by nathanmartz** [comment]
You must have a old SDK in there or something based on the only SDK as we
no longer distribute it require the Google unity player activity.

**Comment by rooskienz** [comment]
@nathanmartz thank you for your reply. Could you clarify please? Or if you could update your reply with punctuation marks, that would help as well. 
Cheers.

**Comment by nathanmartz** [comment]
The error you are getting is "Didn't find class "com.google.unity.UnityPlayerActivity". This class is no longer needed or used by our SDK. You have code somewhere that is expecting it to exist, and that's the problem. You need to remove or fix the code that is depending on this class.

**Comment by rusmaxham** [comment]
Do you have an AndroidManifest.xml file in your project somewhere?  That is where that classname would be specified.  You do not need an AndroidManifest.xml file just to support Daydream and Cardboard.
