### ISSUE TITLE
video surface ignore the rotate by setVideoLocationTransform

### ISSUE THREAD

**Issue by wangxiaogangan** [googlevr/gvr-unity-sdk#767]
when i  use video surface to render a rectangle mesh, i want to rotate the video surface to make it look at me when my head turned, by the api **setVideoLocationTransform**  matrix, i thought LocationTransform will ignore rotate, so is there a way to rotate the video surface in the future?

video surface also called GoogleVRVideoAsyncReprojection

Found using:
 * Google VR SDK version:  1.30
 * Unity version: 2017.2
 * Phone manufacturer, model, and O/S version:  pixel

**Comment by rusmaxham** [comment]
I'm looking into this now.

**Comment by rusmaxham** [comment]
I assume you have started with this document: https://docs.unity3d.com/Manual/VRDevices-GoogleVRVideoAsyncReprojection.html

The sample C# code doesn't copy the rotation of the video screen object into the transform passed into setVideoLocationTransform().  Replace the matrix (`wm`) calculation code with this instead:

```C#
    Matrix4x4 wm = transform.localToWorldMatrix;
    wm = Matrix4x4.Translate(-Camera.main.transform.parent.position) * wm;
    wm = wm * Matrix4x4.Scale(new Vector3(0.5f, 0.5f, 1));
```

**Comment by rusmaxham** [comment]
Please reopen this issue if that does not fix your issue.

**Comment by rusmaxham** [comment]
How are you moving the camera?  Are you moving the main camera itself or are you moving the main camera's parent?

**Comment by wangxiaogangan** [comment]
i try both way, when my head turned, the main camera's rotation changes in my project, so i think in my project i need change the code to
           `wm = Camera.main.transform.worldToLocalMatrix * wm;`
and 776 use `Camera.main.transform.worldToLocalMatrix`, surface translate its pos but ignore its rotation like the pic in 776

when i use `Camera.main.transform.parent.worldToLocalMatrix`, the surface will ignore translate and rotaion standing at original point no matter my head turned

Appreciate your help

**Comment by rusmaxham** [comment]
The problem with using the camera's transform is that the camera's position is not GVR's origin.  The camera's position is offset from GVR's origin by a neck model.  If you derive the video transform direct from the camera, there will be a small misalignment of the edges of the video quad.  The way to get the screen transform to line up is to parent your main camera under another game object and move that parent game object around your scene.  That way, the neck model will be applied relative to that parent game object and the screen to camera parent offset will stay correct and aligned.  All of the GVR demo scenes are configured this way, with the main camera underneath a Player game object.

**Comment by wangxiaogangan** [comment]
thanks for rusmaxham help, i got this work finally with a single rts matrix like below

`                            wm = Matrix4x4.Translate(d) *
                 Matrix4x4.Rotate(MediaTextureManager.GetInstance().leftPlaneGo.transform.rotation ) *
                 Matrix4x4.Scale( new Vector3(scaleWidth  / 2.0f , scaleHeight  / 2.0f, 1));
`
matrix multiply order is important for correct result

**Comment by rusmaxham** [comment]
Glad you got it working.
