### ISSUE TITLE
Camera is rotating slowly, automatically

### ISSUE THREAD

**Issue by marklinmao** [googlevr/gvr-unity-sdk#775]
The camera is always rotating slowly, automatically. It is very slow but it is rotating. As a result, you have to long-press the home button every few minutes to calibrate it. This problem can be observed in the most simple scene, it happens even for the daydream home menu! I guess it could be a bug of daydream platform or the sensor of my phone or the controller. Please confirm if it is a problem of daydream platform or the phone.

Found using:
 * Google VR SDK version: GoogleVRForUnity_1.100.1.unitypackage
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version: MacOS 10.13.1
 * Viewer manufacturer & model: Huawei mate 9 pro

Steps to reproduce the issue:
 1. Start a simple scene (e.g. Daydream home menu), look at the middle of the scene, tilt the phone, put it there for a few minutes(say 10 min), then put on your dream and you will see that it is no longer in the middle, it rotated left or right. (It depends on whether the phone was tilt left or right). As a result, you have to long-press the home button to calibrate it every few minutes.

Workarounds:
No workaround.

Additional comments:
I am not sure if this is a problem of daydream platform, the sensor in the phone or sensor in the controller. Please confirm the root-cause. If it is a problem of the phone, I need to contact the phone manufactor.

**Comment by rusmaxham** [comment]
This issue comes from poor sensors in the phone.

**Comment by marklinmao** [comment]
So, are you suggesting to contact Huawei for the problem?
