### ISSUE TITLE
In-editor Head rotation using alt+mouse stopped working on 1.110.0

### ISSUE THREAD

**Issue by synthercat** [googlevr/gvr-unity-sdk#778]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: ___1.110.0
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version: Windows 10

Steps to reproduce the issue:
 1. Make an empty new scene
 2. Switch to android
 3. Set min API to 19
 4. Enable VR support (Cardboard)
 5. Add a reticle and a GVREditorEmulator
 6. Enter play mode (alt + mouse does not work)

Workarounds:
Adding the `GvrControllerMain` solve this issue. But hey, I am building for cardboard, why do I need the GvrControllerMain?

**Comment by rusmaxham** [comment]
We are looking into this issue.

**Comment by sangarzucchi** [comment]
Hello there.

I have the same problem and I've found that when I "ToggleVR" using this code bellow, the head rotation works again:

`using System.Collections;
using UnityEngine;
using UnityEngine.VR;

public class ToggleVRMode: MonoBehaviour
{

    void Update()
    {

        if (Input.GetMouseButtonDown(0))
        {
            ToggleVR();
        }
    }

    void ToggleVR()
    {

        if (VRSettings.loadedDeviceName == "cardboard")
        {
            StartCoroutine(LoadDevice("None"));
        }
        else
        {
            StartCoroutine(LoadDevice("cardboard"));
        }
    }

    IEnumerator LoadDevice(string newDevice)
    {
        VRSettings.LoadDeviceByName(newDevice);
        yield return null;
        VRSettings.enabled = true;
    }
}`

Credits:
http://talesfromtherift.com/googlevr-cardboard-switch-between-normal-mode-and-vr-mode-at-run-time/

**Comment by dsternfeld7** [comment]
Here is the solution:

cl/175598708

I'm confused by sangarzucchi's response though. It doesn't look related to
this issue so I'm not sure exactly what the behavior s/he is reporting is.

-Dan

**Comment by rusmaxham** [comment]
This will be fixed in the next release of the SDK.

**Comment by fredsa** [comment]
Fixed in 1.120.0
