### ISSUE TITLE
Can I disable Distortion Correction? 

### ISSUE THREAD

**Issue by play123** [googlevr/gvr-unity-sdk#783]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: ___1.110.0
 * Unity version: ___2017.2 = p1
 * Phone manufacturer, model, and O/S version: ___le=mex 2
 * Viewer manufacturer & model: ___https://www.procusgo.com/collections/virtual-reality

Steps to reproduce the issue:
 1. ___When i use long text or make UI Like GEAR VR main HUD typs
2. if Viewer fov is more then 90 like 120 then its look invert.

is there way to remove distrotion or Disable.

**Comment by nathanmartz** [comment]
The only way to disable distortion correction currently is to disable VR mode.
