### ISSUE TITLE
GVRKeyboard Doesn't Work With Single Pass Rendering

### ISSUE THREAD

**Issue by Moncader** [googlevr/gvr-unity-sdk#786]
When single pass rendering is enabled, GVRKeyboard doesn't work.
When attempting to show it, logcat shows the below error:

`E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state`

Found using:
 * Google VR SDK version: v1.110.0
 * Unity version: 2017.2.0p1
 * Phone manufacturer, model, and O/S version: Pixel XL Android 7.1.2
 * Viewer manufacturer & model: Daydream View (2017 or first one)

**Comment by martinbilello** [comment]
Would it be possible to get more lines of the logcat, before and after that line? Thanks

**Comment by Moncader** [comment]
@martinbilello 
https://gist.github.com/Moncader/2a5341a859836ccb554894501da27108
I've uploaded a gist of the logcat.

This is a log from the official GVR SDK sample app keyboard demo.

**Comment by martinbilello** [comment]
Hi,

The Single Pass mode is a preview and is not currently supported by the Keyboard.

Thanks

**Comment by Moncader** [comment]
Are there plans to support it?
There are massive performance benefits to using Single Pass Rendering and it is a shame to have to disable that feature just for a rarely shown keyboard (the rest of the app works just fine).

**Comment by nathanmartz** [comment]
We're looking into support, yes. Regarding single pass rendering, have you profiled your app with and without it on device? In many cases it's benefits are more modest than you might expect (it varies quite a bit based on the graphics driver).

**Comment by Moncader** [comment]
@nathanmartz 
Our tests show a good 30-40% increase in FPS when it's enabled.

**Comment by nathanmartz** [comment]
Thanks for the detail. On which device running what OS?

**Comment by Moncader** [comment]
@nathanmartz 
As said in the original post

> Phone manufacturer, model, and O/S version: Pixel XL Android 7.1.2

**Comment by nathanmartz** [comment]
I don't think multi-view actually works on that phone/OS combo due to a driver bug. When did you last profile it with and without single pass stereo enabled?

**Comment by kristofgiber** [comment]
I second Moncader, found a huge performance improvement with single pass rendering on Gear VR platform using Samsing S7 Edge. I'm basically releasing updates for all of my games in Oculus store just to add single pass rendering.

**Comment by fredsa** [comment]
Single Pass (multi-view) support is currently in "Preview" and should probably not been used in production apps due to devices with bad drivers that fail to render content correctly.

Unity has recently added a warning about this. Here's a screenshot from Unity 2017.3.0p1:

<img width="466" alt="multi-pass-warning" src="https://user-images.githubusercontent.com/1235362/34633114-be6e992a-f22e-11e7-903d-ac231967838a.png">

Please use "Multi Pass" rendering for now.

**Comment by fredsa** [comment]
Filed issue #828 to track the feature request.
