### ISSUE TITLE
Daydream Controller stops working after pressing 'Home' button and then resuming Unity application

### ISSUE THREAD

**Issue by morganpage** [googlevr/gvr-unity-sdk#787]
When you quit a Unity application by pressing the 'Home' button and then from Daydream Home, restart the same Unity application, the daydream controller is unresponsive.

Found using:
 * Google VR SDK version: ___v1.110.0
 * Unity version: ___2017.2.0f3
 * Phone manufacturer, model, and O/S version: ___Google Pixel
 * Viewer manufacturer & model: ___Google Viewer

Steps to reproduce the issue:
 1. ___Build and run the GVRDemo, controller works fine.
 2. ___Click the 'Home' button
 3. ___Restart the GVRDemo, controller is unresponsive 

Workarounds:
___None

Additional comments:
___

**Comment by morganpage** [comment]
Seems to be a Unity 2017.2.0f3 bug, went back to Unity 2017.1.0f3 and it works fine.

**Comment by vinhui** [comment]
see #748
Updating to 2017.2.0p1 fixes this issue
