### ISSUE TITLE
keypad not showing up in orientation change  in  iOS 11

### ISSUE THREAD

**Issue by ashunkhs** [googlevr/gvr-unity-sdk#788]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: ___0.9
 * Unity version: ___2017.1
 * Phone manufacturer, model, and O/S version: ___iOS 11
 * Viewer manufacturer & model: ___iOS 11

Steps to reproduce the issue:
 1. i am using an Text-input field . its working fine when my app in portrait mode . 
 2. once GVR change the orientation from portrait mode to landscape and back to portrait mode keypad not showing . 

Additional comments:
___When i change the scene A ( portrait mode ) to scene B (Landscape mode ) and come back to previous scene  the mobile keypad does not showing when touch the  Text-input field

**Comment by rusmaxham** [comment]
Can you send a simple project that reproduces the issue?

**Comment by rusmaxham** [comment]
Feel free to reopen this issue if you're still experiencing it.
