### ISSUE TITLE
Unity 2017.2 and 5.6.4 not working with GVR 1.110 manifest merging error

### ISSUE THREAD

**Issue by way2sky** [googlevr/gvr-unity-sdk#789]
I only want to build the example scene for cardboard but I am seeing the now well-known manifest merge problem. I even tried testing the custom unity package from the link below but that still didn't build as well. 
https://youtu.be/Qn5BCG8SPN8

The previous thread on this topic:
https://github.com/googlevr/gvr-unity-sdk/issues/524

Anyone encounter this old issue again with the latest versions of unity and gvr?
Please download the example project showing this error here:
https://www.dropbox.com/s/e0cerk9r0rwtwsr/TestGVR.zip?dl=0

Found using:
 * Google VR SDK version: 1.110
 * Tested using both Unity version: 5.6.4 and 2017.2

Steps to reproduce the issue:
 1. Create new empty unity 3d project.
 2. Import gvr 1.110
 3. Set scene to GVR demo 
 4. Switch to android (make sure the scene runs in editor) and build according to official instructions (min android sdk is 19, target at 24 or highest, adding cardboard after checking virtual reality supported in unity, etc.)
 5. Android manifest merge error is produced.

Best,
Sean

**Comment by fredsa** [comment]
Thanks for providing the repro project. I was able to build an Android APK using your project using Unity 2017.2.0p1. I didn't chance any of the settings after opening the TestGVR.zip project you provided.

Can you include the full console error messages text you see when you try to build?

**Comment by fredsa** [comment]
Also, please check that the correct value is set for the Android SDK under "External Tools" section of the Unity preferences.

**Comment by way2sky** [comment]
Thanks for your quick reply. 

Error:Invalid command manifmergerfallback
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_152\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/AndroidStudioSDK\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error:Invalid command manifmergerfallback
]
stdout[

]
exit code: 64
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Error building Player: 3 errors

Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditor.BuildPlayerWindow+BuildMethodException: 4 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x00207] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:172 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by fredsa** [comment]
It sounds like you might be running into Unity case [888859](https://issuetracker.unity3d.com/issues/android-build-fails-when-the-latest-android-sdk-tools-25-dot-3-1-version-is-used).

If so, you can either:
1. Upgrade to a version of Unity that fixes this issue
1. Downgrade the Android SDK 'tools' folder to a version compatible with your version of Unity

To try the tools downgrade option:
1. Rename `C:\AndroidStudioSDK\tools` to `C:\AndroidStudioSDK\tools-backup-for-issue789`
2. Download https://dl-ssl.google.com/android/repository/tools_r25.2.5-windows.zip
3. Extract the zip file into `C:\AndroidStudioSDK\`, which will create a new, downgraded `C:\AndroidStudioSDK\tools`
4. Try building your APK from Unity again.

**Comment by way2sky** [comment]
Thanks! This worked for Unity 2017.2.0f3

**Comment by rusmaxham** [comment]
If you're doing Daydream development, we recommend you update to the latest 2017.2.0 patch release as 2017.2.0f3 has an issue where the Daydream controller will stop working after background > foreground.
