### ISSUE TITLE
Daydream not supported in Editor Mode (Unity, Pixel2, v1.110, 5.6.4p3)

### ISSUE THREAD

**Issue by LazyBrush** [googlevr/gvr-unity-sdk#791]
Hi,

I cannot seem to get the Instant Preview working.   Am I doing something wrong?

In the console I get -
'VRDevice daydream not supported in Editor Mode. Please run on target device'

I can build and install the APK and that works fine.

I've done everything on [the google vr instant preview page](https://developers.google.com/vr/tools/instant-preview)

Found using:
 * Google VR SDK version: 1.110
 * Unity version: 5.6.4p3
 * Phone manufacturer, model, and O/S version: Google Pixel 2 XL, Android 8.0.0
 * Viewer manufacturer & model: Daydream 2017

Steps to reproduce the issue:
 1. Start with empty project, import google VR SDK
 2. Drop the GVRDemo into Scene Hierachy
 3. Hit the play button

  cheers

LB

**Comment by rusmaxham** [comment]
did you set the active platform to Android?  instant preview doesn't work
when targeting anything other than Android.

**Comment by LazyBrush** [comment]
Hi Rus,

  Thanks, yes.  Platform is set to Android.  I can build the APK ok and it builds, installs and runs fine.

  I just can't get the Instant Preview working, and I get the above error.

  The Preview App is running, and I can select USB or network connection.  (I'm using USB)

  I am thinking I've probably just got a new phone and new OS and I need to wait for an update?

  But I thought I should post incase I'm doing something dumb.

  Thanks,

LB

**Comment by gstanlo** [comment]
Do you receive any output in the console window? I've tested on 5.6.4f1 and I'll get the message 

> Instant Preview 1.1.0

and
>Connected to Instant Preview.

Which OS are you running Unity on?

**Comment by LazyBrush** [comment]
Hi gstanlo,

In Console I get -

```
VRDevice daydream not supported in Editor Mode.  Please run on target device.

Instant Preview Version: 1.1.0

Device supports positional tracking!

Connected to Instant Preview.

Failed to read from controller emulator app event socket.
Verify that the controller emulator app is running.
  at Gvr.Internal.EmulatorClientSocket.ProcessConnection (System.Net.Sockets.TcpClient tcpClient) [0x00043] in /Users/andrewwinton/MyCode/Unity VR1/Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:176 
  at Gvr.Internal.EmulatorClientSocket.phoneConnect () [0x00054] in /Users/andrewwinton/MyCode/Unity VR1/Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:101 
  at Gvr.Internal.EmulatorClientSocket.phoneEventSocketLoop () [0x00017] in /Users/andrewwinton/MyCode/Unity VR1/Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:73 
UnityEngine.Debug:LogWarningFormat(String, Object[])
Gvr.Internal.EmulatorClientSocket:phoneEventSocketLoop() (at Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:76)

There are 2 audio listeners in the scene. Please ensure there is always exactly one audio listener in the scene.
(lots of these ^^^ )

Tiled GPU perf. warning: RenderTexture color surface  (2560x1440) was not cleared/discarded, doing <run with profiler for info>
```
I did also get a line which complained about adb
```
Android Debug Bridge (`adb`) command not found.
Verify that the Android SDK is installed and that the directory containing `adb` is included in your PATH environment variable.
  at Gvr.Internal.EmulatorClientSocket.setupPortForwarding (Int32 port) [0x000f0] in /Users/andrewwinton/MyCode/Unity VR1/Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:153 
  at Gvr.Internal.EmulatorClientSocket.phoneConnect () [0x00039] in /Users/andrewwinton/MyCode/Unity VR1/Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:97 
  at Gvr.Internal.EmulatorClientSocket.phoneEventSocketLoop () [0x00017] in /Users/andrewwinton/MyCode/Unity VR1/Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:73 
UnityEngine.Debug:LogWarningFormat(String, Object[])
Gvr.Internal.EmulatorClientSocket:phoneEventSocketLoop() (at Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:76)
```
But I found [this discussion, about half way down](https://forum.unity.com/threads/5-6-0b3-linux-daydream-controller-emulator-wont-work-adb-command-not-found.451423/).  Their fix was to remove the '-l' in the command.   But that was January, and it is now on a different line, so I am suspicious about this one.

Anyway, I still can't get preview working.

I'm running on Mac OSX High Sierra 10.13.1

Any ideas?

Thanks again,

LB

**Comment by gstanlo** [comment]
Hmmm strange, when Unity is open and previewing, can you open a terminal and run `adb reverse --list`? It should show a line like 

> (reverse) tcp:49838 tcp:49838

Another common problem is having two different adb versions on your computer. If you type `which adb`, does that correspond to a different path in your unity preferences? Additionally, do the two have different versions if you run `adb version`?

**Comment by LazyBrush** [comment]
Thanks, both seem ok i think..

```
My-MBP:Unity andy$ adb reverse --list
(reverse) tcp:49838 tcp:49838

My-MBP:Unity andy$ which adb
/Users/andy/Library/Android/sdk/platform-tools/adb
My-MBP:Unity andy$ 
```

That adb is the same as in Unity -> Preferences... -> External Tools ; Android ; SDK

Looking [at this post it seems they think the pixel just cant do editor mode preview?](https://stackoverflow.com/questions/44509873/running-google-vr-unity-daydream-app-on-google-pixel)

Can you confirm it does work for the Pixel 2 XL ?

**Comment by MGutensohn** [comment]
Any success in figuring this out? It appears I'm having the exact same problem.

**Comment by LazyBrush** [comment]
Hi MG,

   Nope.   I've also not managed to find anyone that can confirm it does work for the Pixel 2 XL.

   For now it takes 40 seconds to compile, load, and run a new binary.   A bit of pain, but I've had much worse.

**Comment by gstanlo** [comment]
Apologies I haven't found anything obvious from the logs from Pixel 2s yet, though our analytics indicate some Instant Preview activity from Pixel 2 devices. I have one ordered and should be able to test it myself soon.

**Comment by ashishsfb** [comment]
The adb command not found is because you probably haven't added adb in the environment path variable. I had the same issue, I tried this but then I'm also stuck with not able to connect to instant preview app.

**Comment by LazyBrush** [comment]
There was a new version of Unity released on the 19th Dec.  

Now Instant Preview with the Pixel 2 XL Works!  Yay!

This is on OSX 10.13.2 and Google VR v 1.110.0 and Unity 2017.3.0f3.

There was a little fiddling with the settings.   VR supported moved to a new tab 'XR Settings'.  I have to compile and run on the device once.   After that the play button works.  Sweet.

Thanks Unity, Google, Community!

LB
