### ISSUE TITLE
Wierd problem: can't change camera orientation with mouse

### ISSUE THREAD

**Issue by linglonglinglong** [googlevr/gvr-unity-sdk#793]
Running the Demo scene. Holding shift and move the mouse should change the orientation right? The view doesn't change! In the Scene panel I can see a small black thing rotating, but in the Game panel nothing moves... I've not touched Unity for a while due to a health issue. Before that the scene was good! When I come back, without changing anything, the problem comes...

By the way, when I hold control and move my mouse, the scene rotates. 

Found using:
Google VR SDK version: 1.100.1
Unity version: 2017.2.0f3
Phone manufacturer, model, and O/S version: Samsung S7 Edge, Android 7.0
Viewer manufacturer & model: just on the phone.

**Comment by dsternfeld7** [comment]
Holding shift and moving the mouse is for changing the orientation of the controller. Instead, hold alt and move the mouse to change the orientation of the camera.

The controls for moving the camera in the editor are visible in the inspector when selecting the prefab **GvrEditorEmulator**. For the controller editor controls, you can look at the prefab **GvrControllerMain**.

Thanks,

Dan
