### ISSUE TITLE
Unable to change field of view in gvr v1.100.1 : Stereocontroller missing.

### ISSUE THREAD

**Issue by Sourcetreehugger** [googlevr/gvr-unity-sdk#795]
I recently updated our game from GVR 1.30 Unity 5.5.2 to Unity 2017.2 GVR v1.100.1 because vr view was heavily distorted on the S7. After updating to the newest gvr version, I cannot seem to change the field of view of the VR camera. In earlier versions of gvr I was able to change the field of view of the camera through stereocontroller.cs. This class is missing in the lasts gvr. Now I cannot recreate the binocular effect that I have to use for the game.

Camera.main.fieldofview changes the fov in editor mode, but not in vr.

Found using:
 * Google VR SDK version: v1.100.1
 * Unity version: 2017.2
 * Phone manufacturer, model, and O/S version: Galaxy S7 android 7.0 (not related to current issue)
 * Viewer manufacturer & model: Samsung (not related to current issue)

Steps to reproduce the issue:
 1. Add Camera.main.fieldOfView = 20; to any start or update function active in the scene. Use gvrdemo for example.
 2. Build GVR demo app to phone.
 3. See native FOV

Workarounds:
Did not find any yet. Maybe going to try turning off vr mode in the scene and camera and show fov in mono, duplicating cameras. Anyhow, it's going to effect performance. 

Additional comments:
___

**Comment by fredsa** [comment]
To scale the effective size of the player (so that the world looks smaller / larger) while keeping world scale unchanged (so that physics continues to work correctly), you can adjust the `transform.localScale` of a game object that is a parent of the main camera.

To shrink the player by 10x (world appears bigger):
```
Camera.main.transform.parent.localScale = new Vector3(.1f, .1f, .1f);
```

To enlarge the player by 10x (world appears smaller):
```
Camera.main.transform.parent.localScale = new Vector3(10f, 10f, 10f);
```


The behavior you're seeing with respect to camera field of view is as expected. The Google VR SDK is now natively integrated with Unity, which means the camera `fieldOfView` will be automatically set while your game is in VR mode, based on the optics and design of the user's viewer.

**Comment by Sourcetreehugger** [comment]
Hey Fredsa, thanks for your quick reply. Scaling the player (main camera) results in a translation of the main camera.  This indeed results an 'enlarged' effect of the world. However this is because the player is being translated. Rotating the player results in strange behaviour where rotation and translation clash. For instance looking at the floor results in the camera translating through the floor. 

I found a hacky workaround for the issue but it's probably not the best solution: Create an extra camera and set the field of view at your desired value. Render the camera to a render texture (a quad). Place the quad in front of the main camera and make it a child of the main camera so it rotates with your player. Enable the quad and binocular camera when you enter binocular mode. 

Here is a screenshot of a test with scaling the main camera.

![screenshot_1](https://user-images.githubusercontent.com/25456778/33435493-9fad9f9e-d5e2-11e7-921c-1b1c2f825507.png)

**Comment by fredsa** [comment]
Ah, right. One more thing: you will need to adjust the player height as well. Otherwise, the scaled-up effects of the neck model might allow the player to see below the floor, which is what I think you're seeing.

Here's a test script you can attach to the Player game object in the GVRDemo scene:
```
public class ScaleController : MonoBehaviour {

  // Typically (0, 1.6, 0), assumes player is 1.6m tall.
  Vector3 initialPosition;

  void Awake() {
    // Capture initial player position, so we can later scale height.
    initialPosition = transform.localPosition;
  }

  void Update() {
    if (GvrControllerInput.IsTouching) {
      // For testing, use touchpad to select a scale, approximately 0.1 - 10. 
      float scale = 10f * GvrControllerInput.TouchPos.x;
	
      // Scale player game object.
      transform.localScale = new Vector3(scale, scale, scale);

      // Set scale-adjusted player height.
      transform.localPosition = new Vector3(initialPosition.x,
                                            initialPosition.y * scale,
                                            initialPosition.z);
    }
  }
}
```

**Comment by Sourcetreehugger** [comment]
Hey Fredsa. Thanks for your efforts in trying to help me out here. I tried your method, but still no succes for me. This script attached to the player root results into same behaviour as before (above). This script attatched to the main camera results in no change. 

I deciced to stick with the render texture method as I described earlier. It is a more expensive render method, but it works for me now. I can get away with it with proper culling settings. Anyhow, thanks for your help :)

**Comment by fredsa** [comment]
Can you try:
1. Start with the default GVRDemo scene
1. Change the "Player" game object's local position: from (0, 1, 0) to (0, 1.6, 0)
1. Attach the ScaleController script to that "Player" game object

The "Main Camera" game object should be a child of the "Player" game object with a local position of (0, 0, 0).

(Attaching the script to the "Main Camera" won't work, because Unity will override the location position and rotation of the camera while in VR mode.)

**Comment by fredsa** [comment]
Let us know if you were unable to get this working.

Leaving this issue open since adjusting perceived player world scale is undocumented.

**Comment by Sourcetreehugger** [comment]
Hey Fredsa,

I'm currently on Unity 2017.3. I have found a solution for the problem so I wanted to give an update. Please note that the update only works on a VR device (not in the editor).

Changing field of view is as follows when your device is in VR mode (Tested on Android Oneplus 3).

`using UnityEngine.XR;

//Code for changing FOV
void Start()
{
      XRDevice.fovZoomFactor = 2;
}`

**Comment by fredsa** [comment]
Glad you got it working.

I'll note that I don't think changing `fovZoomFactor` is the right solution for most apps. If you set `fovZoomFactor = 2f` and then rotate your head left/right, you'll see that the world is moving at a different speed than your head is turning. It's like the player is wearing a pair of magnifying goggles, like a pair of strong eye glasses. If that's the effect you want, then go for it.
