### ISSUE TITLE
GVR CHECK failed during launch VR apk

### ISSUE THREAD

**Issue by victorchentw** [googlevr/gvr-unity-sdk#796]
I encounter a assert error during launch my VR apk as below.
what the log mean of "expression='"(size.width) > (0)"' (0 > 0)" ?

11-28 17:23:29.896 17990 17990 I GVR     : [vr/gvr/capi/src/gvr.cc:96] Initialized GVR version 1.60.1
11-28 17:23:29.899 17990 18073 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-28 17:23:29.899 17990 18073 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
11-28 17:23:29.906 17990 17990 D GvrLayoutFactory: Loaded GvrLayout from SDK.
11-28 17:23:29.931 17990 18082 D ConfigUtils: Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params (No such file or directory)
11-28 17:23:29.931 17990 17990 E SdkDaydreamTouchListener: Null deviceParams or no alignment markers found.
11-28 17:23:29.932 17990 18006 F GVR     : [vr/gvr/capi/src/gvr.cc:439] CHECK failed: expression='"(size.width) > (0)"' (0 > 0)
11-28 17:23:29.933 17990 18006 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 18006 (UnityMain)

Found using:
 * Google VR SDK version: 1.60.1
 * Unity version: 2017.1
 * Phone manufacturer, model, and O/S version: apq8098_latv, android 8.0.0
 * Viewer manufacturer & model: any

Steps to reproduce the issue:
 1. launch VR apk

**Comment by rusmaxham** [comment]
Thanks.  We will take a look.

**Comment by jdduke** [comment]
Hi @victorchentw, would you mind attaching a bug report that captures the issue? Or at least including the result of "adb shell dumpsys display | grep DisplayInfo"?

The assertion you're seeing is applied to the buffer size specification set by the client, which is required to be non-zero. If the client (in this case, Unity) is using the result of the recommended render target size, it's possible there's a bogus value being reported for the device's display metrics.

Are you seeing this issue for all Daydream/Cardvborad apps? Or just this particular app?

**Comment by victorchentw** [comment]
Hi @jdduke, 
  I attached the result of "adb shell dumpsys display | grep DisplayInfo" for reference.
  how should I get the bug report for this issue? I would like to provide it to you.
  and I run some cardboard app on the device and all of those app has same problem with GVR assertion
  
[dumpsys_DisplayInfo.txt](https://github.com/googlevr/gvr-unity-sdk/files/1550777/dumpsys_DisplayInfo.txt)

**Comment by jdduke** [comment]
It looks like the device is reporting a DPI value of "0" for the horizontal and vertical DPI:

density 320 (0.0 x 0.0) dpi

**Comment by jdduke** [comment]
Can you share some additional information about this piece of hardware, and its specs? Google isn't revealing much.

**Comment by rusmaxham** [comment]
Closing.  If this is still an issue, please reopen.
