### ISSUE TITLE
Daydream Home still shows old app icon from its cache after changing app icon

### ISSUE THREAD

**Issue by SwitchNZ** [googlevr/gvr-unity-sdk#797]
When updating the Daydream Home Icon for your application in Unity it doesn't update in the daydream app unless you clear the cache

Found using:
 * Google VR SDK version: 1.100.1
 * Unity version: 2017.2.0p2
 * Phone manufacturer, model, and O/S version: 
Tested so far and have this issue:
Google Pixel, Android 7.0 
Google Pixel, Android 8.0
Google Pixel XL, Android 8.0

Steps to reproduce the issue:
 1. Update the app icon in Unity within the Player settings under daydream VR
 2. Push the application to your phone or device - one that had a previous version of the app
 3. The previous icon will show on the daydream home screen

Workarounds:
Deleting the daydream cached data from the application storage menu fixes the issue.

Additional comments:
___

**Comment by fredsa** [comment]
Thanks, Rory. Clearing the Daydream Home app's cache is currently the best workaround.

**Comment by rusmaxham** [comment]
This should be fixed in Daydream Home now.
