### ISSUE TITLE
 It can work at Unity but it doesn't work at Android mobile phone.

### ISSUE THREAD

**Issue by wlsl8135** [googlevr/gvr-unity-sdk#800]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: 1.70 or 1.100
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version: Galaxy S7, Android, Nougot 7.0
 * Viewer manufacturer & model: ___

Steps to reproduce the issue:
Unity : 2017.2.0f3
Android SDK : 2.3.2
Java : 1.8
GVR SDK : 1.70
This is my tool version.
I want to make gaze to click. but It can work at Unity but it doesn't work at Android mobile phone.

Workarounds:
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
public class gaze : MonoBehaviour
{
    bool gazeat = false;
    public float MyTime = 0.0f;
    public Transform RadialProgress;
    RaycastHit hit;
    void Start()
    {
        MyTime = 0.0f;
        RadialProgress.GetComponent<Image>().fillAmount = MyTime / 2;
    }
    public void reset()
    {
        MyTime = 0.0f;
        RadialProgress.GetComponent<Image>().fillAmount = MyTime / 2;
    }
   void Update()
    {
        MyTime += Time.deltaTime;
        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        RadialProgress.GetComponent<Image>().fillAmount= MyTime/2;
        if (MyTime >= 2.0f)
        {
            if (Physics.Raycast(ray, out hit))
            {
                ExecuteEvents.Execute(hit.transform.gameObject, new PointerEventData(EventSystem.current), ExecuteEvents.pointerDownHandler);
                reset();
                this.enabled = false;
            }
        }

    }
}
```
Additional comments:
___
![question](https://user-images.githubusercontent.com/26565404/33518184-3d1a7ffc-d7d4-11e7-97a4-e9a3cb986c1c.png)
![mobile](https://user-images.githubusercontent.com/26565404/33518186-41ce843a-d7d4-11e7-90ed-4d47944997c0.jpg)

**Comment by fredsa** [comment]
Looks like you're trying to use `Input.mousePosition` while in VR where there is no mouse. You can use the pointer input system provided by the Google VR SDK, or you can continue to use raycasting. 

For gaze based raycasting, you can cast a ray from the main camera's position, using the camera's `transform.forward` direction.

While in the editor you can simulate head (camera) movement using the mouse + keyboard controllers.
