### ISSUE TITLE
Can Single-Pass Stereo Rendering(Gpu Instanced) support Android?

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#801]
Unity 2017.2 released, it supports Single Pass Stereo Rendering (Gpu Instanced) for DirectX 11 devices.
For Android devices, we can only use Single Pass Stereo Rendering(Multi-View). There are a lot of issues for Multi-view Stereo Rendering.  Why NOT Unity support Single Pass Stereo Rendering (Gpu Instanced) for Android devices? Unreal also only support Stereo Rendering (Gpu Instanced) for Windows device. 
Why?

**Comment by rusmaxham** [comment]
On Android devices that fully support instanced single-pass rendering, Unity automatically uses instanced single-pass rendering.  However, there are many devices whose instanced single-pass rendering has bugs that prevent it from working properly.  Daydream automatically detects devices with full support for instanced single-pass rendering and enables it accordingly.
