### ISSUE TITLE
delete grey screen insert phone your carboard

### ISSUE THREAD

**Issue by Sanoend** [googlevr/gvr-unity-sdk#802]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: mixed from 1.0.1 to v1.110.0 (We support Gvr for compatibility with the old code, but we use it internally UnityEngine.XR)
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version: nexus 5x
 * Viewer manufacturer & model: carboard

When we use native unity gvr with cardboard, can we remove grey screen "insert phone your carboard" when vr turning on?

since sometimes on a gray screen we get an error: "OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range"

We re-read everything on this issue but it does not help us

**Comment by rusmaxham** [comment]
Yes, in Player Settings for iOS, under Player Settings for iOS > XR Settings > VR SDKs > Cardboard, click the triangle to get more Cardboard settings.  There you will find an Enable Transition View checkbox to control the showing of the transition screen.

![screen shot 2017-12-07 at 3 23 41 pm](https://user-images.githubusercontent.com/13911074/33743716-d5d8a426-db62-11e7-8c93-ab4ec5775556.png)
