### ISSUE TITLE
Video starts with a very low resolution: GVRVideoTextures.cs

### ISSUE THREAD

**Issue by devesh2605** [googlevr/gvr-unity-sdk#804]
I have been using Google VR SDK for a Video aggregation platform and using the Demo Test Sphere Scene for playing video I am able to play the video but the video starts from with a very low bitrate however there is option for setting the Initial resolution with highest or a specific resolution but it does not seems to work. The video works well after 10 seconds but from a consumer point of view this is not acceptable.

Found using:
 * Google VR SDK version: GVR 1.4
 * Unity version: 5.4.2f
 * Phone manufacturer, model, and O/S version: Samsung S6 Edge running Android 7.1
 * Viewer manufacturer & model: ___ Samsung S6 Edge

Steps to reproduce the issue:
 1. Play the test sphere scene with any HLS stream

**Comment by rusmaxham** [comment]
This bug has been fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases) of the SDK.  Sadly, it no longer supports Unity 5.4.2.
