### ISSUE TITLE
Google signin daydream

### ISSUE THREAD

**Issue by vinhui** [googlevr/gvr-unity-sdk#805]
Does the [Google signin](https://github.com/googlesamples/google-signin-unity) work from daydream? Or do we have to ask the user to take their phone out of their headset, let them select their account, and put it back in?

**Comment by rusmaxham** [comment]
I'm not familiar with that plugin, but if it launches any 2D activities to accomplish sign-in, which I suspect it does, you will not be able to use this entirely from within VR.  Our [permissions demo](https://developers.google.com/vr/unity/demos) in the SDK demonstrates the best practice for managing a VR > 2D > VR flow.

**Comment by vinhui** [comment]
But just to confirm, there's no daydream integration for google sign in, also not for native applications?

**Comment by rusmaxham** [comment]
Not currently for in VR, native or engine, no.  I suggest filing a feature request with the Google signin  repo.
