### ISSUE TITLE
not working VR on android 8.1

### ISSUE THREAD

**Issue by Sanoend** [googlevr/gvr-unity-sdk#806]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: 1.4 - 1.110
 * Unity version: 2017.2
 * Phone manufacturer, model, and O/S version: nexus 5x

see screen
![android8 1](https://user-images.githubusercontent.com/2202139/33780887-74252fe0-dc63-11e7-917f-2de8e4a8310e.jpg)

Version GVR to 1.4 and Unity3d less than 5.6 work fine.

The promise of native support turned out to be very bad. We spent more than 300 man hours, but we can not transfer the project to native support and units 5.6 and higher. This is probably one of the worst SDKs for all my experience ((((We solved more than 80 problems in the transition, but new, new and new appear ....

Perhaps you will compile external libraries for Unity 2017 and use GVR 1.0.1 on it at least you could work.

**Comment by rusmaxham** [comment]
I'm sorry your upgrade process was so unpleasant.  Is there a specific issue you would like assistance with?

We won't be providing any support for old versions of the SDK at this time.

**Comment by Sanoend** [comment]
the actual problem on the screen above (and on the latest version of GVR too ...) only appears on android 8.1

**Comment by rusmaxham** [comment]
Can you send me a Unity project that reproduces the issue?  I'm not able to diagnose this problem from a single image.

**Comment by Sanoend** [comment]
Any GVR project (gvr demo etc.). But the problem is solved by beta Unity 2017.3.0f2

**Comment by rusmaxham** [comment]
Sounds like you have a solution.  Please reopen if you need further assistance with this.
