### ISSUE TITLE
How can I  make GvrReticlePointer Radial Progress

### ISSUE THREAD

**Issue by KevinRocka** [googlevr/gvr-unity-sdk#807]
<Brief summary of the issue you encountered>
Hi， Im a new hand for unity , I hava some question who can help me out ，is there is a demo Like （OSVR/Unity-VR-Samples）to integration the gaze input who can make GvrReticlePointer to radial progress ， because there is no controller for cardboard Like Daydream Platform。 Who can help me out.

Found using:
 * Google VR SDK version: v1.110.0
 * Unity version: 5.6.4f1

**Comment by rusmaxham** [comment]
I'll try to find someone who can help you with this issue.

**Comment by fredsa** [comment]
Unity has an article you might be interested in:
https://unity3d.com/learn/tutorials/topics/virtual-reality/interaction-vr

Look for the head "SelectionRadial and SelectionSlider" heading.

**Comment by KevinRocka** [comment]
I have solve this issue by unity tutorials : "https://unity3d.com/learn/tutorials/topics/virtual-reality/interaction-vr". Thanks alot
