### ISSUE TITLE
Change GvrEditorEmulator doesn't work in IOS device

### ISSUE THREAD

**Issue by erikbv99421** [googlevr/gvr-unity-sdk#808]
I want to get head tracked manipulation object setting the head position en rotation to my object in GVREditorEmulator.cs
`
UpdateHeadPositionAndRotation();

IEnumerator<Camera> validCameras = ValidCameras();
while (validCameras.MoveNext()) {
  Camera cam = validCameras.Current;
  // Default code
  //Cam.transform.localPosition = HeadPosition * cam.transform.lossyScale.y;
  MyObject.transform.localPosition = HeadPosition * cam.transform.lossyScale.y;

  // Default code
  //Cam.transform.localRotation = HeadRotation;
  MyObject.transform.localRotation = HeadRotation;
}
`

Found using:
 * Google VR SDK version: v1.110.0
 * Unity version: 5.6
 * Phone manufacturer, model, and O/S version: iPhone 7 plus
 * Viewer manufacturer & model: ___

Steps to reproduce the issue:
 1. Modify the code as I said below
 2. Build and run in iOS device 

Workarounds:
___

Additional comments:

Unity editor works:
<img width="1143" alt="screen shot 2017-12-12 at 18 40 39" src="https://user-images.githubusercontent.com/6623343/33902877-590423a2-df6e-11e7-96d6-80e119e54457.png">
<img width="359" alt="screen shot 2017-12-12 at 18 41 17" src="https://user-images.githubusercontent.com/6623343/33902881-5b8e4b2a-df6e-11e7-9e4b-23954193d570.png">

iPhone 7 plus doesn't work:
![img_4671](https://user-images.githubusercontent.com/6623343/33902896-684742a4-df6e-11e7-8e57-b2224f03b32e.JPG)

Desired result:
![img_0644](https://user-images.githubusercontent.com/6623343/33902987-a432117c-df6e-11e7-9a4d-7a958a8e7f07.png)
![img_2355](https://user-images.githubusercontent.com/6623343/33902988-a464c478-df6e-11e7-994b-d17c21739aa8.png)

**Comment by rusmaxham** [comment]
You can achieve the same effect by placing the object you want to do tracked manipulation with as a child of the Main Camera, then attach a script to the object and in it's Update method do this:

```C#
transform.localRotation = Quaternion.Inverse(Camera.main.transform.localRotation);
```

If you want the lighting to be fixed to the camera, move your lights to be children of the main camera as well.

**Comment by erikbv99421** [comment]
Thank you so much. It worked for me. Have a nice day.

**Comment by rusmaxham** [comment]
Happy to hear.
