### ISSUE TITLE
The screen of the first frame turns black(GVR SDK 1.3.0 Unity5.5.3)

### ISSUE THREAD

**Issue by k-isuzu** [googlevr/gvr-unity-sdk#809]
The screen of the first frame turns black(GVR SDK 1.3.0 Unity5.5.3)

The screen of the 1st frame becomes black.
In the first frame it is expected that writing to RenderTextrue has not been done.
All the images are screenshots of the first frame of GVRDemo.unity.

![01](https://user-images.githubusercontent.com/34502619/33927000-cc00cd96-e023-11e7-9fcb-64f72b5c9ded.png)

It does not occur if VR Mode Enable is false.

![02](https://user-images.githubusercontent.com/34502619/33927010-d3c88d98-e023-11e7-851c-f7b09a584b02.png)

Using Component -> GoogleVR -> Update Stereo Cameras
If you generate the left and right cameras in advance and set Camera component Enable to true, writing to RenderTextrue will succeed.
But why Canvas (World Space) is not rendered.

![03](https://user-images.githubusercontent.com/34502619/33927015-d814e3d8-e023-11e7-9cc6-dd51435138c0.png)

In my game I am using UI.Image for fade in Canvas (World Space).
When using white fade, even if only 1 frame is taken, it becomes bad UX if the screen is black.
If you use Quad instead of UI.Image, smooth fade can be implemented, but is there a better solution?
I also want to know why Canvas (World Space) is not drawn.

 * Google VR SDK version: 1.3.0
 * Unity version: 5.5.3

**Comment by rusmaxham** [comment]
I'm sorry to say that we don't support that version of Unity or that version of the GoogleVR SDK for Unity anymore.  Are you at all able to use more recent versions of Unity and the GVR SDK?

**Comment by k-isuzu** [comment]
It is very difficult to update the SDK version of my project.
I confirmed GVRDemo.unity (Unity 5.6.4, GVR Unity v1.40.0) the same problem occurred.
