### ISSUE TITLE
Video .mp4 black background texture

### ISSUE THREAD

**Issue by Flameshot** [googlevr/gvr-unity-sdk#810]
Hello. I have a .mp4 video where there is a woman model who is turning around, but my movie has a black background. I tried with every shader to remove the black texture from background but nothing.
I placed that video on a VR Room.

Anyone has an idea how can I remove that black texture or what shader should I use or material?

This is my video. https://we.tl/F8sdJY4cva

Found using:
 * Google VR SDK version: 1.100.0
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version: LG Nexus 5x

**Comment by rusmaxham** [comment]
You'll need to edit the shader to add this functionality.  I did this by editing VideoUnlitShader.shader in the GVR SDK for Unity and making the following changes:

First, enable alpha blending by adding a new line after the line containing `Cull off`:

`  Blend SrcAlpha OneMinusSrcAlpha`

Then changed the fragment shader inside `#ifdef FRAGMENT` block to look like this:

```GLSL
  void main() {
    vec4 color = gammaCorrect(texture2D(_MainTex, uv), _Gamma);
    color.a = (color.r + color.g + color.b) * 10.0;
    gl_FragColor = color;
  }
```
You can fiddle with that `10.0` value to adjust the sharpness of the black cutout.  Increase it to narrow the black threshold.

**Comment by Flameshot** [comment]
@rusmaxham  like this?

https://pastebin.com/9mr0mNhi

Also what material should I use?

**Comment by rusmaxham** [comment]
Excellent!  Happy to hear it is working for you now.
