### ISSUE TITLE
Single pass rendering does not work on Pixel phone

### ISSUE THREAD

**Issue by wangvnn** [googlevr/gvr-unity-sdk#811]
Single pass rendering is disabled on Pixel phone with Android Oreo 8

Found using:
 * Google VR SDK version: latest version, GVR Daydream renderer latest
 * Unity version: 2017.1.1f1
 * Phone manufacturer, model, and O/S version: Pixel 1, Android Oreo 8
 * Viewer manufacturer & model: Pixel 1

Steps to reproduce the issue:
 1. Turn on Single pass rendering
 2. Export the game to the phone
 3. Run the game and connect it to profiler in Unity (one frame debugger)
 4. Check that there are 2 sets of identical draw calls.
 If we do the same steps above and export the game to Pixel 2, it has only one set of draw calls.

Workarounds:
There is no workaround unless we downgrade the phone's OS to previous version of android (7.00)
But it is also very buggy to run it successfully.

Additional comments:
We would like to hear from GVR team to confirm if this is a problem.
And It would be nice to know if it will be fixed in near future.

Related info: https://forum.unity.com/threads/single-pass-rendering-on-daydream.499433/

**Comment by rusmaxham** [comment]
In that thread [this comment](https://forum.unity.com/threads/single-pass-rendering-on-daydream.499433/#post-3250692) says that single-pass rendering has been disabled on Pixel + Android 8.0.0, but should be enabled in Android 8.1.0.
