### ISSUE TITLE
view is stretched on Some cell phones

### ISSUE THREAD

**Issue by YoungBill** [googlevr/gvr-unity-sdk#815]
Some cell phones on the view showed abnormal, vr view is stretched, the view becomes very large, the fixation point has become very large. I use unity 5.6.0.f3, googlevr1.4
This one is normal：
![wechatimg419](https://user-images.githubusercontent.com/9884053/34212239-b547c8da-e5d6-11e7-8f07-57213db5f330.jpeg)
This one is not normal：
![wechatimg418](https://user-images.githubusercontent.com/9884053/34212300-d7facab2-e5d6-11e7-8876-9618adc64714.jpeg)

**Comment by YoungBill** [comment]
anyone can help me？

**Comment by fredsa** [comment]
Try resetting the viewer profile to the default "Cardboard" profile? It looks like your viewer profile is causing the issue here.

Please reopen if you still see this issue after updating to the latest Google VR SDK for Unity and after making sure the viewer profile is not the issue.
