### ISSUE TITLE
is there a way to change the VideoStereo TopBottom to LeftRight during the video is playing

### ISSUE THREAD

**Issue by KevinRocka** [googlevr/gvr-unity-sdk#817]
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: ___GoogleVRForUnity_1.110.0
 * Unity version: ___Unity 5.6.4f1

Hi , everyone ,is there a way to change the VideoStereo TopBottom to LeftRight during the video is playing.

**Comment by KevinRocka** [comment]
I just use the code below, it's not gonna work:
`Player.Screen.material.EnableKeyword(keyword:"LeftRight");`
`Player.ReInitializeVideo();`
 `Player.RestartVideo();`

**Comment by rusmaxham** [comment]
[This should do what you want](https://github.com/googlevr/media-app-template/blob/146a14046468f35b31d7fe6a7577b551e4a5b8a5/Assets/MediaAppTemplate/Scripts/MediaPlayer/BaseMediaPlayer.cs#L320).

**Comment by rusmaxham** [comment]
Please reopen and comment if you need any further assistance with this issue.
