### ISSUE TITLE
WARNING! Message telling me to install google vr services

### ISSUE THREAD

**Issue by devesh2605** [googlevr/gvr-unity-sdk#818]
I am building a video aggregation app and keep on getting warning to install Google VR services, this problem can be solved by installing the GVR services but this breaks the user experience, is there any api which I can call and suppress the warning message? It is mentioned in the recent release that the issue is fixed but it does not seem to be solved..

Found using:
 * Google VR SDK version: 1.110
 * Unity version: 5.6.4f
 * Phone manufacturer, model, and O/S version: Samsung, S6 Edge, Android 7.0
 * Viewer manufacturer & model: Samsung S6 Edge running on Android 7.0

Steps to reproduce the issue:
 1. Build the GVR demo scene.
 1. Click on Virtual Reality supported and choose cardboard.

Workarounds:

Install Google VR Services from play store and allow Google VR services.

Additional comments:
___

**Comment by nanweiqing** [comment]
have you resloved the problem ? i also have this problem ,it drives me crazy

**Comment by michael-jennings** [comment]
Make sure your AndroidManifest file ("Assets\Plugins\Android\AndroidManifest") has the correct settings from "Assets\GoogleVR\Plugins\AndroidManifest-Cardboard" and isn't configured for daydream or missing the cardboard settings.
@nanweiqing @devesh2605

**Comment by devesh2605** [comment]
This issue is resolved in the latest gvr skd update.
