### ISSUE TITLE
How to enable Head Tracking in non-VR mode?

### ISSUE THREAD

**Issue by jahKIper** [googlevr/gvr-unity-sdk#821]
Hello!
How can i enable Head Tracking in non-VR mode? Or enable gyro in non-VR mode?
In VR mode all works fine, but I don't understand, how do it works when VR mode is turned off.

Found using:
 * Google VR SDK version: 1.110
 * Unity version: 2017.3.0f2

**Comment by rusmaxham** [comment]
Sadly, there is no way to enable head tracking in non-VR mode without triggering VR transition screens, even though you're not using VR mode.  We're working on a solution to this issue.

**Comment by fredsa** [comment]
Please follow #829 and #703, which aim to document how to do this.
