### ISSUE TITLE
Need more documentation on multiplayer usage

### ISSUE THREAD

**Issue by fadookie** [googlevr/gvr-unity-sdk#823]
I am trying to set up a simple multiplayer scene using UNET (built-in multiplayer system.) This is proving difficult and I cannot find any documentation relating to the current (Daydream-capable) SDK. My initial results have the SDK code trampling over itself when more than one client is connected (latest client's camera takes over view for all clients, client's movement seems to mess with server camera, etc.) Could you please provide some documentation/examples of a multiplayer GVR setup? Thanks.

**Comment by fadookie** [comment]
For anyone else running into this issue I was just able to figure out one way to get this to work. I created a proxy player prefab that serves as the UNET player. When this player spawns, it locally instantiates another prefab containing the actual stereo camera and daydream controller. On update, I copy the daydream camera's transform to the proxy object, and use a NetworkTransform to relay the transform back to the host.

**Comment by fredsa** [comment]
@fadookie Glad you got it working.

In general, you should not move / update the camera transform. This includes not allowing multi-player networking to update the camera transform (or its ancestor transforms).
