### ISSUE TITLE
Failed "attempt to write a readonly database" Unity.2017.3 gvr.1.100

### ISSUE THREAD

**Issue by Frizau** [googlevr/gvr-unity-sdk#825]
<Brief summary of the issue you encountered>
Importing asset pack causes a failed notice (in title). Does this occur with anyone else? Anyone have a fix? I'm an online student so I'm not greatly experienced and only the internet to ask! Any advice would be amazing, thank you! 

Found using:
 * Google VR SDK version: 1.100
 * Unity version: 2017.3
 * Phone manufacturer, model, and O/S version: 6s
 * Viewer manufacturer & model: ___

Steps to reproduce the issue:
 1. ___
 1. ___

Workarounds:
___

Additional comments:
___

**Comment by Sanoend** [comment]
It happens in everyone. Mistakes of a couple hundred, the solutions are different. What are your mistakes now?

**Comment by Frizau** [comment]
@Sanoend, it appeared a had a "Plugins" folder already in my library. I deleted GoogleVR to import the later one and "Plugins" is now imported altogether with the newest SDK. I think the duplication caused some error. It's now importing fine. 

This could have been the problem, this might not have been the problem. I took the project apart and deleted a lot of outdated files and had to relink, recode and reimport files so it's very hard to tell still what was giving me the error but it's gone now. 

I am curious though, I keep reading that android development needs to be selected to instant preview.. I have an iPhone and a Mac..? I'm following GoogleVR's getting started program. I have a lot more questions but I'll share if I definitively get no answers!

**Comment by fredsa** [comment]
@Frizau Glad you got it working.

In general, updating plugins works best if you:
1. Make sure your project is in a good, working state
1. Backup your project
1. Close Unity (so that it does not lock any library files)
1. Delete the the old Plugins' files
1. Open Unity (ignore the compile errors due to missing files)
1. Import the new version of the plugin
1. Make any updates required due to API changes
