### ISSUE TITLE
Document how to recreate "Magic Window" (non-VR) camera tracking

### ISSUE THREAD

**Issue by fredsa** [googlevr/gvr-unity-sdk#829]
Need to document how to setup a (non-VR) "Magic Window" mode, such that the full screen monoscopic image on the device tracks the rotation of the device.

**Comment by fredsa** [comment]
Documentation of how to transition between VR (Daydream/Cardboard) and non-VR ("Magic Window") will be covered in #703.

**Comment by fredsa** [comment]
I've documented a basic script showing a working magic window which you can use to get started in your project: https://github.com/googlevr/gvr-unity-sdk/wiki/Magic-Window

**Comment by ersvltan** [comment]
It doesn't work. When I try to put it to MainCamera as script of GameObject, it says that I should fix compile  errors before attaching it to GameObject. So when I compile it through Visual Studio it says: 
"CS0229  C# Ambiguity between GyroController.CheckDrag() and GyroController.CheckDrag()" And so on. Also I noticed that you forgot one "}" at the end. Please help me to fix that error. Thank you!

**Comment by fredsa** [comment]
I added this missing `}`, but the script appears to compile just fine. Can you git it another try?

**Comment by fredsa** [comment]
Magic Window is now documented here:

https://developers.google.com/vr/develop/unity/guides/magic-window
