### ISSUE TITLE
Adding Cardboard in XR settings breaks working BLE scene

### ISSUE THREAD

**Issue by skywolf829** [googlevr/gvr-unity-sdk#831]
After adding GoogleVR SDK to a Unity project with functioning BLE capabilities, BLE no longer works.

Found using:
 * Google VR SDK version: v1.120.0
 * Unity version: 2017.2.0f1
 * Phone manufacturer, model, and O/S version: Google Pixel 2, 8.1.0
 * Viewer manufacturer & model: Google Cardboard
 * Arduino Uno
 * HM-10 BLE master-slave module
Steps to reproduce the issue:
 1. Create empty Unity project, add minimal code to incorporate BLE connectivity (using Asset store plugin Bluetooth LE for iOS, tvOS, and Android by Shatalmic Inc).
 2. Build to phone and run, verify that it connects to the HM-10 sensor on my Arduino Uno.
3. Uninstall app from phone.
4. Enable Virtual Reality support in Unity XR settings for Android.
5. Build to phone, verify it still works.
6. Uninstall app from phone.
7. Import GoogleVR SDK unitypackage. Add "Cardboard" to list of supported VR platforms in XR settings.
8. Build to phone, observe that BLE no longer connects.
9. Uninstall app from phone.
10. Add <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="false" /> to Android manifest. Build to phone, observe that BLE still no longer works, even with permission to location.

Additional comments:
I've been in contact with the creator of the plugin, and he doesn't quite know where to go either. I've checked permissions inside of settings on my phone and verified that the app does have access to BLE and to connect to BLE devices, as well as location and writing to internal storage.

**Comment by rusmaxham** [comment]
Sorry for the late reply, our platform engineers aren't aware of anything that would cause this.  A couple of things to try:
1. Build your app with and without Cardboard support (working and broken apks), use [apktool](https://ibotpeaches.github.io/Apktool/) to disassemble each of the apks and compare each's AndroidManifest.xml to see if something is being added/removed to cause this.
1. Try building for Cardboard and run on a non-Daydream ready device, like a Nexus 5 or 6, Samsung S6 and see if you're able to reproduce the issue.  If not (BTLE works great with and without Cardboard) then this could point to some poor interaction with the Daydream's usage of BTLE for the controller, even when in Cardboard mode.

**Comment by chaosemer** [comment]
Haven't heard back from you, so I'm assuming your issue is resolved.

**Comment by rusmaxham** [comment]
Could you try the workaround suggested in [this comment](https://github.com/googlevr/gvr-unity-sdk/issues/955#issuecomment-417419081)?
