### ISSUE TITLE
GvrControllerInput.Update() allocates 30 bytes on the heap every frame

### ISSUE THREAD

**Issue by Claytonious** [googlevr/gvr-unity-sdk#835]
GvrControllerInput.Update() allocates 30 bytes on the heap every frame of gameplay. This eventually leads to the GC needing to run. Generally speaking, nothing should allocate on the heap *every* frame of gameplay.

Found using:
Gvr sdk 1.120.0
Unity 2017.3.p2
Google Pixel XL

To repro:
Build any game that uses GvrController prefab with default arm model, etc., connect to Unity profiler, and observe heap allocations.

At first glance, it's not obvious what is allocating in here and I haven't been able to deep profile it yet to find out.

**Comment by ddrocco** [comment]
Thanks for your report; we'll take a look.

**Comment by ddrocco** [comment]
I've traced the allocation to the UnityEngine.XR.XRSettings.loadedDeviceName (UnityEngine.VR.VRSettings.loadedDeviceName pre-2017.2) method, which allocates the memory for a new string.  Unfortunately, I don't see a clean workaround from our end.  I've marked this as a Unity bug.

**Comment by rusmaxham** [comment]
We've partially fixed this in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).

**Comment by ddrocco** [comment]
This has been fixed in our upcoming GVR release.  The fix will be compatible with 2018.3 Unity and later (and will have no effect on earlier versions).

**Comment by Adam-VisualVocal** [comment]
Any chance you could push this fix into the Unity Long Term Support stream? Thanks.
https://unity3d.com/unity/qa/lts-releases

**Comment by rusmaxham** [comment]
This required an API change, and as such, is not likely to get a back port to 2017.4.

**Comment by rusmaxham** [comment]
Now released.
