### ISSUE TITLE
Daydream videos won't work due to seemingly buggy logic

### ISSUE THREAD

**Issue by ylluminarious** [googlevr/gvr-unity-sdk#839]
This issue is also described [here.](https://github.com/googlevr/gvr-unity-sdk/issues/830#issuecomment-359639589)

I cannot get video to work in Daydream, let alone in the editor. There are some other gaping anomalies in `GvrVideoPlayerTexture.cs ` which indicate some real problems.

The root of this problem seems to be that `GetRenderEventFunc` is *only* defined as:

```csharp
  private static IntPtr GetRenderEventFunc() {
    Debug.Log(NOT_IMPLEMENTED_MSG);
    return IntPtr.Zero;
  }
```

Although it seems that it is supposed to be defined differently based on the platform. Because otherwise it will ***always*** block `IssuePlayerEvent` which is called by `Init` which is used to play video:

```csharp
  private void IssuePlayerEvent(RenderCommand evt) {
    if (renderEventFunction == IntPtr.Zero) {
      /* it looks like GetRenderEventFunc is supposed to do something here
       * but it can only ever just log "Not implemented on this platform" */
      renderEventFunction = GetRenderEventFunc();
    }

    /* then it blocks the whole function here as it just logs and returns */
    if (renderEventFunction == IntPtr.Zero || evt == RenderCommand.None) {
      Debug.LogError("Attempt to IssuePlayerEvent before renderEventFunction ready.");
      return;
    }

    GL.IssuePluginEvent(renderEventFunction, videoPlayerEventBase + (int)evt);
  }
```

I am really not sure how exactly this is supposed to work. But this broken chain of logic alone seems to make video a no-go in Daydream. If I'm missing something, I would definitely appreciate some help here. This honestly seems like it's a bug.

Found using:
 * Google VR SDK version: `v1.110.0` and `v1.120.0`
 * Unity version: `2017.3.0f3`
 * Phone manufacturer, model, and O/S version: `ZTE`, `ZTE A2017U`, `Android 7.1.1`
 * Viewer manufacturer & model: `Google Daydream View`

Steps to reproduce the issue:
 1. Try using the VideoDemo Scene, as described [here](https://github.com/googlevr/gvr-unity-sdk/issues/830)

Workarounds:
None

Additional comments:
None

**Comment by rusmaxham** [comment]
The GvrVideoPlayerTexture doesn't work in Editor, only on device.  GetRenderEventFunc is additionally defined for Android devices as:
```C#
  [DllImport(dllName)]
  private static extern IntPtr GetRenderEventFunc();
```
This calls into the video plugin's native lib.  This shouldn't be blocking in either Editor or on device.  The native code simply returns a pointer and does nothing else that would block.

Can you send me your Unity project that reproduces your issue so I can see what other project settings you have configured?

**Comment by ylluminarious** [comment]
@rusmaxham Ok, I was not aware that `[DllImport(dllName)]` signifies calling into the native lib.

I will try to come up with a demo project and send it to you privately. What email address would you like me to send it to?

**Comment by ylluminarious** [comment]
@rusmaxham Friendly ping... did you see my last question there?

**Comment by ylluminarious** [comment]
Ok, so I managed to solve this issue in an email dialog with @rusmaxham. If you're seeing issues similar to mine, it probably boils down to a few things:

- You may be missing `libgvrvideo.so`. In order to get that library, import the [`GVRVideoPlayer.unitypackage` file.](https://i.stack.imgur.com/sS2Pd.png)
- You will probably still see errors saying things like "Video player not ready to Play!" or "illegal instruction" when you try to play videos in the Editor or with Instant Preview. That is just something you'll have to live with for now and it should ***not*** prevent your video from playing in Daydream itself. More explanation is [here.](https://stackoverflow.com/a/45019426/2636454)
- You may also need to adjust the `Stereo mode` in the `VideoStereo` component's settings in order to get the video to display properly. For example, for flat videos you may want to set `Stereo mode` to `None`.
- One more issue is that [Cardboard isn't supported](https://developers.google.com/vr/develop/unity/video-overview) by the video plugin currently. Hopefully @rusmaxham or others will fix this and make the video plugin work with Cardboard as well.
