### ISSUE TITLE
Request to expose HLS-playlist-text or parsed-info   via an api or callback

### ISSUE THREAD

**Issue by aasaanhai** [googlevr/gvr-unity-sdk#840]
As described in [https://developers.google.com/vr/develop/unity/video-overview](https://developers.google.com/vr/develop/unity/video-overview), I am using GvrVideoPlayerTexture and associated materials to render  HLS video. It works.

Now, In my use case, I intend to insert custom meta information in HLS master playlist.
Refering the  [working hls spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.4)

----------------------------------------------------------------------
 4.3.4.4.  EXT-X-SESSION-DATA

   The EXT-X-SESSION-DATA tag allows arbitrary session data to be
   carried in a Master Playlist.

   Its format is:

   EXT-X-SESSION-DATA: attribute-list

----------------------------------------------------------------------

Is there a way the relevant session data can be accessed in my Unity application, through a callback or any other suitable means.

Found using:
 * Google VR SDK version: v1.120.0
 * Unity version: 5.6
 * Phone manufacturer, model, and O/S version: Pixel
 * Viewer manufacturer & model: Pixel 

Additional comments:
___

**Comment by chaosemer** [comment]
This is unfortunately not supported by the library we use to decode the video. Sorry.
