### ISSUE TITLE
How to render mono 360 video. There is no VideoMonoInside material ! 

### ISSUE THREAD

**Issue by aasaanhai** [googlevr/gvr-unity-sdk#841]
Hi , Which material should be used to render mono 360 videos.
 VideoMono  ( for flat mono video ) , VideoStereo ( for flat stereo video ) and VideoStereoInside ( for stereo 360 video ) are provided.  The  "VideoMonoInside" material is not provided. 

**By comparing differences between VideoMono , VideoStereo and  VideoStereoInside, I was able to create VideoMonoInside, which worked for 360 mono videos.  But, It would be better if Google provides one themselves.** 

Google VR SDK version: v1.120.0
Unity version: 5.6
Phone manufacturer, model, and O/S version: Pixel
Viewer manufacturer & model: Pixel

 
Workarounds:
**By comparing differences between VideoMono , VideoStereo and  VideoStereoInside, I was able to create VideoMonoInside, which worked for 360 mono videos.  But, It would be better if Google provides one themselves.** 

Additional comments:
___

**Comment by Neogene** [comment]
I used Unity's VideoPlayer component on a sphere with flipped normals to get maximum compatibility to display 360 videos both on iOS and android.

**Comment by rusmaxham** [comment]
Closing this for now, since a viable workaround is easy to create.
