### ISSUE TITLE
GVR xcode build failure 

### ISSUE THREAD

**Issue by mladang** [googlevr/gvr-unity-sdk#842]
<GVR Unity VideoDemo scene fails to build in xcode>

Found using:
 * Google VR SDK version: 1.120.0
 * Unity version: 2017.3.0f3
 * Phone manufacturer, model, and O/S version: Apple, iPhone 7, iOS 11.2
 * Viewer manufacturer & model: n/a

Steps to reproduce the issue:
 1. Follow directions to set up GVR for Unity for iOS
 2. Build VideoDemo Scene, open in xcode using .xcworkspace
 3. Run--crashes with following error: Apple LLVM 9.0 Error - clang: error: invalid iOS deployment version '-miphoneos-version-min=11.2', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]

Workarounds:
n/a

Additional comments:
___

**Comment by xgraves** [comment]
Not sure if this helps, but I get this error when my deployment targets don't match in Xcode (project and pods).

**Comment by chaosemer** [comment]
iOS builds need to target 64bit.

This sounds like a general Unity issue and you should report it on their [forums](https://forum.unity.com/). I'm gonna close this because it is not GoogleVR specific.
