### ISSUE TITLE
Left eye "flickers" on Pixel 2 when using SPR from Unity 2017.3

### ISSUE THREAD

**Issue by Claytonious** [googlevr/gvr-unity-sdk#843]
Only on Pixel 2 devices, building with single pass rendering from Unity 2017.3p2 leads to frequent "flickering" in the left eye, where the position of the camera in the left eye offsets itself for one frame, then goes back to normal. This happens at a rate of anywhere from about once per second to once every few seconds. It's deeply disturbing for the user. Here is a video of the left eye "flickering" happening in the app (click to play):

[![Video of the flicker](https://img.youtube.com/vi/Zkt_ColYOAY/0.jpg)](https://youtu.be/Zkt_ColYOAY)

The bug manifests even during the static splash screen while the application is loading.

The bug does *not* manifest when running the exact same APK on a Google Pixel 1 XL, or any other device that I've tried so far.

Found using:
 * Google VR SDK version: 1.120.0
 * Unity version: 2017.3p2
 * Phone manufacturer, model, and O/S version: Google Pixel 2 XL
 * Viewer manufacturer & model: Google Daydream 1 headset but doesn't matter

Steps to reproduce the issue:
 1. Build with Unity 2017.3p2 or later with Single Pass Rendering enabled.
 2. Observe flickering in left eye on Pixel 2

Workarounds:
Use multipass rendering, which runs much slower, hurting the user experience.

Additional comments:
I've added even more detail about all of the workarounds I've already tried in vain to try to help live users who are impacted by this here: https://forum.unity.com/threads/left-eye-flicker-only-on-google-pixel-2.513251/.

**Comment by fredsa** [comment]
Support for single pass rendering is trsacked in #828 .
