### ISSUE TITLE
Videoplayer dont play AC3 codec

### ISSUE THREAD

**Issue by HennessyTennessy** [googlevr/gvr-unity-sdk#844]
Found using:
 * Google VR SDK version: v1.120.0
 * Unity version: 2017.3.0f3
 * Phone manufacturer, model, and O/S version: Android/Xiaomi Redmi Note 3 SE 
 * Viewer manufacturer & model: n/a

Steps to reproduce the issue:
 1. Open VideoDemo.scene
 2. Insert path of file on device in Video URL label (for example "file:///storage/Films/LordOfTheRings.mkv")
 3. Build and run on device.

When I start it - I have Video without Audio. I have no problems with .mp4 and .mkv formats with AAC audio codec, but how can I turn on AC3 codec supporting?
P.S. as i know, ExoPlayer support AC3 decoding! Thank you for any info.

**Comment by rusmaxham** [comment]
Yes, unfortunately, Android doesn't support AC3 decode.  The easiest thing to do is to [convert your video file's audio track to AAC](https://trac.ffmpeg.org/wiki/Encode/AAC) before loading it on your device.  If you'd like your app to do the conversion, that will be a much more involved engineering task to embed ffmpeg into your app.  Unfortunately, we are unable to assist with that endeavor.
