### ISSUE TITLE
Freeze when my menu appears

### ISSUE THREAD

**Issue by Paullux** [googlevr/gvr-unity-sdk#847]
Summary:

When i press the button to appears my menu, the vu freeze until i deseapers the menu.

I have a canvas with 4 Images,

Under an Images i have a text and 16 button.

On a button, i have four sprite and a text with a script.
Under the script, i have a scrollbar.

For three first menu i haven't any problem.

For the for menu i have a problem the game freeze. 

I try to remove the texts with the scripts for the 16 button in the 4rd menu, the game don't freeze.

I have only a script on the text of one button for the 4rd menu, the game don't freeze.

Found using:
 * Google VR SDK version: latest
 * Unity version: latest
 * Phone manufacturer, model, and O/S version: OnePlus 3T (the last system)
 * Viewer manufacturer & model: Eligiant the headphone.

Found the prefab of my menu : https://drive.google.com/file/d/1fuwEYm2grbrktg2KPybIVZ1QDMF2szWb/view?usp=sharing

**Comment by Paullux** [comment]
The game is running, but the camera freezed.

**Comment by chaosemer** [comment]
Could you please share the results of an `adb logcat -s Unity`? This sounds like an exception is being thrown.

Thanks.

**Comment by Paullux** [comment]
The problem was i used too many scrollbar in my menu.
When i remove it and recreate my menu without scrollbar, all work correctly.
