### ISSUE TITLE
[Bug] GvrReticlePointer dont work on 

### ISSUE THREAD

**Issue by jxnass** [googlevr/gvr-unity-sdk#848]
Summary:
The reticlepointer events (onpointerenter/exit) does not work with multiple clients, the events will only trigger on the host. 

Found using:
 * Google VR SDK version: v1.110.0
 * Unity version: 2017.2.0f3 
 * Phone manufacturer, model, and O/S version: Galaxy S8 SM-G950F (Android 8.0)
 * Viewer manufacturer & model: Thinkpad T460 (Windows 10 Pro)

Steps to reproduce the issue:
 1. create an simple unity network project 
   a. simple player prefab with network transform & identity
   b. make the Reticlepointer prefab as child of the player prefab
   c. add basic movement to the player
   d. create EventSystem
   e. create cube with gvrpointerphysics raycaster and eventTrigger
   f. start host, host will trigger eventTrigger
   g. start client, connect to host and the cube wont trigger.

Workarounds:
-

Additional comments:
-

**Comment by chaosemer** [comment]
Could you please provide a sample project for reproducing this?

**Comment by rusmaxham** [comment]
Please reopen if you can provide a sample project to reproduce the issue.
