### ISSUE TITLE
Demos VideoDemo scene does not work in Unity Editor preview

### ISSUE THREAD

**Issue by AlexChesser** [googlevr/gvr-unity-sdk#849]
Summary:

Using a default setup of Unity and a fresh install of the GoogleVR release, the VideoDemo scene does not play videos.

Found using:
 * Google VR SDK version: GVR SDK for Unity v1.120.0
 * Unity version: 2017.3.0f3
 * Phone manufacturer, model, and O/S version:  N/A
 * Viewer manufacturer & model: Unity player

Steps to reproduce the issue:
 1. open unity new project
 2. download v1.120.0 (latest release) 
 3. import base unitypackage
 4. open file location assets/googlevr and import GVRVideoPlayer.unitypackage
 5. open `file` > `build settings` select android player and switch platform
 6. open `Assets` > `GoogleVR` > `Demos` > `Scenes` > `VideoDemo`
 7. PLAY video in Unity 
 8. Use GAZE controls (hold alt and move mouse) in `GAME` window to point at one of the menu buttons (eg: 360 video) & click mouse button
 9. Observe screen turns BLUE - video does not play

Workarounds:

None.

Additional comments:

Note that the message

     string NATIVE_LIBS_MISSING_MESSAGE = "Video Support libraries not found or could not be loaded!\n" +
            "Please add the <b>GVRVideoPlayer.unitypackage</b>\n to this project";

is incorrectly assuming the libraries are not installed

          IntPtr ptr = GvrVideoPlayerTexture.CreateVideoPlayer();
          if (ptr != IntPtr.Zero) {

Also under the WARNINGS view there is a statement that `No GvrEditorEmulator instance was found in your scene` however it is clearly present in the default videodemo hierarchy 
```
No GvrEditorEmulator instance was found in your scene. Please ensure thatGvrEditorEmulator exists in your scene.
UnityEngine.Debug:LogWarning(Object)
GvrVRHelpers:GetHeadRotation() (at Assets/GoogleVR/Scripts/Utilities/GvrVRHelpers.cs:47)
GvrVRHelpers:GetHeadForward() (at Assets/GoogleVR/Scripts/Utilities/GvrVRHelpers.cs:41)
GvrArmModel:UpdateTorsoDirection(Boolean) (at Assets/GoogleVR/Scripts/Controller/ArmModel/GvrArmModel.cs:235)
GvrArmModel:OnEnable() (at Assets/GoogleVR/Scripts/Controller/ArmModel/GvrArmModel.cs:202)
```

edit:  note that the expected behavior is that a view PLAYS while in preview mode

**Comment by rusmaxham** [comment]
`GvrVideoPlayerTexture` is only supported on Android devices.
