### ISSUE TITLE
FOV on IPhone X incorrect when using Cardboard

### ISSUE THREAD

**Issue by Moncader** [googlevr/gvr-unity-sdk#850]
On iPhone X, the FOV (?) seems to be incorrect when using the Unity SDK.
You need to make your eyes slightly cross-eyed to focus, and even then there is a lot of visible warping (fish eye) around the edges of your vision.
The problem does not happen on any other iPhone devices.

The problem also happens on Google's official Cardboard app and sample applications (except for street view).

We have tried on multiple iPhone X's with multiple viewers and have had the same issue across the board.

Found using:
 * Google VR SDK version: v1.120.0
 * Unity version: 2017.3.1
 * Phone manufacturer, model, and O/S version: iPhone X, iOS 11.2
 * Viewer manufacturer & model: Multiple

**Comment by fredsa** [comment]
What's the make/brand of the Cardboard viewer you are using? Have you tapped the gear icon to scan the right QR code for your viewer?

**Comment by Moncader** [comment]
I've used the gear icon and used the menu from the cardboard app to set the correct profile.
I've also done this on multiple iPhone's and only iPhone X has the problem.

The viewers we have tried are
* milbox2
* Cardboard VR from IHUAQI Technology Ltd.

**Comment by fredsa** [comment]
Can you try a certified _Works with Google Cardboard_ [viewer](https://vr.google.com/cardboard/get-cardboard/)?

I tested a sample app built with Unity 2017.3.1p1, running on iPhone X and I'm able to converge left and right images correctly using the default configuration and a Google Cardboard viewer.

**Comment by Moncader** [comment]
@fredsa 
The milbox 2 cardboard posted above _is_ a certified viewer.
http://milbox.tokyo/milbox2/

Here in my company some people are saying they have no problem focusing while others (like myself) can't focus unless I go full cross-eyed.
However even the people that say they can focus all say it looks better on a non iPhone X device.

Also, just simply loading up the default cardboard app on iPhone X and doing the same at the same time with an iPhone 8 and comparing physical locations of certain objects in the 3D scene shows that even though the screen viewing area is exactly the same measured size, the location of objects and FOV inside each lens is different on each phone, which can't be correct.

**Comment by Moncader** [comment]
@fredsa 
Is there any update on this?

**Comment by fredsa** [comment]
Another developer reported that updating to the latest SDK fixed this issue.

Feel free to reopen if this is still a problem with the latest SDK.
