### ISSUE TITLE
Audio works in editor but not in the build on iOS.

### ISSUE THREAD

**Issue by slowizzm** [googlevr/gvr-unity-sdk#852]
***Update - I just built a blank proj, no assets imported ... ui button to trigger audio, not working on iOS build, I am going to say this issues is not related to GVR. 

I have been working on a project and have had issues getting the audio to work on ios, so to trouble shoot, I created a new project and imported [GoogleVRForUnity_1.120.0.unitypackage](https://github.com/googlevr/gvr-unity-sdk/releases/download/v1.120.0/GoogleVRForUnity_1.120.0.unitypackage) with no other libraries/assets and I got the same result, audio works in the editor, but fails to work in the build.

Found using:
 * GVR SDK for Unity v1.120.0
 * Unity 2017.3.0f3
 * iPhone 7 iOS 11.3
 * Owl Cardboard VR

Steps to reproduce the issue:
 1. Create project in Unity 2017.3.0f3 and import GoogleVRForUnity_1.120.0.unitypackage.
 2. Build for iOS.
 3. Launch .xcworkspace in xcode 9.2 Beta 2.
 4. Run app on iPhone 7.

Forums say this issue was resolved in GVR 1.70 ... but unfortunately I am having this issue with GVR 1.120. I have not tested any previous versions, but will do so shortly.

**Comment by slowizzm** [comment]
Fixed this ... my Mute switch was on, lol. I never would have thought this would mute my audio from my build, mainly because I always have my mute switch on, bc I thought it was only for the ringer, and often play music, videos, and games, where I never have an issue with audio not playing.

Feel free to close this issue, but if anyone has any knowledge as to how to overcome audio not playing in my app for those of us who leave the must switch on, that would be awesome, until then I will research this as well. Thanks.

**Comment by KarimIbrahim** [comment]
Had same issue, been looking online or a week. Thanks for sharing the solution.
