### ISSUE TITLE
World is upside-down on landscape right on iOS

### ISSUE THREAD

**Issue by rutkoski** [googlevr/gvr-unity-sdk#853]
Summary:

Found using:
 * Google VR SDK version: 1.120.0
 * Unity version: from 2017.2.0p1 to 2017.3.1p1
 * Phone manufacturer, model, and O/S version: iPhone 6, iOS 11
 * Viewer manufacturer & model:

Steps to reproduce the issue:
I activate auto rotation and allow rotation to all orientations.
On orientation change I check if it is portrait, disable VR and show a menu for switching between magic window and VR. When orientation is landscape (left or right) I go back to magic window or VR (according to user choice on menu).

Everything works fine on Android, but on iOS, when user goes to landscape right, the cardboard buttons are oriented correctly, but the world in Unity is upside-down.

**Comment by rusmaxham** [comment]
GVR is designed to be launched in landscape left orientation only. Landscape right is not a supported configuration.

**Comment by dustinkerstein** [comment]
I understand that VR + orientation handling doesn't make much sense, but what about folks using "magic window" mode? In that case, various orientations might be unavoidable. I'm now running into this issue on iOS (GVR 170) and only 1 orientation (landscape right) works correctly - all others are flipped. Android doesn't seem to exhibit this behavior. Can you think of any potential workarounds?
