### ISSUE TITLE
GVR/Unity build fail for iOS (linker command failed with exit code 1)

### ISSUE THREAD

**Issue by mlovelessBaylor** [googlevr/gvr-unity-sdk#854]
Summary:

We built a VR (using GVR components) app in Unity (2017.1.0f3) and are now trying to build it in Xcode (9.2). We have followed all the “methods” from this github article– opened the workspace instead of the project, updated the pods in the project directory, and deleted bogus library paths. We have even tried the bypass option in Method 3, but nothing seems to work.  We were able to successfully build this same app using Unity 5.4.2 and publish (to TestFlight) with no problem in December 2017. Now that we rebuilt the app using this later version of Unity, we can’t seem to be past the “linker command failed with exit code 1” error. Anything else we are missing? Many thanks!
M

Found using:
 * Google VR SDK version:
 * Unity version:
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by whizzkid** [comment]
Same problem here. 
Any progress on this issue?

**Comment by whizzkid** [comment]
update: I successfully made a build by removing ALL plugins and libraries and re-added all neccesary plugins/assets i needed.  And I had to remove some kind of gvrAudio thing which caused unity on mac to not compile. (can't remember which one, because I removed it :P )

**Comment by mlovelessBaylor** [comment]
@whizzkid - glad you got it working. I'll give that a try. Thanks.
