### ISSUE TITLE
Instant Preview on phone have no controls

### ISSUE THREAD

**Issue by linglonglinglong** [googlevr/gvr-unity-sdk#856]
Summary:
I run the Demo scene on Galaxy Note 8. It only shows the scene in starting position, no matter how I rotate my head! Tapping on the screen also doesn't work! Why?

Found using:
 * Google VR SDK version: 1.120.0
 * Unity version: 2017.3.1f1
 * Phone manufacturer, model, and O/S version: Samsung Galaxy Note 8, Android 7.1.1
 * Viewer manufacturer & model: Google Cardboard

**Comment by ddrocco** [comment]
Thanks for your report; we'll take a look!

**Comment by ddrocco** [comment]
Hi, I've tried to reproduce your issue with a new Galaxy Note 8 and a fresh download of GVR SDK 1.120.0 and everything worked for me.

Is your phone loading anything, or is the static starting position scene in the Unity editor?  What do you expect when you tap the screen?

Useful things to verify:
-Unity is set to the Android platform in File > Build Settings.
-The Galaxy Note 8 has USB Debugging set to True.
-You have made no modifications to the code in GVR SDK 1.120.0.

**Comment by ddrocco** [comment]
Hi, I'm going to close this issue; if you're still having this problem, please let us know and reopen it!
