### ISSUE TITLE
IOS google cardboard / gvr screen size cut in half

### ISSUE THREAD

**Issue by Bentoon** [googlevr/gvr-unity-sdk#857]
Summary:
hello I have had his problem in a few different iOs Build recently. 
They build to phone but only **the bottom half of screen** . I can find nothing on line ...
Please help 
Thanks !
![img_2680](https://user-images.githubusercontent.com/1715401/36884195-442eecb4-1dad-11e8-88e8-16f30bf4136c.PNG)

Found using:
 * Google VR SDK version: 1.120.0
 * Unity version: 2017.3.0f3
 * Phone manufacturer, model, and O/S version: Apple / iPhone 6+
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by dmonego** [comment]
I can report similar issues on 2017.3.1f1, using 1.120.0 to build for an iPhone SE.

I'm able to reproduce by going through the quickstart steps for iOS using the HelloVR default scene.

**Comment by tedtheodore** [comment]
I also encountered this bug when using GoogleVR. Enabling VR disables your ability to edit the "Default Orientation" field in the "Settings for iOS" under "Player Settings". The way I solved this was to disable VR, set the Default Orientation to "Landscape Left" and then reenable VR.

**Comment by ghettokon** [comment]
This workaround works for me too. New York thanks you!

**Comment by tedtheodore** [comment]
A lot of trial and error!

**Comment by fredsa** [comment]
If you need portrait orientation in 2D but landscape for VR mode, see the C# workaround in issue 838:
https://github.com/googlevr/gvr-unity-sdk/issues/838#issuecomment-358404072

**Comment by MrKBooi** [comment]
savedmmmylife, thank you
