### ISSUE TITLE
No AA on iOS Cardboard

### ISSUE THREAD

**Issue by reddo123** [googlevr/gvr-unity-sdk#858]
Summary: No anti-aliasing setting seems to take effect on Cardboard build for iOS. Have tried 2x, 4x 8x and disabled settings with no change aliasing.

Found using:
 * Google VR SDK version: 1.120.0
 * Unity version: 2017.3.1p1
 * Phone manufacturer, model, and O/S version: Apple, iPhone6, iOS 11.2.1
 * Viewer manufacturer & model: 

Steps to reproduce the issue:
1. Use HelloVR scene for GVR SDK
2. Set AA to 4x or 8x in Project Settings>Quality
3. Build and Run to IOS device in X-Code

Workarounds:

Additional comments:

**Comment by rusmaxham** [comment]
Did you set the AA setting on the correct Quality Level for iOS?  At the top of the QualitySettings inspector are several Levels.  Make sure the Level with the green checkbox below the iOS icon is selected before setting the AA level.

![screen shot 2018-05-11 at 9 54 56 am](https://user-images.githubusercontent.com/13911074/39936460-6ab148e2-5501-11e8-939d-ce020d8ef580.png)

**Comment by rusmaxham** [comment]
If this is still an issue, please comment.
