### ISSUE TITLE
How to update GvrViewer.Instance.Triggered

### ISSUE THREAD

**Issue by CamiloB** [googlevr/gvr-unity-sdk#859]
Summary:
Hello  i updated the google vr for unity  from 1.110 to 1.120 and i have an issue, i had a trigger instance to jump on my game and now its does not work, the error is on this line part of the code 

GvrViewer.Instance.Triggered 

its says that "The name 'GvrViewer' does not exist in the current context 

`
//Make player jump

		jumpingTimer -= Time.deltaTime;
		if(GvrViewer.Instance.Triggered || Input.GetKeyDown("space")){
			if (jumpingTimer <= 0f) {
				jumpingTimer = jumpingCooldown;
				GetComponent<Rigidbody> ().AddForce (Vector3.up * jumpingForce);
			}
		}
`

Found using:
 * Google VR SDK version: 1.120
 * Unity version: 5.6.0f3
 * Phone manufacturer, model, and O/S version: Android Moto G 4 Plus
 * Viewer manufacturer & model:

**Comment by rusmaxham** [comment]
If you have a GvrReticlePointer in your scene, you can get the trigger down from this property:

```C#
   GvrPointerInputModule.Pointer.TriggerDown
```
