### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by JuanBMMontesinos** [googlevr/gvr-unity-sdk#860]
I created a new Unity project.
I followed those instructions from this tutorial: https://www.youtube.com/watch?v=jqr0jaPKpmA
But when I compile the Android version in my Asus Zenphone 2, the VR effect is not working.

Why?

**Comment by rusmaxham** [comment]
Unfortunately, the Zenphone 2 is an x86 based phone, and GoogleVR is not supported on x86 devices.

**Comment by rusmaxham** [comment]
There is experimental support for x86 devices in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
