### ISSUE TITLE
recticle details

### ISSUE THREAD

**Issue by kbza1work** [googlevr/gvr-unity-sdk#862]
Are the GVRRECTICLEPOINTER details available for other scripts to access / use? 
I am looking for these:
.1 ... the ray cast hit information (3d hit position, hit object)
.2 ... the screen position of the expanded (fully grown) circular recticle
If they are available - please provide details .. thank you

Found using:
 * Google VR SDK version: 1.120.0
 * Unity version: 2017.3.0f3

**Comment by dsternfeld7** [comment]
1. You can use the property GvrReticlePointer. CurrentRaycastResult to get the latest hit information from the reticle. You can also subscribe to events using Unity's pointer handlers. 
2. The screen position of the reticle is always the center of the screen, and you can use GvrReticlePointer.ReticleOuterDiameter to determine the diameter of the reticle when it is expanded. the ReticleOuterDiameter will change to match the current diameter of the reticle.
