### ISSUE TITLE
Daydream keyboard should support Physical keyboards

### ISSUE THREAD

**Issue by RangerMauve** [googlevr/gvr-unity-sdk#866]
Summary:
It would be nice if the GvrKeyboard could act like a standard way of doing any keyboard input including Bluetooth keyboards.

Steps to reproduce the issue:
 1. Connect a bluetooth keyboard
 1. Open a VR app like Chrome
 1. Use either on-screen keyboard or physical keyboard to type

Workarounds:
Apps can manually add listeners for the keyboard APIs, but this would be duplicated effort and a lot of apps probably wouldn't even think to do it.

**Comment by chaosemer** [comment]
Honestly, this is really low priority for us. I don't think we'll get to it any time soon. Closing this.

**Comment by RangerMauve** [comment]
Would a PR be welcome for it?

**Comment by chaosemer** [comment]
Happy to take PRs! Please make sure it can be done in such a way that there's only one GvrKeyboard API to Unity apps that works in both cases.

**Comment by RangerMauve** [comment]
I was thinking the most basic thing that could be done would be to listen on the existing Keyboard APIs that Unity provides in order to add to the input buffer.

**Comment by chaosemer** [comment]
I'd have to see the PR to judge if it looks reasonable or not. The core idea certainly seems reasonable.

This is certainly doable as sample code, but I agree with you that avoiding the duplicate effort seems vauable.
