### ISSUE TITLE
No stereoscopic view on ASUS Zenfone 2 with Android 6.0

### ISSUE THREAD

**Issue by T-0pel** [googlevr/gvr-unity-sdk#867]
Summary:
When I install the apk with the HelloVR scene file on my ASUS Zenfone 2 the app is rendered in monoscopic view, even though the phone supports Google Cardboard, has Android 6.0, and it has a gyroscope. I have tested apps in the official Google Cardboard app and they are working correctly on the phone. All settings in Unity are set correctly, I have tested the exact same apk on Samsung S6 Edge with Android 7, on LG GPad with Android 4.4 and on HTC One. It works as expected on all of them. Unfortunately I do not have another device with Android 6.0.

Found using:
 * Google VR SDK version: v1.120.0
 * Unity version: 2017.3.1f1 
 * Phone manufacturer, model, and O/S version: Asus Zenfone 2 ZE551ML Android 6.0.1
 * Viewer manufacturer & model: issue is not specific to the viewer

Steps to reproduce the issue:
 1. Create apk file based on the Google VR quickstart for Unity
 2. Install app on Asus Zenfone 2

Workarounds:
Use a different device.

**Comment by rusmaxham** [comment]
Unfortunately, the ASUS Zenfone 2 is an x86 based device and the GVR SDK for Unity doesn't support x86 based devices.  The Cardboard app is based on an older version of GoogleVR that did support x86 devices.  You might still be able to build a Unity Cardboard app with SDK version [1.40](https://github.com/googlevr/gvr-unity-sdk/releases/tag/v1.40.0).

**Comment by rusmaxham** [comment]
There is experimental support for x86 devices in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
