### ISSUE TITLE
Scene not levelled/tilted in VR mode

### ISSUE THREAD

**Issue by olibd** [googlevr/gvr-unity-sdk#871]
Summary:
When in VR mode (split screen), the SDK will slowly tilt the "scene to the right" even when the phone is is not tilted, as can be scene in the pictures. The purple info box seen here should be levelled but it's not.

Screenshots:
![screenshot_20180213-160646](https://user-images.githubusercontent.com/6964009/37376980-8ec7a316-26fd-11e8-9680-8af51f3279d8.jpg)

Found using:
 * Google VR SDK version: 1.110.0
 * Unity version: 2017.3.0f3
 * Phone manufacturer, model, and O/S version: OnePlus 3, Android 8.0.0
 * Viewer manufacturer & model: Google Cardboard

Steps to reproduce the issue:
 1. Enter the app in vr mode
 2. As GoogleVR auto adjusts to the orientation of the phone, it will slowly tilt the "scene" to the right

Workarounds:
N/A

Additional comments:
We tried to reproduce the issue on a Samsung galaxy s8 but where seemingly unable to do so. So it may be device related. Please let me know if you have any idea of the cause or if you are able to reproduce the issue

**Comment by tedtheodore** [comment]
If you can't reproduce it, as you say it might be a device thing, but past this it might be worth ensuring all the z rotations of your camera parents in scene are zeroed out

**Comment by rusmaxham** [comment]
This sounds like a device specific issue, likely poorly calibrated motion sensors.  Sadly, there isn't anything we can do about it at the GVR or SDK level.

**Comment by Neogene** [comment]
Have a same problem with Nokia ta-1032
