### ISSUE TITLE
Changing Player's direction with GVR Headset orientation

### ISSUE THREAD

**Issue by spaul13** [googlevr/gvr-unity-sdk#874]
can anyone please tell me how to change the player's orientation along with the Headset orientation change? Right now, although I look into a different direction, I am following the previous path while moving (going forward or backward). Can anyone please tell me how to change player's direction with the headset orientation?

Found using:
 * Google VR SDK version: 1.40 (old version)
 * Unity version: 5.6.4P4
 * Phone manufacturer, model, and O/S version: Google Pixel 2
 * Viewer manufacturer & model:

**Comment by rusmaxham** [comment]
You can enable head tracking on a camera by settings its `Target Eye` setting to `Both`.

![screen shot 2018-03-26 at 7 15 57 pm](https://user-images.githubusercontent.com/13911074/37942900-323cbc62-312a-11e8-942c-352ef0a7193f.png)

**Comment by spaul13** [comment]
@rusmaxham, thanks for your reply. But I have already made the target eye settings to **Both** but it's still not working. (Means the player is not rotating as I rotate the Headset).

Can you please tell me why this is happening, where I have to change or did wrong?

**Comment by rusmaxham** [comment]
Oh, the player game object will not rotate with the camera.  Your game will have to use the rotation from the main camera in your game's player movement logic:  `Camera.main.transform.rotation`  This does not come for free.  You do not want to apply this rotation to the player game object, otherwise it will apply the head rotation twice.  You only want to use this rotation in your movement logic.

**Comment by TonGarcia** [comment]
@rusmaxham do you have any example? Because I'm using a joystick, while moving axis it move the player, but it is not following the camera. I'm editing the FirstPersonController.cs but it still not working to move based on camera direction.

**Comment by TonGarcia** [comment]
I found a way, add it to the FirstPersonController.cs:

```csharp
        private void FixedUpdate()
        {
            float speed;
            GetInput(out speed);
			// always move along the camera forward as it is the direction that it being aimed at
			Vector3 camForward = Camera.main.transform.forward;
			Vector3 camRight = Camera.main.transform.right;

            //Vector3 desiredMove = transform.forward*m_Input.y + transform.right*m_Input.x;
			Vector3 desiredMove = camForward*m_Input.y + camRight*m_Input.x;
```

**Comment by vinhui** [comment]
Also, be sure to cache the `Camera.main` because every time you call it the code behind the property does a `GameObject.FindWithTag("Main Camera");` which isn't cheap.
