### ISSUE TITLE
Degradation of textures.

### ISSUE THREAD

**Issue by kamanii24** [googlevr/gvr-unity-sdk#875]
Non VR<br>
![Imgur](https://i.imgur.com/f5x8hvW.png)
<br><br>
Cardboard<br>
![Imgur](https://i.imgur.com/cf1cDUd.png)
<br><br>
 * Unity version:Unity2017.3.1f1

**Comment by rusmaxham** [comment]
What device does this occur on?  Can you post a repro project?  Looks like a project or texture setting isn't right.

**Comment by Adam-VisualVocal** [comment]
I'm pretty sure I debugged this once and the cause seemed to be GVR using a 565 texture for lens distortion. Those bands look very much like what you get with color gradients on 565 frame buffers.

**Comment by kamanii24** [comment]
iPhone7 iOS11.2.6

I think that it is a phenomenon occurring in the 16-bit frame buffer, so I think that it is necessary to be able to change that setting.

![Imgur](https://i.imgur.com/du7ZRKY.png)

**Comment by rusmaxham** [comment]
Did this solve your issue?

**Comment by kamanii24** [comment]
No, I continue to have this problem.

**Comment by rusmaxham** [comment]
Can you send me a sample project to debug?

**Comment by kamanii24** [comment]
Ok, wait a moment.

**Comment by vinhui** [comment]
We seem to have this issue when were trying to apply post processing effects

**Comment by kamanii24** [comment]
I'm using Post Processing Stack, but Mach bands are never show after.
