### ISSUE TITLE
How to close the app and go back to the Daydream Home ?

### ISSUE THREAD

**Issue by silviocarrera** [googlevr/gvr-unity-sdk#876]
Is there any way to simulate the Home Button behaviour? I want my App Button to go back to the Daydream Home like the Home Button does it. 

If I use Application.Quit() on Unity it closes the App, shows the Daydream Home for a few seconds then it closes it as well.

I realize many Apps just ignore the App Button when on their Home Screen. 

Any help?

**Comment by rusmaxham** [comment]
```C#
  GvrDaydreamApi.LaunchVrHomeAsync(Action<bool> callback);
```
