### ISSUE TITLE
v1.130.0 error CS0234: The type or namespace name iOS' does not exist in the namespaceUnityEditor'. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by rehahoshanli** [googlevr/gvr-unity-sdk#877]
Summary: Installed the latest versions of Unity, Daydream SDKs and followed the steps here: https://developers.google.com/vr/develop/unity/get-started#configure_build_settings_and_player_settings

When Play is pressed I get the following error: 
Assets/GoogleVR/Editor/GvrBuildProcessor.cs(20,19): error CS0234: The type or namespace name iOS' does not exist in the namespaceUnityEditor'. Are you missing an assembly reference?

Found using:
 * Google VR SDK version: v1.130.0
 * Unity version: 2017.3.1
 * Phone manufacturer, model, and O/S version: N/A Mac High Sierra, have not connected Pixel 2
 * Viewer manufacturer & model: N/A

Steps to reproduce the issue:
 1. https://developers.google.com/vr/develop/unity/get-started#configure_build_settings_and_player_settings
 1.
 1.

Workarounds: Issue fixed when I imported v1.120.0 instead

Additional comments:

**Comment by rusmaxham** [comment]
A fix is on the way.

**Comment by rusmaxham** [comment]
Fixed in [v1.130.1](https://github.com/googlevr/gvr-unity-sdk/releases).
