### ISSUE TITLE
Google VR sample pano not playing in Mediatek Processor based phones

### ISSUE THREAD

**Issue by devesh2605** [googlevr/gvr-unity-sdk#879]
Hi, 

I am trying to test my app on the mediatek devices and the sample pano video player is not playing in the phones below:

1. Mediatek Mt6795 
2. Mediatek Mt6735 

Instead of showing the video it shows screen in pink colour, it has anything to do with Texture compression?, I tried changing the textures compression and still does not work. I would appreciate an early response.

Thanks,
Devesh V

**Comment by rusmaxham** [comment]
The GvrVideoPlayerTexture component is not officially supported for Cardboard, only Daydream-ready devices.  It may work on some Android Cardboard devices, but it is known to not work on some.  I don't have any Mediatek devices on hand to test with.  If you could post a logcat from your running app, I could try to debug the issue for you.

**Comment by rusmaxham** [comment]
Please reopen this issue if you'd like further help.
