### ISSUE TITLE
gvrmain

### ISSUE THREAD

**Issue by aserdah** [googlevr/gvr-unity-sdk#882]
Summary:
how we can used gvrmain in the new   Google VR SDK version

Found using:
 * Google VR SDK version:
 * Unity version:
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by rusmaxham** [comment]
GvrMain has been deprecated and removed since the native integration of GVR into Unity.  What functionality did you need from it?

**Comment by rusmaxham** [comment]
Please reopen if you still need help with this issue.
