### ISSUE TITLE
Keep original camera orientation at start

### ISSUE THREAD

**Issue by Neogene** [googlevr/gvr-unity-sdk#885]
When starting a scene camera take an horizontal orientation which is different from the start rotation set inside the editor, there is a way to keep it the same?

The desired behavior is when the user starts the experience to watch toward the direction we set in the scene and not forcing him/her to find the area looking around.

**Comment by rusmaxham** [comment]
Create a Player game object with the desired start position and place the Main camera as a child of this Player object.
