### ISSUE TITLE
Using Daydream Emulator in Unity with one phone only

### ISSUE THREAD

**Issue by rehahoshanli** [googlevr/gvr-unity-sdk#886]
Summary: The Daydream guide requires having 2 Android phones (headset phone, emulator phone) to be able to use a phone emulator. Considering Unity' Game View functionality provides the functionality of the headset phone (the instant preview has a Controller only mode supporting this) simply one Android phone should suffice to be used as the emulator.

This would simplify things, would be useful for developers without a spare device and controller. 

Found using:
 * Google VR SDK version: v1.130.1
 * Unity version: 2017.3.1f1
 * Phone manufacturer, model, and O/S version: Pixel 2
 * Viewer manufacturer & model: Daydream

Steps to reproduce the issue:
 1. Connect an android phone via USB
 2. Press Play in Unity
 3. Keep Instant Preview option as Controller Only 
 4. Open Controller Emulator from the same phone
 

Workarounds:

Additional comments:

**Comment by rusmaxham** [comment]
Is this just a documentation issue, or is there some additional functionality you're requesting?

**Comment by rehahoshanli** [comment]
Documentation states that there is a need for 2 phones (1 headset, 1 spare) and as stated I was not able to make it work without a spare phone. Request here is allowing the use of the emulator with one phone and not requiring a headset phone whilst developing on Unity.

**Comment by vinhui** [comment]
You can use the controller emulator app for that.
https://developers.google.com/vr/daydream/controller-emulator

**Comment by rehahoshanli** [comment]
The document you referred states a spare phone is needed as I mentioned.
Are you saying that is not needed & how?

**Comment by ddrocco** [comment]
Hi, the primary use case of the Controller Emulator is for pairing with an actual Daydream headset.  The controller-only mode of InstantPreview is for working with a Bluetooth-paired device, be it a Controller or Phone emulating a controller.

At the bottom of the Controller Emulator developer page (https://developers.google.com/vr/daydream/controller-emulator), there's a section labelled "Game engines".  You can use a USB debugging-enabled phone running the ControllerEmulator app and connected via USB in Unity Play mode.  Make sure to enable the "USB" EmulatorConnectionMode on the GvrControllerInput script in your Unity scene (which should be default in the Demo scenes)!  Also, make sure the phone running the ControllerEmulator app doesn't have the InstantPreview app installed; I ran into some issues with the InstantPreview app closing the ControllerEmulator when I hit the Play button.

We'll fix up the documentation to point towards these, and look into documentation detailing setups for testing in Play mode with 2 Phones, 1 Phone / 1 Controller, and just 1 Phone.
