### ISSUE TITLE
How to control the grid density in the discretized virtual world in unity

### ISSUE THREAD

**Issue by spaul13** [googlevr/gvr-unity-sdk#887]
Summary:
Can anyone please tell me how to set the grid density in the discretized virtual world where the player can actually move in unity while making a VR game using Google Daydream VR SDK?

Is there any correlation between the grid density and the Stereo separation between two eyes?

Found using:
 * Google VR SDK version: 1.40 (old version)
 * Unity version: 5.6.4p4
 * Phone manufacturer, model, and O/S version: PIXEL XL

**Comment by rusmaxham** [comment]
I think you're asking about [XR.XRSettings.eyeTextureResolutionScale](https://docs.unity3d.com/ScriptReference/XR.XRSettings-eyeTextureResolutionScale.html).  This determines the resolution Unity renders into before distortion rendering.  Higher resolution scale will result in higher sharpness, but increased GPU load, higher thermals, and possible lower frame rate.

Is that what you're looking for?

**Comment by spaul13** [comment]
No. Not this one. I just saw the default value of its 1. But in the case of the grid density, typically it's valued 0.02 Unity units (I found after some search). But I want to know how to control it, how to change that value.

What I know that in the virtual world, we can't move at each and every place we want as it's not continuous. The two neighboring points' gap is 0.02 Unity units which are referred to as grid density.

Can u explain me this little bit and how to change this value?

**Comment by fredsa** [comment]
@spaul13 Are you referring to floating point precision in world space coordinates?

Near the origin `(0, 0, 0)` in world space, precision should be very high. Farther away from the origin precision is reduced, see many articles online ([example](http://davenewson.com/posts/2013/unity-coordinates-and-scales.html)).

Best advice is to keep your game objects relatively close to the origin.

**Comment by rusmaxham** [comment]
If you still need help with this issue, please reopen.
