### ISSUE TITLE
Lenovo Mirage Solo WorldSense support in GVR?

### ISSUE THREAD

**Issue by reed-alpert** [googlevr/gvr-unity-sdk#890]
Summary: Mirage release date is May 6, will GVR have a new release to support WorldSense information such as when the HMD moves and to where?

**Comment by rusmaxham** [comment]
Yes.  Unity 2017.3 builds Daydream apps that support 6DoF head tracking by default.  You can control the level of head tracking support in Player Settings > XR Settings:

![screen shot 2018-03-09 at 2 55 00 pm](https://user-images.githubusercontent.com/13911074/38153486-e7b4d062-3421-11e8-9e63-9b7f23b27ab2.png)

If you're using an older version of Unity, you can manually enable it by copying `Assets/GoogleVR/Plugins/Android/AndroidManifest-6DOF.xml` to `Assets/Plugins/Android/AndroidManifest.xml`.
