### ISSUE TITLE
missing release notes from older releases

### ISSUE THREAD

**Issue by unitycoder** [googlevr/gvr-unity-sdk#893]
in the releases page, older packages don't have any notes.. and the old page in google dev site (which i think used to list these), redirects to github releases..

founded some until 0.7, but missing at least those between 0.8 - 1.30
https://github.com/googlevr/gvr-unity-sdk/blob/ce58e52a6519c15fbc909cf71dcee6532237581b/CHANGELOG

**Comment by rusmaxham** [comment]
We'll get the old release notes back up in the Releases section.

**Comment by rusmaxham** [comment]
Previous release notes now available in the releases section.
