### ISSUE TITLE
GVR SDK used with Muse SDK in Unity causes crash, but only on iOS

### ISSUE THREAD

**Issue by truekvlt** [googlevr/gvr-unity-sdk#894]
Summary:
Something about GVR SDK when used with Muse SDK causes this error:
Thread 1: EXC_BAD_ACCESS (code=1, address=0x2004187a010a0c)

The project builds in Unity, Builds in Xcode, but on the first frame it runs it crashes with that error. There must be a solvable conflict between the libraries.

Found using:
 * Google VR SDK version: v1.130.1
 * Unity version: 2017.4.0f1 Personal
 * Phone manufacturer, model, and O/S version: iPhone 6, iPhone 7, iPhone X // 11.2.6 & 11.3
 * Viewer manufacturer & model: Google Cardboard by Google

Steps to reproduce the issue:
1. Take the example Google VR scene “HelloVR”, and add the Muse “Sample App” script to an object in the scene. Found here: http://developer.choosemuse.com/sdk/unity version: 6.0.3
2. Remove the Google VR android instant preview object from the scene, since that only works for android.
3. The iOS plugins folder has all the Muse for Unity iOS files in it, just like the Muse for Unity iOS example project has. (thats Muse.Framework and LibMuseUnityiOS)
4. Build for iOS.
5. In the resulting Xcode project, add external accessory framework, and core bluetooth framework.
Build to an iPhone/iPad. It builds and installs. It crashes as soon as it starts running.

Workarounds:
None known. GVR & Muse work in android builds, tho. This is iOS specific.

Additional comments:
Mind, I created this example just to reproduce the error. The error occurs in the exact same way in my real project, which has a lot more going on of course.

FYI, Muse is an EEG brain reading headset. I am using the SDK from the manufacturer. It's really cool. I really want this bug fixed so I can make my cool GVR game using brain data! : O

I attach a screenshot of thread 1 in Xcode for reference.

![screen shot 2018-04-05 at 16 16 43](https://user-images.githubusercontent.com/7738264/38422729-14f2e93a-39ac-11e8-87ac-807928e6a231.png)

**Comment by oliver93mk** [comment]
I've encountered the exact same problem! A fix or a workaround would be very much appreciated!

**Comment by truekvlt** [comment]
I posted the same error on the Muse forum. So far, no word, but they said they are looking into it.

http://forum.choosemuse.com/t/muse-sdk-google-vr-sdk-on-unity-ios-builds-but-crashes-immediately/2816 @oliver93mk 

Maybe you can post, here, too, to bring more attention to the issue.

**Comment by fredsa** [comment]
Please reopen if you have additional diagnostic details.

**Comment by danielmapar** [comment]
Any news on that @myloran ?

**Comment by myloran** [comment]
> Any news on that @myloran ?

 nothing

**Comment by danielmapar** [comment]
Yes, the Muse folks don't care a single bit about their SDK.. it is currently fully unsupported. Time to look for other EEG devices.
