### ISSUE TITLE
Can't build non-VR app once sdk is installed

### ISSUE THREAD

**Issue by jacqueslelezard** [googlevr/gvr-unity-sdk#895]
Summary:
I've installed the Google vr sdk, and it works fine when I enable the Unity XR settings. However I would like to build another version WITHOUT vr enabled, but then unity won't let me build, saying that I MUST check this option... Any idea on how to build anyway ? Thanks

To reproduce: 
Unity 2017.4
GVR SDK for Unity v1.130.1

**Comment by unitycoder** [comment]
have you tried this,
https://developers.google.com/vr/develop/unity/guides/hybrid-apps

**Comment by LucasBenvenuti** [comment]
Same problem here... Anyone can help?
