### ISSUE TITLE
Unity iOS: blackout on both left and right side in google cardboard view. 

### ISSUE THREAD

**Issue by MicroEyes** [googlevr/gvr-unity-sdk#897]
Summary:
I am following guide for Unity-iOS from [here](https://developers.google.com/vr/develop/unity/get-started-ios). I am having issues with "HelloVR" demo scene that comes with sdk unity package.

I have two issues here.
1. After installing game on IPhone 5S, without cardboard, both left and right views are not symmetric. Right view/lens shows more towards left side and Left view/lens shows more towards right side. [Attached image gvr_1.jpg]
![gvr_1](https://user-images.githubusercontent.com/2142511/38915588-e2966d18-4301-11e8-81fc-ebd0a7374221.jpg)

2. When using Cardboard views, i see left and right side as completely black and only middle rectangular part for game [Attached vr_camera_error2.jpg]
![vr_camera_error2](https://user-images.githubusercontent.com/2142511/38926633-fc88de94-4320-11e8-9c06-ded1aad6e07a.jpg)

Found using:
 * Google VR SDK version: v1.130.1
 * Unity version: 2017.3.1f1
 * Phone manufacturer, model, and O/S version: IPhone 5S, Model:MF352HN/A, OS version:11.2.2 (15C202)
 * Viewer manufacturer & model: Google v2.0

Steps to reproduce the issue:
 1. On Unity 2017.3.1f1, follow guided for "HelloVR" demo Scene VR.
2. Switch platform to iOS, set VR settings on "Player Settings" and create iOS build.

**Edit#1:** Found _Issue#2_ is specific to iOS. Output from cardboard viewer with Android device is working fine. With android device i can see the whole scene and not blackout on both left-right sides.

**Comment by loop0222** [comment]
i have the same problem as your first issue in android

**Comment by ddrocco** [comment]
Hi, thanks for reporting!  We're looking into this.

**Comment by kschmidtdev** [comment]
I don't have the blackout issue in Android, but on iOS it seems like the eyes are swapped? (using `1.130.1`)

**Comment by rusmaxham** [comment]
For 1) that is the natural result of the headset's field of view being clipped to a small screen.  That is not a bug.  I'm unsure how you got that to happen.  What is "cardboard views"?

**Comment by ddrocco** [comment]
Regarding iOS eye swaps, that seems like a different issue entirely and probably warrants another bug.    I haven't been able to reproduce it.  Are you still encountering that issue?  What steps can I take to try to reproduce it, and what kind of Unity / XCode environment are you running?

**Comment by kschmidtdev** [comment]
@ddrocco I apologize my report is a false positive.

**Comment by ddrocco** [comment]
Awesome, glad to hear things are working :)

**Comment by TonGarcia** [comment]
Hello all, I'm facing the same problem, but a bit more strange... I have the same env of @MicroEyes just my unity is different, it is the 2018.2. My final result is an "exploded eye" and something like a "padding" on top. My icons are "outside of the eye area". My eyes are not seeing the same thing too, that part is not the main problem because I caused it trying to fix it wrong eye dimension.
![unity-googlevr-bug](https://user-images.githubusercontent.com/3121488/40944791-6cdb73e8-682c-11e8-9f54-f799d1869998.jpg)
.

**Comment by TonGarcia** [comment]
Using the same code with Unity 2018.2 it works correctly for Android Moto Z Play. It is a bug for iOS iPhone 5s. I'll test it on an iPhone X.


![2018-06-04 20 44 34](https://user-images.githubusercontent.com/3121488/40947277-40449fe2-6838-11e8-8fbe-94db00fe51c6.jpg)
![2018-06-04 20 44 41](https://user-images.githubusercontent.com/3121488/40947278-4068af90-6838-11e8-8890-4e7991c015fe.jpg)

**Comment by rusmaxham** [comment]
@TonGarcia in Player Settings > Settings for iOS > Resolution and Presentation, are you setting Allowed Orientations for Auto Rotation to "Landscape Left" ONLY (disable portrait orientations_?

**Comment by TonGarcia** [comment]
@rusmaxham It did the trick! Thx!

**Comment by rusmaxham** [comment]
I am happy to hear you are unblocked now.

**Comment by TonGarcia** [comment]
Hi guys, sadly it @rusmaxham solution is not working on a new project using Unity's LightWeight RenderPipeline. There is any additional settings? Android*, not tested for iPhone


![photo_2019-08-21_18-47-37](https://user-images.githubusercontent.com/3121488/63470892-2a6b3500-c444-11e9-9235-48ecb8f752df.jpg)
.

![GVR-Orientation](https://user-images.githubusercontent.com/3121488/63470825-fc85f080-c443-11e9-88a9-75a4b044fbf4.png)
