### ISSUE TITLE
Instant Preview not working in HelloVR demo with Pixel 2

### ISSUE THREAD

**Issue by luxcreativity** [googlevr/gvr-unity-sdk#898]
As stated, I'm finding the documentation of Daydream View 2 absolutely infuriating.

I go through the instructions step by step to test Instant Preview on the HelloVR Demo Scene:

-Android platform selected
-Android version to Nougat 7.0
-VR for Daydream enabled in Player Settings
-USB Debugging enabled on phone
-USB plugged in and set file transfer (as opposed to charging only)

Press play in the editor and receive:
"Virtual Reality SDK Daydream is not supported in Editor Play Mode. Please Build and run on a supported target device.
Attempting to enable None instead."

With "Daydream Instant Preview" stating "Not connected to Editor"

I can't figure out what the issue is here, no other HMD SDK has given me this amount of grief.

Unity 2017.4.1f1, Android 8.1 on Pixel 2, GVR SDK for Unity v1.130.1, newest Java and Android SDKs

**Comment by vinhui** [comment]
Do you have `USB Debugging` enabled on the phone?

**Comment by vinhui** [comment]
Have you authorized your pc on your phone? Try `adb devices` in the command line, do you see your phone there?

**Comment by luxcreativity** [comment]
Hi thanks for your reply.

After restarting multiple times Instant preview is kind of working but the connection persistently drops and then reconnects whilst running at a very low framerate (with vsync turned off) in a near to empty scene (one canvas with button, one sphere with OnPointerEnter trigger event to change material colour).

There's clearly some latent incompatibility issue but I'm at a loss what to look for next.

I'll build and run the near empty scene to check whether it's only an issue with Instant preview or there's a deeper problem.

**Comment by vinhui** [comment]
Have you tried a different usb cable?

**Comment by rusmaxham** [comment]
If you still need assistance with this issue, please reopen.
