### ISSUE TITLE
SupportsPositionalTracking(); does not work on.

### ISSUE THREAD

**Issue by splas-boomerang** [googlevr/gvr-unity-sdk#899]
Summary:
`AndroidNativeHeadsetProvider.SupportsPositionalTracking();` does not return true when the app runs in Daydream Standalone  model.

Found using:
 * Google VR SDK version: v1.130.1 (Also v1.120.0)
 * Unity version: 2017.3.0p4
 * Phone manufacturer, model, and O/S version: Lenovo, Mirage Solo, VR-1541F, Android 8.0.0, OVR1.180406.005
 * Viewer manufacturer & model: Same as above

Steps to reproduce the issue:
 1. Call `GvrHeadset.SupportsPositionalTracking();` in scene;
 2. Build and Run in Daydream Standalone  model likes Mirage Solo.
 3. `GvrHeadset.SupportsPositionalTracking();` return false. 

Workarounds:
None

Additional comments:
None

**Comment by fredsa** [comment]
Can you confirm that **Player Settings > Android > XR Settings > Virtual Reality SDKs > Daydream > Positional Head Tracking** is set to either **Supported** or **Required**?
<img width="351" alt="screen shot 2018-04-24 at 8 43 57 am" src="https://user-images.githubusercontent.com/1235362/39198341-acc6beb0-479b-11e8-94cb-cdd043554a1c.png">

**Comment by rusmaxham** [comment]
Also, do you have the Assets/GoogleVR/Prefabs/Headset/GvrHeadset.prefab in your scene?

**Comment by splas-boomerang** [comment]
@fredsa
Thank you, *Positional Head Tracking* is set to either Supported or Required.

@rusmaxham 
Thank you.  `SupportsPositionalTracking();` has worked when I added GvrHeadset.prefab in scene.
