### ISSUE TITLE
Large increase in blocked frames, Unity rigidbody and hi res textures

### ISSUE THREAD

**Issue by davidcox70** [googlevr/gvr-unity-sdk#900]
Unity 2017.3.1f1 64 bit.
Google VR For Unity SDK 1.130.1
Device: Samsung Galaxy S8 SM-G950F
Google VR Build: 1.14.190701955

This is a bit of an odd one. I've been struggling with frame rate in a particular scenario with a Samsung S8 SM G950F, and have found this odd issue;

With a scene of non-moving textured objects, where the camera is set to spin at a uniform rate using Unity's Update() and Transform methods, the resulting view is a perfectly smooth translation of those objects as they "pass by" the camera's view. However, if I change the way the camera rotates so that it is driven by a RigidBody with some angular force and no drag, as opposed to a direct rotational transform, then the GVR Performance Hud shows up to 50% blocked frames where the view passes highly textured objects.

This seems odd - I understand that blocked frames are the result of the GPU still being busy computing the last frame, so why would the method to rotate the camera in the exact same scene cause blocked frames? Ultimately, what the renderer is being asked to process is the same. It's just how the camera angle of rotation is calculated that changes. I tried the same test exporting to Gear VR using the Oculus SDK and the problem of reduced frame rate is not apparent.

To test, create a very highly textured model. In my case, it is a planet sphere with multiple 4K textures and so probably close to the limit of the device's capability. Set the application frame rate to 60. Then add an empty game object and a camera as a child of that. If you rotate the camera's parent with something like;

`parentGameObject.transform.rotate(0,50*Time.deltaTime,0);`

in the Update() function, there are no blocked frames.

But if you remove the line in Update(), add a rigidBody to the parent game object with gravity and angular drag set to 0, set the physics timestep to 0.01666 (1/60th sec) and instead add something like this in the Start() method to drive the rotation;

`parentGameObject.GetComponent<RigidBody>().AddRelativeTorque(new Vector3(0,10,0));`

then the onset of blocked frames seems to occur earlier in so far that objects with multiple high resolution textures causes blocked frames as they pass by the view.

I'm confused! So any help gratefully received.

DC

**Comment by rusmaxham** [comment]
Are you able to share a sample Unity project that reproduces the issue?

**Comment by davidcox70** [comment]
Well typically, when I made up a new project with just a spinning camera and objects with high resolution textures, it all works fine! So I'll dig deeper and see what other components are causing this....

**Comment by rusmaxham** [comment]
Ok, if you find something in the GVR SDK that is related to this, please re-open this issue.
