### ISSUE TITLE
Can the SDK work with Obi Fluid?

### ISSUE THREAD

**Issue by ylluminarious** [googlevr/gvr-unity-sdk#903]
This is more of a question than a bug report. A project of mine has come to rely on the [Obi Fluid plugin](https://assetstore.unity.com/packages/tools/physics/obi-fluid-63067) from the Asset Store. Unfortunately, [according to their FAQ,](http://obi.virtualmethodstudio.com/tutorials/index.html) Obi Fluid has some limitations regarding VR:

> ### Does it support VR (Virtual Reality)?
> 
> **Cloth and Rope** will support VR. For **Obi Fluid**, you will have to use separate cameras for each eye since the renderer does not support single-pass stereo rendering.

As far as I can tell, this sort of camera setup is incompatible with the way that GVR SDK does things. Am I wrong about this? Can this kind of setup required by Obi Fluid actually work fine with the SDK on both Daydream and Cardboard?

**Comment by rusmaxham** [comment]
You can create multiple cameras and assign them Left/Right Target Eyes.

![screen shot 2018-05-11 at 10 02 37 am](https://user-images.githubusercontent.com/13911074/39936790-800f49c2-5502-11e8-90d6-ecc40e92c9eb.png)

**Comment by rusmaxham** [comment]
If you still need assistance, reply to or reopen this issue.

**Comment by ylluminarious** [comment]
@rusmaxham Sorry, I meant to reply to this a couple of weeks ago after you sent it. I've been terribly busy with this project so I haven't had the time. I haven't tried your solution yet, but according to some correspondence with the Obi developer, this seems like it will work perfectly. I'll reply again if I need further help. Thank you.
