### ISSUE TITLE
iOS overlay: Dead end at cog button-> "Switch viewer"

### ISSUE THREAD

**Issue by lexar** [googlevr/gvr-unity-sdk#906]
Summary:
When on iOS and tapping the cog/settings button, a menu appears with two entries: Help (leads to a website in Safari) and “Switch viewer”. There I am supposed to show a QR code to the camera. 
There is no way to exit this screen except scanning a QR code. “Skip” does not have any effect and there is no other option to go back to the VR app. I found no other way than to kill the app through the task manager.
I’m pretty sure this is a bug unless I overlooked something?

Found using:
 * Google VR SDK version: 1.130.1
 * Unity version: 2017.4.1f1
 * Phone manufacturer, model, and O/S version: Apple, iPhone 6s, iOS 11.3.1
 * Viewer manufacturer & model: Virtoba X5

Steps to reproduce the issue:
 1. Start a cardboard iOS app in VR mode
 2. Tap on the cog symbol in the upper right corner
 3. Tap on "Switch viewer"
 4. It is not possible to exit the screen without scanning a QR code.

Workarounds:
Scan a code or kill the entire app and start over.

Additional comments:

**Comment by rusmaxham** [comment]
I'm unable to reproduce this issue with the same setup.  Are you able to send me a Unity project that reproduces the issue?

**Comment by lexar** [comment]
Hi, I tried with the HelloVR project and a simple example project, the skip button works in both. However, it does not work in my app. I am trying to figure out what is different in my app and will post an example project when I found it.

**Comment by chaosemer** [comment]
Please reopen if you get more details.
