### ISSUE TITLE
using device camera for webcamtexture on google cardboard not working

### ISSUE THREAD

**Issue by pandailing** [googlevr/gvr-unity-sdk#908]
Summary:
i want to use android camera from my Android Phone for the Raw Image in the Unity. I follow the instructions at https://www.youtube.com/watch?v=c6NXkZWXHnc for the simple apps and working.

but when i use "Virtual Reality Supported" on my builder and run it on my phone, the camera didn't work. 

normal apps would ask for permission for this, but when i use vr mode, there is no any pop up messages. What should I do? 

Found using:
 * Google VR SDK version:
 * Unity version: 2017.4.0f1
 * Phone manufacturer, model, and O/S version: Samsung Galaxy S7
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1. follow the tutorial at https://www.youtube.com/watch?v=c6NXkZWXHnc
 1. make the canvas -> render mode -> World space
 1. build and run on Android

Workarounds:

Additional comments:

**Comment by vinhui** [comment]
Check the `PermissionsDemo` scene, that might be what you're looking for

**Comment by pandailing** [comment]
hello guys, i finally had a successful solution, just adding a few line
1. open your AndroidManifest.xml (if you had) and AndroidManifest-Cardboard.xml
2. add following line to your code inside your <activity> tags, to each opened xml
`
<activity android:name= bla bla
......
<meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="false"/>
</activity>
`
3. add following line outside the <application> tag but still inside <manifest> tag
`

  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.hardware.camera"/>
  <uses-feature android:name="android.hardware.camera"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
`
4. build try to run the apps in your mobile phone. At the first splash screen, the permission will pop up and allow it

i hope it would help you all

**Comment by rusmaxham** [comment]
Happy to hear you found a solution.
