### ISSUE TITLE
How to build for iOS when Unity project includes Google VR SDK, but it is not in use?

### ISSUE THREAD

**Issue by dustinfreeman** [googlevr/gvr-unity-sdk#909]
I'm working on a multiplatform app that needs a Cardboard and non-Cardboard (i.e. mono 2D) version. I want to build these both from the same Unity project.
Question: What's the best way to build a conventional, 2D touch-based app not meant to be used with an HMD when the Google VR SDK is in the Unity project? 

Here's my current approach:

To allow Unity builds for iOS, I changed Errors to Warnings in `GvrBuildProcessor.cs`

```        // 'Player Settings > Virtual Reality Supported' must be enabled.
        if (!IsVRSupportEnabled()) {
+            Debug.LogWarningFormat(VR_SETTINGS_NOT_ENABLED_ERROR_MESSAGE_FORMAT, target);
-            Debug.LogErrorFormat(VR_SETTINGS_NOT_ENABLED_ERROR_MESSAGE_FORMAT, target);
        }
...
        if (target == BuildTarget.iOS) {
            // When building for iOS at least one VR SDK must be included.
            // For Google VR only 'Cardboard' is supported.
            if (!IsSDKOtherThanNoneIncluded()) {
+                Debug.LogWarning(IOS_MISSING_GVR_SDK_ERROR_MESSAGE);
-                Debug.LogError(IOS_MISSING_GVR_SDK_ERROR_MESSAGE);
            }
        }
```

However, when I try to build the resulting Xcode project, build fails with errors:

```Showing All Messages
  "_gvr_set_default_viewer_profile", referenced from:
      _GvrCardboardHelpers_SetViewerProfile_m1619990416 in Bulk_Assembly-CSharp_2.o
      _GvrCardboardHelpers_gvr_set_default_viewer_profile_m112123778 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _GvrCardboardHelpers_gvr_set_default_viewer_profile_m112123778)
  "_gvr_reset_tracking", referenced from:
      _GvrCardboardHelpers_Recenter_m4223839489 in Bulk_Assembly-CSharp_2.o
      _GvrCardboardHelpers_gvr_reset_tracking_m716926585 in Bulk_Assembly-CSharp_2.o
     (maybe you meant: _GvrCardboardHelpers_gvr_reset_tracking_m716926585)
  "_gvr_get_time_point_now", referenced from:
      _AndroidNativeKeyboardProvider_gvr_get_time_point_now_m3901657736 in Bulk_Assembly-CSharp_1.o
      _AndroidNativeKeyboardProvider_UpdateData_m3912445729 in Bulk_Assembly-CSharp_1.o
     (maybe you meant: _AndroidNativeKeyboardProvider_gvr_get_time_point_now_m3901657736)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Found using:
 * Google VR SDK version: 1.130.1 (tested with both)
 * Unity version: 2017.4.2f2 and 2017.3.1f1 (tested with both)

**Comment by dustinfreeman** [comment]
Current workaround: I can set the camera in my Unity Scene to have TargetEye = Main Display , as opposed to both left and right eyes. Once the scene loads, everything works as in a conventional 2D iOS app. 

HOWEVER, as the scene is loading, the Google VR stereo view appears, like so:

![2018-05-09 12 30 14](https://user-images.githubusercontent.com/940836/39827420-db51fccc-5385-11e8-98f2-9f6584d04baa.png)

Note that in my XR Settings, "Enable Transition View" is set to false.

**Comment by rusmaxham** [comment]
Follow [this guide](https://developers.google.com/vr/develop/unity/guides/hybrid-apps) for instructions on building a hybrid VR and non-VR app.

**Comment by dustinfreeman** [comment]
For my 2D-only apps, it appears that I can create an app in hybrid mode, and just never transition to VR. This is sufficient for me for now, though I agree that I don't like GVR code creeping in if it isn't relevant. Thanks for the detailed feedback.
