### ISSUE TITLE
Instant Preview doesn't work "Couldn't start Instant Preview server with adb path:"

### ISSUE THREAD

**Issue by Yunqi-Hu** [googlevr/gvr-unity-sdk#910]
Summary:
I was trying to run the Hello VR scene with ASUS ZenPhone AR connected to my Mac. But I couldn't get the instant preview work. It says "Couldn't start Instant Preview server with adb path:". I added the path of the Android SDK to .dash_profile, but it still didn't work. Here is the Unity console
<img width="831" alt="screen shot 2018-05-11 at 12 13 48 am" src="https://user-images.githubusercontent.com/10550363/39911530-9ce0710e-54b0-11e8-9ec2-f7b3d5cbb96f.png">

Found using:
 * Google VR SDK version: 1.130.1
 * Unity version: 2018.1.0f2
 * Phone manufacturer, model, and O/S version: ASUS, Zenphone AR, Android 7.0
 * Viewer manufacturer & model: Daydream View

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by gstanlo** [comment]
To clarify, does adb run properly if you start it from /Users/<name>/Documents/Android SDK/platform-tools/adb ?

**Comment by Yunqi-Hu** [comment]
@gstanlo Thanks for the reminder. I tried to start it from that path, it turns out that path is not valid somehow. I fixed the problem by relocate the SDK and put the new path into both Unity and the .dash_profile. Thank you!
