### ISSUE TITLE
Instant Preview not working on Lenovo Mirage Solo

### ISSUE THREAD

**Issue by FriskyBishop** [googlevr/gvr-unity-sdk#913]
Summary:
Instant Preview not working on Lenovo Mirage Solo when using "Full VR Preview"

Testing with the HelloVR scene.

- If using "Controller Only" option the controller will track OK.
- If using "Full VR Preview" nothing works, neither the controller nor the headset is tracked, device screen is blank, half the time the device crashes and must be restarted

Tested and working on Samsung 8 and 8+

Found using:
 * Google VR SDK version: GVR SDK for Unity v1.130.1
 * Unity version: 2018.1.0b6 & 2017.3.0f3
 * Phone manufacturer, model, and O/S version: Lenovo Mirage Solo Android 8.0.0
 * Viewer manufacturer & model: Lenovo Mirage Solo

Additional:
When running Instant Preview app from the Lenovo Mirage Solo the device screen just goes blank.

**Comment by ddrocco** [comment]
Thanks for reporting, we're looking into this!

**Comment by rusmaxham** [comment]
This will be fixed in the next release.

**Comment by rusmaxham** [comment]
Fixed in [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
