### ISSUE TITLE
Neck offset incorrect

### ISSUE THREAD

**Issue by vinhui** [googlevr/gvr-unity-sdk#914]
Summary:
In editor (instant preview) and in build, the neck offset is incorrect. The offset on the camera is always `.08` in the Z axis. This is incorrect when the camera is rotated 90 degrees on the Y axis. The correct thing would be that it first rotates the camera and then does the `.08` offset on the local forward (instead of the world forward).

Found using:
 * Google VR SDK version: 1.110.0
 * Unity version: 2017.2.0p1
 * Phone manufacturer, model, and O/S version: -
 * Viewer manufacturer & model: -

Steps to reproduce the issue:
 1. Create an empty scene with a camera
 2. Add the instant preview stuff
 3. Go into play mode and see that the Z position of the camera always is `.08`, no matter what the rotation of the device is

Workarounds:

Additional comments:
It seems to me that it's not this sdk nor unity but rather the vr service since the issue is in both the build and instant preview. If it were a unity issue, it wouldn't show up with instant preview because unity handles the camera rotation in build, and if it was the fault of this sdk, it would only show up in instant preview.

**Comment by rusmaxham** [comment]
Thanks for reporting this.  We'll take a look.

**Comment by vinhui** [comment]
Any updates about this issue?

**Comment by rusmaxham** [comment]
We're working on a fix.

**Comment by rusmaxham** [comment]
For the on-device build, Unity doesn't transform the main camera with the neck model.  The only way to get the neck offset on device is to get the Left and Right eye positions and then get the mid-point between them.

```C#
using UnityEngine.XR;
Vector3 pos = Camera.main.transform.parent.TransformPoint(InputTracking.GetLocalPosition(XRNode.LeftEye));
```

Unfortunately, `XRNode.CenterEye` and `XRNode.Head` report the same no-neck-model position as the main camera on Daydream.

**Comment by vinhui** [comment]
So just removing the z offset (that's still there from old sdk setup) is the expected way to set up the camera?

**Comment by rusmaxham** [comment]
What position is it that you would like to get?

**Comment by rusmaxham** [comment]
I've dug into this a bit more and it looks like neck model used to be applied to the main camera, XRNode.Head, and XRNode.CenterEye from Unity 5.6 up through 2017.2, but broke in 2017.3 on.

In general we do recommend parenting the main camera to a player object.  This is how the HelloVR sample is setup.

**Comment by rusmaxham** [comment]
This looks like it may be a GoogleVR platform bug.  Neck model offset is only incorrect on Android 8, but not Android 7.  I believe there is a known issue where GVR on Android 8 smartphones falsely reports that it can do positional head tracking.

**Comment by vinhui** [comment]
Thanks, that was the answer I was looking for.

**Comment by rusmaxham** [comment]
The missing neck model from on-device builds running on Android 8 is fixed in the upcoming release of Daydream VR Services, due to be available in a week or two via Play Store update.  The missing neck model in Instant Preview is fixed in the upcoming release of the GVR SDK for Unity, due to be available in a few weeks.

**Comment by rusmaxham** [comment]
Fixed in [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
