### ISSUE TITLE
GVR Keyboard Doesn't Work With IL2CPP

### ISSUE THREAD

**Issue by Moncader** [googlevr/gvr-unity-sdk#917]
Summary:
When enabling IL2CPP in the newest versions of Unity with the new .NET system, if you attempt to show the GVR Keyboard, Unity will crash.

Found using:
 * Google VR SDK version: v1.130.1
 * Unity version: 2018.1.0f2
 * Phone manufacturer, model, and O/S version: All Pixel/Pixel 2 devices
 * Viewer manufacturer & model: Daydream View (both)

Steps to reproduce the issue:
 1. Show the GVR Keyboard

Workarounds:
```diff
--- a/Assets/GoogleVR/Scripts/Keyboard/GvrKeyboard.cs
+++ b/Assets/GoogleVR/Scripts/Keyboard/GvrKeyboard.cs
@@ -313,6 +315,9 @@ public class GvrKeyboard : MonoBehaviour {
     }
   }

+  private delegate void KeyboardCallbackDelegate(IntPtr closure, GvrKeyboardEvent keyboardEvent);
+
+  [AOT.MonoPInvokeCallback(typeof(KeyboardCallbackDelegate))]
   private static void OnKeyboardCallback(IntPtr closure, GvrKeyboardEvent keyboardEvent) {
     lock (callbacksLock) {
       threadSafeCallbacks.Add(keyboardEvent);
```

The above code fixes the issue.

**Comment by rusmaxham** [comment]
Thanks for reporting this.  This will be fixed in the next release.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
