### ISSUE TITLE
After destroying a GVRKeyboard component, adding a new one will crash Unity

### ISSUE THREAD

**Issue by Moncader** [googlevr/gvr-unity-sdk#918]
Summary:
Exactly as the title says.

Found using:
 * Google VR SDK version: v1.130.1
 * Unity version: 2018.1.0f2
 * Phone manufacturer, model, and O/S version: All Daydream devices
 * Viewer manufacturer & model: All Daydream Views

Steps to reproduce the issue:
 1. Add a GVRKeyboard component to a GameObject in a scene.
 1. Destroy that GameObject or GVRKeyboard component.
 1. Add another GVRKeyboard component to a GameObject in a scene.
 1. Unity will crash.

Workarounds:
```diff
--- a/Assets/GoogleVR/Scripts/Keyboard/GvrKeyboard.cs
+++ b/Assets/GoogleVR/Scripts/Keyboard/GvrKeyboard.cs
@@ -131,6 +131,8 @@ public class GvrKeyboard : MonoBehaviour {

   void OnDestroy() {
     instance = null;
+
+    threadSafeCallbacks.Clear();
   }

   // Use this for initialization.
```
 The above will make everything work again.

**Comment by rusmaxham** [comment]
Thanks for reporting this. This will be fixed in the next release.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
