### ISSUE TITLE
How to determine if pointer click happened on a UI element?

### ISSUE THREAD

**Issue by lexar** [googlevr/gvr-unity-sdk#919]
To determine if a click/tap happened over an UI element (and therefore, ignore that tap in the game) I used
```
void Update() {
if (Input.GetMouseButtonDown(0)) {
            if (EventSystem.current.IsPointerOverGameObject() == true) {
                Debug.Log("Clicked on UI!");
                return false;
            }
            return true;
}
}
```
..which is, although badly named, to my knowledge the intended purpose of EventSystem.isPointerOverGameObject.

But it appears that if the GVRReticlePointer with GVREventSystem is used, the code above will return true to any gameobject. 
So I have no way to determine if a UI button has been clicked. If the code above returns true on isPointerOverGameObject, the button action will happen but the mouse click causes also an action in a game (i.e. a gun is fired). If it returns false, the gun fire is disabled.

Is there a workaround for that? How can I determine if a UI element has been clicked?

**Comment by ddrocco** [comment]
Since it's been a while, I'm marking this as closed for the time being.  Hopefully you found a workaround or got things working!  If not, feel free to reopen this bug with more info and we'll take a look!
