### ISSUE TITLE
HelloVR scene not rendering properly on Samsung Galaxy S8

### ISSUE THREAD

**Issue by mettinger** [googlevr/gvr-unity-sdk#922]
I'm working through the tutorial "Quickstart for Google VR SDK for Unity with Android".  Everything works fine in Unity but when the app runs on my Samsung S8 the scene rendered is just the blank default landscape and not the intended scene that I can see in the Unity editor.  

Furthermore during the "Build and Run" process I get these errors (though the process apparently succeeds in installing the apk to my phone and running it):

UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0021f] in /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:182 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:89 
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

Found using:
 * Google VR SDK version: 1.130.1
 * Unity version: 2018.1.1f1
 * Phone manufacturer, model, and O/S version: Samsung Galaxy S8, Samsung Experience Version 8.1
 * Viewer manufacturer & model: Google Daydream

**Comment by vinhui** [comment]
Did you add the correct scene to the build settings?

**Comment by mettinger** [comment]
Thank you @vinhui, it is working.  Maybe I'm overlooking it, but I can't find this step in the tutorial?

**Comment by rusmaxham** [comment]
Unity should by default build the currently open scene if none are specified in the Build Settings > Scenes In Build.  Did you have the HelloVR scene open in the editor?

**Comment by mettinger** [comment]
I did have the scene open in the editor.  Not sure why default did not work.  In any case, I think it should be noted in the tutorial documentation.  Thanks again!

**Comment by CGAnderson** [comment]
I've seen this behavior from Unity as well. Perhaps caused when you have more than one scene and previous builds. Just guessing tho'.
