### ISSUE TITLE
EntryPointNotFoundException: CreateSoundObject

### ISSUE THREAD

**Issue by vivekghanchi** [googlevr/gvr-unity-sdk#923]
Summary:EntryPointNotFoundException: CreateSoundObject
GvrAudio.CreateAudioSource (Boolean hrtfEnabled) (at Assets/GoogleVR/Scripts/Audio/GvrAudio.cs:138)
GvrAudioSource.InitializeSource () (at Assets/GoogleVR/Scripts/Audio/GvrAudioSource.cs:458)
GvrAudioSource.Play () (at Assets/GoogleVR/Scripts/Audio/GvrAudioSource.cs:376)
GvrAudioSource.Start () (at Assets/GoogleVR/Scripts/Audio/GvrAudioSource.cs:307)

Found using:
 * Google VR SDK version: 1.60.0
 * Unity version: 2017.3.1f1
 * Phone manufacturer, model, and O/S version:Redmi 3s Prime
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by rusmaxham** [comment]
Can you verify that Assets/GoogleVR/Plugins/Android/libs/armeabi-v7a/libaudioplugingvrunity.so exists and the Inspector says that it is configured for Android and ARMv7 CPU?

**Comment by rusmaxham** [comment]
If this is still an issue for you, please comment and re-open.
