### ISSUE TITLE
Force to start application in 2d mode from Daydream Home.

### ISSUE THREAD

**Issue by Azirel** [googlevr/gvr-unity-sdk#924]
Summary:
I have a hybrid application. Is there any way to force application be launched from Daydream Home in 2d mode at start? Without settings screen at the beggining ("Please insert device into elmet"or smth).
Basically at the start of application user has to login into system via socials networks (Google +, FB) which SDKs work with native Android UI which do not work properly in VR mode.
I've managed to make it launch as intended , but only from home screen.

Steps to reproduce the issue:
 1. Make XR settings like this http://prntscr.com/jtx9e0
 2. Switch to VR mode like this somewhere in your Unity project.
   IEnumerator Switch()
   {
            XRSettings.LoadDeviceByName(XRSettings.supportedDevices[1]);
            yield return null;
            XRSettings.enabled = true;
   }
3. Launch from Home screen:
App starts in 2d mode as I want to
4. Launch from Daydream Home:
App starts in VR mode which a very bad user expirience

Specs:
Unity 2018.1.f21

**Comment by rusmaxham** [comment]
If you still need help with this issue, please reopen and comment.
