### ISSUE TITLE
Linker Error (Audio)

### ISSUE THREAD

**Issue by dgoodine** [googlevr/gvr-unity-sdk#925]
Summary:

I get three undefined symbols: _SetSourceListenerDirectivity, _CreateSoundField and _CreateSoundOb jet.

I've reproduced this problem building the HelloVR scene.

Found using:
 * Google VR SDK version: 1.130.1
 * Unity version: 2018.1.3f1
 * Phone manufacturer, model, and O/S version: iPhone
 * Viewer manufacturer & model: Cardboard

**Comment by rusmaxham** [comment]
Can you send me a project that reproduces this issue?

**Comment by dgoodine** [comment]
I can't send the project, but I determined the problem is because of the old audio stuff in the Legacy folders.  After removing those classes.

find . -name '*GvrAudio*'

**Comment by rusmaxham** [comment]
I'm unable to reproduce this with 2018.1.4f1 and our SDK.  Are you able to reproduce this with a new empty project and just the GVR SDK?

**Comment by DylanFilingeri** [comment]
I was having the same exact issue. Deleting the audio folder in legacy seemed to do the trick.
