### ISSUE TITLE
Game stays monoscopic on Android phone

### ISSUE THREAD

**Issue by AgraVik** [googlevr/gvr-unity-sdk#926]
Summary: After trying to do the simple tutorial [here](https://developers.google.com/vr/develop/unity/get-started-android) the game on my phone stayed monoscopic, just like in the Unity editor, with no gyroscope tracking or ability to interact through touchscreen. This only happened to my Asus described below, but when I tried on a Samsung galaxy note 2 it worked just fine. It must have something to do with my phone model.

Found using:
 * Google VR SDK version: 1.130.1 and 1.120.0 (the only 2 I've tried)
 * Unity version: 2018.1.4f1 personal
 * Phone manufacturer, model, and O/S version: Asus Zenfone 2 ZE551ML, Android 6.0.1
 * Viewer manufacturer & model: a simple cardboard

Steps to reproduce the issue:
 [here](https://developers.google.com/vr/develop/unity/get-started-android)

Workarounds:
 none found

Additional comments:
 for some reason a daydream app was installed on my Asus, maybe from the Cardboard app which I uninstalled later but the problem persisted. In Unity I've only added Carboard in XR Settings at Virtual Reality SDKs

**Comment by rusmaxham** [comment]
The Asus Zenfone 2 ZE551ML is an x86 based device and unfortunately, the GoogleVR SDK for Unity only supports Arm-based devices.

**Comment by rusmaxham** [comment]
There is experimental support for x86 devices in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
