### ISSUE TITLE
GVR SDK  for unity version 1.130.1 is teleportation no longer supported or demoed in the SDK pakcage?

### ISSUE THREAD

**Issue by jjennings1990** [googlevr/gvr-unity-sdk#927]
Summary: I have downloaded GoogleVRForUnity_1.130.1 and notice that al verbal references to teleportation and what have you have been removed. Is Teleportation no longer a utilized feature ? 

Found using:
 * Google VR SDK version: 1.130.1
 * Unity version: 2013.3.1p4
 * Phone manufacturer, model, and O/S version: iOS in the  Unity editor 
 * Viewer manufacturer & model: 

Steps to reproduce the issue:
 1. Download 1.130.1
 2. Search for any references to Teleportation or the teleportation demo
 3. Notice there are none

Workarounds: Would love to know

Additional comments: Is it recommended that I write my own  custom  teleportation logic? It was fairly simple in the past to use a demo and get a quick demo of Google Cardboard functionality.

**Comment by rusmaxham** [comment]
Teleportation and other GoogleVR best practices have been moved to [Daydream Elements](https://developers.google.com/vr/elements/overview).
