### ISSUE TITLE
Documentation not up to date? "StereoPanoSphereMaterial"

### ISSUE THREAD

**Issue by Luzido** [googlevr/gvr-unity-sdk#929]
Summary:
The documentation speaks of  "StereoPanoSphereMaterial" located in 
GoogleVR/Demos/Materials/VideoDemo.
I can't find such a Material but only a "VideoStereoInside" located inside GoogleVR/Materials/Video .

Am I right to assume that these are the same materials? Can't find the other Material in older SDKs neither. 

Found using:
 * Google VR SDK version:1.130.1
 * Unity version: 2018.1.5
 * Phone manufacturer, model, and O/S version: Moto Z  Oreo
 * Viewer manufacturer & model:

**Comment by rusmaxham** [comment]
Yes, that is roughly the same material.  We will update our documentation accordingly.

**Comment by rusmaxham** [comment]
Google VR developer docs have been updated.
