### ISSUE TITLE
Problems with unity cardboard and bluetooth joystick

### ISSUE THREAD

**Issue by Katsshura** [googlevr/gvr-unity-sdk#931]
Hello, i'm having a problem with unity cardboard. When i run my app without  cardboard option everything runs fine, including the joystick. The problem is when i turn it on, joystick is no longer recognized by the application. Is there any fix for it?

**Comment by rusmaxham** [comment]
Not knowing anything about your setup it's hard to provide any assistance.  Additionally, since we don't directly support joystick integration in GVR, you would have to take this issue up with the joystick manufacturer.

**Comment by vinhui** [comment]
Maybe this is related to #831

**Comment by rusmaxham** [comment]
Could you try the workaround suggested in [this comment](https://github.com/googlevr/gvr-unity-sdk/issues/955#issuecomment-417419081)?
