### ISSUE TITLE
Mask moves around in front of camera on Unity splash screen load

### ISSUE THREAD

**Issue by luxcreativity** [googlevr/gvr-unity-sdk#934]
The Unity splash screen is an almost empty scene and the mask completely detaches itself and moves in front of the camera.

This wasn't happening before and now happens intermittently when testing on Pixel 2.

Could someone supply some build settings to check against? The Main game scene doesn't have this issue.

**Comment by rusmaxham** [comment]
Can you please supply the following information:

Found using:
 * Google VR SDK version:
 * Unity version:
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.

**Comment by luxcreativity** [comment]
Google VR SDK version: v1.130.1
Unity Version: 2017.4.1f1
Phone: Pixel 2, Daydream 1.16, Android 8.1.0

This issue happens prior to entering a Splash Screen level that loads the Main Game level using AsyncOperation, the Main Game level does not have this issue after scene activation.

**Comment by luxcreativity** [comment]
Additional

Building just the basic loading Splash Screen level (no Main Level) also demonstrates the same issue, frame rate takes a nose dive when there's next to nothing in the scene following the Unity Logo Splash Screen.

I can rule out AsyncOperation as the problem and any performance issues tied to loading the Main Scene.

Could you supply some reliable build settings for me to check against?

**Comment by rusmaxham** [comment]
My default settings:
![screen shot 2018-07-09 at 1 45 52 pm](https://user-images.githubusercontent.com/13911074/42475186-bcb13188-837e-11e8-8d29-3b1a970e45ba.png)
![screen shot 2018-07-09 at 1 46 42 pm](https://user-images.githubusercontent.com/13911074/42475187-be70beda-837e-11e8-9d22-a2c6c64b2c55.png)

**Comment by rusmaxham** [comment]
Are you able to create a project from scratch with the minimum amount needed to reproduce this issue?  If so could you zip that up and send it to me?

**Comment by rusmaxham** [comment]
Please reopen if you are able to get me a minimal repro project.
