### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.    at GvrTrackedController.OnEnable

### ISSUE THREAD

**Issue by VRRollerCoaster** [googlevr/gvr-unity-sdk#935]
Summary: Am getting the exception  when running in Xcode: "NullReferenceException: Object reference not set to an instance of an object.    at GvrTrackedController.OnEnable" on iOS when building.

Found using:
 * Google VR SDK version: 1.5
 * Unity version: 2018.2.0b1
 * Phone manufacturer, model, and O/S version: iPhone X
 * Viewer manufacturer & model: Google Daydream

**Comment by VRRollerCoaster** [comment]
After changing the camera setup to the new one I fixed it.

**Comment by timendez** [comment]
@VRRollerCoaster What things did you need to change for the camera setup to get rid of the error? I am encountering the same issue
