### ISSUE TITLE
Screen automatically rotates when app remain idle

### ISSUE THREAD

**Issue by SinghMohitPratap** [googlevr/gvr-unity-sdk#936]
Summary:

Found using:
 * Google VR SDK version:  v1.150.0
 * Unity version:   2017.3.0f3
 * Phone manufacturer, model, and O/S version:  all types of smartphones (test on mi note 5 pro)
 * Viewer manufacturer & model: 

Steps to reproduce the issue:
 1.  first create the UI button in your scene.
 1.  put your gvr reticle pointer over the UI button.
 1.  leave the gaze there and observe after five minutes the gaze automatically moves in right direction .It looks like the screen is moving

Workarounds:

Additional comments:

**Comment by vinhui** [comment]
This might have something to do with gyros not being perfect on mobile devices thus the view drifting over time.

**Comment by rusmaxham** [comment]
Yes, this is in fact due to the fact that gyros in mobile devices aren't perfect and have some inherent drift.  On Daydream, you can press and hold the system button (bottom most) and it will reset the rotational orientation back to center.

**Comment by emoilenne** [comment]
I believe this is the issue with Daydream controllers. I just spotted the same bug: in Unity playing in Scene mode and leaving controller rotated to the right - moves reticle to the right, to the left - moves to the left, up - moves down and down - moves up. It's not noticeable when there is even the little movement, but when you leave controller on the table for example, the drift is apparent.
