### ISSUE TITLE
Unity IAP breaks VR -- displays 2D purchase dialog

### ISSUE THREAD

**Issue by rtgray** [googlevr/gvr-unity-sdk#940]
Summary:
When using Unity IAP with GVR user is shown a 2D purchase dialog while still in VR rather than maintaining a fully VR friendly experience.

Found using:
 * Google VR SDK version: v1.70.0
 * Unity version: 2017.1.0p3
 * Phone manufacturer, model, and O/S version: Pixel & Pixel 2
 * Viewer manufacturer & model: Mobile Daydream headset

Steps to reproduce the issue:
 1. Set up Unity IAP
 2. Engage with IAP in VR experience, 2D dialogue pops up instead of 3D

Workarounds:

Additional comments:

**Comment by vinhui** [comment]
I have not has this experience when i tried it half a year ago, for me it worked like you would expect

**Comment by rusmaxham** [comment]
I've contacted Unity to see if someone knowledgeable with Unity IAP can offer some assistance.  In the meantime, have you posted to the [Unity user forums](https://forum.unity.com/forums/ar-vr-xr-discussion.80/) or [reported a bug to Unity](https://unity3d.com/unity/qa/bug-reporting)?

**Comment by joejo-unity** [comment]
This is a known issue that the Unity IAP team is looking into. I don't have any ETA or status update on this though.

**Comment by fredsa** [comment]
Fix is available in the Unity Asset Store: `Unity IAP 1.20.1`
