### ISSUE TITLE
Oculus GO

### ISSUE THREAD

**Issue by vinhui** [googlevr/gvr-unity-sdk#941]
When having an Oculus GO attached to my pc and running an application with the gvr sdk, it installs the Instant Preview application on the go and runs it. I have no problem with that, but after that its impossible to close the application other than to reboot the device.

**Comment by rusmaxham** [comment]
Does Instant Preview work properly on Oculus GO?  You can also disable Instant Preview by either disabling or removing the *GvrInstnatPreviewMain* game object from your scene.

**Comment by vinhui** [comment]
It doesn't work and I honestly don't expect it to work (although would be a nice alternative for people without a daydream device). My main issue is that if I accidentally do have the instant preview enabled that I need to reboot the device if I want to use it again.

**Comment by rusmaxham** [comment]
As a temporary workaround, you can add this snippet of code to **InstantPreview.cs** at [line 178](https://github.com/googlevr/gvr-unity-sdk/blob/396e8841fe88dcf031850629eb136a77a4ae792c/Assets/GoogleVR/Scripts/InstantPreview/InstantPreview.cs#L178) of version 1.150 of the SDK:

```C#
            // Gets the vr feature capability of the device.
            RunCommand(InstantPreviewHelper.AdbPath,
                       "shell pm list features | grep feature:oculus.hardware.standalone_vr",
                       out output, out errors);
            // If matches the features grep, then not compatible.
            if (!string.IsNullOrEmpty(output)) {
              Debug.Log("Instant Preview: device is not compatible.");
              return;
            }
```

This will prevent IP from installing on Oculus GO.

**Comment by vinhui** [comment]
Thanks, will try!

**Comment by fredsa** [comment]
We'll look into including a permanent fix in the SDK that makes the Installation of Instant Preview conditional on the device having (Daydream) Google VR support.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
