### ISSUE TITLE
InstantPreview handedness

### ISSUE THREAD

**Issue by vinhui** [googlevr/gvr-unity-sdk#943]
It seems that instant preview is ignoring the handedness of the daydream device and always using the right hand.

Found using gvr v1.150.0 and unity 2017.2.0p1

**Comment by rusmaxham** [comment]
Good find.  We'll take a look.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
