### ISSUE TITLE
Issue with Controller Emulator in Editor

### ISSUE THREAD

**Issue by vlad3489** [googlevr/gvr-unity-sdk#946]
Summary:
I have an issue with Controller Emulator view in Unity Editor, it doesn't work correctly with GVR SDK for Unity v1.150.0.
When i press the touch pad it seems like "bad connection"
GvrControllerVisual->DisplayState->Touching
Field starts to change values very fast (true/false) and visually controller view hover state blinking. You can see it on the video, link attached:
https://drive.google.com/file/d/14wvVyV5FUcRl2gJTr9UkjbdABs-XE6mG/view?usp=sharing

Also when you start moving finger across touch pad it updates more stable. 

When i rollback to GVR SDK for Unity v1.130.1 everything works perfect in Unity Editor. Also in builds everything works like charm with GVR 1.130.1 and GVR 1.150.0

Found using:
 * Google VR SDK version: 1.150.0
 * Controller Emulator:  1.5.01
 * Unity version:  2018.2.0.f2
 * Phone manufacturer, model, and O/S version: Samsung Galaxy S8 (Android 8.0.0)

Steps to reproduce the issue:
 1. Create project
 2. Import GVR SDK for Unity v1.150.0.
 3. To see the effect more clearly you can take example of teleport from Daydream Elements
 4. Start unity editor and controller emulator
 5. Put finger on touch pad

**Comment by fredsa** [comment]
@vlad3489 Could you try using Instant Preview? This should offer the best development experience when it comes to using Daydream View and Daydream controller in Play mode in the Unity editor.

https://developers.google.com/vr/develop/unity/instant-preview

**Comment by fredsa** [comment]
Closing as Controller Emulator is now deprecated.
https://developers.google.com/vr/daydream/controller-emulator
