### ISSUE TITLE
NaN problem with Editor emulator

### ISSUE THREAD

**Issue by CenekStrichel** [googlevr/gvr-unity-sdk#947]
Summary:
From Unity 2018.2+ you can not use emulator GVRController with TimeScale = 0
It happen only in editor. Build looks ok.

Steps to reproduce the issue:
 1. Open HelloVR scene in Unity 2018.2+
 2. Unhide GvrControllerMain
 3. Set Time Scale to 0
4. Play
5. Hold ALT + SHIFT + mouse move
6. You get this
![image](https://user-images.githubusercontent.com/8094238/43742069-db7069f0-99d0-11e8-811d-b2c1928dd6f2.png)

**Comment by ddrocco** [comment]
In MouseControllerProvider.cs, there's a method called `private void UpdateOrientation()`.  In it is the line `state.gyro = deltaDegrees * (Mathf.Deg2Rad / Time.deltaTime);`.  Replace this line with the following:

`if (Time.deltaTime > 0f) {
    state.gyro = deltaDegrees * (Mathf.Deg2Rad / Time.deltaTime);
  } else {
    state.gyro = Vector3.zero;
  }`

That should do the trick.  I'll try to get an official fix out for this shortly.

**Comment by rusmaxham** [comment]
Fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
