### ISSUE TITLE
GvrController click anywhere event ?

### ISSUE THREAD

**Issue by thatsmesasha** [googlevr/gvr-unity-sdk#951]
Hello !
I'm new to Unity and Google VR. I'm trying to find an event trigger when you click on the controller. I figured that Pointer Click event is not exactly what I'm looking for, since it also wants an object with which pointer ray intersects. I want an event that will trigger every time you press touchpad.
To give a bit of context, I want to create a ray that may or may not intersect objects, more descriptively, a magic spell being casted.

**Comment by vinhui** [comment]
You can use 
``` csharp
GvrControllerInput.GetDevice(GvrControllerHand.Dominant).GetButtonDown(GvrControllerButton.TouchPadButton);
``` 
to get the touchpad click state. There is also a `GetButtonUp` and `GetButton`. You can use `GvrControllerButton.TouchPadTouch` to get just the touch. These functions work just like the unity `Input.GetKey*` functions.

**Comment by emoilenne** [comment]
@vinhui  I tried using this, but then I don't know how to get PointerEventData for creating a raycast.
Here `PerformRaycast`, you need PointerEventData, Physics wants EventData too as I remember.
But event triggers functions receive EventData as a parameter (like 'Pointer Click').

**Comment by vinhui** [comment]
Can't you just do a normal raycast from the controller?

**Comment by emoilenne** [comment]
Yep, just checked Physics.Raycast, and it doesn't need EventData. Don't know why I thought it needs.
Thanks !

**Comment by vinhui** [comment]
Those methods are for the ui system.

**Comment by rusmaxham** [comment]
Does `GvrPointerInputModule.CurrentRaycastResult` return what you want?

**Comment by rusmaxham** [comment]
If you still need assistance with this, please reopen and comment.  Closing for now.
