### ISSUE TITLE
PointerEnter event adds varying rotation to ControllerVisual, normal after PointerExit

### ISSUE THREAD

**Issue by emoilenne** [googlevr/gvr-unity-sdk#952]
Summary:
When controller is pointing on some object, the ControllerVisual GameObject changes its rotation by some vector (something around (-7, -3, -0.5), but it always changes) to it, but when you exit the object, it gets back to normal. I'm not sure but maybe this problem is affecting it: https://github.com/googlevr/gvr-unity-sdk/issues/936#issuecomment-415583958

Found using:
 * Google VR SDK version: 1.150.0
 * Unity version: 2018.2.3f1 Personal
 * Phone manufacturer, model, and O/S version: Lenovo Solo VR-1541F
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1. Open demo scene HelloVr.
 2. Press play.
 3. Switch to Scene view.
 4. Point on the Treasure and watch how changes the rotation of the controller in Player/GvrControllerPointer0/ControllerVisual (it's also visual on the scene view).

Workarounds:

Additional comments:
2 provided screenshots were made on the edge of the "treasure", barely any movement, certainly less than difference in rotation vectors. You can see how controller is tilted when the reticle is on the object.

Selected:
<img width="2560" alt="selected" src="https://user-images.githubusercontent.com/22552600/44555783-b50f3c00-a6eb-11e8-84f4-0b123d946b50.png">

Not selected:
<img width="2560" alt="not-selected" src="https://user-images.githubusercontent.com/22552600/44555801-cce6c000-a6eb-11e8-851c-163142c9f6e6.png">

**Comment by rusmaxham** [comment]
This is the result of the Hybrid Raycast Mode configured on the Laser object of the ControllerPointer.  Direct mode won't change the angle of the controller, while Hybrid and Camera will adjust the controller orientation depending on depth of the raycast hit.  See docs on [GvrBasePointer.raycastmode](https://developers.google.com/vr/reference/unity/class/GvrBasePointer#raycastmode).
