### ISSUE TITLE
Update Protocol Buffer

### ISSUE THREAD

**Issue by christougher** [googlevr/gvr-unity-sdk#956]
Summary:  Building project that uses gvr, but will use ArCore and ArKit if the device supports them.  Works fine on Android builds but I get the following error when I build to an IOS device:

[libprotobuf FATAL third_party/protobuf/src/google/protobuf/stubs/common.cc:68] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 3.4.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "third_party/protobuf/src/google/protobuf/timestamp.pb.cc".)
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException

I'm not sure what depends on a higher version of protobuf, perhaps ARCore?  Either way how can I, or the SDK be updated?  

Found using:
 * Google VR SDK version:  1.150 and just tried again with 1.170
 * Unity version: 2018.2.5f1
 * Phone manufacturer, model, and O/S version: Iphone 6s, IOS 11
 * Viewer manufacturer & model: N/A

Steps to reproduce the issue:
 1.  Unity Project with latests SDKs of ARCore, ArKit and GVR, set to Virtual Reality Support with Cardboard, ARCORE supported with IOS Support enabled (I'm using the ArCore components and not the ArKit).
 1.  Build targeting IOS and run in XCode on target device
 1. project build fine and when app first loads up the above error appears.

Workarounds:

Additional comments:

**Comment by rusmaxham** [comment]
We are looking into a solution for this.

**Comment by christougher** [comment]
any update to getting an updated Google.protocolbuffers dll integrated or other fix? Thx!

**Comment by christougher** [comment]
Sooooo, I've tried to recreate this bug on another mac and can't seem to recreate it.  Everything builds fine.

**Comment by rusmaxham** [comment]
Happy to hear it is working for you now.  If you encounter this again, please reopen.
