### ISSUE TITLE
Crash on iOS when 'Back' Arrow is pressed during Splash Screen

### ISSUE THREAD

**Issue by kohijin** [googlevr/gvr-unity-sdk#960]
Summary:

GVR's overlay 'back' arrow causes the app to crash when tapped during the Splash Screen. It works as expected past the Splash Screen.

Found using:
 * Google VR SDK version: v1.170.0
 * Unity version: 2017.4.10f LTS
 * Phone manufacturer, model, and O/S version: Apple, iPhone X, iPad mini, iPhone 7, iPhone OS 11.4.1

Steps to reproduce the issue:
 1. Build & run XCode project on iOS device
 2. Tap "Back" Arrow during splash screen

Workarounds:

We're looking into removal of the 'back' button. Our app is strictly VR and does not need the button to begin with. From our understanding this is currently only possible by modifiying non-C# iOS code that is provided with the SDK?

Thanks in advance for your thoughts!

**Comment by fredsa** [comment]
Do you have a project that reproduces this issue?

Also, it would be helpful if you include a Unity case number, in case we need to follow up with Unity.

**Comment by chaosemer** [comment]
Please reopen if you still have this issue and attach a repro project.
