### ISSUE TITLE
ArmModel doesn't stick to the neck during movement and rotation of the head

### ISSUE THREAD

**Issue by thatsmesasha** [googlevr/gvr-unity-sdk#965]
Summary:
Hi, I'm trying to do 360 game experience on Daydream. I'm using GvrArmModel and as I understand, it is supposed to "stick" the shoulder to the camera at specific position. What I am experiencing is that once the game starts, the arm model is at the initial position (relative to the camera), but when I try to move around or turn the camera, the arm stays at the same position and doesn't rotate either. What I want is that arm moves with the camera and also rotates if I rotate the head (so I can point my controller normally when I rotate my head). Maybe it's not a supposed behavior and you know how to do it?
I searched for a work around, updating shoulder position and rotation manually, but I don't think it's possible. I was looking into ShoulderPosition and ShoulderRotation in GvrArmModel and they are read-only.

Found using:
 * Google VR SDK version: 202.0.0
 * Unity version: 2018.2.3f1

**Comment by rusmaxham** [comment]
The controller pointer will follow the head if it is pointed in the same direction of the head.  If the pointer and head drift out of alignment with each other, the user can press and hold the System button (bottom most one) to realign the two.

**Comment by thatsmesasha** [comment]
Yeah, but in 360 game you shouldn't be readjusting controller every 2 seconds. I believe there is a solution to this problem. In the game Wands on the Google Play market you can rotate yourself 360 degrees and controller arm moves with you. Although you cannot see the arm model directly, by rotating your head and trying to move controller you can notice that the arm model is being rotated too.

**Comment by rusmaxham** [comment]
Oh, are you rotating the player (camera parent) programmatically? If so, you'll need to rotate the parent of the controller pointers as well.  The HelloVR demo scene is setup with a **Player** object that is the parent to both the **Main Camera** and the **GvrControllerPointer**.  Transforms applied to the **Player** object affect both the **Main Camera** and the **GvrControllerPointer**, keeping them in sync.

**Comment by rusmaxham** [comment]
Does this address your issue?

**Comment by fredsa** [comment]
Please feel free to reopen if rotating a parent to the camera game object does not resolve the problem for you.
