### ISSUE TITLE
Permissions request flow does not work with multiple permissions

### ISSUE THREAD

**Issue by hshapley** [googlevr/gvr-unity-sdk#967]
Summary:
The permissions request flow is supposed to be designed for requesting multiple permissions at once. However, the system treats "all permissions granted" differently than "some permissions granted". If all permissions are granted, everything works fine, but there are cases where the developer designs the app to work properly regardless of what permissions are granted. This is the whole point of runtime permissions requests - the app checks at runtime if a permission is granted, and reacts accordingly. Currently, the permissions flow is behaving incorrectly when the user doesn't grant all the permissions.

In my app, the user can choose to open files, requiring the EXTERNAL_STORAGE permission, or use the microphone, requiring the RECORD_AUDIO permission. But they can choose which of those they want to approve and which not to approve, and the app should still work. If not all permissions are granted, the RequestPermissionResult callback is not called at all. You can see that these cases are treated differently in GvrPermissionsRequester.cs at line 147 (onRequestPermissionResult).

Found using:
 * Google VR SDK version: 1.130.1, but with the fix for issue #822 
 * Unity version: 2018.2
 * Phone manufacturer, model, and O/S version: Pixel 2 XL
 * Viewer manufacturer & model: Daydream View

Steps to reproduce the issue:
 1. Edit PermissionsFlowManager.cs to request two permissions - add "android.permission.RECORD_AUDIO" to permissionNames
 2. Build and run on device. Run the permissions demo
 3. When prompted, grant one of the permissions but not the other
Result:
The RequestPermissions callback is not called (text doesn't change to cyan or say permission results)
Note: I have not tried these steps exactly, but they reflect the changes I've made to PermissionsFlowManager.cs.

**Comment by rusmaxham** [comment]
How did you apply the fix for #822 to your 1.130.1 SDK?

**Comment by rusmaxham** [comment]
This scenario of mixing and matching parts from different releases is not supported.  If you can, please update to v1.150 or later to get the permissions flow fix.  We have verified that multiple permissions requests work with the latest SDK.

**Comment by hshapley** [comment]
I fixed 822 by using the updated manifest for gvr-permissionsupport-release.aar. I don't want to go through my code to support multiple controllers yet.

I decided to request permissions on startup instead of during runtime. This goes against your own recommendations but is a better user experience. You really need to add in-VR runtime permissions requests where the user doesn't have to take off their headset.

**Comment by rusmaxham** [comment]
GVR SDK for Unity v1.150 has the permissions request fix but does not have the multiple controller changes.  We do support in-VR permissions requests on the Lenovo Mirage Solo.  Unfortunately, we don't yet have a timeline for bringing that functionality to smartphone VR.

**Comment by hshapley** [comment]
Thanks for the info.

**Comment by hshapley** [comment]
I tracked down the failing line, which is in GvrPermissionsRequester.cs at line 83:
`return AndroidJNIHelper.ConvertFromJNIArray<bool[]>(resultArr.GetRawObject());`

This line throws the following exception during runtime:

```
E/Unity: InvalidCastException: Specified cast is not valid.
        at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
      at UnityEngine._AndroidJNIHelper.ConvertFromJNIArray[ArrayType] (System.IntPtr array) [0x00054] in <>:0 
      at UnityEngine.AndroidJNIHelper.ConvertFromJNIArray[ArrayType] (System.IntPtr array) [0x00001] in <>:0 
      at GvrPermissionsRequester.HasPermissionsGranted (System.String[] permissions) [0x00048] in <>:0 
      at GvrPermissionsRequester+PermissionsCallback.onRequestPermissionResult (System.Boolean allPermissionsGranted) [0x00056] in <>:0 
        at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
```

Any way to fix this? It seems to give the same result whether I pass an array of size 1 or 2.
