### ISSUE TITLE
There is no way to change the scale of the movements of the GvrHeadset in the virtual world

### ISSUE THREAD

**Issue by EstebanGameDevelopment** [googlevr/gvr-unity-sdk#968]
Summary:
I recently finished a project that uses ARCore to provide 6DOF ([link to Google Play](https://play.google.com/store/apps/details?id=com.yourvrexperience.subwaytohell&hl=en)), since a couple of months ago I purchased a Lenovo Mirage Solo I decided to use Daydream positional tracking to do the same that I'm doing with ARCore. To my surprise it seems that there is not way to scale the movements of the real world to the scale I want in the virtual world like I'm doing with ARCore. The only alternative I see right now it's awful and that is to scale the whole world, the whole logic, everything to the fixed scale of movements of the positional tracking offered by Daydream. Unless there is a way you people know about to change scale the movements in the virtual world, I think that my best option would be to give up all together in the Daydream version. I don't think it's worth it all the work it suppose to make it work, let alone that maybe other hardware could change its scale value making all the work done completely useless.

Found using:
 * Google VR SDK version:  1.170.0
 * Unity version: 2018.1.6f1
 * Phone manufacturer, model, and O/S version: Lenovo Mirage Solo
 * Viewer manufacturer & model: Lenovo Mirage Solo

Steps to reproduce the issue:
 1. Run any app that uses GvrHeadset for positional tracking
 2. Notice that you don't have any way to change the scale of the movements in the virtual world

Workarounds:
Scale all the world to fit to the fixed scale provided by Daydream.

**Comment by vinhui** [comment]
You could put the camera in a parent gameobject and move the parent a percentage of the movement of the camera

**Comment by EstebanGameDevelopment** [comment]
> You could put the camera in a parent gameobject and move the parent a percentage of the movement of the camera

I already tried that, the result was that the movement accumulated losing the control of the whole thing. With the current system of GvrHeadset you don't have any kind of control of the camera. Usually I don't ask for help after running out of options. The logical thing it would have been to enable parameters to scale the movements of the camera in the virtual world. If that's not possible it would be good to know so anybody else loses time with positional tracking.

**Comment by vinhui** [comment]
It shouldn't accumulate if you're using the local position of the camera

**Comment by EstebanGameDevelopment** [comment]
> It shouldn't accumulate if you're using the local position of the camera

Thanks for the help. It worked.

For any future developer who will face this same issue, [this is the way it works for me](https://www.dropbox.com/s/5rcs7b8651r9qbz/ScalingTheMovementsOfVirtualWorldFromWorldsense.jpg?dl=0).
