### ISSUE TITLE
[Controller Emulator] ADB Android Debug Bridge ('adb') command not found Gvr Daydream Unity3D  

### ISSUE THREAD

**Issue by fhcampbell** [googlevr/gvr-unity-sdk#969]
Summary:
Android Debug Bridge (`adb`) command not found.

There needs a fix for the Android Debug Bridge automatically.
Google VR works on the desktop and there are only updates to AndroidSDK, but none on the Unity side for this issue.

This is extremely time consuming and unproductive trying to find a way to go-around the problem.
Does anyone have any suggestions?

Unity would never be able to coordinate any android parameters unless it already had the SDK, NDK and JVK backend and these are all located exactly as during all previous Gvr demos.
The only difference is that Android and Google is updated.
However Unity is not recognising anymore what is already there.

The console says:

Verify that the Android SDK is installed and that the directory containing `adb` is included in your PATH environment variable.
  at Gvr.Internal.EmulatorClientSocket.setupPortForwarding (Int32 port) [0x000f0] in D:\Unity3D\GvrStudy\AndroidPluginStudy\Assets\GoogleVR\Scripts\Controller\Internal\Emulator\EmulatorClientSocket.cs:153 
  at Gvr.Internal.EmulatorClientSocket.phoneConnect () [0x00039] in D:\Unity3D\GvrStudy\AndroidPluginStudy\Assets\GoogleVR\Scripts\Controller\Internal\Emulator\EmulatorClientSocket.cs:97 
  at Gvr.Internal.EmulatorClientSocket.phoneEventSocketLoop () [0x00017] in D:\Unity3D\GvrStudy\AndroidPluginStudy\Assets\GoogleVR\Scripts\Controller\Internal\Emulator\EmulatorClientSocket.cs:73 
UnityEngine.Debug:LogWarningFormat(String, Object[])
Gvr.Internal.EmulatorClientSocket:phoneEventSocketLoop() (at Assets/GoogleVR/Scripts/Controller/Internal/Emulator/EmulatorClientSocket.cs:76)

Found using:
 * Google VR SDK version: gvr-android-sdk-1.170
 * Unity version: 2018.2.10f1
 * Phone manufacturer, model, and O/S version: Samsung G960F and ASUS ZenFone AR 4
 * Viewer manufacturer & model: Daydream , Google VR Developer options,

Steps to reproduce the issue:
 1. Run HelloVr or any Gvr game
 1. Build with Android in XR settings (Android 8.0, Daydream)
 

Workarounds:
I tried accessing via the cmd line. and via wirelessly
I tried to also do basic restarts, and re-installs of Unity and of Gvr.
I found where the adb is called in the preview script but it does not occur to me how or what to modify there to make it update. I mean, the code works .  Android works, See the screenshots.

Additional comments:

![unityproblemwith androidgradle](https://user-images.githubusercontent.com/4656464/46610636-91714b00-cb0b-11e8-9797-b2f2dd8a56f8.PNG)
![pathvariable management](https://user-images.githubusercontent.com/4656464/46610646-96ce9580-cb0b-11e8-9520-c59245bbcac8.PNG)
![usbdriver](https://user-images.githubusercontent.com/4656464/46610650-99c98600-cb0b-11e8-922d-719b562ba534.PNG)
![google instantpreview](https://user-images.githubusercontent.com/4656464/46610950-8965db00-cb0c-11e8-8124-5aa5f590633b.PNG)

**Comment by vinhui** [comment]
You need to make sure to have the sdk `platform-tools` in your `PATH`.
https://www.xda-developers.com/adb-fastboot-any-directory-windows-linux/

**Comment by rusmaxham** [comment]
As vinhui says the workaround to this issue is to add `platform-tools` to your `PATH`.  We are working on a fix so that EmulatorClientSocket uses the Android SDK path already configured in Unity's preferences.

**Comment by rusmaxham** [comment]
Another workaround is to disable the **Controller Emulator** by selecting the **GvrControllerMain** game object, then in the Inspector, under **Gvr Controller Input** component, set **Emulator Connection** to **OFF**.

**Comment by fhcampbell** [comment]
Thank you both VERY much each of you for your reply and for your suggestions.
Unfortunately, seems to bypass the configuration for adb set directly by the PC.
I re-verified that adb works from the command and I see the path , as shown.
I rebooted too.

So, then I definitely went to also try emulator OFF, as you suggested.

I am not getting any changes.
When you say that I need to have the sdk platform-tools in my path, where do I do that exactly?
My Editor>External Tools>..already shows the jdk, ndk for it. 

So maybe I am mistkane:  Are you possibly meaning there are other platform-tools to set? and if so, are those in the unity build settings? 
![sad sad sad](https://user-images.githubusercontent.com/4656464/46919568-49f22f80-cfe1-11e8-8b44-16db65fdff4c.PNG)


![persistent error with emulatoroff](https://user-images.githubusercontent.com/4656464/46919427-7907a180-cfdf-11e8-91ac-ab580b164dd5.PNG)
![gvrvideoplayer alreadyinstalled](https://user-images.githubusercontent.com/4656464/46919428-79a03800-cfdf-11e8-8715-b97cd7587782.PNG)
![path](https://user-images.githubusercontent.com/4656464/46919429-79a03800-cfdf-11e8-84f3-e119f28431e4.PNG)


> sdk `platform-tools` in your `PATH`

If I could, I would ask Google to convert the controller to an android peripheral designed like a collapsible husk inside more husks. then i could pull out the design control I want to use and push it back in, to whatever scale of operatoin I needed to build.  If so, then I could customize without the controller being forced to fit into  the unity editor and excluding all the other functionality that android studio has to offer in the final game rendering.

**Comment by vinhui** [comment]
In the last image in your last reply there are 2 boxes, the top one is for the `user variables` and the bottom one for the `system variables`. Try finding the `PATH` variable in the second box (and if it doesn't exist, create it) and add the path to the platform tools there.

**Comment by fhcampbell** [comment]
What should the path to the platform tools look like?

I found the PATH variable exists in the second box, shown in the snapshot here:
![path](https://user-images.githubusercontent.com/4656464/46951785-40240700-d089-11e8-94d6-657786c26a42.PNG)

As you probably know, there are two files in there- each separated by the semi-colon.

If I understand you correctly, you suggest I add the same path to the platform tools into the same second box. 

That means:  copy that path  and  then go back to Unity and paste it into the platform tools (External tools?) by going  Unity>Edit>Preferences>ExternalTools>SDK

Is that what you mean?

If so, it shows  a download requirement.
This means: to copy the Android SDK into whatever that PATH file directory was.

Is that what you mean?
![sdk](https://user-images.githubusercontent.com/4656464/46952141-52527500-d08a-11e8-8479-fd7420ad74fa.PNG)

I'll definitely wait to hear if this is correct before doing it - just in case it would trigger any conflict
And in the meantime I will start copying the long path because CTRL-C in the Environmental Variables windows does not seem to work.

But, I would be so happy if this was the solution and it worked !

**Comment by fhcampbell** [comment]
The other option was to do the following:
1. Add new to the path as SDK platform-tools 
![added here](https://user-images.githubusercontent.com/4656464/46953147-49af6e00-d08d-11e8-8ac7-93915fe01484.PNG)

2. And add it to the User Variables for User too.



![emulator sys](https://user-images.githubusercontent.com/4656464/46953172-5c29a780-d08d-11e8-9120-a99dbcae884c.PNG)

**Comment by fhcampbell** [comment]
The second option that I just described definitely does not work.

Turning the Emulator to OFF from USB or WiFI does not impact the result.

The effect of this problem is huge: No game can be built or run on Google.

I have tried using and setting up the Interactive360 feature, and it includes the GvrSDK instantly.

Well, I have setup another post about the fact that when you launch it, it declares multiple duplicate plugins.  The solution includes deleting Unity's automatica TempPro package instllation .

But, when this is done, Unity auto-searches for OpenVR.
When it does not find OpenVR, it uses Oculus.

It does NOT work with GoogleVR unless it forces in OpenVR and if OpenVR is not wanted, it uses Oculus literally as a constant operation.
 


I need to use Google Daydream and I do not want Oculus.

This is really frustrating.

**Comment by fredsa** [comment]
We will turn off the [deprecated](https://developers.google.com/vr/daydream/controller-emulator) Controller Emulator in the `GvrControllerMain` prefab by default in an upcoming release.

[Instant Preview](https://developers.google.com/vr/develop/unity/instant-preview) should be used instead.

**Comment by fredsa** [comment]
Marking as "fixed in upcoming release" as the controller emulator warnings should no longer appear by default.

**Comment by rusmaxham** [comment]
Turning the Emulator to OFF should address the issue with the errors from EmulatorClientSocket, as it doesn't get instantiated when the Emulator is OFF.  What error are you getting after turning the Emulator OFF?

**Comment by fhcampbell** [comment]
It says the same message of Controller Disconnected.  In the unity top , it also says Remote Not Connected.
It is at times freaking me out-
I am bypassing the steps for now by exporting as an internal (Build > Check Export, Reject Gradle)
My God- I need ot meet with a network-client.  Im building on every workaround because of quality priorities in rendering.
 
If anyone works with google here, would it be at all possible to approach a direction as if you are eventually allowing development  with Android Studio Direct instead of Windows Visual Studio, and  monodevelop.  It would help so much TRULY.  I need that efficiency .   If you are already, thank you with my head bowed,...literally.

**Comment by fredsa** [comment]
@fhcampbell If you prefer Android Studio for your next project, you can use the [Google VR SDK for Android](https://developers.google.com/vr/develop/android/get-started).

**Comment by rusmaxham** [comment]
I'm sorry to hear of all of your frustrations developing for Daydream with Unity.   We're unable to provide support on the development tools themselves (Unity, Visual Studio, Android Studio).  This issue forum is just for the GVR SDK for Unity, not Unity or other tools.  Please do either file a bug with Unity (under the Help menu in Unity Editor) or post to the [Unity Forums](https://forum.unity.com/).

If the original issue of "ADB Android Debug Bridge ('adb') command not found" has been sufficiently worked around, then we will be closing this issue when the Emulator default change becomes public.  If you have other issues with the GVR SDK for Unity, please file a new issue with repro steps.

**Comment by fhcampbell** [comment]
The replies I just received suggest these are bots.
If this is not true, then the issue is more advanced than those who have
replied.

Op di 16 okt. 2018 om 18:51 schreef Fred Sauer <notifications@github.com>:

**Comment by fredsa** [comment]
@fhcampbell The `Verify that the Android SDK is installed and that the directory containing adb is included in your PATH environment variable.` error message is the result of `adb.exe` not being available on your system path.

To turn off the controller emulator functionality, look for the **GvrControllerMain** prefab in your scene. On its `GvrControllerInput` component, set **Emulator Connection Mode** to **OFF**. (We will be setting this to OFF in an upcoming release of the SDK).

![emulator-connection-mode-off](https://user-images.githubusercontent.com/1235362/47175965-502a2980-d2c9-11e8-8773-d94d425de16f.png)

If you'd rather fix the PATH issue:
1. Determine where you have installed the Android SDK. (Based on your screenshots, it looks like this might be `c:\NVPACK\android-sdk-windows`.)
2. Verify that this contains an `platform-tools` directory with `adb.exe` in it. (For you this means `c:\NVPACK\android-sdk-windows\platform-tools\adb.exe`.)
3. Modify your User (or System) environment so that the `platform-tools` directory is on your path. (In your case, add `c:\NVPACK\android-sdk-windows\platform-tools`.)
4. Confirm that step 3 worked: Open a `CMD` window (you use `WINDOWS`-`R` key combination, then type `CMD` and hit `ENTER`), and type `adb`. If `adb.exe` is not found, verify steps 1-3.
5. Restart Unity, to make sure `PATH` changes take effect.

**Comment by fredsa** [comment]
Note that, unlike the deprecated controller emulator, Instant Preview doesn't currently use the system `PATH` environment variable.

Instant Preview uses whatever path you have setup under Unity's **Preferences > External Tools > Android SDK**, appends `platform-tools` to that, and then looks for `adb` (or `adb.exe` on Windows) in the resulting directory.

**Comment by fredsa** [comment]
Ik hoop dat deze uitleg wat helpt. Laat graag weten als het niet zo is.

**Comment by fhcampbell** [comment]
Hartelijk dank voor uw gedetailleerde, perfecte stappen en uitleg. 
My deep apologies for not letting you know that I followed them right away but , again, soemthing is amiss somewhere.  I wanted to explore further and try more solutions - everything I could think of - including if there were bugs in some other programfile.
The steps you gave were awesome and I followed them. It was a great check-through.

Unfortunately, I will have to continue using the two-step internal build-then-transfer to the phone. I've had to build all my games like that for now.
But, I plan to schedule a 2-day take-down of everything, including jdk/ndk and a new Android Studio - everything in a new partition- plus Unity at the time the new Gvr controller-feature or process is released.  

Thank you again!
Really grateful for everyone's reply, always.

**Comment by fredsa** [comment]
Sounds good. Will close this issue for now, but feel free to re-open or file a new issue if you're still having issues. When you're ready, please check the [releases pages](https://github.com/googlevr/gvr-unity-sdk/releases) and make sure you have the latest SDK. We expect that the deprecated emulator controller will be set to `OFF` in version `1.180.0` and later releases.
