### ISSUE TITLE
Double GvrReticlePointer in 2017.4.12f1 for Cardboard

### ISSUE THREAD

**Issue by luxcreativity** [googlevr/gvr-unity-sdk#970]
Double GvrReticlePointer in 2017.4.12f1 with GoogleVRForUnity_1.170.0

Hierarchy is:
Player(empty transform)
-Main Camera
--GvrReticlePointer

On Google Pixel 2 with Google Cardboard off-brand and branded, the issue appears to be that the reticle is instantiated for each eye camera.

**Comment by fredsa** [comment]
Can you try the **HelloVR** scene in the SDK and include a screenshot of the issue?

**Comment by luxcreativity** [comment]
Hi, re-importing the Package has seemed to temporarily resolve the problem, the issue appeared in Hello VR and an Empty scene.

**Comment by fredsa** [comment]
Glad you were able to get it working again by re-installing the Google VR SDK.
