### ISSUE TITLE
Is there "Google Sign In" UI ready to be used?

### ISSUE THREAD

**Issue by juscelinotanaka** [googlevr/gvr-unity-sdk#971]
Summary:
We are working on an App which will integrate Google Photos.
We saw that on YoutubeVR we can choose an account and it shows a UI really similar to the popup used on 2D apps. Is that available to be used like on YoutubeVR?
If not, do you plan to release that? Could we create our own UI without mimicking 2D UI (as it is done on YoutubeVR)?

Since accessing users photos is a restrict scope (from Google API), in a 2D app it opens an web view to request users to authorize the app to access their private data. Can we show that web view inside the VR environment or we need to request user to authenticate outside the App?

Sorry if the question is misplaced.

**Comment by juscelinotanaka** [comment]
Great @rusmaxham. Thank you so much. Do you think it may open a web view inside my App or it will go to ChromeVR then back to my app? Thanks.

**Comment by rusmaxham** [comment]
I'm not sure.  I haven't tried any of this yet.

**Comment by chaosemer** [comment]
This will work on the Lenovo Mirage Solo, but we do not have a timeline to share for bringing this to smartphone VR devices.
