### ISSUE TITLE
Ability to disable Phone Remote functionality

### ISSUE THREAD

**Issue by chrisyarbrough** [googlevr/gvr-unity-sdk#972]
I would like to disable the phone remote part of the in-editor emulation. Specifically, the two GameObjects "PhoneRemoteConfig" and "PhoneRemote" which are instantiated as DontDestroyOnLoad. However, the associated classes seem to be tightly coupled via multiple singleton references. Please decouple these or allow for a configuration option to completely remove the phone remote parts and only keep the GvrEditorEmulator and GvrControllerInput functionality active when running in the editor.

Reason being that we are developing for hardware without a touch interface (e.g. Daydream Mirage Solo) and would like to remove the overhead of unused functionality (failed connection attempts, logged warnings, general clutter in the hierarchy, etc.).

Thank you!

**Comment by rusmaxham** [comment]
Also, those game objects are only created in Editor.  All of the PhoneRemoteXXX objects and Controller Emulator functionality is fully disabled in builds for device.

**Comment by rusmaxham** [comment]
This is now fixed in [the latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
