### ISSUE TITLE
How to develop and deploy apps for Lenovo Mirage Solo using Google VR SDK?

### ISSUE THREAD

**Issue by avinash-sprw** [googlevr/gvr-unity-sdk#975]
I came across Lenovo Mirage Solo VR headset. I would like to know whether it supports development. If yes, how to develop and deploy apps in it? Will it be just same like enabling developer options on android phone, connecting it to the PC and deploying the app from Unity?

**Comment by vinhui** [comment]
Yes, it's almost the same as normal daydream development

**Comment by ddrocco** [comment]
Thanks, vinhui, that's correct.  Closing this issue for now; please reopen it if you have any issues with using the regular Android Phone development/deployment workflow on the Lenovo Mirage Solo!
