### ISSUE TITLE
Input doesn't work when VR is switched off

### ISSUE THREAD

**Issue by ghost** [googlevr/gvr-unity-sdk#979]
We are working with Unity and GoogleVR developing an hybrid app and we have problems changing between VR and non VR during the scene. We are using de code in the [documentation](https://developers.google.com/vr/develop/unity/guides/hybrid-apps), we have a bool which is checked in the update and calls the IEnumerator when needed. 
We have a button on the scene for changing between VR and non VR and when pressed (or gazed) it turns on/off VR making false the previous bool  and deactivating all the GVR prefabs we are using. That works nice, but the program (Unity Editor and built APK) doesn't get any input even mouse or screen touch.
¿What should we do to reactivate inputs?

Found using:
 * Google VR SDK version: 1.170.0
 * Unity version: 2018.2.14f1
 * Phone manufacturer, model, and O/S version: Xiaomi MI A2 Lite / Moto G4 Plus, Android 8.1.0 / Android 7.0
 * Viewer manufacturer & model: BlitzWolf VR V3

Thank you

**Comment by asierts** [comment]
I have been looking at other issues and they are giving more information, so I will do the same.

I have the XRSettings configured with "None" first and "Cardboard" second.
I have a VRnonVR.cs script attached to a GameObject in every scene (it checks every scene to be mono or stereo) with this code:
`using System;
using System.Collections;
using UnityEngine;
using UnityEngine.XR;

public class VRnonVR : MonoBehaviour {

    public bool isVR;

    private void Awake()
    {
        if (isVR)
        {
            StartCoroutine(SwitchToVR());
        } else
        {
            StartCoroutine(SwitchOutOfVr());
        }
    }

    public IEnumerator SwitchToVR()
    {
        string desiredDevice = "cardboard";
        
        if (String.Compare(XRSettings.loadedDeviceName, desiredDevice, true) != 0)
        {
            XRSettings.LoadDeviceByName(desiredDevice);
            
            yield return null;
        }
        
        XRSettings.enabled = true;
    }

    public IEnumerator SwitchOutOfVr()
    {
        XRSettings.LoadDeviceByName("");

        yield return null;
        ResetCameras();
    }

    void ResetCameras()
    {
        for (int i = 0; i < Camera.allCameras.Length; i++)
        {
            Camera cam = Camera.allCameras[i];
            if (cam.enabled && cam.stereoTargetEye != StereoTargetEyeMask.None)
            {
                cam.transform.localPosition = Vector3.zero;
                cam.transform.localRotation = Quaternion.identity;
            }
        }
    }`
This works fine (it has a blink when a VR scene is charged but it doen't matter by now).
I have a button in scene to change from estereo to mono inside a scene, I want the user to be able to change between modes. 
The code used in the button:
`        GVR.SetActive(false);
        // GVR is a GameObject with all the GVR Prefabs I am using 
        camara.AddComponent<GyroController>();
        // I add the Magic Window script to my main camera
        StartCoroutine(GetComponent<VRnonVR>().SwitchOutOfVr());
        // I call the previous coroutine of my VRnonVR script`
When I add the GyroController component in Unity Editor the camera looks to the floor and it doesn't work in the Android build.
This works fine, I turn off VR and it changes from estereo to mono but now I can't press any button. It seems to lose the hability to use Inputs.

**Comment by chaosemer** [comment]
Could you please create and share a minimal repro project so we could investigate this?

**Comment by asierts** [comment]
I have just uploaded it.
[https://github.com/asierts/VRNonVR_Min](https://github.com/asierts/VRNonVR_Min)

**Comment by asierts** [comment]
Any updates about my issue?
Thanks.

**Comment by rusmaxham** [comment]
When VR mode is disabled, the entire VR subsystem, including controller connection, is shut down.  We don't have any plans at this time to support piece-wise support of various parts of the Daydream VR system.
