### ISSUE TITLE
No funciona alv

### ISSUE THREAD

**Issue by Ricardope3** [googlevr/gvr-unity-sdk#980]
Summary:

No mms, no funciona cuando le doy correr, pero cuando lo corro en el unity corre al vergazo, pero cuando lo corro en mi computadora a una resolución del culo, no lo puede correr, se queda en negro ): 

P.D. tampoco puedo en mi cel 

Found using:
 * Google VR SDK version:
 * Unity version:
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by asierts** [comment]
Hola @Ricardope3, 
Aparte de que es una página en inglés y que probablemente sólo den soporte en inglés, si no das más información no se me ocurre que decirte para que te funcione.
En mi equipo empezamos por ver este vídeo para entender el funcionamiento [https://www.youtube.com/watch?v=EAaoEe9ksyE](url) y a partir de ahí empezamos a trastear por nuestra cuenta.

Un saludo

**Comment by chaosemer** [comment]
Would you be able to share a repro project and steps to reproduce your bug? It sounds like you are having initial setup issues.

**Comment by rusmaxham** [comment]
Please reopen if you're still experiencing this issue.
