### ISSUE TITLE
Crashes on import in Unity 2017.2

### ISSUE THREAD

**Issue by frankvHoof93** [googlevr/gvr-unity-sdk#981]
Summary:
Crashes Unity Editor on import of ddcontroller.png (Consistently)

Found using:
 * Google VR SDK version: 1.170
 * Unity version: 2017.2.13f1
 * Phone manufacturer, model, and O/S version: N/A
 * Viewer manufacturer & model: N/A

Steps to reproduce the issue:
1. Download the UnityPackage
2. Import the project
3. Whilst importing ddcontroller.png, Unity crashes

**Comment by rusmaxham** [comment]
Can you file a bug with Unity through the Unity editor?

**Comment by rusmaxham** [comment]
When you file a bug with Unity, could you share the case # with me?
