### ISSUE TITLE
Is there any way to recognize that controller is disconnected in game?

### ISSUE THREAD

**Issue by CrewDaniel** [googlevr/gvr-unity-sdk#982]
Summary: 
Hi, i have a question(or feature request), Is there any way to recognize that controller is disconnected in game? Surely there's a way to check battery level in home screen of Daydream, but sometimes controller is accidentally disconnected no matter how battery level remains. I want to know if there's any prefab or something that indicate controller connection status. If don't, I politely request the function.
Thank you!

Found using:
 * Google VR SDK version: v.1.170.0
 * Unity version: 2018.2.10f1
 * Phone manufacturer, model, and O/S version: Samsung Galaxy S8
 * Viewer manufacturer & model: Daydream View with Controller

**Comment by vinhui** [comment]
This is what we use to check if the controller is connected:
```csharp
        private GvrControllerInputDevice gvrDevice;

        public override bool available
        {
            get
            {
                return gvrDevice.State == GvrConnectionState.Connected;
            }
        }
```

**Comment by CrewDaniel** [comment]
Thanks for your help, @vinhui !
I should check the class.
I'm so appreciated.
