### ISSUE TITLE
GvrKeyboardManager

### ISSUE THREAD

**Issue by pjump3226** [googlevr/gvr-unity-sdk#983]
Summary:

When I added GvrKeyboardManager, keyboard image didn't not appear in the Unity.
Only the center position of the keyboard appears circular on the screen.
Is there a way to view and change keyboard image in Unity?
I could not check the keyboard intuitively, so I had trouble in testing it every time.

Found using:
 * Google VR SDK version: v.1.170.0
 * Unity version: 2018.2.2f1

![image](https://user-images.githubusercontent.com/37100494/48935940-ae8f9b00-ef4c-11e8-9c3f-5b75eb1563a6.png)

**Comment by vinhui** [comment]
When playing in editor, you wont see the keyboard but you can just type with your physical keyboard .

**Comment by rusmaxham** [comment]
This is correct.  There is no editor emulation of the GVR Keyboard.
