### ISSUE TITLE
Performance spikes observed in unity profiler after adding the google-VR module

### ISSUE THREAD

**Issue by spaul13** [googlevr/gvr-unity-sdk#984]
Summary: 
while a simple mobile unity game project (or a simple project with a cube and a camera) provides almost uniform CPU time with less variation while profiling it.

But adding the googleVR (tried latest and old versions) module to it, split into left and right eye (GVRviewer) and profile the VR mobile app provides a lot of spikes or variations which is due to VR.waitforGPU() and in turn gfx.processcommands(). **can anyone please tell me what's the reason behind those performance spikes while adding GVR module?**

I have tried multiple optimizations (e.g. static batching, disabling vsync, optimizing mesh data) but nothing seems to be useful. **Is there any possible way to get rid of this issue?**

Found using:
 * Google VR SDK version: tried multiple VR SDK versions (1.100.1, 1.70.0, 1.40.0, 1.130.0, 1.180.1)
 * Unity version: used multiple unity versions also (2018.2.17f1, 2018.1.0b4, 5.6.4p4)
 * Phone manufacturer, model, and O/S version: Google Pixel 2, Android 8.1.0
 * Viewer manufacturer & model: Google

Steps to reproduce the issue:
 1. Just make a simple VR scene with a camera and any 3D object like a cube in front of the camera
 2. Add GVREditoremulator and VR settings for player settings 
 3. Build and run it on android and profile it using the unity profiler

**Comment by vinhui** [comment]
Did you have vr enabled when you didn't have the GVR package added when profiling?

**Comment by spaul13** [comment]
@vinhui, No. I didn't enable vr from player settings before adding gvr package(it's a normal Android scene then)

**Comment by vinhui** [comment]
Then that's where the spikes are coming from. VR is quite demanding on the device, especially on the GPU.

**Comment by spaul13** [comment]
@vinhui, But if the scene is not changing, same drawcalls, why GPU load will vary only for vr?

**Comment by rusmaxham** [comment]
In VR mode, your scene will more or less be rendered twice, once for each eye.  When that rendering is complete, the rendered eye buffers are handed to the GVR compositor where it does yet another render pass to the screen performing the lens anti-distortion.  Also, what frame rate was your scene previously running at in non-VR mode?  It's possible your scene had been running at 30fps in non-VR mode.  VR mode tries to run at 60fps always.

**Comment by rusmaxham** [comment]
If you have further questions on this issue, please ask and reopen.
