### ISSUE TITLE
HelloVR Demo Scene "Event Trigger - Pointer Click" not working

### ISSUE THREAD

**Issue by johnpaullima** [googlevr/gvr-unity-sdk#985]
Summary: I'm a begginer in Unity and VR development. 
3 Months ago I downloaded google VR package and it was ok (I don't remember the version). HelloVR Demo scene worked as it should. When entering object, it changed its color, when leaving it also changed and when I clicked on game preview, the subroutine TeleportRandomly worked, by moving the object to another place.
The problem is that I came back to this project yesterday and the new version of GoogleVR Package seems not working correctly. in HelloVR scene, Pointer Enter and Pointer Exit is still okay (in any "treasure"object), but Pointer Click is no longer functioning. I tried to change that (to Pointer UP or Pointer Down) but without success. Can someone help me?

Found using:
 * Google VR SDK version: 1.180.0
 * Unity version: 2018.2.
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1. I downloaded google VR Package 1.180.0, then configured Android Support and Cardboard.
 2. Then I opened HelloVR demo scene and runned.
 3. Pointer enter and Pointer Exit are working
**4. Pointer Click is not working**
![image](https://user-images.githubusercontent.com/45721283/49690699-6a8bc100-fb1c-11e8-9481-fc0439a6560a.png)

Workarounds:

Additional comments:

**Comment by T3rO** [comment]
Had the same issue.
Go to GvrBasePointer Script and remove the ! in front of UNITY_EDITOR in line 196.

**Comment by johnpaullima** [comment]
> Had the same issue.
> Go to GvrBasePointer Script and remove the ! in front of UNITY_EDITOR in line 196.

Thanks a lot! It worked!

**Comment by rusmaxham** [comment]
Reopening until this issue is resolved in a GoogleVR SDK release.

**Comment by FishfaceGames** [comment]
> > Had the same issue.
> > Go to GvrBasePointer Script and remove the ! in front of UNITY_EDITOR in line 196.
Did that and it works when I click with my mouse. But tapping the phone or using the cardboard button still doesn't work. Using Unity Remote 5 to preview the game on my android.

**Comment by AmigaAbattoir** [comment]
> > > Had the same issue.
> > > Go to GvrBasePointer Script and remove the ! in front of UNITY_EDITOR in line 196.
> 
> Did that and it works when I click with my mouse. But tapping the phone or using the cardboard button still doesn't work. Using Unity Remote 5 to preview the game on my android.

@T3rO mentions in the "better yet" that you should comment out the whole #if !UNITY_EDITOR and the following #endif, this way it will work on the device. 

If you leave the preprocessor as`#if UNITY_EDITOR` then it means that block of code only happens when running from the Unity editor.

**Comment by maxdevclever** [comment]
This is still an issue (face Palm), to update anyone else struggling with this the new lines you need to comment out are 227 and 239.

**Comment by whizzkid** [comment]
When will this "upcoming release" actually be released?  @rusmaxham

**Comment by KDragos** [comment]
This is still an issue with version 1.190.1. 
Thanks everyone for figuring out the fix.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).

**Comment by TheAbzo** [comment]
> This is still an issue (face Palm), to update anyone else struggling with this the new lines you need to comment out are 227 and 239.

works perfectly :]  Thanks!
