### ISSUE TITLE
Unable to see/use 6DoF Controllers in or outside of app.

### ISSUE THREAD

**Issue by sebastianherscher** [googlevr/gvr-unity-sdk#987]
Summary:

Using the 6DoF controller development kit, I am unable to see or use the controllers in the Daydream menu or inside the provided Unity demo scene. I've followed all instructions listed on g.co/6dofsetup and have successfully paired the controllers. I still see the 3DoF controller in all apps and in the outside menu. 

Found using:
 * Google VR SDK version: v1.180.0
 * Unity version: 2018.2.14f1
 * Viewer manufacturer & model: Google Lenovo Mirage Solo + 6DoF Development Controllers

Steps to reproduce the issue:
 1. Build Hello6DoFControllers app to Mirage Solo.
 2. Connect 6DoF faceplate and pair 6DoF controllers.
 1. Launch Hello6DoFControllers app.

Workarounds: None so far.

Additional comments: I realize this may not be the most correct avenue for feedback for this (may be a controller/OS issue instead of the Unity SDK), but the FAQ and Troubleshooting sections of the 6DoF controllers is still pretty bare. Thank you for understanding!

**Comment by jadware** [comment]
same issue

note that the 3d models for the 6dof controllers are present in the Beta/Models folder but not referenced anywhere in the sample scene or code

**Comment by sousv** [comment]
I'm also experiencing this issue.   I tried power cycling, re-pairing both controllers, edited the Android Manifest file a few times.  Nothing I do seems to have any affect on the headset detecting the 6dof controllers.

**Comment by jadware** [comment]
@sousv @sebastianherscher are you able to get the 6dof controllers working in anything, even non-unity?  I cannot get them to appear anywhere.

**Comment by sousv** [comment]
@jadware I compiled NDK example successfully just now and it still doesn't work.  I'm gonna have to put this on hold.   I think there's a critical step that's missing like paring the 6-dof controllers to the headset.   Hopefully someone updates us if they get it to work successfully.

**Comment by sniejadlik** [comment]
I am seeing the same issue, have followed the guide exactly and even reinstalled the google vr for unity package completely.  No luck seeing either of the 6dof controller, just the standard daydream clicker.

**Comment by sniejadlik** [comment]
> @jadware I compiled NDK example successfully just now and it still doesn't work. I'm gonna have to put this on hold. I think there's a critical step that's missing like paring the 6-dof controllers to the headset. Hopefully someone updates us if they get it to work successfully.

The controllers are showing as paired.  They get paired to the faceplate not the headset.  I was even able to pair "google shaker" to the device which I am assuming was the code name for these but it didn't do anything. There has to be some device update that is needed or something.

**Comment by sousv** [comment]
I contacted google about this issue with a bug report yesterday.  They told me they found the issue and are working on a fix.  They also told me they'll update me as soon as a fix is rolled out.   I was able to reach them at daydream-6dof-controller-devkit-support@google.com

**Comment by sniejadlik** [comment]
@sousv Thanks!  Hopefully they roll it out soon as I am assuming this is affecting everyone that has the devices.

**Comment by NidhiRathi1** [comment]
Thank you for bringing this issue to our attention. We are working on a fix now and should have a status update and a new release next week.

**Comment by rusmaxham** [comment]
This is a VR Services level issue that will be resolved very soon with an auto-pushed update to VR Services.  We will comment and close this issue when the update is pushed.

**Comment by CubicVR** [comment]
Thank you! This fixed our issue. It works now.


*Haldun Kececigil*

*Founder*

*Cubic VR*404.939.5323
haldun@cubic.cool
www.cubic.cool <http://cubic.cool/>
linkedin <http://www.linkedin.com/in/haldun>

<http://cubic.cool>

**Comment by CubicVR** [comment]
It works! Thank you all at Google VR.

**Comment by jadware** [comment]
for me as well, works great!

**Comment by sniejadlik** [comment]
Worked flawlessly, thank you!
