### ISSUE TITLE
Missing teleportation.

### ISSUE THREAD

**Issue by kiborg** [googlevr/gvr-unity-sdk#989]
Summary:
There is doc how to do teleportation.
https://developers.google.com/vr/elements/teleportation
 And there it says to use Demos/Teleport/Prefab/TeleportController.prefab
I can't find this prefab. How to get it? Is it still right way to do it? or it changed?

I can see this repo: 
https://github.com/googlevr/daydream-elements/issues

But it's archived. That's why ask it here. Can't ask there.  So is there better way to do it? 

Found using:
 * Google VR SDK version: GVR SDK for Unity v1.180.0
 * Unity version:
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by rusmaxham** [comment]
Teleportation now only lives in [Daydream Elements](https://developers.google.com/vr/elements/overview).  That will still work with the latest GVR SDK for Unity.

**Comment by tedruxpin** [comment]
That specific prefab can be found in a slightly different location:
https://github.com/googlevr/daydream-elements/tree/master/Assets/DaydreamElements/Elements/Teleport/Prefabs
