### ISSUE TITLE
Question about the usb host mode with faceplate plug

### ISSUE THREAD

**Issue by sniejadlik** [googlevr/gvr-unity-sdk#991]
Summary:
I am trying to figure out the best way to utilize the Instant Preview mode in Unity while also using the new controllers.  The current unplug, plug in, build, unplug, plug in, sync, then put on head is a pain for checking if something is working.  

I was wondering if it's possible to use a usb splitter jack to power the faceplate as well as keep the device plugged into the computer for charging and deployment builds. Something like this that is small and lets the front plate be plugged in.
https://www.ebay.com/i/153164545052?chn=ps&var=453017960630

Additional comments:
I have tried to figure out the instant preview over wifi but the Mirage Solo does not seem to have the interface to allow the wifi connection.

**Comment by rusmaxham** [comment]
You can configure adb to work over wifi, allowing you to build, install, run, and logcat without a USB cable plugged in between your computer and headset.  Instant Preview also works over WiFi with this configuration.  [See instructions here.](https://developers.google.com/vr/develop/experimental/6dof-debugging)
