### ISSUE TITLE
Assets/GoogleVR/Scripts/Controller/GvrController.cs

### ISSUE THREAD

**Issue by kiborg** [googlevr/gvr-unity-sdk#992]
Summary: What happened to this file. it's not in new gvr-unity-sdk ?

Found using:
 * Google VR SDK version:
 * Unity version:
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by rusmaxham** [comment]
This file was deprecated and replaced by [GvrControllerInput.cs](https://github.com/googlevr/gvr-unity-sdk/blob/master/Assets/GoogleVR/Scripts/Controller/GvrControllerInput.cs).
