### ISSUE TITLE
How can find gvr unity sdk version in files? 

### ISSUE THREAD

**Issue by kiborg** [googlevr/gvr-unity-sdk#993]
Summary:

Found using:
 * Google VR SDK version:
 * Unity version:
 * Phone manufacturer, model, and O/S version:
 * Viewer manufacturer & model:

Steps to reproduce the issue:
 1.
 1.
 1.

Workarounds:

Additional comments:

**Comment by shiena** [comment]
@kiborg you can find gvr unity sdk version in [reference](https://developers.google.com/vr/reference/unity/class/GvrUnitySdkVersion) and [GvrUnitySdkVersion.cs](
https://github.com/googlevr/gvr-unity-sdk/blob/master/Assets/GoogleVR/Scripts/GvrUnitySdkVersion.cs)

**Comment by rusmaxham** [comment]
You can get the version string in C# like so:

```C#
string versionString = GvrUnitySdkVersion.GVR_SDK_VERSION;
```
