### ISSUE TITLE
EntryPointNotFoundException: GetGvrEvent

### ISSUE THREAD

**Issue by shiena** [googlevr/gvr-unity-sdk#998]
### SPECIFIC ISSUE ENCOUNTERED

GvrInstantPreviewMain prefab outputs errors to the console.

```
EntryPointNotFoundException: GetGvrEvent
Gvr.Internal.InstantPreview.UpdateEvents () (at Assets/GoogleVR/Scripts/InstantPreview/Internal/InstantPreview.cs:527)
Gvr.Internal.InstantPreview.Update () (at Assets/GoogleVR/Scripts/InstantPreview/Internal/InstantPreview.cs:558)
```

### HARDWARE/SOFTWARE VERSIONS
- Unity: 2018.3.1f
- Google VR SDK for Unity: v1.190.0
- Device manufacturer, model, and O/S: Windows10

### STEPS TO REPRODUCE THE ISSUE
 1. Create new project
 1. Import GoogleVRForUnity_1.190.0.unitypackage
 1. Open Assets/GoogleVR/Demos/Scenes/HelloVR.unity
 1. Play on Editor

![image](https://user-images.githubusercontent.com/1295639/51106658-c0e0d380-182f-11e9-8b17-628680ddd940.png)

**Comment by ytddrocco** [comment]
Hi, thanks for reporting!  We're working on a fix for this ASAP.  We will keep you informed on progress.

**Comment by ddrocco** [comment]
Hi, thanks for reporting!  We're working on a fix ASAP.  We'll keep you posted!

**Comment by BalsamAlkouz** [comment]
I have the same issue

**Comment by rusmaxham** [comment]
Until we get a fix out, you can work around it by removing or disabling the GvrInstantPreviewMain game object.

**Comment by rusmaxham** [comment]
This is now fixed in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).

**Comment by samuelagyemang2012** [comment]
I don't think it has been fixed. I have this same issue

EntryPointNotFoundException: GetGvrEvent
Gvr.Internal.InstantPreview.UpdateEvents () (at Assets/GoogleVR/Scripts/InstantPreview/Internal/InstantPreview.cs:527)
Gvr.Internal.InstantPreview.Update () (at Assets/GoogleVR/Scripts/InstantPreview/Internal/InstantPreview.cs:558)

**Comment by ddrocco** [comment]
What operating system are you using?  I'm unable to replicate your issue on MacOS on the latest release.

**Comment by samuelagyemang2012** [comment]
Hello,
I'm using the latest version of Unity on windows. The dragged the
GvrInstantPreview prefab into scene and clicked play.

Regards
