### ISSUE TITLE
[Question] How can I add a custom animatable avatar for the Daydream in Unity?

### ISSUE THREAD

**Issue by cyrilzakka** [googlevr/gvr-unity-sdk#999]
I'd like to replace the Daydream controller in a VR environment with a hand/wrist/elbow combination whereby moving the controller moves the hand and clicking a button mimics a 'grasping' motion enabling the user to pick up items.

Does the GVR SDK support it? What are some resources for doing this for the Daydream specifically?

So far I've created my hand model, rigged it and added inverse-kinematics to it. How do I proceed?

Bonus: Since Daydream/Cardboard currently only supports one controller (even though the beta API supports 2), is it possible to switch from a left-hand to a right-hand model mid-game?

**Comment by 2348** [comment]
But I don't know

**Comment by rusmaxham** [comment]
We have a sample project called [Daydream Elements](https://developers.google.com/vr/elements/overview) that has a sample scene that demonstrates the use of different [arm models](https://developers.google.com/vr/elements/arm-model).  This scene also demonstrates visualizing more of the arm like I believe you are asking about.

It is possible to switch handedness in the System Dashboard.  [This page](https://support.google.com/daydream/answer/7634679?hl=en) describes how to change a bunch of system settings.  Handedness is at the bottom.

When your app is brought to the foreground again. `GvrSettings.Handedness` will update accordingly.
